Repository wildfly/wildfly, pull requests merged in 2018-04, with the labels that each got.

#10788 WFLY-9724 Undertow does not allow UTF-8 characters in URLs
  testsuite/integration/web/src/test/java/org/jboss/as/test/integration/web/listener/EchoServlet.java
  testsuite/integration/web/src/test/java/org/jboss/as/test/integration/web/listener/UnescapedURITestCase.java
  undertow/src/main/java/org/wildfly/extension/undertow/ListenerResourceDefinition.java
  undertow/src/main/java/org/wildfly/extension/undertow/UndertowSubsystemParser_6_0.java
  undertow/src/main/java/org/wildfly/extension/undertow/UndertowTransformers.java
  undertow/src/main/resources/org/wildfly/extension/undertow/LocalDescriptions.properties
  undertow/src/main/resources/schema/wildfly-undertow_6_0.xsd
  undertow/src/test/java/org/wildfly/extension/undertow/UndertowTransformersTestCase.java
  undertow/src/test/resources/org/wildfly/extension/undertow/undertow-6.0.xml
  undertow/src/test/resources/org/wildfly/extension/undertow/undertow-reject.xml
Labels: Feature

#11051 [WFLY-10080] - [GSS](7.1.z) Need to handle a http post method on pic…
  testsuite/integration/picketlink/src/test/java/org/wildfly/test/integration/security/picketlink/federation/SAMLPostKeepFormDataTestCase.java
  testsuite/integration/picketlink/src/test/resources/org/wildfly/test/integration/security/picketlink/federation/SAMLPostKeepFormData/idp/idp-metadata.xml
  testsuite/integration/picketlink/src/test/resources/org/wildfly/test/integration/security/picketlink/federation/SAMLPostKeepFormData/idp/login.jsp
  testsuite/integration/picketlink/src/test/resources/org/wildfly/test/integration/security/picketlink/federation/SAMLPostKeepFormData/idp/test.xml
  testsuite/integration/picketlink/src/test/resources/org/wildfly/test/integration/security/picketlink/federation/SAMLPostKeepFormData/idp/web.xml
  testsuite/integration/picketlink/src/test/resources/org/wildfly/test/integration/security/picketlink/federation/SAMLPostKeepFormData/sp/index.jsp
  testsuite/integration/picketlink/src/test/resources/org/wildfly/test/integration/security/picketlink/federation/SAMLPostKeepFormData/sp/post-test-main.jsp
  testsuite/integration/picketlink/src/test/resources/org/wildfly/test/integration/security/picketlink/federation/SAMLPostKeepFormData/sp/sp-metadata.xml
  testsuite/integration/picketlink/src/test/resources/org/wildfly/test/integration/security/picketlink/federation/SAMLPostKeepFormData/sp/web.xml
Labels: security

#11058 WFLY-10084 Add support for the proxy protocol
  mod_cluster/undertow/src/test/java/org/wildfly/mod_cluster/undertow/UndertowConnectorTestCase.java
  mod_cluster/undertow/src/test/java/org/wildfly/mod_cluster/undertow/UndertowEngineTestCase.java
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/management/api/web/ListenerTestCase.java
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/management/api/web/RemoteIpServlet.java
  testsuite/shared/src/main/java/org/jboss/as/test/http/util/TestHttpClientUtils.java
  testsuite/shared/src/main/java/org/jboss/as/test/integration/management/Listener.java
  undertow/src/main/java/org/wildfly/extension/undertow/AjpListenerService.java
  undertow/src/main/java/org/wildfly/extension/undertow/Constants.java
  undertow/src/main/java/org/wildfly/extension/undertow/HttpListenerAdd.java
  undertow/src/main/java/org/wildfly/extension/undertow/HttpListenerResourceDefinition.java
  undertow/src/main/java/org/wildfly/extension/undertow/HttpListenerService.java
  undertow/src/main/java/org/wildfly/extension/undertow/HttpsListenerAdd.java
  undertow/src/main/java/org/wildfly/extension/undertow/HttpsListenerResourceDefinition.java
  undertow/src/main/java/org/wildfly/extension/undertow/HttpsListenerService.java
  undertow/src/main/java/org/wildfly/extension/undertow/ListenerService.java
  undertow/src/main/java/org/wildfly/extension/undertow/UndertowSubsystemParser_6_0.java
  undertow/src/main/java/org/wildfly/extension/undertow/UndertowTransformers.java
  undertow/src/main/resources/org/wildfly/extension/undertow/LocalDescriptions.properties
  undertow/src/main/resources/schema/wildfly-undertow_6_0.xsd
  undertow/src/test/java/org/wildfly/extension/undertow/UndertowTransformersTestCase.java
  undertow/src/test/resources/org/wildfly/extension/undertow/undertow-6.0.xml
Labels: Feature

#11141 Add comments to make it easier for prod to find hardcoded versions fo…
  component-matrix/pom.xml
  feature-pack/src/main/resources/modules/system/layers/base/com/sun/jsf-impl/main/module.xml
  feature-pack/src/main/resources/modules/system/layers/base/javax/mail/api/main/module.xml
  servlet-feature-pack/src/main/resources/modules/system/layers/base/javax/enterprise/api/main/module.xml
  servlet-feature-pack/src/main/resources/modules/system/layers/base/javax/validation/api/main/module.xml
  servlet-feature-pack/src/main/resources/modules/system/layers/base/org/glassfish/javax/json/main/module.xml
Labels: fixme

#11143 Add documentation for logging formatters.
  docs/src/main/asciidoc/_admin-guide/subsystem-configuration/Logging.adoc
  docs/src/main/asciidoc/_admin-guide/subsystem-configuration/Logging_Formatters.adoc
Labels: 13.x

#11116 WFLY-10222 Don't propagate exception if reading the resource fails
  feature-pack/src/main/resources/modules/system/layers/base/org/jboss/as/jaxrs/main/module.xml
  jaxrs/src/main/java/org/jboss/as/jaxrs/DeploymentRestResourcesDefintion.java
  jaxrs/src/main/java/org/jboss/as/jaxrs/logging/JaxrsLogger.java
Labels: ready-for-merge

#11151 WFLY-10291 Integration test for read-feature-description op
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/management/api/ReadFeatureDescriptionTestCase.java
Labels: ready-for-merge
