Repository wildfly/wildfly, pull requests merged in 2018-07, with the labels that each got.

#11387 WFLY-10652 Fix singleton MDBs following singleton service API changes.
  ejb3/src/main/java/org/jboss/as/ejb3/clustering/SingletonBarrierService.java
  ejb3/src/main/java/org/jboss/as/ejb3/deployment/processors/MdbDeliveryDependenciesProcessor.java
  ejb3/src/main/java/org/jboss/as/ejb3/subsystem/EJB3SubsystemAdd.java
Labels: ready-for-merge

#11391 WFLY-10663 Upgrade mod_cluster to 1.3.10.Final
  pom.xml
Labels: ready-for-merge

#11396 [WFLY-10667] Upgrade WildFly Core 6.0.0.Alpha3
  pom.xml
Labels: ready-for-merge

#11416 [WFLY-10288] Remove JSF 2.2 support and move to JSF 2.3 support for Java EE 8
  feature-pack/pom.xml
  feature-pack/src/license/full-feature-pack-licenses.xml
  feature-pack/src/main/resources/modules/system/layers/base/com/sun/jsf-impl/main/module.xml
  feature-pack/src/main/resources/modules/system/layers/base/javax/faces/api/main/module.xml
  galleon-pack/pom.xml
  jsf/subsystem/pom.xml
  pom.xml
  spec-api/pom.xml
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/jsf/jsf23/ConfirmBean.java
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/jsf/jsf23/ConfirmRegistrationBehavior.java
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/jsf/jsf23/DummyBean.java
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/jsf/jsf23/JSF23SanityTestCase.java
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/jsf/jsf23/beans.xml
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/jsf/jsf23/confirmation.xhtml
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/jsf/jsf23/faces-config.xml
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/jsf/jsf23/index.xhtml
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/jsf/jsf23/register.taglib.xml
Labels: EE8

#11415 [WFLY-10288] Remove jboss-jaxb-api_2.2_spec support and move to jboss…
  feature-pack/pom.xml
  feature-pack/src/license/full-feature-pack-licenses.xml
  feature-pack/src/main/resources/modules/system/layers/base/javax/xml/bind/api/main/module.xml
  galleon-pack/pom.xml
  pom.xml
Labels: EE8

#11414 [WFLY-10288] Remove jboss-annotations-api_1.2_spec support and move t…
  pom.xml
  servlet-feature-pack/pom.xml
  servlet-feature-pack/src/license/servlet-feature-pack-licenses.xml
  servlet-feature-pack/src/main/resources/modules/system/layers/base/javax/annotation/api/main/module.xml
  servlet-galleon-pack/pom.xml
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/ee/datasourcedefinition/DataSourceDefinitionTestCase.java
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/ee/datasourcedefinition/RepeatableDataSourceDefinitionTestCase.java
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/ee/datasourcedefinition/RepeatedAnnotationDataSourceBean.java
  testsuite/integration/ee8-temp/src/test/java/org/wildfly/test/integration/ee8/commonannotations13/datasourcedefinition/EmbeddedDataSource.java
Labels: EE8

#11411 [WFLY-10288] Remove javax.mail 1.5.6.Final and move to 1.6.1.Final for Java EE 8
  feature-pack/src/main/resources/content/docs/licenses/full-feature-pack-licenses-addendum.html
  feature-pack/src/main/resources/modules/system/layers/base/javax/mail/api/main/module.xml
  pom.xml
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/mail/annotation/MailServlet.java
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/mail/annotation/RepeatableMailSessionDefinitionTestCase.java
  testsuite/integration/ee8-temp/src/test/java/org/wildfly/test/integration/ee8/mail/MailServlet.java
Labels: EE8

#11340 /WFLY-10519 remove Hibernate JPA 2.1 + Hibernate ORM 5.1.x + Hibernate Search 5.5.8
  feature-pack/pom.xml
  feature-pack/src/main/resources/content/docs/licenses/full-feature-pack-licenses-addendum.html
  feature-pack/src/main/resources/modules/system/layers/base/javax/persistence/api/main/module.xml
  feature-pack/src/main/resources/modules/system/layers/base/org/apache/lucene/5.5/module.xml
  feature-pack/src/main/resources/modules/system/layers/base/org/apache/lucene/main/module.xml
  feature-pack/src/main/resources/modules/system/layers/base/org/hibernate/5.0/module.xml
  feature-pack/src/main/resources/modules/system/layers/base/org/hibernate/5.3/module.xml
  feature-pack/src/main/resources/modules/system/layers/base/org/hibernate/jipijapa-hibernate5-3/main/module.xml
  feature-pack/src/main/resources/modules/system/layers/base/org/hibernate/jipijapa-hibernate5/main/module.xml
  feature-pack/src/main/resources/modules/system/layers/base/org/hibernate/main/module.xml
  feature-pack/src/main/resources/modules/system/layers/base/org/hibernate/search/engine/5.10/module.xml
  feature-pack/src/main/resources/modules/system/layers/base/org/hibernate/search/engine/main/module.xml
  feature-pack/src/main/resources/modules/system/layers/base/org/hibernate/search/orm/5.10/module.xml
  feature-pack/src/main/resources/modules/system/layers/base/org/hibernate/search/orm/main/module.xml
  feature-pack/src/main/resources/modules/system/layers/base/org/hibernate/search/serialization-avro/5.10/module.xml
  feature-pack/src/main/resources/modules/system/layers/base/org/infinispan/hibernate-cache/main/module.xml
  galleon-pack/pom.xml
  jpa/hibernate5_3/pom.xml
  jpa/subsystem/src/main/java/org/jboss/as/jpa/config/Configuration.java
  jpa/subsystem/src/main/java/org/jboss/as/jpa/processor/HibernateSearchProcessor.java
  jpa/subsystem/src/main/java/org/jboss/as/jpa/puparser/PersistenceUnitXmlParser.java
  pom.xml
  testsuite/compat/src/test/java/org/jboss/as/test/compat/jpa/hibernate/HibernateJarsInDeploymentTestCase.java
  testsuite/compat/src/test/scripts/build-jars.xml
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/hibernate/SFSBHibernateSessionFactory.java
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/hibernate/naturalid/HibernateNativeAPINaturalIdTestCase.java
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/hibernate/search/Book.java
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/hibernate/search/HibernateSearchJPATestCase.java
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/hibernate/search/SearchBean.java
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/hibernate/secondlevelcache/SFSB.java
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/jpa/hibernate/sessionfactorytest/persistence.xml
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/jpa/jarfile/persistence.xml
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/jpa/resultstream/ResultStreamTest.java
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/jpa/resultstream/ResultStreamTestCase.java
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/jpa/resultstream/Ticket.java
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/jpa/resultstream/persistence.xml
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/jpa/secondlevelcache/JPA2LCTestCase.java
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/jpa/secondlevelcache/SFSB2LC.java
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/jpa/secondlevelcache/persistence.xml
  testsuite/integration/ee8-temp/src/test/java/org/wildfly/test/integration/ee8/hibernatesearch/Book.java
  testsuite/integration/ee8-temp/src/test/java/org/wildfly/test/integration/ee8/hibernatesearch/HibernateSearchJPATestCase.java
  testsuite/integration/ee8-temp/src/test/java/org/wildfly/test/integration/ee8/hibernatesearch/SearchBean.java
  testsuite/integration/ee8-temp/src/test/java/org/wildfly/test/integration/ee8/hibernatesearch/persistence.xml
Labels: EE8, Feature, missing-reqs

#11399 WFLY-10668 Upgrade Narayana to 5.9.0.Final
  pom.xml
Labels: ready-for-merge

#11450 [WFLY-10655] SEVERE error on deploy of ear: "Unable to obtain CDI 1.1…
  jsf/subsystem/src/main/java/org/jboss/as/jsf/deployment/JSFDependencyProcessor.java
Labels: ready-for-merge

#11388 WFLY-10653 Improve EL performance
  undertow/src/main/java/org/wildfly/extension/undertow/ImportedClassELResolver.java
Labels: fixme

#11321 Community doc for WFCORE-3743 and WFCORE-3568, CLI scrolling/searching
  docs/src/main/asciidoc/_admin-guide/Command_Line_Interface.adoc
Labels: Feature, core-upgrade-needed

#11448 [WFLY-10678] Use upper case for table names when database is DB2
  feature-pack/src/main/resources/modules/system/layers/base/org/wildfly/extension/messaging-activemq/main/database/journal-sql.properties
  messaging-activemq/src/main/java/org/wildfly/extension/messaging/activemq/PropertySQLProviderFactory.java
Labels: ready-for-merge

#11459 WFLY-10738 Upgrade Hibernate ORM to 5.3.3.Final and Hibernate Search to 5.10.3.Final
  pom.xml
Labels: ready-for-merge

#11470 Singleton deployment subsystem code cleanup.
  clustering/singleton/extension/src/main/java/org/wildfly/extension/clustering/singleton/SingletonResourceDefinition.java
  clustering/singleton/extension/src/main/java/org/wildfly/extension/clustering/singleton/deployment/SingletonDeploymentSchema.java
Labels: ready-for-merge

#11440 WFLY-10009 Introduce a maximum-timeout management model attribute
  testsuite/integration/basic/pom.xml
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/transaction/MaximumTimeoutTestCase.java
  testsuite/shared/src/main/java/org/jboss/as/test/integration/transactions/TestXAResource.java
  transactions/src/main/java/org/jboss/as/txn/logging/TransactionLogger.java
  transactions/src/main/java/org/jboss/as/txn/subsystem/Attribute.java
  transactions/src/main/java/org/jboss/as/txn/subsystem/CommonAttributes.java
  transactions/src/main/java/org/jboss/as/txn/subsystem/Namespace.java
  transactions/src/main/java/org/jboss/as/txn/subsystem/TransactionExtension.java
  transactions/src/main/java/org/jboss/as/txn/subsystem/TransactionSubsystem40Parser.java
  transactions/src/main/java/org/jboss/as/txn/subsystem/TransactionSubsystem50Parser.java
  transactions/src/main/java/org/jboss/as/txn/subsystem/TransactionSubsystemAdd.java
  transactions/src/main/java/org/jboss/as/txn/subsystem/TransactionSubsystemRootResourceDefinition.java
  transactions/src/main/java/org/jboss/as/txn/subsystem/TransactionSubsystemXMLPersister.java
  transactions/src/main/java/org/jboss/as/txn/subsystem/TransactionTransformers.java
  transactions/src/main/resources/org/jboss/as/txn/subsystem/LocalDescriptions.properties
  transactions/src/main/resources/schema/wildfly-txn_5_0.xsd
  transactions/src/main/resources/subsystem-templates/transactions.xml
  transactions/src/test/java/org/jboss/as/txn/subsystem/TransactionSubsystemTestCase.java
  transactions/src/test/resources/org/jboss/as/txn/subsystem/full-1.2.xml
  transactions/src/test/resources/org/jboss/as/txn/subsystem/full-1.3.xml
  transactions/src/test/resources/org/jboss/as/txn/subsystem/full-1.5.0.xml
  transactions/src/test/resources/org/jboss/as/txn/subsystem/full-3.0.0.xml
  transactions/src/test/resources/org/jboss/as/txn/subsystem/full-4.0.0.xml
  transactions/src/test/resources/org/jboss/as/txn/subsystem/full-expressions-transform.xml
  transactions/src/test/resources/org/jboss/as/txn/subsystem/full-expressions.xml
  transactions/src/test/resources/org/jboss/as/txn/subsystem/subsystem.xml
Labels: ready-for-merge
