Repository wildfly/wildfly, pull requests merged in 2018-09, with the labels that each got.

#11655 WFLY-10956 Upgrade Infinispan to 9.3.3.Final
  pom.xml
Labels: Blocker, Needs JBEAP

#11607 [WFLY-10944] Added script for mariadb
  feature-pack/src/main/resources/modules/system/layers/base/org/jboss/as/ejb3/main/timers/timer-sql.properties
Labels: 15.x

#11601 [WFLY-10939] taglib-location pointing to jar fails to deploy
  undertow/src/main/java/org/wildfly/extension/undertow/deployment/TldParsingDeploymentProcessor.java
Labels: 15.x

#11652 [WFLY-10986] Clone the connection definitions in a synchronized block
  connector/src/main/java/org/jboss/as/connector/metadata/api/resourceadapter/ActivationSecurityUtil.java
Labels: Blocker, Needs JBEAP

#11650 [WFLY-10988] Upgrade parent pom to 29
  pom.xml
Labels: ready-for-merge

#11629 [WFLY-10950] JDK-11 - basic LDAPS tests - alternative name in certificate
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/security/loginmodules/GenerateLDAPSJKSStore.java
Labels: Blocker, Needs JBEAP

#11613 [WFLY-10945] JDK-11 - ws test failures - alternative name, TLS_ECDHE_…
  testsuite/integration/ws/src/test/java/org/jboss/as/test/integration/ws/wsse/GenerateWSKeyStores.java
  testsuite/integration/ws/src/test/java/org/jboss/as/test/integration/ws/wsse/trust/WSBearerElytronSecurityPropagationTestCase.java
  testsuite/integration/ws/src/test/java/org/jboss/as/test/integration/ws/wsse/trust/WSBearerSecurityPropagationTestCase.java
  testsuite/integration/ws/src/test/java/org/jboss/as/test/integration/ws/wsse/trust/WSTrustTestCase.java
Labels: Blocker, Needs JBEAP

#11680 [WFLY-11052]: Set journal-pool-files default value to 10
  galleon-pack/src/main/resources/feature_groups/messaging-activemq-ha.xml
  galleon-pack/src/main/resources/feature_groups/messaging-activemq.xml
  messaging-activemq/src/main/java/org/wildfly/extension/messaging/activemq/MessagingTransformerRegistration.java
  messaging-activemq/src/main/java/org/wildfly/extension/messaging/activemq/ServerDefinition.java
  messaging-activemq/src/main/resources/subsystem-templates/messaging-activemq-colocated.xml
  messaging-activemq/src/main/resources/subsystem-templates/messaging-activemq.xml
  testsuite/domain/src/test/java/org/jboss/as/test/integration/domain/BuildConfigurationTestBase.java
Labels: ready-for-merge

#11697 [WFLY-11083] doc: match-user instead of match-userinfo in elytron client
  docs/src/main/asciidoc/_elytron/Client_Authentication_with_Elytron_Client.adoc
Labels: Feature-Docs

#11576 [WFLY-10438] Create a domain testsuite test for a missing host-exclude
  testsuite/domain/src/test/java/org/jboss/as/test/integration/domain/HostExcludesTestCase.java
Labels: fixme

#11672 [WFLY-9106]: Hard-code default values in messaging-activemq subsystem.
  messaging-activemq/src/main/java/org/wildfly/extension/messaging/activemq/ActiveMQServerService.java
  messaging-activemq/src/main/java/org/wildfly/extension/messaging/activemq/BridgeDefinition.java
  messaging-activemq/src/main/java/org/wildfly/extension/messaging/activemq/BroadcastGroupDefinition.java
  messaging-activemq/src/main/java/org/wildfly/extension/messaging/activemq/ClusterConnectionDefinition.java
  messaging-activemq/src/main/java/org/wildfly/extension/messaging/activemq/CommonAttributes.java
  messaging-activemq/src/main/java/org/wildfly/extension/messaging/activemq/DiscoveryGroupDefinition.java
  messaging-activemq/src/main/java/org/wildfly/extension/messaging/activemq/DivertDefinition.java
  messaging-activemq/src/main/java/org/wildfly/extension/messaging/activemq/GroupingHandlerDefinition.java
  messaging-activemq/src/main/java/org/wildfly/extension/messaging/activemq/MessagingExtension.java
  messaging-activemq/src/main/java/org/wildfly/extension/messaging/activemq/ServerAdd.java
  messaging-activemq/src/main/java/org/wildfly/extension/messaging/activemq/ServerDefinition.java
  messaging-activemq/src/main/java/org/wildfly/extension/messaging/activemq/ha/HAAttributes.java
  messaging-activemq/src/main/java/org/wildfly/extension/messaging/activemq/ha/SharedStoreMasterDefinition.java
  messaging-activemq/src/main/java/org/wildfly/extension/messaging/activemq/jms/ConnectionFactoryAdd.java
  messaging-activemq/src/main/java/org/wildfly/extension/messaging/activemq/jms/ConnectionFactoryAttribute.java
  messaging-activemq/src/main/java/org/wildfly/extension/messaging/activemq/jms/ConnectionFactoryAttributes.java
  messaging-activemq/src/main/java/org/wildfly/extension/messaging/activemq/jms/legacy/LegacyConnectionFactoryDefinition.java
Labels: ready-for-merge
