Repository wildfly/wildfly, pull requests merged in 2018-05, with the labels that each got.

#10768 WFLY-9710 Add Undertow specific buffer pool
  undertow/src/main/java/org/wildfly/extension/undertow/ByteBufferPoolDefinition.java
  undertow/src/main/java/org/wildfly/extension/undertow/Capabilities.java
  undertow/src/main/java/org/wildfly/extension/undertow/Constants.java
  undertow/src/main/java/org/wildfly/extension/undertow/HttpsListenerService.java
  undertow/src/main/java/org/wildfly/extension/undertow/ListenerAdd.java
  undertow/src/main/java/org/wildfly/extension/undertow/ListenerResourceDefinition.java
  undertow/src/main/java/org/wildfly/extension/undertow/ListenerService.java
  undertow/src/main/java/org/wildfly/extension/undertow/ServletContainerAdd.java
  undertow/src/main/java/org/wildfly/extension/undertow/ServletContainerService.java
  undertow/src/main/java/org/wildfly/extension/undertow/UndertowExtension.java
  undertow/src/main/java/org/wildfly/extension/undertow/UndertowRootDefinition.java
  undertow/src/main/java/org/wildfly/extension/undertow/UndertowSubsystemParser_6_0.java
  undertow/src/main/java/org/wildfly/extension/undertow/UndertowTransformers.java
  undertow/src/main/java/org/wildfly/extension/undertow/WebsocketsDefinition.java
  undertow/src/main/resources/org/wildfly/extension/undertow/LocalDescriptions.properties
  undertow/src/main/resources/schema/wildfly-undertow_6_0.xsd
  undertow/src/test/java/org/wildfly/extension/undertow/AbstractUndertowSubsystemTestCase.java
  undertow/src/test/java/org/wildfly/extension/undertow/DefaultInitialization.java
  undertow/src/test/java/org/wildfly/extension/undertow/UndertowTransformersTestCase.java
  undertow/src/test/resources/org/wildfly/extension/undertow/undertow-6.0.xml
  undertow/src/test/resources/org/wildfly/extension/undertow/undertow-reject.xml
Labels: Feature, missing-reqs

#11194 [WFCORE-3596] Add documentation for named permission sets and remove a permissions test case that is no longer valid
  docs/src/main/asciidoc/_elytron/Elytron_Subsystem.adoc
  docs/src/main/asciidoc/_elytron/Using_the_Elytron_Subsystem.adoc
  testsuite/integration/elytron/src/test/java/org/wildfly/test/integration/elytron/permissionmappers/ConstantPermissionMapperTestCase.java
Labels: core-upgrade-needed

#11149 WLFY-10048 - Deploying of malformed MDB should fail
  ejb3/src/main/java/org/jboss/as/ejb3/deployment/processors/MessageDrivenComponentDescriptionFactory.java
  ejb3/src/main/java/org/jboss/as/ejb3/logging/EjbLogger.java
  ejb3/src/main/java/org/jboss/as/ejb3/util/MdbValidationsUtil.java
  ejb3/src/main/java/org/jboss/as/ejb3/util/MdbValidityStatus.java
  ejb3/src/test/java/org/jboss/as/ejb3/util/InvalidMdbFinalClass.java
  ejb3/src/test/java/org/jboss/as/ejb3/util/InvalidMdbInterface.java
  ejb3/src/test/java/org/jboss/as/ejb3/util/InvalidMdbOnMessageCantBeFinal.java
  ejb3/src/test/java/org/jboss/as/ejb3/util/InvalidMdbOnMessageCantBePrivate.java
  ejb3/src/test/java/org/jboss/as/ejb3/util/InvalidMdbOnMessageCantBeStatic.java
  ejb3/src/test/java/org/jboss/as/ejb3/util/InvalidMdbWithFinalizeMethod.java
  ejb3/src/test/java/org/jboss/as/ejb3/util/MdbValidationsUtilTest.java
Labels: ready-for-merge

#11128 [WFLY-10243] replaced -Dsecmgr with -secmgr
  feature-pack/src/main/resources/content/bin/wsconsume.bat
  feature-pack/src/main/resources/content/bin/wsprovide.bat
Labels: ready-for-merge

#11069 WFLY-9648 Expose configuration for non-blocking initial state transfer for replicated/distributed caches
  clustering/common/src/main/java/org/jboss/as/clustering/controller/transform/RejectAttributeValueChecker.java
  clustering/common/src/main/java/org/jboss/as/clustering/logging/ClusteringLogger.java
  clustering/common/src/test/java/org/jboss/as/clustering/subsystem/RejectedValueConfig.java
  clustering/infinispan/extension/src/main/java/org/jboss/as/clustering/infinispan/subsystem/StateTransferBuilder.java
  clustering/infinispan/extension/src/main/java/org/jboss/as/clustering/infinispan/subsystem/StateTransferResourceDefinition.java
  clustering/infinispan/extension/src/main/resources/org/jboss/as/clustering/infinispan/subsystem/LocalDescriptions.properties
  clustering/infinispan/extension/src/main/resources/schema/jboss-as-infinispan_6_0.xsd
  clustering/infinispan/extension/src/test/java/org/jboss/as/clustering/infinispan/subsystem/InfinispanTransformersTestCase.java
  clustering/infinispan/extension/src/test/resources/org/jboss/as/clustering/infinispan/subsystem/infinispan-transformer-reject.xml
  clustering/infinispan/extension/src/test/resources/org/jboss/as/clustering/infinispan/subsystem/subsystem-infinispan-6_0.xml
  docs/src/main/asciidoc/_high-availability/subsystem-support/Infinispan_Subsystem.adoc
Labels: Feature, Galleon impact checked

#11228 WFLY-10376 Move trace logging to correct place
  ee/src/main/java/org/jboss/as/ee/component/deployers/ModuleJndiBindingProcessor.java
Labels: ready-for-merge

#11225 [WFLY-10228] Upgrade Picketlink from 2.5.5.SP10 to 2.5.5.SP11
  pom.xml
Labels: ready-for-merge

#11204 [WFLY-10330] delete duplicate version properties after component-matrix version revert
  pom.xml
Labels: ready-for-merge

#11197 WFLY-10337
  testsuite/integration/ws/src/test/java/org/jboss/as/test/integration/ws/authentication/policy/AuthenticationPolicyContextTestCase.java
Labels: ready-for-merge

#11238 [WFLY-10386] Replace hard coded dependent groupId with project.groupId
  clustering/infinispan/extension/pom.xml
  dist/pom.xml
  galleon-pack/pom.xml
  servlet-build/pom.xml
  servlet-dist/pom.xml
Labels: ready-for-merge
