Repository wildfly/wildfly, pull requests merged in 2018-10, with the labels that each got.

#11720 WFLY-10464 ChannelCommandDispatcher's RequestCorellator bypasses stack configuration including encryption
  clustering/server/src/main/java/org/wildfly/clustering/server/dispatcher/ChannelCommandDispatcherFactory.java
Labels: ready-for-merge

#11736 [WFCORE-4127] Add documentation how to disable CLI paging with an option
  docs/src/main/asciidoc/_admin-guide/Command_Line_Interface.adoc
Labels: ready-for-merge

#11722 [WFLY-11080] Upgrade smallrye-config 1.3.4
  pom.xml
Labels: ready-for-merge

#11732 WFLY-11155 IdentifierSerializerTestCase.testHex fails in JDK11
  clustering/web/spi/src/main/java/org/wildfly/clustering/web/IdentifierSerializer.java
Labels: ready-for-merge

#11725 [WFLY-11128] added ref to jboss-modules
  feature-pack/src/main/resources/modules/system/layers/base/org/jboss/ws/jaxws-client/main/module.xml
Labels: Blocker

#11735 [WFLY-10530] Define the java.util.logging.manager system property in …
  testsuite/domain/pom.xml
Labels: ready-for-merge

#11737 [WFLY-11160] upgrade jboss-el-api_spec to 1.0.13.Final
  pom.xml
Labels: ready-for-merge

#11739 WFLY-11169 Default ASYM_ENCRYPT asym_keylength is considered breakable
  clustering/jgroups/extension/src/main/resources/jgroups-defaults.xml
Labels: ready-for-merge

#11742 [WFLY-11182] Upgrade to WildFly Galleon Plugins 2.0.2.Final and prope…
  build/pom.xml
  dist/pom.xml
  galleon-pack/pom.xml
  pom.xml
  servlet-build/pom.xml
  servlet-dist/pom.xml
  servlet-galleon-pack/pom.xml
  testsuite/integration/elytron/pom.xml
  testsuite/integration/smoke/pom.xml
Labels: ready-for-merge

#11743 [WFLY-11183]: Artemis client pulls netty dependencies
  pom.xml
  testsuite/integration/elytron/pom.xml
Labels: ready-for-merge

#11750 [WFLY-11196] The javax.orb.api module only optionally depends on subs…
  feature-pack/src/main/resources/modules/system/layers/base/javax/orb/api/main/module.xml
Labels: ready-for-merge

#11754 WFLY-11184, make jpa dependency on ejb3 optional
  feature-pack/src/main/resources/modules/system/layers/base/org/jboss/as/jpa/main/module.xml
  jpa/subsystem/src/main/java/org/jboss/as/jpa/subsystem/JPASubSystemAdd.java
Labels: ready-for-merge

#11757 [WFLY-11137] Make undertow extension module's dependency on org.jbossas.security and org.picketbox modules optional
  security/subsystem/src/main/java/org/jboss/as/security/RealmDirectLoginModule.java
  security/subsystem/src/main/java/org/jboss/as/security/deployment/SecurityAttachments.java
  servlet-feature-pack/src/main/resources/modules/system/layers/base/org/wildfly/extension/undertow/main/module.xml
  undertow/src/main/java/org/wildfly/extension/undertow/deployment/UndertowDeploymentProcessor.java
  undertow/src/main/java/org/wildfly/extension/undertow/security/DigestCredentialImpl.java
Labels: ready-for-merge

#11758 [WFLY-11201] Mark JPA subsystem use of org.jboss.as.weld.common as op…
  feature-pack/src/main/resources/modules/system/layers/base/org/jboss/as/jpa/main/module.xml
Labels: ready-for-merge

#11734 [WFLY-11157] Remove unused module and pom dependencies on org.jboss.as.threads
  clustering/infinispan/extension/pom.xml
  feature-pack/src/main/resources/modules/system/layers/base/org/jboss/as/clustering/infinispan/main/module.xml
  feature-pack/src/main/resources/modules/system/layers/base/org/jboss/as/jdr/main/module.xml
  feature-pack/src/main/resources/modules/system/layers/base/org/jboss/as/jpa/main/module.xml
  jdr/jboss-as-jdr/pom.xml
  servlet-feature-pack/src/main/resources/modules/system/layers/base/org/wildfly/extension/undertow/main/module.xml
Labels: ready-for-merge

#11748 [WFLY-11185] Transaction subsystem only optionally depends on io.unde…
  feature-pack/src/main/resources/modules/system/layers/base/org/jboss/as/transactions/main/module.xml
  transactions/src/main/java/org/jboss/as/txn/subsystem/TransactionSubsystemAdd.java
Labels: ready-for-merge

#11752 [WFLY-11197] Add capability to bean-validation; use it in JSF and JPA…
  bean-validation/src/main/java/org/wildfly/extension/beanvalidation/BeanValidationRootDefinition.java
  feature-pack/src/main/resources/modules/system/layers/base/org/jboss/as/jpa/main/module.xml
  feature-pack/src/main/resources/modules/system/layers/base/org/jboss/as/jsf/main/module.xml
  jpa/subsystem/src/main/java/org/jboss/as/jpa/processor/PersistenceUnitServiceHandler.java
  jsf/subsystem/src/main/java/org/jboss/as/jsf/subsystem/JSFSubsystemAdd.java
Labels: ready-for-merge

#11761 [WFLY-11202] Upgrade yasson to 1.0.2; fix https://github.com/eclipse-…
  pom.xml
Labels: ready-for-merge

#11763 [WFLY-11207] Remove link to a constant from java doc
  security/subsystem/src/main/java/org/jboss/as/security/deployment/SecurityAttachments.java
Labels: ready-for-merge

#11765 [WFLY-11200]: Messaging-activemq integration code alters the JMS client's enabled protocols via TransportConfiguration
  messaging-activemq/src/main/java/org/wildfly/extension/messaging/activemq/TransportConfigOperationHandlers.java
  messaging-activemq/src/main/java/org/wildfly/extension/messaging/activemq/jms/ExternalPooledConnectionFactoryService.java
  messaging-activemq/src/main/java/org/wildfly/extension/messaging/activemq/jms/PooledConnectionFactoryService.java
Labels: ready-for-merge

#11715 [WFLY-10531] Wildfly leaks ActiveMQ connections
  messaging-activemq/src/main/java/org/wildfly/extension/messaging/activemq/deployment/injection/TransactedJMSContext.java
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/messaging/jms/context/notClosingInjectedContext/NotClosingInjectedContextTestCase.java
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/messaging/jms/context/notClosingInjectedContext/auxiliary/Ejb.java
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/messaging/jms/context/notClosingInjectedContext/auxiliary/Mdb.java
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/messaging/jms/context/notClosingInjectedContext/auxiliary/StartUp.java
Labels: ready-for-merge

#11751 [WFLY-11195] The org.jboss.xts module only require org.jboss.as.xts i…
  feature-pack/src/main/resources/modules/system/layers/base/org/jboss/xts/main/module.xml
Labels: ready-for-merge

#11740 [WFLY-11175] Use a standard dependency injection for TM integration i…
  messaging-activemq/src/main/java/org/wildfly/extension/messaging/activemq/jms/bridge/JMSBridgeAdd.java
  messaging-activemq/src/main/java/org/wildfly/extension/messaging/activemq/jms/bridge/JMSBridgeService.java
Labels: ready-for-merge

#11718 [WFLY-10902] Mixed domain test for WildFly 14
  galleon-pack/src/main/resources/feature_groups/domain-host-excludes.xml
  testsuite/domain/src/test/java/org/jboss/as/test/integration/domain/HostExcludesTestCase.java
  testsuite/integration/manualmode/src/test/resources/legacy-configs/domain/wildfly-14-0-0.xml
  testsuite/mixed-domain/src/test/java/org/jboss/as/test/integration/domain/mixed/DomainAdjuster.java
  testsuite/mixed-domain/src/test/java/org/jboss/as/test/integration/domain/mixed/DomainHostExcludesTest.java
  testsuite/mixed-domain/src/test/java/org/jboss/as/test/integration/domain/mixed/MixedDomainTestSupport.java
  testsuite/mixed-domain/src/test/java/org/jboss/as/test/integration/domain/mixed/Version.java
  testsuite/mixed-domain/src/test/java/org/jboss/as/test/integration/domain/mixed/eap710/DomainAdjuster710.java
  testsuite/mixed-domain/src/test/java/org/jboss/as/test/integration/domain/mixed/eap720/DomainAdjuster720.java
  testsuite/mixed-domain/src/test/java/org/jboss/as/test/integration/domain/mixed/eap720/DomainHostExcludes720TestCase.java
  testsuite/mixed-domain/src/test/java/org/jboss/as/test/integration/domain/mixed/eap720/ElytronOnlyMaster720TestSuite.java
  testsuite/mixed-domain/src/test/java/org/jboss/as/test/integration/domain/mixed/eap720/ElytronOnlyMasterSmoke720TestCase.java
  testsuite/mixed-domain/src/test/java/org/jboss/as/test/integration/domain/mixed/eap720/KernelBehavior720TestSuite.java
  testsuite/mixed-domain/src/test/java/org/jboss/as/test/integration/domain/mixed/eap720/LegacyConfig720TestCase.java
  testsuite/mixed-domain/src/test/java/org/jboss/as/test/integration/domain/mixed/eap720/LegacyConfig720TestSuite.java
  testsuite/mixed-domain/src/test/java/org/jboss/as/test/integration/domain/mixed/eap720/LegacyConfigAdjuster720.java
  testsuite/mixed-domain/src/test/java/org/jboss/as/test/integration/domain/mixed/eap720/MixedDomain720TestSuite.java
  testsuite/mixed-domain/src/test/java/org/jboss/as/test/integration/domain/mixed/eap720/MixedDomainDeployment720TestCase.java
  testsuite/mixed-domain/src/test/java/org/jboss/as/test/integration/domain/mixed/eap720/MixedDomainDeploymentOverlay720TestCase.java
  testsuite/mixed-domain/src/test/java/org/jboss/as/test/integration/domain/mixed/eap720/MixedDomainOverlay720TestSuite.java
  testsuite/mixed-domain/src/test/java/org/jboss/as/test/integration/domain/mixed/eap720/RBACConfig720TestCase.java
  testsuite/mixed-domain/src/test/java/org/jboss/as/test/integration/domain/mixed/eap720/SimpleMixedDomain720TestCase.java
  testsuite/mixed-domain/src/test/java/org/jboss/as/test/integration/domain/mixed/eap720/WildcardReads720TestCase.java
Labels: ready-for-merge

#11772 [WFLY-11222] Remove the check for the -secmgr in the JAVA_OPTS. This …
  feature-pack/src/main/resources/content/bin/wsconsume.bat
  feature-pack/src/main/resources/content/bin/wsconsume.sh
  feature-pack/src/main/resources/content/bin/wsprovide.bat
  feature-pack/src/main/resources/content/bin/wsprovide.sh
Labels: Blocker

#11768 [WFLY-11212] jdbc-driver's datasource-class-info is not a metric
  connector/src/main/java/org/jboss/as/connector/subsystems/datasources/JdbcDriverDefinition.java
Labels: ready-for-merge

#11696 [WFLY-11077] JwtValidator jku and kid header parameters
  docs/src/main/asciidoc/_elytron/Bearer_Token_Authorization.adoc
Labels: Feature-Docs, core-upgrade-needed

#11787 [WFLY-11257] Validate requirement for modules previously exported by javax.ejb.api on org.jboss.as.jsr77
  feature-pack/src/main/resources/modules/system/layers/base/org/jboss/as/jsr77/main/module.xml
Labels: ready-for-merge
