Repository wildfly/wildfly, pull requests merged in 2018-02, with the labels that each got.

#10761 [WFLY-9679] removing duplication in implementation of test XAResources
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/ejb/transaction/exception/TimeoutTestXAResource.java
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/ejb/transaction/exception/TxExceptionBaseTestCase.java
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/ejb/transaction/exception/bean/ejb3/CmtEjb3.java
  testsuite/shared/src/main/java/org/jboss/as/test/integration/transactions/TestXAResource.java
Labels: ready-for-merge

#10694 [WFLY-9538] support for -secmgr replaces old flag
  feature-pack/src/main/resources/content/bin/wsprovide.bat
  feature-pack/src/main/resources/content/bin/wsprovide.sh
Labels: ready-for-merge

#10763 WFLY-9540 Add session operations and details to the Undertow subsystem
  testsuite/integration/web/src/test/java/org/jboss/as/test/integration/web/session/SessionManagementTestCase.java
  undertow/src/main/java/org/wildfly/extension/undertow/Constants.java
  undertow/src/main/java/org/wildfly/extension/undertow/DeploymentDefinition.java
  undertow/src/main/java/org/wildfly/extension/undertow/logging/UndertowLogger.java
  undertow/src/main/resources/org/wildfly/extension/undertow/LocalDescriptions.properties
Labels: Feature, hold

#10863 [WFLY-6458] Ensure the correct version of the JavaMail API used.
  feature-pack/src/main/resources/modules/system/layers/base/javax/mail/api/main/module.xml
Labels: EE8

#10854 [WFLY-9128] JAXB 2.2 / 2.3 module switch to load the API that matches…
  feature-pack/pom.xml
  feature-pack/src/main/resources/modules/system/layers/base/javax/xml/bind/api/main/module.xml
  pom.xml
Labels: EE8

#10734 [WFLY-6462] Add support for JSF 2.3 using the ee8.preview.mode switch
  feature-pack/pom.xml
  feature-pack/src/license/full-feature-pack-licenses.xml
  feature-pack/src/main/resources/modules/system/layers/base/com/sun/jsf-impl/main/module.xml
  feature-pack/src/main/resources/modules/system/layers/base/javax/faces/api/main/module.xml
  jsf/subsystem/pom.xml
  pom.xml
  spec-api/pom.xml
  testsuite/integration/ee8-temp/pom.xml
  testsuite/integration/ee8-temp/src/test/java/org/wildfly/test/integration/ee8/temp/jsf23/ConfirmBean.java
  testsuite/integration/ee8-temp/src/test/java/org/wildfly/test/integration/ee8/temp/jsf23/ConfirmRegistrationBehavior.java
  testsuite/integration/ee8-temp/src/test/java/org/wildfly/test/integration/ee8/temp/jsf23/DummyBean.java
  testsuite/integration/ee8-temp/src/test/java/org/wildfly/test/integration/ee8/temp/jsf23/JSF23SanityTestCase.java
  testsuite/integration/ee8-temp/src/test/java/org/wildfly/test/integration/ee8/temp/jsf23/beans.xml
  testsuite/integration/ee8-temp/src/test/java/org/wildfly/test/integration/ee8/temp/jsf23/confirmation.xhtml
  testsuite/integration/ee8-temp/src/test/java/org/wildfly/test/integration/ee8/temp/jsf23/faces-config.xml
  testsuite/integration/ee8-temp/src/test/java/org/wildfly/test/integration/ee8/temp/jsf23/index.xhtml
  testsuite/integration/ee8-temp/src/test/java/org/wildfly/test/integration/ee8/temp/jsf23/register.taglib.xml
Labels: EE8, Feature

#10725 WFLY-9628 Bean Validation 2.0 support with ee8.preview.mode switch
  bean-validation/pom.xml
  bean-validation/src/main/java/org/jboss/as/ee/beanvalidation/LazyValidatorFactory.java
  bean-validation/src/test/java/org/jboss/as/ee/beanvalidation/testprovider/MyConfiguration.java
  bean-validation/src/test/java/org/jboss/as/ee/beanvalidation/testprovider/MyValidatorFactoryImpl.java
  connector/src/main/java/org/jboss/as/connector/util/JCAValidatorFactory.java
  docs/src/main/asciidoc/Getting_Started_Guide.adoc
  feature-pack/pom.xml
  feature-pack/src/license/full-feature-pack-licenses.xml
  feature-pack/src/main/resources/modules/system/layers/base/org/hibernate/validator/cdi/main/module.xml
  feature-pack/src/main/resources/modules/system/layers/base/org/hibernate/validator/main/module.xml
  jpa/hibernate5/pom.xml
  pom.xml
  servlet-feature-pack/feature-pack-build.xml
  servlet-feature-pack/src/main/resources/modules/system/layers/base/javax/validation/api/main/module.xml
  testsuite/integration/ee8-temp/pom.xml
  testsuite/integration/ee8-temp/src/test/java/org/wildfly/test/integration/ee8/temp/BeanValidationEE8TestCase.java
  weld/bean-validation/pom.xml
Labels: EE8, Feature

#10872 [WFLY-6460] and [WFLY-7185] Add JSON-P 1.1 and JSON-B 1.0 Java EE 8 tech preview support
  client/jms/pom.xml
  ee/src/main/java/org/jboss/as/ee/managedbean/processors/JavaEEDependencyProcessor.java
  pom.xml
  servlet-feature-pack/pom.xml
  servlet-feature-pack/src/main/resources/modules/system/layers/base/javax/json/api/main/module.xml
  servlet-feature-pack/src/main/resources/modules/system/layers/base/javax/json/bind/api/main/module.xml
  servlet-feature-pack/src/main/resources/modules/system/layers/base/org/eclipse/yasson/main/module.xml
  servlet-feature-pack/src/main/resources/modules/system/layers/base/org/glassfish/javax/json/main/module.xml
  spec-api/pom.xml
  testsuite/integration/ee8-temp/pom.xml
  testsuite/integration/ee8-temp/src/test/java/org/jboss/as/test/integration/json/JSONBServlet.java
  testsuite/integration/ee8-temp/src/test/java/org/jboss/as/test/integration/json/JSONBTestCase.java
  testsuite/integration/ee8-temp/src/test/java/org/jboss/as/test/integration/json/JSONPServlet.java
  testsuite/integration/ee8-temp/src/test/java/org/jboss/as/test/integration/json/JSONPTestCase.java
  webservices/tests-integration/pom.xml
Labels: EE8

#10875 [WFLY-9628] Follow up to fix the way the module resources are applied
  pom.xml
  servlet-feature-pack/feature-pack-build.xml
  servlet-feature-pack/src/main/resources/modules/system/layers/base/javax/validation/api/main/module.xml
Labels: EE8

#10830 [WFCORE-3305] Add documentation for the advanced key-store manipulation management operations and update the one-way and two-way SSL documentation accordingly
  docs/src/main/asciidoc/_elytron/Using_the_Elytron_Subsystem.adoc
Labels: core-upgrade-needed

#10824 WFLY-9772 Intermittent failures in EjbRemoveUnitTestCase
  ee/src/main/java/org/jboss/as/ee/component/deployers/ModuleJndiBindingProcessor.java
Labels: core-upgrade-needed

#10808 [ee8] WFLY-6463 Common Annotations 1.3 Support
  ee/pom.xml
  jaxrs/pom.xml
  jpa/eclipselink/pom.xml
  jpa/hibernate4_1/pom.xml
  jpa/hibernate4_3/pom.xml
  jpa/hibernate5/pom.xml
  pom.xml
  servlet-feature-pack/pom.xml
  servlet-feature-pack/src/license/servlet-feature-pack-licenses.xml
  servlet-feature-pack/src/main/resources/modules/system/layers/base/javax/annotation/api/main/module.xml
  spec-api/pom.xml
  testsuite/integration/ee8-temp/pom.xml
  testsuite/integration/ee8-temp/src/test/java/org/wildfly/test/integration/ee8/commonannotations13/datasourcedefinition/DataSourceBean.java
  testsuite/integration/ee8-temp/src/test/java/org/wildfly/test/integration/ee8/commonannotations13/datasourcedefinition/EmbeddedDataSource.java
  testsuite/integration/ee8-temp/src/test/java/org/wildfly/test/integration/ee8/commonannotations13/datasourcedefinition/RepeatableDataSourceDefinitionTestCase.java
  web-common/pom.xml
  weld/subsystem/pom.xml
Labels: EE8, Feature

#10811 Add test for WFCORE-3447, CLI SSL commands for undertow server
  docs/src/main/asciidoc/_admin-guide/CLI_Recipes.adoc
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/management/cli/SecurityCommandsTestCase.java
Labels: core-upgrade-needed

#10896 [WFLY-9821] Fix WeldProvider
  weld/subsystem/src/main/java/org/jboss/as/weld/WeldProvider.java
Labels: ready-for-merge

#10911 WFLY-9866 (EE 8) JSF 2.3 api needs a dependency on websocket
  feature-pack/src/main/resources/modules/system/layers/base/javax/faces/api/main/module.xml
Labels: ready-for-merge

#10910 WFLY-9865 ugraded Jastow to 2.0.3.Final
  pom.xml
Labels: ready-for-merge

#10901 WFLY-9857 wildfly-clustering-spi brings in unnecessary/duplicated dep…
  clustering/infinispan/spi/pom.xml
  clustering/infinispan/spi/src/main/java/org/wildfly/clustering/infinispan/spi/persistence/DynamicKeyFormatMapper.java
Labels: ready-for-merge

#10731 [WFLY-9637] Stop using deprecated OFE constructor
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/ejb/timerservice/mgmt/AbstractTimerManagementTestCase.java
Labels: ready-for-merge

#10700 [WFLY-8875] EE: more informative log when injection fails
  ee/src/main/java/org/jboss/as/ee/component/ManagedReferenceFieldInjectionInterceptorFactory.java
  ee/src/main/java/org/jboss/as/ee/logging/EeLogger.java
Labels: fixme

#10702 [WFLY-9346] IIOP: elytron capabilities refactor
  iiop-openjdk/src/main/java/org/wildfly/iiop/openjdk/Capabilities.java
  iiop-openjdk/src/main/java/org/wildfly/iiop/openjdk/IIOPRootDefinition.java
  iiop-openjdk/src/main/java/org/wildfly/iiop/openjdk/IIOPSubsystemAdd.java
  iiop-openjdk/src/test/java/org/wildfly/iiop/openjdk/IIOPSubsystemTransformersTestCase.java
Labels: fixme

#10915 WFLY-9870 Intermittent failure in InterDeploymentDependenciesEarTestCase
  ee/src/main/java/org/jboss/as/ee/component/deployers/ModuleJndiBindingProcessor.java
  naming/src/main/java/org/jboss/as/naming/service/BinderService.java
Labels: hold

#10925 Fix WFLY-9884
  weld/subsystem/src/main/java/org/jboss/as/weld/services/bootstrap/WeldResourceInjectionServices.java
Labels: ready-for-merge

#10940 [WFLY-9706] Correct negative values to -1 for messaging attributes
  messaging-activemq/src/main/java/org/wildfly/extension/messaging/activemq/BridgeDefinition.java
  messaging-activemq/src/main/java/org/wildfly/extension/messaging/activemq/ClusterConnectionDefinition.java
  messaging-activemq/src/main/java/org/wildfly/extension/messaging/activemq/CommonAttributes.java
  messaging-activemq/src/main/java/org/wildfly/extension/messaging/activemq/InfiniteOrPositiveValidators.java
  messaging-activemq/src/main/java/org/wildfly/extension/messaging/activemq/ServerDefinition.java
  messaging-activemq/src/main/java/org/wildfly/extension/messaging/activemq/ha/HAAttributes.java
  messaging-activemq/src/main/java/org/wildfly/extension/messaging/activemq/jms/ConnectionFactoryAttributes.java
  messaging-activemq/src/main/java/org/wildfly/extension/messaging/activemq/jms/bridge/JMSBridgeDefinition.java
  messaging-activemq/src/main/java/org/wildfly/extension/messaging/activemq/jms/legacy/LegacyConnectionFactoryDefinition.java
Labels: 12.x, ready-for-merge

#10938 [WFLY-9897] getBytes(); calls should be replaced with getBytes(Standa…
  clustering/jgroups/extension/src/main/java/org/jboss/as/clustering/jgroups/subsystem/CipherAuthTokenBuilder.java
  clustering/jgroups/extension/src/main/java/org/jboss/as/clustering/jgroups/subsystem/DigestAuthTokenBuilder.java
  clustering/jgroups/extension/src/main/java/org/jboss/as/clustering/jgroups/subsystem/PlainAuthTokenBuilder.java
Labels: ready-for-merge

#10946 Upgrade WildFly Core to 4.0.0.CR1
  pom.xml
Labels: 12.x

#10945 [WFLY-9912] Upgrade Artemis 1.5.5.jbossorg-009
  pom.xml
Labels: 12.x, ready-for-merge
