Repository wildfly/wildfly, pull requests merged in 2018-11, with the labels that each got.

#11778 [WFLY-11238] Eliminating ServiceBuilder's deprecated methods usages
  datasources-agroal/src/main/java/org/wildfly/extension/datasources/agroal/DataSourceService.java
  ee/src/main/java/org/jboss/as/ee/concurrent/service/ContextServiceService.java
  ee/src/main/java/org/jboss/as/ee/concurrent/service/EEConcurrentAbstractService.java
  ee/src/main/java/org/jboss/as/ee/naming/ApplicationContextProcessor.java
  ee/src/main/java/org/jboss/as/ee/naming/InApplicationClientBindingProcessor.java
  ee/src/main/java/org/jboss/as/ee/naming/ModuleContextProcessor.java
  ee/src/main/java/org/jboss/as/ee/subsystem/ContextServiceAdd.java
  iiop-openjdk/src/main/java/org/wildfly/iiop/openjdk/service/CorbaServiceUtil.java
  jpa/subsystem/src/main/java/org/jboss/as/jpa/processor/PersistenceUnitServiceHandler.java
  jpa/subsystem/src/main/java/org/jboss/as/jpa/service/PersistenceUnitServiceImpl.java
  jsr77/src/main/java/org/jboss/as/jsr77/subsystem/JSR77ManagementSubsystemAdd.java
  mail/src/main/java/org/jboss/as/mail/extension/MailSessionAdd.java
  mail/src/main/java/org/jboss/as/mail/extension/MailSessionDefinitionInjectionSource.java
  messaging-activemq/src/main/java/org/wildfly/extension/messaging/activemq/BinderServiceUtil.java
  messaging-activemq/src/main/java/org/wildfly/extension/messaging/activemq/deployment/JMSDestinationDefinitionInjectionSource.java
  naming/src/main/java/org/jboss/as/naming/WritableServiceBasedNamingStore.java
  security/subsystem/src/main/java/org/jboss/as/security/SecuritySubsystemRootResourceDefinition.java
  security/subsystem/src/main/java/org/jboss/as/security/service/SecurityBootstrapService.java
  weld/subsystem/src/main/java/org/jboss/as/weld/deployment/processors/WeldBeanManagerServiceProcessor.java
Labels: fixme

#11816 WFLY-11291 DependencyCollectingServiceBuilder must implement both requires() and addDependency() methods
  clustering/common/src/main/java/org/jboss/as/clustering/controller/CredentialSourceDependency.java
Labels: ready-for-merge

#11821 WFLY-11299 Add EAP 7.2.0 transformers tests for mod_cluster subsystem
  mod_cluster/extension/src/main/java/org/wildfly/extension/mod_cluster/ModClusterModel.java
  mod_cluster/extension/src/test/java/org/wildfly/extension/mod_cluster/ModClusterTransformersTestCase.java
Labels: ready-for-merge

#11618 [WFLY-10949] IllegalArgumentException when get jdbc driver info if xa-datasource-class is not defined
  connector/src/main/java/org/jboss/as/connector/subsystems/datasources/GetInstalledDriverOperationHandler.java
  testsuite/integration/smoke/src/test/java/org/jboss/as/test/smoke/mgmt/datasource/DataSourceOperationsUnitTestCase.java
Labels: ready-for-merge

#11717 [WFLY-11125] Convert weld subsystem module dependencies on security modules to optional
  feature-pack/src/main/resources/modules/system/layers/base/org/jboss/as/weld/common/main/module.xml
  feature-pack/src/main/resources/modules/system/layers/base/org/jboss/as/weld/main/module.xml
  weld/subsystem/src/main/java/org/jboss/as/weld/deployment/processors/SecurityBootstrapDependencyInstaller.java
  weld/subsystem/src/main/java/org/jboss/as/weld/services/bootstrap/WeldSecurityServices.java
Labels: ready-for-merge

#11726 WFLY-11117 Executing legacy operations in mod_cluster subsystem
  mod_cluster/extension/src/main/java/org/wildfly/extension/mod_cluster/LegacyMetricOperationsRegistration.java
  mod_cluster/extension/src/main/java/org/wildfly/extension/mod_cluster/LegacyProxyOperation.java
  mod_cluster/extension/src/main/java/org/wildfly/extension/mod_cluster/ProxyOperation.java
  mod_cluster/extension/src/main/java/org/wildfly/extension/mod_cluster/ProxyOperationExecutor.java
Labels: ready-for-merge

#11782 [WFLY-11248] - EJB Timer is not properly set when the database is different than the defaults
  ejb3/src/main/java/org/jboss/as/ejb3/timerservice/persistence/database/DatabaseTimerPersistence.java
  ejb3/src/test/java/org/jboss/as/ejb3/timerservice/persistence/database/DatabaseTimerPersistenceTestCase.java
Labels: ready-for-merge

#11807 [WFLY-11279] Remove unused dependencies from org.jboss.as.jpa
  feature-pack/src/main/resources/modules/system/layers/base/org/jboss/as/jpa/main/module.xml
Labels: ready-for-merge

#11818 [WFLY-11290]: Look up of RemoteConnectionFactory with discovery-group is null.
  messaging-activemq/src/main/java/org/wildfly/extension/messaging/activemq/jms/ExternalConnectionFactoryAdd.java
Labels: ready-for-merge

#11564 [WFLY-10894] Tests for propagating undertow authentication mode to El…
  testsuite/integration/elytron/src/test/java/org/wildfly/test/integration/elytron/authmode/ConstraintDrivenAuthModeTestCase.java
  testsuite/integration/elytron/src/test/java/org/wildfly/test/integration/elytron/authmode/ProactiveAuthModeTestCase.java
  testsuite/integration/elytron/src/test/java/org/wildfly/test/integration/elytron/authmode/authmode-page.jsp
  testsuite/integration/elytron/src/test/java/org/wildfly/test/integration/elytron/authmode/authmode-web.xml
Labels: ready-for-merge

#11789 [WFLY-11250] Add documentation for 'default-ssl-context' attribute.
  docs/src/main/asciidoc/_elytron/Using_the_Elytron_Subsystem.adoc
Labels: Feature-Docs

#11822 [WFLY-11303] Unnecessary registration of a CDI portable extension in Smallrye micro profile config
  feature-pack/src/main/resources/modules/system/layers/base/org/wildfly/extension/microprofile/config-smallrye/main/module.xml
  microprofile/config-smallrye/pom.xml
  microprofile/config-smallrye/src/main/java/org/wildfly/extension/microprofile/config/smallrye/deployment/SubsystemDeploymentProcessor.java
Labels: ready-for-merge

#11823 [WFLY-11306] Validate requirement for modules previously exported by javax.ejb.api on org.jberet.jberet-core
  feature-pack/src/main/resources/modules/system/layers/base/org/jberet/jberet-core/main/module.xml
Labels: ready-for-merge

#11824 [WFLY-11297] Documentation fix- add user to filesystem-realm using management CLI
  docs/src/main/asciidoc/_elytron/Using_the_Elytron_Subsystem.adoc
Labels: ready-for-merge

#11828 WFLY-11320 Upgrade Infinispan to 9.4.1.Final
  pom.xml
Labels: ready-for-merge

#11839 [WFLY-11330] Upgrade to Galleon and WildFly Galleon Plugins 3.0.0.CR1
  galleon-pack/pom.xml
  galleon-pack/src/main/resources/configs/domain/domain.xml/config.xml
  galleon-pack/src/main/resources/configs/domain/model.xml
  galleon-pack/src/main/resources/configs/host/host-master.xml/config.xml
  galleon-pack/src/main/resources/configs/host/host-slave.xml/config.xml
  galleon-pack/src/main/resources/configs/host/host.xml/config.xml
  galleon-pack/src/main/resources/configs/standalone/model.xml
  galleon-pack/src/main/resources/configs/standalone/standalone-full-ha.xml/config.xml
  galleon-pack/src/main/resources/configs/standalone/standalone-full.xml/config.xml
  galleon-pack/src/main/resources/configs/standalone/standalone-ha.xml/config.xml
  galleon-pack/src/main/resources/configs/standalone/standalone.xml/config.xml
  galleon-pack/wildfly-feature-pack-build.xml
  pom.xml
  servlet-galleon-pack/pom.xml
  servlet-galleon-pack/src/main/resources/configs/domain/domain.xml/config.xml
  servlet-galleon-pack/src/main/resources/configs/domain/model.xml
  servlet-galleon-pack/src/main/resources/configs/host/host-master.xml/config.xml
  servlet-galleon-pack/src/main/resources/configs/host/host-slave.xml/config.xml
  servlet-galleon-pack/src/main/resources/configs/host/host.xml/config.xml
  servlet-galleon-pack/src/main/resources/configs/standalone/model.xml
  servlet-galleon-pack/src/main/resources/configs/standalone/standalone-load-balancer.xml/config.xml
  servlet-galleon-pack/src/main/resources/configs/standalone/standalone.xml/config.xml
  servlet-galleon-pack/wildfly-feature-pack-build.xml
Labels: ready-for-merge

#11830 [WFLY-10712] Observability: MicroProfile Metrics
  batch-jberet/src/main/java/org/wildfly/extension/batch/jberet/deployment/BatchEnvironmentProcessor.java
  docs/src/main/asciidoc/_admin-guide/Subsystem_configuration.adoc
  docs/src/main/asciidoc/_admin-guide/subsystem-configuration/MicroProfile_Metrics.adoc
  feature-pack/pom.xml
  feature-pack/src/main/resources/configuration/examples/subsystems-activemq-colocated.xml
  feature-pack/src/main/resources/configuration/examples/subsystems-genericjms.xml
  feature-pack/src/main/resources/configuration/examples/subsystems-jts.xml
  feature-pack/src/main/resources/configuration/examples/subsystems-picketlink.xml
  feature-pack/src/main/resources/configuration/examples/subsystems-rts.xml
  feature-pack/src/main/resources/configuration/examples/subsystems-xts.xml
  feature-pack/src/main/resources/configuration/standalone/subsystems.xml
  feature-pack/src/main/resources/modules/system/layers/base/io/smallrye/metrics/main/module.xml
  feature-pack/src/main/resources/modules/system/layers/base/org/eclipse/microprofile/metrics/api/main/module.xml
  feature-pack/src/main/resources/modules/system/layers/base/org/wildfly/extension/microprofile/metrics-smallrye/main/module.xml
  galleon-pack/pom.xml
  galleon-pack/src/main/resources/feature_groups/domain-host-excludes.xml
  galleon-pack/src/main/resources/feature_groups/metrics.xml
  galleon-pack/src/main/resources/feature_groups/standalone-ha.xml
  galleon-pack/src/main/resources/feature_groups/standalone-profile.xml
  galleon-pack/wildfly-feature-pack-build.xml
  microprofile/metrics-smallrye/pom.xml
  microprofile/metrics-smallrye/src/main/java/org/wildfly/extension/microprofile/metrics/MetricsContextService.java
  microprofile/metrics-smallrye/src/main/java/org/wildfly/extension/microprofile/metrics/MetricsRegistrationService.java
  microprofile/metrics-smallrye/src/main/java/org/wildfly/extension/microprofile/metrics/MicroProfileMetricsExtension.java
  microprofile/metrics-smallrye/src/main/java/org/wildfly/extension/microprofile/metrics/MicroProfileMetricsParser_1_0.java
  microprofile/metrics-smallrye/src/main/java/org/wildfly/extension/microprofile/metrics/MicroProfileMetricsSubsystemAdd.java
  microprofile/metrics-smallrye/src/main/java/org/wildfly/extension/microprofile/metrics/MicroProfileMetricsSubsystemDefinition.java
  microprofile/metrics-smallrye/src/main/java/org/wildfly/extension/microprofile/metrics/_private/MicroProfileMetricsLogger.java
  microprofile/metrics-smallrye/src/main/java/org/wildfly/extension/microprofile/metrics/deployment/DependencyProcessor.java
  microprofile/metrics-smallrye/src/main/java/org/wildfly/extension/microprofile/metrics/deployment/DeploymentMetricProcessor.java
  microprofile/metrics-smallrye/src/main/java/org/wildfly/extension/microprofile/metrics/deployment/DeploymentMetricService.java
  microprofile/metrics-smallrye/src/main/resources/META-INF/services/org.jboss.as.controller.Extension
  microprofile/metrics-smallrye/src/main/resources/io/smallrye/metrics/base-metrics.properties
  microprofile/metrics-smallrye/src/main/resources/io/smallrye/metrics/vendor-metrics.properties
  microprofile/metrics-smallrye/src/main/resources/org/wildfly/extension/microprofile/metrics/LocalDescriptions.properties
  microprofile/metrics-smallrye/src/main/resources/schema/wildfly-microprofile-metrics-smallrye_1_0.xsd
  microprofile/metrics-smallrye/src/main/resources/subsystem-templates/microprofile-metrics-smallrye.xml
  microprofile/metrics-smallrye/src/test/java/org/wildfly/extension/microprofile/metrics/Subsystem_1_0_ParsingTestCase.java
  microprofile/metrics-smallrye/src/test/resources/org/wildfly/extension/microprofile/metrics/subsystem_1_0.xml
  pom.xml
  testsuite/integration/basic/pom.xml
  testsuite/integration/basic/src/test/java/org/wildfly/test/integration/microprofile/config/smallrye/app/MicroProfileConfigTestCase.java
  testsuite/integration/basic/src/test/java/org/wildfly/test/integration/microprofile/metrics/MetricsHelper.java
  testsuite/integration/basic/src/test/java/org/wildfly/test/integration/microprofile/metrics/application/MicroProfileMetricsApplicationTestCase.java
  testsuite/integration/basic/src/test/java/org/wildfly/test/integration/microprofile/metrics/application/TestApplication.java
  testsuite/integration/basic/src/test/java/org/wildfly/test/integration/microprofile/metrics/base/MicroProfileMetricsBaseTestCase.java
Labels: Feature

#11843 [WFLY-11308] Refactoring - eliminating ServiceBuilder.addDependency(ServiceName,Injector) usages
  connector/src/main/java/org/jboss/as/connector/subsystems/resourceadapters/AdminObjectAdd.java
  connector/src/main/java/org/jboss/as/connector/subsystems/resourceadapters/ConnectionDefinitionAdd.java
  connector/src/main/java/org/jboss/as/connector/subsystems/resourceadapters/RaAdd.java
  ejb3/src/main/java/org/jboss/as/ejb3/deployment/processors/DeploymentRepositoryProcessor.java
  jpa/subsystem/src/main/java/org/jboss/as/jpa/processor/PersistenceUnitServiceHandler.java
  jpa/subsystem/src/main/java/org/jboss/as/jpa/service/JPAUserTransactionListenerService.java
  pojo/src/main/java/org/jboss/as/pojo/descriptor/DefaultConfigVisitor.java
  weld/bean-validation/src/main/java/org/jboss/as/weld/deployment/processor/CdiBeanValidationFactoryProcessor.java
Labels: ready-for-merge

#11829 [WFCORE-4207]: Add capabilities in the Thread subsystem resource defi…
  connector/src/test/java/org/jboss/as/connector/subsystems/jca/JcaSubsystemTestCase.java
Labels: ready-for-merge

#11773 WFLY-11000 Upgrade dom4j from 1.6.1 to 2.1.1
  feature-pack/javadoc/README.txt
  feature-pack/pom.xml
  feature-pack/src/license/full-feature-pack-licenses.xml
  feature-pack/src/main/resources/modules/system/layers/base/org/dom4j/main/module.xml
  galleon-pack/javadoc/README.txt
  galleon-pack/pom.xml
  jpa/hibernate-transformer/pom.xml
  jpa/hibernate4_1/pom.xml
  jpa/hibernate4_3/pom.xml
  pom.xml
  testsuite/compat/pom.xml
  testsuite/compat/src/test/scripts/build-jars.xml
Labels: ready-for-merge

#11614 WFLY-7085 - Server should verify EJB business methods during deployment and log a warning
  ejb3/src/main/java/org/jboss/as/ejb3/component/EJBValidationConfigurator.java
  ejb3/src/main/java/org/jboss/as/ejb3/component/session/SessionBeanObjectViewConfigurator.java
  ejb3/src/main/java/org/jboss/as/ejb3/deployment/processors/MessageDrivenComponentDescriptionFactory.java
  ejb3/src/main/java/org/jboss/as/ejb3/logging/EjbLogger.java
  ejb3/src/main/java/org/jboss/as/ejb3/util/EjbValidationsUtil.java
  ejb3/src/main/java/org/jboss/as/ejb3/util/MdbValidationsUtil.java
  ejb3/src/test/java/org/jboss/as/ejb3/util/BusinessInterface.java
  ejb3/src/test/java/org/jboss/as/ejb3/util/ClassWithBusinessMethod.java
  ejb3/src/test/java/org/jboss/as/ejb3/util/EjbValidationsUtilTest.java
  ejb3/src/test/java/org/jboss/as/ejb3/util/EjbWithFinalMethod.java
  ejb3/src/test/java/org/jboss/as/ejb3/util/EjbWithPrivateFinalMethod.java
  ejb3/src/test/java/org/jboss/as/ejb3/util/EjbWithStaticMethod.java
Labels: fixme

#11864 [WFLY-11382] MicroProfileMetricsSubsystemAdd to use org.jboss.as.serv…
  microprofile/metrics-smallrye/src/main/java/org/wildfly/extension/microprofile/metrics/MicroProfileMetricsSubsystemAdd.java
Labels: ready-for-merge

#11888 [WFLY-11424]: Externalize the client configuration properties in an artifact.
  client/properties/pom.xml
  client/properties/src/main/resources/org.apache.activemq.artemis.api.jms.ActiveMQJMSClient.properties
  client/shade/pom.xml
  pom.xml
Labels: Blocker

#11889 [WFLY-11419] Upgrade artemis to 2.6.3.jbossorg-00014
  pom.xml
Labels: Blocker

#11854 [WFLY-11356] Test MaximumTimeoutTestCase fails with security manager
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/transaction/MaximumTimeoutTestCase.java
Labels: ready-for-merge

#11860 [WFLY-11373] run SetupActions when completing Weld initialization
  weld/subsystem/src/main/java/org/jboss/as/weld/WeldStartCompletionService.java
  weld/subsystem/src/main/java/org/jboss/as/weld/deployment/processors/WeldDeploymentCleanupProcessor.java
  weld/subsystem/src/main/java/org/jboss/as/weld/deployment/processors/WeldDeploymentProcessor.java
Labels: ready-for-merge

#11863 [WFLY-10168]: Unable to set global-client-thread-pool-max-size without setting global-client-scheduled-thread-pool-max-size and vice versa.
  messaging-activemq/src/main/java/org/wildfly/extension/messaging/activemq/MessagingSubsystemAdd.java
Labels: ready-for-merge

#11876 [WFLY-11402] Additional coverage for MP Metrics
  testsuite/integration/basic/src/test/java/org/wildfly/test/integration/microprofile/metrics/metadata/MicroProfileMetricsMetadataTestCase.java
  testsuite/integration/basic/src/test/java/org/wildfly/test/integration/microprofile/metrics/metadata/MicroProfileMetricsRequestMethodsTestCase.java
  testsuite/integration/basic/src/test/java/org/wildfly/test/integration/microprofile/metrics/secured/MicroProfileMetricsSecuredEndpointEmptyMgmtUsersTestCase.java
  testsuite/integration/basic/src/test/java/org/wildfly/test/integration/microprofile/metrics/secured/MicroProfileMetricsSecuredEndpointSetupTask.java
  testsuite/integration/basic/src/test/java/org/wildfly/test/integration/microprofile/metrics/secured/MicroProfileMetricsSecuredEndpointTestCase.java
Labels: ready-for-merge

#11884 [WFLY-11416] Add non-heap memory metrics + WFLY-11409
  microprofile/metrics-smallrye/src/main/resources/io/smallrye/metrics/base-metrics.properties
Labels: ready-for-merge

#11659 [WFLY-11003] Add documentation describing how to define an SSLContextfor SNI in the WildFly Elytron subsystem.
  docs/src/main/asciidoc/_elytron/Using_the_Elytron_Subsystem.adoc
Labels: Feature-Docs, ready-for-merge

#11903 [WFLY-11448] Fix registration of the :check operation
  microprofile/health-smallrye/src/main/java/org/wildfly/extension/microprofile/health/CheckOperation.java
  microprofile/health-smallrye/src/main/java/org/wildfly/extension/microprofile/health/MicroProfileHealthExtension.java
  microprofile/health-smallrye/src/main/java/org/wildfly/extension/microprofile/health/MicroProfileHealthSubsystemDefinition.java
Labels: ready-for-merge
