Repository wildfly/wildfly, pull requests merged in 2019-08, with the labels that each got.

#12470 [WFLY-12219] Disabling SSL failing tests for now on JDK14+
  testsuite/integration/manualmode/src/test/java/org/jboss/as/test/manualmode/web/ssl/CertificateRolesLoginModuleTestCase.java
  testsuite/integration/manualmode/src/test/java/org/jboss/as/test/manualmode/web/ssl/DatabaseCertLoginModuleTestCase.java
  testsuite/integration/manualmode/src/test/java/org/jboss/as/test/manualmode/web/ssl/HTTPSWebConnectorTestCase.java
Labels: deps-ok

#12468 [WFLY-12301] Ensure that EJBComponentDescription#setSecurityRequired only gets called if security is actually required to avoid resetting the value when there are multiple views
  ejb3/src/main/java/org/jboss/as/ejb3/security/EJBSecurityViewConfigurator.java
Labels: deps-ok

#12464 WFLY-12340 SimpleSecurityManager uses AccessController.doPrivileged e…
  security/subsystem/src/main/java/org/jboss/as/security/service/SimpleSecurityManager.java
Labels: deps-ok

#12471 WFLY-12350 Upgrade Infinispan to 9.4.16.Final
  clustering/infinispan/client/src/main/java/org/wildfly/clustering/infinispan/client/manager/RemoteCacheManager.java
  clustering/infinispan/client/src/main/java/org/wildfly/clustering/infinispan/client/near/CaffeineNearCache.java
  clustering/infinispan/client/src/main/java/org/wildfly/clustering/infinispan/client/near/CaffeineNearCacheService.java
  clustering/web/hotrod/src/main/java/org/wildfly/clustering/web/hotrod/session/SessionManagerNearCacheFactory.java
  pom.xml
  testsuite/integration/clustering/pom.xml
  testsuite/integration/clustering/src/test/java/org/jboss/as/test/clustering/cluster/web/remote/InfinispanServerSetupTask.java
Labels: deps-ok, ready-for-merge

#12473 WFLY-12351 Upgrade Weld core to 3.1.2.Final and Weld API to 3.1.SP1.
  pom.xml
Labels: deps-ok

#12482 [WFLY-12359] Upgrade WildFly Core 10.0.0.Beta3
  pom.xml
Labels: deps-ok, ready-for-merge

#12479 [WFLY-12341] component upgrade Narayana for 5.9.6.Final
  pom.xml
Labels: deps-ok, ready-for-merge

#12478 WFLY-12347 Upgrade jgroups-kubernetes to 1.0.12.Final
  pom.xml
Labels: deps-ok, ready-for-merge

#12477 [WFLY-12357] Upgrade to jackson-databind 2.9.9.3
  pom.xml
Labels: deps-ok, ready-for-merge

#11827 [WFLY-11318] Validate requirement for modules previously exported by javax.ejb.api on org.jboss.ws.common
  feature-pack/src/main/resources/modules/system/layers/base/org/jboss/ws/common/main/module.xml
Labels: deps-ok, ready-for-merge

#12484 WFLY-12362 integration test for WFCORE-3670 'module defined with an a…
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/deployment/structure/ear/Available2.java
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/deployment/structure/ear/EarJBossDeploymentStructureTestCase.java
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/deployment/structure/ear/jboss-deployment-structure.xml
Labels: deps-ok

#12474 WFLY-12352 Distributable SFSB creation unnecessarily checks passivation store
  clustering/ejb/infinispan/src/main/java/org/wildfly/clustering/ejb/infinispan/InfinispanBeanManager.java
  clustering/ejb/infinispan/src/main/java/org/wildfly/clustering/ejb/infinispan/bean/InfinispanBeanFactory.java
  clustering/ejb/infinispan/src/main/java/org/wildfly/clustering/ejb/infinispan/group/InfinispanBeanGroupFactory.java
  ejb3/src/main/java/org/jboss/as/ejb3/cache/distributable/DistributableCache.java
Labels: deps-ok

#12488 WFLY-12365 Cache TSR for manually bootstrapped hibernate apps
  jpa/hibernate5_3/src/main/java/org/jboss/as/jpa/hibernate5/service/WildFlyCustomJtaPlatform.java
Labels: deps-ok

#12486 [WFLY-12363] Eliminating deprecated WorkerService constructor usages
  undertow/src/test/java/org/wildfly/extension/undertow/AbstractUndertowSubsystemTestCase.java
Labels: deps-ok

#12268 [WFLY-6143] Server interceptors
  docs/src/main/asciidoc/_admin-guide/subsystem-configuration/EJB3.adoc
  ee/src/main/java/org/jboss/as/ee/component/interceptors/InterceptorOrder.java
  ejb3/src/main/java/org/jboss/as/ejb3/component/ContainerInterceptorMethodInterceptorFactory.java
  ejb3/src/main/java/org/jboss/as/ejb3/component/EJBComponentDescription.java
  ejb3/src/main/java/org/jboss/as/ejb3/component/EJBViewDescription.java
  ejb3/src/main/java/org/jboss/as/ejb3/component/ServerInterceptorsViewConfigurator.java
  ejb3/src/main/java/org/jboss/as/ejb3/component/session/SessionBeanComponentDescription.java
  ejb3/src/main/java/org/jboss/as/ejb3/interceptor/server/ServerInterceptorCache.java
  ejb3/src/main/java/org/jboss/as/ejb3/interceptor/server/ServerInterceptorMetaData.java
  ejb3/src/main/java/org/jboss/as/ejb3/logging/EjbLogger.java
  ejb3/src/main/java/org/jboss/as/ejb3/subsystem/EJB3Extension.java
  ejb3/src/main/java/org/jboss/as/ejb3/subsystem/EJB3Subsystem50Parser.java
  ejb3/src/main/java/org/jboss/as/ejb3/subsystem/EJB3Subsystem60Parser.java
  ejb3/src/main/java/org/jboss/as/ejb3/subsystem/EJB3SubsystemAdd.java
  ejb3/src/main/java/org/jboss/as/ejb3/subsystem/EJB3SubsystemModel.java
  ejb3/src/main/java/org/jboss/as/ejb3/subsystem/EJB3SubsystemNamespace.java
  ejb3/src/main/java/org/jboss/as/ejb3/subsystem/EJB3SubsystemRootResourceDefinition.java
  ejb3/src/main/java/org/jboss/as/ejb3/subsystem/EJB3SubsystemXMLAttribute.java
  ejb3/src/main/java/org/jboss/as/ejb3/subsystem/EJB3SubsystemXMLElement.java
  ejb3/src/main/java/org/jboss/as/ejb3/subsystem/EJB3SubsystemXMLPersister.java
  ejb3/src/main/java/org/jboss/as/ejb3/subsystem/EJBTransformers.java
  ejb3/src/main/java/org/jboss/as/ejb3/subsystem/ServerInterceptorsBindingsProcessor.java
  ejb3/src/main/java/org/jboss/as/ejb3/subsystem/ServerInterceptorsDependenciesDeploymentUnitProcessor.java
  ejb3/src/main/resources/org/jboss/as/ejb3/subsystem/LocalDescriptions.properties
  ejb3/src/main/resources/schema/wildfly-ejb3_6_0.xsd
  ejb3/src/main/resources/subsystem-templates/ejb3.xml
  ejb3/src/test/java/org/jboss/as/ejb3/subsystem/Ejb3SubsystemUnitTestCase.java
  ejb3/src/test/java/org/jboss/as/ejb3/subsystem/Ejb3TransformersTestCase.java
  ejb3/src/test/resources/org/jboss/as/ejb3/subsystem/subsystem.xml
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/ejb/interceptor/serverside/AbstractServerInterceptorsSetupTask.java
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/ejb/interceptor/serverside/InterceptorModule.java
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/ejb/interceptor/serverside/InterceptorsSetupTask.java
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/ejb/interceptor/serverside/SampleBean.java
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/ejb/interceptor/serverside/ScheduleBean.java
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/ejb/interceptor/serverside/ServerInterceptor.java
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/ejb/interceptor/serverside/ServerInterceptorsTestCase.java
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/ejb/interceptor/serverside/module.xml
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/ejb/interceptor/serverside/multiple/ExceptionThrowingInterceptor.java
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/ejb/interceptor/serverside/multiple/MultipleInterceptorsTestCase.java
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/ejb/interceptor/serverside/multiple/first-module.xml
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/ejb/interceptor/serverside/multiple/second-module.xml
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/ejb/interceptor/serverside/protocol/ProtocolSampleInterceptor.java
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/ejb/interceptor/serverside/protocol/RemoteProtocolChangeTestCase.java
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/ejb/interceptor/serverside/protocol/module.xml
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/ejb/interceptor/serverside/remote/LoggingInterceptor.java
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/ejb/interceptor/serverside/remote/RemoteBeanTestCase.java
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/ejb/interceptor/serverside/remote/SimpleCounter.java
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/ejb/interceptor/serverside/remote/StatefulCounterBean.java
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/ejb/interceptor/serverside/remote/module.xml
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/ejb/interceptor/serverside/secured/SampleInterceptor.java
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/ejb/interceptor/serverside/secured/SecuredBean.java
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/ejb/interceptor/serverside/secured/SecuredBeanTestCase.java
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/ejb/interceptor/serverside/secured/jboss-web.xml
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/ejb/interceptor/serverside/secured/module.xml
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/ejb/interceptor/serverside/secured/permissions.xml
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/ejb/interceptor/serverside/secured/roles.properties
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/ejb/interceptor/serverside/secured/users.properties
Labels: Feature, deps-ok

#12485 WFLY-12283 Upgrade IronJacamar from 1.4.16.Final to 1.4.17.Final
  pom.xml
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/ee/datasourcedefinition/DataSourceDefinitionTestCase.java
Labels: deps-ok, ready-for-merge

#12491 [WFLY-12367] Use capability name instead of SuspendController.SERVICE…
  batch-jberet/src/main/java/org/wildfly/extension/batch/jberet/_private/Capabilities.java
  batch-jberet/src/main/java/org/wildfly/extension/batch/jberet/deployment/BatchEnvironmentProcessor.java
  ejb3/src/main/java/org/jboss/as/ejb3/component/messagedriven/MessageDrivenComponentDescription.java
  ejb3/src/main/java/org/jboss/as/ejb3/subsystem/EJB3SubsystemAdd.java
  mod_cluster/undertow/src/main/java/org/wildfly/mod_cluster/undertow/UndertowEventHandlerAdapterServiceConfigurator.java
  transactions/src/main/java/org/jboss/as/txn/subsystem/TransactionSubsystemAdd.java
  undertow/src/main/java/org/wildfly/extension/undertow/Capabilities.java
  undertow/src/main/java/org/wildfly/extension/undertow/HostAdd.java
  undertow/src/main/java/org/wildfly/extension/undertow/deployment/UndertowDeploymentProcessor.java
  undertow/src/test/java/org/wildfly/extension/undertow/AbstractUndertowSubsystemTestCase.java
Labels: deps-ok

#12494 [WFLY-12280] - DatabaseTimerPersistence does not detect mssql driver …
  ejb3/src/main/java/org/jboss/as/ejb3/timerservice/persistence/database/DatabaseTimerPersistence.java
  ejb3/src/test/java/org/jboss/as/ejb3/timerservice/persistence/database/DatabaseTimerPersistenceTestCase.java
Labels: deps-ok

#12466 WFLY-12344 SecurityManager push/pull is expensive also for datasources
  connector/src/main/java/org/jboss/as/connector/subsystems/datasources/AbstractDataSourceService.java
Labels: deps-ok

#12492 WFLY-12369 Upgrade jboss-ejb-client from 4.0.21 to 4.0.22
  pom.xml
Labels: deps-ok

#12495 [WFLY-12280] Make MSSQL pattern static final field
  ejb3/src/main/java/org/jboss/as/ejb3/timerservice/persistence/database/DatabaseTimerPersistence.java
Labels: deps-ok

#12453 [WFLY-12326]: Messaging subsystem model version bump.
  messaging-activemq/src/main/java/org/wildfly/extension/messaging/activemq/MessagingExtension.java
  messaging-activemq/src/main/java/org/wildfly/extension/messaging/activemq/MessagingTransformerRegistration.java
Labels: deps-ok

#12467 [WFLY-12279] introducing ee concurrent resource capabilities
  ee/src/main/java/org/jboss/as/ee/concurrent/service/ConcurrentServiceNames.java
  ee/src/main/java/org/jboss/as/ee/subsystem/ContextServiceAdd.java
  ee/src/main/java/org/jboss/as/ee/subsystem/ContextServiceRemove.java
  ee/src/main/java/org/jboss/as/ee/subsystem/ContextServiceResourceDefinition.java
  ee/src/main/java/org/jboss/as/ee/subsystem/ManagedExecutorServiceAdd.java
  ee/src/main/java/org/jboss/as/ee/subsystem/ManagedExecutorServiceRemove.java
  ee/src/main/java/org/jboss/as/ee/subsystem/ManagedExecutorServiceResourceDefinition.java
  ee/src/main/java/org/jboss/as/ee/subsystem/ManagedScheduledExecutorServiceAdd.java
  ee/src/main/java/org/jboss/as/ee/subsystem/ManagedScheduledExecutorServiceRemove.java
  ee/src/main/java/org/jboss/as/ee/subsystem/ManagedScheduledExecutorServiceResourceDefinition.java
  ee/src/main/java/org/jboss/as/ee/subsystem/ManagedThreadFactoryAdd.java
  ee/src/main/java/org/jboss/as/ee/subsystem/ManagedThreadFactoryRemove.java
  ee/src/main/java/org/jboss/as/ee/subsystem/ManagedThreadFactoryResourceDefinition.java
  ee/src/test/resources/org/jboss/as/ee/subsystem/subsystem.xml
  ee/src/test/resources/org/jboss/as/ee/subsystem/subsystem_3_0.xml
  testsuite/mixed-domain/src/test/java/org/jboss/as/test/integration/domain/mixed/eap640/DomainAdjuster640.java
Labels: deps-ok, ready-for-merge

#12437 [WFLY-12294] Upgrade MicroProfile Metrics 2.0.1
  feature-pack/pom.xml
  feature-pack/src/license/full-feature-pack-licenses.xml
  feature-pack/src/main/resources/modules/system/layers/base/io/smallrye/metrics/main/module.xml
  galleon-pack/pom.xml
  microprofile/metrics-smallrye/pom.xml
  microprofile/metrics-smallrye/src/main/java/org/wildfly/extension/microprofile/metrics/MetricsContextService.java
  microprofile/metrics-smallrye/src/main/resources/io/smallrye/metrics/base-metrics.properties
  pom.xml
  testsuite/integration/basic/src/test/java/org/wildfly/test/integration/microprofile/metrics/MetricsHelper.java
  testsuite/integration/basic/src/test/java/org/wildfly/test/integration/microprofile/metrics/application/MicroProfileMetricsApplicationTestCase.java
  testsuite/integration/basic/src/test/java/org/wildfly/test/integration/microprofile/metrics/application/resource/ResourceSimple.java
  testsuite/integration/basic/src/test/java/org/wildfly/test/integration/microprofile/metrics/metadata/MicroProfileMetricsMetadataTestCase.java
  testsuite/integration/basic/src/test/java/org/wildfly/test/integration/microprofile/metrics/metadata/resources/MicroProfileMetricsCounterResource.java
  testsuite/integration/basic/src/test/java/org/wildfly/test/integration/microprofile/metrics/metadata/resources/MicroProfileMetricsHistogramResource.java
  testsuite/integration/basic/src/test/java/org/wildfly/test/integration/microprofile/metrics/secured/MicroProfileMetricsSecuredEndpointTestCase.java
  testsuite/integration/microprofile-tck/metrics/pom.xml
  testsuite/integration/microprofile-tck/metrics/src/test/resources/arquillian.xml
  testsuite/integration/microprofile-tck/pom.xml
Labels: Feature, deps-changed

#12497 [WFLY-12373] Avoided contended reads of MSC Supplier instances
  weld/common/src/main/java/org/jboss/as/weld/interceptors/Jsr299BindingsInterceptor.java
  weld/subsystem/src/main/java/org/jboss/as/weld/deployment/WeldClassIntrospector.java
  weld/subsystem/src/main/java/org/jboss/as/weld/interceptors/Jsr299BindingsCreateInterceptor.java
  weld/subsystem/src/main/java/org/jboss/as/weld/services/bootstrap/WeldSecurityServices.java
Labels: deps-ok, ready-for-merge

#12501 [WFLY-12378] Upgrade jboss-ejb-client to 4.0.23.Final
  pom.xml
Labels: deps-ok

#12469 [WFLY-12346] Adding test to test adding an Elytron jdbc-realm in admin only mode
  testsuite/integration/elytron/src/test/java/org/wildfly/test/integration/elytron/realm/JDBCRealmAdminOnlyModeTestCase.java
Labels: deps-ok

#12503 WFLY-12233 Upgrade Hibernate ORM from 5.3.10 to 5.3.11
  pom.xml
Labels: deps-ok

#12502 WFLY-12380 Fix org.wildfly.clustering.service.ServiceSupplier usage
  clustering/common/src/main/java/org/jboss/as/clustering/controller/Operation.java
  clustering/infinispan/extension/src/main/java/org/jboss/as/clustering/infinispan/subsystem/BackupOperationExecutor.java
  clustering/infinispan/extension/src/main/java/org/jboss/as/clustering/infinispan/subsystem/CacheContainerMetricExecutor.java
  clustering/infinispan/extension/src/main/java/org/jboss/as/clustering/infinispan/subsystem/CacheMetricExecutor.java
  clustering/infinispan/extension/src/main/java/org/jboss/as/clustering/infinispan/subsystem/ClusteredCacheMetricExecutor.java
  clustering/infinispan/extension/src/main/java/org/jboss/as/clustering/infinispan/subsystem/EvictionMetricExecutor.java
  clustering/infinispan/extension/src/main/java/org/jboss/as/clustering/infinispan/subsystem/LockingMetricExecutor.java
  clustering/infinispan/extension/src/main/java/org/jboss/as/clustering/infinispan/subsystem/PartitionHandlingMetricExecutor.java
  clustering/infinispan/extension/src/main/java/org/jboss/as/clustering/infinispan/subsystem/PartitionHandlingOperationExecutor.java
  clustering/infinispan/extension/src/main/java/org/jboss/as/clustering/infinispan/subsystem/StoreMetricExecutor.java
  clustering/infinispan/extension/src/main/java/org/jboss/as/clustering/infinispan/subsystem/TransactionMetricExecutor.java
  clustering/jgroups/extension/src/main/java/org/jboss/as/clustering/jgroups/subsystem/ChannelMetricExecutor.java
  clustering/jgroups/extension/src/main/java/org/jboss/as/clustering/jgroups/subsystem/ChannelRuntimeResourceRegistration.java
  clustering/jgroups/extension/src/main/java/org/jboss/as/clustering/jgroups/subsystem/ForkProtocolRuntimeResourceRegistration.java
  clustering/service/src/main/java/org/wildfly/clustering/service/ActiveServiceSupplier.java
  clustering/service/src/main/java/org/wildfly/clustering/service/PassiveServiceSupplier.java
  mod_cluster/extension/src/main/java/org/wildfly/extension/mod_cluster/LegacyProxyOperation.java
  mod_cluster/extension/src/main/java/org/wildfly/extension/mod_cluster/ModClusterSubsystemServiceHandler.java
  mod_cluster/extension/src/main/java/org/wildfly/extension/mod_cluster/ProxyOperationExecutor.java
Labels: deps-ok, ready-for-merge

#12480 [WFLY-12317][JBEAP-17293] changing of txn subsystem node identifier requires JVM restart
  transactions/src/main/java/org/jboss/as/txn/subsystem/TransactionExtension.java
  transactions/src/main/java/org/jboss/as/txn/subsystem/TransactionSubsystemRootResourceDefinition.java
  transactions/src/main/java/org/jboss/as/txn/subsystem/TransactionTransformers.java
  transactions/src/main/resources/schema/wildfly-txn_5_0.xsd
  transactions/src/test/java/org/jboss/as/txn/subsystem/TransactionSubsystemTestCase.java
  transactions/src/test/resources/org/jboss/as/txn/subsystem/full-5.0.0.xml
Labels: deps-ok

#12420 [WFLY-12184] http transaction provider itegrated with WFTC
  feature-pack/src/main/resources/modules/system/layers/base/org/wildfly/transaction/client/main/module.xml
  testsuite/integration/multinode/src/test/java/org/jboss/as/test/multinode/transaction/nooutbound/ClientStatelessBean.java
  testsuite/integration/multinode/src/test/java/org/jboss/as/test/multinode/transaction/nooutbound/ProviderUrlData.java
  testsuite/integration/multinode/src/test/java/org/jboss/as/test/multinode/transaction/nooutbound/ServerMandatoryStatelessBean.java
  testsuite/integration/multinode/src/test/java/org/jboss/as/test/multinode/transaction/nooutbound/ServerNeverStatelessBean.java
  testsuite/integration/multinode/src/test/java/org/jboss/as/test/multinode/transaction/nooutbound/ServerStatelessRemote.java
  testsuite/integration/multinode/src/test/java/org/jboss/as/test/multinode/transaction/nooutbound/TransactionContextRemoteCallTestCase.java
Labels: deps-ok, ready-for-merge

#12460 WFLY-12265 Warning when singleton EJB implements SessionBean interface
  ejb3/src/main/java/org/jboss/as/ejb3/deployment/processors/SessionBeanComponentDescriptionFactory.java
  ejb3/src/main/java/org/jboss/as/ejb3/logging/EjbLogger.java
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/ejb/singleton/sessionbean/SingletonImplementingSessionBeanTestCase.java
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/ejb/singleton/sessionbean/SingletonSessionBean.java
Labels: deps-ok, ready-for-merge

#12505 [WFLY-12391] enable running XTS txbridge tests by default
  testsuite/integration/xts/pom.xml
  testsuite/integration/xts/src/test/java/org/jboss/as/test/txbridge/fromjta/BridgeFromJTATestCase.java
Labels: deps-ok

#12452 [WFLY-11293]: Add attribute to model which will indicate that backup is synchronized with live server.
  messaging-activemq/src/main/java/org/wildfly/extension/messaging/activemq/ServerDefinition.java
  messaging-activemq/src/main/java/org/wildfly/extension/messaging/activemq/ha/HAPolicySynchronizationStatusReadHandler.java
  messaging-activemq/src/main/java/org/wildfly/extension/messaging/activemq/ha/ReplicationMasterDefinition.java
  messaging-activemq/src/main/java/org/wildfly/extension/messaging/activemq/ha/ReplicationSlaveDefinition.java
  messaging-activemq/src/main/resources/org/wildfly/extension/messaging/activemq/LocalDescriptions.properties
  testsuite/integration/manualmode/keystores-workdir/client.crt
  testsuite/integration/manualmode/keystores-workdir/client.keystore
  testsuite/integration/manualmode/keystores-workdir/client.truststore
  testsuite/integration/manualmode/keystores-workdir/server.crt
  testsuite/integration/manualmode/keystores-workdir/server.keystore
  testsuite/integration/manualmode/keystores-workdir/server.truststore
  testsuite/integration/manualmode/keystores-workdir/untrusted.crt
  testsuite/integration/manualmode/keystores-workdir/untrusted.keystore
  testsuite/integration/manualmode/pom.xml
  testsuite/integration/manualmode/src/test/config/arq/arquillian.xml
  testsuite/integration/manualmode/src/test/java/org/jboss/as/test/manualmode/messaging/ha/AbstractMessagingHATestCase.java
  testsuite/integration/manualmode/src/test/java/org/jboss/as/test/manualmode/messaging/ha/FailoverTestCase.java
  testsuite/integration/manualmode/src/test/java/org/jboss/as/test/manualmode/messaging/ha/ReplicatedFailoverTestCase.java
  testsuite/integration/manualmode/src/test/java/org/jboss/as/test/manualmode/messaging/ha/SharedStoreFailoverTestCase.java
Labels: Feature, deps-ok, missing-reqs

#12511 Fix for WFLY-12299, More fine grain dependency for galleon basic layers
  docs/src/main/asciidoc/_admin-guide/Galleon_provisioning.adoc
  galleon-pack/src/main/resources/layers/standalone/cdi/layer-spec.xml
  galleon-pack/src/main/resources/layers/standalone/cloud-profile/layer-spec.xml
  galleon-pack/src/main/resources/layers/standalone/jms-activemq/layer-spec.xml
  galleon-pack/src/main/resources/layers/standalone/jpa/layer-spec.xml
  galleon-pack/src/main/resources/layers/standalone/observability/layer-spec.xml
  galleon-pack/src/main/resources/layers/standalone/resource-adapters/layer-spec.xml
Labels: deps-ok, ready-for-merge

#12523 WFLY-12422 Upgrade Narayana to 5.9.7.Final
  pom.xml
Labels: deps-ok

#12284 WFLY-12150: make attributes with default values optional
  ejb3/src/main/java/org/jboss/as/ejb3/subsystem/deployment/MessageDrivenBeanResourceDefinition.java
  legacy/messaging/src/main/java/org/jboss/as/messaging/InVMTransportDefinition.java
  legacy/messaging/src/main/java/org/jboss/as/messaging/MigrateOperation.java
  legacy/messaging/src/main/java/org/jboss/as/messaging/SecurityRoleDefinition.java
  transactions/src/main/java/org/jboss/as/txn/subsystem/TransactionSubsystemRootResourceDefinition.java
Labels: deps-ok, ready-for-merge

#12499 [WFLY-12243]: Monitor resource adapter thread pools.
  messaging-activemq/src/main/java/org/wildfly/extension/messaging/activemq/MessagingSubsystemRootResourceDefinition.java
  messaging-activemq/src/main/resources/org/wildfly/extension/messaging/activemq/LocalDescriptions.properties
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/messaging/mgmt/metrics/JMSThreadPoolMetricsMDB.java
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/messaging/mgmt/metrics/JMSThreadPoolMetricsSetup.java
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/messaging/mgmt/metrics/JMSThreadPoolMetricsUtil.java
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/messaging/mgmt/metrics/ScheduledThreadPoolMetricsTestCase.java
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/messaging/mgmt/metrics/ThreadPoolMetricsTestCase.java
Labels: Feature, deps-ok, ready-for-merge

#12513 WFLY-12405 Reduce distributed web session expiration scheduler payload
  clustering/web/infinispan/src/main/java/org/wildfly/clustering/web/infinispan/session/CancelSchedulerCommand.java
  clustering/web/infinispan/src/main/java/org/wildfly/clustering/web/infinispan/session/InfinispanSessionManagerFactory.java
  clustering/web/infinispan/src/main/java/org/wildfly/clustering/web/infinispan/session/PrimaryOwnerScheduler.java
  clustering/web/infinispan/src/main/java/org/wildfly/clustering/web/infinispan/session/ScheduleSchedulerCommand.java
  clustering/web/infinispan/src/main/java/org/wildfly/clustering/web/infinispan/session/Scheduler.java
  clustering/web/infinispan/src/main/java/org/wildfly/clustering/web/infinispan/session/SessionExpirationScheduler.java
  clustering/web/infinispan/src/test/java/org/wildfly/clustering/web/infinispan/session/SessionExpirationSchedulerTestCase.java
Labels: deps-ok, ready-for-merge

#12516 [WFLY-12397] Avoid creating WebResourcePermission with an action of "!".
  undertow/src/main/java/org/wildfly/extension/undertow/security/jacc/WarJACCService.java
Labels: deps-ok, ready-for-merge

#12518 WFLY-12414 Merged/Killed member handling in CacheRegistry triggers intermittent failures during server startup
  clustering/server/src/main/java/org/wildfly/clustering/server/registry/CacheRegistry.java
Labels: deps-ok, ready-for-merge

#12522 [WFLY-12421] Use maven project.groupId for wildfly-client-all depende…
  testsuite/integration/manualmode/pom.xml
Labels: deps-ok, ready-for-merge

#12524 WFLY-12399: Upgrade HAL to 3.2.1.Final
  pom.xml
Labels: deps-ok

#12526 Remove duplicate dependency declaration to fix maven warning
  testsuite/integration/basic/pom.xml
Labels: deps-ok

#12528 [WFLY-12428] Upgrade WildFly Core to 10.0.0.Beta4
  pom.xml
Labels: deps-ok

#12551 WFLY-12448 Upgrade boss-transaction-api_1.2_spec to 2.0.0.CR1
  pom.xml
Labels: deps-changed

#12559 [WFLY-12455] Update permission names in tests to fix failures that occur with the security manager enabled with the JBoss Jakarta JACC and JASPI upgrades
  pom.xml
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/security/jacc/context/PolicyContextTestCase.java
  testsuite/integration/elytron/src/test/java/org/wildfly/test/integration/elytron/jaspi/JaspiTestBase.java
  testsuite/integration/ws/src/test/java/org/jboss/as/test/integration/ws/authentication/policy/AuthenticationPolicyContextTestCase.java
Labels: deps-ok

#12554 [WFLY-12450] Upgrade jboss-jms-api_2.0_spec from 1.0.2.Final to 2.0.0…
  pom.xml
Labels: deps-changed

#12553 [WFLY-12449] Update jboss-jakarta-ejb-api_spec to 2.0.0.CR2
  pom.xml
Labels: deps-changed

#12548 [WFLY-12441]Upgrade jboss-jaxb-api_2.3_spec from 1.0.1.Final to 2.0.0…
  pom.xml
Labels: deps-changed

#12544 [WFLY-12437] Upgrade org.jboss.spec.javax.servlet.jboss-servlet-api_4…
  pom.xml
Labels: deps-changed

#12422 [WFLY-12275] Add documentation for the enhanced audit logging - RFC support and Configuring Reconnects
  docs/src/main/asciidoc/_elytron/Audit.adoc
Labels: Feature-Docs, core-upgrade-needed, deps-ok, ready-for-merge

#12537 WFLY-12434 Upgrade jboss-jakarta-connector-api_spec to 2.0.0.Final
  feature-pack/pom.xml
  galleon-pack/pom.xml
  pom.xml
Labels: deps-changed, ready-for-merge

#12557 [WFLY-12453] Update wildfly-transaction-client to 1.1.7.Final
  pom.xml
Labels: deps-ok, ready-for-merge

#12560 [WFLY-12456] Use a different package for the tests in dist-legacy
  dist-legacy/src/test/java/org/wildfly/dist/legacy/subsystem/xml/AbstractValidationUnitTest.java
  dist-legacy/src/test/java/org/wildfly/dist/legacy/subsystem/xml/StandardConfigsXMLValidationUnitTestCase.java
  dist-legacy/src/test/java/org/wildfly/dist/legacy/subsystem/xml/XSDValidationUnitTestCase.java
Labels: deps-ok, ready-for-merge

#12545 [WFLY-12438] Upgrade org.jboss.spec.javax.websockets to 2.0.0.CR1
  pom.xml
Labels: deps-changed, ready-for-merge

#11921 [WFCORE-4227] Add documentation about the ability of the CLI SSL securi…
  docs/src/main/asciidoc/_admin-guide/CLI_Recipes.adoc
Labels: Feature-Docs, core-upgrade-needed

#12509 [WFCORE-4336] Add documentation for the filter resource. Move the cur…
  docs/src/main/asciidoc/_admin-guide/subsystem-configuration/Logging.adoc
  docs/src/main/asciidoc/_admin-guide/subsystem-configuration/Logging_Filters.adoc
Labels: Feature-Docs, core-upgrade-needed, deps-ok

#12563 [WFLY-12447] Removing generated keystore files from source control
  testsuite/integration/manualmode/keystores-workdir/client.crt
  testsuite/integration/manualmode/keystores-workdir/client.keystore
  testsuite/integration/manualmode/keystores-workdir/client.truststore
  testsuite/integration/manualmode/keystores-workdir/server.crt
  testsuite/integration/manualmode/keystores-workdir/server.keystore
  testsuite/integration/manualmode/keystores-workdir/server.truststore
  testsuite/integration/manualmode/keystores-workdir/untrusted.crt
  testsuite/integration/manualmode/keystores-workdir/untrusted.keystore
  testsuite/integration/manualmode/src/test/java/org/jboss/as/test/manualmode/web/ssl/AbstractCertificateLoginModuleTestCase.java
Labels: deps-ok

#12566 Bulk upgrades
  ejb3/pom.xml
  ejb3/src/test/java/org/jboss/as/ejb3/subsystem/Ejb3TransformersTestCase.java
  feature-pack/pom.xml
  feature-pack/src/license/full-feature-pack-licenses.xml
  galleon-pack/pom.xml
  pom.xml
Labels: deps-changed

#12550 [WFLY-12443]:Upgrade jboss-jaxrpc-api_1.1_spec from 1.0.2.Final to 2.…
  pom.xml
Labels: deps-changed
