Repository wildfly/wildfly, pull requests merged in 2019-06, with the labels that each got.

#12335 [WFLY-12153] Replace redundant StringBuilder append String.subString with append CharSequence
  connector/src/main/java/org/jboss/as/connector/services/resourceadapters/deployment/JBossLogPrintWriter.java
  iiop-openjdk/src/main/java/org/wildfly/iiop/openjdk/rmi/ContainerAnalysis.java
  legacy/web/src/main/java/org/jboss/as/web/WebMigrateOperation.java
  testsuite/domain/src/test/java/org/jboss/as/test/integration/domain/BuildConfigurationTestBase.java
  testsuite/mixed-domain/src/test/java/org/jboss/as/test/integration/domain/mixed/LegacySubsystemConfigurationUtil.java
  testsuite/shared/src/main/java/org/jboss/as/test/shared/PropertiesValueResolver.java
Labels: ready-for-merge

#12334 [WFLY-12152] Remove redundant subString endIndex .length() calls
  appclient/src/main/java/org/jboss/as/appclient/subsystem/Main.java
  ee/src/main/java/org/jboss/as/ee/resource/definition/ResourceDefinitionInjectionSource.java
  ee/src/main/java/org/jboss/as/ee/utils/DescriptorUtils.java
  naming/src/main/java/org/wildfly/naming/java/permission/JndiPermission.java
  testsuite/integration/web/src/test/java/org/jboss/as/test/integration/web/handlers/RequestDumpingHandlerTestImpl.java
Labels: ready-for-merge

#12333 [WFLY-11109] Fix the log pattern host documentation to reflect the co…
  docs/src/main/asciidoc/_admin-guide/subsystem-configuration/Logging_Formatters.adoc
Labels: deps-ok, ready-for-merge

#12332 [WFLY-12147] Update MinimalWebAuthenticationTestCase so that it doesn't use an authentication factory as specified in the test description
  testsuite/integration/elytron/src/test/java/org/wildfly/test/integration/elytron/web/MinimalWebAuthenticationTestCase.java
Labels: deps-ok, ready-for-merge

#12329 [WFLY-12140]Set bridgeName while creating JMSBridge on server
  messaging-activemq/src/main/java/org/wildfly/extension/messaging/activemq/jms/bridge/JMSBridgeAdd.java
Labels: deps-ok, ready-for-merge

#12312 [WFLY-12090] At TransactionSubsystemAdd, make RemoteTransactionServic…
  transactions/src/main/java/org/jboss/as/txn/subsystem/TransactionSubsystemAdd.java
Labels: deps-ok, ready-for-merge

#12295 WFLY-12071: use management name for deployment address
  microprofile/metrics-smallrye/src/main/java/org/wildfly/extension/microprofile/metrics/deployment/DeploymentMetricService.java
  testsuite/integration/basic/src/test/java/org/wildfly/test/integration/microprofile/metrics/application/MicroProfileMetricsDifferentRuntimeNameTestCase.java
Labels: deps-ok, ready-for-merge

#12287 WFLY-12032 EJB subsystem doesn't set TCCL when deserializing request
  ejb3/src/main/java/org/jboss/as/ejb3/remote/AssociationImpl.java
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/ejb/remote/requestdeserialization/HelloBean.java
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/ejb/remote/requestdeserialization/HelloRemote.java
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/ejb/remote/requestdeserialization/Request.java
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/ejb/remote/requestdeserialization/RequestDeserializationTestCase.java
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/ejb/remote/requestdeserialization/Response.java
Labels: deps-ok

#12341 [WFLY-12168] Upgrade wildfly-core from 9.0.0.Beta7 to 9.0.0.Final
  pom.xml
Labels: deps-ok

#12338 WFLY-12161 Expressions not working in XA DS attr share-prepared-state…
  connector/src/main/java/org/jboss/as/connector/subsystems/datasources/DataSourceModelNodeUtil.java
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/management/cli/DataSourceTestCase.java
Labels: deps-ok

#12231 WFLY-11991 Applications that extend certain Hibernate classes should be updated to use type SharedSessionContractImplementor instead of SessionImplementor
  docs/src/main/asciidoc/_developer-guide/JPA_Reference_Guide.adoc
  jpa/hibernate-transformer/src/main/java/org/jboss/as/hibernate/Hibernate51CompatibilityTransformer.java
  jpa/hibernate-transformer/src/main/java/org/jboss/as/hibernate/MethodAdapter.java
  testsuite/compat/src/test/java/org/jboss/as/test/compat/jpa/hibernate/transformer/AbstractVerifyHibernate51CompatibilityTestCase.java
  testsuite/compat/src/test/java/org/jboss/as/test/compat/jpa/hibernate/transformer/StateType.java
  testsuite/compat/src/test/java/org/jboss/as/test/compat/jpa/hibernate/transformer/VerifyHibernate51CompatibilityJDSEnabledTransformerTestCase.java
  testsuite/compat/src/test/java/org/jboss/as/test/compat/jpa/hibernate/transformer/VerifyHibernate51CompatibilityPropertyAndJDSEnabledTransformerTestCase.java
Labels: deps-ok

#12342 WFLY-12169 Remove use of deprecated ServiceBuilder.addAliases(...) within Infinispan subsystem
  clustering/infinispan/extension/src/main/java/org/jboss/as/clustering/infinispan/subsystem/CacheContainerServiceConfigurator.java
Labels: deps-ok

#12337 [WFLY-12160] Upgrade jboss-common-beans to 2.0.1.Final
  pom.xml
Labels: deps-ok

#12348 [WFLY-12174]: Configure internal broker not to check for configuration changes.
  messaging-activemq/src/main/java/org/wildfly/extension/messaging/activemq/ServerAdd.java
Labels: deps-ok, ready-for-merge

#12344 [WFLY-12172] Add file permissions for EJB client tests
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/ejb/client/descriptor/EJBClientDescriptorTestCase.java
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/ejb/security/runas/propagation/RunAsWithElytronEJBContextPropagationTestCase.java
  testsuite/integration/manualmode/src/test/java/org/jboss/as/test/manualmode/ejb/client/outbound/connection/RemoteOutboundConnectionReconnectTestCase.java
  testsuite/integration/manualmode/src/test/java/org/jboss/as/test/manualmode/ejb/client/outbound/connection/security/ElytronRemoteOutboundConnectionTestCase.java
  testsuite/integration/multinode/src/test/java/org/jboss/as/test/multinode/remotecall/RemoteLocalCallProfileTestCase.java
  testsuite/integration/multinode/src/test/java/org/jboss/as/test/multinode/remotecall/RemoteLocalCallTestCase.java
  testsuite/integration/multinode/src/test/java/org/jboss/as/test/multinode/transaction/TransactionInvocationTestCase.java
  testsuite/integration/multinode/src/test/java/org/jboss/as/test/multinode/transaction/async/TransactionPropagationTestCase.java
  testsuite/shared/src/main/java/org/jboss/as/test/shared/integration/ejb/security/PermissionUtils.java
Labels: deps-ok, ready-for-merge

#12345 [WFLY-11768] Upgrade Jaeger client to 0.34.0 and libthrift to 0.12.0
  pom.xml
Labels: deps-ok

#12349 WFLY-12167 Don't return from ServiceSupplier.get() until one-time service is removed.
  clustering/service/src/main/java/org/wildfly/clustering/service/ServiceSupplier.java
Labels: deps-ok

#12350 [WFLY-12176] Upgrade WildFly Core to 9.0.1.Final
  pom.xml
Labels: deps-ok

#12359 WFLY-11890 Upgrade JGroups to 4.1.1.Final
  clustering/jgroups/extension/src/main/java/org/jboss/as/clustering/jgroups/auth/BinaryAuthToken.java
  clustering/jgroups/extension/src/main/java/org/jboss/as/clustering/jgroups/logging/JGroupsLogger.java
  clustering/jgroups/extension/src/main/java/org/jboss/as/clustering/jgroups/subsystem/AbstractProtocolConfigurationServiceConfigurator.java
  clustering/jgroups/extension/src/main/java/org/jboss/as/clustering/jgroups/subsystem/ProtocolDefaultsServiceConfigurator.java
  clustering/server/src/main/java/org/wildfly/clustering/server/dispatcher/ChannelCommandDispatcherFactory.java
  clustering/server/src/main/java/org/wildfly/clustering/server/dispatcher/CommandResponseMarshaller.java
  clustering/server/src/main/java/org/wildfly/clustering/server/group/AddressSerializer.java
  connector/pom.xml
  pom.xml
Labels: deps-ok

#12357 WFLY-12181 Remove obsolete classes
  clustering/infinispan/client/src/main/java/org/wildfly/clustering/infinispan/client/manager/RemoteCacheManager.java
  clustering/infinispan/extension/src/main/java/org/jboss/as/clustering/infinispan/subsystem/remote/RemoteCacheContainerServiceConfigurator.java
  clustering/web/hotrod/src/main/java/org/wildfly/clustering/web/hotrod/HotRodMarshaller.java
  clustering/web/hotrod/src/main/java/org/wildfly/clustering/web/hotrod/RemoteCacheContainerConfiguration.java
  clustering/web/hotrod/src/main/java/org/wildfly/clustering/web/hotrod/RemoteCacheContainerFactory.java
Labels: deps-ok

#12356 [WFLY-12180] no NPE on registering synchronization on no active transaction
  transactions/src/main/java/org/jboss/as/txn/logging/TransactionLogger.java
  transactions/src/main/java/org/jboss/as/txn/service/internal/tsr/TransactionSynchronizationRegistryWrapper.java
Labels: deps-ok

#12353 [WFLY-12179] Update the AggregateRealmTestCase to use ConfigurableElement definitions.
  testsuite/integration/elytron/src/test/java/org/wildfly/test/integration/elytron/realm/AggregateRealmTestCase.java
  testsuite/integration/elytron/src/test/java/org/wildfly/test/integration/elytron/ssl/UndertowSslSecurityDomainTestCase.java
  testsuite/integration/web/src/test/java/org/jboss/as/test/integration/web/security/WebSecurityCommon.java
  testsuite/integration/web/src/test/java/org/jboss/as/test/integration/web/security/WebSimpleRoleMappingSecurityDomainSetup.java
  testsuite/integration/web/src/test/java/org/jboss/as/test/integration/web/security/WebTestsSecurityDomainSetup.java
  testsuite/integration/web/src/test/java/org/jboss/as/test/integration/web/security/cert/WebCERTTestsElytronSetup.java
  testsuite/integration/web/src/test/java/org/jboss/as/test/integration/web/security/digest/WebSecurityDigestSecurityDomainSetup.java
  testsuite/integration/web/src/test/java/org/jboss/as/test/integration/web/security/jaspi/WebJaspiTestsSecurityDomainSetup.java
  testsuite/shared/src/main/java/org/wildfly/test/security/common/elytron/AbstractUserAttributeValuesCapableElement.java
  testsuite/shared/src/main/java/org/wildfly/test/security/common/elytron/AggregateSecurityRealm.java
  testsuite/shared/src/main/java/org/wildfly/test/security/common/elytron/FileSystemRealm.java
  testsuite/shared/src/main/java/org/wildfly/test/security/common/elytron/PropertiesRealm.java
  testsuite/shared/src/main/java/org/wildfly/test/security/common/elytron/PropertyFileAuthzBasedDomain.java
  testsuite/shared/src/main/java/org/wildfly/test/security/common/elytron/PropertyFileBasedDomain.java
  testsuite/shared/src/main/java/org/wildfly/test/security/common/elytron/UserWithAttributeValues.java
  testsuite/shared/src/main/java/org/wildfly/test/security/common/elytron/UsersAttributeValuesCapableElement.java
Labels: deps-ok

#12340 [WFLY-12162] Upgrading Naming Client to 1.0.11.Final.
  pom.xml
Labels: 18.x, deps-ok

#12355 [WFLY-11674] JTA documentation to be enriched with a section about synchronization
  docs/src/main/asciidoc/_developer-guide/JTA_Reference.adoc
Labels: deps-ok

#12367 [WFLY-11759] Exclude problematic Undertow interfaces from ServiceLoader calls when testing management model transformation
  undertow/src/test/java/org/wildfly/extension/undertow/UndertowTransformersTestCase.java
  undertow/src/test/resources/org/wildfly/extension/undertow/undertow-7.1-transformers.xml
Labels: deps-ok

#12363 [WFLY-11759] Revert UndertowTransformersTestCase workaround
  undertow/src/test/java/org/wildfly/extension/undertow/UndertowTransformersTestCase.java
  undertow/src/test/resources/org/wildfly/extension/undertow/undertow-7.1-transformers.xml
Labels: deps-ok

#12365 [WFLY-12204] Update wildfly-transaction-client to 1.1.4.Final
  pom.xml
Labels: deps-ok, ready-for-merge

#12360 [WFLY-11925] Add documentation on the attributes that can be specified when configuring server and client SSLContexts
  docs/src/main/asciidoc/_elytron/Using_the_Elytron_Subsystem.adoc
Labels: deps-ok, ready-for-merge

#12336 WFLY-11983 Unify line-endings of bat scripts (regression against WF15)
  .gitattributes
Labels: deps-ok, ready-for-merge

#12374 WFLY-12208 Upgrade Infinispan to 9.4.15.Final
  pom.xml
Labels: deps-ok

#12216 [WFLY-11958] Eliminating deprecated DeploymentPhaseContext methods usages
  ee/src/main/java/org/jboss/as/ee/component/NamespaceConfigurator.java
  ee/src/main/java/org/jboss/as/ee/naming/InjectedEENamespaceContextSelector.java
  ee/src/main/java/org/jboss/as/ee/naming/ModuleContextProcessor.java
  transactions/src/main/java/org/jboss/as/txn/ee/concurrency/EEConcurrencyContextHandleFactoryProcessor.java
  transactions/src/main/java/org/jboss/as/txn/ee/concurrency/TransactionLeakContextHandleFactory.java
Labels: 18.x

#12358 WFLY-10872 Confusing error message when writing simple-load-provider …
  mod_cluster/extension/src/main/java/org/wildfly/extension/mod_cluster/ModClusterLogger.java
  mod_cluster/extension/src/main/java/org/wildfly/extension/mod_cluster/ProxyConfigurationResourceDefinition.java
  mod_cluster/extension/src/test/java/org/wildfly/extension/mod_cluster/ModClusterOperationsTestCase.java
Labels: deps-ok

#12179 [WFLY-6684]: JMS Bridge should display statistics about messages that have been processed.
  docs/src/main/asciidoc/_admin-guide/subsystem-configuration/Messaging.adoc
  messaging-activemq/src/main/java/org/wildfly/extension/messaging/activemq/jms/bridge/JMSBridgeDefinition.java
  messaging-activemq/src/main/java/org/wildfly/extension/messaging/activemq/jms/bridge/JMSBridgeHandler.java
  messaging-activemq/src/main/resources/org/wildfly/extension/messaging/activemq/LocalDescriptions.properties
  testsuite/integration/smoke/src/test/java/org/jboss/as/test/smoke/jms/JMSBridgeTest.java
Labels: Feature, deps-ok, ready-for-merge

#12379 [WFLY-11759] At undertow-7.1-transformres.xml, remove commented line …
  undertow/src/test/resources/org/wildfly/extension/undertow/undertow-7.1-transformers.xml
Labels: deps-ok

#12376 [WFLY-12213] Upgrade smallrye-config 1.3.6
  pom.xml
Labels: deps-ok, ready-for-merge

#12384 [WFLY-12235] Upgrade to jboss-jaxrs-api_2.1_spec 1.0.3.Final
  pom.xml
Labels: deps-ok

#12390 WFLY-12242 Default VERIFY_SUSPECT timeout is too high
  clustering/jgroups/extension/src/main/resources/jgroups-defaults.xml
Labels: deps-ok

#12389 WFLY-12212 Restore LastNodeToLeaveRemoteEJBTestCase
  testsuite/integration/clustering/pom.xml
  testsuite/integration/clustering/src/test/config/arq/arquillian-byteman.xml
  testsuite/integration/clustering/src/test/java/org/jboss/as/test/clustering/NodeUtil.java
  testsuite/integration/clustering/src/test/java/org/jboss/as/test/clustering/cluster/AbstractClusteringTestCase.java
  testsuite/integration/clustering/src/test/java/org/jboss/as/test/clustering/cluster/ejb/remote/byteman/LastNodeToLeaveRemoteEJBTestCase.java
  testsuite/integration/clustering/src/test/java/org/jboss/as/test/clustering/cluster/ejb/remote/byteman/LastNodeToLeaveTestHelper.java
  testsuite/pom.xml
Labels: deps-ok, ready-for-merge

#12380 [WFLY-12219] Disabling SSL failing tests for now on JDK13+
  testsuite/integration/manualmode/src/test/java/org/jboss/as/test/manualmode/web/ssl/CertificateRolesLoginModuleTestCase.java
  testsuite/integration/manualmode/src/test/java/org/jboss/as/test/manualmode/web/ssl/DatabaseCertLoginModuleTestCase.java
  testsuite/integration/manualmode/src/test/java/org/jboss/as/test/manualmode/web/ssl/HTTPSWebConnectorTestCase.java
Labels: deps-ok, ready-for-merge

#12383 WFLY-12232 Fix FD_SOCK socket binding name/stack mismatch in legacy b…
  clustering/jgroups/extension/src/main/resources/subsystem-templates/jgroups.xml
Labels: deps-ok

#12362 [WFLY-12189] Add MicroProfile Config TCK
  pom.xml
  testsuite/domain/pom.xml
  testsuite/integration/basic/pom.xml
  testsuite/integration/clustering/pom.xml
  testsuite/integration/elytron/pom.xml
  testsuite/integration/iiop/pom.xml
  testsuite/integration/legacy-ejb-client/pom.xml
  testsuite/integration/legacy/pom.xml
  testsuite/integration/manualmode/pom.xml
  testsuite/integration/microprofile-tck/config/pom.xml
  testsuite/integration/microprofile-tck/config/src/test/java/org/wildfly/extension/microprofile/config/test/DeploymentProcessor.java
  testsuite/integration/microprofile-tck/config/src/test/java/org/wildfly/extension/microprofile/config/test/WildFlyArquillianExtension.java
  testsuite/integration/microprofile-tck/config/src/test/resources/META-INF/services/org.jboss.arquillian.core.spi.LoadableExtension
  testsuite/integration/microprofile-tck/config/src/test/resources/arquillian.xml
  testsuite/integration/microprofile-tck/config/tck-suite.xml
  testsuite/integration/microprofile-tck/pom.xml
  testsuite/integration/multinode/pom.xml
  testsuite/integration/picketlink/pom.xml
  testsuite/integration/pom.xml
  testsuite/integration/rbac/pom.xml
  testsuite/integration/rts/pom.xml
  testsuite/integration/secman/pom.xml
  testsuite/integration/smoke/pom.xml
  testsuite/integration/vdx/pom.xml
  testsuite/integration/web/pom.xml
  testsuite/integration/ws/pom.xml
  testsuite/integration/xts/pom.xml
  testsuite/mixed-domain/pom.xml
  testsuite/shared/pom.xml
Labels: deps-ok

#12375 [WFLY-12200][WFLY-12201] Update jboss-ejb-client and ExceptionEjbClientTestCase
  pom.xml
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/ejb/stateful/exception/ExceptionEjbClientTestCase.java
Labels: deps-ok, ready-for-merge

#12368 [JBEAP-16664][WFLY-10808] - test local-receiver-pass-by-value(or said…
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/ejb/client/descriptor/passbyvalue/ClientPassByValueTestServlet.java
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/ejb/client/descriptor/passbyvalue/DummySerializableObject.java
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/ejb/client/descriptor/passbyvalue/PassValueTypeTestCase.java
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/ejb/client/descriptor/passbyvalue/TestEJB.java
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/ejb/client/descriptor/passbyvalue/TestEJBRemote.java
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/ejb/client/descriptor/passbyvalue/jboss-ejb-client.xml
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/ejb/client/descriptor/passbyvalue/web.xml
Labels: deps-ok, ready-for-merge

#12394 WFLY-12247, WFLY-12248 Alignment of clustering configurations
  clustering/web/extension/src/main/java/org/wildfly/extension/clustering/web/DistributableWebXMLParser.java
  galleon-pack/src/main/resources/feature_groups/domain-ec2-full-ha.xml
  galleon-pack/src/main/resources/feature_groups/domain-ec2-ha.xml
  galleon-pack/src/main/resources/feature_groups/standalone-azure-full-ha.xml
  galleon-pack/src/main/resources/feature_groups/standalone-azure-ha.xml
  galleon-pack/src/main/resources/feature_groups/standalone-ec2-full-ha.xml
  galleon-pack/src/main/resources/feature_groups/standalone-ec2-ha.xml
  galleon-pack/src/main/resources/feature_groups/standalone-gossip-ha.xml
Labels: deps-ok

#12393 WFLY-12245 Default routing cache in HA profiles should use replicated-cache
  galleon-pack/src/main/resources/feature_groups/infinispan-dist.xml
Labels: deps-ok

#12386 [WFLY-12236] Turn off the INFO Artemis audit logging.
  messaging-activemq/src/main/java/org/wildfly/extension/messaging/activemq/MessagingExtension.java
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/messaging/mgmt/NoAuditLogTestCase.java
Labels: deps-ok, ready-for-merge

#12395 [WFLY-12236] Turn off the INFO Artemis audit logging.
  messaging-activemq/src/main/java/org/wildfly/extension/messaging/activemq/MessagingExtension.java
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/messaging/mgmt/NoAuditLogTestCase.java
Labels: deps-ok, ready-for-merge

#12400 [WFLY-12193] Upgrade Netty from 4.1.29.Final to 4.1.34.Final
  pom.xml
Labels: deps-ok

#12402 [17.0.x] WFLY-12248 Align jgroups stacks in example configurations with default ha configuration
  galleon-pack/src/main/resources/feature_groups/domain-ec2-full-ha.xml
  galleon-pack/src/main/resources/feature_groups/domain-ec2-ha.xml
  galleon-pack/src/main/resources/feature_groups/standalone-azure-full-ha.xml
  galleon-pack/src/main/resources/feature_groups/standalone-azure-ha.xml
  galleon-pack/src/main/resources/feature_groups/standalone-ec2-full-ha.xml
  galleon-pack/src/main/resources/feature_groups/standalone-ec2-ha.xml
  galleon-pack/src/main/resources/feature_groups/standalone-gossip-ha.xml
Labels: 17.x
