Repository wildfly/wildfly, pull requests merged in 2019-07, with the labels that each got.

#12388 [WFLY-12226] Horrible hack to avoid complaints return type for proper…
  messaging-activemq/src/main/java/org/wildfly/extension/messaging/activemq/ActiveMQResourceAdapter.java
Labels: deps-ok

#12408 [WFLY-12226] Horrible hack to avoid complaints return type for proper…
  messaging-activemq/src/main/java/org/wildfly/extension/messaging/activemq/ActiveMQResourceAdapter.java
Labels: 17.x

#12406 [WFLY-12256] Upgrade WildFly Core 9.0.2.Final
  pom.xml
Labels: 17.x, deps-changed

#12404 [WFLY-12200][WFLY-12201] Update jboss-ejb-client and ExceptionEjbClientTestCase
  pom.xml
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/ejb/stateful/exception/ExceptionEjbClientTestCase.java
Labels: 17.x

#12411 WFLY-12266 Distributed session changes fail to replicate if subsequent request arrives < 1 second after session was created
  clustering/web/cache/src/main/java/org/wildfly/clustering/web/cache/session/SessionAccessMetaDataExternalizer.java
  clustering/web/hotrod/src/main/java/org/wildfly/clustering/web/hotrod/session/HotRodSessionMetaDataFactory.java
  clustering/web/infinispan/src/main/java/org/wildfly/clustering/web/infinispan/session/InfinispanSessionMetaDataFactory.java
  testsuite/integration/clustering/src/test/java/org/jboss/as/test/clustering/cluster/web/AbstractWebFailoverTestCase.java
  testsuite/integration/clustering/src/test/java/org/jboss/as/test/clustering/single/web/SimpleServlet.java
Labels: deps-ok

#12412 [17.0.x] WFLY-12266 Distributed session changes fail to replicate if subsequent request arrives < 1 second after session was created
  clustering/web/cache/src/main/java/org/wildfly/clustering/web/cache/session/SessionAccessMetaDataExternalizer.java
  clustering/web/hotrod/src/main/java/org/wildfly/clustering/web/hotrod/session/HotRodSessionMetaDataFactory.java
  clustering/web/infinispan/src/main/java/org/wildfly/clustering/web/infinispan/session/InfinispanSessionMetaDataFactory.java
  testsuite/integration/clustering/src/test/java/org/jboss/as/test/clustering/cluster/web/AbstractWebFailoverTestCase.java
  testsuite/integration/clustering/src/test/java/org/jboss/as/test/clustering/single/web/SimpleServlet.java
Labels: 17.x

#12415 [WFLY-12264] Upgrade WildFly Core 10.0.0.Beta1
  pom.xml
Labels: deps-changed

#12418 [WFLY-12270] Upgrade wildfly-http-client version to 1.0.16.Final
  pom.xml
Labels: deps-ok

#12262 [WFLY-12044] Add documentation on how to configure certificate author…
  docs/src/main/asciidoc/_elytron/Using_the_Elytron_Subsystem.adoc
Labels: Feature-Docs, deps-ok, ready-for-merge

#12316 [WFLY-12124] SSL certificate revocation list community docs
  docs/src/main/asciidoc/_elytron/Using_the_Elytron_Subsystem.adoc
Labels: 18.x, deps-ok, ready-for-merge

#12317 [WFLY-12123] Support SSL Certificate revocation using OCSP community docs
  docs/src/main/asciidoc/_elytron/Using_the_Elytron_Subsystem.adoc
Labels: 18.x, deps-ok, ready-for-merge

#12352 [WFLY-12133] Add documentation on Elytron evidence decoders
  docs/src/main/asciidoc/_elytron/Custom_Components.adoc
  docs/src/main/asciidoc/_elytron/Elytron_Subsystem.adoc
  docs/src/main/asciidoc/_elytron/Using_the_Elytron_Subsystem.adoc
Labels: Feature, deps-ok, ready-for-merge

#12373 [WFLY-12207] Upgrade RESTEasy 3.7.0.Final -> 3.8.0.Final
  pom.xml
Labels: Feature, deps-ok, ready-for-merge

#12382 [WFLY-12255 ][WFLY-951] adjustment of the fix for expiry scanner definition
  transactions/src/main/java/org/jboss/as/txn/service/ArjunaRecoveryManagerService.java
Labels: deps-ok, ready-for-merge

#12391 WFLY-9631 "Failed to reinstate timer" warning is shown when creating …
  ejb3/src/main/java/org/jboss/as/ejb3/timerservice/persistence/database/DatabaseTimerPersistence.java
Labels: deps-ok, ready-for-merge

#12410 WFLY-12238 SimpleLoadProviderResourceDefinition - identical code in d…
  mod_cluster/extension/src/main/java/org/wildfly/extension/mod_cluster/ProxyConfigurationResourceDefinition.java
  mod_cluster/extension/src/main/java/org/wildfly/extension/mod_cluster/SimpleLoadProviderResourceDefinition.java
Labels: deps-ok, ready-for-merge

#12413 [WFLY-12267]:Upgrade java-support to 7.3.0
  pom.xml
Labels: deps-ok, ready-for-merge

#12377 [WFLY-12216] Log WARN if application specifies @RunAsPrincipal and no…
  ejb3/src/main/java/org/jboss/as/ejb3/deployment/processors/merging/RunAsMergingProcessor.java
  ejb3/src/main/java/org/jboss/as/ejb3/logging/EjbLogger.java
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/ejb/security/RunAsPrincipalTestCase.java
  testsuite/shared/src/main/java/org/jboss/as/test/shared/TestLogHandlerSetupTask.java
  testsuite/shared/src/main/java/org/jboss/as/test/shared/util/LoggingUtil.java
Labels: deps-ok, ready-for-merge

#12381 [WFLY-12175] Fix some wrong links in the documentation
  docs/src/main/asciidoc/_admin-guide/Management_resources.adoc
  docs/src/main/asciidoc/_admin-guide/management-api/Description_of_the_Management_Model.adoc
  docs/src/main/asciidoc/_admin-guide/management-api/Global_operations.adoc
  docs/src/main/asciidoc/_extending-wildfly/Key_Interfaces_and_Classes_Relevant_to_Extension_Developers.adoc
Labels: deps-ok, ready-for-merge

#12428 [WFLY-12042] missing serialVersionUIDon EE Concurrency SetupContextHa…
  ee/src/main/java/org/jboss/as/ee/concurrent/ConcurrentContext.java
  ee/src/main/java/org/jboss/as/ee/concurrent/handle/ClassLoaderContextHandleFactory.java
  ee/src/main/java/org/jboss/as/ee/concurrent/handle/NamingContextHandleFactory.java
  ee/src/main/java/org/jboss/as/ee/concurrent/handle/NullContextHandle.java
  ee/src/main/java/org/jboss/as/ee/concurrent/handle/OtherEESetupActionsContextHandleFactory.java
  ejb3/src/main/java/org/jboss/as/ejb3/component/concurrent/EJBContextHandleFactory.java
  security/subsystem/src/main/java/org/jboss/as/security/deployment/SecurityContextHandleFactory.java
  transactions/src/main/java/org/jboss/as/txn/ee/concurrency/TransactionLeakContextHandleFactory.java
Labels: deps-ok

#12425 WFLY-12281 Upgrade jboss-ejb-client from 4.0.20 to 4.0.21
  pom.xml
Labels: deps-ok

#12424 WFLY-12258 Upgrade wildfly-transaction-client from 1.1.4.Final to 1.1…
  pom.xml
Labels: deps-ok

#12426 [WFLY-11841] use request-controller capability on EE concurrency reso…
  ee/src/main/java/org/jboss/as/ee/subsystem/ManagedExecutorServiceAdd.java
  ee/src/main/java/org/jboss/as/ee/subsystem/ManagedScheduledExecutorServiceAdd.java
Labels: deps-ok

#12427 [WFLY-12282] use request-controller capability on Batch resources
  batch-jberet/src/main/java/org/wildfly/extension/batch/jberet/BatchSubsystemDefinition.java
Labels: deps-ok

#12434 [WFLY-12207] Upgrade to RESTEasy 3.8.1.Final
  pom.xml
Labels: deps-ok, ready-for-merge

#12370 [WFLY-12194] adding testcase for transaction affinity for SLSB
  testsuite/integration/clustering/src/test/java/org/jboss/as/test/clustering/cluster/ejb/remote/TransactionalRemoteStatelessTestCase.java
  testsuite/integration/clustering/src/test/java/org/jboss/as/test/clustering/cluster/ejb/remote/bean/StatelessTransactionBean.java
  testsuite/integration/clustering/src/test/java/org/jboss/as/test/clustering/cluster/ejb/remote/bean/StatelessTransactionNoResourceBean.java
  testsuite/shared/src/main/java/org/jboss/as/test/integration/transactions/TransactionTestLookupUtil.java
  testsuite/shared/src/main/java/org/jboss/as/test/integration/transactions/TxTestUtil.java
Labels: deps-ok, ready-for-merge

#12436 [WFLY-12296] Upgrade WildFly Core 10.0.0.Beta2
  pom.xml
Labels: deps-ok

#12378 [WFLY-12217] Update subsystem schemas to reference the new XML schema for credential-reference
  clustering/jgroups/extension/src/main/resources/schema/jboss-as-jgroups_7_0.xsd
  connector/src/main/resources/schema/wildfly-datasources_5_0.xsd
  connector/src/main/resources/schema/wildfly-resource-adapters_5_0.xsd
  datasources-agroal/src/main/resources/schema/wildfly-agroal_1_0.xsd
  mail/src/main/resources/schema/wildfly-mail_3_0.xsd
  messaging-activemq/src/main/resources/schema/wildfly-messaging-activemq_7_0.xsd
  undertow/src/main/resources/schema/wildfly-undertow_9_0.xsd
Labels: deps-ok, ready-for-merge

#12417 Fix for WFLY-12269, transactions galleon layer
  galleon-pack/src/main/resources/layers/standalone/jms-activemq/layer-spec.xml
  galleon-pack/src/main/resources/layers/standalone/jpa/layer-spec.xml
  galleon-pack/src/main/resources/layers/standalone/resource-adapters/layer-spec.xml
  galleon-pack/src/main/resources/layers/standalone/transactions/layer-spec.xml
  testsuite/layers/pom.xml
Labels: deps-ok

#12443 WFLY-12309 Need to include the schedule expression value in the toStr…
  ejb3/src/main/java/org/jboss/as/ejb3/timerservice/CalendarTimer.java
Labels: deps-ok

#12438 Fix a typo in infinispan schemas
  clustering/infinispan/extension/src/main/resources/schema/jboss-as-infinispan_1_0.xsd
  clustering/infinispan/extension/src/main/resources/schema/jboss-as-infinispan_1_1.xsd
  clustering/infinispan/extension/src/main/resources/schema/jboss-as-infinispan_1_2.xsd
  clustering/infinispan/extension/src/main/resources/schema/jboss-as-infinispan_1_3.xsd
  clustering/infinispan/extension/src/main/resources/schema/jboss-as-infinispan_1_4.xsd
  clustering/infinispan/extension/src/main/resources/schema/jboss-as-infinispan_1_5.xsd
  clustering/infinispan/extension/src/main/resources/schema/jboss-as-infinispan_2_0.xsd
  clustering/infinispan/extension/src/main/resources/schema/jboss-as-infinispan_3_0.xsd
  clustering/infinispan/extension/src/main/resources/schema/jboss-as-infinispan_4_0.xsd
  clustering/infinispan/extension/src/main/resources/schema/jboss-as-infinispan_5_0.xsd
  clustering/infinispan/extension/src/main/resources/schema/jboss-as-infinispan_6_0.xsd
  clustering/infinispan/extension/src/main/resources/schema/jboss-as-infinispan_7_0.xsd
  clustering/infinispan/extension/src/main/resources/schema/jboss-as-infinispan_8_0.xsd
Labels: deps-ok

#12442 Clustering TS: Also disable byteman tests surefire execution when usi…
  testsuite/integration/clustering/pom.xml
Labels: deps-ok

#12445 WFLY-12314 Fix inadvertent inverse tautology in local command dispatching assertion
  clustering/server/src/main/java/org/wildfly/clustering/server/dispatcher/LocalCommandDispatcher.java
Labels: deps-ok

#12431 [WFLY-12277] Avoid doubled 'image' in docs image URLs; use correct if…
  docs/src/main/asciidoc/Getting_Started_Guide.adoc
  docs/src/main/asciidoc/_admin-guide/Default_HTTP_Interface_Security.adoc
  docs/src/main/asciidoc/_admin-guide/Operating_modes.adoc
  docs/src/main/asciidoc/_admin-guide/RBAC.adoc
  docs/src/main/asciidoc/_admin-guide/add-user-utility.adoc
  docs/src/main/asciidoc/_developer-guide/jax-ws/WS-Security.adoc
  docs/src/main/asciidoc/_extras/Developing_JSF_Project_Using,_Maven_and_IntelliJ.adoc
  docs/src/main/asciidoc/_high-availability/Clustering_and_Domain_Setup_Walkthrough.adoc
  docs/src/main/asciidoc/_javaee-guide/Java_API_for_RESTful_Web_Services_(JAX-RS).adoc
  docs/src/main/asciidoc/index.adoc
Labels: deps-ok

#12446 WFLY-12318 removing unuseful push/pull in SecurityManager
  connector/src/main/java/org/jboss/as/connector/services/resourceadapters/deployment/AbstractResourceAdapterDeploymentService.java
Labels: deps-ok, ready-for-merge

#12447 [WFLY-12319] exclude not prod artifacts from server's dep management
  pom.xml
Labels: deps-ok, ready-for-merge

#12451 WFLY-12325 Upgrade Jackson2 databind to 2.9.9.1
  pom.xml
Labels: deps-ok, ready-for-merge

#12454 WFLY-12323 Upgrade wildfly-transaction-client from 1.1.5.Final to 1.1…
  pom.xml
Labels: deps-ok, ready-for-merge

#12397 [WFLY-12252]: Add metric type flags on messaging subsytem metrics.
  messaging-activemq/src/main/java/org/wildfly/extension/messaging/activemq/CommonAttributes.java
  messaging-activemq/src/main/java/org/wildfly/extension/messaging/activemq/jms/JMSTopicDefinition.java
  messaging-activemq/src/main/java/org/wildfly/extension/messaging/activemq/jms/bridge/JMSBridgeDefinition.java
Labels: deps-ok, ready-for-merge

#12456 WFLY-12331 Skip redundant put operations when distributable SFSBs use local, non-persistent cache configuration
  clustering/ee/infinispan/src/main/java/org/wildfly/clustering/ee/infinispan/InfinispanMutatorFactory.java
  clustering/ee/spi/src/main/java/org/wildfly/clustering/ee/MutatorFactory.java
  clustering/ejb/infinispan/src/main/java/org/wildfly/clustering/ejb/infinispan/bean/InfinispanBeanFactory.java
  clustering/ejb/infinispan/src/main/java/org/wildfly/clustering/ejb/infinispan/group/InfinispanBeanGroupFactory.java
Labels: deps-ok, ready-for-merge

#12463 WFLY-12338: enabled JBoss Enterprise Maven Repository
  pom.xml
Labels: deps-ok
