Repository wildfly/wildfly, pull requests merged in 2019-05, with the labels that each got.

#12252 [WFLY-12041] Upgrade WildFly Core 9.0.0.Beta4
  pom.xml
Labels: deps-ok

#12168 [WFLY-11869] JSF Session / View Beans @Destroy not invoked after GC
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/jsf/managedbean/gc/CountBean.java
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/jsf/managedbean/gc/CountBeanViewScoped.java
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/jsf/managedbean/gc/GCPreDestroyTestCase.java
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/jsf/managedbean/gc/InitBean.java
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/jsf/managedbean/gc/InitBeanViewScoped.java
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/jsf/managedbean/gc/TestResultsBean.java
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/jsf/managedbean/gc/sessionscoped.xhtml
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/jsf/managedbean/gc/viewscoped.xhtml
  web-common/src/main/java/org/jboss/as/web/common/WebInjectionContainer.java
Labels: deps-ok

#12247 [WFLY-12021] Clean up expanded legacy version zips
  testsuite/mixed-domain/src/test/java/org/jboss/as/test/integration/domain/mixed/OldVersionCopier.java
Labels: deps-ok

#12253 [WFLY-12028] / [WFLY-12029] JBoss Parent and Checkstyle Config Updates.
  pom.xml
Labels: deps-ok

#12250 [WFLY-12036]:Upgrade jaxbintros to 1.0.3.GA
  pom.xml
Labels: deps-ok

#12256 WFLY-12035 Upgrade jberet-core from 1.3.3.Final to 1.3.4.Final
  pom.xml
Labels: deps-ok, ready-for-merge

#12257 WFLY-12047 Single sign-on removal does not remove all installed services.
  clustering/service/src/main/java/org/wildfly/clustering/service/CascadeRemovalLifecycleListener.java
  clustering/web/undertow/src/main/java/org/wildfly/clustering/web/undertow/sso/DistributableSingleSignOnManagerServiceConfigurator.java
  clustering/web/undertow/src/main/java/org/wildfly/clustering/web/undertow/sso/elytron/DistributableSingleSignOnManagerServiceConfigurator.java
Labels: deps-ok, ready-for-merge

#12260 WFLY-12000 Upgrade Weld to 3.1.1.Final.
  pom.xml
Labels: deps-ok, ready-for-merge

#12254 Galleon 4.0, deps provided for Galleon FP, generate all-artifacts list.
  dist/pom.xml
  dist/src/test/java/org/wildfly/dist/subsystem/xml/XSDValidationUnitTestCase.java
  galleon-pack/pom.xml
  pom.xml
  servlet-galleon-pack/pom.xml
Labels: deps-ok

#12265 [WFLY-12055] Update jboss-ejb-client to 4.0.18.Final
  pom.xml
Labels: deps-ok

#12266 [WFLY-12057] Upgrade WildFly Core 9.0.0.Beta5
  pom.xml
Labels: deps-ok

#12271 [WFLY-12062] Upgrade to Galleon and WFGP 4.0.0.Final
  pom.xml
Labels: deps-ok

#12178 [WFLY-11876]: Upgrade Artemis to 2.7.0
  feature-pack/feature-pack-build.xml
  feature-pack/pom.xml
  feature-pack/src/license/full-feature-pack-licenses.xml
  feature-pack/src/main/resources/modules/system/layers/base/org/apache/activemq/artemis/journal/main/module.xml
  feature-pack/src/main/resources/modules/system/layers/base/org/apache/activemq/artemis/main/module.xml
  galleon-pack/pom.xml
  galleon-pack/src/main/resources/packages/org.apache.activemq.artemis.journal/pm/wildfly/tasks.xml
  legacy/messaging/pom.xml
  messaging-activemq/src/test/java/org/wildfly/extension/messaging/activemq/jms/PooledConnectionFactoryAttributesTestCase.java
  pom.xml
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/messaging/security/SecurityTestCase.java
Labels: deps-changed

#11918 WFLY-11404 Add journal-file-open-timeout attribute to messaging server
  messaging-activemq/src/main/java/org/wildfly/extension/messaging/activemq/MessagingSubsystemParser_6_0.java
  messaging-activemq/src/main/java/org/wildfly/extension/messaging/activemq/MessagingTransformerRegistration.java
  messaging-activemq/src/main/java/org/wildfly/extension/messaging/activemq/ServerAdd.java
  messaging-activemq/src/main/java/org/wildfly/extension/messaging/activemq/ServerDefinition.java
  messaging-activemq/src/main/resources/org/wildfly/extension/messaging/activemq/LocalDescriptions.properties
  messaging-activemq/src/main/resources/schema/wildfly-messaging-activemq_6_0.xsd
  messaging-activemq/src/test/java/org/wildfly/extension/messaging/activemq/MessagingActiveMQSubsystem_6_0_TestCase.java
  messaging-activemq/src/test/resources/org/wildfly/extension/messaging/activemq/subsystem_6_0.xml
  messaging-activemq/src/test/resources/org/wildfly/extension/messaging/activemq/subsystem_6_0_reject_transform.xml
Labels: Feature, deps-ok, ready-for-merge

#12173 [WFLY-9529] proper EE integration for cdi app context lifecycle event…
  connector/src/main/java/org/jboss/as/connector/deployers/datasource/DefaultDataSourceBindingProcessor.java
  ee/src/main/java/org/jboss/as/ee/component/Attachments.java
  ee/src/main/java/org/jboss/as/ee/component/deployers/AbstractPlatformBindingProcessor.java
  ee/src/main/java/org/jboss/as/ee/concurrent/deployers/EEConcurrentContextProcessor.java
  ee/src/main/java/org/jboss/as/ee/concurrent/deployers/EEConcurrentDefaultBindingProcessor.java
  messaging-activemq/src/main/java/org/wildfly/extension/messaging/activemq/deployment/DefaultJMSConnectionFactoryBindingProcessor.java
  testsuite/integration/basic/pom.xml
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/messaging/jms/external/DiscoveryGroupExternalMessagingDeploymentTestCase.java
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/messaging/jms/external/ExternalMessagingDeploymentRemoteTestCase.java
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/messaging/jms/external/ExternalMessagingDeploymentTestCase.java
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/messaging/jms/external/SendToExternalJMSQueueTestCase.java
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/messaging/jms/external/SendToExternalJMSTopicTestCase.java
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/messaging/mgmt/ExternalPooledConnectionFactoryStatisticsTestCase.java
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/weld/context/application/lifecycle/ApplicationContextLifecycleTestCase.java
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/weld/context/application/lifecycle/Bean.java
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/weld/context/application/lifecycle/Ejb.java
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/weld/context/application/lifecycle/Mdb.java
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/weld/context/application/lifecycle/Servlet.java
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/weld/context/application/lifecycle/TestResults.java
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/weld/context/application/lifecycle/TestResultsBean.java
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/weld/context/application/lifecycle/Utils.java
  transactions/src/main/java/org/jboss/as/txn/deployment/TransactionJndiBindingProcessor.java
  weld/subsystem/src/main/java/org/jboss/as/weld/WeldSubsystemAdd.java
  weld/subsystem/src/main/java/org/jboss/as/weld/deployment/processors/EarApplicationScopedObserverMethodProcessor.java
  weld/subsystem/src/main/java/org/jboss/as/weld/deployment/processors/WeldDeploymentProcessor.java
Labels: deps-ok, fixme

#12255 WFLY-12034 Upgrade jboss-batch-api_1.0_spec from 1.0.1.Final to 1.0.2…
  pom.xml
Labels: deps-ok, ready-for-merge

#12267 [WFLY-12059] Upgrade wildfly-common to 1.5.1.Final
  pom.xml
Labels: deps-ok, ready-for-merge

#12269 [WFLY-12054] Intermittent failures in WebsocketApplicationScopedTestCase
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/weld/deployment/WebsocketApplicationScopedTestCase.java
Labels: deps-ok, ready-for-merge

#12270 [WFLY-12058] Deprecated WeldDeploymentMarker and WeldPortableExtensions functionality not working as expected
  ee/src/main/java/org/jboss/as/ee/weld/WeldDeploymentMarker.java
  weld/common/src/main/java/org/jboss/as/weld/deployment/WeldPortableExtensions.java
  weld/subsystem/src/main/java/org/jboss/as/weld/WeldCapabilityImpl.java
  weld/subsystem/src/main/java/org/jboss/as/weld/_private/WeldDeploymentMarker.java
  weld/subsystem/src/main/java/org/jboss/as/weld/_private/WeldPortableExtensions.java
  weld/subsystem/src/main/java/org/jboss/as/weld/deployment/processors/DevelopmentModeProcessor.java
  weld/subsystem/src/main/java/org/jboss/as/weld/deployment/processors/WeldDeploymentProcessor.java
  weld/subsystem/src/main/java/org/jboss/as/weld/deployment/processors/WeldPortableExtensionProcessor.java
Labels: deps-ok, ready-for-merge

#12272 WFLY-12064 SFSBs left in invalid/inconsistent state if @PrePassivate throws an exception/error
  clustering/ejb/infinispan/src/main/java/org/wildfly/clustering/ejb/infinispan/group/InfinispanBeanGroupFactory.java
Labels: deps-ok

#12263 [WFLY-12050] Don't try to get metrics from a UndertowDeploymentServic…
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/management/deploy/runtime/FailedDeploymentUndertowRuntimeTestCase.java
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/management/deploy/runtime/servlet/BadContextListener.java
  undertow/src/main/java/org/wildfly/extension/undertow/DeploymentServletDefinition.java
Labels: deps-ok

#12275 WFLY-11159 Upgrade mod_cluster to 1.4.1.Final
  pom.xml
Labels: deps-ok

#12274 WFLY-12066 Upgrade jgroups-azure to 1.2.1.Final
  pom.xml
Labels: deps-ok

#12279 [WFLY-12069] Upgrade WildFly Core 9.0.0.Beta6
  pom.xml
Labels: deps-ok

#12206 [WFLY-11923] Test case and documentation addition for JDBC SecurityRealm enhancements/
  docs/src/main/asciidoc/_elytron/Passwords.adoc
  docs/src/main/asciidoc/_elytron/components/JDBC_Security_Realm.adoc
  testsuite/integration/elytron/src/test/java/org/wildfly/test/integration/elytron/realm/JdbcRealmTestCase.java
  testsuite/shared/src/main/java/org/wildfly/test/security/common/elytron/JdbcSecurityRealm.java
Labels: Feature-Docs, deps-ok, ready-for-merge

#12277 [WFLY-12068] Update openjdk-orb 8.1.4.Final
  pom.xml
Labels: deps-ok, ready-for-merge

#12286 [WFLY-12001] Upgrade HAL to 3.2.0.Final
  pom.xml
Labels: Feature, deps-ok, ready-for-merge

#12290 [WFLY-12076] Use maven project.groupId for the aggregation of galleonfeature-pack offliner files
  dist/pom.xml
Labels: deps-ok, ready-for-merge

#12292 Drop workaround for WELD-2577 following upgrade to 3.1.1.Final.
  clustering/web/undertow/src/main/java/org/wildfly/clustering/web/undertow/session/DistributableSession.java
Labels: deps-ok, ready-for-merge

#12299 Fix for WFLY-12080, Upgrade galleon-plugins to 4.0.1
  dist/pom.xml
  pom.xml
Labels: deps-ok

#12276 [WFLY-12067] Reorganize pom properties to clearly segregate props sol…
  pom.xml
Labels: deps-ok

#12030 [WFLY-11489] Correct assignment of EJB client affinties on server side.
  ejb3/src/main/java/org/jboss/as/ejb3/remote/AssociationImpl.java
  testsuite/integration/clustering/src/test/java/org/jboss/as/test/clustering/cluster/ejb/remote/PassivationDisabledRemoteStatefulEjbFailoverTestCase.java
  testsuite/integration/clustering/src/test/java/org/jboss/as/test/clustering/cluster/ejb/remote/bean/PassivationDisabledStatefulIncrementorBean.java
Labels: deps-ok

#12133 [WFLY-11682] Send CLUSTER_REMOVED message to client when last node in cluster leaves.
  ejb3/src/main/java/org/jboss/as/ejb3/remote/AssociationImpl.java
  ejb3/src/main/java/org/jboss/as/ejb3/remote/AssociationService.java
  ejb3/src/main/java/org/jboss/as/ejb3/remote/EJBRemoteConnectorService.java
Labels: deps-ok

#12302 [WFLY-11908] Bring subsystem namespace versions up to date in appclie…
  feature-pack/src/main/resources/content/appclient/configuration/appclient.xml
Labels: deps-ok, ready-for-merge

#12303 WFLY-12086 Hibernate 2lc should be enabled if Hibernate cache properties are enabled and shared cache mode is not set to NONE
  docs/src/main/asciidoc/_developer-guide/JPA_Reference_Guide.adoc
  jpa/hibernate5_3/src/main/java/org/jboss/as/jpa/hibernate5/HibernatePersistenceProviderAdaptor.java
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/jpa/secondlevelcache/persistence.xml
Labels: deps-ok, ready-for-merge

#12307 [WFLY-12105]: Upgrade Apache Artemis from 2.8.0.Final to 2.8.1.Final.
  pom.xml
Labels: deps-ok

#12282 [WFLY-12070]Upgrade to Apache CXF 3.3.2 and JBossWS 5.3.0.Final
  pom.xml
  testsuite/integration/xts/src/test/java/org/jboss/as/test/xts/suspend/AbstractTestCase.java
  testsuite/integration/xts/src/test/java/org/jboss/as/test/xts/suspend/wsat/AtomicTransactionSuspendTestCase.java
Labels: deps-ok, ready-for-merge

#12288 [WFLY-12038]: Expose the enable1Prefixes configuration on external (pooled) connection factories.
  docs/src/main/asciidoc/_admin-guide/subsystem-configuration/Messaging_Connect_a_pooled-connection-factory_to_a_Remote_Artemis_Server.adoc
  messaging-activemq/src/main/java/org/wildfly/extension/messaging/activemq/MessagingSubsystemParser_7_0.java
  messaging-activemq/src/main/java/org/wildfly/extension/messaging/activemq/MessagingTransformerRegistration.java
  messaging-activemq/src/main/java/org/wildfly/extension/messaging/activemq/jms/ConnectionFactoryAttributes.java
  messaging-activemq/src/main/java/org/wildfly/extension/messaging/activemq/jms/ExternalConnectionFactoryAdd.java
  messaging-activemq/src/main/java/org/wildfly/extension/messaging/activemq/jms/ExternalConnectionFactoryDefinition.java
  messaging-activemq/src/main/java/org/wildfly/extension/messaging/activemq/jms/ExternalConnectionFactoryService.java
  messaging-activemq/src/main/java/org/wildfly/extension/messaging/activemq/jms/ExternalPooledConnectionFactoryDefinition.java
  messaging-activemq/src/main/java/org/wildfly/extension/messaging/activemq/jms/JMSQueueService.java
  messaging-activemq/src/main/java/org/wildfly/extension/messaging/activemq/jms/JMSTopicService.java
  messaging-activemq/src/main/resources/org/wildfly/extension/messaging/activemq/LocalDescriptions.properties
  messaging-activemq/src/main/resources/schema/wildfly-messaging-activemq_7_0.xsd
  messaging-activemq/src/test/java/org/wildfly/extension/messaging/activemq/MessagingActiveMQSubsystem_7_0_TestCase.java
  messaging-activemq/src/test/resources/org/wildfly/extension/messaging/activemq/subsystem_7_0.xml
  messaging-activemq/src/test/resources/org/wildfly/extension/messaging/activemq/subsystem_7_0_reject_transform.xml
Labels: Feature, deps-ok

#12239 [WFLY-11967] Eliminating CapabilityServiceTarget.addCapability() deprecated method usages
  connector/src/main/java/org/jboss/as/connector/subsystems/jca/JcaSubsystemAdd.java
  datasources-agroal/src/main/java/org/wildfly/extension/datasources/agroal/DataSourceOperations.java
  datasources-agroal/src/main/java/org/wildfly/extension/datasources/agroal/DriverOperations.java
  datasources-agroal/src/main/java/org/wildfly/extension/datasources/agroal/XADataSourceOperations.java
  ejb3/src/main/java/org/jboss/as/ejb3/subsystem/EJB3RemoteServiceAdd.java
  mail/src/main/java/org/jboss/as/mail/extension/MailSessionAdd.java
  microprofile/health-smallrye/src/main/java/org/wildfly/extension/microprofile/health/HealthReporterService.java
  transactions/src/main/java/org/jboss/as/txn/service/TransactionSynchronizationRegistryService.java
  transactions/src/main/java/org/jboss/as/txn/subsystem/TransactionSubsystemAdd.java
  undertow/src/main/java/org/wildfly/extension/undertow/AccessLogAdd.java
  undertow/src/main/java/org/wildfly/extension/undertow/AjpListenerAdd.java
  undertow/src/main/java/org/wildfly/extension/undertow/ByteBufferPoolDefinition.java
  undertow/src/main/java/org/wildfly/extension/undertow/HostAdd.java
  undertow/src/main/java/org/wildfly/extension/undertow/HostSingleSignOnServiceHandler.java
  undertow/src/main/java/org/wildfly/extension/undertow/HttpInvokerDefinition.java
  undertow/src/main/java/org/wildfly/extension/undertow/HttpListenerAdd.java
  undertow/src/main/java/org/wildfly/extension/undertow/HttpsListenerAdd.java
  undertow/src/main/java/org/wildfly/extension/undertow/ListenerAdd.java
  undertow/src/main/java/org/wildfly/extension/undertow/LocationAdd.java
  undertow/src/main/java/org/wildfly/extension/undertow/ServerAdd.java
  undertow/src/main/java/org/wildfly/extension/undertow/ServletContainerAdd.java
  undertow/src/main/java/org/wildfly/extension/undertow/UndertowSubsystemAdd.java
  undertow/src/main/java/org/wildfly/extension/undertow/filters/ModClusterService.java
  undertow/src/main/java/org/wildfly/extension/undertow/handlers/HandlerAdd.java
  undertow/src/main/java/org/wildfly/extension/undertow/handlers/ReverseProxyHandlerHost.java
Labels: deps-ok, ready-for-merge

#12281 [WFLY-11829]: Support messaging clusters (Artemis Clusters) behind HTTP load balancers.
  docs/src/main/asciidoc/_admin-guide/subsystem-configuration/Messaging_Discovery_Configuration.adoc
  messaging-activemq/src/main/java/org/wildfly/extension/messaging/activemq/MessagingSubsystemParser_7_0.java
  messaging-activemq/src/main/java/org/wildfly/extension/messaging/activemq/MessagingTransformerRegistration.java
  messaging-activemq/src/main/java/org/wildfly/extension/messaging/activemq/jms/ConnectionFactoryAdd.java
  messaging-activemq/src/main/java/org/wildfly/extension/messaging/activemq/jms/ConnectionFactoryAttributes.java
  messaging-activemq/src/main/java/org/wildfly/extension/messaging/activemq/jms/ExternalConnectionFactoryDefinition.java
  messaging-activemq/src/main/resources/org/wildfly/extension/messaging/activemq/LocalDescriptions.properties
  messaging-activemq/src/main/resources/schema/wildfly-messaging-activemq_7_0.xsd
  messaging-activemq/src/test/java/org/wildfly/extension/messaging/activemq/MessagingActiveMQSubsystem_7_0_TestCase.java
  messaging-activemq/src/test/java/org/wildfly/extension/messaging/activemq/jms/PooledConnectionFactoryAttributesTestCase.java
  messaging-activemq/src/test/resources/org/wildfly/extension/messaging/activemq/subsystem_7_0.xml
  messaging-activemq/src/test/resources/org/wildfly/extension/messaging/activemq/subsystem_7_0_reject_transform.xml
  messaging-activemq/src/test/resources/org/wildfly/extension/messaging/activemq/subsystem_7_0_transform.xml
Labels: Feature, deps-ok, ready-for-merge

#12304 [WFLY-12096] Do not use hardcoded name to point to the provisioned server dist module
  dist/pom.xml
Labels: deps-ok, ready-for-merge

#12306 Add a missing letter in the logging documentation
  docs/src/main/asciidoc/_admin-guide/subsystem-configuration/Logging.adoc
Labels: deps-ok, ready-for-merge

#12308 [WFLY-12107] Upgrade JBoss Negotiation to 3.0.6.Final
  pom.xml
Labels: deps-ok, ready-for-merge

#12309 [WFLY-12108] Use a timeout utility instead of a sleep. Also remove th…
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/web/access/log/ConsoleAccessLogTestCase.java
Labels: deps-ok, ready-for-merge

#12318 WFLY-9776 Clustering testsuite: remove reuseFork=false workaround
  testsuite/integration/clustering/pom.xml
  testsuite/integration/clustering/src/test/java/org/jboss/as/test/clustering/cluster/ejb/remote/ClientClusterNodeSelectorTestCase.java
  testsuite/integration/clustering/src/test/java/org/jboss/as/test/clustering/cluster/ejb/remote/TransactionalRemoteStatefulEJBFailoverTestCase.java
Labels: deps-ok

#12314 [WFLY-12122] Upgrade to component matrix 1.0.3.Final
  pom.xml
Labels: deps-ok

#12323 [WFLY-12131] Missing clustering web configurations in the legacy builds
  feature-pack/pom.xml
  feature-pack/src/main/resources/configuration/examples/subsystems-activemq-colocated.xml
  feature-pack/src/main/resources/configuration/examples/subsystems-genericjms.xml
  feature-pack/src/main/resources/configuration/examples/subsystems-jts.xml
  feature-pack/src/main/resources/configuration/examples/subsystems-picketlink.xml
  feature-pack/src/main/resources/configuration/examples/subsystems-rts.xml
  feature-pack/src/main/resources/configuration/examples/subsystems-xts.xml
Labels: deps-ok

#12319 [WFLY-12110] Enhance Elytron Filesystem Realm documentation
  docs/src/main/asciidoc/_elytron/Elytron_Subsystem.adoc
  docs/src/main/asciidoc/_elytron/Subsystem_Component_Documentation.adoc
  docs/src/main/asciidoc/_elytron/components/Filesystem_Security_Realm.adoc
Labels: deps-ok

#12324 [WFLY-12132] Upgrade WildFly Core 9.0.0.Beta7
  pom.xml
Labels: deps-ok

#12310 WFLY-12113 Upgrade jgroups-kubernetes to 1.0.9.Final
  pom.xml
Labels: deps-ok, ready-for-merge

#12313 [WFLY-12120] Upgrade websockets-api 1.1 to 1.1.4.Final
  pom.xml
Labels: deps-ok, ready-for-merge

#12322 [WFLY-12130] Remove duplicate host-exclude from legacy build template config file
  feature-pack/src/main/resources/configuration/domain/template.xml
Labels: deps-ok, ready-for-merge

#12326 WFLY-12100 Upgrade Infinispan to 9.4.14.Final
  pom.xml
  testsuite/integration/clustering/src/test/java/org/jboss/as/test/clustering/cluster/web/persistence/AbstractDatabasePersistenceWebFailoverTestCase.java
  testsuite/integration/clustering/src/test/java/org/jboss/as/test/clustering/cluster/web/persistence/CoarseDatabasePersistenceWebFailoverTestCase.java
  testsuite/integration/clustering/src/test/java/org/jboss/as/test/clustering/cluster/web/persistence/FineDatabasePersistenceWebFailoverTestCase.java
  testsuite/integration/clustering/src/test/java/org/jboss/as/test/clustering/cluster/web/remote/AbstractHotRodPersistenceWebFailoverTestCase.java
Labels: deps-ok, ready-for-merge

#12327 WFLY-12139 Mutations following HttpSession.setAttribute(...) lost on failover ...
  clustering/web/cache/src/main/java/org/wildfly/clustering/web/cache/session/coarse/CoarseSessionAttributes.java
Labels: deps-ok, ready-for-merge

#12330 [WFLY-12143] Upgrade to Jackson 2.9.9
  pom.xml
Labels: deps-ok, ready-for-merge

#12331 [WFLY-12145] Move Galleon universe and producers to 1.0.2.Final
  pom.xml
Labels: deps-ok, ready-for-merge
