Repository wildfly/wildfly, pull requests merged in 2019-04, with the labels that each got.

#12187 [WFLY-11911] Remove READ_TIMEOUT from channel configuration options
  ejb3/src/main/resources/subsystem-templates/ejb3.xml
  galleon-pack/src/main/resources/feature_groups/ejb3.xml
Labels: ready-for-merge

#12200 [WFLY-11934] Upgrade wildfly-arquillian from 2.1.1.Final to 2.2.0.Fin…
  pom.xml
Labels: ready-for-merge

#12182 [WFLY-11896] Improve ability of mixed-domain testsuite to deal with different JVMs
  testsuite/mixed-domain/pom.xml
  testsuite/mixed-domain/src/test/java/org/jboss/as/test/integration/domain/mixed/DomainAdjuster.java
  testsuite/mixed-domain/src/test/java/org/jboss/as/test/integration/domain/mixed/LegacyConfigAdjuster.java
  testsuite/mixed-domain/src/test/java/org/jboss/as/test/integration/domain/mixed/MixedDomainTestSuite.java
  testsuite/mixed-domain/src/test/java/org/jboss/as/test/integration/domain/mixed/MixedDomainTestSupport.java
  testsuite/mixed-domain/src/test/java/org/jboss/as/test/integration/domain/mixed/SimpleMixedDomainTest.java
  testsuite/mixed-domain/src/test/java/org/jboss/as/test/integration/domain/mixed/Version.java
  testsuite/mixed-domain/src/test/java/org/jboss/as/test/integration/domain/mixed/eap640/ElytronOnlyMaster640TestSuite.java
Labels: ready-for-merge

#12199 [WFLY-11932] Use HTTPS for repository and pluginRepository URLs
  docs/src/main/asciidoc/_extending-wildfly/Example_subsystem.adoc
  pom.xml
Labels: ready-for-merge

#12201 [WFLY-11936] only log unbound msgs if binding service was up
  connector/src/main/java/org/jboss/as/connector/deployers/datasource/DataSourceDefinitionInjectionSource.java
  connector/src/main/java/org/jboss/as/connector/deployers/ds/processors/DsXmlDeploymentInstallProcessor.java
  connector/src/main/java/org/jboss/as/connector/deployers/ra/AdministeredObjectDefinitionInjectionSource.java
  connector/src/main/java/org/jboss/as/connector/services/resourceadapters/deployment/AbstractResourceAdapterDeploymentService.java
  connector/src/main/java/org/jboss/as/connector/subsystems/datasources/AbstractDataSourceAdd.java
  mail/src/main/java/org/jboss/as/mail/extension/MailSessionAdd.java
  mail/src/main/java/org/jboss/as/mail/extension/MailSessionDefinitionInjectionSource.java
  messaging-activemq/src/main/java/org/wildfly/extension/messaging/activemq/BinderServiceUtil.java
  messaging-activemq/src/main/java/org/wildfly/extension/messaging/activemq/deployment/JMSDestinationDefinitionInjectionSource.java
Labels: ready-for-merge

#12204 [WFLY-11931] Add test case to test the JDBC SecurityRealm integration.
  testsuite/integration/elytron/pom.xml
  testsuite/integration/elytron/src/test/java/org/wildfly/test/integration/elytron/realm/JdbcRealmTestCase.java
  testsuite/integration/elytron/src/test/java/org/wildfly/test/integration/elytron/realm/JdbcTestServlet.java
  testsuite/integration/elytron/src/test/java/org/wildfly/test/integration/elytron/realm/jdbc-realm-web.xml
  testsuite/shared/src/main/java/org/jboss/as/test/integration/security/common/Utils.java
  testsuite/shared/src/main/java/org/wildfly/test/security/common/elytron/ConstantRealmMapper.java
  testsuite/shared/src/main/java/org/wildfly/test/security/common/elytron/JdbcSecurityRealm.java
  testsuite/shared/src/main/java/org/wildfly/test/security/common/elytron/MappedRegexRealmMapper.java
  testsuite/shared/src/main/java/org/wildfly/test/security/common/elytron/RegexPrincipalTransformer.java
  testsuite/shared/src/main/java/org/wildfly/test/security/common/elytron/SimpleSecurityDomain.java
Labels: ready-for-merge

#12207 [WFLY-11944] Some clustering test cases do not close JNDI context between tests
  testsuite/integration/clustering/src/test/java/org/jboss/as/test/clustering/cluster/ejb2/stateful/failover/RemoteEJBClientStatefulFailoverTestBase.java
  testsuite/integration/clustering/src/test/java/org/jboss/as/test/clustering/cluster/ejb2/stateful/passivation/ClusterPassivationTestBase.java
  testsuite/integration/clustering/src/test/java/org/jboss/as/test/clustering/cluster/ejb2/stateless/RemoteStatelessFailoverTestCase.java
  testsuite/integration/clustering/src/test/java/org/jboss/as/test/clustering/ejb/RemoteEJBDirectory.java
Labels: ready-for-merge

#12208 WFLY-11946/WFLY-10340 Remove unneeded dependencies from OpenJPA module
  docs/src/main/asciidoc/_developer-guide/JPA_Reference_Guide.adoc
  feature-pack/src/main/resources/modules/system/layers/base/org/apache/openjpa/main/module.xml
  testsuite/compat/src/test/java/org/jboss/as/test/compat/jpa/openjpa/OpenJPASharedModuleProviderTestCase.java
  testsuite/compat/src/test/scripts/build-jars.xml
Labels: ready-for-merge

#12214 [WFLY-11672] @ApplicationScoped does not work when used with @ServerEndpoint
  testsuite/integration/basic/pom.xml
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/weld/deployment/ChatWebsocketResource.java
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/weld/deployment/WebsocketApplicationScopedTestCase.java
  weld/subsystem/src/main/java/org/jboss/as/weld/deployment/WeldClassIntrospector.java
Labels: fixme, ready-for-merge

#12212 [WFLY-11949] Eliminate unneeded dependencies from the legacy messagin…
  feature-pack/src/main/resources/modules/system/layers/base/org/jboss/as/messaging/main/module.xml
  legacy/messaging/pom.xml
  legacy/messaging/src/main/java/org/jboss/as/messaging/AbstractTransportDefinition.java
  legacy/messaging/src/main/java/org/jboss/as/messaging/Messaging13SubsystemParser.java
  legacy/messaging/src/main/java/org/jboss/as/messaging/Messaging20SubsystemParser.java
  legacy/messaging/src/main/java/org/jboss/as/messaging/MessagingSubsystemParser.java
  legacy/messaging/src/main/java/org/jboss/as/messaging/Namespace.java
  legacy/messaging/src/main/java/org/jboss/as/messaging/PathDefinition.java
  legacy/messaging/src/main/java/org/jboss/as/messaging/jms/ConnectionFactoryAttribute.java
  legacy/messaging/src/main/java/org/jboss/as/messaging/logging/MessagingLogger.java
Labels: ready-for-merge

#12160 [WFLY-11352] WildFly registers multiple distinct drivers for current MySQL driver jar - rework
  connector/src/main/java/org/jboss/as/connector/deployers/ds/processors/DriverProcessor.java
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/jca/datasource/DatasourceWrongDsClassTestCase.java
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/jca/datasource/TestDriver2.java
Labels: ready-for-merge

#12205 [WFLY-11941] Add the org.wildfly.event.logger module to the NOT_USED …
  testsuite/layers/src/test/java/org/jboss/as/test/layers/LayersTestCase.java
Labels: ready-for-merge

#12215 [WFLY-9954] Fixing too many services and dependencies created for EJBs issue
  ee/src/main/java/org/jboss/as/ee/component/deployers/EEModuleInitialProcessor.java
  ee/src/main/java/org/jboss/as/ee/naming/InApplicationClientBindingProcessor.java
  ee/src/main/java/org/jboss/as/ee/naming/InstanceNameBindingProcessor.java
  naming/src/main/java/org/jboss/as/naming/deployment/JndiNamingDependencyProcessor.java
  transactions/src/main/java/org/jboss/as/txn/deployment/TransactionJndiBindingProcessor.java
  weld/subsystem/src/main/java/org/jboss/as/weld/deployment/processors/WeldBeanManagerServiceProcessor.java
Labels: ready-for-merge

#12218 Update links for *EJBForwardingTestCase
  testsuite/integration/clustering/src/test/java/org/jboss/as/test/clustering/cluster/ejb/forwarding/AbstractRemoteEJBForwardingTestCase.java
Labels: ready-for-merge

#12219 [WFLY-11966] Capability requirements declared twice in JCA root resource definition
  connector/src/main/java/org/jboss/as/connector/subsystems/jca/JcaSubsystemRootDefinition.java
  connector/src/test/java/org/jboss/as/connector/subsystems/jca/JcaSubsystemTestCase.java
Labels: ready-for-merge

#12221 [WFLY-11974] resource adapter configured as module not finding validation provider
  feature-pack/src/main/resources/modules/system/layers/base/org/jboss/ironjacamar/impl/main/module.xml
Labels: ready-for-merge

#12222 WFLY-11975 Distributed web session metadata payload contains unnecessary nanosecond precision
  clustering/web/infinispan/src/main/java/org/wildfly/clustering/web/infinispan/session/SessionCreationMetaDataEntryExternalizer.java
  clustering/web/infinispan/src/test/java/org/wildfly/clustering/web/infinispan/session/SessionCreationMetaDataEntryExternalizerTestCase.java
Labels: ready-for-merge

#12228 WFLY-11984 ChannelCommandDispatcherFactory does not notify any GroupListener
  clustering/server/src/main/java/org/wildfly/clustering/server/dispatcher/ChannelCommandDispatcherFactory.java
  testsuite/integration/clustering/src/test/java/org/jboss/as/test/clustering/cluster/group/GroupListenerTestCase.java
  testsuite/integration/clustering/src/test/java/org/jboss/as/test/clustering/cluster/group/bean/ClusterTopology.java
  testsuite/integration/clustering/src/test/java/org/jboss/as/test/clustering/cluster/group/bean/ClusterTopologyRetriever.java
  testsuite/integration/clustering/src/test/java/org/jboss/as/test/clustering/cluster/group/bean/ClusterTopologyRetrieverBean.java
  testsuite/integration/clustering/src/test/java/org/jboss/as/test/clustering/cluster/group/bean/Group.java
  testsuite/integration/clustering/src/test/java/org/jboss/as/test/clustering/cluster/group/bean/GroupBean.java
Labels: ready-for-merge

#12189 WFLY-11801: fixes thread safety issues when adding/removing metric fa…
  microprofile/metrics-smallrye/src/main/java/org/wildfly/extension/microprofile/metrics/PrometheusCollector.java
Labels: 16.x

#12232 WFLY-11995 Template for legacy build of infinispan subsystem contains misnamed cache
  clustering/infinispan/extension/src/main/resources/subsystem-templates/infinispan.xml
Labels: deps-ok

#12230 [WFLY-11972] Update openjdk-orb to 8.1.3.Final
  pom.xml
Labels: deps-ok

#12229 [WFLY-11993] Prefer HTTPS over plain-text HTTP in default welcome-con…
  servlet-feature-pack/src/main/resources/content/welcome-content/index.html
  servlet-feature-pack/src/main/resources/content/welcome-content/index_noconsole.html
Labels: deps-ok

#12227 [WFLY-11973] Upgrade IronJacamar from 1.4.15.Final to 1.4.16.Final
  pom.xml
Labels: deps-ok, ready-for-merge

#12226 [WFLY-11985] Upgrade Commons Codec to 1.11
  pom.xml
Labels: deps-ok

#12234 [WFLY-11969] Upgrade Mojarra to 2.3.9.SP02
  pom.xml
Labels: deps-ok

#12225 [WFLY-10351] BMT interceptor timeout reset adjustment
  ejb3/src/main/java/org/jboss/as/ejb3/tx/BMTInterceptor.java
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/ejb/transaction/bmt/timeout/StatelessTimeoutTestCase.java
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/ejb/transaction/cmt/timeout/TransactionTimeoutTestCase.java
Labels: deps-ok, ready-for-merge

#12236 [WFLY-12004] Upgrade WildFly Core 9.0.0.Beta3
  pom.xml
Labels: deps-ok

#12243 Revert "[WFLY-12004] Upgrade WildFly Core 9.0.0.Beta3"
  pom.xml
Labels: deps-ok

#12240 WFLY-12005 Add documentation section for tuning distributed web application performance
  docs/src/main/asciidoc/_high-availability/subsystem-support/Distributable_Web_Applications.adoc
Labels: deps-ok

#12094 WFLY-11752 testsuite/integration/elytron uses directly a jboss.dist d…
  testsuite/integration/elytron/pom.xml
Labels: deps-ok, ready-for-merge

#12198 WFLY-9477: avoid registering ROOT.war as default web module more than…
  undertow/src/main/java/org/wildfly/extension/undertow/HostAdd.java
  undertow/src/main/java/org/wildfly/extension/undertow/HostDefinition.java
Labels: ready-for-merge

#12217 WFLY-11870 Do not process resource annotations on abstract classes or …
  ee/src/main/java/org/jboss/as/ee/component/deployers/ModuleJndiBindingProcessor.java
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/ejb/annotationprocessing/AbstractReferencingBeanA.java
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/ejb/annotationprocessing/ReferencedBean.java
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/ejb/annotationprocessing/ReferencedBeanInterface.java
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/ejb/annotationprocessing/ReferencingBeanBInterface.java
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/ejb/annotationprocessing/ReferencingClassA.java
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/ejb/annotationprocessing/ReferencingClassB.java
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/ejb/annotationprocessing/ReferencingComponentA.java
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/ejb/annotationprocessing/ReferencingComponentB.java
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/ejb/annotationprocessing/ResourceAnnotationsProcessingTestCase.java
Labels: ready-for-merge

#12220 WFLY-11906 Managed Executor Task Fails with CDI if created from Batch…
  batch-jberet/src/main/java/org/wildfly/extension/batch/jberet/deployment/BatchEnvironmentService.java
  batch-jberet/src/main/java/org/wildfly/extension/batch/jberet/deployment/ConcurrentContextHandle.java
Labels: deps-ok, ready-for-merge

#12235 [WFLY-11976] Upgrading WildFly-Naming-Client to 1.0.10.Final
  pom.xml
Labels: deps-ok, ready-for-merge

#12237 WFLY-12006 EJB3 IIOP attributes enable-by-default and use-qualified-name should be required
  ejb3/src/main/java/org/jboss/as/ejb3/subsystem/EJB3IIOPAdd.java
  ejb3/src/main/java/org/jboss/as/ejb3/subsystem/EJB3IIOPResourceDefinition.java
  ejb3/src/main/java/org/jboss/as/ejb3/subsystem/RemotingEjbReceiverChannelCreationOptionResource.java
  ejb3/src/main/java/org/jboss/as/ejb3/subsystem/RemotingEjbReceiverDefinition.java
  undertow/src/main/java/org/wildfly/extension/undertow/handlers/ReverseProxyHandlerHost.java
Labels: deps-ok, ready-for-merge

#12238 [WFLY-12007] Upgrade jboss-ejb-api_3.2_spec to 1.0.2.Final
  pom.xml
Labels: deps-ok, ready-for-merge

#12242 WFLY-12008 WFLY-11875 - Upgrade Hibernate ORM to 5.3.10.Final; upgrade Javassist to 3.23.2-GA
  pom.xml
Labels: deps-ok, ready-for-merge

#12180 WFLY-11891 Add tests that enable JPA entity class bytecode enhancement
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/jpa/basic/multiplepersistenceunittest/persistence.xml
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/jpa/entitylistener/persistence.xml
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/jpa/epcpropagation/persistence.xml
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/jpa/hibernate/envers/persistence.xml
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/jpa/hibernate/management/persistence.xml
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/jpa/secondlevelcache/persistence.xml
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/jpa/transaction/persistence.xml
Labels: deps-ok, ready-for-merge

#12244 [WFLY-10798] Setting correct TCCL for Datasource constructor
  connector/src/main/java/org/jboss/as/connector/subsystems/datasources/JdbcDriverAdd.java
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/jca/classloading/AbstractDataSourceClassloadingTestCase.java
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/jca/classloading/ClassloadingDataSource.java
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/jca/classloading/ClassloadingDriver.java
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/jca/classloading/ClassloadingXADataSource.java
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/jca/classloading/DataSourceTcclDatasourceClassTestCase.java
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/jca/classloading/DataSourceTcclDriverClassTestCase.java
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/jca/classloading/DataSourceTcclXADatasourceClassTestCase.java
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/jca/classloading/TestConnection.java
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/jca/classloading/TestXAConnection.java
Labels: deps-ok, ready-for-merge

#12246 [WFLY-11965] Upgrade WildFly HTTP Client to 1.0.15.Final
  pom.xml
Labels: deps-ok, ready-for-merge

#12249 WFLY-12022 Concurrent singleton service installation can cause service to run simultaneously on 2 members
  clustering/server/src/main/java/org/wildfly/clustering/server/provider/CacheServiceProviderRegistry.java
  clustering/server/src/main/java/org/wildfly/clustering/server/singleton/AbstractDistributedSingletonService.java
Labels: deps-ok

#12251 [WFLY-12039][JBEAP-16818] adding TCCL setup/reset to the null context…
  ee/src/main/java/org/jboss/as/ee/concurrent/DefaultContextSetupProviderImpl.java
  ee/src/main/java/org/jboss/as/ee/concurrent/handle/ClassLoaderContextHandleFactory.java
  ee/src/main/java/org/jboss/as/ee/concurrent/handle/NullContextHandle.java
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/ee/naming/defaultbindings/concurrency/DefaultConcurrencyTestCDIBean.java
Labels: deps-ok
