Repository wildfly/wildfly, pull requests merged in 2019-09, with the labels that each got.

#12514 WFLY-10057 EJB subsystem configure max threads and core threads independently
  docs/src/main/asciidoc/_admin-guide/subsystem-configuration/EJB3.adoc
  ejb3/src/main/java/org/jboss/as/ejb3/subsystem/EJB3Subsystem12Parser.java
  ejb3/src/main/java/org/jboss/as/ejb3/subsystem/EJB3SubsystemModel.java
  ejb3/src/main/java/org/jboss/as/ejb3/subsystem/EJB3SubsystemRootResourceDefinition.java
  ejb3/src/main/java/org/jboss/as/ejb3/subsystem/EJB3SubsystemXMLPersister.java
  ejb3/src/main/java/org/jboss/as/ejb3/subsystem/EJBTransformers.java
  ejb3/src/main/resources/schema/wildfly-ejb3_6_0.xsd
  ejb3/src/main/resources/subsystem-templates/ejb3.xml
  ejb3/src/test/java/org/jboss/as/ejb3/subsystem/Ejb3TransformersTestCase.java
  ejb3/src/test/resources/org/jboss/as/ejb3/subsystem/subsystem-ejb3-transform-reject.xml
  ejb3/src/test/resources/org/jboss/as/ejb3/subsystem/subsystem-ejb3-transform.xml
  ejb3/src/test/resources/org/jboss/as/ejb3/subsystem/subsystem.xml
  galleon-pack/src/main/resources/feature_groups/ejb3.xml
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/ejb/threadpool/Ejb3NonCoreThreadTimeoutTestCase.java
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/ejb/threadpool/Ejb3ThreadPoolBase.java
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/ejb/threadpool/Ejb3ThreadPoolModelTestCase.java
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/ejb/threadpool/Ejb3ThreadReuseTestCase.java
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/ejb/threadpool/ScheduleSingletonOneTimer.java
Labels: Feature, deps-ok, ready-for-merge

#12565 [WFLY-12466] Upgrade RESTEasy to 3.9.0.Final
  pom.xml
Labels: deps-ok

#12569 Fix for WFLY-12470, ee-security galleon layer
  docs/src/main/asciidoc/_admin-guide/Galleon_provisioning.adoc
  galleon-pack/src/main/resources/layers/standalone/cloud-profile/layer-spec.xml
  galleon-pack/src/main/resources/layers/standalone/ee-security/layer-spec.xml
  testsuite/layers/pom.xml
Labels: deps-ok

#12568 WFLY-12469 Timer ScheduleExpression default timezone should be null
  ejb3/src/main/java/org/jboss/as/ejb3/deployment/processors/annotation/ScheduleAnnotationInformationFactory.java
Labels: deps-ok

#12461 WFLY-12165 Expose management metrics for HotRod caches
  clustering/common/src/main/java/org/jboss/as/clustering/controller/BinaryServiceNameFactory.java
  clustering/common/src/main/java/org/jboss/as/clustering/controller/Operation.java
  clustering/common/src/main/java/org/jboss/as/clustering/controller/UnaryServiceNameFactory.java
  clustering/infinispan/client/pom.xml
  clustering/infinispan/client/src/main/java/org/wildfly/clustering/infinispan/client/RegisteredRemoteCache.java
  clustering/infinispan/client/src/main/java/org/wildfly/clustering/infinispan/client/RemoteCacheContainer.java
  clustering/infinispan/client/src/main/java/org/wildfly/clustering/infinispan/client/manager/RemoteCacheManager.java
  clustering/infinispan/client/src/main/java/org/wildfly/clustering/infinispan/client/service/RemoteCacheServiceConfigurator.java
  clustering/infinispan/extension/src/main/java/org/jboss/as/clustering/infinispan/subsystem/CacheContainerResourceDefinition.java
  clustering/infinispan/extension/src/main/java/org/jboss/as/clustering/infinispan/subsystem/CacheResourceDefinition.java
  clustering/infinispan/extension/src/main/java/org/jboss/as/clustering/infinispan/subsystem/CustomStoreResourceDefinition.java
  clustering/infinispan/extension/src/main/java/org/jboss/as/clustering/infinispan/subsystem/FileStoreResourceDefinition.java
  clustering/infinispan/extension/src/main/java/org/jboss/as/clustering/infinispan/subsystem/InfinispanSubsystemXMLReader.java
  clustering/infinispan/extension/src/main/java/org/jboss/as/clustering/infinispan/subsystem/JDBCStoreResourceDefinition.java
  clustering/infinispan/extension/src/main/java/org/jboss/as/clustering/infinispan/subsystem/RemoteStoreResourceDefinition.java
  clustering/infinispan/extension/src/main/java/org/jboss/as/clustering/infinispan/subsystem/StoreResourceDefinition.java
  clustering/infinispan/extension/src/main/java/org/jboss/as/clustering/infinispan/subsystem/remote/ConnectionPoolResourceDefinition.java
  clustering/infinispan/extension/src/main/java/org/jboss/as/clustering/infinispan/subsystem/remote/HotRodStore.java
  clustering/infinispan/extension/src/main/java/org/jboss/as/clustering/infinispan/subsystem/remote/HotRodStoreResourceDefinition.java
  clustering/infinispan/extension/src/main/java/org/jboss/as/clustering/infinispan/subsystem/remote/InvalidationNearCacheResourceDefinition.java
  clustering/infinispan/extension/src/main/java/org/jboss/as/clustering/infinispan/subsystem/remote/InvalidationNearCacheServiceConfigurator.java
  clustering/infinispan/extension/src/main/java/org/jboss/as/clustering/infinispan/subsystem/remote/ManagedRemoteCacheContainer.java
  clustering/infinispan/extension/src/main/java/org/jboss/as/clustering/infinispan/subsystem/remote/NearCacheResourceDefinition.java
  clustering/infinispan/extension/src/main/java/org/jboss/as/clustering/infinispan/subsystem/remote/NoNearCacheResourceDefinition.java
  clustering/infinispan/extension/src/main/java/org/jboss/as/clustering/infinispan/subsystem/remote/RemoteCacheContainerConfigurationServiceConfigurator.java
  clustering/infinispan/extension/src/main/java/org/jboss/as/clustering/infinispan/subsystem/remote/RemoteCacheContainerMetric.java
  clustering/infinispan/extension/src/main/java/org/jboss/as/clustering/infinispan/subsystem/remote/RemoteCacheContainerMetricExecutor.java
  clustering/infinispan/extension/src/main/java/org/jboss/as/clustering/infinispan/subsystem/remote/RemoteCacheContainerResource.java
  clustering/infinispan/extension/src/main/java/org/jboss/as/clustering/infinispan/subsystem/remote/RemoteCacheContainerResourceDefinition.java
  clustering/infinispan/extension/src/main/java/org/jboss/as/clustering/infinispan/subsystem/remote/RemoteCacheContainerServiceConfigurator.java
  clustering/infinispan/extension/src/main/java/org/jboss/as/clustering/infinispan/subsystem/remote/RemoteCacheMetric.java
  clustering/infinispan/extension/src/main/java/org/jboss/as/clustering/infinispan/subsystem/remote/RemoteCacheMetricExecutor.java
  clustering/infinispan/extension/src/main/java/org/jboss/as/clustering/infinispan/subsystem/remote/RemoteCacheOperation.java
  clustering/infinispan/extension/src/main/java/org/jboss/as/clustering/infinispan/subsystem/remote/RemoteCacheOperationExecutor.java
  clustering/infinispan/extension/src/main/java/org/jboss/as/clustering/infinispan/subsystem/remote/RemoteCacheResourceDefinition.java
  clustering/infinispan/extension/src/main/java/org/jboss/as/clustering/infinispan/subsystem/remote/RemoteClusterOperation.java
  clustering/infinispan/extension/src/main/java/org/jboss/as/clustering/infinispan/subsystem/remote/RemoteClusterOperationExecutor.java
  clustering/infinispan/extension/src/main/java/org/jboss/as/clustering/infinispan/subsystem/remote/RemoteClusterResourceDefinition.java
  clustering/infinispan/extension/src/main/java/org/jboss/as/clustering/infinispan/subsystem/remote/RemoteTransactionResourceDefinition.java
  clustering/infinispan/extension/src/main/java/org/jboss/as/clustering/infinispan/subsystem/remote/SecurityResourceDefinition.java
  clustering/infinispan/extension/src/main/resources/org/jboss/as/clustering/infinispan/subsystem/LocalDescriptions.properties
  clustering/infinispan/extension/src/main/resources/schema/jboss-as-infinispan_9_0.xsd
  clustering/infinispan/extension/src/test/java/org/jboss/as/clustering/infinispan/subsystem/InfinispanTransformersTestCase.java
  clustering/infinispan/extension/src/test/resources/org/jboss/as/clustering/infinispan/subsystem/infinispan-transformer-reject.xml
  clustering/infinispan/extension/src/test/resources/org/jboss/as/clustering/infinispan/subsystem/subsystem-infinispan-transform-8_0_0.xml
  clustering/jgroups/extension/src/main/java/org/jboss/as/clustering/jgroups/subsystem/ChannelResourceDefinition.java
  clustering/web/hotrod/src/main/java/org/wildfly/clustering/web/hotrod/session/HotRodSessionManagerFactoryServiceConfigurator.java
  docs/src/main/asciidoc/_high-availability/subsystem-support/Infinispan_Subsystem.adoc
  docs/src/main/asciidoc/_high-availability/subsystem-support/Offloading_session_state_to_remote_Infinispan_server_cluster.adoc
  feature-pack/src/main/resources/modules/system/layers/base/org/wildfly/clustering/infinispan/client/main/module.xml
  pom.xml
  testsuite/integration/clustering/src/test/java/org/jboss/as/test/clustering/cluster/web/remote/AbstractHotRodWebFailoverTestCase.java
  testsuite/integration/clustering/src/test/java/org/jboss/as/test/clustering/cluster/web/remote/InfinispanServerSetupTask.java
Labels: Feature, deps-ok

#12581 [WFLY-12481] Bump the surefire forkedProcessTimeoutInSeconds to 4500 …
  testsuite/integration/clustering/pom.xml
Labels: deps-ok

#12573 [WFLY-12472] Fixing NPE in JndiNamginDependencyProcessor if EE subsystem is N/A
  naming/src/main/java/org/jboss/as/naming/deployment/JndiNamingDependencyProcessor.java
Labels: deps-ok

#12547 [WFLY-12440]:Upgrade jboss-jaxws-api_2.3_spec from 1.0.0.Final to 2.0…
  pom.xml
Labels: 18.x, deps-changed, sep4

#12574 WFLY-12355 Upgrade jboss-batch-api_1.0_spec from 1.0.2.Final to 2.0.0…
  pom.xml
Labels: 18.x, deps-ok, sep4

#12562 WFLY-12460 Upgrade jboss-transaction-api_1.2_spec to jboss-transactio…
  client/shade/pom.xml
  clustering/ee/cache/pom.xml
  clustering/ee/hotrod/pom.xml
  clustering/ee/infinispan/pom.xml
  clustering/ejb/infinispan/pom.xml
  clustering/infinispan/client/pom.xml
  clustering/server/pom.xml
  clustering/web/infinispan/pom.xml
  ee/pom.xml
  feature-pack/pom.xml
  feature-pack/src/license/full-feature-pack-licenses.xml
  feature-pack/src/main/resources/content/bin/client/README-EJB-JMS.txt
  galleon-pack/pom.xml
  iiop-openjdk/pom.xml
  jpa/eclipselink/pom.xml
  jpa/hibernate-transformer/pom.xml
  jpa/hibernate4_1/pom.xml
  jpa/hibernate4_3/pom.xml
  jpa/hibernate5/pom.xml
  jpa/hibernate5_3/pom.xml
  jpa/spi/pom.xml
  pom.xml
  servlet-feature-pack/pom.xml
  servlet-feature-pack/src/license/servlet-feature-pack-licenses.xml
  servlet-feature-pack/src/main/resources/modules/system/layers/base/javax/transaction/api/main/module.xml
  servlet-galleon-pack/pom.xml
  spec-api/pom.xml
  testsuite/compat/pom.xml
  testsuite/shared/pom.xml
  transactions/pom.xml
Labels: 18.x, deps-changed, ready-for-merge, sep4

#12575 [WFLY-12474] Upgrade smallrye-metrics 2.1.4
  feature-pack/pom.xml
  feature-pack/src/license/full-feature-pack-licenses.xml
  feature-pack/src/main/resources/modules/system/layers/base/io/smallrye/metrics/main/module.xml
  galleon-pack/pom.xml
  microprofile/metrics-smallrye/pom.xml
  pom.xml
Labels: deps-changed, ready-for-merge, sep4

#12576 WFLY-12471 Upgrade Narayana to 5.9.8.Final
  pom.xml
Labels: deps-ok, ready-for-merge, sep4

#12577 [WFLY-12479]: Upgrade Apache Artemis from 2.8.1 to 2.9.0
  pom.xml
Labels: deps-ok, ready-for-merge, sep4

#12578 [WFLY-12478] Upgrade WildFly Core from 10.0.0.Beta5 to 10.0.0.Beta6
  pom.xml
Labels: deps-ok, ready-for-merge, sep4

#12570 Revert Temporary WFLY-12373 Weld MSC Contention issue Workaround
  weld/common/src/main/java/org/jboss/as/weld/interceptors/Jsr299BindingsInterceptor.java
  weld/subsystem/src/main/java/org/jboss/as/weld/deployment/WeldClassIntrospector.java
  weld/subsystem/src/main/java/org/jboss/as/weld/interceptors/Jsr299BindingsCreateInterceptor.java
  weld/subsystem/src/main/java/org/jboss/as/weld/services/bootstrap/WeldSecurityServices.java
Labels: deps-ok

#12585 WFLY-12355 Added an exclusion on the jboss-transaction-api_1.2_spec t…
  pom.xml
Labels: deps-ok

#12583 Fix for WFLY-12482, Layers test not disabling inheritance in transitive deps
  testsuite/layers/pom.xml
Labels: deps-ok

#12490 [WFLY-6144] EJB static client interceptors
  docs/src/main/asciidoc/_admin-guide/subsystem-configuration/EJB3.adoc
  ejb3/src/main/java/org/jboss/as/ejb3/deployment/processors/EJBClientDescriptorMetaDataProcessor.java
  ejb3/src/main/java/org/jboss/as/ejb3/interceptor/server/ClientInterceptorCache.java
  ejb3/src/main/java/org/jboss/as/ejb3/subsystem/ClientInterceptorsBindingsProcessor.java
  ejb3/src/main/java/org/jboss/as/ejb3/subsystem/EJB3Subsystem60Parser.java
  ejb3/src/main/java/org/jboss/as/ejb3/subsystem/EJB3SubsystemAdd.java
  ejb3/src/main/java/org/jboss/as/ejb3/subsystem/EJB3SubsystemModel.java
  ejb3/src/main/java/org/jboss/as/ejb3/subsystem/EJB3SubsystemRootResourceDefinition.java
  ejb3/src/main/java/org/jboss/as/ejb3/subsystem/EJB3SubsystemXMLElement.java
  ejb3/src/main/java/org/jboss/as/ejb3/subsystem/EJB3SubsystemXMLPersister.java
  ejb3/src/main/java/org/jboss/as/ejb3/subsystem/EJBTransformers.java
  ejb3/src/main/java/org/jboss/as/ejb3/subsystem/StaticInterceptorsDependenciesDeploymentUnitProcessor.java
  ejb3/src/main/java/org/jboss/as/ejb3/subsystem/deployment/Attachments.java
  ejb3/src/main/resources/org/jboss/as/ejb3/subsystem/LocalDescriptions.properties
  ejb3/src/main/resources/schema/wildfly-ejb3_6_0.xsd
  ejb3/src/test/java/org/jboss/as/ejb3/subsystem/Ejb3TransformersTestCase.java
  ejb3/src/test/resources/org/jboss/as/ejb3/subsystem/subsystem-ejb3-transform-reject.xml
  ejb3/src/test/resources/org/jboss/as/ejb3/subsystem/subsystem.xml
  testsuite/integration/multinode/src/test/java/org/jboss/as/test/multinode/clientinterceptor/ClientInterceptor.java
  testsuite/integration/multinode/src/test/java/org/jboss/as/test/multinode/clientinterceptor/RemoteCallClientInterceptorTestCase.java
  testsuite/integration/multinode/src/test/java/org/jboss/as/test/multinode/clientinterceptor/StatelessBean.java
  testsuite/integration/multinode/src/test/java/org/jboss/as/test/multinode/clientinterceptor/StatelessRemote.java
  testsuite/integration/multinode/src/test/java/org/jboss/as/test/multinode/clientinterceptor/module.xml
  testsuite/integration/multinode/src/test/java/org/jboss/as/test/multinode/clientinterceptor/multiple/ExceptionClientInterceptor.java
  testsuite/integration/multinode/src/test/java/org/jboss/as/test/multinode/clientinterceptor/multiple/MultipleClientInterceptorTestCase.java
  testsuite/integration/multinode/src/test/java/org/jboss/as/test/multinode/clientinterceptor/multiple/first-module.xml
  testsuite/integration/multinode/src/test/java/org/jboss/as/test/multinode/clientinterceptor/multiple/second-module.xml
  testsuite/integration/multinode/src/test/java/org/jboss/as/test/multinode/clientinterceptor/protocol/ProtocolSampleClientInterceptor.java
  testsuite/integration/multinode/src/test/java/org/jboss/as/test/multinode/clientinterceptor/protocol/RemoteProtocolChangeClientInterceptorTestCase.java
  testsuite/integration/multinode/src/test/java/org/jboss/as/test/multinode/clientinterceptor/protocol/jboss-ejb-client.xml
  testsuite/integration/multinode/src/test/java/org/jboss/as/test/multinode/clientinterceptor/protocol/module.xml
  testsuite/integration/multinode/src/test/java/org/jboss/as/test/multinode/clientinterceptor/secured/EjbSecurityDomainSetup.java
  testsuite/integration/multinode/src/test/java/org/jboss/as/test/multinode/clientinterceptor/secured/SampleSecureInterceptor.java
  testsuite/integration/multinode/src/test/java/org/jboss/as/test/multinode/clientinterceptor/secured/Secured.java
  testsuite/integration/multinode/src/test/java/org/jboss/as/test/multinode/clientinterceptor/secured/SecuredBean.java
  testsuite/integration/multinode/src/test/java/org/jboss/as/test/multinode/clientinterceptor/secured/SecuredBeanClientInterceptorTestCase.java
  testsuite/integration/multinode/src/test/java/org/jboss/as/test/multinode/clientinterceptor/secured/jboss-web.xml
  testsuite/integration/multinode/src/test/java/org/jboss/as/test/multinode/clientinterceptor/secured/module.xml
  testsuite/integration/multinode/src/test/java/org/jboss/as/test/multinode/clientinterceptor/secured/roles.properties
  testsuite/integration/multinode/src/test/java/org/jboss/as/test/multinode/clientinterceptor/secured/users.properties
  testsuite/shared/src/main/java/org/jboss/as/test/shared/integration/interceptor/clientside/AbstractClientInterceptorsSetupTask.java
  testsuite/shared/src/main/java/org/jboss/as/test/shared/integration/interceptor/clientside/InterceptorModule.java
  testsuite/shared/src/main/java/org/jboss/as/test/shared/integration/interceptor/clientside/InterceptorsSetupTask.java
  testsuite/shared/src/main/java/org/jboss/as/test/shared/util/ClientInterceptorUtil.java
  testsuite/shared/src/main/java/org/wildfly/test/security/common/elytron/EjbElytronDomainSetup.java
Labels: Feature, deps-ok, sep4

#12556 [WFLY-12087]:Upgrade CXF to 3.3.3
  pom.xml
  testsuite/integration/xts/src/test/java/org/jboss/as/test/xts/suspend/AbstractTestCase.java
  testsuite/integration/xts/src/test/java/org/jboss/as/test/xts/suspend/wsat/AtomicTransactionSuspendTestCase.java
Labels: deps-ok, sep4

#12579 [WFLY-12202] Add documentation for the `principal-transformer` attribute in aggregate-realm
  docs/src/main/asciidoc/_elytron/Elytron_Subsystem.adoc
  docs/src/main/asciidoc/_elytron/Subsystem_Component_Documentation.adoc
  docs/src/main/asciidoc/_elytron/components/Aggregate_Security_Realm.adoc
  testsuite/integration/elytron/src/test/java/org/wildfly/test/integration/elytron/realm/AggregateRealmTestCase.java
  testsuite/integration/elytron/src/test/java/org/wildfly/test/integration/elytron/realm/AggregateRealmUtil.java
  testsuite/integration/elytron/src/test/java/org/wildfly/test/integration/elytron/realm/AggregateRealmWithTransformerTestCase.java
  testsuite/integration/elytron/src/test/java/org/wildfly/test/integration/elytron/realm/AggregateRealmWrongPrincipalSetupTestCase.java
  testsuite/integration/elytron/src/test/java/org/wildfly/test/integration/elytron/realm/RoleServlets.java
  testsuite/integration/elytron/src/test/java/org/wildfly/test/integration/elytron/realm/aggregate-realm-with-transformer-web.xml
  testsuite/shared/src/main/java/org/wildfly/test/security/common/elytron/AggregateSecurityRealm.java
  testsuite/shared/src/main/java/org/wildfly/test/security/common/elytron/servlet/AttributePrintingServlet.java
Labels: 18.x, Feature-Docs, deps-ok, sep4

#12582 WFLY-12339: upgrade PicketLink to 2.5.5.SP12-redhat-00006 to fix CVE-…
  pom.xml
Labels: deps-ok, sep4

#12586 [WFLY-12433] Move to jboss-jaxrs-api_2.1_spec to 2.0.0.CR2
  pom.xml
Labels: deps-ok, sep4

#12591 [WFLY-12495] Separate out feature groups related to clustering
  galleon-pack/src/main/resources/feature_groups/basic-profile.xml
  galleon-pack/src/main/resources/feature_groups/distributable-web-local.xml
  galleon-pack/src/main/resources/feature_groups/distributable-web.xml
  galleon-pack/src/main/resources/feature_groups/infinispan-dist-ejb.xml
  galleon-pack/src/main/resources/feature_groups/infinispan-dist-hibernate.xml
  galleon-pack/src/main/resources/feature_groups/infinispan-dist-server.xml
  galleon-pack/src/main/resources/feature_groups/infinispan-dist-web.xml
  galleon-pack/src/main/resources/feature_groups/infinispan-dist.xml
  galleon-pack/src/main/resources/feature_groups/infinispan-local-ejb.xml
  galleon-pack/src/main/resources/feature_groups/infinispan-local-server.xml
  galleon-pack/src/main/resources/feature_groups/infinispan-local-web.xml
  galleon-pack/src/main/resources/feature_groups/infinispan-local.xml
  galleon-pack/src/main/resources/feature_groups/jgroups-all.xml
Labels: deps-ok

#12593 Fix for WFLY-12498, wildfly-clustering-web-* deps missing provided sc…
  galleon-pack/pom.xml
  servlet-galleon-pack/pom.xml
Labels: deps-ok, ready-for-merge

#12605 Ignore DynamicJNDIContextEJBInvocationTestCase
  testsuite/integration/multinode/src/test/java/org/jboss/as/test/multinode/remotecall/scoped/context/DynamicJNDIContextEJBInvocationTestCase.java
Labels: deps-ok

#12608 WFLY-12513 Invalid logger exclude in org.wildfly.clustering.web.hotrod module.xml
  clustering/web/hotrod/src/main/java/org/wildfly/clustering/web/hotrod/logging/Logger.java
  clustering/web/hotrod/src/main/java/org/wildfly/clustering/web/hotrod/session/ExpiredSessionRemover.java
  clustering/web/hotrod/src/main/java/org/wildfly/clustering/web/hotrod/session/HotRodSessionManager.java
  clustering/web/hotrod/src/main/java/org/wildfly/clustering/web/hotrod/session/SessionExpirationScheduler.java
  clustering/web/hotrod/src/main/java/org/wildfly/clustering/web/hotrod/session/coarse/CoarseSessionAttributesFactory.java
  clustering/web/hotrod/src/main/java/org/wildfly/clustering/web/hotrod/session/fine/FineSessionAttributesFactory.java
  clustering/web/hotrod/src/main/java/org/wildfly/clustering/web/hotrod/sso/HotRodSSOFactory.java
  feature-pack/src/main/resources/modules/system/layers/base/org/wildfly/clustering/web/hotrod/main/module.xml
Labels: deps-ok

#12609 [WFLY-12514] Switch ServerReload.reloadIfRequired(ModelControllerClie…
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/ejb/client/descriptor/EJBClientDescriptorTestCase.java
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/security/aselytron/SecurityDomainAsElytronSecurityRealmTestCase.java
  testsuite/integration/elytron/src/test/java/org/wildfly/test/integration/elytron/audit/AbstractAuditLogTestCase.java
  testsuite/integration/elytron/src/test/java/org/wildfly/test/integration/elytron/audit/CustomSecurityEventListenerTestCase.java
  testsuite/integration/elytron/src/test/java/org/wildfly/test/integration/elytron/audit/FileAuditLogTestCase.java
  testsuite/integration/elytron/src/test/java/org/wildfly/test/integration/elytron/audit/TCPSyslogAuditLogTestCase.java
  testsuite/integration/elytron/src/test/java/org/wildfly/test/integration/elytron/audit/TLSSyslogAuditLogTestCase.java
  testsuite/integration/elytron/src/test/java/org/wildfly/test/integration/elytron/audit/UDPSyslogAuditLogTestCase.java
  testsuite/integration/elytron/src/test/java/org/wildfly/test/integration/elytron/principaltransformers/ChainedPrincipalTransformerTestCase.java
  testsuite/integration/elytron/src/test/java/org/wildfly/test/integration/elytron/principaltransformers/ConstantPrincipalTransformerTestCase.java
  testsuite/integration/elytron/src/test/java/org/wildfly/test/integration/elytron/principaltransformers/RegexPrincipalTransformerTestCase.java
  testsuite/integration/elytron/src/test/java/org/wildfly/test/integration/elytron/principaltransformers/RegexValidatingPrincipalTransformerTestCase.java
  testsuite/integration/elytron/src/test/java/org/wildfly/test/integration/elytron/realm/LdapRealmTestCase.java
  testsuite/integration/elytron/src/test/java/org/wildfly/test/integration/elytron/realmmappers/ConstantRealmMapperTestCase.java
  testsuite/integration/elytron/src/test/java/org/wildfly/test/integration/elytron/realmmappers/MappedRegexRealmMapperTestCase.java
  testsuite/integration/elytron/src/test/java/org/wildfly/test/integration/elytron/realmmappers/SimpleRegexRealmMapperTestCase.java
  testsuite/integration/elytron/src/test/java/org/wildfly/test/integration/elytron/roledecoders/SimpleRoleDecoderTestCase.java
  testsuite/integration/manualmode/src/test/java/org/jboss/as/test/manualmode/ejb/client/outbound/connection/security/ElytronRemoteOutboundConnectionTestCase.java
  testsuite/integration/smoke/src/test/java/org/jboss/as/test/smoke/messaging/client/messaging/MessagingClientTestCase.java
  testsuite/shared/src/main/java/org/jboss/as/test/shared/ServerReload.java
  testsuite/shared/src/main/java/org/wildfly/test/security/common/AbstractElytronSetupTask.java
  testsuite/shared/src/main/java/org/wildfly/test/security/common/elytron/EjbElytronDomainSetup.java
Labels: deps-ok

#12534 [WFLY-12384] enforce managed executors use thread factory without a c…
  ee/src/main/java/org/jboss/as/ee/concurrent/ManagedExecutorServiceImpl.java
  ee/src/main/java/org/jboss/as/ee/concurrent/ManagedScheduledExecutorServiceImpl.java
  ee/src/main/java/org/jboss/as/ee/concurrent/ManagedThreadFactoryImpl.java
  ee/src/main/java/org/jboss/as/ee/concurrent/service/ManagedExecutorServiceService.java
  ee/src/main/java/org/jboss/as/ee/concurrent/service/ManagedScheduledExecutorServiceService.java
  ee/src/main/java/org/jboss/as/ee/concurrent/service/ManagedThreadFactoryService.java
  ee/src/main/java/org/jboss/as/ee/subsystem/ManagedExecutorServiceAdd.java
  ee/src/main/java/org/jboss/as/ee/subsystem/ManagedScheduledExecutorServiceAdd.java
  ee/src/main/java/org/jboss/as/ee/subsystem/ManagedThreadFactoryResourceDefinition.java
Labels: deps-ok, ready-for-merge

#12572 [WFLY-12427] Add missing dependencies for smallrye-health
  feature-pack/src/main/resources/modules/system/layers/base/io/smallrye/health/main/module.xml
  feature-pack/src/main/resources/modules/system/layers/base/org/wildfly/extension/microprofile/health-smallrye/main/module.xml
  testsuite/integration/basic/src/test/java/org/wildfly/test/integration/microprofile/opentracing/EarOpenTracingWithWeldProbeTestCase.java
Labels: deps-ok, ready-for-merge

#12588 WFLY-12487 Include the original cause of failure, if jsf-injection module load fails
  jsf/subsystem/src/main/java/org/jboss/as/jsf/deployment/JSFDependencyProcessor.java
  jsf/subsystem/src/main/java/org/jboss/as/jsf/logging/JSFLogger.java
Labels: deps-ok, ready-for-merge

#12596 [WFLY-12497] Upgrade Generic JMS RA 2.0.2.Final
  pom.xml
Labels: deps-ok, ready-for-merge

#12600 [WFLY-12392] Removing javaee.api dependency from JSF modules
  feature-pack/src/main/resources/modules/system/layers/base/com/sun/jsf-impl/main/module.xml
  jsf/multi-jsf-installer/src/main/resources/mojarra-impl-module.xml
  jsf/multi-jsf-installer/src/main/resources/myfaces-impl-module.xml
Labels: deps-ok, ready-for-merge

#12598 WFLY-12508 Replace CompositeCharSequence with version from wildfly-common
  servlet-feature-pack/src/main/resources/modules/system/layers/base/org/jboss/as/web-common/main/module.xml
  web-common/src/main/java/org/jboss/as/web/session/CompositeCharSequence.java
  web-common/src/main/java/org/jboss/as/web/session/SimpleRoutingSupport.java
  web-common/src/test/java/org/jboss/as/web/session/CompositeCharSequenceTestCase.java
Labels: deps-ok

#12616 WFLY-12429 MockitoException in InfinispanBeanTestCase on latest JDK13
  clustering/ejb/infinispan/src/test/java/org/wildfly/clustering/ejb/infinispan/bean/InfinispanBeanTestCase.java
Labels: deps-ok

#12618 [WFLY-12512] Correctly tear down Elytron EJB integration tests config…
  testsuite/shared/src/main/java/org/jboss/as/test/shared/integration/interceptor/clientside/AbstractClientInterceptorsSetupTask.java
  testsuite/shared/src/main/java/org/wildfly/test/security/common/elytron/EjbElytronDomainSetup.java
  testsuite/shared/src/main/java/org/wildfly/test/security/common/elytron/Utils.java
Labels: deps-ok

#12613 [WFLY-12519] Set version to null all the time in close method of MixedDomainTestSuite
  testsuite/mixed-domain/src/test/java/org/jboss/as/test/integration/domain/mixed/MixedDomainTestSuite.java
Labels: deps-ok

#12589 WFLY-12480 Switch from javax.persistence:javax.persistence-api to jakarta.persistence:jakarta.persistence-api
  appclient/pom.xml
  ejb3/pom.xml
  feature-pack/pom.xml
  feature-pack/src/license/full-feature-pack-licenses.xml
  feature-pack/src/main/resources/modules/system/layers/base/javax/persistence/api/main/module.xml
  galleon-pack/pom.xml
  jpa/hibernate5/pom.xml
  jpa/hibernate5_3/pom.xml
  jpa/spi/pom.xml
  pom.xml
  spec-api/pom.xml
  testsuite/integration/basic/pom.xml
  testsuite/integration/legacy-ejb-client/pom.xml
  testsuite/integration/picketlink/pom.xml
  testsuite/integration/xts/pom.xml
Labels: deps-changed

#12620 WFLY-12528 Updated to jakarta.enterprise:jakarta.enterprise.cdi-api:2.0.2
  jpa/spi/pom.xml
  jpa/subsystem/pom.xml
  picketlink/pom.xml
  pom.xml
  servlet-feature-pack/pom.xml
  servlet-feature-pack/src/license/servlet-feature-pack-licenses.xml
  servlet-feature-pack/src/main/resources/modules/system/layers/base/javax/enterprise/api/main/module.xml
  servlet-galleon-pack/pom.xml
  spec-api/pom.xml
  testsuite/integration/pom.xml
  testsuite/mixed-domain/pom.xml
  testsuite/shared/pom.xml
Labels: deps-changed, ready-for-merge

#12619 WFLY-12395 Upgrade JGroups to 4.1.4.Final
  pom.xml
Labels: deps-ok

#12624 [WFLY-12531] Upgrade org.jboss.spec.javax.servlet.jboss-servlet-api_4…
  pom.xml
  servlet-feature-pack/src/license/servlet-feature-pack-licenses.xml
Labels: deps-ok

#12617 [WFLY-12524] Move com.sun.mail:javax.mail:1.6.2 to com.sun.mail.mail:jakar…
  bean-validation/pom.xml
  connector/pom.xml
  feature-pack/pom.xml
  feature-pack/src/license/full-feature-pack-licenses.xml
  feature-pack/src/main/resources/modules/system/layers/base/javax/mail/api/main/module.xml
  galleon-pack/pom.xml
  mail/pom.xml
  pom.xml
  servlet-feature-pack/pom.xml
  servlet-feature-pack/src/license/servlet-feature-pack-licenses.xml
  servlet-feature-pack/src/main/resources/modules/system/layers/base/javax/validation/api/main/module.xml
  servlet-galleon-pack/pom.xml
  spec-api/pom.xml
  testsuite/integration/basic/pom.xml
  webservices/tests-integration/pom.xml
Labels: deps-changed, ready-for-merge

#12621 [WFLY-12526] Ensure isUserInRole uses a PrivilegedAction as the deployments ProtectionDomain is not relevant.
  undertow/src/main/java/org/wildfly/extension/undertow/security/JbossAuthorizationManager.java
  undertow/src/main/java/org/wildfly/extension/undertow/security/SecurityActions.java
Labels: 18.x, Blocker, deps-ok

#12627 Wfly 12300
  feature-pack/pom.xml
  feature-pack/src/license/full-feature-pack-licenses.xml
  galleon-pack/pom.xml
  pom.xml
  servlet-feature-pack/src/license/servlet-feature-pack-licenses.xml
  servlet-feature-pack/src/main/resources/content/docs/licenses/gnu general public license version 2, with classpath exception.txt
Labels: deps-ok

#12614 WFLY-12505 Dependency cleanup of clustering modules
  clustering/api/pom.xml
  clustering/common/pom.xml
  clustering/ee/cache/pom.xml
  clustering/ee/hotrod/pom.xml
  clustering/ee/infinispan/pom.xml
  clustering/ee/pom.xml
  clustering/ee/spi/pom.xml
  clustering/ejb/infinispan/pom.xml
  clustering/ejb/pom.xml
  clustering/ejb/spi/pom.xml
  clustering/infinispan/client/pom.xml
  clustering/infinispan/extension/pom.xml
  clustering/infinispan/pom.xml
  clustering/infinispan/spi/pom.xml
  clustering/jgroups/api/pom.xml
  clustering/jgroups/pom.xml
  clustering/jgroups/spi/pom.xml
  clustering/marshalling/api/pom.xml
  clustering/marshalling/infinispan/pom.xml
  clustering/marshalling/jboss/pom.xml
  clustering/marshalling/spi/pom.xml
  clustering/pom.xml
  clustering/server/pom.xml
  clustering/service/pom.xml
  clustering/singleton/api/pom.xml
  clustering/singleton/extension/pom.xml
  clustering/singleton/pom.xml
  clustering/spi/pom.xml
  clustering/web/api/pom.xml
  clustering/web/cache/pom.xml
  clustering/web/container/pom.xml
  clustering/web/extension/pom.xml
  clustering/web/hotrod/pom.xml
  clustering/web/infinispan/pom.xml
  clustering/web/pom.xml
  clustering/web/spi/pom.xml
  clustering/web/undertow/pom.xml
  feature-pack/src/main/resources/modules/system/layers/base/org/apache/activemq/artemis/main/module.xml
  feature-pack/src/main/resources/modules/system/layers/base/org/infinispan/main/module.xml
  feature-pack/src/main/resources/modules/system/layers/base/org/jboss/as/clustering/infinispan/main/module.xml
  feature-pack/src/main/resources/modules/system/layers/base/org/jboss/as/clustering/jgroups/main/module.xml
  feature-pack/src/main/resources/modules/system/layers/base/org/jboss/ironjacamar/impl/main/module.xml
  feature-pack/src/main/resources/modules/system/layers/base/org/wildfly/clustering/ee/hotrod/main/module.xml
  feature-pack/src/main/resources/modules/system/layers/base/org/wildfly/clustering/ee/infinispan/main/module.xml
  feature-pack/src/main/resources/modules/system/layers/base/org/wildfly/clustering/ejb/infinispan/main/module.xml
  feature-pack/src/main/resources/modules/system/layers/base/org/wildfly/clustering/ejb/spi/main/module.xml
  feature-pack/src/main/resources/modules/system/layers/base/org/wildfly/clustering/infinispan/client/main/module.xml
  feature-pack/src/main/resources/modules/system/layers/base/org/wildfly/clustering/infinispan/spi/main/module.xml
  feature-pack/src/main/resources/modules/system/layers/base/org/wildfly/clustering/jgroups/spi/main/module.xml
  feature-pack/src/main/resources/modules/system/layers/base/org/wildfly/clustering/marshalling/jboss/main/module.xml
  feature-pack/src/main/resources/modules/system/layers/base/org/wildfly/clustering/spi/main/module.xml
  feature-pack/src/main/resources/modules/system/layers/base/org/wildfly/clustering/web/cache/main/module.xml
  feature-pack/src/main/resources/modules/system/layers/base/org/wildfly/clustering/web/hotrod/main/module.xml
  feature-pack/src/main/resources/modules/system/layers/base/org/wildfly/clustering/web/infinispan/main/module.xml
  feature-pack/src/main/resources/modules/system/layers/base/org/wildfly/clustering/web/spi/main/module.xml
  feature-pack/src/main/resources/modules/system/layers/base/org/wildfly/clustering/web/undertow/main/module.xml
  servlet-feature-pack/src/main/resources/modules/system/layers/base/org/jboss/as/clustering/common/main/module.xml
  servlet-feature-pack/src/main/resources/modules/system/layers/base/org/wildfly/clustering/service/main/module.xml
  servlet-feature-pack/src/main/resources/modules/system/layers/base/org/wildfly/clustering/web/container/main/module.xml
  servlet-feature-pack/src/main/resources/modules/system/layers/base/org/wildfly/extension/undertow/main/module.xml
Labels: deps-ok

#12629 More javax to Jakarta moves
  pom.xml
  servlet-feature-pack/src/license/servlet-feature-pack-licenses.xml
  testsuite/integration/basic/src/test/java/org/wildfly/test/integration/jsp/JspELTestCase.java
Labels: 18.x, Blocker, deps-changed

#12625 WFLY-12539 Do not auto-update legacy JGroup protocols in domain contr…
  clustering/jgroups/extension/src/main/java/org/jboss/as/clustering/jgroups/subsystem/ProtocolRegistration.java
  testsuite/domain/src/test/java/org/jboss/as/test/integration/domain/LegacyJGroupsProtocolsTestCase.java
Labels: deps-ok, ready-for-merge

#12641 Upgrade jboss-connector-api_1.7_spec to 2.0.0.Final
  pom.xml
Labels: deps-ok, ready-for-merge

#12638 WFLY-12534 WFLY-12546 WFLY-12550 - Upgrade Hibernate ORM to 5.3.12.Final; Hibernate Search to 5.10.7; ByteBuddy to 1.9.11
  feature-pack/src/main/resources/modules/system/layers/base/org/hibernate/main/module.xml
  pom.xml
Labels: deps-ok, ready-for-merge

#12639 [WFLY-12552] Upgrade wildfly-build-tools to 1.2.12.Final
  pom.xml
Labels: deps-ok

#12644 [WFLY-12300] Further updates to final API releases
  feature-pack/pom.xml
  galleon-pack/pom.xml
  pom.xml
Labels: deps-changed

#12642 [WFLY-12558] See if allowing reconnect attempts solves the intermitte…
  testsuite/integration/elytron/src/test/java/org/wildfly/test/integration/elytron/audit/TCPSyslogAuditLogTestCase.java
  testsuite/shared/src/main/java/org/wildfly/test/security/common/elytron/SyslogAuditLog.java
Labels: deps-ok

#12640 [WFLY-12554][WFLY-12555] upgrade smallrye health 2.0 & MP Health 2.1
  feature-pack/pom.xml
  feature-pack/src/license/full-feature-pack-licenses.xml
  feature-pack/src/main/resources/modules/system/layers/base/io/smallrye/health/main/module.xml
  galleon-pack/pom.xml
  microprofile/health-smallrye/pom.xml
  pom.xml
  testsuite/integration/microprofile-tck/health/pom.xml
  testsuite/integration/microprofile-tck/health/tck-suite.xml
Labels: 18.x, Blocker, deps-changed

#12633 WFLY-11764
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/web/servlet/preservepath/ForwardingServlet.java
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/web/servlet/preservepath/PreservePathFilter.java
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/web/servlet/preservepath/PreservePathTestCase.java
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/web/servlet/preservepath/preserve-path.jsp
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/web/servlet/preservepath/web.xml
  undertow/src/main/java/org/wildfly/extension/undertow/ServletContainerAdd.java
  undertow/src/main/java/org/wildfly/extension/undertow/ServletContainerService.java
  undertow/src/main/java/org/wildfly/extension/undertow/deployment/UndertowDeploymentInfoService.java
Labels: deps-ok

#12630 [WFLY-12540] Move from javax.activation:activation:1.1.1 to com.sun.a…
  bean-validation/pom.xml
  pom.xml
  servlet-feature-pack/pom.xml
  servlet-feature-pack/src/license/servlet-feature-pack-licenses.xml
  servlet-feature-pack/src/main/resources/modules/system/layers/base/javax/activation/api/main/module.xml
  servlet-galleon-pack/pom.xml
  testsuite/integration/basic/pom.xml
  testsuite/integration/manualmode/pom.xml
  testsuite/integration/rts/pom.xml
  testsuite/integration/smoke/pom.xml
  testsuite/integration/ws/pom.xml
  testsuite/integration/xts/pom.xml
  testsuite/layers/pom.xml
  testsuite/mixed-domain/pom.xml
Labels: deps-changed

#12622 [WFLY-12529] add permissions for DefaultConcurrencyCDITestCase
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/ee/naming/defaultbindings/concurrency/DefaultConcurrencyCDITestCase.java
Labels: deps-ok

#12508 [WFLY-12394] Execute portions of the testsuite using a slimmed server instead of the normal dist
  feature-pack/src/main/resources/modules/system/layers/base/org/wildfly/transaction/client/main/module.xml
  pom.xml
  servlet-galleon-pack/src/main/resources/feature_groups/undertow-elytron-security.xml
  testsuite/integration/basic/pom.xml
  testsuite/integration/basic/src/test/config/arq/arquillian.xml
  testsuite/integration/microprofile-tck/config/pom.xml
  testsuite/integration/microprofile-tck/config/src/test/resources/arquillian.xml
  testsuite/integration/microprofile-tck/health/pom.xml
  testsuite/integration/microprofile-tck/health/src/test/resources/arquillian.xml
  testsuite/integration/microprofile-tck/metrics/pom.xml
  testsuite/integration/microprofile-tck/metrics/src/test/resources/arquillian.xml
  testsuite/integration/microprofile-tck/opentracing/pom.xml
  testsuite/integration/microprofile-tck/opentracing/src/test/resources/arquillian.xml
  testsuite/integration/microprofile-tck/pom.xml
  testsuite/integration/pom.xml
  testsuite/integration/smoke/pom.xml
  testsuite/integration/smoke/src/test/config/arq/arquillian.xml
  testsuite/integration/web/pom.xml
  testsuite/integration/web/src/test/config/arq/arquillian.xml
  testsuite/integration/web/src/test/java/org/jboss/as/test/integration/web/formauth/FormAuthUnitTestCase.java
  testsuite/layers/pom.xml
  testsuite/pom.xml
  testsuite/test-feature-pack/pom.xml
  testsuite/test-feature-pack/src/main/resources/layers/standalone/cloud-server/layer-spec.xml
  testsuite/test-feature-pack/src/main/resources/layers/standalone/datasources-web-server/layer-spec.xml
  testsuite/test-feature-pack/src/main/resources/layers/standalone/jaxrs-server/layer-spec.xml
  testsuite/test-feature-pack/src/main/resources/layers/standalone/jpa-distributed/layer-spec.xml
  testsuite/test-feature-pack/src/main/resources/layers/standalone/web-clustering/layer-spec.xml
  testsuite/test-feature-pack/wildfly-feature-pack-build.xml
Labels: deps-ok

#12649 WFLY-12449 update the license for jboss-ejb-api_3.2_spec in full-feat…
  feature-pack/src/license/full-feature-pack-licenses.xml
Labels: deps-ok

#12650 [WFLY-12561] Upgrade J2EE Management API spec to 2.0.0.Final
  feature-pack/src/license/full-feature-pack-licenses.xml
  pom.xml
Labels: deps-ok

#12653 [WFLY-12562] Upgrade WildFly Core 10.0.0.Beta9
  pom.xml
Labels: 18.x, Blocker, deps-ok

#12632 [WFLY-12311] Use smallrye-metrics to expose subsystem metrics
  feature-pack/pom.xml
  feature-pack/src/main/resources/modules/system/layers/base/io/prometheus/simpleclient/main/module.xml
  feature-pack/src/main/resources/modules/system/layers/base/org/wildfly/extension/microprofile/metrics-smallrye/main/module.xml
  galleon-pack/pom.xml
  microprofile/metrics-smallrye/pom.xml
  microprofile/metrics-smallrye/src/main/java/org/wildfly/extension/microprofile/metrics/MetricCollector.java
  microprofile/metrics-smallrye/src/main/java/org/wildfly/extension/microprofile/metrics/MetricsCollectorService.java
  microprofile/metrics-smallrye/src/main/java/org/wildfly/extension/microprofile/metrics/MetricsContextService.java
  microprofile/metrics-smallrye/src/main/java/org/wildfly/extension/microprofile/metrics/PrometheusCollector.java
  microprofile/metrics-smallrye/src/main/java/org/wildfly/extension/microprofile/metrics/UnitConverter.java
  pom.xml
Labels: 18.x, Blocker, deps-changed, ready-for-merge

#12455 [WFLY-12332] Basic integration tests for OCSP
  testsuite/integration/elytron/pom.xml
  testsuite/integration/elytron/src/test/java/org/wildfly/test/integration/elytron/certs/CommonBase.java
  testsuite/integration/elytron/src/test/java/org/wildfly/test/integration/elytron/certs/crl/CertificateRevocationListTestBase.java
  testsuite/integration/elytron/src/test/java/org/wildfly/test/integration/elytron/certs/crl/CertificateRevocationListTestCase.java
  testsuite/integration/elytron/src/test/java/org/wildfly/test/integration/elytron/certs/ocsp/OcspResponderDownTestCase.java
  testsuite/integration/elytron/src/test/java/org/wildfly/test/integration/elytron/certs/ocsp/OcspTestBase.java
  testsuite/integration/elytron/src/test/java/org/wildfly/test/integration/elytron/certs/ocsp/OcspTestCase.java
  testsuite/integration/elytron/src/test/java/org/wildfly/test/integration/elytron/certs/ocsp/TestingOcspServer.java
  testsuite/integration/elytron/src/test/resources/org/wildfly/test/integration/elytron/certs/ocsp/ocsp-db.properties
  testsuite/integration/elytron/src/test/resources/org/wildfly/test/integration/elytron/certs/ocsp/ocsp-responder.xml
  testsuite/shared/src/main/java/org/wildfly/test/security/common/elytron/CertificateRevocationList.java
  testsuite/shared/src/main/java/org/wildfly/test/security/common/elytron/Ocsp.java
  testsuite/shared/src/main/java/org/wildfly/test/security/common/elytron/SimpleTrustManager.java
Labels: 18.x, deps-ok

#12654 [WFLY-12509] Upgrade jboss-jsf-api_2.3_spec to 3.0.0.Final
  feature-pack/src/license/full-feature-pack-licenses.xml
  pom.xml
Labels: 18.x, deps-ok

#12645 [WFLY-12542] MP Metrics should require the MP Config capability.
  microprofile/config-smallrye/src/main/java/org/wildfly/extension/microprofile/config/smallrye/MicroProfileConfigSubsystemAdd.java
  microprofile/config-smallrye/src/main/java/org/wildfly/extension/microprofile/config/smallrye/MicroProfileConfigSubsystemRemove.java
  microprofile/config-smallrye/src/main/java/org/wildfly/extension/microprofile/config/smallrye/MicroProfileSubsystemDefinition.java
  microprofile/metrics-smallrye/src/main/java/org/wildfly/extension/microprofile/metrics/MetricsCollectorService.java
  microprofile/metrics-smallrye/src/main/java/org/wildfly/extension/microprofile/metrics/MicroProfileMetricsSubsystemDefinition.java
Labels: deps-ok

#12623 [WFLY-12530] Add doPrivileged calls to access the AuthConfigFactory.
  undertow/src/main/java/org/wildfly/extension/undertow/security/jaspi/JASPICSecurityContext.java
  undertow/src/main/java/org/wildfly/extension/undertow/security/jaspi/SecurityActions.java
Labels: deps-ok

#12107 [WFLY-11764] Expose UndertowOptions.PRESERVE_PATH_ON_FORWARD in Under…
  docs/src/main/asciidoc/_admin-guide/subsystem-configuration/Undertow.adoc
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/web/servlet/preservepath/PreservePathFilter.java
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/web/servlet/preservepath/PreservePathTestCase.java
  undertow/src/main/java/org/wildfly/extension/undertow/Constants.java
  undertow/src/main/java/org/wildfly/extension/undertow/ServletContainerAdd.java
  undertow/src/main/java/org/wildfly/extension/undertow/ServletContainerDefinition.java
  undertow/src/main/java/org/wildfly/extension/undertow/UndertowSubsystemParser_10_0.java
  undertow/src/main/java/org/wildfly/extension/undertow/UndertowTransformers.java
  undertow/src/main/resources/org/wildfly/extension/undertow/LocalDescriptions.properties
  undertow/src/main/resources/schema/wildfly-undertow_10_0.xsd
  undertow/src/test/java/org/wildfly/extension/undertow/UndertowTransformersTestCase.java
  undertow/src/test/resources/org/wildfly/extension/undertow/undertow-10.0.xml
  undertow/src/test/resources/org/wildfly/extension/undertow/undertow-reject.xml
Labels: 18.x, Feature, deps-ok, ready-for-merge

#12657 [WFLY-12565] Downgrade Yasson from 1.0.4 to 1.0.3
  pom.xml
Labels: 18.x, Blocker, deps-ok

#12612 WFLY-12518: prevent IllegalStateException while creation of RealmUse…
  security/api/src/main/java/org/jboss/as/security/api/ConnectionSecurityContext.java
Labels: deps-ok

#12656 Just a couple minor pom fixes that were missed in some Jakarta EE changes
  pom.xml
Labels: deps-ok

#12305 Fix for WFLY-11990, Separate opentracing from observability layer
  docs/src/main/asciidoc/_admin-guide/Galleon_provisioning.adoc
  galleon-pack/src/main/resources/layers/standalone/observability/layer-spec.xml
  galleon-pack/src/main/resources/layers/standalone/open-tracing/layer-spec.xml
  testsuite/layers/pom.xml
Labels: deps-ok, ready-for-merge

#12558 [WFLY-12457] Single action timer is not triggered automatically after a DB outage, requires server restart
  ejb3/src/main/java/org/jboss/as/ejb3/timerservice/TimerImpl.java
  ejb3/src/main/java/org/jboss/as/ejb3/timerservice/TimerServiceImpl.java
  ejb3/src/main/java/org/jboss/as/ejb3/timerservice/persistence/TimerPersistence.java
  ejb3/src/main/java/org/jboss/as/ejb3/timerservice/persistence/database/DatabaseTimerPersistence.java
Labels: deps-ok, ready-for-merge

#12631 WFLY-12545 fix IllegalArgumentException when list-clear persist empty…
  ejb3/src/main/java/org/jboss/as/ejb3/subsystem/EJB3Subsystem12Parser.java
Labels: deps-ok, ready-for-merge

#12651 [WFLY-12557] Fix CDI injection of health check probes
  feature-pack/src/main/resources/modules/system/layers/base/org/eclipse/microprofile/health/api/main/module.xml
  microprofile/health-smallrye/src/main/java/org/wildfly/extension/microprofile/health/deployment/CDIExtension.java
  testsuite/integration/microprofile-tck/health/pom.xml
  testsuite/integration/microprofile-tck/health/tck-suite.xml
Labels: 18.x, deps-ok, ready-for-merge

#12655 Remove obsolete files used in legacy ejb3 transformer tests
  ejb3/src/test/resources/org/jboss/as/ejb3/subsystem/timer_path_expr.xml
  ejb3/src/test/resources/org/jboss/as/ejb3/subsystem/transform_1_1_0.xml
  ejb3/src/test/resources/org/jboss/as/ejb3/subsystem/transform_1_1_0_expressions.xml
  ejb3/src/test/resources/org/jboss/as/ejb3/subsystem/transform_1_2_0_reject.xml
  ejb3/src/test/resources/org/jboss/as/ejb3/subsystem/transform_1_2_1.xml
  ejb3/src/test/resources/org/jboss/as/ejb3/subsystem/transform_1_3_0.xml
  ejb3/src/test/resources/org/jboss/as/ejb3/subsystem/transform_database_1_2_0.xml
Labels: deps-ok, ready-for-merge

#12659 [WFLY-12541][WFLY-12566] Licenses cleanup
  feature-pack/src/license/full-feature-pack-licenses.xml
  servlet-feature-pack/src/license/servlet-feature-pack-licenses.xml
  servlet-feature-pack/src/main/resources/content/docs/licenses/gnu general public license version 2, with classpath exception.txt
Labels: 18.x, deps-ok

#12660 [WFLY-12551] Add entries to maven-enforcer-plugin ban-bad-dependencie…
  jpa/hibernate5-3-legacy/pom.xml
  jpa/hibernate5-legacy/pom.xml
  pom.xml
  testsuite/layers/pom.xml
  testsuite/mixed-domain/pom.xml
  weld/spi/pom.xml
Labels: 18.x, deps-ok

#12549 [WFLY-12442]:Upgrade jboss-saaj-api and saaj-impl from 1.3 to 1.4
  feature-pack/pom.xml
  feature-pack/src/license/full-feature-pack-licenses.xml
  feature-pack/src/main/resources/modules/system/layers/base/com/sun/xml/messaging/saaj/main/module.xml
  feature-pack/src/main/resources/modules/system/layers/base/javax/xml/soap/api/main/module.xml
  feature-pack/src/main/resources/modules/system/layers/base/org/apache/cxf/main/module.xml
  feature-pack/src/main/resources/modules/system/layers/base/org/apache/ws/security/main/module.xml
  galleon-pack/pom.xml
  pom.xml
  spec-api/pom.xml
  testsuite/integration/ws/pom.xml
  testsuite/integration/ws/src/test/java/org/jboss/as/test/integration/ws/authentication/policy/AuthenticationPolicyContextTestCase.java
Labels: 18.x, deps-changed

#12663 [WFLY-12578] Upgrade Yasson from 1.0.3 to 1.0.5
  pom.xml
Labels: deps-ok

#12665 [WFLY-12579] Tweak basic integration tests for OCSP to be able to run them in product branches
  testsuite/integration/elytron/src/test/java/org/wildfly/test/integration/elytron/certs/CommonBase.java
Labels: 18.x, deps-ok, ready-for-merge

#12666 [WFLY-12580] Explicitly disable the inheritance of Galleon configurations from transitive feature pack
  build/pom.xml
  dist/pom.xml
  galleon-pack/src/main/resources/configs/standalone/standalone-load-balancer.xml/config.xml
  galleon-pack/wildfly-feature-pack-build.xml
  servlet-build/pom.xml
  servlet-dist/pom.xml
Labels: 18.x, deps-ok, ready-for-merge

#12669 [WFLY-12577] Upgrade WildFly Core to 10.0.0.Final
  pom.xml
Labels: 18.x, Blocker, deps-ok

#12664 [WFLY-12551] Add the SAAJ 1.3 API to the list of banned dependencies
  pom.xml
Labels: 18.x, deps-ok, ready-for-merge

#12670 [WFLY-12585] Upgrade Jackson to 2.9.10
  pom.xml
Labels: 18.x, Blocker, deps-ok, ready-for-merge

#12448 [WFLY-12322] Avoid re-dispatching to the worker
  ejb3/src/main/java/org/jboss/as/ejb3/remote/AssociationImpl.java
Labels: 18.x, deps-ok

#12673 WFLY-12511 refer to Full Profile as Full Platform instead
  docs/src/main/asciidoc/Getting_Started_Guide.adoc
  docs/src/main/asciidoc/_developer-guide/How_do_I_migrate_my_application_from_AS7_to_WildFly.adoc
  docs/src/main/asciidoc/_testsuite/WildFly_Testsuite_Overview.adoc
Labels: 18.x, deps-ok

#12672 [WFLY-12591] Upgrade spullara mustache to 0.9.6
  pom.xml
Labels: deps-ok

#12679 Revert "[WFLY-12591] Upgrade spullara mustache to 0.9.6"
  pom.xml
Labels: 18.x, deps-ok
