Repository wildfly/wildfly, pull requests merged in 2020-02, with the labels that each got.

#12942 Fix for WFLY-13017, cloud-server layer to extend jaxrs-server layer
  docs/src/main/asciidoc/_admin-guide/Galleon_provisioning.adoc
  galleon-pack/src/main/resources/layers/standalone/cloud-server/layer-spec.xml
  galleon-pack/src/main/resources/layers/standalone/jaxrs-server/layer-spec.xml
Labels: 19.x, deps-ok, ready-for-merge

#12951 Fix for WFLY-13041, Upgrade to Galleon 4.2.4
  pom.xml
Labels: 19.x, deps-ok, ready-for-merge

#12949 [WFLY-13039]: Upgrade OpenTracing API from 1.3.1 to 1.3.2.
  pom.xml
Labels: 19.x, deps-ok

#12958 servlet-feature-pack-licenses: fix jboss-el-api_3.0_spec license name
  servlet-feature-pack/src/license/servlet-feature-pack-licenses.xml
Labels: deps-ok, ready-for-merge

#12959 [WFCORE-13062] Upgrade WildFly Core 11.0.0.Beta8
  feature-pack/src/main/resources/configuration/domain/template.xml
  feature-pack/src/main/resources/configuration/host/host-master.xml
  feature-pack/src/main/resources/configuration/host/host-slave.xml
  feature-pack/src/main/resources/configuration/host/host.xml
  feature-pack/src/main/resources/configuration/standalone/template.xml
  feature-pack/src/main/resources/content/appclient/configuration/appclient.xml
  feature-pack/src/main/resources/content/docs/examples/configs/standalone-minimalistic.xml
  pom.xml
  servlet-feature-pack/src/main/resources/configuration/domain/template.xml
  servlet-feature-pack/src/main/resources/configuration/host/host-master.xml
  servlet-feature-pack/src/main/resources/configuration/host/host-slave.xml
  servlet-feature-pack/src/main/resources/configuration/host/host.xml
  servlet-feature-pack/src/main/resources/configuration/standalone/template.xml
  testsuite/domain/src/test/resources/domain-configs/domain-minimal.xml
  testsuite/domain/src/test/resources/domain-configs/domain-rbac.xml
  testsuite/domain/src/test/resources/domain-configs/domain-respawn.xml
  testsuite/domain/src/test/resources/domain-configs/domain-standard-ee.xml
  testsuite/domain/src/test/resources/domain-configs/domain-standard.xml
  testsuite/domain/src/test/resources/host-configs/host-failover1.xml
  testsuite/domain/src/test/resources/host-configs/host-failover2.xml
  testsuite/domain/src/test/resources/host-configs/host-failover3.xml
  testsuite/domain/src/test/resources/host-configs/host-master-elytron.xml
  testsuite/domain/src/test/resources/host-configs/host-master-no-http.xml
  testsuite/domain/src/test/resources/host-configs/host-master-no-local.xml
  testsuite/domain/src/test/resources/host-configs/host-master-rbac-properties.xml
  testsuite/domain/src/test/resources/host-configs/host-master-rbac.xml
  testsuite/domain/src/test/resources/host-configs/host-master.xml
  testsuite/domain/src/test/resources/host-configs/host-secrets.xml
  testsuite/domain/src/test/resources/host-configs/host-slave-discovery-options.xml
  testsuite/domain/src/test/resources/host-configs/host-slave-elytron.xml
  testsuite/domain/src/test/resources/host-configs/host-slave-rbac-properties.xml
  testsuite/domain/src/test/resources/host-configs/host-slave-rbac.xml
  testsuite/domain/src/test/resources/host-configs/host-slave.xml
  testsuite/domain/src/test/resources/host-configs/respawn-master.xml
  testsuite/mixed-domain/src/test/resources/legacy-templates/test-template.xml
  testsuite/mixed-domain/src/test/resources/master-config/domain-minimal.xml
  testsuite/mixed-domain/src/test/resources/master-config/host-master-elytron.xml
  testsuite/mixed-domain/src/test/resources/master-config/host.xml
Labels: 19.x, deps-ok

#12945 Clustering jpa2lc tests with no ejb, exclude layers test
  testsuite/integration/clustering/pom.xml
  testsuite/integration/clustering/src/test/config/arq/arquillian.xml
  testsuite/integration/clustering/src/test/java/org/jboss/as/test/clustering/cluster/jpa2lc/DummyEntityRESTResource.java
  testsuite/integration/clustering/src/test/java/org/jboss/as/test/clustering/cluster/jpa2lcCustomRegion/DummyEntityCustomRegionRESTResource.java
  testsuite/integration/src/test/scripts/clustering-build.xml
  testsuite/integration/web/pom.xml
Labels: deps-ok

#12940 [WFLY-12952] Register default readiness probe for deployment
  docs/src/main/asciidoc/_admin-guide/subsystem-configuration/MicroProfile_Health.adoc
  feature-pack/src/main/resources/modules/system/layers/base/org/wildfly/extension/microprofile/health-smallrye/main/module.xml
  microprofile/health-smallrye/pom.xml
  microprofile/health-smallrye/src/main/java/org/wildfly/extension/microprofile/health/deployment/CDIExtension.java
  microprofile/health-smallrye/src/main/java/org/wildfly/extension/microprofile/health/deployment/DeploymentProcessor.java
  testsuite/integration/basic/src/test/java/org/wildfly/test/integration/microprofile/health/MicroProfileHealthApplicationWithoutReadinessOperationTestCase.java
  testsuite/integration/basic/src/test/java/org/wildfly/test/integration/microprofile/health/MicroProfileHealthApplicationWithoutReadinessTestBase.java
  testsuite/integration/basic/src/test/java/org/wildfly/test/integration/microprofile/health/MicroProfileHealthApplicationWitouhtReadinessHTTPEndpointTestCase.java
  testsuite/integration/microprofile-tck/health/pom.xml
Labels: 19.x, deps-ok

#12955 [WFLY-13049]: Upgrade netty to 4.1.45.Final
  pom.xml
Labels: deps-ok

#12962 [WFLY-13068]: Error adding activemq-subsystem with outbound socket bindings
  messaging-activemq/src/main/java/org/wildfly/extension/messaging/activemq/Capabilities.java
Labels: deps-ok

#12960 Upgrade Apache CXF from 3.3.4 to 3.3.5
  pom.xml
Labels: deps-ok

#12943 [WFLY-13026] Upgrade jboss-ejb-client 4.0.30.Final
  pom.xml
Labels: deps-ok, fixme

#12969 [WFLY-13072] HostExcludesTestCase should search all module layers
  testsuite/domain/src/test/java/org/jboss/as/test/integration/domain/HostExcludesTestCase.java
Labels: deps-ok

#12970 [WFLY-13073] LayeredDistributionTestCase should not discard content f…
  testsuite/integration/manualmode/src/test/java/org/jboss/as/test/manualmode/layered/LayeredDistributionTestCase.java
Labels: deps-ok

#12971 [WFLY-13050] Metrics should be optional in the observability layer
  docs/src/main/asciidoc/_admin-guide/Galleon_provisioning.adoc
  ee-galleon-pack/src/main/resources/layers/standalone/observability/layer-spec.xml
Labels: 19.x, deps-ok

#12956 Fix for WFLY-13050, metrics should be optional in observability layer
  docs/src/main/asciidoc/_admin-guide/Galleon_provisioning.adoc
  galleon-pack/src/main/resources/layers/standalone/observability/layer-spec.xml
Labels: deps-ok

#12975 [WFLY-13072] Limit HostExcludesTestCase extension searching to module…
  testsuite/domain/src/test/java/org/jboss/as/test/integration/domain/HostExcludesTestCase.java
Labels: deps-ok

#12982 [19.0.x][WFLY-13072] Limit HostExcludesTestCase extension searching to module…
  testsuite/domain/src/test/java/org/jboss/as/test/integration/domain/HostExcludesTestCase.java
Labels: 19.x, deps-ok

#12996 [WFLY-13096] Upgrade Soteria to 1.0.1-jbossorg-1
  pom.xml
Labels: 19.x, Blocker

#12995 [WFLY-13096] Upgrade Soteria to 1.0.1-jbossorg-1
  pom.xml
Labels: Blocker, deps-ok

#12978 [WFLY-13708] Upgrade SmallRye JWT to 2.0.13
  pom.xml
Labels: deps-ok, ready-for-merge

#12988 [WFLY-13708] Upgrade SmallRye JWT to 2.0.13
  pom.xml
Labels: 19.x, ready-for-merge

#12989 [WFLY-13022] Upgrade MicroProfile Metrics 2.3
  microprofile/metrics-smallrye/src/main/resources/io/smallrye/metrics/base-metrics.properties
  pom.xml
  testsuite/integration/microprofile-tck/metrics/pom.xml
Labels: Feature, deps-ok, ready-for-merge

#12998 [19.0.x] [WFLY-13022] Upgrade MicroProfile Metrics 2.3
  microprofile/metrics-smallrye/src/main/resources/io/smallrye/metrics/base-metrics.properties
  pom.xml
  testsuite/integration/microprofile-tck/metrics/pom.xml
Labels: 19.x, Feature, deps-ok, ready-for-merge

#13002 [WFLY-13100]: Upgrade Jaeger Java Client to 0.34.3 and smallrye opentracing to 1.3.4
  pom.xml
Labels: deps-ok, ready-for-merge

#13001 [WFLY-13100]: Upgrade Jaeger Java Client to 0.34.3 and smallrye opentracing to 1.3.4
  pom.xml
Labels: 19.x, deps-ok, ready-for-merge

#12972 [WFLY-12985] Remove cruft from observability override POC
  galleon-pack/pom.xml
Labels: deps-ok, ready-for-merge

#12977 [WFLY-12913] Rationalize com.sum.xml.bind module dependencies
  feature-pack/src/main/resources/modules/system/layers/base/com/github/relaxng/main/module.xml
  feature-pack/src/main/resources/modules/system/layers/base/com/sun/istack/main/module.xml
  feature-pack/src/main/resources/modules/system/layers/base/com/sun/xml/bind/main/module.xml
  feature-pack/src/main/resources/modules/system/layers/base/com/sun/xml/txw2/main/module.xml
  feature-pack/src/main/resources/modules/system/layers/base/com/sun/xsom/main/module.xml
Labels: deps-ok, ready-for-merge

#12997 [WFLY-13098] Excluding a test scopped dependency from io7m.xom ...
  pom.xml
Labels: deps-ok, ready-for-merge

#12973 [WFLY-12985] Clean out feature pack resource copy cruft
  galleon-pack/pom.xml
Labels: deps-ok

#13018 [WFLY-13135] Upgrade WildFly Core 11.0.0.Beta9
  pom.xml
Labels: deps-ok

#13024 [WFLY-13136]: Can't create a Pooled Connection Factory using JGroups
  messaging-activemq/src/main/java/org/wildfly/extension/messaging/activemq/jms/ExternalConnectionFactoryAdd.java
  messaging-activemq/src/main/java/org/wildfly/extension/messaging/activemq/jms/ExternalPooledConnectionFactoryAdd.java
Labels: deps-ok

#13000 [WFLY-13102] assertion error is expected when ejb is not available
  testsuite/integration/clustering/src/test/java/org/jboss/as/test/clustering/cluster/ejb/remote/TransactionalRemoteStatelessTestCase.java
Labels: deps-ok

#12846 WFLY-12871 - System Exception (EJBException) should be thrown instea…
  ejb3/src/main/java/org/jboss/as/ejb3/tx/CMTTxInterceptor.java
Labels: deps-ok

#13027 [WFLY-13139] Upgrade org.glassfish:jakarta-el from 3.0.3.jbossorg-1 t…
  pom.xml
Labels: deps-ok

#13028 [WFLY-13139] Upgrade org.glassfish:jakarta-el from 3.0.3.jbossorg-1 t…
  pom.xml
Labels: 19.x, deps-ok

#12965 [WFLY-13023] Upgrade MicroProfile Config 1.4
  ee-galleon-pack/pom.xml
  feature-pack/pom.xml
  feature-pack/src/license/full-feature-pack-licenses.xml
  feature-pack/src/main/resources/modules/system/layers/base/io/smallrye/config/main/module.xml
  microprofile/config-smallrye/pom.xml
  microprofile/config-smallrye/src/main/java/org/wildfly/extension/microprofile/config/smallrye/DirConfigSourceRegistrationService.java
  pom.xml
  testsuite/integration/basic/src/test/java/org/wildfly/test/integration/microprofile/config/smallrye/app/MicroProfileConfigTestCase.java
  testsuite/integration/basic/src/test/java/org/wildfly/test/integration/microprofile/config/smallrye/app/TestApplication.java
  testsuite/integration/microprofile-tck/config/pom.xml
  testsuite/integration/microprofile-tck/config/src/test/java/org/wildfly/extension/microprofile/config/test/DeploymentProcessor.java
  testsuite/integration/microprofile-tck/config/tck-suite.xml
Labels: Feature, deps-changed

#12984 [19.0.x] [WFLY-13023] Upgrade MicroProfile Config 1.4
  ee-galleon-pack/pom.xml
  feature-pack/pom.xml
  feature-pack/src/license/full-feature-pack-licenses.xml
  feature-pack/src/main/resources/modules/system/layers/base/io/smallrye/config/main/module.xml
  microprofile/config-smallrye/pom.xml
  microprofile/config-smallrye/src/main/java/org/wildfly/extension/microprofile/config/smallrye/DirConfigSourceRegistrationService.java
  pom.xml
  testsuite/integration/basic/src/test/java/org/wildfly/test/integration/microprofile/config/smallrye/app/MicroProfileConfigTestCase.java
  testsuite/integration/basic/src/test/java/org/wildfly/test/integration/microprofile/config/smallrye/app/TestApplication.java
  testsuite/integration/microprofile-tck/config/pom.xml
  testsuite/integration/microprofile-tck/config/src/test/java/org/wildfly/extension/microprofile/config/test/DeploymentProcessor.java
  testsuite/integration/microprofile-tck/config/tck-suite.xml
Labels: 19.x, Blocker, Feature, deps-changed

#13025 [WFLY-13136]: Can't create a Pooled Connection Factory using JGroups
  messaging-activemq/src/main/java/org/wildfly/extension/messaging/activemq/jms/ExternalConnectionFactoryAdd.java
  messaging-activemq/src/main/java/org/wildfly/extension/messaging/activemq/jms/ExternalPooledConnectionFactoryAdd.java
Labels: 19.x, deps-ok, ready-for-merge

#13032 [WFLY-13091] Upgrade HAL to 3.2.7.Final
  pom.xml
Labels: deps-ok, ready-for-merge

#13033 [19.0.x][WFLY-13143] Upgrade HAL to 3.2.7.Final
  pom.xml
Labels: 19.x, deps-ok, ready-for-merge

#13019 [19.0.x][WFLY-13135] Upgrade WildFly Core 11.0.0.Beta9
  pom.xml
Labels: 19.x, deps-ok

#13037 [WFLY-13023] Upgrade MicroProfile Config 1.4
  testsuite/integration/microprofile-tck/config/tck-suite.xml
Labels: deps-ok

#12983 [WFLY-13048] Upgrade MicroProfile Health 2.2
  microprofile/health-smallrye/pom.xml
  microprofile/health-smallrye/src/main/java/org/wildfly/extension/microprofile/health/deployment/CDIExtension.java
  pom.xml
Labels: Feature, deps-ok

#12999 [19.0.x] [WFLY-13048] Upgrade MicroProfile Health 2.2
  microprofile/health-smallrye/pom.xml
  microprofile/health-smallrye/src/main/java/org/wildfly/extension/microprofile/health/deployment/CDIExtension.java
  pom.xml
Labels: 19.x, Feature, deps-ok

#13010 [WFLY-13124][WFLY-13089] Upgrade RESTEasy to 3.11.0.Final
  pom.xml
Labels: Feature, deps-ok

#13011 [19.x][WFLY-13124][WFLY-13089] Upgrade RESTEasy to 3.11.0.Final
  pom.xml
Labels: 19.x, Feature, deps-ok

#13036 [WFLY-13137] Facilitate use of a distinct maven groupId for artifacts…
  build/pom.xml
  dist/pom.xml
  galleon-pack/pom.xml
  microprofile/fault-tolerance-smallrye/cdi/pom.xml
  microprofile/fault-tolerance-smallrye/extension/pom.xml
  microprofile/fault-tolerance-smallrye/pom.xml
  microprofile/openapi-smallrye/pom.xml
  microprofile/pom.xml
  pom.xml
  testsuite/integration/basic/pom.xml
  testsuite/integration/clustering/pom.xml
  testsuite/integration/elytron/pom.xml
  testsuite/integration/microprofile-tck/config/pom.xml
  testsuite/integration/microprofile-tck/fault-tolerance/pom.xml
  testsuite/integration/microprofile-tck/health/pom.xml
  testsuite/integration/microprofile-tck/jwt/pom.xml
  testsuite/integration/microprofile-tck/metrics/pom.xml
  testsuite/integration/microprofile-tck/openapi/pom.xml
  testsuite/integration/microprofile-tck/opentracing/pom.xml
  testsuite/integration/microprofile/pom.xml
  testsuite/integration/smoke/pom.xml
  testsuite/integration/web/pom.xml
  testsuite/layers/pom.xml
Labels: deps-ok

#13040 [19.0.x][WFLY-13137] Facilitate use of a distinct maven groupId for artifacts…
  build/pom.xml
  dist/pom.xml
  galleon-pack/pom.xml
  microprofile/fault-tolerance-smallrye/cdi/pom.xml
  microprofile/fault-tolerance-smallrye/extension/pom.xml
  microprofile/fault-tolerance-smallrye/pom.xml
  microprofile/openapi-smallrye/pom.xml
  microprofile/pom.xml
  pom.xml
  testsuite/integration/basic/pom.xml
  testsuite/integration/clustering/pom.xml
  testsuite/integration/elytron/pom.xml
  testsuite/integration/microprofile-tck/config/pom.xml
  testsuite/integration/microprofile-tck/fault-tolerance/pom.xml
  testsuite/integration/microprofile-tck/health/pom.xml
  testsuite/integration/microprofile-tck/jwt/pom.xml
  testsuite/integration/microprofile-tck/metrics/pom.xml
  testsuite/integration/microprofile-tck/openapi/pom.xml
  testsuite/integration/microprofile-tck/opentracing/pom.xml
  testsuite/integration/microprofile/pom.xml
  testsuite/integration/smoke/pom.xml
  testsuite/integration/web/pom.xml
  testsuite/layers/pom.xml
Labels: 19.x, deps-ok

#13048 WFLY-13127 NPE in OpenApiAnnotationScanner when OpenTracing TCK war is deployed
  pom.xml
Labels: deps-ok

#13049 [19.0.x] WFLY-13127 NPE in OpenApiAnnotationScanner when OpenTracing TCK war is deployed
  pom.xml
Labels: deps-ok

#13044 WFLY-13121 jgroups channel protocol read-resource error with include-…
  clustering/jgroups/extension/src/main/java/org/jboss/as/clustering/jgroups/subsystem/ProtocolMetricsHandler.java
Labels: deps-ok
