Repository wildfly/wildfly, pull requests merged in 2020-03, with the labels that each got.

#13063 WFLY-13168 Invalidation caches use wrong key affinity
  clustering/ejb/infinispan/src/main/java/org/wildfly/clustering/ejb/infinispan/InfinispanBeanManager.java
  clustering/infinispan/extension/src/main/java/org/jboss/as/clustering/infinispan/subsystem/KeyAffinityServiceFactoryServiceConfigurator.java
  clustering/web/infinispan/src/main/java/org/wildfly/clustering/web/infinispan/routing/PrimaryOwnerRouteLocator.java
  clustering/web/infinispan/src/test/java/org/wildfly/clustering/web/infinispan/routing/PrimaryOwnerRouteLocatorTestCase.java
Labels: deps-ok

#13064 [19.0.x] WFLY-13168 Invalidation caches use wrong key affinity
  clustering/ejb/infinispan/src/main/java/org/wildfly/clustering/ejb/infinispan/InfinispanBeanManager.java
  clustering/infinispan/extension/src/main/java/org/jboss/as/clustering/infinispan/subsystem/KeyAffinityServiceFactoryServiceConfigurator.java
  clustering/web/infinispan/src/main/java/org/wildfly/clustering/web/infinispan/routing/PrimaryOwnerRouteLocator.java
  clustering/web/infinispan/src/test/java/org/wildfly/clustering/web/infinispan/routing/PrimaryOwnerRouteLocatorTestCase.java
Labels: deps-ok

#13061 [WFLY-13171] Validate requirement for modules previously exported by javax.ejb.api on JSF implementations
  feature-pack/src/main/resources/modules/system/layers/base/com/sun/jsf-impl/main/module.xml
  jsf/multi-jsf-installer/src/main/resources/mojarra-impl-module.xml
  jsf/multi-jsf-installer/src/main/resources/myfaces-impl-module.xml
  jsf/subsystem/src/test/resources/modules/com/sun/jsf-impl/main/module.xml
  jsf/subsystem/src/test/resources/modules/com/sun/jsf-impl/myfaces/module.xml
  jsf/subsystem/src/test/resources/modules2/com/sun/jsf-impl/myfaces2/module.xml
Labels: deps-ok

#13062 WFLY-13175 Expressions in jboss-ejb-client.xml don't work for client-…
  ee/src/main/java/org/jboss/as/ee/structure/EJBClientDescriptor12Parser.java
Labels: deps-ok

#13050 WFLY-12926 Upgrade Infinispan to 9.4.18.Final
  pom.xml
Labels: deps-ok

#13051 [19.0.x] WFLY-12926 Upgrade Infinispan to 9.4.18.Final
  pom.xml
Labels: deps-ok

#13029 [WFLY-13142]: Can't create a Connection Factory using Jgroups discovery
  messaging-activemq/src/main/java/org/wildfly/extension/messaging/activemq/jms/ExternalConnectionFactoryAdd.java
  messaging-activemq/src/main/java/org/wildfly/extension/messaging/activemq/jms/PooledConnectionFactoryAdd.java
Labels: deps-ok

#13030 [WFLY-13142]: Can't create a Connection Factory using Jgroups discovery
  messaging-activemq/src/main/java/org/wildfly/extension/messaging/activemq/jms/ExternalConnectionFactoryAdd.java
  messaging-activemq/src/main/java/org/wildfly/extension/messaging/activemq/jms/PooledConnectionFactoryAdd.java
Labels: 19.x, deps-ok

#13054 WFLY-13167 Upgrade JGroups to 4.2.0.Final
  clustering/jgroups/extension/src/main/java/org/jboss/as/clustering/jgroups/subsystem/DigestAuthTokenServiceConfigurator.java
  pom.xml
Labels: deps-ok

#12987 [WFLY-13086] Upgrade gson from 2.8.2 to 2.8.6
  pom.xml
Labels: deps-ok

#12991 [WFLY-13092] Remove the quotes from the FILE parameter due to GAL-309…
  ee-galleon-pack/src/main/resources/feature_groups/domain-load-balancer.xml
  servlet-galleon-pack/src/main/resources/feature_groups/domain-profile.xml
Labels: deps-ok

#12934 Add Wildscribe model description to the generated documentation
  docs/pom.xml
  docs/src/main/asciidoc/index.adoc
  pom.xml
Labels: deps-ok

#13039 [WFLY-13151] Add Wildscribe model documentation to the WildFly docume…
  docs/pom.xml
  docs/src/main/asciidoc/index.adoc
  pom.xml
Labels: 19.x, deps-ok

#13052 WFLY-13152 WFLYEJB0094: EJB 3.1 FR 5.4.2 MessageDrivenBean does not i…
  ejb3/src/main/java/org/jboss/as/ejb3/deployment/processors/MessageDrivenComponentDescriptionFactory.java
Labels: deps-ok

#13009 [WFLY-13123] adding timeout for container stop operation for RemoteEJBClientStatefulFailover tests
  testsuite/integration/clustering/src/test/java/org/jboss/as/test/clustering/cluster/ejb2/stateful/failover/RemoteEJBClientStatefulFailoverTestBase.java
Labels: deps-ok

#12985 [WFLY-13088] Ejb binding should not be listed if there is no Remote i…
  ejb3/src/main/java/org/jboss/as/ejb3/deployment/processors/EjbJndiBindingsDeploymentUnitProcessor.java
Labels: deps-ok

#13003 WFLY-13024 Integrate MP Fault Tolerance 2.1
  docs/src/main/asciidoc/_admin-guide/subsystem-configuration/MicroProfile_Fault_Tolerance_SmallRye.adoc
  ee-build/src/verifier/verifications.xml
  ee-dist/src/verifier/verifications.xml
  galleon-pack/pom.xml
  galleon-pack/src/license/microprofile-feature-pack-licenses.xml
  galleon-pack/src/main/resources/modules/system/layers/base/com/netflix/archaius/core/main/module.xml
  galleon-pack/src/main/resources/modules/system/layers/base/com/netflix/hystrix/core/main/module.xml
  galleon-pack/src/main/resources/modules/system/layers/base/io/reactivex/rxjava/main/module.xml
  galleon-pack/src/main/resources/modules/system/layers/base/io/smallrye/fault-tolerance/main/module.xml
  galleon-pack/src/main/resources/modules/system/layers/base/org/hdrhistogram/main/module.xml
  galleon-pack/src/main/resources/modules/system/layers/base/org/wildfly/extension/microprofile/fault-tolerance-smallrye/main/module.xml
  galleon-pack/src/main/resources/modules/system/layers/base/org/wildfly/microprofile/fault-tolerance-smallrye/executor/main/module.xml
  microprofile/fault-tolerance-smallrye/cdi/pom.xml
  microprofile/fault-tolerance-smallrye/cdi/src/main/java/org/wildfly/extension/microprofile/faulttolerance/cdi/RequestContextCommandListener.java
  microprofile/fault-tolerance-smallrye/cdi/src/main/java/org/wildfly/extension/microprofile/faulttolerance/cdi/WeldCommandListenersProvider.java
  microprofile/fault-tolerance-smallrye/executor/pom.xml
  microprofile/fault-tolerance-smallrye/executor/src/main/java/org/wildfly/extension/microprofile/faulttolerance/FaultToleranceContainerExecutorFactory.java
  microprofile/fault-tolerance-smallrye/executor/src/main/resources/META-INF/services/io.smallrye.faulttolerance.ExecutorFactory
  microprofile/fault-tolerance-smallrye/extension/pom.xml
  microprofile/fault-tolerance-smallrye/extension/src/main/java/org/wildfly/extension/microprofile/faulttolerance/MicroProfileFaultToleranceLogger.java
  microprofile/fault-tolerance-smallrye/extension/src/main/java/org/wildfly/extension/microprofile/faulttolerance/deployment/MicroProfileFaultToleranceCDIExtension.java
  microprofile/fault-tolerance-smallrye/extension/src/main/java/org/wildfly/extension/microprofile/faulttolerance/deployment/MicroProfileFaultToleranceDependenciesProcessor.java
  microprofile/fault-tolerance-smallrye/extension/src/main/java/org/wildfly/extension/microprofile/faulttolerance/deployment/MicroProfileFaultToleranceDeploymentProcessor.java
  microprofile/fault-tolerance-smallrye/pom.xml
  pom.xml
  testsuite/integration/microprofile-tck/fault-tolerance/pom.xml
  testsuite/integration/microprofile-tck/fault-tolerance/src/test/java/org/wildfly/extension/microprofile/faulttolerance/tck/FaultToleranceApplicationArchiveProcessor.java
  testsuite/integration/microprofile-tck/fault-tolerance/src/test/java/org/wildfly/extension/microprofile/faulttolerance/tck/HystrixCommandSemaphoreCleanup.java
  testsuite/integration/microprofile-tck/fault-tolerance/src/test/resources/arquillian.xml
  testsuite/integration/microprofile-tck/fault-tolerance/tck-suite.xml
  testsuite/integration/microprofile/pom.xml
  testsuite/integration/microprofile/src/test/java/org/wildfly/test/integration/microprofile/faulttolerance/async/requestcontext/AsynchronousRequestContextTest.java
  testsuite/integration/microprofile/src/test/java/org/wildfly/test/integration/microprofile/faulttolerance/sync/ShakyServiceClient.java
  testsuite/integration/microprofile/src/test/java/org/wildfly/test/integration/microprofile/faulttolerance/sync/SyncCircuitBreakerDisabledTest.java
  testsuite/integration/microprofile/src/test/java/org/wildfly/test/integration/microprofile/jwt/.gitkeep
  testsuite/integration/microprofile/src/test/java/org/wildfly/test/integration/microprofile/openapi/.gitkeep
Labels: Feature, deps-ok, missing-reqs, ready-for-merge

#13022 [19.x] WFLY-13024 Integrate MP Fault Tolerance 2.1
  docs/src/main/asciidoc/_admin-guide/subsystem-configuration/MicroProfile_Fault_Tolerance_SmallRye.adoc
  ee-build/src/verifier/verifications.xml
  ee-dist/src/verifier/verifications.xml
  galleon-pack/pom.xml
  galleon-pack/src/license/microprofile-feature-pack-licenses.xml
  galleon-pack/src/main/resources/modules/system/layers/base/com/netflix/archaius/core/main/module.xml
  galleon-pack/src/main/resources/modules/system/layers/base/com/netflix/hystrix/core/main/module.xml
  galleon-pack/src/main/resources/modules/system/layers/base/io/reactivex/rxjava/main/module.xml
  galleon-pack/src/main/resources/modules/system/layers/base/io/smallrye/fault-tolerance/main/module.xml
  galleon-pack/src/main/resources/modules/system/layers/base/org/hdrhistogram/main/module.xml
  galleon-pack/src/main/resources/modules/system/layers/base/org/wildfly/extension/microprofile/fault-tolerance-smallrye/main/module.xml
  galleon-pack/src/main/resources/modules/system/layers/base/org/wildfly/microprofile/fault-tolerance-smallrye/executor/main/module.xml
  microprofile/fault-tolerance-smallrye/cdi/pom.xml
  microprofile/fault-tolerance-smallrye/cdi/src/main/java/org/wildfly/extension/microprofile/faulttolerance/cdi/RequestContextCommandListener.java
  microprofile/fault-tolerance-smallrye/cdi/src/main/java/org/wildfly/extension/microprofile/faulttolerance/cdi/WeldCommandListenersProvider.java
  microprofile/fault-tolerance-smallrye/executor/pom.xml
  microprofile/fault-tolerance-smallrye/executor/src/main/java/org/wildfly/extension/microprofile/faulttolerance/FaultToleranceContainerExecutorFactory.java
  microprofile/fault-tolerance-smallrye/executor/src/main/resources/META-INF/services/io.smallrye.faulttolerance.ExecutorFactory
  microprofile/fault-tolerance-smallrye/extension/pom.xml
  microprofile/fault-tolerance-smallrye/extension/src/main/java/org/wildfly/extension/microprofile/faulttolerance/MicroProfileFaultToleranceLogger.java
  microprofile/fault-tolerance-smallrye/extension/src/main/java/org/wildfly/extension/microprofile/faulttolerance/deployment/MicroProfileFaultToleranceCDIExtension.java
  microprofile/fault-tolerance-smallrye/extension/src/main/java/org/wildfly/extension/microprofile/faulttolerance/deployment/MicroProfileFaultToleranceDependenciesProcessor.java
  microprofile/fault-tolerance-smallrye/extension/src/main/java/org/wildfly/extension/microprofile/faulttolerance/deployment/MicroProfileFaultToleranceDeploymentProcessor.java
  microprofile/fault-tolerance-smallrye/pom.xml
  pom.xml
  testsuite/integration/microprofile-tck/fault-tolerance/pom.xml
  testsuite/integration/microprofile-tck/fault-tolerance/src/test/java/org/wildfly/extension/microprofile/faulttolerance/tck/FaultToleranceApplicationArchiveProcessor.java
  testsuite/integration/microprofile-tck/fault-tolerance/src/test/java/org/wildfly/extension/microprofile/faulttolerance/tck/HystrixCommandSemaphoreCleanup.java
  testsuite/integration/microprofile-tck/fault-tolerance/src/test/resources/arquillian.xml
  testsuite/integration/microprofile-tck/fault-tolerance/tck-suite.xml
  testsuite/integration/microprofile/pom.xml
  testsuite/integration/microprofile/src/test/java/org/wildfly/test/integration/microprofile/faulttolerance/async/requestcontext/AsynchronousRequestContextTest.java
  testsuite/integration/microprofile/src/test/java/org/wildfly/test/integration/microprofile/faulttolerance/sync/ShakyServiceClient.java
  testsuite/integration/microprofile/src/test/java/org/wildfly/test/integration/microprofile/faulttolerance/sync/SyncCircuitBreakerDisabledTest.java
  testsuite/integration/microprofile/src/test/java/org/wildfly/test/integration/microprofile/jwt/.gitkeep
  testsuite/integration/microprofile/src/test/java/org/wildfly/test/integration/microprofile/openapi/.gitkeep
Labels: 19.x, Feature, deps-ok, ready-for-merge

#13072 [WFLY-13158] Upgrade smallrye-config 1.6.2
  pom.xml
Labels: deps-ok, ready-for-merge

#13073 [19.0.x] [WFLY-13158] Upgrade smallrye-config 1.6.2
  pom.xml
Labels: 19.x, deps-ok, ready-for-merge

#13074 Cleanup documentation for "Using WildFly as a Load Balancer" section;…
  docs/src/main/asciidoc/_admin-guide/subsystem-configuration/Messaging_Discovery_Configuration.adoc
  docs/src/main/asciidoc/_admin-guide/subsystem-configuration/Undertow_using_as_a_Load_Balancer.adoc
Labels: deps-ok

#13070 [WFLY-13187] Add wildflyee.api as non referenced module in LayersTestCase
  testsuite/layers/src/test/java/org/jboss/as/test/layers/LayersTestCase.java
Labels: deps-ok

#13043 [19.0.x] WFLY-13099 Standard configuration files for MicroProfile use cases
  dist/src/test/java/org/wildfly/dist/subsystem/xml/StandardConfigsXMLValidationUnitTestCase.java
  docs/src/main/asciidoc/Getting_Started_Guide.adoc
  ee-galleon-pack/src/main/resources/layers/standalone/jpa-distributed/layer-spec.xml
  galleon-pack/src/main/resources/configs/standalone/standalone-microprofile-ha.xml/config.xml
  galleon-pack/src/main/resources/configs/standalone/standalone-microprofile.xml/config.xml
  galleon-pack/wildfly-feature-pack-build.xml
  pom.xml
  testsuite/integration/basic/pom.xml
  testsuite/integration/clustering/clustering-all.cli
  testsuite/integration/clustering/pom.xml
  testsuite/integration/clustering/src/test/java/org/jboss/as/test/clustering/cluster/sso/ElytronSSOServerSetupTask.java
  testsuite/integration/microprofile-tck/config/pom.xml
  testsuite/integration/microprofile-tck/config/src/test/resources/arquillian.xml
  testsuite/integration/microprofile-tck/fault-tolerance/pom.xml
  testsuite/integration/microprofile-tck/fault-tolerance/src/test/resources/arquillian.xml
  testsuite/integration/microprofile-tck/health/pom.xml
  testsuite/integration/microprofile-tck/health/src/test/resources/arquillian.xml
  testsuite/integration/microprofile-tck/jwt/pom.xml
  testsuite/integration/microprofile-tck/jwt/src/test/resources/arquillian.xml
  testsuite/integration/microprofile-tck/metrics/pom.xml
  testsuite/integration/microprofile-tck/metrics/src/test/resources/arquillian.xml
  testsuite/integration/microprofile-tck/openapi/pom.xml
  testsuite/integration/microprofile-tck/openapi/src/test/resources/arquillian.xml
  testsuite/integration/microprofile-tck/opentracing/pom.xml
  testsuite/integration/microprofile-tck/opentracing/src/test/resources/arquillian.xml
  testsuite/integration/microprofile-tck/pom.xml
  testsuite/integration/microprofile/pom.xml
  testsuite/integration/microprofile/src/test/config/arq/arquillian.xml
  testsuite/integration/microprofile/src/test/java/org/wildfly/test/integration/microprofile/openapi/OpenAPIAbsoluteServersTestCase.java
  testsuite/integration/pom.xml
  testsuite/integration/smoke/pom.xml
  testsuite/integration/web/pom.xml
  testsuite/layers/pom.xml
  testsuite/test-feature-pack/src/main/resources/layers/standalone/distributable-web/layer-spec.xml
Labels: 19.x, deps-ok

#13066 [19.0.x][WFLY-13137] Use ee.maven.groupId in dependency management where ee.m…
  microprofile/fault-tolerance-smallrye/executor/pom.xml
  microprofile/fault-tolerance-smallrye/extension/pom.xml
  microprofile/jwt-smallrye/pom.xml
  microprofile/openapi-smallrye/pom.xml
  pom.xml
Labels: 19.x, deps-ok

#13065 [WFLY-13137] Use ee.maven.groupId in dependency management where ee.m…
  microprofile/fault-tolerance-smallrye/executor/pom.xml
  microprofile/fault-tolerance-smallrye/extension/pom.xml
  microprofile/jwt-smallrye/pom.xml
  microprofile/openapi-smallrye/pom.xml
  pom.xml
Labels: deps-ok

#13081 [19.0.x] [WFLY-13203] Upgrade WildFly Core 11.0.0.Beta10
  pom.xml
Labels: 19.x, deps-ok

#13080 [WFLY-13203] Upgrade WildFly Core 11.0.0.Beta10
  pom.xml
Labels: deps-ok

#13077 Update the Wildscribe links to use the version of Wildscribe associat…
  docs/src/main/asciidoc/_admin-guide/subsystem-configuration/Batch_(JSR-352).adoc
  docs/src/main/asciidoc/_admin-guide/subsystem-configuration/Undertow_using_as_a_Load_Balancer.adoc
  docs/src/main/asciidoc/_developer-guide/JTA_Reference.adoc
  docs/src/main/asciidoc/_high-availability/subsystem-support/Infinispan_Subsystem.adoc
Labels: 19.x, deps-ok

#13076 Update the Wildscribe links to use the version of Wildscribe associat…
  docs/src/main/asciidoc/_admin-guide/subsystem-configuration/Batch_(JSR-352).adoc
  docs/src/main/asciidoc/_admin-guide/subsystem-configuration/Undertow_using_as_a_Load_Balancer.adoc
  docs/src/main/asciidoc/_developer-guide/JTA_Reference.adoc
  docs/src/main/asciidoc/_high-availability/subsystem-support/Infinispan_Subsystem.adoc
Labels: deps-ok

#13082 [WFLY-13137] Don't use project.groupId for galleon-pack module depend…
  build/pom.xml
  dist/pom.xml
  galleon-pack/pom.xml
Labels: deps-ok

#13083 [WFLY-13137] Don't use project.groupId for galleon-pack module depend…
  build/pom.xml
  dist/pom.xml
  galleon-pack/pom.xml
Labels: deps-ok

#13015 WFLY-13099 Standard configuration files for MicroProfile use cases
  dist/src/test/java/org/wildfly/dist/subsystem/xml/StandardConfigsXMLValidationUnitTestCase.java
  docs/src/main/asciidoc/Getting_Started_Guide.adoc
  ee-galleon-pack/src/main/resources/layers/standalone/jpa-distributed/layer-spec.xml
  galleon-pack/src/main/resources/configs/standalone/standalone-microprofile-ha.xml/config.xml
  galleon-pack/src/main/resources/configs/standalone/standalone-microprofile.xml/config.xml
  galleon-pack/wildfly-feature-pack-build.xml
  pom.xml
  testsuite/integration/basic/pom.xml
  testsuite/integration/clustering/clustering-all.cli
  testsuite/integration/clustering/pom.xml
  testsuite/integration/clustering/src/test/java/org/jboss/as/test/clustering/cluster/sso/ElytronSSOServerSetupTask.java
  testsuite/integration/microprofile-tck/config/pom.xml
  testsuite/integration/microprofile-tck/config/src/test/resources/arquillian.xml
  testsuite/integration/microprofile-tck/fault-tolerance/pom.xml
  testsuite/integration/microprofile-tck/fault-tolerance/src/test/resources/arquillian.xml
  testsuite/integration/microprofile-tck/health/pom.xml
  testsuite/integration/microprofile-tck/health/src/test/resources/arquillian.xml
  testsuite/integration/microprofile-tck/jwt/pom.xml
  testsuite/integration/microprofile-tck/jwt/src/test/resources/arquillian.xml
  testsuite/integration/microprofile-tck/metrics/pom.xml
  testsuite/integration/microprofile-tck/metrics/src/test/resources/arquillian.xml
  testsuite/integration/microprofile-tck/openapi/pom.xml
  testsuite/integration/microprofile-tck/openapi/src/test/resources/arquillian.xml
  testsuite/integration/microprofile-tck/opentracing/pom.xml
  testsuite/integration/microprofile-tck/opentracing/src/test/resources/arquillian.xml
  testsuite/integration/microprofile-tck/pom.xml
  testsuite/integration/microprofile/pom.xml
  testsuite/integration/microprofile/src/test/config/arq/arquillian.xml
  testsuite/integration/microprofile/src/test/java/org/wildfly/test/integration/microprofile/openapi/OpenAPIAbsoluteServersTestCase.java
  testsuite/integration/pom.xml
  testsuite/integration/smoke/pom.xml
  testsuite/integration/web/pom.xml
  testsuite/layers/pom.xml
  testsuite/test-feature-pack/src/main/resources/layers/standalone/distributable-web/layer-spec.xml
Labels: Feature, deps-ok

#13088 WFLY-13211 Upgrade jgroups-kubernetes to 1.0.15.Final
  pom.xml
Labels: deps-ok

#13078 WFLY-13191 Docs: invalid CLI instructions in SSL and mod_cluster section
  docs/src/main/asciidoc/_high-availability/subsystem-support/SSL_Configuration_using_Elytron_Subsystem.adoc
Labels: deps-ok

#13102 [19.x][WFLY-13222] Use org.jboss.product from ee-galleon-pack
  dist-legacy/src/distribution/resources/bin/product.conf
  dist-legacy/src/distribution/resources/modules/system/layers/base/org/jboss/as/product/main/dir/META-INF/MANIFEST.MF
  dist-legacy/src/distribution/resources/modules/system/layers/base/org/jboss/as/product/main/module.xml
  ee-galleon-pack/src/main/resources/packages/product.conf/content/bin/product.conf
  ee-galleon-pack/src/main/resources/packages/product.conf/content/modules/system/layers/base/org/jboss/as/product/main/module.xml
  ee-galleon-pack/src/main/resources/packages/product.conf/content/modules/system/layers/base/org/jboss/as/product/wildfly-ee/module.xml
  ee-galleon-pack/src/main/resources/packages/product.conf/pm/wildfly/resources/modules/system/layers/base/org/jboss/as/product/main/dir/META-INF/MANIFEST.MF
  galleon-pack/src/main/resources/packages/product.conf/content/bin/product.conf
  galleon-pack/src/main/resources/packages/product.conf/package.xml
  galleon-pack/src/main/resources/packages/product.conf/pm/wildfly/resources/modules/system/layers/base/org/jboss/as/product/wildfly-full/dir/META-INF/MANIFEST.MF
  galleon-pack/src/main/resources/packages/product.conf/pm/wildfly/tasks.xml
  galleon-pack/wildfly-feature-pack-build.xml
  pom.xml
Labels: deps-ok

#13101 [WFLY-13222] Use org.jboss.product from ee-galleon-pack
  dist-legacy/src/distribution/resources/bin/product.conf
  dist-legacy/src/distribution/resources/modules/system/layers/base/org/jboss/as/product/main/dir/META-INF/MANIFEST.MF
  dist-legacy/src/distribution/resources/modules/system/layers/base/org/jboss/as/product/main/module.xml
  ee-galleon-pack/src/main/resources/packages/product.conf/content/bin/product.conf
  ee-galleon-pack/src/main/resources/packages/product.conf/content/modules/system/layers/base/org/jboss/as/product/main/module.xml
  ee-galleon-pack/src/main/resources/packages/product.conf/content/modules/system/layers/base/org/jboss/as/product/wildfly-ee/module.xml
  ee-galleon-pack/src/main/resources/packages/product.conf/pm/wildfly/resources/modules/system/layers/base/org/jboss/as/product/main/dir/META-INF/MANIFEST.MF
  galleon-pack/src/main/resources/packages/product.conf/content/bin/product.conf
  galleon-pack/src/main/resources/packages/product.conf/package.xml
  galleon-pack/src/main/resources/packages/product.conf/pm/wildfly/resources/modules/system/layers/base/org/jboss/as/product/wildfly-full/dir/META-INF/MANIFEST.MF
  galleon-pack/src/main/resources/packages/product.conf/pm/wildfly/tasks.xml
  galleon-pack/wildfly-feature-pack-build.xml
  pom.xml
Labels: deps-ok

#13093 WFLY-13216 /openapi throws 406 when Accept header is sufficiently complex
  microprofile/openapi-smallrye/src/main/java/org/wildfly/extension/microprofile/openapi/deployment/OpenAPIHttpHandler.java
  testsuite/integration/microprofile/src/test/java/org/wildfly/test/integration/microprofile/openapi/OpenAPIFormatTestCase.java
  testsuite/integration/microprofile/src/test/java/org/wildfly/test/integration/microprofile/openapi/service/EchoResource.java
Labels: deps-ok, ready-for-merge

#13096 [19.0.x] WFLY-13216 /openapi throws 406 when Accept header is sufficiently complex
  microprofile/openapi-smallrye/src/main/java/org/wildfly/extension/microprofile/openapi/deployment/OpenAPIHttpHandler.java
  testsuite/integration/microprofile/src/test/java/org/wildfly/test/integration/microprofile/openapi/OpenAPIFormatTestCase.java
  testsuite/integration/microprofile/src/test/java/org/wildfly/test/integration/microprofile/openapi/service/EchoResource.java
Labels: 19.x, deps-ok, ready-for-merge

#13098 [WFLY-13137] Remove unneeded use of relativePath in poms now that expressions are …
  build/pom.xml
  dist/pom.xml
  microprofile/fault-tolerance-smallrye/executor/pom.xml
  microprofile/fault-tolerance-smallrye/extension/pom.xml
  microprofile/fault-tolerance-smallrye/pom.xml
  microprofile/jwt-smallrye/pom.xml
  microprofile/openapi-smallrye/pom.xml
Labels: deps-ok, ready-for-merge

#13099 [WFLY-13137] Remove unneeded use of relativePath in poms now that expressions are …
  build/pom.xml
  dist/pom.xml
  galleon-pack/pom.xml
  microprofile/fault-tolerance-smallrye/executor/pom.xml
  microprofile/fault-tolerance-smallrye/extension/pom.xml
  microprofile/fault-tolerance-smallrye/pom.xml
  microprofile/jwt-smallrye/pom.xml
  microprofile/openapi-smallrye/pom.xml
Labels: deps-ok, ready-for-merge

#13090 WFLY-13214 Add section headers for different session management profiles
  docs/src/main/asciidoc/_high-availability/subsystem-support/Distributable_Web_Applications.adoc
Labels: deps-ok, ready-for-merge

#13094 [WFLY-13217] Update wildfly-transaction-client to 1.1.10.Final
  pom.xml
Labels: deps-ok, ready-for-merge

#13095 [WFLY-13218] Upgrade jboss-ejb-client to 4.0.31.Final
  pom.xml
Labels: deps-ok, ready-for-merge

#13084 WFLY-13162 ConcurrentModificationException in WildFlyJobXmlResolver
  batch-jberet/src/main/java/org/wildfly/extension/batch/jberet/deployment/WildFlyJobXmlResolver.java
Labels: deps-ok, ready-for-merge

#13097 [WFLY-13219] Upgrade jose4j to 0.7.0 to align with the version used b…
  pom.xml
Labels: deps-ok, ready-for-merge

#13104 [WFLY-13229] Upgrade WildFly Core 11.0.0.Final
  pom.xml
Labels: deps-ok

#13105 [19.0.x][WFLY-13229] Upgrade WildFly Core 11.0.0.Final
  pom.xml
Labels: 19.x, deps-ok

#13106 [WFLY-13225] / [WFLY-12870] JSF component upgrades
  pom.xml
Labels: deps-ok, ready-for-merge

#13089 [WFLY-13185]:Add microprofile restclient dependency to jaxrs deployment to fix NPE issue
  jaxrs/src/main/java/org/jboss/as/jaxrs/JaxrsSubsystemDefinition.java
  jaxrs/src/main/java/org/jboss/as/jaxrs/deployment/JaxrsDependencyProcessor.java
Labels: deps-ok, ready-for-merge

#13092 [WFLY-13185]:Add microprofile restclient dependency to jaxrs deployment
  jaxrs/src/main/java/org/jboss/as/jaxrs/JaxrsSubsystemDefinition.java
  jaxrs/src/main/java/org/jboss/as/jaxrs/deployment/JaxrsDependencyProcessor.java
Labels: 19.x, deps-ok, ready-for-merge

#13086 Fix for WFLY-13210, open-tracing layer must depend on microprofile-config
  ee-galleon-pack/src/main/resources/layers/standalone/open-tracing/layer-spec.xml
Labels: deps-ok, ready-for-merge

#13087 [19.0.x] Fix for WFLY-13210, open-tracing layer must depend on microprofile-config
  ee-galleon-pack/src/main/resources/layers/standalone/open-tracing/layer-spec.xml
Labels: 19.x, deps-ok, ready-for-merge

#13111 [19.x] WFLY-13121 jgroups channel protocol read-resource error with include-…
  clustering/jgroups/extension/src/main/java/org/jboss/as/clustering/jgroups/subsystem/ProtocolMetricsHandler.java
Labels: 19.x, deps-ok, ready-for-merge

#13107 [WFLY-13232] The correct license name for JBoss Negotiation is "GNU Lesser General Public License v2.1 or later".
  servlet-feature-pack/src/license/servlet-feature-pack-licenses.xml
Labels: deps-ok, ready-for-merge

#13109 WFLY-13235 Upgrade JGroups to 4.2.1.Final
  pom.xml
Labels: deps-ok

#13114 WFLY-13240 Clustering TS: Default to non-multicast discovery protocol…
  testsuite/integration/clustering/clustering-all.cli
  testsuite/integration/clustering/src/test/java/org/jboss/as/test/clustering/cluster/xsite/XSiteSimpleTestCase.java
Labels: deps-ok

#13113 WFLY-13233 & WFLY-13238 Mutable attribute fixes
  clustering/web/cache/src/main/java/org/wildfly/clustering/web/cache/session/fine/FineSessionAttributes.java
  clustering/web/hotrod/src/main/java/org/wildfly/clustering/web/hotrod/session/coarse/CoarseSessionAttributesFactory.java
  clustering/web/infinispan/src/main/java/org/wildfly/clustering/web/infinispan/session/coarse/CoarseSessionAttributesFactory.java
  testsuite/integration/clustering/src/test/java/org/jboss/as/test/clustering/cluster/cdi/CdiIncrementorBean.java
  testsuite/integration/clustering/src/test/java/org/jboss/as/test/clustering/cluster/cdi/CdiServlet.java
  testsuite/integration/clustering/src/test/java/org/jboss/as/test/clustering/cluster/ejb/stateful/bean/Incrementor.java
  testsuite/integration/clustering/src/test/java/org/jboss/as/test/clustering/cluster/web/AbstractWebFailoverTestCase.java
  testsuite/integration/clustering/src/test/java/org/jboss/as/test/clustering/cluster/web/remote/AbstractHotRodWebFailoverTestCase.java
  testsuite/integration/clustering/src/test/java/org/jboss/as/test/clustering/single/web/Mutable.java
  testsuite/integration/clustering/src/test/java/org/jboss/as/test/clustering/single/web/SimpleServlet.java
Labels: deps-ok

#13116 [WFLY-13242] Upgrade snakeyaml to 1.26
  pom.xml
Labels: deps-ok

#13119 [19.0.x][WFLY-13242] Upgrade snakeyaml to 1.26
  pom.xml
Labels: 19.x, deps-ok

#13117 [WFLY-13243] Upgrade cryptacular to 1.24
  pom.xml
Labels: deps-ok

#13118 [19.0.x][WFLY-13243] Upgrade cryptacular to 1.24
  pom.xml
Labels: 19.x, deps-ok

#13123 Fix for WFLY-13204, Move testsuite/layers in ts.layers profile
  testsuite/layers/pom.xml
  testsuite/pom.xml
Labels: deps-ok

#13126 [WFLY-13261]: Messages are being added to topic even if there are no
  messaging-activemq/src/main/java/org/wildfly/extension/messaging/activemq/ConfigurationHelper.java
Labels: deps-ok

#13108 WFLY-13162 ConcurrentModificationException in WildFlyJobXmlResolver
  batch-jberet/src/main/java/org/wildfly/extension/batch/jberet/deployment/WildFlyJobXmlResolver.java
Labels: deps-ok

#13125 [WFLY-13255] Upgrade Apache wss4j to 2.2.5
  pom.xml
Labels: deps-ok

#13120 [WFLY-13247] Upgrade Jakarta Mail to 1.6.5
  pom.xml
Labels: deps-ok

#12804 [WFLY-12624] Adjust default client mapping to return hostname if possible
  ejb3/src/main/java/org/jboss/as/ejb3/remote/EJBRemotingConnectorClientMappingsEntryProviderService.java
Labels: deps-changed, ready-for-merge

#12974 WFLY-13074 Don't start the app context unless the server is running.
  mod_cluster/undertow/src/main/java/org/wildfly/mod_cluster/undertow/UndertowEventHandlerAdapterService.java
Labels: deps-changed, ready-for-merge

#13115 WFLY-11315 Remove unused dependencies from org.jboss.as.jpa
  feature-pack/src/main/resources/modules/system/layers/base/org/jboss/as/jpa/main/module.xml
Labels: deps-ok, ready-for-merge

#13124 [WFLY-12567] Upgrade PicketLink from 2.5.5.SP12-redhat-00006 to 2.5.5.SP12-redhat-00009
  pom.xml
Labels: deps-ok, ready-for-merge

#13047 [WFLY-13161] CLIENT-CERT login does not work in intermediate elytron setup
  security/subsystem/src/main/java/org/jboss/as/security/elytron/SecurityDomainContextRealm.java
  testsuite/integration/basic/src/test/java/org/wildfly/test/elytron/intermediate/X509SecurityDomainContextRealmTestCase.java
  testsuite/integration/basic/src/test/java/org/wildfly/test/elytron/intermediate/x509-security-domain-context-realm-web.xml
Labels: deps-ok

#13129 [WFLY-12851] Upgrade PicketLink bindings from 2.5.5.SP12-redhat-00009-jbossorg-1 to 2.5.5.SP12-redhat-00012
  pom.xml
Labels: deps-ok

#13132 [WFLY-13255]:Upgrade to Apache WSS4j 2.2.5
  pom.xml
Labels: deps-ok

#13136 [WFLY-13284] Fix incorrect method call in EJB3IIOPResource write-attibute handler
  ejb3/src/main/java/org/jboss/as/ejb3/subsystem/EJB3IIOPResourceDefinition.java
Labels: deps-ok

#13133 [WFLY-13273] Add tests for WFCORE-4860. The tests are required here a…
  testsuite/integration/basic/pom.xml
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/logging/config/AbstractConfigTestCase.java
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/logging/config/LoggerResource.java
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/logging/config/LoggingConfigSharedTestCase.java
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/logging/config/LoggingConfigTestCase.java
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/logging/config/LoggingProfileSharedTestCase.java
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/logging/config/LoggingProfileTestCase.java
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/logging/config/LoggingServlet.java
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/logging/config/LoggingStartup.java
Labels: deps-ok, ready-for-merge

#13138 [WFLY-13054] : Upgrade of jackson databind to 2.10.3 ...
  pom.xml
Labels: deps-ok

#13145 [WFLY-13156] Upgrade to RESTEasy 3.11.1.Final
  pom.xml
Labels: deps-ok

#13146 Fix project URL in README.md
  README.md
Labels: deps-ok

#13152 [WFLY-12834] Add documentation on the enabled-protocols attribute and indicate how it works when OpenSSL 1.1.0 or higher is in use
  docs/src/main/asciidoc/_admin-guide/Security_Realms_Detailed_Configuration.adoc
Labels: deps-ok, ready-for-merge

#13153 [WFLY-13297] Provide the deployment's PropertyReplacer to WeldInjecti…
  feature-pack/src/main/resources/modules/system/layers/base/org/jboss/as/weld/common/main/module.xml
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/ee/injection/resource/substitution/ResourceInjectionSubstitutionTestCase.java
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/ee/injection/resource/substitution/SimpleCDIBean.java
  weld/common/src/main/java/org/jboss/as/weld/util/ResourceInjectionUtilities.java
  weld/subsystem/src/main/java/org/jboss/as/weld/deployment/processors/DefaultModuleServiceProvider.java
  weld/subsystem/src/main/java/org/jboss/as/weld/services/bootstrap/WeldResourceInjectionServices.java
Labels: deps-ok
