Repository wildfly/wildfly, pull requests merged in 2020-12, with the labels that each got.

#13759 [WFLY-14145] Temporarily ignore SecurityCommandsTestCase
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/management/cli/SecurityCommandsTestCase.java
Labels: deps-ok

#13746 [WFLY-14135] Do not overwrite the default-stateful-bean-access-timeou…
  ee-feature-pack/galleon-common/src/main/resources/layers/standalone/ejb-dist-cache/layer-spec.xml
  ee-feature-pack/galleon-common/src/main/resources/layers/standalone/ejb-local-cache/layer-spec.xml
Labels: deps-ok, ready-for-merge

#13762 [WFLY-14149] Upgrade HAL to 3.2.12.Final
  pom.xml
Labels: deps-ok, ready-for-merge

#13764 WFLY-14152 Upgrade smallrye-fault-tolerance to 4.3.2
  pom.xml
Labels: deps-ok, ready-for-merge

#13768 WFLY-14155 Upgrade JGroups to 4.2.10.Final
  pom.xml
Labels: deps-ok

#13767 WFLY-14153 Upgrade smallrye-open-api to 2.0.15
  pom.xml
Labels: deps-ok

#13758 [WFLY-14093] deprecate XTS
  ee-feature-pack/common/src/main/resources/modules/system/layers/base/org/jboss/narayana/compensations/main/module.xml
  ee-feature-pack/common/src/main/resources/modules/system/layers/base/org/jboss/xts/main/module.xml
  xts/src/main/java/org/jboss/as/xts/XTSSubsystemDefinition.java
  xts/src/main/resources/org/jboss/as/xts/LocalDescriptions.properties
Labels: deps-ok

#13763 [WFLY-14150] Upgrade Galleon Plugins to 5.0.0.Beta3
  pom.xml
Labels: deps-ok, ready-for-merge

#13770 WFLY-14154 Upgrade Infinispan to 11.0.7.Final
  clustering/infinispan/client/src/main/java/org/wildfly/clustering/infinispan/client/RemoteCacheContainer.java
  clustering/infinispan/extension/src/main/java/org/jboss/as/clustering/infinispan/subsystem/InfinispanSubsystemXMLReader.java
  clustering/infinispan/extension/src/main/java/org/jboss/as/clustering/infinispan/subsystem/ThreadPoolServiceConfigurator.java
  pom.xml
  testsuite/integration/clustering/pom.xml
Labels: deps-ok, ready-for-merge

#13775 [WFLY-14158] Override the observability layer from the 'wildfly-ee' f…
  microprofile/galleon-common/src/main/resources/layers/standalone/observability/layer-spec.xml
Labels: deps-ok

#13776 WFLY-14118 Distributed session manager can throw UnsupportedOperationException...
  clustering/ee/cache/src/main/java/org/wildfly/clustering/ee/cache/ConcurrentManager.java
  clustering/ee/cache/src/test/java/org/wildfly/clustering/ee/cache/ConcurrentManagerTestCase.java
Labels: 21.x, deps-ok

#13779 [21.x][WFLY-14094]: Potential memory leak when using opentracing.
  pom.xml
Labels: 21.x, deps-ok

#13771 [WFLY-14010] Upgrade Mojarra to 2.3.14.SP02
  pom.xml
Labels: deps-ok, ready-for-merge

#13778 [WFLY-14161] Upgrade jboss-ejb-client to 4.0.37.Final
  pom.xml
Labels: deps-ok

#13425 [WFLY-13698] NullPointerException due to JSFDependencyProcessor addin…
  jsf/subsystem/src/main/java/org/jboss/as/jsf/deployment/JSFDependencyProcessor.java
  pom.xml
  testsuite/integration/basic/pom.xml
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/jsf/deployment/NonExistingJsfImplDeploymentTestCase.java
Labels: deps-ok

#13782 [WFLY-14166] Upgrade WildFly Core 14.0.0.Beta3
  pom.xml
Labels: deps-ok

#13773 [WFLY-14090] Use shared test utilities for log handling in NetworkHea…
  testsuite/integration/manualmode/src/test/java/org/jboss/as/test/manualmode/messaging/NetworkHealthTestCase.java
  testsuite/shared/src/main/java/org/jboss/as/test/shared/util/LoggingUtil.java
Labels: deps-ok

#13596 [WFLY-13782] Tests and documentation for the automatic generation of a self-signed certificate on first use
  docs/src/main/asciidoc/_elytron/Elytron_Subsystem.adoc
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/management/cli/SecurityCommandsTestCase.java
  testsuite/integration/elytron/src/test/java/org/wildfly/test/integration/elytron/ssl/AutomaticSelfSignedCertificateGenerationTestCase.java
  testsuite/integration/elytron/src/test/java/org/wildfly/test/integration/elytron/ssl/AutomaticSelfSignedCertificateNotGeneratedTestCase.java
  testsuite/shared/src/main/java/org/wildfly/test/security/common/elytron/SimpleKeyManager.java
Labels: 22.x, deps-ok

#13742 [WFLY-14113] Move wildfly-preview to jakarta.authentication-api
  ee-9/feature-pack/pom.xml
  ee-9/feature-pack/src/license/feature-pack-licenses.xml
  ee-9/feature-pack/src/main/resources/modules/system/layers/base/jakarta/security/auth/message/api/main/module.xml
Labels: deps-ok

#13744 [WFLY-14025] Don't create default binding injections if they are not …
  connector/src/main/java/org/jboss/as/connector/deployers/datasource/DefaultDataSourceResourceReferenceProcessor.java
  ee/src/main/java/org/jboss/as/ee/component/deployers/ResourceReferenceRegistrySetupProcessor.java
  ee/src/main/java/org/jboss/as/ee/subsystem/DefaultBindingsAdd.java
  messaging-activemq/src/main/java/org/wildfly/extension/messaging/activemq/deployment/DefaultJMSConnectionFactoryResourceReferenceProcessor.java
Labels: deps-ok

#13781 [WFLY-14165] Move the EE 9 EJB API spec jar to the final 4.0.0 release
  ee-9/feature-pack/pom.xml
Labels: deps-ok

#13786 [WFLY-14163] Remove the BouncyCastle dependency definitions as these are defined in WildFly Core.
  pom.xml
  testsuite/integration/elytron/pom.xml
Labels: deps-ok

#13772 WFLY-13792 Test for JSF deployment failure due to UnsupportedOperationExceptio…
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/jsf/unsupportedwar/ConfigurationBean.java
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/jsf/unsupportedwar/FaceletsViewMappingsTestCase.java
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/jsf/unsupportedwar/HelloBean.java
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/jsf/unsupportedwar/hello.jsf
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/jsf/unsupportedwar/web.xml
Labels: deps-ok

#13769 Update the logging documentation for log4j2.
  docs/src/main/asciidoc/_admin-guide/subsystem-configuration/Logging_How_To.adoc
  docs/src/main/asciidoc/_developer-guide/Implicit_module_dependencies_for_deployments.adoc
Labels: Feature-Docs, core-upgrade-needed, deps-ok

#13801 [WFLY-14187] Upgrade to EE 9 fork of Jakarta Expression Language SPEC API (jboss-jakarta-el-api_spec)
  ee-9/feature-pack/pom.xml
  ee-9/feature-pack/src/license/feature-pack-licenses.xml
  ee-9/feature-pack/src/main/resources/modules/system/layers/base/jakarta/el/api/main/module.xml
Labels: deps-ok

#13789 [WFLY-14171]:Upgrade jbossws-spi to 3.3.1.Final
  pom.xml
Labels: deps-ok, ready-for-merge

#13784 WFLY-13307 Throw javax.ejb.ConcurrentAccessTimeoutException if bean lookup times out due to concurrent access by another cluster member
  clustering/ejb/infinispan/src/main/java/org/wildfly/clustering/ejb/infinispan/bean/InfinispanBeanFactory.java
  ee-feature-pack/common/src/main/resources/modules/system/layers/base/org/wildfly/clustering/ejb/infinispan/main/module.xml
Labels: deps-ok

#13755 [WFLY-9288] Enable session auto-creation in the event that the wrong …
  ejb3/src/main/java/org/jboss/as/ejb3/remote/AssociationImpl.java
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/ejb/remote/client/api/EJBClientAPIUsageTestCase.java
Labels: deps-ok

#13752 [WFLY-14114] JDBC: deregister all drivers on undeployment
  connector/src/main/java/org/jboss/as/connector/_drivermanager/DriverManagerAdapter.java
  connector/src/main/java/org/jboss/as/connector/deployers/ds/processors/DriverManagerAdapterProcessor.java
  connector/src/main/java/org/jboss/as/connector/deployers/ds/processors/DriverProcessor.java
  connector/src/main/java/org/jboss/as/connector/deployers/ra/RaDeploymentActivator.java
  ee-feature-pack/common/src/main/resources/modules/system/layers/base/org/jboss/as/connector/main/module.xml
Labels: deps-ok

#13790 WFLY-14172 Update Weld 4 for EE 9 WFLY. Also try to align Weld SE ver…
  ee-9/feature-pack/pom.xml
  pom.xml
Labels: deps-ok, ready-for-merge

#13797 [WFLY-14182] Upgrade MyFaces to 2.3.7
  jsf/multi-jsf-installer/pom.xml
  pom.xml
Labels: deps-ok, ready-for-merge

#13347 WFLY-11999 Wildfly creates to many instances of all web service classes
  ee-feature-pack/common/src/main/resources/modules/system/layers/base/org/jboss/as/webservices/main/module.xml
  testsuite/integration/ws/src/test/java/org/jboss/as/test/integration/ws/basic/InstanceCountEndpoint.java
  testsuite/integration/ws/src/test/java/org/jboss/as/test/integration/ws/basic/InstanceCountEndpointIface.java
  testsuite/integration/ws/src/test/java/org/jboss/as/test/integration/ws/basic/InstanceCountEndpointTestcase.java
  webservices/server-integration/src/main/java/org/jboss/as/webservices/deployers/deployment/AbstractDeploymentModelBuilder.java
  webservices/server-integration/src/main/java/org/jboss/as/webservices/deployers/deployment/DeploymentModelBuilderJAXWS_EJB.java
  webservices/server-integration/src/main/java/org/jboss/as/webservices/deployers/deployment/DeploymentModelBuilderJAXWS_JMS.java
  webservices/server-integration/src/main/java/org/jboss/as/webservices/deployers/deployment/DeploymentModelBuilderJAXWS_POJO.java
  webservices/server-integration/src/main/java/org/jboss/as/webservices/invocation/AbstractInvocationHandler.java
  webservices/server-integration/src/main/java/org/jboss/as/webservices/metadata/model/AbstractEndpoint.java
Labels: deps-ok

#13791 [WFLY-14174] Update DefaultBindingsAdd to use Phase ID defined in WildFly Core.
  ee/src/main/java/org/jboss/as/ee/subsystem/DefaultBindingsAdd.java
Labels: deps-ok

#13804 WFLY-14132 jboss-ejb3.xml is ignored for exploded deployments
  ejb3/src/main/java/org/jboss/as/ejb3/deployment/processors/EjbJarParsingDeploymentUnitProcessor.java
Labels: deps-ok

#13805 [WFLY-14183] Upgrade RESTEasy to 3.14.0.Final
  docs/src/main/asciidoc/_admin-guide/Subsystem_configuration.adoc
  docs/src/main/asciidoc/_admin-guide/subsystem-configuration/JAXRS.adoc
  pom.xml
Labels: deps-ok

#13792 WFLY-14175 Update Jakarta Activation 1.2.2
  pom.xml
Labels: deps-ok, ready-for-merge

#13796 WFLY-14179 Update Apache commons-lang3 3.11
  pom.xml
Labels: deps-ok, ready-for-merge

#13807 WFLY-14205 Upgrade smallrye-open-api to 2.0.16
  pom.xml
Labels: deps-ok, ready-for-merge

#13809 WFLY-14204 Upgrade Infinispan to 11.0.8.Final
  pom.xml
  testsuite/integration/clustering/pom.xml
Labels: deps-ok, ready-for-merge

#13816 [WFLY-14217] Upgrade WildFly Core 14.0.0.Beta4
  pom.xml
Labels: deps-ok

#13817 [WFLY-14194] Driver processor: only remove drivers explicitly registe…
  connector/src/main/java/org/jboss/as/connector/deployers/ds/processors/DriverProcessor.java
Labels: deps-ok

#13813 [WFLY-14213] Update org.kohsuke.metainf-services 1.8
  pom.xml
Labels: deps-ok, ready-for-merge

#13814 Fix for WFLY-14214 and WFLY-14198, Galleon upgrades
  pom.xml
Labels: deps-ok, ready-for-merge

#13760 WFLY-14147 Near-cache should be disabled when max-active-sessions is 0
  clustering/infinispan/client/src/main/java/org/wildfly/clustering/infinispan/client/NearCacheFactory.java
  clustering/infinispan/client/src/main/java/org/wildfly/clustering/infinispan/client/RemoteCacheContainer.java
  clustering/infinispan/client/src/main/java/org/wildfly/clustering/infinispan/client/manager/RemoteCacheManager.java
  clustering/infinispan/client/src/main/java/org/wildfly/clustering/infinispan/client/near/SimpleNearCacheFactory.java
  clustering/infinispan/client/src/main/java/org/wildfly/clustering/infinispan/client/service/RemoteCacheServiceConfigurator.java
  clustering/infinispan/extension/src/main/java/org/jboss/as/clustering/infinispan/subsystem/remote/ManagedRemoteCacheContainer.java
  clustering/web/hotrod/src/main/java/org/wildfly/clustering/web/hotrod/session/SessionManagerNearCacheFactory.java
  clustering/web/hotrod/src/main/java/org/wildfly/clustering/web/hotrod/sso/HotRodSSOManagerFactoryServiceConfigurator.java
Labels: deps-ok

#13798 WFLY-14181 Update Apache Groovy 2.4.21
  pom.xml
Labels: deps-ok

#13822 [WFLY-14220] Upgrade Hibernate Validator to 7.0.0.CR1 in WildFly Preview
  ee-9/feature-pack/pom.xml
Labels: deps-ok, ready-for-merge

#13820 [WFLY-14211] Always clean the target dir when building feature packs
  ee-9/feature-pack/pom.xml
  ee-feature-pack/galleon-feature-pack/pom.xml
  ee-feature-pack/legacy-feature-pack/pom.xml
  galleon-pack/pom.xml
  servlet-feature-pack/galleon-feature-pack/pom.xml
  servlet-feature-pack/legacy-feature-pack/pom.xml
Labels: deps-ok

#13716 [WFLY-9213]: Implement the Pause method for a Topic via Management APIs
  docs/src/main/asciidoc/_admin-guide/subsystem-configuration/Messaging.adoc
  messaging-activemq/src/main/java/org/wildfly/extension/messaging/activemq/MessagingTransformerRegistration.java
  messaging-activemq/src/main/java/org/wildfly/extension/messaging/activemq/jms/JMSTopicControlHandler.java
  messaging-activemq/src/main/java/org/wildfly/extension/messaging/activemq/jms/JMSTopicDefinition.java
  messaging-activemq/src/main/java/org/wildfly/extension/messaging/activemq/jms/JMSTopicReadAttributeHandler.java
  messaging-activemq/src/main/resources/org/wildfly/extension/messaging/activemq/LocalDescriptions.properties
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/messaging/mgmt/JMSTopicManagementTestCase.java
  testsuite/integration/manualmode/src/test/java/org/jboss/as/test/manualmode/messaging/RuntimeJMSTopicManagementTestCase.java
Labels: Feature, deps-ok, ready-for-merge

#13675 [WFLY-13695] Upgrade Wildfly HTTP Client to 1.1.4.Final
  pom.xml
Labels: deps-ok

#13824 [WFLY-14226] Upgrade Mojarra to 3.0.0.SP03 in the EE9 feature pack
  ee-9/feature-pack/pom.xml
Labels: deps-ok

#13757 WFLY-14076 HotRodSessionManager fails to expire abandoned sessions following failover
  clustering/ee/cache/src/main/java/org/wildfly/clustering/ee/cache/ConcurrentManager.java
  clustering/ee/hotrod/src/main/java/org/wildfly/clustering/ee/hotrod/RemoteCacheEntryMutator.java
  clustering/ee/hotrod/src/main/java/org/wildfly/clustering/ee/hotrod/RemoteCacheMutatorFactory.java
  clustering/web/cache/src/main/java/org/wildfly/clustering/web/cache/session/CompositeSessionFactory.java
  clustering/web/cache/src/main/java/org/wildfly/clustering/web/cache/session/CompositeSessionMetaDataEntry.java
  clustering/web/cache/src/main/java/org/wildfly/clustering/web/cache/session/SessionFactory.java
  clustering/web/hotrod/src/main/java/org/wildfly/clustering/web/hotrod/session/ExpiredSessionRemover.java
  clustering/web/hotrod/src/main/java/org/wildfly/clustering/web/hotrod/session/HotRodSessionFactory.java
  clustering/web/hotrod/src/main/java/org/wildfly/clustering/web/hotrod/session/HotRodSessionManager.java
  clustering/web/hotrod/src/main/java/org/wildfly/clustering/web/hotrod/session/HotRodSessionManagerConfiguration.java
  clustering/web/hotrod/src/main/java/org/wildfly/clustering/web/hotrod/session/HotRodSessionManagerFactory.java
  clustering/web/hotrod/src/main/java/org/wildfly/clustering/web/hotrod/session/HotRodSessionMetaDataFactory.java
  clustering/web/hotrod/src/main/java/org/wildfly/clustering/web/hotrod/session/SessionExpirationScheduler.java
  clustering/web/infinispan/src/main/java/org/wildfly/clustering/web/infinispan/session/InfinispanSessionManagerFactory.java
  clustering/web/infinispan/src/main/java/org/wildfly/clustering/web/infinispan/session/InfinispanSessionMetaDataFactory.java
  ee-feature-pack/common/src/main/resources/modules/system/layers/base/org/wildfly/clustering/web/hotrod/main/module.xml
  ee-feature-pack/common/src/main/resources/modules/system/layers/base/org/wildfly/clustering/web/infinispan/main/module.xml
  testsuite/integration/clustering/pom.xml
  testsuite/integration/clustering/src/test/java/org/jboss/as/test/clustering/cluster/web/expiration/SessionExpirationTestCase.java
  testsuite/integration/clustering/src/test/java/org/jboss/as/test/clustering/cluster/web/expiration/SessionOperationServlet.java
  testsuite/integration/clustering/src/test/java/org/jboss/as/test/clustering/cluster/web/remote/AbstractHotRodSessionExpirationTestCase.java
  testsuite/integration/clustering/src/test/java/org/jboss/as/test/clustering/cluster/web/remote/CoarseHotRodSessionExpirationTestCase.java
  testsuite/integration/clustering/src/test/java/org/jboss/as/test/clustering/cluster/web/remote/FineHotRodSessionExpirationTestCase.java
  testsuite/integration/clustering/src/test/java/org/jboss/as/test/clustering/cluster/web/remote/InfinispanServerSetupTask.java
Labels: deps-ok

#13812 [WFLY-14210] Bump the jaxrs subsystems model version. Reject attribut…
  jaxrs/src/main/java/org/jboss/as/jaxrs/JaxrsDeploymentDefinition.java
  jaxrs/src/main/java/org/jboss/as/jaxrs/JaxrsExtension.java
  jaxrs/src/main/java/org/jboss/as/jaxrs/JaxrsSubsystemParser_1_0.java
  jaxrs/src/main/java/org/jboss/as/jaxrs/JaxrsSubsystemParser_2_0.java
  jaxrs/src/main/java/org/jboss/as/jaxrs/JaxrsTransformers.java
  jaxrs/src/test/java/org/jboss/as/jaxrs/JaxrsTransformersTestCase.java
Labels: deps-ok

#13379 [WFLY-13570] Add the ability to adjust the case of a user name using an Elytron principal transformer
  docs/src/main/asciidoc/_elytron/Elytron_Subsystem.adoc
  docs/src/main/asciidoc/_elytron/Using_the_Elytron_Subsystem.adoc
  testsuite/integration/elytron/src/test/java/org/wildfly/test/integration/elytron/principaltransformers/CasePrincipalTransformerTestCase.java
Labels: 22.x, Feature-Docs, deps-ok

#13825 [WFLY-14199] Do not remove the microprofile-opentracing-smallrye subs…
  testsuite/integration/microprofile/src/test/java/org/wildfly/test/integration/microprofile/opentracing/OnOffOpenTracingTestCase.java
  testsuite/integration/microprofile/src/test/java/org/wildfly/test/integration/microprofile/opentracing/application/SimpleJaxRs.java
Labels: deps-ok

#13573 [WFLY-13876] Test for key-store certificate realm login (test for ELY-2023)
  testsuite/integration/elytron/src/test/java/org/wildfly/test/integration/elytron/certs/CommonBase.java
  testsuite/integration/elytron/src/test/java/org/wildfly/test/integration/elytron/certs/realm/KeystoreRealmTestCase-web.xml
  testsuite/integration/elytron/src/test/java/org/wildfly/test/integration/elytron/certs/realm/KeystoreRealmTestCase.java
Labels: 22.x, deps-ok

#13404 WFLY-13655 LOG INFO level message if the Hibernate second level cache is enabled
  jpa/hibernate5_3/src/main/java/org/jboss/as/jpa/hibernate5/HibernatePersistenceProviderAdaptor.java
  jpa/hibernate5_3/src/main/java/org/jboss/as/jpa/hibernate5/JpaLogger.java
Labels: deps-ok

#13487 [WFLY-13150] Create a Galleon layer for distributable web
  docs/src/main/asciidoc/_galleon/Galleon_layers.adoc
  ee-feature-pack/galleon-common/src/main/resources/layers/standalone/web-passivation/layer-spec.xml
  testsuite/integration/clustering/clustering-web-passivation.cli
  testsuite/integration/clustering/pom.xml
  testsuite/integration/clustering/src/test/config/arq/arquillian-bootable.xml
  testsuite/integration/clustering/src/test/config/arq/arquillian.xml
  testsuite/integration/clustering/src/test/java/org/jboss/as/test/clustering/single/web/NonHaWebSessionPersistenceTestCase.java
  testsuite/integration/clustering/src/test/resources/filtered/clustering-web-passivation.properties
  testsuite/layers/pom.xml
  testsuite/pom.xml
Labels: 22.x, Feature, deps-ok, missing-reqs

#13539 [WFLY-13283] suspending WFTC transaction on response of REST-AT bridge
  rts/src/main/java/org/wildfly/extension/rts/jaxrs/ImportWildflyClientGlobalTransactionFilter.java
  rts/src/main/java/org/wildfly/extension/rts/logging/RTSLogger.java
  xts/src/main/java/org/jboss/as/xts/XTSHandlerDeploymentProcessor.java
  xts/src/main/java/org/jboss/as/xts/txnclient/WildflyTransactionClientTxBridgeIntegrationHandler.java
Labels: deps-ok

#13828 [WFLY-14229] Allow MP modules to easily change its maven groupid
  ee-feature-pack/common/src/license/feature-pack-licenses.xml
  microprofile/config-smallrye/pom.xml
  microprofile/galleon-common/src/license/microprofile-feature-pack-licenses.xml
  microprofile/health-smallrye/pom.xml
  microprofile/metrics-smallrye/pom.xml
  microprofile/opentracing-extension/pom.xml
  microprofile/opentracing-smallrye/pom.xml
Labels: deps-ok

#13823 Fix for WFLY-14190, EE9 tests for bootable jar
  pom.xml
  testsuite/integration/basic/pom.xml
  testsuite/integration/clustering/pom.xml
  testsuite/integration/clustering/src/test/java/org/jboss/as/test/clustering/cluster/sso/ElytronSSOServerSetupTask.java
  testsuite/integration/clustering/src/test/java/org/jboss/as/test/clustering/single/web/NonHaWebSessionPersistenceTestCase.java
  testsuite/integration/elytron/pom.xml
  testsuite/integration/microprofile-tck/config/pom.xml
  testsuite/integration/microprofile-tck/fault-tolerance/pom.xml
  testsuite/integration/microprofile-tck/health/pom.xml
  testsuite/integration/microprofile-tck/jwt/pom.xml
  testsuite/integration/microprofile-tck/metrics/pom.xml
  testsuite/integration/microprofile-tck/openapi/pom.xml
  testsuite/integration/microprofile-tck/opentracing/pom.xml
  testsuite/integration/microprofile-tck/pom.xml
  testsuite/integration/microprofile-tck/rest-client/pom.xml
  testsuite/integration/microprofile/pom.xml
  testsuite/integration/microprofile/src/test/java/org/wildfly/test/integration/microprofile/config/smallrye/converter/SetupTask.java
  testsuite/integration/pom.xml
  testsuite/integration/smoke/pom.xml
  testsuite/integration/web/pom.xml
Labels: deps-ok

#13747 [WFLY-12503] Turn off the default surefire execution when the 'elytron', 'security.manager' and 'bootable.jar' profiles are used
  pom.xml
  testsuite/compat/pom.xml
  testsuite/domain/pom.xml
  testsuite/integration/basic/pom.xml
  testsuite/integration/clustering/pom.xml
  testsuite/integration/elytron/pom.xml
  testsuite/integration/iiop/pom.xml
  testsuite/integration/manualmode/pom.xml
  testsuite/integration/microprofile/pom.xml
  testsuite/integration/pom.xml
  testsuite/integration/smoke/pom.xml
  testsuite/integration/web/pom.xml
  testsuite/integration/ws/pom.xml
  testsuite/layers/pom.xml
  testsuite/mixed-domain/pom.xml
  testsuite/pom.xml
Labels: deps-ok

#13736 [WFLY-14115] Multinode tests failures: grant delete permission for EJ…
  testsuite/integration/multinode/src/test/java/org/jboss/as/test/multinode/ejb/http/EjbOverHttpDescriptorTestCase.java
  testsuite/integration/multinode/src/test/java/org/jboss/as/test/multinode/ejb/http/EjbOverHttpTestCase.java
  testsuite/integration/multinode/src/test/java/org/jboss/as/test/multinode/ejb/http/EjbOverHttpWrongCredentialsTestCase.java
  testsuite/integration/multinode/src/test/java/org/jboss/as/test/multinode/remotecall/RemoteLocalCallProfileTestCase.java
  testsuite/integration/multinode/src/test/java/org/jboss/as/test/multinode/remotecall/RemoteLocalCallTestCase.java
  testsuite/integration/multinode/src/test/java/org/jboss/as/test/multinode/transaction/TransactionInvocationTestCase.java
  testsuite/integration/multinode/src/test/java/org/jboss/as/test/multinode/transaction/nooutbound/TransactionContextRemoteCallTestCase.java
Labels: deps-ok

#13679 [WFLY-14018] Allow injection for Validator/Converter/Behavior if managed=true
  jsf/subsystem/src/main/java/org/jboss/as/jsf/deployment/JSFAnnotationProcessor.java
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/jsf/injection/FacesConverterInjectionTestCase.java
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/jsf/injection/JSF23ConfigurationBean.java
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/jsf/injection/URLConverter.java
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/jsf/injection/UrlConverterBean.java
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/jsf/injection/url.xhtml
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/jsf/injection/web.xml
Labels: deps-ok, ready-for-merge

#13649 [WFLY-13968] Consider internal jaxb-impl module in more situations (tests)
  pom.xml
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/jaxb/FakeJAXBContextFactory.java
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/jaxb/JAXBContextServlet.java
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/jaxb/unit/JAXBContextSystemPropCustomTestCase.java
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/jaxb/unit/JAXBContextSystemPropInternalTestCase.java
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/jaxb/unit/JAXBContextTestBase.java
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/jaxb/unit/JAXBContextUsingPropertiesTestCase.java
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/jaxb/unit/JAXBContextUsingServicesTestCase.java
Labels: deps-ok

#13830 WFLY-14236 HotRodSessionManager expiration listener thread applies unnecessary JNDI context
  clustering/web/hotrod/src/main/java/org/wildfly/clustering/web/hotrod/session/HotRodSessionFactory.java
Labels: deps-ok

#13831 WFLY-14240 Upgrade Weld 4 for Final version.
  ee-9/feature-pack/pom.xml
Labels: deps-ok

#13834 [WFLY-14137] Typo in JWT_CAPABILITY_NAME
  microprofile/jwt-smallrye/src/main/java/org/wildfly/extension/microprofile/jwt/smallrye/Capabilities.java
Labels: deps-ok
