Repository wildfly/wildfly, pull requests merged in 2020-01, with the labels that each got.

#12777 [WFLY-12763] Create a 'bean-validation' layer separate from 'cdi'
  docs/src/main/asciidoc/_admin-guide/Galleon_provisioning.adoc
  galleon-pack/src/main/resources/layers/standalone/bean-validation/layer-spec.xml
  galleon-pack/src/main/resources/layers/standalone/cloud-profile/layer-spec.xml
  galleon-pack/src/main/resources/layers/standalone/jaxrs-server/layer-spec.xml
  testsuite/layers/pom.xml
Labels: deps-ok

#12873 [WFLY-12921] Upgrade SM Fault Tolerance to 2.1.4
  pom.xml
Labels: deps-ok

#12875 WFLY-12923 unused methodIdentifier removal
  ejb3/src/main/java/org/jboss/as/ejb3/security/EjbJaccConfigurator.java
Labels: deps-ok

#12881 WFLY-12929 HttpSessionListener.sessionDestroyed event can deadlock if it attempts write operations on a session
  clustering/web/infinispan/src/main/java/org/wildfly/clustering/web/infinispan/session/InfinispanSessionManager.java
Labels: deps-ok

#12878 [WFLY-12486]: Memory leak in OpenTracing when deployment is redeploy…
  feature-pack/src/main/resources/modules/system/layers/base/org/wildfly/extension/microprofile/opentracing-smallrye/main/module.xml
  feature-pack/src/main/resources/modules/system/layers/base/org/wildfly/microprofile/opentracing-smallrye/main/module.xml
  microprofile/opentracing-extension/src/main/java/org/wildfly/extension/microprofile/opentracing/SubsystemDefinition.java
  microprofile/opentracing-extension/src/main/java/org/wildfly/extension/microprofile/opentracing/TracingDeploymentProcessor.java
  microprofile/opentracing-extension/src/main/java/org/wildfly/extension/microprofile/opentracing/TracingExtensionLogger.java
  microprofile/opentracing-smallrye/src/main/java/org/wildfly/microprofile/opentracing/smallrye/TracerConstants.java
  microprofile/opentracing-smallrye/src/main/java/org/wildfly/microprofile/opentracing/smallrye/TracerDynamicFeature.java
  microprofile/opentracing-smallrye/src/main/java/org/wildfly/microprofile/opentracing/smallrye/TracerInitializer.java
  microprofile/opentracing-smallrye/src/main/java/org/wildfly/microprofile/opentracing/smallrye/TracerProducer.java
Labels: deps-ok

#12863 WFLY-12863 microprofile-health subsystem should not expose smallrye implementation to deployments
  microprofile/health-smallrye/src/main/java/org/wildfly/extension/microprofile/health/deployment/DependencyProcessor.java
Labels: ready-for-merge

#12874 [WFLY-12826] switch to GAV-based locations for feature-pack dependencies
  build/pom.xml
  dist/pom.xml
  galleon-pack/wildfly-feature-pack-build.xml
  pom.xml
  servlet-build/pom.xml
  servlet-dist/pom.xml
  servlet-galleon-pack/wildfly-feature-pack-build.xml
  testsuite/integration/basic/pom.xml
  testsuite/integration/clustering/pom.xml
  testsuite/integration/elytron/pom.xml
  testsuite/integration/microprofile-tck/config/pom.xml
  testsuite/integration/microprofile-tck/fault-tolerance/pom.xml
  testsuite/integration/microprofile-tck/health/pom.xml
  testsuite/integration/microprofile-tck/metrics/pom.xml
  testsuite/integration/microprofile-tck/opentracing/pom.xml
  testsuite/integration/microprofile/pom.xml
  testsuite/integration/smoke/pom.xml
  testsuite/integration/web/pom.xml
  testsuite/layers/pom.xml
  testsuite/test-feature-pack/wildfly-feature-pack-build.xml
Labels: deps-ok, ready-for-merge

#12879 WFLY-12838 Upgrade Infinispan to 9.4.17.Final
  clustering/infinispan/extension/src/main/java/org/jboss/as/clustering/infinispan/subsystem/remote/ManagedRemoteCacheContainer.java
  pom.xml
  testsuite/integration/clustering/src/test/java/org/jboss/as/test/clustering/cluster/xsite/CacheAccessServlet.java
  testsuite/integration/clustering/src/test/java/org/jboss/as/test/clustering/cluster/xsite/web.xml
Labels: deps-ok, ready-for-merge

#12885 [WFLY-12935] Move to jakarta EE8 Concurrency RI
  ee/pom.xml
  pom.xml
  servlet-feature-pack/pom.xml
  servlet-feature-pack/src/license/servlet-feature-pack-licenses.xml
  servlet-feature-pack/src/main/resources/modules/system/layers/base/org/glassfish/javax/enterprise/concurrent/main/module.xml
  servlet-galleon-pack/pom.xml
Labels: deps-changed, ready-for-merge

#12720 [WFLY-12685] Updated Microprofile Health to 2.1
  pom.xml
Labels: Feature, deps-ok, rebase-this

#12890 [WFLY-12942] Upgrade WildFly Core 11.0.0.Beta6
  pom.xml
Labels: deps-ok, ready-for-merge

#12852 WFLY-12313 Integrate MicroProfile OpenAPI 1.1
  docs/src/main/asciidoc/_admin-guide/Subsystem_configuration.adoc
  docs/src/main/asciidoc/_admin-guide/subsystem-configuration/MicroProfile_OpenAPI.adoc
  feature-pack/pom.xml
  feature-pack/src/license/full-feature-pack-licenses.xml
  feature-pack/src/main/resources/configuration/examples/subsystems-activemq-colocated.xml
  feature-pack/src/main/resources/configuration/examples/subsystems-genericjms.xml
  feature-pack/src/main/resources/configuration/examples/subsystems-jts.xml
  feature-pack/src/main/resources/configuration/examples/subsystems-picketlink.xml
  feature-pack/src/main/resources/configuration/examples/subsystems-rts.xml
  feature-pack/src/main/resources/configuration/examples/subsystems-xts.xml
  feature-pack/src/main/resources/configuration/standalone/subsystems-full-ha.xml
  feature-pack/src/main/resources/configuration/standalone/subsystems-full.xml
  feature-pack/src/main/resources/configuration/standalone/subsystems-ha.xml
  feature-pack/src/main/resources/configuration/standalone/subsystems.xml
  feature-pack/src/main/resources/modules/system/layers/base/com/fasterxml/jackson/dataformat/jackson-dataformat-yaml/main/module.xml
  feature-pack/src/main/resources/modules/system/layers/base/io/smallrye/openapi/main/module.xml
  feature-pack/src/main/resources/modules/system/layers/base/org/eclipse/microprofile/openapi/api/main/module.xml
  feature-pack/src/main/resources/modules/system/layers/base/org/wildfly/extension/microprofile/openapi-smallrye/main/module.xml
  galleon-pack/pom.xml
  galleon-pack/src/main/resources/feature_groups/domain-host-excludes.xml
  galleon-pack/src/main/resources/layers/standalone/microprofile-openapi/layer-spec.xml
  galleon-pack/wildfly-feature-pack-build.xml
  microprofile/openapi-smallrye/pom.xml
  microprofile/openapi-smallrye/src/main/java/org/wildfly/extension/microprofile/openapi/MicroProfileOpenAPIExtension.java
  microprofile/openapi-smallrye/src/main/java/org/wildfly/extension/microprofile/openapi/MicroProfileOpenAPIModel.java
  microprofile/openapi-smallrye/src/main/java/org/wildfly/extension/microprofile/openapi/MicroProfileOpenAPIParser.java
  microprofile/openapi-smallrye/src/main/java/org/wildfly/extension/microprofile/openapi/MicroProfileOpenAPISchema.java
  microprofile/openapi-smallrye/src/main/java/org/wildfly/extension/microprofile/openapi/MicroProfileOpenAPIServiceHandler.java
  microprofile/openapi-smallrye/src/main/java/org/wildfly/extension/microprofile/openapi/MicroProfileOpenAPISubsystemDefinition.java
  microprofile/openapi-smallrye/src/main/java/org/wildfly/extension/microprofile/openapi/deployment/OpenAPIDependencyProcessor.java
  microprofile/openapi-smallrye/src/main/java/org/wildfly/extension/microprofile/openapi/deployment/OpenAPIDocumentBuilder.java
  microprofile/openapi-smallrye/src/main/java/org/wildfly/extension/microprofile/openapi/deployment/OpenAPIDocumentProcessor.java
  microprofile/openapi-smallrye/src/main/java/org/wildfly/extension/microprofile/openapi/deployment/OpenAPIHttpHandler.java
  microprofile/openapi-smallrye/src/main/java/org/wildfly/extension/microprofile/openapi/deployment/OpenAPIHttpHandlerServiceConfigurator.java
  microprofile/openapi-smallrye/src/main/java/org/wildfly/extension/microprofile/openapi/deployment/OpenAPIModelServiceConfigurator.java
  microprofile/openapi-smallrye/src/main/java/org/wildfly/extension/microprofile/openapi/deployment/OpenAPIServiceNameProvider.java
  microprofile/openapi-smallrye/src/main/java/org/wildfly/extension/microprofile/openapi/logging/MicroProfileOpenAPILogger.java
  microprofile/openapi-smallrye/src/main/resources/org/wildfly/extension/microprofile/openapi/LocalDescriptions.properties
  microprofile/openapi-smallrye/src/main/resources/schema/wildfly-microprofile-openapi-smallrye_1_0.xsd
  microprofile/openapi-smallrye/src/main/resources/subsystem-templates/microprofile-openapi-smallrye.xml
  microprofile/openapi-smallrye/src/test/java/org/wildfly/extension/microprofile/openapi/MicroProfileOpenAPISubsystemTestCase.java
  microprofile/openapi-smallrye/src/test/resources/org/wildfly/extension/microprofile/openapi/microprofile-openapi-smallrye_1_0.xml
  microprofile/pom.xml
  pom.xml
  testsuite/integration/microprofile-tck/openapi/pom.xml
  testsuite/integration/microprofile-tck/openapi/src/test/resources/arquillian.xml
  testsuite/integration/microprofile-tck/pom.xml
  testsuite/integration/microprofile/pom.xml
  testsuite/integration/microprofile/src/test/java/org/wildfly/test/integration/microprofile/openapi/OpenAPIAbsoluteServersTestCase.java
  testsuite/integration/microprofile/src/test/java/org/wildfly/test/integration/microprofile/openapi/OpenAPIAltPathTestCase.java
  testsuite/integration/microprofile/src/test/java/org/wildfly/test/integration/microprofile/openapi/OpenAPIDisabledTestCase.java
  testsuite/integration/microprofile/src/test/java/org/wildfly/test/integration/microprofile/openapi/OpenAPIFormatTestCase.java
  testsuite/integration/microprofile/src/test/java/org/wildfly/test/integration/microprofile/openapi/OpenAPIMultiModuleDeploymentTestCase.java
  testsuite/integration/microprofile/src/test/java/org/wildfly/test/integration/microprofile/openapi/service/EchoResource.java
  testsuite/integration/microprofile/src/test/java/org/wildfly/test/integration/microprofile/openapi/service/TestApplication.java
  testsuite/integration/microprofile/src/test/java/org/wildfly/test/integration/microprofile/openapi/service/web.xml
  testsuite/layers/pom.xml
Labels: Feature, deps-changed

#12888 [WFCORE-4788] Upgrade httpclient 4.5.10
  testsuite/integration/basic/pom.xml
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/web/servlet/preservepath/PreservePathTestCase.java
Labels: deps-ok, ready-for-merge

#12893 [WFLY-12953] Delete any existing licenses.html before transforming to…
  galleon-pack/src/main/resources/packages/docs.licenses.merge/pm/wildfly/alternative-tasks.xml
  galleon-pack/src/main/resources/packages/docs.licenses.merge/pm/wildfly/tasks.xml
  servlet-galleon-pack/src/main/resources/packages/docs.licenses.merge/pm/wildfly/alternative-tasks.xml
  servlet-galleon-pack/src/main/resources/packages/docs.licenses.merge/pm/wildfly/tasks.xml
Labels: deps-ok

#12897 Fix for WFLY-12955, Upgrade galleon to 4.2.3
  dist/pom.xml
  pom.xml
Labels: deps-ok, ready-for-merge

#12895 WFLY-12943: Upgrade HAL to 3.2.5.Final
  pom.xml
Labels: deps-ok

#12901 [WFLY-12826] Clean out more unneeded f-p declarations
  testsuite/integration/basic/pom.xml
Labels: deps-ok

#12567 [WFLY-11255] Managed Executor Runtime Stats
  ee/src/main/java/org/jboss/as/ee/concurrent/ManagedExecutorRuntimeStats.java
  ee/src/main/java/org/jboss/as/ee/concurrent/ManagedExecutorRuntimeStatsImpl.java
  ee/src/main/java/org/jboss/as/ee/concurrent/ManagedExecutorServiceImpl.java
  ee/src/main/java/org/jboss/as/ee/concurrent/ManagedScheduledExecutorServiceImpl.java
  ee/src/main/java/org/jboss/as/ee/concurrent/service/ManagedExecutorServiceService.java
  ee/src/main/java/org/jboss/as/ee/concurrent/service/ManagedScheduledExecutorServiceService.java
  ee/src/main/java/org/jboss/as/ee/logging/EeLogger.java
  ee/src/main/java/org/jboss/as/ee/subsystem/EeExtension.java
  ee/src/main/java/org/jboss/as/ee/subsystem/ManagedExecutorServiceMetricsAttributes.java
  ee/src/main/java/org/jboss/as/ee/subsystem/ManagedExecutorServiceMetricsHandler.java
  ee/src/main/java/org/jboss/as/ee/subsystem/ManagedExecutorServiceResourceDefinition.java
  ee/src/main/java/org/jboss/as/ee/subsystem/ManagedScheduledExecutorServiceResourceDefinition.java
  ee/src/main/resources/org/jboss/as/ee/subsystem/LocalDescriptions.properties
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/ee/concurrent/ManagedExecutorServiceMetricsTestCase.java
Labels: 19.x, Feature, deps-ok, ready-for-merge

#12900 WFLY-12958 Calling Asynchronous EJB will use the propagated caller tr…
  ejb3/src/main/java/org/jboss/as/ejb3/tx/CMTTxInterceptor.java
  testsuite/integration/multinode/src/test/java/org/jboss/as/test/multinode/transaction/async/ClientBean.java
  testsuite/integration/multinode/src/test/java/org/jboss/as/test/multinode/transaction/async/TransactionPropagationTestCase.java
  testsuite/integration/multinode/src/test/java/org/jboss/as/test/multinode/transaction/async/TransactionalMandatory.java
  testsuite/integration/multinode/src/test/java/org/jboss/as/test/multinode/transaction/async/TransactionalRemote.java
  testsuite/integration/multinode/src/test/java/org/jboss/as/test/multinode/transaction/async/TransactionalStatusByManager.java
  testsuite/integration/multinode/src/test/java/org/jboss/as/test/multinode/transaction/async/TransactionalStatusByRegistry.java
Labels: deps-ok

#12835 [WFLY-12298] Implement RESTEasy context parameters in Wildfly
  docs/src/main/asciidoc/_admin-guide/subsystem-configuration/JAXRS.adoc
  docs/src/main/asciidoc/_admin-guide/subsystem-configuration/Simple_configuration_subsystems.adoc
  docs/src/main/asciidoc/_extending-wildfly/Domain_Mode_Subsystem_Transformers.adoc
  galleon-pack/src/main/resources/feature_groups/basic-profile.xml
  galleon-pack/src/main/resources/feature_groups/jaxrs.xml
  galleon-pack/src/main/resources/layers/standalone/jaxrs/layer-spec.xml
  jaxrs/src/main/java/org/jboss/as/jaxrs/JaxrsAttribute.java
  jaxrs/src/main/java/org/jboss/as/jaxrs/JaxrsConstants.java
  jaxrs/src/main/java/org/jboss/as/jaxrs/JaxrsElement.java
  jaxrs/src/main/java/org/jboss/as/jaxrs/JaxrsExtension.java
  jaxrs/src/main/java/org/jboss/as/jaxrs/JaxrsParamHandler.java
  jaxrs/src/main/java/org/jboss/as/jaxrs/JaxrsServerConfig.java
  jaxrs/src/main/java/org/jboss/as/jaxrs/JaxrsServerConfigService.java
  jaxrs/src/main/java/org/jboss/as/jaxrs/JaxrsSubsystemAdd.java
  jaxrs/src/main/java/org/jboss/as/jaxrs/JaxrsSubsystemDefinition.java
  jaxrs/src/main/java/org/jboss/as/jaxrs/JaxrsSubsystemParser_1_0.java
  jaxrs/src/main/java/org/jboss/as/jaxrs/JaxrsSubsystemParser_2_0.java
  jaxrs/src/main/java/org/jboss/as/jaxrs/JaxrsTransformers.java
  jaxrs/src/main/java/org/jboss/as/jaxrs/deployment/JaxrsIntegrationProcessor.java
  jaxrs/src/main/java/org/jboss/as/jaxrs/logging/JaxrsLogger.java
  jaxrs/src/main/resources/META-INF/services/org.jboss.as.controller.transform.ExtensionTransformerRegistration
  jaxrs/src/main/resources/org/jboss/as/jaxrs/LocalDescriptions.properties
  jaxrs/src/main/resources/schema/jboss-as-jaxrs_2_0.xsd
  jaxrs/src/main/resources/subsystem-templates/jaxrs.xml
  jaxrs/src/test/java/org/jboss/as/jaxrs/JaxrsSubsystem20MinimalTestCase.java
  jaxrs/src/test/java/org/jboss/as/jaxrs/JaxrsSubsystem20TestCase.java
  jaxrs/src/test/java/org/jboss/as/jaxrs/JaxrsSubsystemTestCase.java
  jaxrs/src/test/java/org/jboss/as/jaxrs/JaxrsTransformersTestCase.java
  jaxrs/src/test/resources/org/jboss/as/jaxrs/jaxrs-1.0.xml
  jaxrs/src/test/resources/org/jboss/as/jaxrs/jaxrs-2.0.xml
  jaxrs/src/test/resources/org/jboss/as/jaxrs/jaxrs-2.0_minimal.xml
  testsuite/integration/basic/pom.xml
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/jaxrs/cfg/EJB_Resource1.java
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/jaxrs/cfg/EJB_Resource2.java
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/jaxrs/cfg/ResteasyAttributeResource.java
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/jaxrs/cfg/ResteasyAttributeTestCase.java
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/management/api/SimpleSubsystemsTestCase.java
Labels: Feature, deps-ok

#12853 [WFLY-12609] / [WFLY-12641] Add MicroProfile JWT Support
  docs/src/main/asciidoc/_admin-guide/Subsystem_configuration.adoc
  docs/src/main/asciidoc/_admin-guide/subsystem-configuration/MicroProfile_JWT.adoc
  feature-pack/pom.xml
  feature-pack/src/license/full-feature-pack-licenses.xml
  feature-pack/src/main/resources/configuration/domain/subsystems.xml
  feature-pack/src/main/resources/configuration/examples/subsystems-activemq-colocated.xml
  feature-pack/src/main/resources/configuration/examples/subsystems-genericjms.xml
  feature-pack/src/main/resources/configuration/examples/subsystems-jts.xml
  feature-pack/src/main/resources/configuration/examples/subsystems-picketlink.xml
  feature-pack/src/main/resources/configuration/examples/subsystems-rts.xml
  feature-pack/src/main/resources/configuration/examples/subsystems-xts.xml
  feature-pack/src/main/resources/configuration/standalone/subsystems-full-ha.xml
  feature-pack/src/main/resources/configuration/standalone/subsystems-ha.xml
  feature-pack/src/main/resources/configuration/standalone/subsystems.xml
  feature-pack/src/main/resources/modules/system/layers/base/io/smallrye/jwt/main/module.xml
  feature-pack/src/main/resources/modules/system/layers/base/org/bitbucket/jose4j/main/module.xml
  feature-pack/src/main/resources/modules/system/layers/base/org/eclipse/microprofile/jwt/auth/api/main/module.xml
  feature-pack/src/main/resources/modules/system/layers/base/org/wildfly/extension/microprofile/jwt-smallrye/main/module.xml
  feature-pack/src/main/resources/modules/system/layers/base/org/wildfly/security/elytron-jwt/main/module.xml
  galleon-pack/pom.xml
  galleon-pack/src/main/resources/feature_groups/basic-profile.xml
  galleon-pack/src/main/resources/feature_groups/domain-host-excludes.xml
  galleon-pack/src/main/resources/layers/standalone/microprofile-jwt/layer-spec.xml
  galleon-pack/wildfly-feature-pack-build.xml
  microprofile/jwt-smallrye/pom.xml
  microprofile/jwt-smallrye/src/main/java/org/wildfly/extension/microprofile/jwt/smallrye/Capabilities.java
  microprofile/jwt-smallrye/src/main/java/org/wildfly/extension/microprofile/jwt/smallrye/JwtActivationProcessor.java
  microprofile/jwt-smallrye/src/main/java/org/wildfly/extension/microprofile/jwt/smallrye/JwtDependencyProcessor.java
  microprofile/jwt-smallrye/src/main/java/org/wildfly/extension/microprofile/jwt/smallrye/JwtDeploymentMarker.java
  microprofile/jwt-smallrye/src/main/java/org/wildfly/extension/microprofile/jwt/smallrye/MicroProfileJWTExtension.java
  microprofile/jwt-smallrye/src/main/java/org/wildfly/extension/microprofile/jwt/smallrye/MicroProfileJWTSubsystemAdd.java
  microprofile/jwt-smallrye/src/main/java/org/wildfly/extension/microprofile/jwt/smallrye/MicroProfileJWTSubsystemParser_1_0.java
  microprofile/jwt-smallrye/src/main/java/org/wildfly/extension/microprofile/jwt/smallrye/MicroProfileSubsystemDefinition.java
  microprofile/jwt-smallrye/src/main/java/org/wildfly/extension/microprofile/jwt/smallrye/_private/MicroProfileJWTLogger.java
  microprofile/jwt-smallrye/src/main/resources/META-INF/services/org.jboss.as.controller.Extension
  microprofile/jwt-smallrye/src/main/resources/org/wildfly/extension/microprofile/jwt/smallrye/LocalDescriptions.properties
  microprofile/jwt-smallrye/src/main/resources/schema/wildfly-microprofile-jwt-smallrye_1_0.xsd
  microprofile/jwt-smallrye/src/main/resources/subsystem-templates/microprofile-jwt-smallrye.xml
  microprofile/jwt-smallrye/src/test/java/org/wildfly/extension/microprofile/jwt/smallrye/Subsystem_1_0_ParsingTestCase.java
  microprofile/jwt-smallrye/src/test/resources/org/wildfly/extension/microprofile/jwt/smallrye/subsystem_1_0.xml
  microprofile/pom.xml
  pom.xml
  testsuite/integration/microprofile-tck/jwt/pom.xml
  testsuite/integration/microprofile-tck/jwt/src/test/java/org/wildfly/extension/microprofile/jwt/test/DeploymentProcessor.java
  testsuite/integration/microprofile-tck/jwt/src/test/java/org/wildfly/extension/microprofile/jwt/test/WildFlyArquillianExtension.java
  testsuite/integration/microprofile-tck/jwt/src/test/resources/META-INF/microprofile-config-local.properties
  testsuite/integration/microprofile-tck/jwt/src/test/resources/META-INF/services/org.jboss.arquillian.core.spi.LoadableExtension
  testsuite/integration/microprofile-tck/jwt/src/test/resources/WEB-INF/jboss-web.xml
  testsuite/integration/microprofile-tck/jwt/src/test/resources/WEB-INF/web.xml
  testsuite/integration/microprofile-tck/jwt/src/test/resources/arquillian.xml
  testsuite/integration/microprofile-tck/jwt/tck-base-suite.xml
  testsuite/integration/microprofile-tck/pom.xml
  testsuite/layers/pom.xml
  testsuite/mixed-domain/src/test/java/org/jboss/as/test/integration/domain/mixed/DomainAdjuster.java
  testsuite/mixed-domain/src/test/java/org/jboss/as/test/integration/domain/mixed/Version.java
  testsuite/mixed-domain/src/test/java/org/jboss/as/test/integration/domain/mixed/eap720/DomainAdjuster720.java
  testsuite/mixed-domain/src/test/java/org/jboss/as/test/integration/domain/mixed/eap730/DomainAdjuster730.java
  undertow/src/main/java/org/wildfly/extension/undertow/deployment/UndertowDeploymentInfoService.java
  undertow/src/main/java/org/wildfly/extension/undertow/deployment/UndertowDeploymentProcessor.java
Labels: Feature, deps-changed

#12909 [WFLY-12962] Upgrade WildFly Core 11.0.0.Beta7
  pom.xml
  testsuite/integration/basic/pom.xml
Labels: deps-ok, ready-for-merge

#12910 [WFLY-12963] Use maven project.groupId for wildfly-microprofile-jwt-s…
  microprofile/jwt-smallrye/pom.xml
Labels: deps-ok

#12361 [WFLY-12187] Add documentation and test updates for TLS 1.3 support
  docs/src/main/asciidoc/_client-guide/authentication-client.adoc
  docs/src/main/asciidoc/_elytron/Using_the_Elytron_Subsystem.adoc
  testsuite/integration/elytron/src/test/java/org/wildfly/test/integration/elytron/ssl/UndertowSslSecurityDomainTestCase.java
Labels: Feature-Docs, deps-changed

#12904 WFLY-12959 Upgrade microprofile-fault-tolerance-api to 2.0.3
  pom.xml
Labels: deps-ok, ready-for-merge

#12902 [WFLY-12903] - EJBComponent.checkCallerSecurityIdentityRole check for…
  ejb3/src/main/java/org/jboss/as/ejb3/component/EJBComponent.java
Labels: deps-ok

#12911 [WFLY-12885] Upgrade Mojarra to 2.3.9.SP06
  pom.xml
Labels: deps-ok, ready-for-merge

#12916 WFLY-12909 Fix license names for org.hdrhistogram:HdrHistogram licenses
  feature-pack/src/license/full-feature-pack-licenses.xml
Labels: deps-ok, ready-for-merge

#12913 WFLY-12966 WFLY-12964 Upgrade Hibernate ORM to 5.3.15.Final; fix CfgF…
  pom.xml
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/jpa/cfgfile/CfgFileTestCase.java
Labels: deps-ok

#12856 [WFLY-12892] Upgrade JAXB from 2.3.1 to 2.3.3-b02
  pom.xml
Labels: deps-ok

#12886 WFLY-12937, WFLY-12938, WFLY-12939 Fix memory leaks due to orphaned expired cache entries following topology change
  clustering/ee/cache/src/main/java/org/wildfly/clustering/ee/cache/scheduler/LocalScheduler.java
  clustering/ejb/infinispan/src/main/java/org/wildfly/clustering/ejb/infinispan/InfinispanBeanManager.java
  clustering/infinispan/spi/src/main/java/org/wildfly/clustering/infinispan/spi/distribution/ConsistentHashLocality.java
  clustering/web/infinispan/src/main/java/org/wildfly/clustering/web/infinispan/session/InfinispanSessionManagerFactory.java
Labels: deps-ok, ready-for-merge

#12914 [WFLY-12712] Upgrade RESTEasy to 3.10.0.Final
  pom.xml
Labels: deps-ok

#12908 WFLY-12961 Fix intermittent deadlock between LocalScheduler.close() and run()
  clustering/ee/cache/src/main/java/org/wildfly/clustering/ee/cache/scheduler/LocalScheduler.java
  clustering/ee/cache/src/test/java/org/wildfly/clustering/ee/cache/scheduler/LocalSchedulerTestCase.java
  clustering/ejb/infinispan/src/main/java/org/wildfly/clustering/ejb/infinispan/BeanExpirationScheduler.java
  clustering/ejb/infinispan/src/main/java/org/wildfly/clustering/ejb/infinispan/EagerEvictionScheduler.java
  clustering/ejb/infinispan/src/main/java/org/wildfly/clustering/ejb/infinispan/InfinispanBeanManager.java
  clustering/ejb/infinispan/src/test/java/org/wildfly/clustering/ejb/infinispan/BeanExpirationSchedulerTestCase.java
  clustering/web/hotrod/src/main/java/org/wildfly/clustering/web/hotrod/session/HotRodSessionManagerFactory.java
  clustering/web/hotrod/src/main/java/org/wildfly/clustering/web/hotrod/session/SessionExpirationScheduler.java
  clustering/web/infinispan/src/main/java/org/wildfly/clustering/web/infinispan/session/InfinispanSessionManagerFactory.java
  clustering/web/infinispan/src/main/java/org/wildfly/clustering/web/infinispan/session/SessionExpirationScheduler.java
  clustering/web/infinispan/src/test/java/org/wildfly/clustering/web/infinispan/session/SessionExpirationSchedulerTestCase.java
  ejb3/src/main/java/org/jboss/as/ejb3/cache/simple/SimpleCache.java
Labels: deps-ok, ready-for-merge

#12880 [WFLY-12928] Clean up some http maven repo URL cruft
  docs/src/main/asciidoc/_extras/Developing_JSF_Project_Using,_Maven_and_IntelliJ.adoc
  testsuite/pom.xml
Labels: deps-ok, ready-for-merge

#12896 WFLY-12954 Skip passivation of entries on stop if passivation store uses purgeOnStartup.
  clustering/infinispan/spi/src/main/java/org/wildfly/clustering/infinispan/spi/service/CacheServiceConfigurator.java
Labels: deps-ok

#12768 [WFLY-11930] Allow Java EE Subsystem to enable/disable descriptor bas…
  docs/src/main/asciidoc/_admin-guide/subsystem-configuration/EE_Application_Deployment_Configuration.adoc
  ee/src/main/java/org/jboss/as/ee/metadata/property/PropertyResolverProcessor.java
  testsuite/integration/secman/pom.xml
  testsuite/integration/secman/src/test/java/org/jboss/as/testsuite/integration/secman/propertypermission/PermissionParserExpressionsTestCase.java
  testsuite/integration/secman/src/test/java/org/jboss/as/testsuite/integration/secman/propertypermission/PropertyPermissionExpressionsTestCase.java
  testsuite/integration/secman/src/test/resources/propertypermission/permissions.xml
Labels: Feature, deps-ok

#12919 WFLY-12974 Default cache configurations for local/passivating caches are overly restrictive
  clustering/infinispan/extension/src/main/resources/subsystem-templates/infinispan.xml
  galleon-pack/src/main/resources/feature_groups/infinispan-local-ejb.xml
  galleon-pack/src/main/resources/feature_groups/infinispan-local-server.xml
  galleon-pack/src/main/resources/feature_groups/infinispan-local-web.xml
Labels: deps-ok

#12922 Add missing provided scope tags
  galleon-pack/pom.xml
Labels: deps-ok

#12915 WFLY-12957 MP Fault tolerance tests are failing on Ubuntu
  testsuite/integration/microprofile-tck/fault-tolerance/pom.xml
  testsuite/integration/microprofile-tck/fault-tolerance/src/test/resources/arquillian.xml
  testsuite/integration/microprofile/pom.xml
Labels: deps-ok

#12489 [WFLY-1160] Provide ability to easily apply certain JBoss module libraries to all deployments running in a server
  docs/src/main/asciidoc/_admin-guide/subsystem-configuration/EE.adoc
  docs/src/main/asciidoc/_admin-guide/subsystem-configuration/EE_Application_Deployment_Configuration.adoc
  docs/src/main/asciidoc/_developer-guide/Class_Loading_in_WildFly.adoc
  ee/src/main/java/org/jboss/as/ee/logging/EeLogger.java
  ee/src/main/java/org/jboss/as/ee/structure/GlobalDirectoryDependencyProcessor.java
  ee/src/main/java/org/jboss/as/ee/subsystem/Attribute.java
  ee/src/main/java/org/jboss/as/ee/subsystem/EESubsystemModel.java
  ee/src/main/java/org/jboss/as/ee/subsystem/EESubsystemParser40.java
  ee/src/main/java/org/jboss/as/ee/subsystem/EESubsystemParser50.java
  ee/src/main/java/org/jboss/as/ee/subsystem/EESubsystemXmlPersister.java
  ee/src/main/java/org/jboss/as/ee/subsystem/EETransformers.java
  ee/src/main/java/org/jboss/as/ee/subsystem/EeCapabilities.java
  ee/src/main/java/org/jboss/as/ee/subsystem/EeExtension.java
  ee/src/main/java/org/jboss/as/ee/subsystem/EeSubsystemAdd.java
  ee/src/main/java/org/jboss/as/ee/subsystem/EeSubsystemRootResource.java
  ee/src/main/java/org/jboss/as/ee/subsystem/Element.java
  ee/src/main/java/org/jboss/as/ee/subsystem/GlobalDirectoryDeploymentService.java
  ee/src/main/java/org/jboss/as/ee/subsystem/GlobalDirectoryResourceDefinition.java
  ee/src/main/java/org/jboss/as/ee/subsystem/GlobalDirectoryService.java
  ee/src/main/resources/org/jboss/as/ee/subsystem/LocalDescriptions.properties
  ee/src/main/resources/schema/jboss-as-ee_5_0.xsd
  ee/src/test/java/org/jboss/as/ee/subsystem/EeSubsystemTestCase.java
  ee/src/test/resources/org/jboss/as/ee/subsystem/subsystem.xml
  testsuite/domain/pom.xml
  testsuite/domain/src/test/java/org/jboss/as/test/integration/domain/suites/DomainTestSuite.java
  testsuite/domain/src/test/java/org/jboss/as/test/integration/domain/suites/GlobalDirectoryDeployment.java
  testsuite/domain/src/test/java/org/jboss/as/test/integration/domain/suites/GlobalDirectoryDomainTestCase.java
  testsuite/domain/src/test/java/org/jboss/as/test/integration/domain/suites/GlobalDirectoryLibrary.java
  testsuite/domain/src/test/java/org/jboss/as/test/integration/domain/suites/GlobalDirectoryLibraryImpl.java
  testsuite/integration/manualmode/src/test/java/org/jboss/as/test/manualmode/ee/globaldirectory/EchoServlet.java
  testsuite/integration/manualmode/src/test/java/org/jboss/as/test/manualmode/ee/globaldirectory/EchoUtility.java
  testsuite/integration/manualmode/src/test/java/org/jboss/as/test/manualmode/ee/globaldirectory/GlobalDirectoryBase.java
  testsuite/integration/manualmode/src/test/java/org/jboss/as/test/manualmode/ee/globaldirectory/GlobalDirectoryBasicTestCase.java
  testsuite/integration/manualmode/src/test/java/org/jboss/as/test/manualmode/ee/globaldirectory/GlobalDirectoryTestCase.java
  testsuite/integration/manualmode/src/test/java/org/jboss/as/test/manualmode/ee/globaldirectory/deployments/GlobalDirectoryDeployment.java
  testsuite/integration/manualmode/src/test/java/org/jboss/as/test/manualmode/ee/globaldirectory/deployments/GlobalDirectoryDeployment2.java
  testsuite/integration/manualmode/src/test/java/org/jboss/as/test/manualmode/ee/globaldirectory/deployments/GlobalDirectoryDeployment3.java
  testsuite/integration/manualmode/src/test/java/org/jboss/as/test/manualmode/ee/globaldirectory/libraries/GlobalDirectoryLibrary.java
  testsuite/integration/manualmode/src/test/java/org/jboss/as/test/manualmode/ee/globaldirectory/libraries/GlobalDirectoryLibraryImpl.java
  testsuite/integration/manualmode/src/test/java/org/jboss/as/test/manualmode/ee/globaldirectory/libraries/GlobalDirectoryLibraryImpl2.java
  testsuite/integration/manualmode/src/test/java/org/jboss/as/test/manualmode/ee/globaldirectory/libraries/GlobalDirectoryLibraryImpl3.java
  testsuite/integration/manualmode/src/test/java/org/jboss/as/test/manualmode/weld/extension/BeforeShutdownJNDILookupTestCase.java
  testsuite/integration/manualmode/src/test/resources/org/jboss/as/test/manualmode/ee/globaldirectory/global-directory.properties
  testsuite/integration/manualmode/src/test/resources/org/jboss/as/test/manualmode/ee/globaldirectory/sub/sub-global-directory.properties
Labels: 19.x, Feature, deps-ok

#12924 [WFLY-12940] / [WFLY-12983] JBossWS and SAAJ Component Upgrades
  feature-pack/pom.xml
  feature-pack/src/main/resources/modules/system/layers/base/org/jboss/as/webservices/main/module.xml
  galleon-pack/pom.xml
  pom.xml
Labels: deps-changed

#12917 [WFLY-12940]:Upgrade JBossWS to 5.4.0.Final
  feature-pack/pom.xml
  feature-pack/src/main/resources/modules/system/layers/base/org/jboss/as/webservices/main/module.xml
  galleon-pack/pom.xml
  pom.xml
Labels: deps-changed

#12926 [WFLY-12984] Temporary workaround to resolve OpenTracing TCK issues w…
  testsuite/integration/microprofile-tck/opentracing/pom.xml
Labels: deps-ok

#12928 [WFLY-12940]:Upgrade jbossws-cxf to 5.4.1.Final
  pom.xml
Labels: deps-ok

#12932 [WFLY-12993] Update SmallRye JWT to 2.0.12
  pom.xml
Labels: deps-ok

#12931 [WFLY-12991] SunX509 TrustManagerFactory not available from Elytron tests on IBM jdk
  testsuite/shared/src/main/java/org/wildfly/test/security/common/elytron/SimpleTrustManager.java
Labels: deps-ok

#12929 WFLY-12988 Upgrade smallrye-fault-tolerance to 2.1.5
  pom.xml
Labels: deps-ok

#12925 [WFLY-12968] SecurityDomainContextRealm is not caching passwords correctly
  security/subsystem/src/main/java/org/jboss/as/security/elytron/SecurityDomainContextRealm.java
  testsuite/integration/basic/src/test/java/org/wildfly/test/elytron/intermediate/LoginCounterLoginModule.java
  testsuite/integration/basic/src/test/java/org/wildfly/test/elytron/intermediate/PrincipalCounterServlet.java
  testsuite/integration/basic/src/test/java/org/wildfly/test/elytron/intermediate/SecurityDomainContextRealmTestCase.java
  testsuite/integration/basic/src/test/java/org/wildfly/test/elytron/intermediate/roles.properties
  testsuite/integration/basic/src/test/java/org/wildfly/test/elytron/intermediate/security-domain-context-realm-web.xml
  testsuite/integration/basic/src/test/java/org/wildfly/test/elytron/intermediate/users.properties
Labels: deps-ok, ready-for-merge

#12891 [WFLY-12949] Upgrade WildFly Http Client to 1.0.20.Final
  pom.xml
Labels: deps-ok, ready-for-merge

#12935 [WFLY-934] Placing test log to target directory
  testsuite/compat/pom.xml
Labels: deps-ok, ready-for-merge

#12937 WFLY-12967 Improve tests in integration/multinode/transaction/async/T…
  testsuite/integration/multinode/src/test/java/org/jboss/as/test/multinode/transaction/async/ClientBean.java
  testsuite/integration/multinode/src/test/java/org/jboss/as/test/multinode/transaction/async/TransactionPropagationTestCase.java
  testsuite/integration/multinode/src/test/java/org/jboss/as/test/multinode/transaction/async/TransactionalMandatory.java
  testsuite/integration/multinode/src/test/java/org/jboss/as/test/multinode/transaction/async/TransactionalRemote.java
  testsuite/integration/multinode/src/test/java/org/jboss/as/test/multinode/transaction/async/TransactionalStatusByManager.java
  testsuite/integration/multinode/src/test/java/org/jboss/as/test/multinode/transaction/async/TransactionalStatusByRegistry.java
Labels: deps-ok, ready-for-merge

#12938 WFLY-13004 Upgrade jgroups-kubernetes to 1.0.14.Final
  pom.xml
Labels: deps-ok

#12944 Fix method shadowing issues in preparation for WFCORE-4819.
  security/subsystem/src/main/java/org/jboss/as/security/MappingModuleDefinition.java
  undertow/src/main/java/org/wildfly/extension/undertow/handlers/ReverseProxyHandlerHost.java
Labels: deps-ok

#12941 [WFLY-13009] Send moduleAvailability message only after module started
  ejb3/src/main/java/org/jboss/as/ejb3/remote/AssociationImpl.java
Labels: deps-ok

#12946 [WFLY-13028] Add the 'microprofile-jwt' layer to the documentation.
  docs/src/main/asciidoc/_admin-guide/Galleon_provisioning.adoc
Labels: deps-ok

#12947 [WFLY-13036] Update the URL from 'issues.jboss.org' to 'issues.redhat.com'.
  docs/src/main/asciidoc/_admin-guide/Security_Realms.adoc
  docs/src/main/asciidoc/_admin-guide/Security_Realms_Detailed_Configuration.adoc
  docs/src/main/asciidoc/_developer-guide/Embedded_API.adoc
  docs/src/main/asciidoc/_developer-guide/Scoped_EJB_client_contexts.adoc
  docs/src/main/asciidoc/_developer-guide/ejb3/Container_interceptors.adoc
  docs/src/main/asciidoc/_developer-guide/ejb3/EJB_on_Kubernetes.adoc
  docs/src/main/asciidoc/_javaee-guide/Java_API_for_RESTful_Web_Services_(JAX-RS).adoc
  docs/src/main/asciidoc/_testsuite/WildFly_Integration_Testsuite_User_Guide.adoc
  docs/src/main/asciidoc/_testsuite/WildFly_Testsuite_Harness_Developer_Guide.adoc
  docs/src/main/asciidoc/_testsuite/WildFly_Testsuite_Test_Developer_Guide.adoc
  docs/src/main/asciidoc/index.adoc
Labels: deps-ok
