Repository wildfly/wildfly, pull requests merged in 2020-09, with the labels that each got.

#13514 [WFLY-13811] EJB3's dep on org.jboss.as.remoting is not optional unti…
  ee-feature-pack/common/src/main/resources/modules/system/layers/base/org/jboss/as/ejb3/main/module.xml
Labels: deps-ok

#13515 [WFLY-13812] Update RemoteNamingAdd to use the endpoint capability to…
  naming/src/main/java/org/jboss/as/naming/subsystem/RemoteNamingAdd.java
  naming/src/main/java/org/jboss/as/naming/subsystem/RemoteNamingResourceDefinition.java
  servlet-feature-pack/common/src/main/resources/modules/system/layers/base/org/jboss/as/naming/main/module.xml
Labels: deps-ok

#13519 Fix for WFLY-13815, Make core-tools optional in datasources-web-server layer
  ee-feature-pack/galleon-common/src/main/resources/layers/standalone/datasources-web-server/layer-spec.xml
Labels: deps-ok

#13476 [WFLY-13749] Add the bean-validation Galleon layer as an optional dep…
  ee-feature-pack/galleon-common/src/main/resources/layers/standalone/jpa-distributed/layer-spec.xml
  ee-feature-pack/galleon-common/src/main/resources/layers/standalone/jpa/layer-spec.xml
Labels: deps-ok

#13531 [WFLY-13740] Upgrade Narayana to 5.10.6.Final
  pom.xml
Labels: deps-ok, ready-for-merge

#13522 [WFLY-13559]: Header response has changed and missing fields.
  microprofile/opentracing-extension/src/main/java/org/wildfly/extension/microprofile/opentracing/TracingDeploymentProcessor.java
  testsuite/integration/basic/src/test/java/org/wildfly/test/integration/microprofile/opentracing/jaxrs/ResteasyProvidersTestCase.java
  testsuite/integration/basic/src/test/java/org/wildfly/test/integration/microprofile/opentracing/jaxrs/application/Services.java
  testsuite/integration/basic/src/test/java/org/wildfly/test/integration/microprofile/opentracing/jaxrs/application/filters/ResponseContextProviderFilter.java
  testsuite/integration/basic/src/test/java/org/wildfly/test/integration/microprofile/opentracing/jaxrs/application/model/TestResponse.java
  testsuite/integration/basic/src/test/java/org/wildfly/test/integration/microprofile/opentracing/jaxrs/application/services/EndpointService.java
Labels: deps-ok

#13517 [WFLY-13814]: Drop messaging subsystem's HTTPUpgradeService's use of SimpleHttpUpgradeHandshake, drop dep on org.jboss.as.remoting.
  ee-feature-pack/common/src/main/resources/modules/system/layers/base/org/wildfly/extension/messaging-activemq/main/module.xml
  messaging-activemq/src/main/java/org/wildfly/extension/messaging/activemq/HTTPAcceptorDefinition.java
  messaging-activemq/src/main/java/org/wildfly/extension/messaging/activemq/HTTPUpgradeService.java
  messaging-activemq/src/main/java/org/wildfly/extension/messaging/activemq/logging/MessagingLogger.java
Labels: deps-ok

#13524 WFLY-13354 Add Galleon layers for the EJB subsystem
  docs/src/main/asciidoc/_admin-guide/Galleon_provisioning.adoc
  ee-feature-pack/galleon-common/src/main/resources/layers/standalone/ejb-dist-cache/layer-spec.xml
  ee-feature-pack/galleon-common/src/main/resources/layers/standalone/ejb-lite/layer-spec.xml
  ee-feature-pack/galleon-common/src/main/resources/layers/standalone/ejb-local-cache/layer-spec.xml
  ee-feature-pack/galleon-common/src/main/resources/layers/standalone/ejb/layer-spec.xml
  testsuite/integration/basic/pom.xml
  testsuite/integration/clustering/pom.xml
  testsuite/layers/pom.xml
  testsuite/test-feature-pack/src/main/resources/layers/standalone/ejb-elytron-testsuite/layer-spec.xml
Labels: Feature, deps-ok, missing-reqs

#13330 [WFLY-13350] Add a Galleon layer for JSF support
  docs/src/main/asciidoc/_admin-guide/Galleon_provisioning.adoc
  ee-feature-pack/galleon-common/src/main/resources/layers/standalone/jsf/layer-spec.xml
  testsuite/integration/basic/pom.xml
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/jsf/phaselistener/injectiontarget/bean/InjectionBeanToPhaseListenerTest.java
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/jsf/phaselistener/injectiontarget/bean/SimpleBean.java
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/jsf/phaselistener/injectiontarget/bean/TestPhaseListener.java
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/jsf/phaselistener/injectiontarget/bean/faces-config.xml
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/jsf/phaselistener/injectiontarget/bean/home.xhtml
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/jsf/phaselistener/injectiontarget/bean/web.xml
  testsuite/integration/clustering/pom.xml
  testsuite/layers/pom.xml
Labels: 21.x, Feature, deps-ok, hold, missing-reqs

#13520 [WFLY-13490] Add Galleon layer for web console
  docs/src/main/asciidoc/_admin-guide/Galleon_provisioning.adoc
  ee-feature-pack/galleon-common/src/main/resources/layers/standalone/web-console/layer-spec.xml
  testsuite/integration/basic/pom.xml
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/management/console/HttpManagementConstantHeadersTestCase.java
  testsuite/layers/pom.xml
Labels: Feature, deps-ok, ready-for-merge

#13528 [WFLY-13539] Add Galleon layer for JBoss Diagnostic Reporting support
  docs/src/main/asciidoc/_admin-guide/Galleon_provisioning.adoc
  ee-feature-pack/galleon-common/src/main/resources/layers/standalone/jdr/layer-spec.xml
  testsuite/integration/basic/pom.xml
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/jdr/mgmt/JdrReportManagmentTestCase.java
  testsuite/layers/pom.xml
Labels: Feature, deps-ok, ready-for-merge

#13518 WFLY-13803 Upgrade RESTEasy to 3.13.0.Final
  pom.xml
Labels: deps-ok

#12948 WFLY-12681 Provide a 'microprofile-platform' Galleon layer
  docs/src/main/asciidoc/_admin-guide/Galleon_provisioning.adoc
  galleon-pack/src/main/resources/configs/standalone/standalone-microprofile.xml/config.xml
  galleon-pack/src/main/resources/layers/standalone/microprofile-platform/layer-spec.xml
  testsuite/integration/basic/pom.xml
  testsuite/integration/basic/src/test/java/org/wildfly/test/integration/microprofile/opentracing/MultiTracerTestCase.java
  testsuite/integration/microprofile/pom.xml
  testsuite/layers/pom.xml
Labels: Feature, deps-ok

#13545 WFLY-13835 Extraneous character in remote-store's remote-servers desc…
  clustering/infinispan/extension/src/main/resources/schema/jboss-as-infinispan_10_0.xsd
  clustering/infinispan/extension/src/main/resources/schema/jboss-as-infinispan_11_0.xsd
  clustering/infinispan/extension/src/main/resources/schema/jboss-as-infinispan_4_0.xsd
  clustering/infinispan/extension/src/main/resources/schema/jboss-as-infinispan_5_0.xsd
  clustering/infinispan/extension/src/main/resources/schema/jboss-as-infinispan_6_0.xsd
  clustering/infinispan/extension/src/main/resources/schema/jboss-as-infinispan_7_0.xsd
  clustering/infinispan/extension/src/main/resources/schema/jboss-as-infinispan_8_0.xsd
  clustering/infinispan/extension/src/main/resources/schema/jboss-as-infinispan_9_0.xsd
Labels: deps-ok, ready-for-merge

#13521 WFLY-13819 Drop jipijapa-hibernate5x-legacy modules
  ee-feature-pack/common/pom.xml
  ee-feature-pack/common/src/main/resources/modules/system/layers/base/org/hibernate/jipijapa-hibernate5-3/main/module.xml
  ee-feature-pack/pruned/pom.xml
  ee-feature-pack/pruned/src/main/resources/modules/system/layers/base/org/hibernate/jipijapa-hibernate5/main/module.xml
  jpa/hibernate5-3-legacy/pom.xml
  jpa/hibernate5-3-legacy/src/main/java/org/jboss/as/jpa/hibernate5/infinispan/DeprecatedInfinispanRegionFactory.java
  jpa/hibernate5-3-legacy/src/main/java/org/jboss/as/jpa/hibernate5/infinispan/InfinispanRegionFactory.java
  jpa/hibernate5-3-legacy/src/main/java/org/jboss/as/jpa/hibernate5/infinispan/Logger.java
  jpa/hibernate5-3-legacy/src/main/java/org/jboss/as/jpa/hibernate5/infinispan/SharedInfinispanRegionFactory.java
  jpa/hibernate5-legacy/pom.xml
  jpa/hibernate5-legacy/src/main/java/org/jboss/as/jpa/hibernate5/infinispan/DeprecatedInfinispanRegionFactory.java
  jpa/hibernate5-legacy/src/main/java/org/jboss/as/jpa/hibernate5/infinispan/InfinispanRegionFactory.java
  jpa/hibernate5-legacy/src/main/java/org/jboss/as/jpa/hibernate5/infinispan/Logger.java
  jpa/hibernate5-legacy/src/main/java/org/jboss/as/jpa/hibernate5/infinispan/SharedInfinispanRegionFactory.java
  jpa/pom.xml
  pom.xml
Labels: deps-ok, ready-for-merge

#13558 WFLY-13849 Decouple version.org.infinispan.server from version.org.in…
  pom.xml
  testsuite/integration/clustering/pom.xml
Labels: deps-ok, ready-for-merge

#13554 [WFLY-13841] Fix regular expression used to get ZipEntries on JdrRepo…
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/jdr/mgmt/JdrReportManagmentTestCase.java
Labels: deps-ok

#13553 [WFLY-13838] plain text j_password appears in the legacy audit log
  undertow/src/main/java/org/wildfly/extension/undertow/security/AuditNotificationReceiver.java
Labels: deps-ok

#13566 [WFLY-13865] Enable switching Galleon pack Maven coordinates for the …
  testsuite/integration/clustering/pom.xml
Labels: deps-ok

#13563 [WFLY-13860] Upgrade RESTEasy to 3.13.1.Final
  pom.xml
Labels: deps-ok

#13534 [WFLY-13826] Ensure the 'session-bean' start element is written befor…
  ejb3/src/main/java/org/jboss/as/ejb3/subsystem/EJB3SubsystemXMLPersister.java
Labels: deps-ok, ready-for-merge

#13557 [WFLY-13846] Eliminate the connector dependency on the legacy security subsystem's module.
  connector/pom.xml
  connector/src/main/java/org/jboss/as/connector/deployers/ds/processors/DsXmlDeploymentInstallProcessor.java
  connector/src/main/java/org/jboss/as/connector/deployers/ra/processors/ParsedRaDeploymentProcessor.java
  connector/src/main/java/org/jboss/as/connector/services/resourceadapters/DirectConnectionFactoryActivatorService.java
  connector/src/main/java/org/jboss/as/connector/subsystems/datasources/AbstractDataSourceAdd.java
  connector/src/main/java/org/jboss/as/connector/subsystems/resourceadapters/ConnectionDefinitionAdd.java
  connector/src/main/java/org/jboss/as/connector/subsystems/resourceadapters/RaOperationUtil.java
  ee-feature-pack/common/src/main/resources/modules/system/layers/base/org/jboss/as/connector/main/module.xml
  ejb3/pom.xml
  messaging-activemq/pom.xml
Labels: deps-ok

#13570 [WFLY-13870] Upgrade WildFly Core 13.0.0.Beta6
  pom.xml
Labels: deps-ok, ready-for-merge

#13499 [WFLY-13791] Disable the manual IIOP/CORBA stub generation on IBM JDK…
  testsuite/integration/basic/pom.xml
Labels: deps-ok, ready-for-merge

#13551 [WFLY-13839] Undertow https-listerner does not generate required capability
  undertow/src/main/java/org/wildfly/extension/undertow/HttpListenerResourceDefinition.java
  undertow/src/main/java/org/wildfly/extension/undertow/HttpsListenerResourceDefinition.java
  undertow/src/main/java/org/wildfly/extension/undertow/ListenerResourceDefinition.java
Labels: deps-ok, ready-for-merge

#13559 [WFLY-13850] Fix maven coordinate variables for the provisioning of m…
  testsuite/integration/basic/pom.xml
  testsuite/layers/pom.xml
Labels: deps-ok

#13560 WFLY-13854 WildFly cannot connect to an infinispan-server cluster req…
  clustering/infinispan/extension/src/main/java/org/jboss/as/clustering/infinispan/subsystem/InfinispanSubsystemXMLReader.java
  clustering/infinispan/extension/src/main/java/org/jboss/as/clustering/infinispan/subsystem/InfinispanSubsystemXMLWriter.java
  clustering/infinispan/extension/src/main/java/org/jboss/as/clustering/infinispan/subsystem/StoreResourceDefinition.java
  clustering/infinispan/extension/src/main/java/org/jboss/as/clustering/infinispan/subsystem/remote/RemoteCacheContainerConfigurationServiceConfigurator.java
  clustering/infinispan/extension/src/main/java/org/jboss/as/clustering/infinispan/subsystem/remote/RemoteCacheContainerResourceDefinition.java
  clustering/infinispan/extension/src/main/resources/org/jboss/as/clustering/infinispan/subsystem/LocalDescriptions.properties
  clustering/infinispan/extension/src/main/resources/schema/jboss-as-infinispan_11_0.xsd
  clustering/infinispan/extension/src/test/java/org/jboss/as/clustering/infinispan/subsystem/InfinispanTransformersTestCase.java
  clustering/infinispan/extension/src/test/resources/org/jboss/as/clustering/infinispan/subsystem/subsystem-infinispan-11_0.xml
  clustering/infinispan/extension/src/test/resources/org/jboss/as/clustering/infinispan/subsystem/subsystem-infinispan-transformer-reject.xml
  clustering/web/spi/src/main/java/org/wildfly/clustering/web/session/DistributableSessionManagementProvider.java
  testsuite/integration/clustering/pom.xml
  testsuite/integration/clustering/src/test/java/org/jboss/as/test/clustering/cluster/AbstractClusteringTestCase.java
  testsuite/integration/clustering/src/test/java/org/jboss/as/test/clustering/cluster/sso/InfinispanServerSetupTask.java
  testsuite/integration/clustering/src/test/java/org/jboss/as/test/clustering/cluster/web/remote/InfinispanServerSetupTask.java
  testsuite/integration/clustering/src/test/resources/infinispan-server/infinispan.xml
  testsuite/integration/clustering/src/test/resources/infinispan-server/users.properties
Labels: deps-ok, ready-for-merge

#13569 WFLY-13869 Fixed intermittent blocked thread that can cause deployment failure of a distributable web application.
  clustering/server/src/main/java/org/wildfly/clustering/server/group/CacheGroupServiceConfigurator.java
  clustering/web/infinispan/src/main/java/org/wildfly/clustering/web/infinispan/routing/PrimaryOwnerRouteLocatorServiceConfigurator.java
Labels: deps-ok, ready-for-merge

#13571 [WFLY-13874] Use testsuite.ee.galleon.pack.groupId in the webservice …
  testsuite/integration/ws/pom.xml
Labels: deps-ok

#12682 [WFLY-12608] Integration tests for OCSP followup
  testsuite/integration/elytron/src/test/java/org/wildfly/test/integration/elytron/certs/CommonBase.java
  testsuite/integration/elytron/src/test/java/org/wildfly/test/integration/elytron/certs/ocsp/OcspTestBase.java
  testsuite/integration/elytron/src/test/java/org/wildfly/test/integration/elytron/certs/ocsp/OcspTestCase.java
  testsuite/shared/src/main/java/org/wildfly/test/security/common/elytron/Ocsp.java
Labels: 21.x, deps-ok, ready-for-merge

#12802 [WFLY-11868] Documentation for Rest integration with WildFly Elytron …
  docs/src/main/asciidoc/_elytron/Configuring_other_clients_using_wildfly-config.adoc
Labels: Feature-Docs, deps-ok, ready-for-merge

#13231 [WFLY-13125] Adding support for External HTTP authentication mechanis…
  docs/src/main/asciidoc/_elytron/General_Elytron_Architecture.adoc
  docs/src/main/asciidoc/_high-availability/subsystem-support/mod_cluster_Subsystem.adoc
  testsuite/integration/web/src/test/java/org/jboss/as/test/integration/web/security/external/Credentials.java
  testsuite/integration/web/src/test/java/org/jboss/as/test/integration/web/security/external/ExternalAuthSecurityDomainSetup.java
  testsuite/integration/web/src/test/java/org/jboss/as/test/integration/web/security/external/ExternalLoginModule.java
  testsuite/integration/web/src/test/java/org/jboss/as/test/integration/web/security/external/UserHandler.java
  testsuite/integration/web/src/test/java/org/jboss/as/test/integration/web/security/external/WebSecurityExternalAuthTestCase.java
  testsuite/shared/src/main/java/org/wildfly/test/security/common/elytron/UndertowDomainMapper.java
Labels: 21.x, Feature-Docs, deps-ok, ready-for-merge

#13484 [WFLY-13716] Integration tests for Elytron failover-realm
  testsuite/integration/elytron/src/test/java/org/wildfly/test/integration/elytron/realm/FailoverRealmTestCase.java
  testsuite/integration/elytron/src/test/java/org/wildfly/test/integration/elytron/realm/failover-realm-bearer-token-web.xml
  testsuite/integration/elytron/src/test/java/org/wildfly/test/integration/elytron/realm/failover-realm-web.xml
  testsuite/shared/src/main/java/org/wildfly/test/security/common/elytron/FailoverRealm.java
  testsuite/shared/src/main/java/org/wildfly/test/security/common/elytron/FileSystemRealm.java
  testsuite/shared/src/main/java/org/wildfly/test/security/common/elytron/PropertiesRealm.java
  testsuite/shared/src/main/java/org/wildfly/test/security/common/elytron/TokenRealm.java
Labels: deps-ok, ready-for-merge

#13533 WFLY-13825 The 'microprofile.surefire' execution doesn't run microprofile tests at all due to wrong package name include
  testsuite/integration/basic/pom.xml
  testsuite/integration/basic/src/test/java/org/wildfly/test/integration/microprofile/config/smallrye/converter/HighPriorityStringConverter1.java
  testsuite/integration/basic/src/test/java/org/wildfly/test/integration/microprofile/config/smallrye/converter/HighPriorityStringConverter2.java
Labels: 21.x, deps-ok, ready-for-merge

#13542 WFLY-12586 Duplicated classes in test suite, content slightly differs in some cases
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/deployment/classloading/war/WarInEarChildFirstClassLoadingTestCase.java
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/deployment/resourcelisting/EarResourceListingTestCase.java
  testsuite/integration/web/src/test/java/org/jboss/as/test/integration/deployment/classloading/war/WarClassLoadingTestCase.java
  testsuite/integration/web/src/test/java/org/jboss/as/test/integration/deployment/classloading/war/WebInfLibClass.java
  testsuite/integration/web/src/test/java/org/jboss/as/test/integration/deployment/resourcelisting/WarResourceListingTestCase.java
  testsuite/shared/src/main/java/org/jboss/as/test/integration/common/WebInfLibClass.java
Labels: deps-ok, ready-for-merge

#13544 WFLY-13832 Bug in detecting the org.apache.cxf module
  webservices/server-integration/pom.xml
  webservices/server-integration/src/main/java/org/jboss/as/webservices/deployers/WSClassVerificationProcessor.java
  webservices/server-integration/src/test/java/org/jboss/as/webservices/deployers/WSClassVerificationProcessorTestCase.java
Labels: deps-ok, ready-for-merge

#13561 [WFLY-13857] Remove the duplicate dependencies element
  ee-feature-pack/galleon-common/src/main/resources/layers/standalone/ejb-dist-cache/layer-spec.xml
Labels: deps-ok, ready-for-merge

#13564 WFLY-13856 [WARNING] 'profiles.profile[ts.clustering.layers.profile].plugins.plugin.(groupId:artifactId)' must be unique but found duplicate declaration of plugin org.wildfly.plugins:wildfly-maven-plugin @ line 1255, column 29
  testsuite/integration/clustering/pom.xml
  testsuite/integration/elytron/pom.xml
Labels: deps-ok, ready-for-merge

#13565 WFLY-13863 Adding Wildfly logo in README.md
  README.md
  logo/wildfly_logo.svg
Labels: deps-ok, ready-for-merge

#12887 [WFLY-12190] EJB: EJB over HTTP discovery configuration
  docs/src/main/asciidoc/_admin-guide/subsystem-configuration/EJB3.adoc
  ee-feature-pack/common/src/main/resources/modules/system/layers/base/org/jboss/as/ejb3/main/module.xml
  ee-feature-pack/common/src/main/resources/modules/system/layers/base/org/wildfly/http-client/ejb/main/module.xml
  ee/src/main/java/org/jboss/as/ee/metadata/EJBClientDescriptorMetaData.java
  ee/src/main/java/org/jboss/as/ee/structure/EJBClientDescriptor14Parser.java
  ee/src/main/java/org/jboss/as/ee/structure/EJBClientDescriptorXMLAttribute.java
  ee/src/main/java/org/jboss/as/ee/structure/EJBClientDescriptorXMLElement.java
  ejb3/pom.xml
  ejb3/src/main/java/org/jboss/as/ejb3/deployment/processors/DiscoveryRegistrationProcessor.java
  ejb3/src/main/java/org/jboss/as/ejb3/deployment/processors/EJBClientDescriptorMetaDataProcessor.java
  ejb3/src/main/java/org/jboss/as/ejb3/deployment/processors/EjbClientContextSetupProcessor.java
  ejb3/src/main/java/org/jboss/as/ejb3/remote/EJBClientContextService.java
  ejb3/src/main/java/org/jboss/as/ejb3/remote/RemotingProfileService.java
  ejb3/src/main/java/org/jboss/as/ejb3/subsystem/EJB3Subsystem50Parser.java
  ejb3/src/main/java/org/jboss/as/ejb3/subsystem/EJB3Subsystem60Parser.java
  ejb3/src/main/java/org/jboss/as/ejb3/subsystem/EJB3SubsystemModel.java
  ejb3/src/main/java/org/jboss/as/ejb3/subsystem/EJB3SubsystemXMLElement.java
  ejb3/src/main/java/org/jboss/as/ejb3/subsystem/EJB3SubsystemXMLPersister.java
  ejb3/src/main/java/org/jboss/as/ejb3/subsystem/RemoteHttpConnectionDefinition.java
  ejb3/src/main/java/org/jboss/as/ejb3/subsystem/RemotingProfileAdd.java
  ejb3/src/main/java/org/jboss/as/ejb3/subsystem/RemotingProfileResourceDefinition.java
  ejb3/src/main/resources/org/jboss/as/ejb3/subsystem/LocalDescriptions.properties
  pom.xml
  testsuite/integration/multinode/src/test/java/org/jboss/as/test/multinode/ejb/http/EjbOverHttpDescriptorTestCase.java
  testsuite/integration/multinode/src/test/java/org/jboss/as/test/multinode/ejb/http/EjbOverHttpTestCase.java
  testsuite/integration/multinode/src/test/java/org/jboss/as/test/multinode/ejb/http/EjbOverHttpWrongCredentialsTestCase.java
  testsuite/integration/multinode/src/test/java/org/jboss/as/test/multinode/ejb/http/StatelessBean.java
  testsuite/integration/multinode/src/test/java/org/jboss/as/test/multinode/ejb/http/StatelessLocal.java
  testsuite/integration/multinode/src/test/java/org/jboss/as/test/multinode/ejb/http/StatelessRemote.java
  testsuite/integration/multinode/src/test/java/org/jboss/as/test/multinode/remotecall/RemoteLocalCallProfileTestCase.java
  testsuite/integration/multinode/src/test/resources/META-INF/jboss-ejb-client-http-connections.xml
  testsuite/integration/multinode/src/test/resources/META-INF/jboss-ejb-client-profile.xml
  testsuite/integration/multinode/src/test/resources/ejb-http-wildfly-config-wrong.xml
  testsuite/integration/multinode/src/test/resources/ejb-http-wildfly-config.xml
Labels: 21.x, Feature, deps-ok

#13552 [WFLY-13842]:Upgrade jbossws-cxf to 5.4.2.Final
  pom.xml
Labels: deps-ok

#13578 [WFLY-13879] Upgrade Mojarra to 2.3.14.SP01
  pom.xml
Labels: deps-ok

#13397 [WFLY-12342] Add server probes for readiness health check
  docs/src/main/asciidoc/_admin-guide/subsystem-configuration/MicroProfile_Health.adoc
  microprofile/health-smallrye/pom.xml
  microprofile/health-smallrye/src/main/java/org/wildfly/extension/microprofile/health/HealthReporter.java
  microprofile/health-smallrye/src/main/java/org/wildfly/extension/microprofile/health/HealthReporterService.java
  microprofile/health-smallrye/src/main/java/org/wildfly/extension/microprofile/health/MicroProfileHealthSubsystemDefinition.java
  microprofile/health-smallrye/src/main/java/org/wildfly/extension/microprofile/health/ServerReadinessProbes.java
  microprofile/health-smallrye/src/main/resources/org/wildfly/extension/microprofile/health/LocalDescriptions.properties
  microprofile/health-smallrye/src/test/java/org/wildfly/extension/microprofile/health/Subsystem_2_0_ParsingTestCase.java
  testsuite/integration/basic/src/test/java/org/wildfly/test/integration/microprofile/health/MicroProfileHealthApplicationReadyHTTPEndpointTestCase.java
  testsuite/integration/basic/src/test/java/org/wildfly/test/integration/microprofile/health/MicroProfileHealthApplicationReadySetupTask.java
  testsuite/integration/basic/src/test/java/org/wildfly/test/integration/microprofile/health/MicroProfileHealthApplicationWithoutReadinessHTTPEndpointTestCase.java
  testsuite/integration/microprofile-tck/health/src/test/resources/arquillian.xml
Labels: 21.x, Feature, deps-ok

#13580 WFLY-13832 Added copyright header
  webservices/server-integration/src/test/java/org/jboss/as/webservices/deployers/WSClassVerificationProcessorTestCase.java
Labels: deps-ok, ready-for-merge

#13229 [WFLY-13396] Tests for RESTEasy integration with WildFly Elytron - Au…
  testsuite/integration/elytron/src/test/java/org/wildfly/test/integration/elytron/application/BasicAuthnTestCase.java
  testsuite/integration/elytron/src/test/java/org/wildfly/test/integration/elytron/resteasyclient/ClientConfigProviderBearerTokenTest.java
  testsuite/integration/elytron/src/test/java/org/wildfly/test/integration/elytron/ssl/UndertowTwoWaySslNeedClientAuthTestCase.java
  testsuite/integration/elytron/src/test/java/org/wildfly/test/integration/elytron/util/ClientConfigProviderBearerTokenAbortFilter.java
  testsuite/integration/elytron/src/test/java/org/wildfly/test/integration/elytron/util/ClientConfigProviderNoBasicAuthorizationHeaderFilter.java
  testsuite/integration/elytron/src/test/resources/org/wildfly/test/integration/elytron/ssl/wildfly-config-correct-truststore-correct-host.xml
  testsuite/integration/elytron/src/test/resources/org/wildfly/test/integration/elytron/ssl/wildfly-config-correct-truststore-different-host.xml
  testsuite/integration/elytron/src/test/resources/org/wildfly/test/integration/elytron/ssl/wildfly-config-correct-truststore-missing.xml
  testsuite/integration/elytron/src/test/resources/org/wildfly/test/integration/elytron/ssl/wildfly-config-correct-truststore.xml
Labels: 21.x, deps-ok

#13463 [WFLY-13747] Add tests for the remoting layers, these require Undertow.
  docs/src/main/asciidoc/_admin-guide/Galleon_provisioning.adoc
  testsuite/layers/pom.xml
Labels: 21.x, deps-ok, ready-for-merge

#13414 [WFLY-13085] Add documentation on the TLS 1.3 support for the OpenSSL TLS provider
  docs/src/main/asciidoc/_elytron/OpenSSL.adoc
  docs/src/main/asciidoc/_elytron/Using_the_Elytron_Subsystem.adoc
Labels: 21.x, Feature-Docs, deps-ok, ready-for-merge

#13584 [WFLY-13881][WFLY-13717] Correct diffs between the dist-legacy and ee-dist builds
  clustering/infinispan/extension/src/main/resources/subsystem-templates/infinispan.xml
  ee-feature-pack/galleon-common/src/main/resources/feature_groups/domain-mail-sockets.xml
Labels: 21.x, deps-ok

#13591 WFLY-13885 SharedSessionTestCase should test non-distributed session manager
  testsuite/integration/web/src/test/java/org/jboss/as/test/integration/web/sharedsession/jboss-all.xml
Labels: deps-ok, ready-for-merge

#13582 WFLY-13878 Add transformer and subsystem test coverage for EJB over H…
  docs/src/main/asciidoc/_admin-guide/subsystem-configuration/EJB3.adoc
  ejb3/src/main/java/org/jboss/as/ejb3/subsystem/EJB3Subsystem60Parser.java
  ejb3/src/main/java/org/jboss/as/ejb3/subsystem/EJB3Subsystem80Parser.java
  ejb3/src/main/java/org/jboss/as/ejb3/subsystem/EJBTransformers.java
  ejb3/src/main/resources/schema/wildfly-ejb3_8_0.xsd
  ejb3/src/test/java/org/jboss/as/ejb3/subsystem/Ejb3TransformersTestCase.java
  ejb3/src/test/resources/org/jboss/as/ejb3/subsystem/subsystem-ejb3-transform-reject.xml
  ejb3/src/test/resources/org/jboss/as/ejb3/subsystem/subsystem-ejb3-transform.xml
  ejb3/src/test/resources/org/jboss/as/ejb3/subsystem/subsystem.xml
Labels: deps-ok, ready-for-merge

#13592 [WFLY-13864] Added the fault-tolerance-smallrye and open-api-smallrye…
  docs/pom.xml
Labels: deps-ok

#13606 [WFLY-13901] Upgrade Jastow to 2.0.9.Final
  pom.xml
Labels: deps-ok

#13594 [WFLY-13892]: Opentracing capability is not properly registered
  microprofile/opentracing-extension/src/main/java/org/wildfly/extension/microprofile/opentracing/SubsystemAdd.java
  microprofile/opentracing-extension/src/main/java/org/wildfly/extension/microprofile/opentracing/SubsystemDefinition.java
  microprofile/opentracing-extension/src/test/java/org/wildfly/extension/microprofile/opentracing/Subsystem_2_0_ParsingTestCase.java
  microprofile/opentracing-extension/src/test/java/org/wildfly/extension/microprofile/opentracing/Subsystem_3_0_ParsingTestCase.java
  testsuite/mixed-domain/src/test/java/org/jboss/as/test/integration/domain/mixed/eap710/DomainAdjuster710.java
  testsuite/mixed-domain/src/test/java/org/jboss/as/test/integration/domain/mixed/eap730/DomainAdjuster730.java
Labels: deps-ok

#13603 WFLY-13894 Upgrade jboss-ejb-client to 4.0.35.Final
  pom.xml
Labels: deps-ok

#13595 [WFLY-13884] JdrReportManagmentTestCase fails when using the wildfly-…
  jdr/jboss-as-jdr/src/main/java/org/jboss/as/jdr/JdrRunner.java
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/jdr/mgmt/JdrReportManagmentTestCase.java
Labels: deps-ok

#13600 [WFLY-13807] EE: Add component class info to interface based proxy to preserve validation metadata
  ee/src/main/java/org/jboss/as/ee/component/DefaultComponentViewConfigurator.java
  ee/src/main/java/org/jboss/as/ee/component/ViewService.java
  ejb3/src/main/java/org/jboss/as/ejb3/security/AuthorizationInterceptor.java
  testsuite/integration/basic/pom.xml
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/ejb/validation/DummyAbstractClass.java
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/ejb/validation/DummyClass.java
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/ejb/validation/DummyFlag.java
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/ejb/validation/DummyFlagImpl.java
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/ejb/validation/DummySubclass.java
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/ejb/validation/EchoResource.java
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/ejb/validation/EchoResourceImpl.java
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/ejb/validation/EjbBeanValidationTestCase.java
Labels: deps-ok

#13599 [WFLY-13802] Minor fixes for Undertow deployments to allow web applications to be deployed when the EE subsystem is not installed.
  ee/src/main/java/org/jboss/as/ee/component/ComponentRegistry.java
  undertow/src/main/java/org/wildfly/extension/undertow/deployment/UndertowDeploymentInfoService.java
  undertow/src/main/java/org/wildfly/extension/undertow/deployment/UndertowDeploymentProcessor.java
Labels: 21.x, deps-ok

#13607 WFLY-13855 remote-cache-container protocol-version allowed values con…
  clustering/infinispan/extension/src/main/java/org/jboss/as/clustering/infinispan/subsystem/remote/RemoteCacheContainerResourceDefinition.java
Labels: deps-ok

#13605 WFLY-13900 - Update MyFaces version to 2.3.6
  jsf/multi-jsf-installer/pom.xml
  pom.xml
Labels: deps-ok, ready-for-merge

#13604 WFLY-13899 Fix wrong digester version
  jsf/multi-jsf-installer/src/main/resources/myfaces-deploy.scr
Labels: deps-ok, ready-for-merge
