Repository wildfly/wildfly, pull requests merged in 2020-04, with the labels that each got.

#13148 [WFLY-13264]: Messages are being added to topic even if there are no subscribers.
  messaging-activemq/src/main/java/org/wildfly/extension/messaging/activemq/ConfigurationHelper.java
Labels: 19.x, deps-ok, ready-for-merge

#13161 [WFLY-13316]: MicroProfile OpenTracing integration requires scope request.
  microprofile/opentracing-extension/src/main/java/org/wildfly/extension/microprofile/opentracing/TracingDeploymentProcessor.java
  microprofile/opentracing-smallrye/src/main/java/org/wildfly/microprofile/opentracing/smallrye/TracerProducer.java
  microprofile/opentracing-smallrye/src/main/java/org/wildfly/microprofile/opentracing/smallrye/TracingCDIExtension.java
Labels: deps-ok, ready-for-merge

#13162 [WFLY-13316]: MicroProfile OpenTracing integration requires scope req…
  microprofile/opentracing-extension/src/main/java/org/wildfly/extension/microprofile/opentracing/TracingDeploymentProcessor.java
  microprofile/opentracing-smallrye/src/main/java/org/wildfly/microprofile/opentracing/smallrye/TracerProducer.java
  microprofile/opentracing-smallrye/src/main/java/org/wildfly/microprofile/opentracing/smallrye/TracingCDIExtension.java
Labels: deps-ok

#13141 [WFLY-13288] Upgrade Mojarra to 2.3.9.SP08
  pom.xml
Labels: deps-ok, ready-for-merge

#13154 WFLY-13223: Upgrade HAL to 3.2.8.Final
  pom.xml
Labels: deps-ok, ready-for-merge

#13159 WFLY-13311 Upgrade Weld to 3.1.4.Final.
  pom.xml
Labels: deps-ok, ready-for-merge

#13139 WFLY-13287 Sync version of arquillian-testng-container with arquillian-junit-container
  pom.xml
Labels: deps-ok, ready-for-merge

#13144 WFLY-13278 CommandDispatcher cannot optimize marshalling of user command responses
  clustering/marshalling/jboss/src/main/java/org/wildfly/clustering/marshalling/jboss/DynamicClassTable.java
  clustering/marshalling/jboss/src/main/java/org/wildfly/clustering/marshalling/jboss/ExternalizerObjectTable.java
  clustering/server/src/main/java/org/wildfly/clustering/server/dispatcher/ChannelCommandDispatcher.java
  clustering/server/src/main/java/org/wildfly/clustering/server/dispatcher/ChannelCommandDispatcherFactory.java
  clustering/server/src/main/java/org/wildfly/clustering/server/dispatcher/CommandDispatcherContext.java
  clustering/server/src/main/java/org/wildfly/clustering/server/dispatcher/ServiceRequest.java
Labels: deps-ok, ready-for-merge

#13155 [WFLY-13300] Upgrade hibernate-validator to 6.0.19.Final
  pom.xml
Labels: deps-ok, ready-for-merge

#13157 [WFLY-13308] remove ejb client bom from dependency management
  pom.xml
Labels: deps-ok, ready-for-merge

#13171 WFLY-13333 Content-Length should specify length of *encoded* OpenAPI document
  microprofile/openapi-smallrye/src/main/java/org/wildfly/extension/microprofile/openapi/deployment/OpenAPIHttpHandler.java
Labels: deps-ok

#13178 [WFLY-13334]: MP Opentracing tests are not passing with a SecurityMan…
  feature-pack/src/main/resources/modules/system/layers/base/org/wildfly/microprofile/opentracing-smallrye/main/module.xml
  microprofile/opentracing-smallrye/src/main/java/org/wildfly/microprofile/opentracing/smallrye/TracingCDIExtension.java
Labels: 19.x, deps-ok

#13158 [19.0.x] [WFLY-13308] remove ejb client bom from dependency management
  pom.xml
Labels: 19.x, deps-ok, ready-for-merge

#13166 [19.0.x] [WFLY-13318] / [WFLY-13304] NPE Activating JWT without realm name and test cases.
  microprofile/jwt-smallrye/src/main/java/org/wildfly/extension/microprofile/jwt/smallrye/JwtActivationProcessor.java
  microprofile/jwt-smallrye/src/main/java/org/wildfly/extension/microprofile/jwt/smallrye/_private/MicroProfileJWTLogger.java
  pom.xml
  testsuite/integration/microprofile/pom.xml
  testsuite/integration/microprofile/src/test/java/org/wildfly/test/integration/microprofile/jwt/BaseCase.java
  testsuite/integration/microprofile/src/test/java/org/wildfly/test/integration/microprofile/jwt/SampleEndPoint.java
  testsuite/integration/microprofile/src/test/java/org/wildfly/test/integration/microprofile/jwt/TokenUtil.java
  testsuite/integration/microprofile/src/test/java/org/wildfly/test/integration/microprofile/jwt/norealm/App.java
  testsuite/integration/microprofile/src/test/java/org/wildfly/test/integration/microprofile/jwt/norealm/JWTNoRealmTestCase.java
  testsuite/integration/microprofile/src/test/java/org/wildfly/test/integration/microprofile/jwt/norealm/package-info.java
  testsuite/integration/microprofile/src/test/java/org/wildfly/test/integration/microprofile/jwt/smoke/App.java
  testsuite/integration/microprofile/src/test/java/org/wildfly/test/integration/microprofile/jwt/smoke/JWTSmokeTestCase.java
  testsuite/integration/microprofile/src/test/java/org/wildfly/test/integration/microprofile/jwt/smoke/package-info.java
  testsuite/integration/microprofile/src/test/resources/jwt/Readme.txt
  testsuite/integration/microprofile/src/test/resources/jwt/microprofile-config.properties
  testsuite/integration/microprofile/src/test/resources/jwt/private.pem
  testsuite/integration/microprofile/src/test/resources/jwt/public.pem
  testsuite/integration/microprofile/src/test/resources/jwt/web.xml
Labels: 19.x, deps-ok

#13172 [19.0.x] WFLY-13333 Content-Length should specify length of the *encoded* OpenAPI document
  microprofile/openapi-smallrye/src/main/java/org/wildfly/extension/microprofile/openapi/deployment/OpenAPIHttpHandler.java
Labels: 19.x, deps-ok

#13156 WFLY-13303 : Upgrade Hibernate ORM from 5.3.15 to 5.3.16
  pom.xml
Labels: deps-ok, ready-for-merge

#13151 WFLY-13176 Add jboss-ejb-client_1_3.xsd schema
  ejb3/src/main/resources/schema/jboss-ejb-client_1_3.xsd
Labels: deps-ok, ready-for-merge

#13127 WFLY-13277 Reduce latency of synchronous remote cache operations
  clustering/jgroups/extension/src/main/resources/jgroups-defaults.xml
Labels: deps-ok, ready-for-merge

#13163 [WFLY-12899] Set arbitrary property in surefire env rather depend on …
  testsuite/integration/basic/pom.xml
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/ee/jmx/property/JMXPropertyEditorsTestCase.java
Labels: deps-ok

#13053 WFLY-13163 Upgrade smallrye-open-api to 1.2.1
  pom.xml
Labels: deps-ok, ready-for-merge

#13185 [WFLY-13337]:Upgrade CXF from 3.3.5 to 3.3.6
  pom.xml
Labels: deps-ok, ready-for-merge

#13186 [WFLY-13337]:Upgrade CXF from 3.3.5 to 3.3.6
  pom.xml
Labels: 19.x, deps-ok

#13182 [WFLY-13339] Remove transitive dependencies from MP OpenAPI TCKs
  pom.xml
  testsuite/integration/microprofile-tck/openapi/pom.xml
Labels: deps-ok, ready-for-merge

#13180 [WFLY-11848][WFLY-13338] Work re log checking in tests
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/ejb/jndi/logging/Hello.java
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/ejb/jndi/logging/HelloBean.java
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/ejb/jndi/logging/JNDIBindingsNoAppNameTestCase.java
  testsuite/shared/src/main/java/org/jboss/as/test/shared/util/LoggingUtil.java
Labels: deps-ok, ready-for-merge

#13173 [WFLY-19905] Move module org.apache.xml-resolver from WildFly Core to WildFly
  ee-galleon-pack/pom.xml
  feature-pack/pom.xml
  feature-pack/src/license/full-feature-pack-licenses.xml
  feature-pack/src/main/resources/modules/system/layers/base/org/apache/xml-resolver/main/module.xml
  pom.xml
Labels: deps-changed, ready-for-merge

#13160 Follow up from https://github.com/wildfly/wildfly/pull/13153 to remov…
  weld/common/src/main/java/org/jboss/as/weld/util/ResourceInjectionUtilities.java
Labels: deps-ok, ready-for-merge

#13147 [WFLY-12807] Test Case for WFCORE-4475
  testsuite/integration/basic/src/test/java/org/wildfly/test/integration/web/annotationsmodule/EarModuleDeploymentTestCase.java
  testsuite/integration/basic/src/test/java/org/wildfly/test/integration/web/annotationsmodule/ModuleServlet.java
  testsuite/integration/basic/src/test/java/org/wildfly/test/integration/web/annotationsmodule/ModuleServlet2.java
  testsuite/integration/basic/src/test/java/org/wildfly/test/integration/web/annotationsmodule/TestEjb.java
  testsuite/integration/basic/src/test/java/org/wildfly/test/integration/web/annotationsmodule/TestServlet.java
  testsuite/integration/basic/src/test/resources/org/wildfly/test/integration/web/annotationsmodule/application1.xml
  testsuite/integration/basic/src/test/resources/org/wildfly/test/integration/web/annotationsmodule/application2.xml
  testsuite/integration/basic/src/test/resources/org/wildfly/test/integration/web/annotationsmodule/jboss-deployment-structure1.xml
  testsuite/integration/basic/src/test/resources/org/wildfly/test/integration/web/annotationsmodule/jboss-deployment-structure2.xml
Labels: deps-ok, ready-for-merge

#13121 WFLY-13147 Avoid processing deployments multiple times in Weld subsys…
  weld/subsystem/src/main/java/org/jboss/as/weld/deployment/BeanDeploymentArchiveImpl.java
  weld/subsystem/src/main/java/org/jboss/as/weld/deployment/processors/ExternalBeanArchiveProcessor.java
Labels: deps-ok, ready-for-merge

#13071 [WFLY-13189] CDI layer should not add the BV subsystem
  ee-galleon-pack/src/main/resources/layers/standalone/cdi/layer-spec.xml
Labels: deps-ok, ready-for-merge

#13184 [19.0.x][WFLY-13326] Upgrade RESTEasy to 3.11.2.Final
  pom.xml
Labels: 19.x, deps-ok, ready-for-merge

#13192 [WFLY-13342]: Upgrade Netty to 4.1.48
  pom.xml
Labels: deps-ok, ready-for-merge

#13193 [WFLY-13342]: Upgrade Netty to 4.1.48
  pom.xml
Labels: 19.x, deps-ok, ready-for-merge

#13189 WFLY-13346 Upgrade IronJacamar from 1.4.20.Final to 1.4.22.Final
  pom.xml
Labels: deps-ok

#13194 [19.0.x] [WFLY-13288] / [WFLY-12870] JSF component upgrades
  pom.xml
Labels: 19.x, deps-ok

#13046 WFLY-13159 Datasource resolution fails for application layer alias when using Hibernate bytecode enhancement
  docs/src/main/asciidoc/_developer-guide/JPA_Reference_Guide.adoc
  jpa/subsystem/src/main/java/org/jboss/as/jpa/config/Configuration.java
  jpa/subsystem/src/main/java/org/jboss/as/jpa/processor/PersistenceUnitServiceHandler.java
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/jpa/datasourcedefinition/persistence.xml
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/jpa/resourceref/DataSourceResourceReferenceTestCase.java
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/jpa/resourceref/Employee.java
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/jpa/resourceref/MyEjb.java
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/jpa/resourceref/application.xml
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/jpa/resourceref/persistence.xml
Labels: deps-ok, ready-for-merge

#13149 [WFLY-13293] When deploying "ROOT.war" in EAP7.x, the context root value output through jboss-cli is not valid
  testsuite/integration/basic/src/test/java/org/wildfly/test/integration/web/VirtualHostTestCase.java
  undertow/src/main/java/org/wildfly/extension/undertow/deployment/UndertowDeploymentInfoService.java
  undertow/src/main/java/org/wildfly/extension/undertow/deployment/UndertowDeploymentProcessor.java
Labels: deps-ok, ready-for-merge

#13164 WFLY-11442 Remove unused dependencies from org.jboss.as.ejb3
  feature-pack/src/main/resources/modules/system/layers/base/org/jboss/as/ejb3/main/module.xml
Labels: deps-ok, ready-for-merge

#13176 WFLY-13323 Upgrade smallrye-fault-tolerance to 4.2.0
  microprofile/fault-tolerance-smallrye/extension/src/main/java/org/wildfly/extension/microprofile/faulttolerance/MicroProfileFaultToleranceModel.java
  microprofile/fault-tolerance-smallrye/extension/src/main/java/org/wildfly/extension/microprofile/faulttolerance/MicroProfileFaultToleranceSchema.java
  pom.xml
Labels: deps-ok

#13197 WFLY-13359 Upgrade JGroups to 4.2.2.Final
  pom.xml
Labels: deps-ok

#13122 WFLY-12018 Fix NotSerializableException when a distributable web application uses web sockets.
  clustering/web/undertow/src/main/java/org/wildfly/clustering/web/undertow/session/DistributableSession.java
  clustering/web/undertow/src/main/java/org/wildfly/clustering/web/undertow/session/LocalSessionContext.java
  clustering/web/undertow/src/main/java/org/wildfly/clustering/web/undertow/session/LocalSessionContextFactory.java
  clustering/web/undertow/src/test/java/org/wildfly/clustering/web/undertow/session/DistributableSessionTestCase.java
Labels: deps-ok

#13201 [WFLY-13349] Upgrade WildFly Core 12.0.0.Beta1
  clustering/jgroups/extension/src/main/resources/schema/jboss-as-jgroups_7_0.xsd
  connector/src/main/resources/schema/wildfly-datasources_5_0.xsd
  connector/src/main/resources/schema/wildfly-resource-adapters_5_0.xsd
  datasources-agroal/src/main/resources/schema/wildfly-agroal_1_0.xsd
  feature-pack/src/main/resources/configuration/domain/template.xml
  feature-pack/src/main/resources/configuration/host/host-master.xml
  feature-pack/src/main/resources/configuration/host/host-slave.xml
  feature-pack/src/main/resources/configuration/host/host.xml
  feature-pack/src/main/resources/configuration/standalone/template.xml
  feature-pack/src/main/resources/content/appclient/configuration/appclient.xml
  feature-pack/src/main/resources/content/docs/examples/configs/standalone-minimalistic.xml
  mail/src/main/resources/schema/wildfly-mail_3_0.xsd
  messaging-activemq/src/main/resources/schema/wildfly-messaging-activemq_9_0.xsd
  pom.xml
  servlet-feature-pack/src/main/resources/configuration/domain/template.xml
  servlet-feature-pack/src/main/resources/configuration/host/host-master.xml
  servlet-feature-pack/src/main/resources/configuration/host/host-slave.xml
  servlet-feature-pack/src/main/resources/configuration/host/host.xml
  servlet-feature-pack/src/main/resources/configuration/standalone/template.xml
  testsuite/domain/src/test/resources/domain-configs/domain-minimal.xml
  testsuite/domain/src/test/resources/domain-configs/domain-rbac.xml
  testsuite/domain/src/test/resources/domain-configs/domain-respawn.xml
  testsuite/domain/src/test/resources/domain-configs/domain-standard-ee.xml
  testsuite/domain/src/test/resources/domain-configs/domain-standard.xml
  testsuite/domain/src/test/resources/host-configs/host-failover1.xml
  testsuite/domain/src/test/resources/host-configs/host-failover2.xml
  testsuite/domain/src/test/resources/host-configs/host-failover3.xml
  testsuite/domain/src/test/resources/host-configs/host-master-elytron.xml
  testsuite/domain/src/test/resources/host-configs/host-master-no-http.xml
  testsuite/domain/src/test/resources/host-configs/host-master-no-local.xml
  testsuite/domain/src/test/resources/host-configs/host-master-rbac-properties.xml
  testsuite/domain/src/test/resources/host-configs/host-master-rbac.xml
  testsuite/domain/src/test/resources/host-configs/host-master.xml
  testsuite/domain/src/test/resources/host-configs/host-secrets.xml
  testsuite/domain/src/test/resources/host-configs/host-slave-discovery-options.xml
  testsuite/domain/src/test/resources/host-configs/host-slave-elytron.xml
  testsuite/domain/src/test/resources/host-configs/host-slave-rbac-properties.xml
  testsuite/domain/src/test/resources/host-configs/host-slave-rbac.xml
  testsuite/domain/src/test/resources/host-configs/host-slave.xml
  testsuite/domain/src/test/resources/host-configs/respawn-master.xml
  testsuite/mixed-domain/src/test/resources/legacy-templates/test-template.xml
  testsuite/mixed-domain/src/test/resources/master-config/domain-minimal.xml
  testsuite/mixed-domain/src/test/resources/master-config/host-master-elytron.xml
  testsuite/mixed-domain/src/test/resources/master-config/host.xml
Labels: deps-changed

#13205 [WFLY-13370] Eliminate fault-tolerance/executor dependence on ee subs…
  galleon-pack/src/main/resources/modules/system/layers/base/org/wildfly/microprofile/fault-tolerance-smallrye/executor/main/module.xml
  microprofile/fault-tolerance-smallrye/executor/pom.xml
  microprofile/fault-tolerance-smallrye/executor/src/main/java/org/wildfly/extension/microprofile/faulttolerance/FaultToleranceContainerExecutorFactory.java
Labels: deps-ok

#13202 [WFLY-13361] Upgrade jboss-ejb-client to 4.0.32.Final
  pom.xml
Labels: deps-ok, ready-for-merge

#13199 WFLY-13362 Distributable web session attribute IDs do not need cryptographically strong pseudo random number generation.
  clustering/web/cache/src/main/java/org/wildfly/clustering/web/cache/session/fine/FineSessionAttributes.java
Labels: deps-ok

#12986 [WFLY-13087] Upgrade reactive-streams from 1.0.2 to 1.0.3
  pom.xml
Labels: deps-ok, ready-for-merge

#13211 [WFLY-13221] Remove package-schema cruft from wildfly-feature-pack-build.xml files
  dist-legacy/src/verifier/verifications.xml
  dist/src/verifier/verifications.xml
  ee-dist/src/verifier/verifications.xml
  ee-galleon-pack/wildfly-feature-pack-build.xml
  galleon-pack/wildfly-feature-pack-build.xml
  servlet-dist-legacy/src/verifier/verifications.xml
  servlet-dist/src/verifier/verifications.xml
  servlet-galleon-pack/wildfly-feature-pack-build.xml
Labels: deps-ok, ready-for-merge

#13212 [WFLY-13375] JNDI view does not show implementation classes for connection factories and destinations registered by 3rd party resource adapters.
  connector/src/main/java/org/jboss/as/connector/services/resourceadapters/AdminObjectReferenceFactoryService.java
  connector/src/main/java/org/jboss/as/connector/services/resourceadapters/ConnectionFactoryReferenceFactoryService.java
Labels: deps-ok, ready-for-merge

#13215 WFLY-13376 Removal of metric providing clustering resource leaves residual service.
  clustering/common/src/main/java/org/jboss/as/clustering/controller/ServiceValueExecutorRegistry.java
  clustering/common/src/main/java/org/jboss/as/clustering/controller/ServiceValueRegistry.java
  clustering/infinispan/extension/src/main/java/org/jboss/as/clustering/infinispan/subsystem/CacheContainerServiceHandler.java
  clustering/jgroups/extension/src/main/java/org/jboss/as/clustering/jgroups/subsystem/ChannelServiceHandler.java
  testsuite/integration/clustering/src/test/java/org/jboss/as/test/clustering/cluster/singleton/service/NodeServiceExecutorRegistry.java
Labels: deps-ok, ready-for-merge

#13216 [WFLY-13380] Upgrade dom4j to 2.1.3
  pom.xml
Labels: deps-ok, ready-for-merge

#13218 [WFLY-13381] At EJB3 remote AssociationImpl, we need to take into acc…
  ejb3/src/main/java/org/jboss/as/ejb3/remote/AssociationImpl.java
Labels: deps-ok, ready-for-merge

#13217 [19.0.x][WFLY-13380] Upgrade dom4j to 2.1.3
  pom.xml
Labels: 19.x, deps-ok, ready-for-merge

#13219 Remove licenses for artifacts that are not part of final zip
  ee-galleon-pack/pom.xml
  feature-pack/pom.xml
  feature-pack/src/license/full-feature-pack-licenses.xml
  galleon-pack/pom.xml
  servlet-galleon-pack/pom.xml
Labels: deps-ok

#13214 WFLY-13377 Upgrade JGroups to 4.2.3.Final
  pom.xml
Labels: deps-ok, ready-for-merge

#13228 Simplify PR template
  .github/PULL_REQUEST_TEMPLATE.md
Labels: deps-ok

#13240 Fix for WFLY-13406, Update layersTest to recognize bootable jar runtime
  testsuite/layers/src/test/java/org/jboss/as/test/layers/LayersTestCase.java
Labels: deps-ok, ready-for-merge

#13198 Fix for WFLY-13093, Upgrade Galleon from 4.2.4.Final to 4.2.5.Final
  pom.xml
Labels: deps-ok, ready-for-merge

#13206 [WFLY-13371] Clarify the MicroProfile subsystem dependency trees
  microprofile/config-smallrye/pom.xml
  microprofile/fault-tolerance-smallrye/extension/pom.xml
  microprofile/health-smallrye/pom.xml
  microprofile/jwt-smallrye/pom.xml
  microprofile/metrics-smallrye/pom.xml
  microprofile/openapi-smallrye/pom.xml
  microprofile/opentracing-extension/pom.xml
  microprofile/opentracing-smallrye/pom.xml
Labels: deps-ok, ready-for-merge

#13224 [WFLY-13390]:migrate operation on legacy messaging subsystem fails wi…
  legacy/messaging/src/main/java/org/jboss/as/messaging/MigrateOperation.java
  legacy/messaging/src/main/java/org/jboss/as/messaging/logging/MessagingLogger.java
  legacy/messaging/src/test/java/org/jboss/as/messaging/test/MigrateTestCase.java
  legacy/messaging/src/test/resources/org/jboss/as/messaging/test/subsystem_migration.xml
Labels: deps-ok, ready-for-merge

#13227 WFLY-13378 Upgrade Eclipse MicroProfile Fault Tolerance API to 2.1.1-RC1
  pom.xml
  testsuite/integration/microprofile-tck/fault-tolerance/src/test/java/org/wildfly/extension/microprofile/faulttolerance/tck/FaultToleranceApplicationArchiveProcessor.java
Labels: deps-ok, ready-for-merge

#13230 WFLY-13014 Consolidate instances of DefaultValueAttributeConverter
  clustering/infinispan/extension/src/main/java/org/jboss/as/clustering/infinispan/subsystem/ClusteredCacheResourceDefinition.java
  clustering/infinispan/extension/src/main/java/org/jboss/as/clustering/infinispan/subsystem/DistributedCacheResourceDefinition.java
  clustering/infinispan/extension/src/main/java/org/jboss/as/clustering/infinispan/subsystem/LockingResourceDefinition.java
  clustering/infinispan/extension/src/main/java/org/jboss/as/clustering/infinispan/subsystem/SegmentedCacheResourceDefinition.java
  clustering/infinispan/extension/src/main/java/org/jboss/as/clustering/infinispan/subsystem/StateTransferResourceDefinition.java
  clustering/infinispan/extension/src/main/java/org/jboss/as/clustering/infinispan/subsystem/StoreWriteBehindResourceDefinition.java
  clustering/infinispan/extension/src/main/java/org/jboss/as/clustering/infinispan/subsystem/TransactionResourceDefinition.java
  clustering/infinispan/extension/src/main/java/org/jboss/as/clustering/infinispan/subsystem/remote/RemoteCacheContainerResourceDefinition.java
  clustering/jgroups/extension/src/main/java/org/jboss/as/clustering/jgroups/subsystem/ThreadPoolResourceDefinition.java
  clustering/jgroups/extension/src/main/java/org/jboss/as/clustering/jgroups/subsystem/TransportResourceDefinition.java
  connector/src/main/java/org/jboss/as/connector/subsystems/datasources/DataSourcesTransformers.java
  connector/src/main/java/org/jboss/as/connector/subsystems/resourceadapters/ResourceAdaptersTransformers.java
  iiop-openjdk/src/main/java/org/wildfly/iiop/openjdk/IIOPTransformers.java
  legacy/jacorb/src/main/java/org/jboss/as/jacorb/JacORBExtension.java
  messaging-activemq/src/main/java/org/wildfly/extension/messaging/activemq/MessagingTransformerRegistration.java
  transactions/src/main/java/org/jboss/as/txn/subsystem/TransactionTransformers.java
  undertow/src/main/java/org/wildfly/extension/undertow/UndertowTransformers.java
Labels: deps-ok, ready-for-merge

#13234 [WFLY-13184] Convert javaee.api module name in an alias of wildlfyee...
  feature-pack/src/main/resources/modules/system/layers/base/javaee/api/main/module.xml
Labels: deps-ok, ready-for-merge

#13236 WFLY-13399 Upgrade Infinispan to 9.4.19.Final
  clustering/infinispan/client/src/main/java/org/wildfly/clustering/infinispan/client/RegisteredRemoteCache.java
  clustering/web/cache/src/main/java/org/wildfly/clustering/web/cache/session/fine/FineSessionAttributes.java
  pom.xml
Labels: deps-ok, ready-for-merge

#13244 [WFLY-13405] provide a CommonDeployment name to the debug logging
  connector/src/main/java/org/jboss/as/connector/subsystems/datasources/CommonDeploymentService.java
Labels: deps-ok

#13245 [WFLY-13405] provide a CommonDeployment name to the debug logging
  connector/src/main/java/org/jboss/as/connector/subsystems/datasources/CommonDeploymentService.java
Labels: 19.x, deps-ok

#13246 [WFLY-13371] Add missing test dependencies
  microprofile/config-smallrye/pom.xml
  microprofile/fault-tolerance-smallrye/extension/pom.xml
  microprofile/health-smallrye/pom.xml
  microprofile/jwt-smallrye/pom.xml
  microprofile/metrics-smallrye/pom.xml
  microprofile/openapi-smallrye/pom.xml
  microprofile/opentracing-extension/pom.xml
Labels: deps-ok

#13221 [WFLY-13267] Convert EJB3 subsystem transformers to use chained transformers
  ejb3/src/main/java/org/jboss/as/ejb3/subsystem/EJB3Model.java
  ejb3/src/main/java/org/jboss/as/ejb3/subsystem/EJBTransformers.java
  ejb3/src/test/java/org/jboss/as/ejb3/subsystem/Ejb3TransformersTestCase.java
Labels: deps-ok

#13020 Fix for WFLY-13129, Example CLI script
  docs/src/main/asciidoc/_admin-guide/CLI_Recipes.adoc
  galleon-pack/src/main/resources/packages/docs.examples/content/docs/examples/enable-microprofile.cli
  galleon-pack/src/main/resources/packages/docs.examples/package.xml
  galleon-pack/wildfly-feature-pack-build.xml
  testsuite/integration/manualmode/src/test/java/org/wildfly/test/manual/management/MPScriptTestCase.java
  testsuite/integration/microprofile/pom.xml
  testsuite/pom.xml
Labels: Feature, deps-ok

#13251 [WFLY-13415] Upgrade WildFly Core 12.0.0.Beta2
  pom.xml
Labels: deps-ok, ready-for-merge

#13248 WFLY-13413 Undertow mod-cluster filter capability name is incorrectly…
  undertow/src/main/java/org/wildfly/extension/undertow/filters/ModClusterDefinition.java
  undertow/src/test/resources/org/wildfly/extension/undertow/undertow-10.0.xml
Labels: deps-ok, ready-for-merge

#13254 [WFLY-13414] Upgrade WildFly Core 11.1.1.Final
  pom.xml
Labels: 19.x, deps-ok

#13190 [19.0.x] [WFLY-12834] Add documentation on the enabled-protocols attribute and indicate how it works when OpenSSL 1.1.0 or higher is in use
  docs/src/main/asciidoc/_admin-guide/Security_Realms_Detailed_Configuration.adoc
Labels: 19.x, deps-ok
