Repository wildfly/wildfly, pull requests merged in 2020-07, with the labels that each got.

#13393 WFLY-12709 20.x
  pom.xml
  testsuite/integration/microprofile-tck/pom.xml
  testsuite/integration/microprofile-tck/rest-client/beans.xml
  testsuite/integration/microprofile-tck/rest-client/module.xml
  testsuite/integration/microprofile-tck/rest-client/pom.xml
  testsuite/integration/microprofile-tck/rest-client/src/test/resources/arquillian.xml
  testsuite/integration/microprofile-tck/rest-client/wiremock.cli
Labels: 20.x, deps-ok

#13396 [20.x] [WFLY-13644] Upgrade WildFly Core 12.0.3.Final
  pom.xml
Labels: 20.x, deps-ok

#13390 [WFLY-13626] make transaction subsytem CMR attributes optional
  transactions/pom.xml
  transactions/src/main/java/org/jboss/as/txn/subsystem/TransactionSubsystem15Parser.java
  transactions/src/main/java/org/jboss/as/txn/subsystem/TransactionSubsystem30Parser.java
  transactions/src/test/java/org/jboss/as/txn/TestWildFlyTSR.java
  transactions/src/test/java/org/jboss/as/txn/subsystem/TransactionSubsystemTestCase.java
  transactions/src/test/resources/org/jboss/as/txn/subsystem/cmr.xml
Labels: deps-ok

#13395 WFLY-13643 Test Case of WFLY-13592 "jndi-view doen't show values for EJB in java:jboss/exported"
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/naming/remote/ejb/RemoteNamingEjbTestCase.java
Labels: deps-ok

#13391 WFLY-13627 Distributed sessions/SFSBs stored in non-transactional invalidation-cache should schedule expirations locally
  clustering/ee/infinispan/src/main/java/org/wildfly/clustering/ee/infinispan/PrimaryOwnerLocator.java
  clustering/ejb/infinispan/src/main/java/org/wildfly/clustering/ejb/infinispan/InfinispanBeanManager.java
  clustering/infinispan/extension/src/main/java/org/jboss/as/clustering/infinispan/subsystem/KeyAffinityServiceFactoryServiceConfigurator.java
  clustering/web/infinispan/src/main/java/org/wildfly/clustering/web/infinispan/routing/PrimaryOwnerRouteLocator.java
  clustering/web/infinispan/src/main/java/org/wildfly/clustering/web/infinispan/routing/RankedRouteLocator.java
  clustering/web/infinispan/src/main/java/org/wildfly/clustering/web/infinispan/session/InfinispanSessionManager.java
  clustering/web/infinispan/src/test/java/org/wildfly/clustering/web/infinispan/routing/PrimaryOwnerRouteLocatorTestCase.java
  clustering/web/infinispan/src/test/java/org/wildfly/clustering/web/infinispan/routing/RankedRouteLocatorTestCase.java
Labels: deps-ok

#13392 WFLY-13628 Invalidation caches need to consider keys in the cache store when reassigning ownership
  clustering/ejb/infinispan/src/main/java/org/wildfly/clustering/ejb/infinispan/InfinispanBeanManager.java
  clustering/web/infinispan/src/main/java/org/wildfly/clustering/web/infinispan/session/ExpiredSessionRemover.java
  clustering/web/infinispan/src/main/java/org/wildfly/clustering/web/infinispan/session/InfinispanSessionManager.java
  clustering/web/infinispan/src/main/java/org/wildfly/clustering/web/infinispan/session/InfinispanSessionManagerConfiguration.java
  clustering/web/infinispan/src/main/java/org/wildfly/clustering/web/infinispan/session/InfinispanSessionManagerFactory.java
Labels: deps-ok

#13400 [WFLY-13649] Make possible swap maven coordinates for MP Rest Client
  testsuite/integration/microprofile-tck/rest-client/pom.xml
Labels: deps-ok

#13334 WFLY-13538 Port Java 9+ version of ConcurrentDirectDeque from Undertow
  clustering/ee/cache/build-include-jdk-misc
  clustering/ee/cache/build-test-java10
  clustering/ee/cache/build-test-java11
  clustering/ee/cache/build-test-java8
  clustering/ee/cache/build-test-java9
  clustering/ee/cache/pom.xml
  clustering/ee/cache/src/main/java9/org/wildfly/clustering/ee/cache/scheduler/FastConcurrentDirectDeque.java
Labels: deps-ok

#13398 WFLY-13639 Avoid duplicate expiration scheduling on member leave for non-tx invalidation cache
  clustering/ee/cache/src/main/java/org/wildfly/clustering/ee/cache/Key.java
  clustering/ee/infinispan/src/main/java/org/wildfly/clustering/ee/infinispan/GroupedKey.java
  clustering/ee/infinispan/src/main/java/org/wildfly/clustering/ee/infinispan/PrimaryOwnerLocator.java
  clustering/ee/infinispan/src/main/java/org/wildfly/clustering/ee/infinispan/scheduler/ScheduleLocalEntriesTask.java
  clustering/ee/infinispan/src/main/java/org/wildfly/clustering/ee/infinispan/scheduler/ScheduleLocalKeysTask.java
  clustering/ee/infinispan/src/main/java/org/wildfly/clustering/ee/infinispan/scheduler/SchedulerListener.java
  clustering/ee/infinispan/src/main/java/org/wildfly/clustering/ee/infinispan/scheduler/SchedulerTopologyChangeListener.java
  clustering/ejb/infinispan/src/main/java/org/wildfly/clustering/ejb/infinispan/BeanGroupKey.java
  clustering/ejb/infinispan/src/main/java/org/wildfly/clustering/ejb/infinispan/BeanKey.java
  clustering/ejb/infinispan/src/main/java/org/wildfly/clustering/ejb/infinispan/InfinispanBeanManager.java
  clustering/ejb/infinispan/src/main/java/org/wildfly/clustering/ejb/infinispan/bean/InfinispanBeanKey.java
  clustering/ejb/infinispan/src/main/java/org/wildfly/clustering/ejb/infinispan/group/InfinispanBeanGroupKey.java
  clustering/infinispan/extension/src/main/java/org/jboss/as/clustering/infinispan/subsystem/KeyAffinityServiceFactoryServiceConfigurator.java
  clustering/infinispan/spi/src/main/java/org/wildfly/clustering/infinispan/spi/distribution/KeyPartitionerFactory.java
  clustering/web/infinispan/src/main/java/org/wildfly/clustering/web/infinispan/AffinityIdentifierFactory.java
  clustering/web/infinispan/src/main/java/org/wildfly/clustering/web/infinispan/SessionKeyExternalizer.java
  clustering/web/infinispan/src/main/java/org/wildfly/clustering/web/infinispan/SessionKeyFormat.java
  clustering/web/infinispan/src/main/java/org/wildfly/clustering/web/infinispan/routing/PrimaryOwnerRouteLocator.java
  clustering/web/infinispan/src/main/java/org/wildfly/clustering/web/infinispan/routing/PrimaryOwnerRouteLocatorConfiguration.java
  clustering/web/infinispan/src/main/java/org/wildfly/clustering/web/infinispan/routing/PrimaryOwnerRouteLocatorServiceConfigurator.java
  clustering/web/infinispan/src/main/java/org/wildfly/clustering/web/infinispan/routing/RankedRouteLocator.java
  clustering/web/infinispan/src/main/java/org/wildfly/clustering/web/infinispan/session/InfinispanSessionManager.java
  clustering/web/infinispan/src/main/java/org/wildfly/clustering/web/infinispan/session/InfinispanSessionManagerConfiguration.java
  clustering/web/infinispan/src/main/java/org/wildfly/clustering/web/infinispan/session/InfinispanSessionManagerFactory.java
  clustering/web/infinispan/src/main/java/org/wildfly/clustering/web/infinispan/session/InfinispanSessionMetaDataFactory.java
  clustering/web/infinispan/src/main/java/org/wildfly/clustering/web/infinispan/session/SessionAccessMetaDataKey.java
  clustering/web/infinispan/src/main/java/org/wildfly/clustering/web/infinispan/session/SessionCreationMetaDataKey.java
  clustering/web/infinispan/src/main/java/org/wildfly/clustering/web/infinispan/session/SessionExpirationScheduler.java
  clustering/web/infinispan/src/main/java/org/wildfly/clustering/web/infinispan/session/coarse/CoarseSessionAttributesFactory.java
  clustering/web/infinispan/src/main/java/org/wildfly/clustering/web/infinispan/session/coarse/SessionAttributesKey.java
  clustering/web/infinispan/src/main/java/org/wildfly/clustering/web/infinispan/session/fine/FineSessionAttributesFactory.java
  clustering/web/infinispan/src/main/java/org/wildfly/clustering/web/infinispan/session/fine/SessionAttributeKey.java
  clustering/web/infinispan/src/main/java/org/wildfly/clustering/web/infinispan/session/fine/SessionAttributeKeyExternalizer.java
  clustering/web/infinispan/src/main/java/org/wildfly/clustering/web/infinispan/session/fine/SessionAttributeKeyFormat.java
  clustering/web/infinispan/src/main/java/org/wildfly/clustering/web/infinispan/session/fine/SessionAttributeNamesKey.java
  clustering/web/infinispan/src/main/java/org/wildfly/clustering/web/infinispan/sso/AuthenticationKey.java
  clustering/web/infinispan/src/main/java/org/wildfly/clustering/web/infinispan/sso/InfinispanSSOManagerFactory.java
  clustering/web/infinispan/src/main/java/org/wildfly/clustering/web/infinispan/sso/coarse/CoarseSessionsFactory.java
  clustering/web/infinispan/src/main/java/org/wildfly/clustering/web/infinispan/sso/coarse/CoarseSessionsKey.java
  clustering/web/infinispan/src/test/java/org/wildfly/clustering/web/infinispan/AffinityIdentityFactoryTestCase.java
  clustering/web/infinispan/src/test/java/org/wildfly/clustering/web/infinispan/routing/PrimaryOwnerRouteLocatorTestCase.java
  clustering/web/infinispan/src/test/java/org/wildfly/clustering/web/infinispan/routing/RankedRouteLocatorTestCase.java
  feature-pack/src/main/resources/modules/system/layers/base/org/wildfly/clustering/ee/infinispan/main/module.xml
  feature-pack/src/main/resources/modules/system/layers/base/org/wildfly/clustering/web/infinispan/main/module.xml
Labels: deps-ok

#13405 WFLY-13616 Distributed session manager should trigger HttpSessionAttributeListener.attributeRemoved events on session destroy
  clustering/web/cache/src/main/java/org/wildfly/clustering/web/cache/session/ImmutableSessionBindingNotifier.java
  clustering/web/cache/src/main/java/org/wildfly/clustering/web/cache/session/MarshalledValueSessionAttributesFactoryConfiguration.java
  clustering/web/cache/src/test/java/org/wildfly/clustering/web/cache/session/ImmutableSessionBindingNotifierTestCase.java
  clustering/web/hotrod/src/main/java/org/wildfly/clustering/web/hotrod/session/HotRodSessionManagementProvider.java
  clustering/web/hotrod/src/main/java/org/wildfly/clustering/web/hotrod/session/HotRodSessionManagerFactory.java
  clustering/web/hotrod/src/main/java/org/wildfly/clustering/web/hotrod/session/HotRodSessionManagerFactoryConfiguration.java
  clustering/web/hotrod/src/main/java/org/wildfly/clustering/web/hotrod/session/HotRodSessionManagerFactoryServiceConfigurator.java
  clustering/web/infinispan/src/main/java/org/wildfly/clustering/web/infinispan/session/InfinispanSessionManagementProvider.java
  clustering/web/infinispan/src/main/java/org/wildfly/clustering/web/infinispan/session/InfinispanSessionManager.java
  clustering/web/infinispan/src/main/java/org/wildfly/clustering/web/infinispan/session/InfinispanSessionManagerConfiguration.java
  clustering/web/infinispan/src/main/java/org/wildfly/clustering/web/infinispan/session/InfinispanSessionManagerFactory.java
  clustering/web/infinispan/src/main/java/org/wildfly/clustering/web/infinispan/session/InfinispanSessionManagerFactoryConfiguration.java
  clustering/web/infinispan/src/main/java/org/wildfly/clustering/web/infinispan/session/InfinispanSessionManagerFactoryServiceConfigurator.java
  clustering/web/spi/src/main/java/org/wildfly/clustering/web/session/DistributableSessionManagementProvider.java
  clustering/web/spi/src/main/java/org/wildfly/clustering/web/session/HttpSessionBindingListenerProvider.java
  clustering/web/spi/src/main/java/org/wildfly/clustering/web/session/SessionManagerFactoryConfiguration.java
  clustering/web/spi/src/main/java/org/wildfly/clustering/web/session/SpecificationProvider.java
  clustering/web/undertow/src/main/java/org/wildfly/clustering/web/undertow/session/DistributableSession.java
  clustering/web/undertow/src/main/java/org/wildfly/clustering/web/undertow/session/SessionManagerFactoryConfigurationAdapter.java
  clustering/web/undertow/src/main/java/org/wildfly/clustering/web/undertow/session/UndertowSessionExpirationListener.java
  clustering/web/undertow/src/main/java/org/wildfly/clustering/web/undertow/session/UndertowSpecificationProvider.java
  clustering/web/undertow/src/test/java/org/wildfly/clustering/web/undertow/session/DistributableSessionTestCase.java
  clustering/web/undertow/src/test/java/org/wildfly/clustering/web/undertow/session/UndertowHttpSessionBindingListenerProviderTestCase.java
  testsuite/integration/clustering/src/test/java/org/jboss/as/test/clustering/cluster/web/expiration/SessionExpirationTestCase.java
  testsuite/integration/clustering/src/test/java/org/jboss/as/test/clustering/cluster/web/expiration/SessionOperationServlet.java
Labels: deps-ok

#13210 [WFLY-13090] EJB: global configuration for request compression
  docs/src/main/asciidoc/_client-guide/jboss-ejb-client.adoc
  docs/src/main/asciidoc/_client-guide/wildfly-config-jboss-ejb-client.adoc
  ee/src/main/java/org/jboss/as/ee/metadata/EJBClientDescriptorMetaData.java
  ee/src/main/java/org/jboss/as/ee/structure/EJBClientDescriptor14Parser.java
  ee/src/main/java/org/jboss/as/ee/structure/EJBClientDescriptorParsingProcessor.java
  ee/src/main/java/org/jboss/as/ee/structure/EJBClientDescriptorXMLAttribute.java
  ejb3/src/main/java/org/jboss/as/ejb3/deployment/processors/EJBClientDescriptorMetaDataProcessor.java
  ejb3/src/main/java/org/jboss/as/ejb3/remote/EJBClientContextService.java
  ejb3/src/main/resources/schema/jboss-ejb-client_1_4.xsd
Labels: Feature, deps-ok, ready-for-merge

#13289 WFLY-13469 Decouple distributed SFSB cache from client mappings registry
  clustering/ee/infinispan/src/main/java/org/wildfly/clustering/ee/infinispan/PrimaryOwnerLocator.java
  clustering/ejb/infinispan/src/main/java/org/wildfly/clustering/ejb/infinispan/ClientMappingsCacheServiceConfiguratorProvider.java
  clustering/ejb/infinispan/src/main/java/org/wildfly/clustering/ejb/infinispan/InfinispanBeanManager.java
  clustering/ejb/infinispan/src/main/java/org/wildfly/clustering/ejb/infinispan/InfinispanBeanManagerConfiguration.java
  clustering/ejb/infinispan/src/main/java/org/wildfly/clustering/ejb/infinispan/InfinispanBeanManagerFactory.java
  clustering/ejb/infinispan/src/main/java/org/wildfly/clustering/ejb/infinispan/InfinispanBeanManagerFactoryConfiguration.java
  clustering/ejb/infinispan/src/main/java/org/wildfly/clustering/ejb/infinispan/InfinispanBeanManagerFactoryServiceConfigurator.java
  clustering/ejb/infinispan/src/main/java/org/wildfly/clustering/ejb/infinispan/InfinispanBeanManagerFactoryServiceConfiguratorFactory.java
  clustering/ejb/spi/src/main/java/org/wildfly/clustering/ejb/BeanManagerFactoryServiceConfiguratorFactory.java
  clustering/server/src/main/java/org/wildfly/clustering/server/CacheRequirementServiceConfiguratorProvider.java
  clustering/server/src/main/java/org/wildfly/clustering/server/GroupRequirementServiceConfiguratorProvider.java
  clustering/server/src/main/java/org/wildfly/clustering/server/IdentityCacheRequirementServiceConfiguratorProvider.java
  clustering/server/src/main/java/org/wildfly/clustering/server/IdentityGroupRequirementServiceConfiguratorProvider.java
  clustering/server/src/main/java/org/wildfly/clustering/server/registry/IdentityRegistryFactoryServiceConfiguratorProvider.java
  clustering/server/src/main/java/org/wildfly/clustering/server/registry/RegistryFactoryServiceConfiguratorProvider.java
  clustering/server/src/main/java/org/wildfly/clustering/server/singleton/IdentitySingletonServiceBuilderFactoryBuilderProvider.java
  clustering/server/src/main/java/org/wildfly/clustering/server/singleton/SingletonServiceConfiguratorFactoryServiceConfiguratorProvider.java
  clustering/spi/src/main/java/org/wildfly/clustering/spi/CacheServiceConfiguratorProvider.java
  clustering/spi/src/main/java/org/wildfly/clustering/spi/GroupServiceConfiguratorProvider.java
  clustering/spi/src/main/java/org/wildfly/clustering/spi/IdentityCacheServiceConfiguratorProvider.java
  clustering/spi/src/main/java/org/wildfly/clustering/spi/IdentityGroupServiceConfiguratorProvider.java
  clustering/web/cache/src/main/java/org/wildfly/clustering/web/cache/routing/LocalRoutingProvider.java
  clustering/web/infinispan/src/main/java/org/wildfly/clustering/web/infinispan/routing/InfinispanRoutingProvider.java
  clustering/web/spi/src/main/java/org/wildfly/clustering/web/routing/RoutingProvider.java
  ejb3/src/main/java/org/jboss/as/ejb3/cache/CacheFactoryBuilder.java
  ejb3/src/main/java/org/jboss/as/ejb3/cache/distributable/DistributableCacheFactoryBuilderServiceConfigurator.java
  ejb3/src/main/java/org/jboss/as/ejb3/cache/simple/SimpleCacheFactoryBuilderServiceConfigurator.java
Labels: deps-ok, ready-for-merge

#13348 [WFLY-12171] toss the ejb-xa-recovery file permissions out of ejb client tests
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/ejb/client/descriptor/EJBClientDescriptorTestCase.java
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/ejb/security/runas/propagation/RunAsWithElytronEJBContextPropagationTestCase.java
  testsuite/integration/manualmode/src/test/java/org/jboss/as/test/manualmode/ejb/client/outbound/connection/RemoteOutboundConnectionReconnectTestCase.java
  testsuite/integration/manualmode/src/test/java/org/jboss/as/test/manualmode/ejb/client/outbound/connection/security/ElytronRemoteOutboundConnectionTestCase.java
  testsuite/integration/manualmode/src/test/java/org/jboss/as/test/manualmode/ejb/client/outbound/connection/transaction/preparehalt/TransactionPropagationPrepareHaltTestCase.java
  testsuite/integration/multinode/src/test/java/org/jboss/as/test/multinode/clientinterceptor/RemoteCallClientInterceptorTestCase.java
  testsuite/integration/multinode/src/test/java/org/jboss/as/test/multinode/clientinterceptor/multiple/MultipleClientInterceptorTestCase.java
  testsuite/integration/multinode/src/test/java/org/jboss/as/test/multinode/clientinterceptor/protocol/RemoteProtocolChangeClientInterceptorTestCase.java
  testsuite/integration/multinode/src/test/java/org/jboss/as/test/multinode/clientinterceptor/secured/SecuredBeanClientInterceptorTestCase.java
  testsuite/integration/multinode/src/test/java/org/jboss/as/test/multinode/remotecall/RemoteLocalCallProfileTestCase.java
  testsuite/integration/multinode/src/test/java/org/jboss/as/test/multinode/remotecall/RemoteLocalCallTestCase.java
  testsuite/integration/multinode/src/test/java/org/jboss/as/test/multinode/transaction/TransactionInvocationTestCase.java
  testsuite/integration/multinode/src/test/java/org/jboss/as/test/multinode/transaction/async/TransactionPropagationTestCase.java
Labels: deps-ok, ready-for-merge

#13389 [WFLY-13622] Upgrade WildFly maven-plugins to 2.2.0.Final
  pom.xml
Labels: deps-ok, ready-for-merge

#13403 AbstractEJBComponentResourceDefinition.METHODS should be a map of complex objects
  ejb3/src/main/java/org/jboss/as/ejb3/subsystem/deployment/AbstractEJBComponentResourceDefinition.java
Labels: deps-ok, ready-for-merge

#13406 WFLY-13641 Do not try to index beans if module from jboss-deployment-…
  microprofile/opentracing-extension/src/main/java/org/wildfly/extension/microprofile/opentracing/TracingDependencyProcessor.java
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/logging/config/LoggingConfigSharedTestCase.java
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/logging/config/LoggingProfileSharedTestCase.java
  weld/subsystem/src/main/java/org/jboss/as/weld/deployment/processors/ExternalBeanArchiveProcessor.java
Labels: deps-ok, ready-for-merge

#13363 WFLY-12654 Switch from javax.jws:jsr181-api to jakarta.jws:jakarta.jws-api
  pom.xml
  webservices/server-integration/pom.xml
  webservices/tests-integration/pom.xml
Labels: deps-ok, ready-for-merge

#13399 [WFLY-13647] Annotation processing error sun.reflect.annotation.TypeNotPresentExceptionProxy does not indicate issue
  ejb3/src/main/java/org/jboss/as/ejb3/deployment/processors/BusinessViewAnnotationProcessor.java
  ejb3/src/main/java/org/jboss/as/ejb3/logging/EjbLogger.java
  undertow/src/main/java/org/wildfly/extension/undertow/deployment/ServletContainerInitializerDeploymentProcessor.java
  undertow/src/main/java/org/wildfly/extension/undertow/logging/UndertowLogger.java
Labels: deps-ok, ready-for-merge

#13402 [WFLY-13650] Allow expressions for ordinal attribute
  microprofile/config-smallrye/pom.xml
  microprofile/config-smallrye/src/main/java/org/wildfly/extension/microprofile/config/smallrye/ConfigSourceDefinition.java
  microprofile/config-smallrye/src/main/java/org/wildfly/extension/microprofile/config/smallrye/ConfigSourceProviderDefinition.java
  microprofile/config-smallrye/src/main/java/org/wildfly/extension/microprofile/config/smallrye/MicroProfileConfigExtension.java
  microprofile/config-smallrye/src/main/java/org/wildfly/extension/microprofile/config/smallrye/MicroProfileConfigTransformers.java
  microprofile/config-smallrye/src/test/java/org/wildfly/extension/microprofile/config/Subsystem_1_0_ParsingTestCase.java
  microprofile/config-smallrye/src/test/java/org/wildfly/extension/microprofile/config/smallrye/Subsystem_1_0_ParsingTestCase.java
  microprofile/config-smallrye/src/test/resources/org/wildfly/extension/microprofile/config/smallrye/subsystem_1_0.xml
  microprofile/config-smallrye/src/test/resources/org/wildfly/extension/microprofile/config/smallrye/subsystem_1_0_reject_transformers.xml
Labels: deps-ok, ready-for-merge

#13411 [WFLY-13675] Make dependency on PicketBox optional for Batch subsystem.
  batch-jberet/pom.xml
  batch-jberet/src/main/java/org/wildfly/extension/batch/jberet/BatchSubsystemDefinition.java
  batch-jberet/src/main/java/org/wildfly/extension/batch/jberet/deployment/BatchEnvironmentProcessor.java
  batch-jberet/src/main/java/org/wildfly/extension/batch/jberet/deployment/BatchEnvironmentService.java
  feature-pack/src/main/resources/modules/system/layers/base/org/wildfly/extension/batch/jberet/main/module.xml
Labels: deps-ok, ready-for-merge

#13412 [WFLY-13677] Make dependency on PicketBox optional for the Weld subsystem.
  feature-pack/src/main/resources/modules/system/layers/base/org/jboss/as/weld/main/module.xml
  weld/subsystem/pom.xml
  weld/subsystem/src/main/java/org/jboss/as/weld/services/bootstrap/WeldSecurityServices.java
Labels: deps-ok, ready-for-merge

#13420 [WFLY-13688] Upgrade WildFly Core 13.0.0.Beta2
  pom.xml
Labels: deps-ok

#13429 [WFLY-13703] Increase the test coverage of LayersTestCase for the all…
  testsuite/layers/pom.xml
Labels: deps-ok

#13424 [WFLY-13676] Increase the test coverage of jpa and jpa-distribute gal…
  testsuite/integration/basic/pom.xml
  testsuite/integration/clustering/pom.xml
  testsuite/layers/pom.xml
Labels: deps-ok

#13421 WFLY-13689/WFLY-13690 Fix service name generation when components contain DOTs
  clustering/web/infinispan/src/main/java/org/wildfly/clustering/web/infinispan/routing/InfinispanRoutingProvider.java
  jpa/subsystem/src/main/java/org/jboss/as/jpa/processor/secondlevelcache/InfinispanCacheDeploymentListener.java
Labels: deps-ok, ready-for-merge

#13409 WFLY-13546 Upgrade smallrye-open-api to 2.0.3
  galleon-pack/pom.xml
  galleon-pack/src/main/resources/modules/system/layers/base/io/smallrye/openapi/main/module.xml
  galleon-pack/src/main/resources/modules/system/layers/base/org/wildfly/extension/microprofile/openapi-smallrye/main/module.xml
  microprofile/openapi-smallrye/pom.xml
  microprofile/openapi-smallrye/src/main/java/org/wildfly/extension/microprofile/openapi/deployment/OpenAPIHttpHandler.java
  microprofile/openapi-smallrye/src/main/java/org/wildfly/extension/microprofile/openapi/deployment/OpenAPIModelServiceConfigurator.java
  pom.xml
Labels: deps-ok

#13427 [WFLY-13701] Upgrade the jboss-parent pom from 35 to 37
  pom.xml
Labels: deps-ok

#13432 [WFLY-13703] Cleanup duplicate all-layers-jpa-distributed-provisionin…
  testsuite/layers/pom.xml
Labels: deps-ok

#13417 [WFLY-13683] Remove microprofile-metrics dependency from jpa, jpa-dis…
  ee-galleon-pack/src/main/resources/layers/standalone/jpa-distributed/layer-spec.xml
  ee-galleon-pack/src/main/resources/layers/standalone/jpa/layer-spec.xml
  ee-galleon-pack/src/main/resources/layers/standalone/web-clustering/layer-spec.xml
Labels: deps-ok, ready-for-merge

#13430 WFLY-13704 Change the deprecated org.jboss.remoting3 module to org.jb…
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/batch/chunk/ChunkPartitionTestCase.java
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/batch/deployment/JobControlTestCase.java
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/ee/concurrent/EEConcurrentManagementTestCase.java
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/ee/concurrent/ManagedExecutorServiceMetricsTestCase.java
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/ejb/container/interceptor/security/SwitchIdentityTestCase.java
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/ejb/interceptor/serverside/ServerInterceptorsTestCase.java
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/ejb/mdb/MDBTestCase.java
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/ejb/mdb/deliveryactive/MDBTestCase.java
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/ejb/mdb/ejb2x/MDB20TopicTestCase.java
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/ejb/stateful/timeout/StatefulTimeoutTestBase2.java
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/ejb/threadpool/Ejb3ThreadPoolBase.java
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/ejb/timerservice/suspend/TimerServiceSuspendTestCase.java
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/jca/datasource/DatasourceNonCcmTestCase.java
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/jca/poolattributes/DatasourceMaxPoolAttributeTestCase.java
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/jca/poolattributes/DatasourceMinPoolAttributeTestCase.java
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/jca/poolattributes/DatasourcePoolAttributesTestCase.java
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/jca/poolattributes/ResourceAdapterPoolAttributesTestCase.java
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/management/api/expression/ExpressionSubstitutionInContainerTestCase.java
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/messaging/jms/context/notclosinginjectedcontext/NotClosingInjectedContextTestCase.java
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/messaging/mgmt/metrics/ScheduledThreadPoolMetricsTestCase.java
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/messaging/mgmt/metrics/ThreadPoolMetricsTestCase.java
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/naming/RebindTestCase.java
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/naming/URLBindingTestCase.java
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/transaction/MaximumTimeoutTestCase.java
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/web/suspend/WebSuspendTestCase.java
  testsuite/integration/smoke/src/test/java/org/jboss/as/test/smoke/jms/JMSBridgeTest.java
Labels: deps-ok, ready-for-merge

#13415 [WFLY-13433] Improve capability support in EJB3 subsystem
  ejb3/src/main/java/org/jboss/as/ejb3/component/EJBComponentDescription.java
  ejb3/src/main/java/org/jboss/as/ejb3/component/messagedriven/MessageDrivenComponentDescription.java
  ejb3/src/main/java/org/jboss/as/ejb3/component/pool/StrictMaxPoolConfigService.java
  ejb3/src/main/java/org/jboss/as/ejb3/component/stateless/StatelessComponentDescription.java
  ejb3/src/main/java/org/jboss/as/ejb3/deployment/processors/EJBClientDescriptorMetaDataProcessor.java
  ejb3/src/main/java/org/jboss/as/ejb3/deployment/processors/EJBDefaultSecurityDomainProcessor.java
  ejb3/src/main/java/org/jboss/as/ejb3/deployment/processors/EjbIIOPDeploymentUnitProcessor.java
  ejb3/src/main/java/org/jboss/as/ejb3/deployment/processors/MdbDeliveryDependenciesProcessor.java
  ejb3/src/main/java/org/jboss/as/ejb3/deployment/processors/TimerServiceDeploymentProcessor.java
  ejb3/src/main/java/org/jboss/as/ejb3/logging/EjbLogger.java
  ejb3/src/main/java/org/jboss/as/ejb3/remote/RemotingProfileService.java
  ejb3/src/main/java/org/jboss/as/ejb3/subsystem/ApplicationSecurityDomainDefinition.java
  ejb3/src/main/java/org/jboss/as/ejb3/subsystem/CacheFactoryAdd.java
  ejb3/src/main/java/org/jboss/as/ejb3/subsystem/CacheFactoryResourceDefinition.java
  ejb3/src/main/java/org/jboss/as/ejb3/subsystem/ClusterPassivationStoreResourceDefinition.java
  ejb3/src/main/java/org/jboss/as/ejb3/subsystem/DatabaseDataStoreAdd.java
  ejb3/src/main/java/org/jboss/as/ejb3/subsystem/DatabaseDataStoreResourceDefinition.java
  ejb3/src/main/java/org/jboss/as/ejb3/subsystem/EJB3AsyncResourceDefinition.java
  ejb3/src/main/java/org/jboss/as/ejb3/subsystem/EJB3AsyncServiceAdd.java
  ejb3/src/main/java/org/jboss/as/ejb3/subsystem/EJB3IIOPAdd.java
  ejb3/src/main/java/org/jboss/as/ejb3/subsystem/EJB3IIOPResourceDefinition.java
  ejb3/src/main/java/org/jboss/as/ejb3/subsystem/EJB3RemoteResourceDefinition.java
  ejb3/src/main/java/org/jboss/as/ejb3/subsystem/EJB3RemoteServiceAdd.java
  ejb3/src/main/java/org/jboss/as/ejb3/subsystem/EJB3SubsystemAdd.java
  ejb3/src/main/java/org/jboss/as/ejb3/subsystem/EJB3SubsystemDefaultPoolWriteHandler.java
  ejb3/src/main/java/org/jboss/as/ejb3/subsystem/EJB3SubsystemModel.java
  ejb3/src/main/java/org/jboss/as/ejb3/subsystem/EJB3SubsystemRemove.java
  ejb3/src/main/java/org/jboss/as/ejb3/subsystem/EJB3SubsystemRootResourceDefinition.java
  ejb3/src/main/java/org/jboss/as/ejb3/subsystem/FileDataStoreAdd.java
  ejb3/src/main/java/org/jboss/as/ejb3/subsystem/FileDataStoreResourceDefinition.java
  ejb3/src/main/java/org/jboss/as/ejb3/subsystem/FilePassivationStoreAdd.java
  ejb3/src/main/java/org/jboss/as/ejb3/subsystem/FilePassivationStoreResourceDefinition.java
  ejb3/src/main/java/org/jboss/as/ejb3/subsystem/IdentityResourceDefinition.java
  ejb3/src/main/java/org/jboss/as/ejb3/subsystem/LegacyPassivationStoreResourceDefinition.java
  ejb3/src/main/java/org/jboss/as/ejb3/subsystem/MdbDeliveryGroupAdd.java
  ejb3/src/main/java/org/jboss/as/ejb3/subsystem/MdbDeliveryGroupResourceDefinition.java
  ejb3/src/main/java/org/jboss/as/ejb3/subsystem/PassivationStoreRemove.java
  ejb3/src/main/java/org/jboss/as/ejb3/subsystem/PassivationStoreResourceDefinition.java
  ejb3/src/main/java/org/jboss/as/ejb3/subsystem/RemotingProfileAdd.java
  ejb3/src/main/java/org/jboss/as/ejb3/subsystem/RemotingProfileChildResourceHandlerBase.java
  ejb3/src/main/java/org/jboss/as/ejb3/subsystem/RemotingProfileResourceChildWriteAttributeHandler.java
  ejb3/src/main/java/org/jboss/as/ejb3/subsystem/RemotingProfileResourceDefinition.java
  ejb3/src/main/java/org/jboss/as/ejb3/subsystem/StrictMaxPoolAdd.java
  ejb3/src/main/java/org/jboss/as/ejb3/subsystem/StrictMaxPoolDerivedSizeReadHandler.java
  ejb3/src/main/java/org/jboss/as/ejb3/subsystem/StrictMaxPoolResourceDefinition.java
  ejb3/src/main/java/org/jboss/as/ejb3/subsystem/StrictMaxPoolWriteHandler.java
  ejb3/src/main/java/org/jboss/as/ejb3/subsystem/TimerServiceAdd.java
  ejb3/src/main/java/org/jboss/as/ejb3/subsystem/TimerServiceResourceDefinition.java
  ejb3/src/test/java/org/jboss/as/ejb3/subsystem/Ejb3SubsystemUnitTestCase.java
  ejb3/src/test/java/org/jboss/as/ejb3/subsystem/Ejb3TransformersTestCase.java
  ejb3/src/test/resources/org/jboss/as/ejb3/subsystem/subsystem.xml
  feature-pack/src/main/resources/modules/system/layers/base/org/jboss/as/ejb3/main/module.xml
  testsuite/domain/src/test/resources/domain-configs/domain-standard-ee.xml
  testsuite/integration/multinode/src/test/java/org/jboss/as/test/multinode/ejb/timer/database/DatabaseTimerServiceMultiNodeExecutionDisabledTestCase.java
  testsuite/integration/multinode/src/test/java/org/jboss/as/test/multinode/ejb/timer/database/DatabaseTimerServiceMultiNodeTestCase.java
  testsuite/integration/multinode/src/test/java/org/jboss/as/test/multinode/ejb/timer/database/DatabaseTimerServiceRefreshTestCase.java
  testsuite/integration/multinode/src/test/java/org/jboss/as/test/multinode/remotecall/RemoteLocalCallProfileTestCase.java
  testsuite/mixed-domain/src/test/java/org/jboss/as/test/integration/domain/mixed/eap640/LegacyConfigAdjuster640.java
  transactions/src/main/java/org/jboss/as/txn/subsystem/TransactionSubsystemAdd.java
  transactions/src/main/java/org/jboss/as/txn/subsystem/TransactionSubsystemRootResourceDefinition.java
Labels: deps-ok

#13436 WFLY-13712 Remove Infinispan/EJB runtime handling made obsolete by capability references
  clustering/infinispan/extension/src/main/java/org/jboss/as/clustering/infinispan/subsystem/CacheContainerServiceHandler.java
  ejb3/src/main/java/org/jboss/as/ejb3/subsystem/EJB3RemoteServiceAdd.java
Labels: deps-ok

#13443 [WFLY-13725] The layer which brings in the security-manager subsystem is called "security-manager".
  docs/src/main/asciidoc/_admin-guide/Galleon_provisioning.adoc
Labels: deps-ok

#13445 Disable WebJPATestCase in the ts.layers profile pending resolution of…
  testsuite/integration/basic/pom.xml
Labels: deps-ok
