Repository wildfly/wildfly, pull requests merged in 2020-06, with the labels that each got.

#13335 [WFLY-13543] Upgrade RESTEasy to 3.12.1.Final
  pom.xml
Labels: 20.x, deps-ok

#13336 full-feature-pack-licenses: add missing license for com.github.fge:jackson-coreutils
  feature-pack/src/license/full-feature-pack-licenses.xml
Labels: 20.x, deps-ok

#13337 [WFLY-13550] Upgrade WildFly Core 12.0.0.Final
  pom.xml
Labels: 20.x, deps-ok

#13333 WFLY-13535 Upgrade smallrye-fault-tolerance to 4.2.1
  pom.xml
Labels: 20.x, deps-ok

#13332 WFLY-13527 Thousand of unauthorized requests in between balancer and …
  undertow/src/main/java/org/wildfly/extension/undertow/HttpInvokerHostService.java
Labels: 20.x, deps-ok

#13339 [WFLY-13522] Upgrade jboss-ejb-client to 4.0.33.Final
  pom.xml
Labels: 20.x, deps-ok

#13338 [WFLY-13549] Apply class filtering to remote EJB and Naming invocations
  ejb3/src/main/java/org/jboss/as/ejb3/iiop/EjbIIOPService.java
  ejb3/src/main/java/org/jboss/as/ejb3/logging/EjbLogger.java
  ejb3/src/main/java/org/jboss/as/ejb3/remote/EJBRemoteConnectorService.java
  ejb3/src/main/java/org/jboss/as/ejb3/remote/http/EJB3RemoteHTTPService.java
  ejb3/src/main/java/org/jboss/as/ejb3/subsystem/EJB3RemoteServiceAdd.java
  ejb3/src/main/java/org/jboss/as/ejb3/subsystem/EJB3SubsystemAdd.java
  ejb3/src/main/java/org/jboss/as/ejb3/subsystem/FilterSpecClassResolverFilter.java
  ejb3/src/test/java/org/jboss/as/ejb3/subsystem/FilterSpecClassResolverFilterUnitTestCase.java
  naming/src/main/java/org/jboss/as/naming/remote/HttpRemoteNamingServerService.java
  naming/src/main/java/org/jboss/as/naming/remote/RemoteNamingServerService.java
  pom.xml
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/ejb/remote/requestdeserialization/AbstactUnmarshallingFilterTestCase.java
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/ejb/remote/requestdeserialization/Request.java
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/ejb/remote/requestdeserialization/Response.java
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/ejb/remote/requestdeserialization/UnmarshallingFilterDisabledTestCase.java
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/ejb/remote/requestdeserialization/UnmarshallingFilterTestCase.java
Labels: 20.x, deps-ok

#13345 [WFLY-13421] / [WFLY-13553] JSF Component Upgrades
  pom.xml
Labels: 20.x, deps-ok

#13351 [WFLY-13558] Upgrade WildFly Core 12.0.1.Final
  pom.xml
Labels: 20.x, Blocker, deps-ok

#13346 WFLY-10173 Fix EjbInvocationStatisticsTestCase#testSingletonWaitTime …
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/ejb/management/deployments/EjbInvocationStatisticsTestCase.java
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/ejb/management/deployments/WaitTimeInterface.java
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/ejb/management/deployments/WaitTimeSingletonBean.java
Labels: 20.x, deps-ok

#13321 [WFLY-13508] Fix layer name for naming, it should be 'naming' instead …
  servlet-galleon-pack/src/main/resources/layers/standalone/naming/layer-spec.xml
Labels: deps-ok, ready-for-merge

#13322 [WFLY-13422] Make some org.jboss.as.naming module dependencies option…
  naming/src/main/java/org/jboss/as/naming/subsystem/RemoteNamingResourceDefinition.java
  naming/src/test/java/org/jboss/as/naming/subsystem/NamingSubsystemTestCase.java
  servlet-feature-pack/src/main/resources/modules/system/layers/base/org/jboss/as/naming/main/module.xml
Labels: 21.x, deps-ok, ready-for-merge

#13344 WFLY-13555 Upgrade jgroups-azure to 1.3.0.Final
  pom.xml
Labels: deps-changed, ready-for-merge

#13352 WFLY-13561 Upgrade jberet-core from 1.3.6.Final to 1.3.7.Final
  pom.xml
Labels: deps-ok, ready-for-merge

#13354 WFLY-13566 Ensure that Jandex indexes are released from JPA deployment memory after deployment completes
  jpa/subsystem/src/main/java/org/jboss/as/jpa/service/PersistenceUnitServiceImpl.java
Labels: deps-ok, ready-for-merge

#13328 WFLY-11767 Remove unused dependencies from org.jboss.as.connector
  feature-pack/src/main/resources/modules/system/layers/base/org/jboss/as/connector/main/module.xml
Labels: 21.x, deps-ok, ready-for-merge

#13359 [WFLY-13576] Upgrade WildFly Galleon Plugins from 4.2.6.Final to 4.2.8.Final
  pom.xml
Labels: deps-ok

#13357 [WFLY-13567] Do not run the MPScriptTestCase if the example configura…
  testsuite/integration/manualmode/src/test/java/org/wildfly/test/manual/management/MPScriptTestCase.java
Labels: deps-ok

#13358 [WFLY-10173][20.x] Fix EjbInvocationStatisticsTestCase#testSingletonWaitTime
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/ejb/management/deployments/EjbInvocationStatisticsTestCase.java
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/ejb/management/deployments/WaitTimeInterface.java
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/ejb/management/deployments/WaitTimeSingletonBean.java
Labels: 20.x, deps-ok

#13353 WFLY-13557 Clustering TS: Support for test execution parallelization …
  docs/src/main/asciidoc/_testsuite/WildFly_Testsuite_Overview.adoc
  testsuite/integration/clustering/pom.xml
Labels: deps-ok, ready-for-merge

#13195 [WFLY-13345] Ignore classloading failures when processing component i…
  ee/src/main/java/org/jboss/as/ee/component/deployers/InterceptorAnnotationProcessor.java
Labels: deps-ok

#13232 [WFLY-13392] WFSM000001: Permission check failed ... FilePermission when Security Manager enabled and Web App tries to forward to jsp
  testsuite/integration/secman/src/test/java/org/jboss/as/testsuite/integration/secman/ForwardJSPTestCase.java
  testsuite/integration/secman/src/test/java/org/jboss/as/testsuite/integration/secman/servlets/ForwardServlet.java
  testsuite/integration/secman/src/test/java/org/jboss/as/testsuite/integration/secman/servlets/forward.jsp
Labels: deps-ok, ready-for-merge

#13241 Test Case for the issue WFLY-13375, if connection factory or JMS destination is configured for third party resource adapter
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/jca/deployment/JndiViewOperationJMSTestCase.java
Labels: deps-ok, ready-for-merge

#13249 [WFLY-13358] Tests for WFCORE-4950 - Regression: Legacy Ldap Realm securing EJB with JDK8 not working
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/ejb/security/LdapLegacyTestCase.java
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/security/loginmodules/LdapExtLDAPServerSetupTask.java
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/security/loginmodules/LdapExtLoginModuleTestCase.ldif
  testsuite/integration/basic/src/test/resources/org/jboss/as/test/integration/ejb/security/LdapLegacyTestCase-ejb-jar.xml
  testsuite/integration/basic/src/test/resources/org/jboss/as/test/integration/ejb/security/LdapLegacyTestCase-jboss-ejb3.xml
Labels: core-upgrade-needed, deps-ok, ready-for-merge

#13269 [WFLY-13244]: MicroProfile open-tracing should expliciely depends on microprofile-config.
  feature-pack/src/main/resources/modules/system/layers/base/org/wildfly/extension/microprofile/opentracing-smallrye/main/module.xml
  microprofile/opentracing-extension/pom.xml
  microprofile/opentracing-extension/src/main/java/org/wildfly/extension/microprofile/opentracing/SubsystemDefinition.java
  microprofile/opentracing-smallrye/src/main/java/org/wildfly/microprofile/opentracing/smallrye/TracerDynamicFeature.java
  testsuite/integration/basic/src/test/java/org/wildfly/test/integration/microprofile/config/smallrye/SubsystemConfigSourceTask.java
  testsuite/integration/basic/src/test/java/org/wildfly/test/integration/microprofile/opentracing/ConfigHttpPathTask.java
  testsuite/integration/basic/src/test/java/org/wildfly/test/integration/microprofile/opentracing/ResourceTracedTestCase.java
  testsuite/integration/basic/src/test/java/org/wildfly/test/integration/microprofile/opentracing/ResourceWithCDITestCase.java
  testsuite/integration/basic/src/test/java/org/wildfly/test/integration/microprofile/opentracing/ResourceWithCustomOperationNameBeanTestCase.java
Labels: deps-ok, ready-for-merge

#13277 [WFLY-13432] Provide capability for Undertow HTTP_UPGRADE_REGISTRY
  legacy/messaging/src/test/java/org/jboss/as/messaging/test/MigrateTestCase.java
  messaging-activemq/src/main/java/org/wildfly/extension/messaging/activemq/Capabilities.java
  messaging-activemq/src/main/java/org/wildfly/extension/messaging/activemq/HTTPAcceptorAdd.java
  messaging-activemq/src/main/java/org/wildfly/extension/messaging/activemq/HTTPAcceptorDefinition.java
  messaging-activemq/src/main/java/org/wildfly/extension/messaging/activemq/HTTPUpgradeService.java
  messaging-activemq/src/main/java/org/wildfly/extension/messaging/activemq/MessagingServices.java
  messaging-activemq/src/main/java/org/wildfly/extension/messaging/activemq/ServerAdd.java
  mod_cluster/undertow/src/test/java/org/wildfly/mod_cluster/undertow/UndertowConnectorTestCase.java
  mod_cluster/undertow/src/test/java/org/wildfly/mod_cluster/undertow/UndertowEngineTestCase.java
  undertow/src/main/java/org/wildfly/extension/undertow/AjpListenerAdd.java
  undertow/src/main/java/org/wildfly/extension/undertow/AjpListenerResourceDefinition.java
  undertow/src/main/java/org/wildfly/extension/undertow/AjpListenerService.java
  undertow/src/main/java/org/wildfly/extension/undertow/Capabilities.java
  undertow/src/main/java/org/wildfly/extension/undertow/HttpListenerAdd.java
  undertow/src/main/java/org/wildfly/extension/undertow/HttpListenerResourceDefinition.java
  undertow/src/main/java/org/wildfly/extension/undertow/HttpListenerService.java
  undertow/src/main/java/org/wildfly/extension/undertow/HttpsListenerAdd.java
  undertow/src/main/java/org/wildfly/extension/undertow/HttpsListenerResourceDefinition.java
  undertow/src/main/java/org/wildfly/extension/undertow/HttpsListenerService.java
  undertow/src/main/java/org/wildfly/extension/undertow/ListenerResourceDefinition.java
  undertow/src/test/java/org/wildfly/extension/undertow/AbstractUndertowSubsystemTestCase.java
Labels: deps-ok, ready-for-merge

#13288 [WFLY-13471]:Warn the ws deployment packaged with JAXP implementation
  webservices/server-integration/src/main/java/org/jboss/as/webservices/deployers/WSLibraryFilterProcessor.java
  webservices/server-integration/src/main/java/org/jboss/as/webservices/logging/WSLogger.java
Labels: deps-ok, ready-for-merge

#13316 [WFLY-13423] Remove the uses of AbstractOutboundConnectionService fro…
  ejb3/pom.xml
  ejb3/src/main/java/org/jboss/as/ejb3/deployment/processors/EJBClientDescriptorMetaDataProcessor.java
  ejb3/src/main/java/org/jboss/as/ejb3/deployment/processors/EjbClientContextSetupProcessor.java
  ejb3/src/main/java/org/jboss/as/ejb3/remote/RemotingProfileService.java
  ejb3/src/main/java/org/jboss/as/ejb3/subsystem/EJB3RemoteResourceDefinition.java
  ejb3/src/main/java/org/jboss/as/ejb3/subsystem/EJB3SubsystemXMLPersister.java
  ejb3/src/main/java/org/jboss/as/ejb3/subsystem/RemotingProfileAdd.java
  feature-pack/src/main/resources/modules/system/layers/base/org/jboss/as/ejb3/main/module.xml
Labels: 21.x, deps-ok, ready-for-merge

#13355 WFLY-13569 Increase timeout multiplier in MP FT TCK testsuite; Interm…
  testsuite/integration/microprofile-tck/fault-tolerance/pom.xml
Labels: deps-ok, ready-for-merge

#13362 [WFLY-13581]: The multicast queue stats are not correct.
  messaging-activemq/src/main/java/org/wildfly/extension/messaging/activemq/jms/DestinationConfiguration.java
Labels: deps-ok, ready-for-merge

#13364 [WFLY-13584] Upgrade the minimum Maven version to 3.6.0 and default t…
  .mvn/jvm.config
  .mvn/maven.config
  .mvn/wrapper/maven-wrapper.properties
  README.md
  pom.xml
Labels: deps-ok, ready-for-merge

#13366 [WFLY-13572] / [WFLY-13573] JSF Component Upgrades
  pom.xml
Labels: deps-ok, ready-for-merge

#13368 WFLY-13590, WFLY-13591 JGroups subsystem fixes
  clustering/jgroups/extension/pom.xml
  clustering/jgroups/extension/src/main/java/org/jboss/as/clustering/jgroups/ManagedSocketFactory.java
  clustering/jgroups/extension/src/main/java/org/jboss/as/clustering/jgroups/subsystem/TransportConfigurationServiceConfigurator.java
  clustering/jgroups/extension/src/main/resources/jgroups-defaults.xml
Labels: deps-ok, ready-for-merge

#13369 [WFLY-13583] Remove Zanata configuration as the service is no longer …
  .gitignore
  checkstyle-suppressions.xml
  pom.xml
  zanata.xml
Labels: deps-ok, ready-for-merge

#13367 [WFLY-13572] / [WFLY-13573] [20.x] JSF Component Upgrades
  pom.xml
Labels: 20.x, deps-ok

#13371 servlet-feature-pack-licenses: merge org.wildfly.core:wildfly-event-logger licenses in one entry only
  servlet-feature-pack/src/license/servlet-feature-pack-licenses.xml
Labels: deps-ok

#13376 [WFLY-13605] fix licenses in full-feature-pack-licenses.xml
  feature-pack/src/license/full-feature-pack-licenses.xml
Labels: deps-ok, ready-for-merge

#13384 [20.x] WFLY-13590 JGroups subsystem logs "version is missing in the configuration file" warning on startup
  clustering/jgroups/extension/pom.xml
  clustering/jgroups/extension/src/main/resources/jgroups-defaults.xml
Labels: deps-ok

#13385 [WFLY-13618] Upgrade WildFly Core 13.0.0.Beta1
  feature-pack/src/main/resources/configuration/domain/template.xml
  feature-pack/src/main/resources/configuration/host/host-master.xml
  feature-pack/src/main/resources/configuration/host/host-slave.xml
  feature-pack/src/main/resources/configuration/host/host.xml
  feature-pack/src/main/resources/configuration/standalone/template.xml
  feature-pack/src/main/resources/content/appclient/configuration/appclient.xml
  feature-pack/src/main/resources/content/docs/examples/configs/standalone-minimalistic.xml
  pom.xml
  servlet-feature-pack/src/main/resources/configuration/domain/template.xml
  servlet-feature-pack/src/main/resources/configuration/host/host-master.xml
  servlet-feature-pack/src/main/resources/configuration/host/host-slave.xml
  servlet-feature-pack/src/main/resources/configuration/host/host.xml
  servlet-feature-pack/src/main/resources/configuration/standalone/template.xml
  testsuite/domain/src/test/resources/domain-configs/domain-minimal.xml
  testsuite/domain/src/test/resources/domain-configs/domain-rbac.xml
  testsuite/domain/src/test/resources/domain-configs/domain-respawn.xml
  testsuite/domain/src/test/resources/domain-configs/domain-standard-ee.xml
  testsuite/domain/src/test/resources/domain-configs/domain-standard.xml
  testsuite/domain/src/test/resources/host-configs/host-failover1.xml
  testsuite/domain/src/test/resources/host-configs/host-failover2.xml
  testsuite/domain/src/test/resources/host-configs/host-failover3.xml
  testsuite/domain/src/test/resources/host-configs/host-master-elytron.xml
  testsuite/domain/src/test/resources/host-configs/host-master-no-http.xml
  testsuite/domain/src/test/resources/host-configs/host-master-no-local.xml
  testsuite/domain/src/test/resources/host-configs/host-master-rbac-properties.xml
  testsuite/domain/src/test/resources/host-configs/host-master-rbac.xml
  testsuite/domain/src/test/resources/host-configs/host-master.xml
  testsuite/domain/src/test/resources/host-configs/host-secrets.xml
  testsuite/domain/src/test/resources/host-configs/host-slave-discovery-options.xml
  testsuite/domain/src/test/resources/host-configs/host-slave-elytron.xml
  testsuite/domain/src/test/resources/host-configs/host-slave-rbac-properties.xml
  testsuite/domain/src/test/resources/host-configs/host-slave-rbac.xml
  testsuite/domain/src/test/resources/host-configs/host-slave.xml
  testsuite/domain/src/test/resources/host-configs/respawn-master.xml
  testsuite/mixed-domain/src/test/resources/legacy-templates/test-template.xml
  testsuite/mixed-domain/src/test/resources/master-config/domain-minimal.xml
  testsuite/mixed-domain/src/test/resources/master-config/host-master-elytron.xml
  testsuite/mixed-domain/src/test/resources/master-config/host.xml
Labels: deps-changed, ready-for-merge

#12626 [WFLY-12537] Incoming RunAsPrincipal is not being propagated to an unsecured EJB
  ejb3/src/main/java/org/jboss/as/ejb3/component/EJBComponent.java
  testsuite/integration/basic/src/test/java/org/wildfly/test/integration/weld/builtinBeans/BeanWithInjectedPrincipal.java
  testsuite/integration/basic/src/test/java/org/wildfly/test/integration/weld/builtinBeans/BeanWithPrincipalFromEJBContext.java
  testsuite/integration/basic/src/test/java/org/wildfly/test/integration/weld/builtinBeans/BeanWithSecuredPrincipal.java
  testsuite/integration/basic/src/test/java/org/wildfly/test/integration/weld/builtinBeans/CallerWithIdentity.java
  testsuite/integration/basic/src/test/java/org/wildfly/test/integration/weld/builtinBeans/InjectPrincipalTestCase.java
  testsuite/integration/basic/src/test/resources/org/wildfly/test/integration/weld/builtinBeans/jboss-ejb3.xml
Labels: deps-ok, ready-for-merge

#13361 [WFLY-13579] adjust testsuite waiting times with the timeout factor
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/ejb/management/deployments/EjbInvocationStatisticsTestCase.java
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/ejb/management/deployments/EjbJarRuntimeResourceTestBase.java
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/ejb/management/deployments/WaitTimeSingletonBean.java
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/ejb/mdb/JMSMessagingUtil.java
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/ejb/mdb/MDBTestCase.java
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/ejb/mdb/cdi/MDBCdiIntegrationTestCase.java
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/ejb/mdb/cdi/MDBRAScopeCdiIntegrationTestCase.java
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/ejb/mdb/messagedrivencontext/SetMessageDrivenContextInvocationTestCase.java
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/ejb/mdb/messagelistener/MessageListenerInClassHierarchyTestCase.java
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/ejb/mdb/objectmessage/unit/ObjectMessageTestCase.java
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/ejb/mdb/resourceadapter/ConfiguredResourceAdapterNameTestCase.java
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/ejb/mdb/resourceadapter/ResourceAdapterNameTestCase.java
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/ejb/singleton/dependson/mdb/MDBWhichDependsOnTestCase.java
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/management/cli/SecurityAuthCommandsTestCase.java
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/management/cli/SecurityCommandsTestCase.java
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/messaging/jms/context/ScopedInjectedJMSContextTestCase.java
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/messaging/jms/context/auxiliary/BeanManagedMessageConsumer.java
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/security/auditing/SecurityAuditingTestCase.java
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/weld/context/application/lifecycle/ApplicationContextLifecycleTestCase.java
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/weld/context/application/lifecycle/TestResultsBean.java
  testsuite/integration/ws/src/test/java/org/jboss/as/test/integration/ws/cdi/CdiJsfWebServicesTestCase.java
  testsuite/shared/src/main/java/org/jboss/as/test/shared/ServerReload.java
Labels: deps-ok, ready-for-merge

#13372 [WFLY-13606] socket-level keepalive flag in OpenJDK ORB connections
  iiop-openjdk/src/main/java/org/wildfly/iiop/openjdk/security/SocketFactoryBase.java
Labels: ready-for-merge

#13373 [WFLY-13596] Add missing exclusions for dependencies artifacts
  microprofile/fault-tolerance-smallrye/extension/pom.xml
  pom.xml
Labels: deps-ok, ready-for-merge

#13374 WFLY-13603 Handle case where cache configuration has not defined a DataContainerConfiguration.
  clustering/infinispan/spi/src/main/java/org/wildfly/clustering/infinispan/spi/DataContainerFactory.java
Labels: deps-ok, ready-for-merge

#13378 WFLY-13592 [GSS] (7.3.z) jndi-view doen't show values for EJB in java:jboss/exported
  ejb3/src/main/java/org/jboss/as/ejb3/deployment/processors/EjbJndiBindingsDeploymentUnitProcessor.java
Labels: deps-ok, ready-for-merge

#13383 [WFLY-13614] Upgrade Artemis Native to 1.0.2
  pom.xml
Labels: deps-ok, ready-for-merge

#13375 [20.x] WFLY-13603 Handle case where cache configuration has not defined a DataContainerConfiguration.
  clustering/infinispan/spi/src/main/java/org/wildfly/clustering/infinispan/spi/DataContainerFactory.java
Labels: 20.x, deps-ok

#13387 Couple of documentation fixes (grammar, style, markdown, etc) in Elyt…
  docs/src/main/asciidoc/WildFly_Elytron_Security.adoc
  docs/src/main/asciidoc/_elytron/Audit.adoc
  docs/src/main/asciidoc/_elytron/Bearer_Token_Authorization.adoc
  docs/src/main/asciidoc/_elytron/Client_Authentication_with_Elytron_Client.adoc
  docs/src/main/asciidoc/_elytron/Credential_Store.adoc
  docs/src/main/asciidoc/_elytron/Custom_Components.adoc
  docs/src/main/asciidoc/_elytron/Elytron_Subsystem.adoc
  docs/src/main/asciidoc/_elytron/General_Elytron_Architecture.adoc
  docs/src/main/asciidoc/_elytron/Passwords.adoc
  docs/src/main/asciidoc/_elytron/Subsystem_Component_Documentation.adoc
  docs/src/main/asciidoc/_elytron/Using_the_Elytron_Subsystem.adoc
  docs/src/main/asciidoc/_elytron/Web_Single_Sign_On.adoc
Labels: deps-ok

#13380 [WFLY-13609] : Disable microprofile tests when XP dist is not used.
  testsuite/integration/manualmode/pom.xml
Labels: deps-ok
