Repository wildfly/wildfly, pull requests merged in 2021-01, with the labels that each got.

#13833 [WFLY-14243] New JAXB tests in WFLY-13968 fails on ee9 profile
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/jaxb/unit/JAXBContextSystemPropCustomTestCase.java
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/jaxb/unit/JAXBContextSystemPropInternalTestCase.java
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/jaxb/unit/JAXBContextTestBase.java
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/jaxb/unit/JAXBContextUsingPropertiesTestCase.java
Labels: deps-ok

#13810 WFLY-14110 Distributed session manager reports HttpSession.getLastAccessedTime() incorrectly
  clustering/ee/cache/src/main/java/org/wildfly/clustering/ee/cache/ConcurrentManager.java
  clustering/ee/hotrod/src/main/java/org/wildfly/clustering/ee/hotrod/RemoteCacheEntryMutator.java
  clustering/ee/hotrod/src/main/java/org/wildfly/clustering/ee/hotrod/RemoteCacheMutatorFactory.java
  clustering/web/cache/src/main/java/org/wildfly/clustering/web/cache/session/CompositeSession.java
  clustering/web/cache/src/main/java/org/wildfly/clustering/web/cache/session/CompositeSessionMetaData.java
  clustering/web/cache/src/main/java/org/wildfly/clustering/web/cache/session/ImmutableSessionAccessMetaData.java
  clustering/web/cache/src/main/java/org/wildfly/clustering/web/cache/session/ImmutableSessionCreationMetaData.java
  clustering/web/cache/src/main/java/org/wildfly/clustering/web/cache/session/InvalidatableSessionMetaData.java
  clustering/web/cache/src/main/java/org/wildfly/clustering/web/cache/session/MutableSessionAccessMetaData.java
  clustering/web/cache/src/main/java/org/wildfly/clustering/web/cache/session/MutableSessionCreationMetaData.java
  clustering/web/cache/src/main/java/org/wildfly/clustering/web/cache/session/SessionAccessMetaData.java
  clustering/web/cache/src/main/java/org/wildfly/clustering/web/cache/session/SessionAccessMetaDataExternalizer.java
  clustering/web/cache/src/main/java/org/wildfly/clustering/web/cache/session/SessionAttributes.java
  clustering/web/cache/src/main/java/org/wildfly/clustering/web/cache/session/SessionCreationMetaData.java
  clustering/web/cache/src/main/java/org/wildfly/clustering/web/cache/session/SimpleImmutableSessionMetaData.java
  clustering/web/cache/src/main/java/org/wildfly/clustering/web/cache/session/SimpleSessionAccessMetaData.java
  clustering/web/cache/src/main/java/org/wildfly/clustering/web/cache/session/SimpleSessionCreationMetaData.java
  clustering/web/cache/src/main/java/org/wildfly/clustering/web/cache/session/fine/FineImmutableSessionAttributes.java
  clustering/web/cache/src/main/java/org/wildfly/clustering/web/cache/session/fine/FineSessionAttributes.java
  clustering/web/cache/src/main/resources/org.wildfly.clustering.web.cache.session.proto
  clustering/web/cache/src/test/java/org/wildfly/clustering/web/cache/session/CompositeSessionMetaDataTestCase.java
  clustering/web/cache/src/test/java/org/wildfly/clustering/web/cache/session/CompositeSessionTestCase.java
  clustering/web/cache/src/test/java/org/wildfly/clustering/web/cache/session/ImmutableSessionActivationNotifierTestCase.java
  clustering/web/cache/src/test/java/org/wildfly/clustering/web/cache/session/SessionAccessMetaDataExternalizerTestCase.java
  clustering/web/hotrod/src/main/java/org/wildfly/clustering/web/hotrod/session/HotRodSessionMetaDataFactory.java
  clustering/web/hotrod/src/main/java/org/wildfly/clustering/web/hotrod/session/fine/FineSessionAttributesFactory.java
  clustering/web/infinispan/src/main/java/org/wildfly/clustering/web/infinispan/session/InfinispanSessionMetaDataFactory.java
  clustering/web/infinispan/src/main/java/org/wildfly/clustering/web/infinispan/session/SessionExpirationScheduler.java
  clustering/web/infinispan/src/main/java/org/wildfly/clustering/web/infinispan/session/fine/FineSessionAttributesFactory.java
  clustering/web/infinispan/src/test/java/org/wildfly/clustering/web/infinispan/session/SessionExpirationSchedulerTestCase.java
  clustering/web/spi/src/main/java/org/wildfly/clustering/web/session/ImmutableSessionMetaData.java
  clustering/web/spi/src/main/java/org/wildfly/clustering/web/session/SessionMetaData.java
  clustering/web/undertow/src/main/java/org/wildfly/clustering/web/undertow/session/DistributableImmutableSession.java
  clustering/web/undertow/src/main/java/org/wildfly/clustering/web/undertow/session/DistributableSession.java
  clustering/web/undertow/src/main/java/org/wildfly/clustering/web/undertow/session/UndertowSpecificationProvider.java
  clustering/web/undertow/src/test/java/org/wildfly/clustering/web/undertow/session/DistributableSessionManagerTestCase.java
  clustering/web/undertow/src/test/java/org/wildfly/clustering/web/undertow/session/DistributableSessionTestCase.java
  clustering/web/undertow/src/test/java/org/wildfly/clustering/web/undertow/session/UndertowHttpSessionFactoryTestCase.java
  clustering/web/undertow/src/test/java/org/wildfly/clustering/web/undertow/session/UndertowSessionExpirationListenerTestCase.java
  testsuite/integration/clustering/src/test/java/org/jboss/as/test/clustering/cluster/web/AbstractSessionActivationTestCase.java
  testsuite/integration/clustering/src/test/java/org/jboss/as/test/clustering/cluster/web/event/SessionActivationServlet.java
Labels: deps-ok

#13832 [WFLY-14208] Group wildfly-galleon-pack Galleon layers on testsuite/l…
  testsuite/layers/pom.xml
Labels: deps-ok

#13849 [WFLY-13706] Add documentation describing how to use the Keycloak adapters with WildFly Elytron.
  docs/src/main/asciidoc/WildFly_Elytron_Security.adoc
  docs/src/main/asciidoc/_elytron/KeyCloak_Integration.adoc
  docs/src/main/asciidoc/_elytron/Keycloak_Integration.adoc
Labels: 22.x, Feature-Docs, deps-ok

#13859 [WFLY-14628] Upgrade WildFly Core 14.0.0.Beta5
  pom.xml
Labels: deps-ok

#13847 WFLY-14260 Fix ClassCastException during expiration scheduling
  clustering/web/infinispan/src/main/java/org/wildfly/clustering/web/infinispan/session/InfinispanSessionManagerFactoryServiceConfigurator.java
Labels: deps-ok

#13852 [WFLY-14265] Upgrade Hibernate Validator to 6.0.22
  pom.xml
Labels: deps-ok

#13853 [WFLY-14264] Update the default Elytron KeyStore type to JKS in the Elytron subsystem documentation
  docs/src/main/asciidoc/_elytron/Elytron_Subsystem.adoc
Labels: 22.x, Blocker, deps-ok

#13848 [WFLY-14271] timed object id throws null when tried to be restored
  ejb3/src/main/java/org/jboss/as/ejb3/logging/EjbLogger.java
  ejb3/src/main/java/org/jboss/as/ejb3/timerservice/TimerServiceImpl.java
  ejb3/src/main/java/org/jboss/as/ejb3/timerservice/persistence/TimerPersistence.java
  ejb3/src/main/java/org/jboss/as/ejb3/timerservice/persistence/database/DatabaseTimerPersistence.java
Labels: deps-ok

#13855 [WFLY-14230] - Integrate MP OpenTracing 2.0 into EAP
  pom.xml
  testsuite/integration/microprofile-tck/opentracing/pom.xml
  testsuite/integration/microprofile-tck/opentracing/src/test/java/io/smallrye/opentracing/arquillian/DeploymentProcessor.java
  testsuite/integration/microprofile-tck/opentracing/src/test/resources/io/smallrye/opentracing/arquillian/jboss-deployment-structure.xml
  testsuite/integration/microprofile/src/test/java/org/wildfly/test/integration/microprofile/opentracing/SimpleRestClientTestCase.java
  testsuite/integration/microprofile/src/test/java/org/wildfly/test/integration/microprofile/opentracing/SubsystemConfigurationTestCase.java
  testsuite/integration/microprofile/src/test/java/org/wildfly/test/integration/microprofile/opentracing/application/TracerConfigurationApplication.java
Labels: Feature, MP-4.0

#13865 [WFLY-14262] Avoid running microprofile TCK related plugin executions…
  testsuite/domain/src/test/resources/domain-configs/domain-standard-ee.xml
  testsuite/domain/src/test/resources/domain-configs/domain-standard.xml
  testsuite/integration/manualmode/src/test/java/org/jboss/as/test/manualmode/parse/ParseAndMarshalModelsTestCase.java
  testsuite/integration/microprofile-tck/fault-tolerance/pom.xml
  testsuite/integration/microprofile-tck/jwt/pom.xml
  testsuite/integration/microprofile-tck/openapi/pom.xml
  testsuite/integration/microprofile-tck/pom.xml
  testsuite/integration/microprofile-tck/rest-client/pom.xml
  testsuite/layers/pom.xml
Labels: deps-ok

#13868 Fix for WFLY-14279, Failing bootable EE9 microprofile-tck tests
  testsuite/integration/microprofile-tck/config/pom.xml
  testsuite/integration/microprofile-tck/health/pom.xml
  testsuite/integration/microprofile-tck/metrics/pom.xml
  testsuite/integration/microprofile-tck/opentracing/pom.xml
  testsuite/integration/microprofile-tck/rest-client/pom.xml
Labels: deps-ok

#13869 Fix for WFLY-14279, Failing EE9 microprofile-tck tests
  testsuite/integration/microprofile-tck/config/pom.xml
  testsuite/integration/microprofile-tck/health/pom.xml
  testsuite/integration/microprofile-tck/metrics/pom.xml
  testsuite/integration/microprofile-tck/opentracing/pom.xml
  testsuite/integration/microprofile-tck/rest-client/pom.xml
Labels: deps-ok

#13867 [WFLY-14278] Upgrade WildFly Core to 14.0.0.Final
  pom.xml
Labels: 22.x, Blocker, deps-ok

#13850 [WFLY-14261] Integrate MP Health 3.0 into EAP
  microprofile/health-smallrye/src/main/java/org/wildfly/extension/microprofile/health/MicroProfileHealthReporter.java
  microprofile/health-smallrye/src/main/java/org/wildfly/extension/microprofile/health/MicroProfileHealthReporterService.java
  microprofile/health-smallrye/src/main/java/org/wildfly/extension/microprofile/health/deployment/CDIExtension.java
  pom.xml
  testsuite/integration/microprofile/src/test/java/org/wildfly/test/integration/microprofile/health/HealthConfigSource.java
  testsuite/integration/microprofile/src/test/java/org/wildfly/test/integration/microprofile/health/MicroProfileHealthApplicationLiveHTTPEndpointTestCase.java
  testsuite/integration/microprofile/src/test/java/org/wildfly/test/integration/microprofile/health/MicroProfileHealthApplicationLiveOperationTestCase.java
  testsuite/integration/microprofile/src/test/java/org/wildfly/test/integration/microprofile/health/MicroProfileHealthApplicationLiveTestBase.java
  testsuite/integration/microprofile/src/test/java/org/wildfly/test/integration/microprofile/health/MyLiveProbe.java
  testsuite/integration/microprofile/src/test/java/org/wildfly/test/integration/microprofile/health/TestApplication.java
Labels: Feature, MP-4.0

#13873 WFLY-14283 Allow Infinispan to resolve exceptions containing JBoss Marshalling TraceInformation
  ee-feature-pack/common/src/main/resources/modules/system/layers/base/org/infinispan/main/module.xml
Labels: deps-ok

#13878 Fix for WFLY-14290, Missing microprofile-rest-client in doc
  docs/src/main/asciidoc/_galleon/Galleon_layers.adoc
Labels: deps-ok

#13881 [22.x] Fix for WFLY-14290, Missing microprofile-rest-client in doc
  docs/src/main/asciidoc/_galleon/Galleon_layers.adoc
Labels: 22.x

#13884 [WFLY-14291] Document the microprofile-opentracing layer
  docs/src/main/asciidoc/_galleon/Galleon_layers.adoc
Labels: deps-ok

#13892 Update Getting_Started_Guide.adoc
  docs/src/main/asciidoc/Getting_Started_Guide.adoc
Labels: deps-ok

#13889 Fix for WFLY-14294, Upgrade tests to bootable JAR 3.0.0.Final
  pom.xml
Labels: deps-ok

#13890 [22.x] Fix for WFLY-14294, Upgrade tests to bootable JAR 3.0.0.Final
  pom.xml
Labels: 22.x

#13875 WFLY-14286 Infinispan should enable JMX registration when jmx capability is present
  clustering/infinispan/extension/src/main/java/org/jboss/as/clustering/infinispan/subsystem/GlobalConfigurationServiceConfigurator.java
  clustering/infinispan/extension/src/main/java/org/jboss/as/clustering/infinispan/subsystem/remote/RemoteCacheContainerConfigurationServiceConfigurator.java
Labels: deps-ok

#13882 [22.x] WFLY-14286 Infinispan should enable JMX registration when jmx capability is present
  clustering/infinispan/extension/src/main/java/org/jboss/as/clustering/infinispan/subsystem/GlobalConfigurationServiceConfigurator.java
  clustering/infinispan/extension/src/main/java/org/jboss/as/clustering/infinispan/subsystem/remote/RemoteCacheContainerConfigurationServiceConfigurator.java
Labels: 22.x

#13876 [WFLY-14282] HostExcludesTestCase fails when using wildfly-ee-galleon…
  testsuite/domain/pom.xml
  testsuite/domain/src/test/java/org/jboss/as/test/integration/domain/HostExcludesTestCase.java
Labels: deps-ok

#13866 [WFLY-14238] FaceletsResourceResolver annotation is not taken into account
  jsf/injection/src/main/java/org/jboss/as/jsf/injection/AnnotationMap.java
  jsf/subsystem/src/main/java/org/jboss/as/jsf/deployment/JSFAnnotationProcessor.java
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/jsf/resourceResolver/CustomResourceResolver.java
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/jsf/resourceResolver/FaceletsResourceResolverTestCase.java
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/jsf/resourceResolver/index.xhtml
Labels: deps-ok

#13877 WFLY-14289 Upgrade Weld to 3.1.6.Final.
  pom.xml
Labels: deps-ok

#13894 [WFLY-12877] Using descriptive error message for duplicate host/conte…
  undertow/src/main/java/org/wildfly/extension/undertow/deployment/UndertowDeploymentProcessor.java
  undertow/src/main/java/org/wildfly/extension/undertow/logging/UndertowLogger.java
Labels: deps-ok

#13794 WFLY-14176 Update Apache commons CLI 1.4
  pom.xml
Labels: deps-ok

#13874 WFLY-14245 Integrate MicroProfile OpenAPI 2.0
  pom.xml
Labels: MP-4.0

#13808 WFLY-14061 Replace Java EE references in java doc with corresponding …
  docs/src/main/asciidoc/_admin-guide/subsystem-configuration/JSF.adoc
  docs/src/main/asciidoc/_developer-guide/EJB3_Reference_Guide.adoc
  docs/src/main/asciidoc/_developer-guide/Implicit_module_dependencies_for_deployments.adoc
  docs/src/main/asciidoc/_developer-guide/Remote_EJB_invocations_via_JNDI_-_EJB_client_API_or_remote-naming_project.adoc
  docs/src/main/asciidoc/_developer-guide/ejb3/Container_interceptors.adoc
  docs/src/main/asciidoc/_extras/Developing_JSF_Project_Using,_Maven_and_IntelliJ.adoc
  docs/src/main/asciidoc/_extras/Getting_Started_Developing_Applications_Presentation_Demo.adoc
  docs/src/main/asciidoc/index.adoc
  ee/src/main/java/org/jboss/as/ee/managedbean/processors/JavaEEDependencyProcessor.java
  jsf/subsystem/src/main/java/org/jboss/as/jsf/deployment/JSFComponentProcessor.java
  spec-api/test/src/test/java/org/jboss/as/spec/api/test/SpecApiDependencyCheck.java
  webservices/server-integration/src/main/java/org/jboss/as/webservices/logging/WSLogger.java
  weld/subsystem/src/main/java/org/jboss/as/weld/services/ModuleGroupSingletonProvider.java
Labels: deps-ok

#13896 Update SmallRye Health to 3.0.0
  pom.xml
Labels: MP-4.0

#13897 [WFLY-14304] add exclusions for artemis dependency
  pom.xml
Labels: deps-ok

#13898 WFLY-14305 Some mistakes in Developer Guide
  docs/src/main/asciidoc/_developer-guide/Application_Client_Reference.adoc
  docs/src/main/asciidoc/_developer-guide/CDI_Reference.adoc
  docs/src/main/asciidoc/_developer-guide/Class_Loading_in_WildFly.adoc
  docs/src/main/asciidoc/_developer-guide/EE_Concurrency_Utilities.adoc
  docs/src/main/asciidoc/_developer-guide/Implicit_module_dependencies_for_deployments.adoc
  docs/src/main/asciidoc/_developer-guide/JNDI_Local_Reference.adoc
  docs/src/main/asciidoc/_developer-guide/JTA_Reference.adoc
  docs/src/main/asciidoc/_developer-guide/Migrate_Seam_2_Booking_EAR_Binaries_-_Step_by_Step.adoc
  docs/src/main/asciidoc/_developer-guide/Scoped_EJB_client_contexts.adoc
Labels: deps-ok

#13900 [WFLY-14311] javax.naming.OperationNotSupportedException should be thrown when read-only remote naming operations failed
  naming/src/main/java/org/jboss/as/naming/WritableServiceBasedNamingStore.java
  naming/src/main/java/org/jboss/as/naming/logging/NamingLogger.java
  naming/src/test/java/org/jboss/as/naming/WritableServiceBasedNamingStoreTestCase.java
Labels: deps-ok

#13899 [WFLY-14310] Use standard idioms for handling attribute resolution in…
  ee-feature-pack/galleon-common/src/main/resources/feature_groups/jpa.xml
  jpa/subsystem/src/main/java/org/jboss/as/jpa/subsystem/JPADefinition.java
  jpa/subsystem/src/main/java/org/jboss/as/jpa/subsystem/JPAExtension.java
  jpa/subsystem/src/main/java/org/jboss/as/jpa/subsystem/JPASubSystemAdd.java
  jpa/subsystem/src/main/resources/subsystem-templates/jpa.xml
  jpa/subsystem/src/test/java/org/jboss/as/jpa/subsystem/JPA10SubsystemTestCase.java
  jpa/subsystem/src/test/java/org/jboss/as/jpa/subsystem/JPA11SubsystemTestCase.java
  jpa/subsystem/src/test/resources/org/jboss/as/jpa/subsystem/subsystem-1.0-empty.xml
  jpa/subsystem/src/test/resources/org/jboss/as/jpa/subsystem/subsystem-1.1-empty.xml
Labels: deps-ok

#13904 [WFLY-14219] Fix ee-8-api...javax/ws/rs/api/main/module.xml for TCK test
  ee-feature-pack/ee-8-api/src/main/resources/modules/system/layers/base/javax/ws/rs/api/main/module.xml
Labels: deps-ok

#13905 [WFLY-14219] Add java.xml dependency to the WildFly Preview jakarta.w…
  ee-9/feature-pack/src/main/resources/modules/system/layers/base/jakarta/ws/rs/api/main/module.xml
Labels: deps-ok

#13843 [WFLY-14256] Correct what testsuite/layers provisioning executions ru…
  testsuite/layers/pom.xml
Labels: deps-ok

#13872 [WFLY-14277] Upgrade to support MicroProfile JWT 1.2
  microprofile/galleon-common/pom.xml
  microprofile/galleon-common/src/license/microprofile-feature-pack-licenses.xml
  microprofile/galleon-common/src/main/resources/modules/system/layers/base/io/smallrye/jwt/main/module.xml
  pom.xml
  testsuite/integration/microprofile-tck/jwt/tck-base-suite.xml
Labels: MP-4.0

#13910 [WFLY-14339] Add the javax.api module back as a module dependency to …
  servlet-feature-pack/common/src/main/resources/modules/system/layers/base/org/jboss/as/security/main/module.xml
Labels: deps-ok

#13911 WFLY-14341 Upgrade JGroups to 4.2.11.Final
  pom.xml
Labels: deps-ok

#13912 WFLY-14340 Upgrade Infinispan to 11.0.9.Final
  pom.xml
Labels: deps-ok

#13908 [WFLY-14277] Upgrade to SmallRye JWT 3.0.0-RC3
  microprofile/galleon-common/pom.xml
  microprofile/galleon-common/src/license/microprofile-feature-pack-licenses.xml
  microprofile/galleon-common/src/main/resources/modules/system/layers/base/io/smallrye/jwt/main/module.xml
  pom.xml
Labels: MP-4.0

#13919 WFLY-14245 Update smallrye-open-api to 2.1.1
  pom.xml
Labels: MP-4.0

#13800 [WFLY-14186] Update netty.io 4.1.58
  pom.xml
Labels: deps-ok, hold

#13921 [WFLY-14355] Move missing MP Opentracing and MP REST Client licenses from wildfly-ee to wildfly
  ee-feature-pack/common/src/license/feature-pack-licenses.xml
  microprofile/galleon-common/src/license/microprofile-feature-pack-licenses.xml
Labels: deps-ok

#13928 [WFLY-14367] Missing assignment of returned value for check in MP Met…
  testsuite/integration/microprofile/src/test/java/org/wildfly/test/integration/microprofile/metrics/application/MicroProfileMetricsApplicationTestCase.java
Labels: deps-ok, ready-for-merge

#13930 Revert "[WFLY-14339] Add the javax.api module back as a module dependency to …"
  servlet-feature-pack/common/src/main/resources/modules/system/layers/base/org/jboss/as/security/main/module.xml
Labels: deps-ok

#13918 [WFLY-14352] Upgrading WildFly Naming Client to 1.0.14.Final
  pom.xml
Labels: deps-ok, ready-for-merge

#13925 WFLY-14356 Infinispan heap-memory caches transcoding key/values unnecessarily
  clustering/infinispan/extension/src/main/java/org/jboss/as/clustering/infinispan/subsystem/CacheConfigurationServiceConfigurator.java
Labels: deps-ok, ready-for-merge

#13926 [22.x] WFLY-14356 Infinispan heap-memory caches transcoding key/values unnecessarily
  clustering/infinispan/extension/src/main/java/org/jboss/as/clustering/infinispan/subsystem/CacheConfigurationServiceConfigurator.java
Labels: 22.x

#13901 [WFLY-14189] The RunAs annotation doesn't work in EJBs with Elytron
  ejb3/src/main/java/org/jboss/as/ejb3/component/singleton/SingletonComponentDescription.java
  testsuite/integration/elytron/src/test/java/org/wildfly/test/integration/elytron/ejb/RolePropagationTest.java
  testsuite/integration/elytron/src/test/java/org/wildfly/test/integration/elytron/ejb/RolePropagationTestImpl.java
  testsuite/integration/elytron/src/test/java/org/wildfly/test/integration/elytron/ejb/RolePropagationTestSecuredBean.java
  testsuite/integration/elytron/src/test/java/org/wildfly/test/integration/elytron/ejb/RolePropagationWithoutExplicitSecDomainElytronTest.java
Labels: deps-ok

#13871 WFLY-14275 Large job repository is blocking deployment
  batch-jberet/src/main/java/org/wildfly/extension/batch/jberet/deployment/BatchJobExecutionResource.java
Labels: deps-ok

#13879 WFLY-14276 Store elytron security identity in local context, not as a replicated session attribute, as this is not serializable.
  clustering/web/undertow/src/main/java/org/wildfly/clustering/web/undertow/session/DistributableSession.java
  clustering/web/undertow/src/main/java/org/wildfly/clustering/web/undertow/session/DistributableSessionManager.java
  clustering/web/undertow/src/main/java/org/wildfly/clustering/web/undertow/session/DistributableSessionManagerConfiguration.java
  clustering/web/undertow/src/main/java/org/wildfly/clustering/web/undertow/session/DistributableSessionManagerFactory.java
  clustering/web/undertow/src/main/java/org/wildfly/clustering/web/undertow/session/DistributableSessionManagerFactoryServiceConfigurator.java
  clustering/web/undertow/src/main/java/org/wildfly/clustering/web/undertow/session/LocalSessionContext.java
  clustering/web/undertow/src/main/java/org/wildfly/clustering/web/undertow/session/LocalSessionContextFactory.java
  clustering/web/undertow/src/main/java/org/wildfly/clustering/web/undertow/session/SessionManagerFactoryConfigurationAdapter.java
  clustering/web/undertow/src/main/java/org/wildfly/clustering/web/undertow/session/UndertowSessionManager.java
  clustering/web/undertow/src/test/java/org/wildfly/clustering/web/undertow/session/DistributableSessionManagerTestCase.java
  clustering/web/undertow/src/test/java/org/wildfly/clustering/web/undertow/session/DistributableSessionTestCase.java
  clustering/web/undertow/src/test/java/org/wildfly/clustering/web/undertow/session/UndertowSessionExpirationListenerTestCase.java
Labels: deps-ok

#13887 [WFLY-14293]:Fix regression failures when deploy JMS and session Endpoint
  webservices/server-integration/src/main/java/org/jboss/as/webservices/deployers/deployment/DeploymentModelBuilderJAXWS_JMS.java
  webservices/server-integration/src/main/java/org/jboss/as/webservices/invocation/AbstractInvocationHandler.java
Labels: deps-ok

#13927 WFLY-14361 Workaround for ISPN-11121: Failed permission check during PersistenceManager.start()
  clustering/ejb/infinispan/src/main/java/org/wildfly/clustering/ejb/infinispan/InfinispanClientMappingsRegistryProvider.java
  clustering/infinispan/spi/src/main/java/org/wildfly/clustering/infinispan/spi/persistence/PersistenceManagerFactory.java
  clustering/infinispan/spi/src/main/java/org/wildfly/clustering/infinispan/spi/service/TemplateConfigurationServiceConfigurator.java
  clustering/web/infinispan/src/main/java/org/wildfly/clustering/web/infinispan/routing/InfinispanLegacyRoutingProviderFactory.java
Labels: deps-ok

#13880 [22.x] WFLY-14276 Store elytron security identity in local context, not as a replicated session attribute, as this is not serializable.
  clustering/web/undertow/src/main/java/org/wildfly/clustering/web/undertow/session/DistributableSession.java
  clustering/web/undertow/src/main/java/org/wildfly/clustering/web/undertow/session/DistributableSessionManager.java
  clustering/web/undertow/src/main/java/org/wildfly/clustering/web/undertow/session/DistributableSessionManagerConfiguration.java
  clustering/web/undertow/src/main/java/org/wildfly/clustering/web/undertow/session/DistributableSessionManagerFactory.java
  clustering/web/undertow/src/main/java/org/wildfly/clustering/web/undertow/session/DistributableSessionManagerFactoryServiceConfigurator.java
  clustering/web/undertow/src/main/java/org/wildfly/clustering/web/undertow/session/LocalSessionContext.java
  clustering/web/undertow/src/main/java/org/wildfly/clustering/web/undertow/session/LocalSessionContextFactory.java
  clustering/web/undertow/src/main/java/org/wildfly/clustering/web/undertow/session/SessionManagerFactoryConfigurationAdapter.java
  clustering/web/undertow/src/main/java/org/wildfly/clustering/web/undertow/session/UndertowSessionManager.java
  clustering/web/undertow/src/test/java/org/wildfly/clustering/web/undertow/session/DistributableSessionManagerTestCase.java
  clustering/web/undertow/src/test/java/org/wildfly/clustering/web/undertow/session/DistributableSessionTestCase.java
  clustering/web/undertow/src/test/java/org/wildfly/clustering/web/undertow/session/UndertowSessionExpirationListenerTestCase.java
Labels: 22.x

#13888 [22.x][WFLY-14293]:Fix regression failures when deploy JMS and session endpoint
  webservices/server-integration/src/main/java/org/jboss/as/webservices/deployers/deployment/DeploymentModelBuilderJAXWS_JMS.java
  webservices/server-integration/src/main/java/org/jboss/as/webservices/invocation/AbstractInvocationHandler.java
Labels: 22.x

#13920 [WFLY-11272] wildfly-microprofile-health-smallrye_1_0.xsd doesn't hav…
  microprofile/health-smallrye/src/main/resources/schema/wildfly-microprofile-health-smallrye_1_0.xsd
  microprofile/health-smallrye/src/main/resources/schema/wildfly-microprofile-health-smallrye_2_0.xsd
Labels: deps-ok

#13815 WFLY-14216 Update Extended StAX API 1.8.3
  ee-feature-pack/common/src/license/feature-pack-licenses.xml
  pom.xml
Labels: deps-ok, ready-for-merge

#13938 [WFLY-14379] Update tests to use SHA256withRSA instead of SHA1withRSA
  testsuite/integration/elytron/src/test/java/org/wildfly/test/integration/elytron/certs/realm/KeystoreRealmTestCase.java
  testsuite/integration/elytron/src/test/java/org/wildfly/test/integration/elytron/ssl/AutomaticSelfSignedCertificateNotGeneratedTestCase.java
Labels: deps-ok, ready-for-merge

#13935 WFLY-14315 Replace JavaServer Faces|JSF references in java doc with c…
  docs/src/main/asciidoc/Getting_Started_Developing_Applications_Guide.adoc
  docs/src/main/asciidoc/Getting_Started_Guide.adoc
  docs/src/main/asciidoc/JavaEE_Tutorial.adoc
  docs/src/main/asciidoc/_admin-guide/Subsystem_configuration.adoc
  docs/src/main/asciidoc/_admin-guide/subsystem-configuration/Jakarta_Server_Faces.adoc
  docs/src/main/asciidoc/_developer-guide/Implicit_module_dependencies_for_deployments.adoc
  docs/src/main/asciidoc/_extras/Developing_Jakarta_Server_Faces_Project_Using_Maven_and_IntelliJ.adoc
  docs/src/main/asciidoc/_javaee-guide/Jakarta_Server_Faces_Technology_(Jakarta_Server_Faces).adoc
  docs/src/main/asciidoc/_javaee-guide/Java_Server_Faces_Technology_(JSF).adoc
  jsf/injection/src/main/java/org/jboss/as/jsf/injection/AnnotationMap.java
  jsf/injection/src/main/java/org/jboss/as/jsf/injection/JSFInjectionProvider.java
  jsf/injection/src/main/java/org/jboss/as/jsf/injection/JandexAnnotationProvider.java
  jsf/injection/src/main/java/org/jboss/as/jsf/injection/MyFacesAnnotationProvider.java
  jsf/injection/src/main/java/org/jboss/as/jsf/injection/weld/WildFlyConversationAwareViewHandler.java
  jsf/subsystem/src/main/java/org/jboss/as/jsf/deployment/JSFDependencyProcessor.java
  jsf/subsystem/src/main/java/org/jboss/as/jsf/deployment/JSFVersionProcessor.java
  jsf/subsystem/src/main/java/org/jboss/as/jsf/logging/JSFLogger.java
  legacy/web/src/main/java/org/jboss/as/web/DefaultJsfProfileCompletionHandler.java
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/jaxb/unit/JAXBUsageTestCase.java
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/jsf/beanvalidation/cdi/BeanValidationCdiIntegrationTestCase.java
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/jsf/doctype/DoctypeDeclTestCase.java
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/jsf/injection/JSF23ConfigurationBean.java
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/jsf/jsf23/JSF23SanityTestCase.java
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/jsf/jsf23/confirmation.xhtml
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/jsf/managedbean/managedproperty/ManagedPropertyManagedBeanTestCase.java
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/jsf/managedbean/managedproperty/SimpleJsfManagedBean.java
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/jsf/undertow/CallEnumParameterMethodTestCase.java
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/jsf/unsupportedwar/FaceletsViewMappingsTestCase.java
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/jsf/unsupportedwar/hello.jsf
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/jsf/version/JSFDeploymentProcessorTestCase.java
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/xerces/unit/XercesUsageTestCase.java
  testsuite/integration/clustering/src/test/java/org/jboss/as/test/clustering/cluster/jsf/JSFFailoverTestCase.java
  testsuite/integration/ws/src/test/java/org/jboss/as/test/integration/ws/cdi/CdiJsfWebServicesTestCase.java
  undertow/src/main/java/org/wildfly/extension/undertow/deployment/ExternalTldParsingDeploymentProcessor.java
Labels: deps-ok
