Repository wildfly/wildfly, pull requests merged in 2021-08, with the labels that each got.

#14519 [WFLY-15078] Upgrade WildFly Core 17.0.0.Beta4
  pom.xml
Labels: deps-ok

#14525 WFLY-15079 MicroProfileConfigConvertersTestCase uses Converter<String…
  testsuite/integration/microprofile/src/test/java/org/wildfly/test/integration/microprofile/config/smallrye/converter/HighPriorityMyStringConverter1.java
  testsuite/integration/microprofile/src/test/java/org/wildfly/test/integration/microprofile/config/smallrye/converter/HighPriorityMyStringConverter2.java
  testsuite/integration/microprofile/src/test/java/org/wildfly/test/integration/microprofile/config/smallrye/converter/MicroProfileConfigConvertersTestCase.java
  testsuite/integration/microprofile/src/test/java/org/wildfly/test/integration/microprofile/config/smallrye/converter/MyString.java
  testsuite/integration/microprofile/src/test/java/org/wildfly/test/integration/microprofile/config/smallrye/converter/SetupTask.java
  testsuite/integration/microprofile/src/test/java/org/wildfly/test/integration/microprofile/config/smallrye/converter/TestApplication.java
Labels: deps-ok

#14515 [WFLY-14406] Update mixed domain tests to use EAP 7.4.0 rather than WF23
  testsuite/integration/manualmode/src/test/java/org/jboss/as/test/manualmode/parse/ParseAndMarshalModelsTestCase.java
  testsuite/integration/manualmode/src/test/resources/legacy-configs/domain/eap-7-4-0.xml
  testsuite/integration/manualmode/src/test/resources/legacy-configs/host/eap-7-4-0.xml
  testsuite/integration/manualmode/src/test/resources/legacy-configs/standalone/domain-ec2.xml
  testsuite/integration/manualmode/src/test/resources/legacy-configs/standalone/eap-7-4-0-activemq-colocated.xml
  testsuite/integration/manualmode/src/test/resources/legacy-configs/standalone/eap-7-4-0-azure-full-ha.xml
  testsuite/integration/manualmode/src/test/resources/legacy-configs/standalone/eap-7-4-0-azure-ha.xml
  testsuite/integration/manualmode/src/test/resources/legacy-configs/standalone/eap-7-4-0-ec2-full-ha.xml
  testsuite/integration/manualmode/src/test/resources/legacy-configs/standalone/eap-7-4-0-ec2-ha.xml
  testsuite/integration/manualmode/src/test/resources/legacy-configs/standalone/eap-7-4-0-full-ha.xml
  testsuite/integration/manualmode/src/test/resources/legacy-configs/standalone/eap-7-4-0-full.xml
  testsuite/integration/manualmode/src/test/resources/legacy-configs/standalone/eap-7-4-0-genericjms.xml
  testsuite/integration/manualmode/src/test/resources/legacy-configs/standalone/eap-7-4-0-gossip-full-ha.xml
  testsuite/integration/manualmode/src/test/resources/legacy-configs/standalone/eap-7-4-0-gossip-ha.xml
  testsuite/integration/manualmode/src/test/resources/legacy-configs/standalone/eap-7-4-0-ha.xml
  testsuite/integration/manualmode/src/test/resources/legacy-configs/standalone/eap-7-4-0-jts.xml
  testsuite/integration/manualmode/src/test/resources/legacy-configs/standalone/eap-7-4-0-load-balancer.xml
  testsuite/integration/manualmode/src/test/resources/legacy-configs/standalone/eap-7-4-0-minimalistic.xml
  testsuite/integration/manualmode/src/test/resources/legacy-configs/standalone/eap-7-4-0-picketlink.xml
  testsuite/integration/manualmode/src/test/resources/legacy-configs/standalone/eap-7-4-0-rts.xml
  testsuite/integration/manualmode/src/test/resources/legacy-configs/standalone/eap-7-4-0-xts.xml
  testsuite/integration/manualmode/src/test/resources/legacy-configs/standalone/eap-7-4-0.xml
  testsuite/mixed-domain/src/test/java/org/jboss/as/test/integration/domain/mixed/Version.java
  testsuite/mixed-domain/src/test/java/org/jboss/as/test/integration/domain/mixed/eap730/DomainAdjuster730.java
  testsuite/mixed-domain/src/test/java/org/jboss/as/test/integration/domain/mixed/eap740/DomainAdjuster740.java
Labels: deps-ok

#14526 [WFLY-15081] Update wildfly-galleon-plugin to 5.2.2.Beta2
  pom.xml
Labels: deps-ok

#14520 [WFLY-15044] Avoid Nullpointer (Weld)
  weld/subsystem/src/main/java/org/jboss/as/weld/deployment/processors/ExternalBeanArchiveProcessor.java
Labels: deps-ok

#14523 [WFLY-15044] Avoid Nullpointer (Messaging-ActiveMQ)
  messaging-activemq/subsystem/src/main/java/org/wildfly/extension/messaging/activemq/ElytronSecurityManager.java
  messaging-activemq/subsystem/src/main/java/org/wildfly/extension/messaging/activemq/HTTPUpgradeService.java
  messaging-activemq/subsystem/src/main/java/org/wildfly/extension/messaging/activemq/jms/ExternalPooledConnectionFactoryService.java
Labels: deps-ok

#14522 [WFLY-15044] Avoid Nullpointer (Naming)
  naming/src/main/java/org/jboss/as/naming/ServiceBasedNamingStore.java
Labels: deps-ok

#14531 Jakarta REST Specification Upgrades
  ee-9/feature-pack/pom.xml
  pom.xml
Labels: deps-ok

#14502 [WFLY-15031] Move WildFly Preview to a native jakarta namespace variant of the WildFly Transaction Client jar
  ee-9/feature-pack/pom.xml
  ee-9/feature-pack/src/main/resources/modules/system/layers/base/org/wildfly/transaction/client/main/module.xml
Labels: deps-ok

#14529 WFLY-15083 Upgrade Infinispan to 12.1.7.Final
  pom.xml
  testsuite/integration/clustering/pom.xml
Labels: deps-ok

#14402 [WFLY-1909][UNDERTOW-1909] Changing Eclipse JDT groupId coordinates to by in sync with latest Eclipse JDT maven releases.
  pom.xml
  servlet-feature-pack/common/pom.xml
  servlet-feature-pack/common/src/main/resources/license/servlet-feature-pack-common-licenses.xml
  servlet-feature-pack/common/src/main/resources/modules/system/layers/base/org/eclipse/jdt/ecj/main/module.xml
Labels: deps-changed

#14440 [WFLY-14972] Check emptiness with Collection.isEmpty() (Messaging-AMQ)
  messaging-activemq/subsystem/src/main/java/org/wildfly/extension/messaging/activemq/ActiveMQServerResource.java
  messaging-activemq/subsystem/src/main/java/org/wildfly/extension/messaging/activemq/CoreAddressResource.java
  messaging-activemq/subsystem/src/main/java/org/wildfly/extension/messaging/activemq/jms/ConnectionFactoryAdd.java
  messaging-activemq/subsystem/src/main/java/org/wildfly/extension/messaging/activemq/jms/PooledConnectionFactoryService.java
Labels: deps-ok

#14428 [WFLY-14968] Collapse if-statements (JPA)
  jpa/eclipselink/src/main/java/org/jipijapa/eclipselink/WildFlyServerPlatform.java
  jpa/hibernate5/src/main/java/org/jboss/as/jpa/hibernate5/HibernateSecondLevelCache.java
  jpa/hibernate5_3/src/main/java/org/jboss/as/jpa/hibernate5/HibernateSecondLevelCache.java
  jpa/subsystem/src/main/java/org/jboss/as/jpa/container/PersistenceUnitSearch.java
  jpa/subsystem/src/main/java/org/jboss/as/jpa/processor/JPAClassFileTransformerProcessor.java
  jpa/subsystem/src/main/java/org/jboss/as/jpa/processor/PersistenceUnitServiceHandler.java
  jpa/subsystem/src/main/java/org/jboss/as/jpa/transaction/TransactionUtil.java
Labels: deps-ok

#14473 [WFLY-15009] - SecurityContextImpl.login incorrectly assumes authenti…
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/security/securitycontext/MyDummyTokenHandler.java
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/security/securitycontext/MyServletExtension.java
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/security/securitycontext/SecurityContextImplLoginTestCase.java
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/security/securitycontext/index.html
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/security/securitycontext/io.undertow.servlet.ServletExtension
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/security/securitycontext/jboss-web.xml
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/security/securitycontext/main/index.html
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/security/securitycontext/pub/login-error.html
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/security/securitycontext/pub/login.html
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/security/securitycontext/web.xml
Labels: deps-ok

#14406 [WFLY-14955] Use logger instead of syserr
  metrics/src/main/java/org/wildfly/extension/metrics/_private/MetricsLogger.java
  metrics/src/main/java/org/wildfly/extension/metrics/jmx/JmxMetricCollector.java
Labels: deps-ok

#14493 WFLY-15041 MDB not working when the bean class does not implement Mes…
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/ejb/mdb/activationconfig/MDBWithLookupActivationConfigProperties.java
Labels: deps-ok

#14485 [WFLY-15035][WFLY-15036] Use source code transformation to produce a native jakarta namespace variant of the mail subsystem artifact
  ee-9/feature-pack/pom.xml
  ee-9/feature-pack/src/main/resources/license/preview-feature-pack-licenses.xml
  ee-9/feature-pack/src/main/resources/modules/system/layers/base/org/jboss/as/mail/main/module.xml
  ee-9/pom.xml
  ee-9/source-transform/mail/pom.xml
  ee-9/source-transform/pom.xml
  mail/src/test/java/org/jboss/as/mail/extension/MailTransformersTestCase.java
Labels: deps-ok

#14528 WFLY-13809 Get application name from BatchEnvironment instead of jndi lookup and Upgrade jberet-core from 1.3.9.Final to 1.3.10.Final; from 2.0.0.Final to 2.0.1.Final in ee-9 preview
  batch-jberet/src/main/java/org/wildfly/extension/batch/jberet/DefaultBatchEnvironment.java
  batch-jberet/src/main/java/org/wildfly/extension/batch/jberet/deployment/BatchEnvironmentService.java
  ee-9/feature-pack/pom.xml
  pom.xml
Labels: deps-ok

#14355 WFLY-14877 Do not allow application to create a new session or change the identifier of a session after response is committed
  clustering/web/undertow/src/main/java/org/wildfly/clustering/web/undertow/session/DistributableSession.java
  clustering/web/undertow/src/main/java/org/wildfly/clustering/web/undertow/session/DistributableSessionManager.java
  clustering/web/undertow/src/main/java/org/wildfly/clustering/web/undertow/session/DistributableSessionManagerConfiguration.java
  clustering/web/undertow/src/main/java/org/wildfly/clustering/web/undertow/session/DistributableSessionManagerFactory.java
  clustering/web/undertow/src/main/java/org/wildfly/clustering/web/undertow/session/OrphanSession.java
  clustering/web/undertow/src/test/java/org/wildfly/clustering/web/undertow/session/DistributableSessionManagerTestCase.java
  clustering/web/undertow/src/test/java/org/wildfly/clustering/web/undertow/session/DistributableSessionTestCase.java
Labels: deps-ok, 25.x

#14507 [WFLY-15092] Use maven-resource-plugin filtering to avoid duplicating …
  ee-9/feature-pack/pom.xml
  ee-9/feature-pack/src/main/resources/modules/system/layers/base/com/fasterxml/jackson/jaxrs/jackson-jaxrs-json-provider/main/module.xml
  ee-9/feature-pack/src/main/resources/modules/system/layers/base/org/jboss/as/mail/main/module.xml
  ee-feature-pack/common/src/main/resources/modules/system/layers/base/com/fasterxml/jackson/jaxrs/jackson-jaxrs-json-provider/main/module.xml
  ee-feature-pack/common/src/main/resources/modules/system/layers/base/org/jboss/as/mail/main/module.xml
  ee-feature-pack/galleon-feature-pack/pom.xml
  pom.xml
Labels: deps-ok

#14541 WFLY-15096 ProtoStream marshaller for loaded classes fails when using modular ClassLoader
  clustering/marshalling/protostream/src/main/java/org/wildfly/clustering/marshalling/protostream/LoadedClassField.java
Labels: deps-ok

#14495 [WFLY-15018] Manage the BouncyCastle Jakarta Mail dependency with Wil…
  ee-9/feature-pack/pom.xml
Labels: deps-ok

#14536 [WFLY-15087] Fix useServerLog value in AccessLogService constructor
  undertow/src/main/java/org/wildfly/extension/undertow/AccessLogAdd.java
  undertow/src/main/java/org/wildfly/extension/undertow/AccessLogService.java
Labels: deps-ok

#14535 [WFLY-14569] Change 'Eclipse MicroProfile' to 'MicroProfile' in non-d…
  microprofile/config-smallrye/src/main/java/org/wildfly/extension/microprofile/config/smallrye/ServiceNames.java
  microprofile/config-smallrye/src/main/resources/org/wildfly/extension/microprofile/config/smallrye/LocalDescriptions.properties
  microprofile/health-smallrye/src/main/resources/org/wildfly/extension/microprofile/health/LocalDescriptions.properties
  microprofile/jwt-smallrye/src/main/resources/org/wildfly/extension/microprofile/jwt/smallrye/LocalDescriptions.properties
  microprofile/metrics-smallrye/src/main/resources/org/wildfly/extension/microprofile/metrics/LocalDescriptions.properties
  microprofile/opentracing-extension/src/main/resources/org/wildfly/extension/microprofile/opentracing/LocalDescriptions.properties
Labels: deps-ok

#14544 WFLY-15118 Upgrade smallrye-open-api to 2.1.9
  pom.xml
Labels: deps-ok

#14545 [WFLY-15119]: Add WildFly style parameter mappings for connectors.
  messaging-activemq/subsystem/src/main/java/org/wildfly/extension/messaging/activemq/TransportConfigOperationHandlers.java
Labels: deps-ok

#14548 WFLY-15122 Remove obsolete ManagedCommandDispatchFactory
  clustering/server/src/main/java/org/wildfly/clustering/server/dispatcher/ChannelCommandDispatcherFactoryServiceConfigurator.java
  clustering/server/src/main/java/org/wildfly/clustering/server/dispatcher/ManagedCommandDispatcher.java
  clustering/server/src/main/java/org/wildfly/clustering/server/dispatcher/ManagedCommandDispatcherFactory.java
  clustering/server/src/main/java/org/wildfly/clustering/server/logging/ClusteringServerLogger.java
  clustering/server/src/test/java/org/wildfly/clustering/server/dispatcher/ManagedCommandDispatcherFactoryTestCase.java
  clustering/server/src/test/java/org/wildfly/clustering/server/dispatcher/ManagedCommandDispatcherTestCase.java
Labels: deps-ok

#14549 WFLY-15121 Remove deprecated param TransactionManager from TimerPersi…
  ejb3/src/main/java/org/jboss/as/ejb3/timerservice/TimerServiceImpl.java
  ejb3/src/main/java/org/jboss/as/ejb3/timerservice/persistence/TimerPersistence.java
  ejb3/src/main/java/org/jboss/as/ejb3/timerservice/persistence/database/DatabaseTimerPersistence.java
  ejb3/src/main/java/org/jboss/as/ejb3/timerservice/persistence/filestore/FileTimerPersistence.java
Labels: deps-ok

#14405 [WFLY-14954] Add testsuite/integration/secman to the WF Preview ts.ee…
  testsuite/integration/pom.xml
  testsuite/integration/secman/pom.xml
Labels: deps-ok

#14537 [WFLY-15023] Move WildFly Preview to a native jakarta.* namespace variant of JBoss Metadata artifacts that use EE APIs
  ee-9/feature-pack/pom.xml
  ee-9/feature-pack/src/main/resources/license/preview-feature-pack-licenses.xml
  ee-feature-pack/common/src/main/resources/modules/system/layers/base/org/jboss/metadata/ejb/main/module.xml
  ee-feature-pack/galleon-feature-pack/pom.xml
  servlet-feature-pack/common/src/main/resources/modules/system/layers/base/org/jboss/metadata/common/main/module.xml
  servlet-feature-pack/common/src/main/resources/modules/system/layers/base/org/jboss/metadata/ear/main/module.xml
  servlet-feature-pack/common/src/main/resources/modules/system/layers/base/org/jboss/metadata/web/main/module.xml
  servlet-feature-pack/galleon-feature-pack/pom.xml
Labels: deps-ok

#14552 [WFLY-15126]:Upgrade CXF from 3.3.10 to 3.4.4
  pom.xml
Labels: deps-ok

#14373 WFLY-14377 Update all projects with a dependency on wildfly-elytron to use individual modules
  appclient/pom.xml
  batch-jberet/pom.xml
  bean-validation/pom.xml
  client/shade/pom.xml
  clustering/common/pom.xml
  clustering/ee/cache/pom.xml
  clustering/ee/infinispan/pom.xml
  clustering/ejb/infinispan/pom.xml
  clustering/infinispan/extension/pom.xml
  clustering/infinispan/marshalling/pom.xml
  clustering/infinispan/spi/pom.xml
  clustering/jgroups/extension/pom.xml
  clustering/marshalling/jboss/pom.xml
  clustering/marshalling/protostream/pom.xml
  clustering/marshalling/spi/pom.xml
  clustering/server/pom.xml
  clustering/spi/pom.xml
  clustering/web/cache/pom.xml
  clustering/web/hotrod/pom.xml
  clustering/web/infinispan/pom.xml
  clustering/web/undertow/pom.xml
  connector/pom.xml
  datasources-agroal/pom.xml
  ee/pom.xml
  ejb3/pom.xml
  health/pom.xml
  iiop-openjdk/pom.xml
  jaxrs/pom.xml
  jpa/hibernate-transformer/pom.xml
  jpa/subsystem/pom.xml
  jsf/subsystem/pom.xml
  jsr77/pom.xml
  legacy/web/pom.xml
  mail/pom.xml
  messaging-activemq/subsystem/pom.xml
  metrics/pom.xml
  microprofile/metrics-smallrye/pom.xml
  microprofile/opentracing-extension/pom.xml
  microprofile/opentracing-smallrye/pom.xml
  microprofile/reactive-messaging-smallrye/extension/pom.xml
  naming/pom.xml
  pojo/pom.xml
  sar/pom.xml
  security/api/pom.xml
  security/plugins/pom.xml
  security/subsystem/pom.xml
  testsuite/integration/pom.xml
  testsuite/shared/pom.xml
  transactions/pom.xml
  undertow/pom.xml
  web-common/pom.xml
  webservices/server-integration/pom.xml
  weld/bean-validation/pom.xml
  weld/common/pom.xml
  weld/subsystem/pom.xml
Labels: deps-ok

#14553 [WFLY-13059]:Move jasypt to a dedicated module
  ee-feature-pack/common/src/main/resources/modules/system/layers/base/org/apache/ws/security/main/module.xml
  ee-feature-pack/common/src/main/resources/modules/system/layers/base/org/jasypt/main/module.xml
Labels: deps-ok

#14555 Exclude the ClusteredMessagingTestCase from running in WildFly Previe…
  testsuite/integration/clustering/pom.xml
Labels: deps-ok

#14554 [WFLY-15133] Upgrade SmallRye Config to 2.4.3
  pom.xml
Labels: deps-ok

#14550 WFLY-15113 EJB timer: need to consider existing timers in database wh…
  ejb3/src/main/java/org/jboss/as/ejb3/timerservice/TimerServiceImpl.java
Labels: deps-ok

#14539 WFLY-14923 Update JPA handling to support initialize-in-order
  ee-feature-pack/common/src/main/resources/modules/system/layers/base/org/jboss/as/jpa/main/module.xml
  ee-feature-pack/common/src/main/resources/modules/system/layers/base/org/jboss/as/weld/jpa/main/module.xml
  jpa/spi/src/main/java/org/jipijapa/plugin/spi/PersistenceUnitMetadata.java
  jpa/subsystem/src/main/java/org/jboss/as/jpa/config/PersistenceUnitMetadataImpl.java
  jpa/subsystem/src/main/java/org/jboss/as/jpa/processor/JPAClassFileTransformerProcessor.java
  jpa/subsystem/src/main/java/org/jboss/as/jpa/processor/JPADelegatingClassFileTransformer.java
  jpa/subsystem/src/main/java/org/jboss/as/jpa/processor/JPADependencyProcessor.java
  jpa/subsystem/src/main/java/org/jboss/as/jpa/processor/PersistenceUnitParseProcessor.java
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/jpa/initializeinorder/AbstractCMTBean.java
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/jpa/initializeinorder/CdiJpaInjectingBean.java
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/jpa/initializeinorder/Employee.java
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/jpa/initializeinorder/InitializeInOrderTestCase.java
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/jpa/initializeinorder/MyEjb.java
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/jpa/initializeinorder/MyEjb2.java
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/jpa/initializeinorder/MyListener.java
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/jpa/initializeinorder/MyServlet.java
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/jpa/initializeinorder/QualifyEntityManager.java
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/jpa/initializeinorder/QualifyEntityManagerFactory.java
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/jpa/initializeinorder/SFSBCMT.java
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/jpa/initializeinorder/SingletonCMT.java
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/jpa/initializeinorder/TestState.java
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/jpa/initializeinorder/application.xml
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/jpa/initializeinorder/persistence.xml
  weld/common/src/main/java/org/jboss/as/weld/logging/WeldLogger.java
  weld/jpa/src/main/java/org/jboss/as/weld/deployment/processor/JpaDependenciesProvider.java
  weld/jpa/src/main/java/org/jboss/as/weld/services/bootstrap/WeldJpaInjectionServices.java
Labels: deps-ok

#14297 [WFLY-14691] Tests the data source statistics attribute MaxWaitCount during waiting requests.
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/jca/statistics/DataSourceMultipleConnStatsServerSetupTask.java
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/jca/statistics/DataSourceMultipleConnStatsTestCase.java
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/jca/statistics/SleepServlet.java
Labels: deps-ok

#14557 WFLY-15141 Add EAP 7.4.0 transformers tests for mod_cluster subsystem
  mod_cluster/extension/src/test/java/org/wildfly/extension/mod_cluster/ModClusterTransformersTestCase.java
Labels: deps-ok

#14560 WFLY-15146 Add EAP 7.4.0 transformers tests for distributable-web sub…
  clustering/web/extension/src/test/java/org/wildfly/extension/clustering/web/DistributableWebTransformerTestCase.java
Labels: deps-ok

#14564 WFLY-15149 Remove Netty (unused) dependency on javassist
  ee-feature-pack/common/src/main/resources/modules/system/layers/base/io/netty/main/module.xml
Labels: deps-ok

#14565 [WFLY-15150][WFLY-14888] Hibernate ORM to support JDK 17
  pom.xml
Labels: deps-ok

#13985 WFLY-10607 Fix EJBForwardingTestCase keeping it ignored due to remaining issues
  testsuite/integration/clustering/pom.xml
  testsuite/integration/clustering/src/test/java/org/jboss/as/test/clustering/cluster/ejb/forwarding/AbstractRemoteEJBForwardingTestCase.java
  testsuite/integration/clustering/src/test/java/org/jboss/as/test/clustering/cluster/ejb/forwarding/bean/forwarding/AbstractForwardingStatefulSBImpl.java
Labels: deps-ok

#14559 WFLY-15143 Add EAP 7.4.0 transformers tests for jgroups subsystem
  clustering/jgroups/extension/src/main/java/org/jboss/as/clustering/jgroups/subsystem/JGroupsModel.java
  clustering/jgroups/extension/src/test/java/org/jboss/as/clustering/jgroups/subsystem/JGroupsTransformersTestCase.java
  clustering/jgroups/extension/src/test/resources/org/jboss/as/clustering/jgroups/subsystem/subsystem-jgroups-transform-8_0_0.xml
Labels: deps-ok

#14558 WFLY-15142 Add EAP 7.4.0 transformers tests for singleton subsystem
  clustering/singleton/extension/src/test/java/org/wildfly/extension/clustering/singleton/SingletonTransformersTestCase.java
Labels: deps-ok

#14556 [WFLY-15140]: Upgrade WildFly to JBoss Metadata 14.0.0.Final
  appclient/pom.xml
  clustering/web/spi/pom.xml
  ee-9/feature-pack/pom.xml
  ee-feature-pack/common/pom.xml
  jsf/subsystem/pom.xml
  microprofile/jwt-smallrye/pom.xml
  microprofile/openapi-smallrye/pom.xml
  microprofile/opentracing-extension/pom.xml
  pom.xml
  weld/subsystem/pom.xml
Labels: deps-changed

#14569 [WFLY-15044] Avoid Nullpointer (Infinispan)
  clustering/ee/hotrod/src/main/java/org/wildfly/clustering/ee/hotrod/RemoteCacheKey.java
  clustering/infinispan/extension/src/main/java/org/jboss/as/clustering/infinispan/subsystem/InfinispanSubsystemXMLReader.java
Labels: deps-ok

#14576 [WFLY-15157]: Simplify the creation of a jakarta native namespace mail subsystem.
  ee-9/feature-pack/pom.xml
  ee-9/source-transform/pom.xml
Labels: deps-ok

#14575 [WFLY-15155] Updated tarLongFileMode to use POSIX
  build/pom.xml
  dist/pom.xml
  ee-9/build/pom.xml
  ee-9/dist/pom.xml
  ee-build/pom.xml
  ee-dist/pom.xml
  ee-feature-pack/common/pom.xml
  ee-feature-pack/ee-8-api/pom.xml
  ee-feature-pack/galleon-common/pom.xml
  ee-feature-pack/galleon-content/pom.xml
  ee-feature-pack/pruned/pom.xml
  galleon-pack/galleon-content/pom.xml
  microprofile/galleon-common/pom.xml
  pom.xml
  servlet-build/pom.xml
  servlet-dist/pom.xml
  servlet-feature-pack/common/pom.xml
  servlet-feature-pack/ee-8-api/pom.xml
  servlet-feature-pack/galleon-common/pom.xml
  servlet-feature-pack/galleon-pruned/pom.xml
Labels: deps-ok

#14551 [WFLY-15117] guard potential NPE from service controller
  undertow/src/main/java/org/wildfly/extension/undertow/ConsoleRedirectService.java
  undertow/src/main/java/org/wildfly/extension/undertow/DeploymentDefinition.java
  undertow/src/main/java/org/wildfly/extension/undertow/security/jacc/WarJACCService.java
Labels: deps-ok

#14484 WFLY-14902 Clustering TS: Enable authentication and authorization for Infinispan Server tests + enable on Windows + instances provisioned by testsuite never shutdown
  testsuite/integration/clustering/pom.xml
  testsuite/integration/clustering/src/test/java/org/jboss/as/test/clustering/cluster/AbstractClusteringTestCase.java
  testsuite/integration/clustering/src/test/java/org/jboss/as/test/clustering/cluster/sso/remote/InfinispanServerSetupTask.java
  testsuite/integration/clustering/src/test/java/org/jboss/as/test/clustering/cluster/web/remote/InfinispanServerSetupTask.java
  testsuite/integration/clustering/src/test/resources/infinispan-server-overlay/groups.properties
  testsuite/integration/clustering/src/test/resources/infinispan-server-overlay/users.properties
  testsuite/integration/clustering/src/test/resources/infinispan.xml
Labels: deps-ok

#14590 [WFCORE-5406][WFLY-14793] Adding required --add-opens & --add-exports clauses
  pom.xml
Labels: deps-ok

#14587 [WFLY-15184] MicroProfile Health HTTP endpoint test cases double clos…
  testsuite/integration/manualmode/src/test/java/org/wildfly/test/manual/microprofile/health/MicroProfileHealthDefaultEmptyStartupHTTPEndpointTestCase.java
  testsuite/integration/microprofile/src/test/java/org/wildfly/test/integration/microprofile/health/MicroProfileHealthApplicationStartupHTTPEndpointTestCase.java
  testsuite/integration/microprofile/src/test/java/org/wildfly/test/integration/microprofile/health/MicroProfileHealthApplicationWithoutStartupHTTPEndpointTestCase.java
Labels: deps-ok

#14562 [WFLY-11566] EJB: make a bean class a superclass to a proxy
  ee/src/main/java/org/jboss/as/ee/component/DefaultComponentViewConfigurator.java
  ee/src/main/java/org/jboss/as/ee/component/ViewDescription.java
  ejb3/src/main/java/org/jboss/as/ejb3/component/EJBViewDescription.java
  ejb3/src/main/java/org/jboss/as/ejb3/component/session/SessionBeanObjectViewConfigurator.java
  ejb3/src/main/java/org/jboss/as/ejb3/logging/EjbLogger.java
Labels: deps-ok

#14591 [WFLY-15190]: Upgrade generic jms resource adapter to 2.0.10.Final an…d use jakarta native namespace components in WF preview.
  ee-9/feature-pack/pom.xml
  ee-9/feature-pack/src/main/resources/modules/system/layers/base/org/jboss/genericjms/main/META-INF/ra.xml
  ee-9/feature-pack/src/main/resources/modules/system/layers/base/org/jboss/genericjms/main/module.xml
  pom.xml
Labels: deps-ok

#14577 WFLY-15039 BroadcastCommandDispatcherFactory instances should be shared across server resources.
  messaging-activemq/subsystem/src/main/java/org/wildfly/extension/messaging/activemq/MessagingExtension.java
  messaging-activemq/subsystem/src/main/java/org/wildfly/extension/messaging/activemq/MessagingServices.java
  messaging-activemq/subsystem/src/main/java/org/wildfly/extension/messaging/activemq/MessagingSubsystemAdd.java
  messaging-activemq/subsystem/src/main/java/org/wildfly/extension/messaging/activemq/MessagingSubsystemParser_1_0.java
  messaging-activemq/subsystem/src/main/java/org/wildfly/extension/messaging/activemq/MessagingSubsystemRootResourceDefinition.java
  messaging-activemq/subsystem/src/main/java/org/wildfly/extension/messaging/activemq/ServerAdd.java
  messaging-activemq/subsystem/src/main/java/org/wildfly/extension/messaging/activemq/ServerDefinition.java
  messaging-activemq/subsystem/src/main/java/org/wildfly/extension/messaging/activemq/broadcast/BroadcastCommandDispatcherFactoryInstaller.java
  messaging-activemq/subsystem/src/main/java/org/wildfly/extension/messaging/activemq/jms/ExternalConnectionFactoryAdd.java
  messaging-activemq/subsystem/src/main/java/org/wildfly/extension/messaging/activemq/jms/ExternalPooledConnectionFactoryService.java
Labels: deps-ok

#14589 [WFLY-15188]: Upgrade artemis-wildfly-integration to 1.0.5 in WildFly Preview.
  ee-9/feature-pack/pom.xml
  ee-feature-pack/common/src/main/resources/modules/system/layers/base/org/wildfly/extension/messaging-activemq/main/module.xml
Labels: deps-ok

#14567 [WFLY-15044] Avoid Nullpointer (EJB)
  ejb3/src/main/java/org/jboss/as/ejb3/component/messagedriven/MessageDrivenComponentCreateService.java
  ejb3/src/main/java/org/jboss/as/ejb3/deployment/processors/dd/MethodResolutionUtils.java
  ejb3/src/main/java/org/jboss/as/ejb3/iiop/RemoteObjectSubstitutionService.java
Labels: deps-ok
