Repository wildfly/wildfly, pull requests merged in 2021-09, with the labels that each got.

#14594 WFLY-15164 Drop distributable-web subsystem model versions/transforme…
  clustering/common/src/main/java/org/jboss/as/clustering/controller/Model.java
  clustering/web/extension/src/main/java/org/wildfly/extension/clustering/web/DistributableWebModel.java
  clustering/web/extension/src/main/java/org/wildfly/extension/clustering/web/RankedAffinityResourceTransformer.java
  clustering/web/extension/src/test/java/org/wildfly/extension/clustering/web/DistributableWebTransformerTestCase.java
Labels: deps-ok

#14596 [WFLY-15115] Upgrade WildFly Core 17.0.0.Beta5
  pom.xml
Labels: deps-ok

#14376 [WFLY-14899 - Document env var expression resolution
  docs/src/main/asciidoc/_admin-guide/management-api/Description_of_the_Management_Model.adoc
  docs/src/main/asciidoc/_admin-guide/management-api/Detyped_management_and_the_jboss-dmr_library.adoc
Labels: core-upgrade-needed, Feature-Docs, deps-ok

#14581 [WFLY-15174] Use commons-lang3 only, remove commons-lang(2) uses
  ee-feature-pack/common/pom.xml
  ee-feature-pack/common/src/main/resources/license/ee-feature-pack-common-licenses.xml
  ee-feature-pack/common/src/main/resources/modules/system/layers/base/com/microsoft/azure/storage/main/module.xml
  ee-feature-pack/common/src/main/resources/modules/system/layers/base/org/apache/commons/lang/main/module.xml
  jsf/multi-jsf-installer/src/main/resources/myfaces-api-module.xml
  testsuite/integration/basic/pom.xml
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/deployment/structure/war/symboliclink/SymlinkingUnitTestCase.java
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/security/loginmodules/LdapExtLDAPServerSetupTask.java
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/security/loginmodules/LdapExtLikeAdvancedLdapLMTestCase.java
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/security/loginmodules/LdapExtLoginModuleTestCase.java
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/security/loginmodules/negotiation/AdvancedLdapLoginModuleTestCase.java
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/security/loginmodules/negotiation/PropagateIdentityServlet.java
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/security/loginmodules/negotiation/SPNEGOLoginModuleTestCase.java
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/security/xacml/JBossPDPInteroperabilityTestCase.java
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/security/xacml/XACMLTestUtils.java
  testsuite/integration/clustering/src/test/java/org/jboss/as/test/clustering/cluster/ejb/remote/ClientClusterNodeSelectorTestCase.java
  testsuite/integration/clustering/src/test/java/org/jboss/as/test/clustering/cluster/ejb/remote/SuspendResumeRemoteEJBTestCase.java
  testsuite/integration/elytron/src/test/java/org/wildfly/test/integration/elytron/rolemappers/AbstractRoleMapperTest.java
  testsuite/integration/manualmode/src/test/java/org/jboss/as/test/manualmode/security/OutboundLdapConnectionClientCertTestCase.java
  testsuite/integration/manualmode/src/test/java/org/jboss/as/test/manualmode/security/OutboundLdapConnectionTestCase.java
  testsuite/integration/manualmode/src/test/java/org/jboss/as/test/manualmode/web/ssl/AbstractCertificateLoginModuleTestCase.java
  testsuite/integration/manualmode/src/test/java/org/jboss/as/test/manualmode/web/ssl/HTTPSWebConnectorTestCase.java
  testsuite/integration/picketlink/src/test/java/org/wildfly/test/integration/security/picketlink/idm/util/LdapServerSetupTask.java
  testsuite/integration/ws/src/test/java/org/jboss/as/test/integration/ws/basic/EJBEndpointTestCase.java
  testsuite/integration/ws/src/test/java/org/jboss/as/test/integration/ws/basic/PojoEndpointTestCase.java
  testsuite/integration/xts/src/test/java/org/jboss/as/test/txbridge/fromjta/BridgeFromJTATestCase.java
  testsuite/integration/xts/src/test/java/org/jboss/as/test/xts/annotation/client/CompensatableTestCase.java
  testsuite/integration/xts/src/test/java/org/jboss/as/test/xts/annotation/client/TransactionalTestCase.java
  testsuite/integration/xts/src/test/java/org/jboss/as/test/xts/suspend/wsat/AtomicTransactionSuspendTestCase.java
  testsuite/integration/xts/src/test/java/org/jboss/as/test/xts/suspend/wsba/BusinessActivitySuspendTestCase.java
  testsuite/integration/xts/src/test/java/org/jboss/as/test/xts/wsat/client/ATTestCase.java
  testsuite/integration/xts/src/test/java/org/jboss/as/test/xts/wsba/coordinatorcompletion/client/BACoordinatorCompletionTestCase.java
  testsuite/shared/src/main/java/org/jboss/as/test/integration/security/common/AbstractDataSourceServerSetupTask.java
  testsuite/shared/src/main/java/org/jboss/as/test/integration/security/common/AbstractKrb5ConfServerSetupTask.java
  testsuite/shared/src/main/java/org/jboss/as/test/integration/security/common/AbstractSecurityDomainsServerSetupTask.java
  testsuite/shared/src/main/java/org/jboss/as/test/integration/security/common/RolesPrintingServletUtils.java
  testsuite/shared/src/main/java/org/jboss/as/test/integration/security/common/Utils.java
  testsuite/shared/src/main/java/org/wildfly/test/security/common/elytron/SimpleTrustManager.java
Labels: deps-changed

#14571 [WFLY-14871] Logic in try/finally blocks hides exceptions (Appclient)
  appclient/src/main/java/org/jboss/as/appclient/service/ApplicationClientStartService.java
Labels: deps-ok

#14602 [WFLY-15194] Update jsoup version
  pom.xml
Labels: ready-for-merge, deps-ok

#14628 [WFLY-15023][WFCORE-5572] Add infrastructure to allow jakarta version expressions in module.xml files in WildFly Core feature packs
  ee-9/feature-pack/pom.xml
  ee-feature-pack/galleon-feature-pack/pom.xml
  servlet-feature-pack/galleon-feature-pack/pom.xml
Labels: deps-ok

#14621 [WFLY-15215] Drop mail model transformers prior to 4.0.0
  mail/src/main/java/org/jboss/as/mail/extension/MailTransformers.java
  mail/src/main/resources/META-INF/services/org.jboss.as.controller.transform.ExtensionTransformerRegistration
  mail/src/test/java/org/jboss/as/mail/extension/MailTransformersTestCase.java
  mail/src/test/resources/org/jboss/as/mail/extension/mail_4_0-reject.xml
  mail/src/test/resources/org/jboss/as/mail/extension/mail_4_0-transformers.xml
Labels: deps-ok

#14617 [WFLY-15213] MicroProfileHealthDefaultEmpty*HTTPEndpointTestCase manu…
  health/src/main/java/org/wildfly/extension/health/HealthContextService.java
Labels: deps-ok

#14627 [WFLY-15020] Add an ejb-http-invoker layer
  docs/src/main/asciidoc/_galleon/Galleon_layers.adoc
  ee-feature-pack/galleon-common/src/main/resources/feature_groups/application-http-basic.xml
  ee-feature-pack/galleon-common/src/main/resources/feature_groups/undertow-http-invoker.xml
  ee-feature-pack/galleon-common/src/main/resources/layers/standalone/ejb-http-invoker/layer-spec.xml
  ee-feature-pack/galleon-content/src/main/resources/feature_groups/basic-profile.xml
  servlet-feature-pack/galleon-feature-pack/src/main/resources/configs/standalone/standalone.xml/config.xml
  servlet-feature-pack/galleon-pruned/src/main/resources/feature_groups/servlet-basic-profile.xml
  servlet-feature-pack/galleon-pruned/src/main/resources/feature_groups/servlet-domain-profile.xml
  servlet-feature-pack/galleon-pruned/src/main/resources/feature_groups/servlet-standalone-profile.xml
  servlet-feature-pack/galleon-pruned/src/main/resources/feature_groups/undertow.xml
  testsuite/layers/pom.xml
Labels: deps-ok

#14616 [WFLY-15211] Remove unused module references from LayersTestCase
  testsuite/layers/src/test/java/org/jboss/as/test/layers/LayersTestCase.java
Labels: deps-ok

#14607 WFLY-15192 Reduce the usage of TimeHandle in ejb timer service; and g…
  ejb3/src/main/java/org/jboss/as/ejb3/timerservice/CalendarTimer.java
  ejb3/src/main/java/org/jboss/as/ejb3/timerservice/TimerImpl.java
  ejb3/src/main/java/org/jboss/as/ejb3/timerservice/TimerServiceImpl.java
  ejb3/src/main/java/org/jboss/as/ejb3/timerservice/persistence/database/DatabaseTimerPersistence.java
Labels: deps-ok

#14597 WFLY-15193 Upgrade smallrye-open-api to 2.1.10
  pom.xml
Labels: deps-ok

#14601 [WFLY-15197]: Fixing how elytron configuration is applied.
  testsuite/integration/manualmode/pom.xml
  testsuite/integration/manualmode/src/test/java/org/wildfly/test/manual/elytron/seccontext/AbstractSecurityContextPropagationTestBase.java
  testsuite/integration/manualmode/src/test/java/org/wildfly/test/manual/elytron/seccontext/seccontext-setup.cli
  testsuite/shared/enable-elytron-manualmode.cli
Labels: deps-ok

#14605 [WFLY-15153] Upgrade ironjacamar to 1.5.1.Final
  connector/src/main/java/org/jboss/as/connector/subsystems/datasources/AbstractDataSourceService.java
  pom.xml
Labels: deps-ok

#14603 [WFLY-15147][WFLY-15148] Move WildFly Preview to the available undertow -jakartaee9 artifacts
  ee-9/feature-pack/pom.xml
  ee-9/feature-pack/src/main/resources/license/preview-feature-pack-licenses.xml
  pom.xml
  servlet-feature-pack/common/src/main/resources/modules/system/layers/base/io/undertow/servlet/main/module.xml
  servlet-feature-pack/common/src/main/resources/modules/system/layers/base/io/undertow/websocket/main/module.xml
Labels: deps-ok

#14636 WFLY-15192 Reduce the usage of TimeHandle in ejb timer service (fix N…
  ejb3/src/main/java/org/jboss/as/ejb3/timerservice/TimerImpl.java
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/ejb/timerservice/simple/SimpleTimerServiceTestCase.java
Labels: deps-ok

#14634 [WFLY-15032] Use jboss-invocation-jakarta version for WildFly Preview
  ee-9/feature-pack/pom.xml
  ee-9/feature-pack/src/main/resources/license/preview-feature-pack-licenses.xml
Labels: deps-ok

#14638 [WFLY-15250] Remove security-realm operations from CLI script.
  testsuite/shared/enable-elytron-manualmode.cli
Labels: deps-ok

#14629 [WFLY-15230] Update the Elytron schema version specified in test configs
  testsuite/domain/src/test/resources/domain-configs/domain-standard-ee.xml
  testsuite/domain/src/test/resources/domain-configs/domain-standard.xml
  testsuite/domain/src/test/resources/host-configs/host-master.xml
  testsuite/domain/src/test/resources/host-configs/host-slave.xml
  testsuite/mixed-domain/src/test/resources/master-config/host.xml
Labels: Blocker, deps-ok

#14619 [WFLY-14932] MP Reactive Messaging Kafka user API
  docs/src/main/asciidoc/_admin-guide/subsystem-configuration/MicroProfile_Reactive_Messsaging_SmallRye.adoc
  testsuite/integration/microprofile/pom.xml
  testsuite/integration/microprofile/src/test/java/org/wildfly/test/integration/microprofile/opentracing/ResourceWithCustomOperationNameNoTopicSetupOverrideForAllMessagesTestCase.java
  testsuite/integration/microprofile/src/test/java/org/wildfly/test/integration/microprofile/reactive/RunKafkaSetupTask.java
  testsuite/integration/microprofile/src/test/java/org/wildfly/test/integration/microprofile/reactive/messaging/kafka/api/ConfiguredToSendToTopicAndOverrideTopicForSomeMessagesBean.java
  testsuite/integration/microprofile/src/test/java/org/wildfly/test/integration/microprofile/reactive/messaging/kafka/api/InDepthMetadataBean.java
  testsuite/integration/microprofile/src/test/java/org/wildfly/test/integration/microprofile/reactive/messaging/kafka/api/NoTopicSetupOverrideForAllMessagesBean.java
  testsuite/integration/microprofile/src/test/java/org/wildfly/test/integration/microprofile/reactive/messaging/kafka/api/ReactiveMessagingKafkaUserApiTestCase.java
  testsuite/integration/microprofile/src/test/java/org/wildfly/test/integration/microprofile/reactive/messaging/kafka/api/SpecifyPartitionBean.java
  testsuite/integration/microprofile/src/test/java/org/wildfly/test/integration/microprofile/reactive/messaging/kafka/api/microprofile-config.properties
  testsuite/integration/microprofile/src/test/java/org/wildfly/test/integration/microprofile/reactive/messaging/kafka/serializer/Bean.java
  testsuite/integration/microprofile/src/test/java/org/wildfly/test/integration/microprofile/reactive/messaging/kafka/serializer/ReactiveMessagingKafkaSerializerTestCase.java
  testsuite/integration/microprofile/src/test/java/org/wildfly/test/integration/microprofile/reactive/messaging/kafka/tx/ReactiveMessagingKafkaTestCase.java
  testsuite/integration/microprofile/src/test/java/org/wildfly/test/integration/microprofile/reactive/messaging/rest/channels/EmitterToChannelPublisherViaKafkaEndpoint.java
  testsuite/integration/microprofile/src/test/java/org/wildfly/test/integration/microprofile/reactive/messaging/rest/channels/ReactiveMessagingChannelsTestCase.java
Labels: Feature, missing-reqs, deps-ok

#14641 [WFLY-15014] Upgrade to MP Reactive Messaging API (and TCK) 2.0.1
  pom.xml
  testsuite/integration/microprofile-tck/reactive-messaging/pom.xml
Labels: deps-ok

#14615 [WFLY-15210] Remove MP extensions and subsystem from default configur…
  testsuite/mixed-domain/src/test/java/org/jboss/as/test/integration/domain/mixed/DomainAdjuster.java
  testsuite/mixed-domain/src/test/java/org/jboss/as/test/integration/domain/mixed/eap740/DomainAdjuster740.java
Labels: deps-ok

#14643 [WFLY-15265] Add jackson-core dep to MP Health TCK module to prevent …
  testsuite/integration/microprofile-tck/health/pom.xml
Labels: deps-ok

#14579 WFLY-15162 Drop deprecated interfaces/classes/methods from wildfly-clustering-singleton-api
  clustering/singleton/api/src/main/java/org/wildfly/clustering/singleton/Singleton.java
  clustering/singleton/api/src/main/java/org/wildfly/clustering/singleton/SingletonServiceName.java
Labels: deps-ok

#14649 [WFLY-15277] Upgrade WildFly Core 17.0.0.Beta7
  pom.xml
Labels: deps-ok

#14631 WFLY-15198 Avoid unneeded TimerImpl instances during db refresh
  ejb3/src/main/java/org/jboss/as/ejb3/timerservice/TimerServiceImpl.java
  ejb3/src/main/java/org/jboss/as/ejb3/timerservice/TimerState.java
  ejb3/src/main/java/org/jboss/as/ejb3/timerservice/persistence/database/DatabaseTimerPersistence.java
  ejb3/src/main/java/org/jboss/as/ejb3/timerservice/persistence/filestore/FileTimerPersistence.java
Labels: deps-ok

#14613 [WFLY-15208] Compare Objects with correct type or method (jaxrs)
  jaxrs/src/main/java/org/jboss/as/jaxrs/deployment/JaxrsIntegrationProcessor.java
Labels: ready-for-merge, deps-ok

#14612 [WFLY-15208] Compare Objects with correct type or method (EJB)
  ejb3/src/main/java/org/jboss/as/ejb3/util/EjbValidationsUtil.java
Labels: deps-ok

#14653 [WFLY-15281] JsonParsingException in MicroProfileHealthDefaultEmpty*H…
  health/src/main/java/org/wildfly/extension/health/HealthContextService.java
Labels: deps-ok

#14630 [WFLY-15228] Improve RA and DS subsystems' handling of the absence of…
  connector/src/main/java/org/jboss/as/connector/deployers/ds/processors/DsXmlDeploymentInstallProcessor.java
  connector/src/main/java/org/jboss/as/connector/deployers/ra/ConnectionFactoryDefinitionAnnotationProcessor.java
  connector/src/main/java/org/jboss/as/connector/deployers/ra/ConnectionFactoryDefinitionDescriptorProcessor.java
  connector/src/main/java/org/jboss/as/connector/deployers/ra/ConnectionFactoryDefinitionInjectionSource.java
  connector/src/main/java/org/jboss/as/connector/deployers/ra/RaDeploymentActivator.java
  connector/src/main/java/org/jboss/as/connector/deployers/ra/processors/ParsedRaDeploymentProcessor.java
  connector/src/main/java/org/jboss/as/connector/logging/ConnectorLogger.java
  connector/src/main/java/org/jboss/as/connector/metadata/api/resourceadapter/ActivationSecurityUtil.java
  connector/src/main/java/org/jboss/as/connector/services/resourceadapters/DirectConnectionFactoryActivatorService.java
  connector/src/main/java/org/jboss/as/connector/subsystems/datasources/AbstractDataSourceAdd.java
  connector/src/main/java/org/jboss/as/connector/subsystems/datasources/DataSourcesSubsystemAdd.java
  connector/src/main/java/org/jboss/as/connector/subsystems/jca/JcaSubsystemAdd.java
  connector/src/main/java/org/jboss/as/connector/subsystems/resourceadapters/ConnectionDefinitionAdd.java
  connector/src/main/java/org/jboss/as/connector/subsystems/resourceadapters/ConnectionDefinitionService.java
  connector/src/main/java/org/jboss/as/connector/subsystems/resourceadapters/RaAdd.java
  messaging-activemq/subsystem/src/main/java/org/wildfly/extension/messaging/activemq/MessagingSubsystemAdd.java
  messaging-activemq/subsystem/src/main/java/org/wildfly/extension/messaging/activemq/deployment/JMSConnectionFactoryDefinitionAnnotationProcessor.java
  messaging-activemq/subsystem/src/main/java/org/wildfly/extension/messaging/activemq/deployment/JMSConnectionFactoryDefinitionInjectionSource.java
  testsuite/integration/smoke/pom.xml
Labels: deps-ok

#14675 [WFLY-15307] AppClient o.j.a.a.s.parsing.AppClientXml readServerElement_18
  appclient/src/main/java/org/jboss/as/appclient/subsystem/parsing/AppClientXml.java
Labels: deps-ok

#14673 [WFLY-14798] Fix TCK on EE9
  testsuite/integration/microprofile-tck/reactive-messaging/src/test/java/org/wildfly/test/integration/mp/tck/reactive/messaging/WildFlyDeploymentExceptionTransformer.java
Labels: deps-ok

#14658 WFLY-15232 Persisted AutoTimer doesn't pick up TimerConfig.info change
  ejb3/src/main/java/org/jboss/as/ejb3/timerservice/TimerServiceImpl.java
Labels: deps-ok

#14654 [WFLY-15282] Narayana 5.12.1.Final component upgrade
  pom.xml
Labels: deps-ok

#14679 Allow testsuite/integration/basic execution with the ts.ee9 profile (round2)
  testsuite/integration/basic/pom.xml
Labels: deps-ok

#14669 [WFLY-15199] Remove elytron profile from domain testsuite.
  testsuite/domain/pom.xml
Labels: deps-ok

#14651 [WFLY-15235] Upgrade jakarta.el from 3.0.3.jbossorg-3 to 3.0.3.jbosso…
  pom.xml
Labels: deps-ok

#14683 [WFLY-15315] Move Open Telemetry mixed domains tweaks to base DomainA…
  testsuite/mixed-domain/src/test/java/org/jboss/as/test/integration/domain/mixed/DomainAdjuster.java
  testsuite/mixed-domain/src/test/java/org/jboss/as/test/integration/domain/mixed/eap740/DomainAdjuster740.java
Labels: deps-ok

#14685 Fix for WFLY-15320, Upgrade galleon-plugins to 5.2.2.Final
  pom.xml
Labels: deps-ok

#14690 [WFLY-15313] Upgrade module version to 1.9 (jsf)
  jsf/multi-jsf-installer/src/main/resources/mojarra-api-module.xml
  jsf/multi-jsf-installer/src/main/resources/mojarra-impl-module.xml
  jsf/multi-jsf-installer/src/main/resources/mojarra-injection-module.xml
  jsf/multi-jsf-installer/src/main/resources/myfaces-api-module.xml
  jsf/multi-jsf-installer/src/main/resources/myfaces-digester-module.xml
  jsf/multi-jsf-installer/src/main/resources/myfaces-impl-module.xml
  jsf/multi-jsf-installer/src/main/resources/myfaces-injection-module.xml
Labels: deps-ok

#14688 [WFLY-15313] Upgrade module version to 1.9 (documentation)
  docs/src/main/asciidoc/_admin-guide/Security_Realms_Plugins.adoc
  docs/src/main/asciidoc/_admin-guide/subsystem-configuration/EE_Application_Deployment_Configuration.adoc
  docs/src/main/asciidoc/_admin-guide/subsystem-configuration/Messaging.adoc
  docs/src/main/asciidoc/_developer-guide/Class_Loading_in_WildFly.adoc
  docs/src/main/asciidoc/_developer-guide/Jakarta_Persistence_Reference_Guide.adoc
  docs/src/main/asciidoc/_extending-wildfly/Example_subsystem.adoc
Labels: deps-ok

#14668 [WFLY-15299] Kafka user API module should be visible to users
  microprofile/galleon-common/src/main/resources/modules/system/layers/base/io/smallrye/reactive/converters/api/main/module.xml
  microprofile/galleon-common/src/main/resources/modules/system/layers/base/io/smallrye/reactive/messaging/connector/kafka/api/main/module.xml
  microprofile/galleon-common/src/main/resources/modules/system/layers/base/io/smallrye/reactive/messaging/connector/kafka/main/module.xml
  microprofile/galleon-common/src/main/resources/modules/system/layers/base/io/smallrye/reactive/messaging/connector/main/module.xml
  microprofile/galleon-common/src/main/resources/modules/system/layers/base/io/smallrye/reactive/messaging/main/module.xml
  microprofile/galleon-common/src/main/resources/modules/system/layers/base/io/smallrye/reactive/mutiny/vertx-core/main/module.xml
  microprofile/galleon-common/src/main/resources/modules/system/layers/base/io/smallrye/reactive/mutiny/vertx-kafka-client/main/module.xml
  microprofile/galleon-common/src/main/resources/modules/system/layers/base/io/smallrye/reactive/mutiny/vertx-runtime/main/module.xml
  microprofile/galleon-common/src/main/resources/modules/system/layers/base/io/vertx/client/kafka/main/module.xml
  microprofile/galleon-common/src/main/resources/modules/system/layers/base/io/vertx/client/main/module.xml
  microprofile/galleon-common/src/main/resources/modules/system/layers/base/io/vertx/core/main/module.xml
  microprofile/galleon-common/src/main/resources/modules/system/layers/base/org/apache/kafka/client/main/module.xml
  microprofile/galleon-common/src/main/resources/modules/system/layers/base/org/eclipse/microprofile/reactive-messaging/api/main/module.xml
  microprofile/galleon-common/src/main/resources/modules/system/layers/base/org/eclipse/microprofile/reactive-streams-operators/api/main/module.xml
  microprofile/galleon-common/src/main/resources/modules/system/layers/base/org/eclipse/microprofile/reactive-streams-operators/core/main/module.xml
  microprofile/galleon-common/src/main/resources/modules/system/layers/base/org/wildfly/extension/microprofile/reactive-messaging-smallrye/main/module.xml
  microprofile/galleon-common/src/main/resources/modules/system/layers/base/org/wildfly/extension/microprofile/reactive-streams-operators-smallrye/main/module.xml
  microprofile/galleon-common/src/main/resources/modules/system/layers/base/org/wildfly/reactive/messaging/common/main/module.xml
  microprofile/galleon-common/src/main/resources/modules/system/layers/base/org/wildfly/reactive/messaging/config/main/module.xml
  microprofile/galleon-common/src/main/resources/modules/system/layers/base/org/wildfly/reactive/messaging/kafka/main/module.xml
Labels: deps-ok

#14693 [WFLY-14798] Upgrade to latest SmallRye Reactive Messaging
  pom.xml
Labels: deps-ok

#14686 [WFLY-15316] Update jose4j to 0.7.9
  pom.xml
Labels: deps-ok

#14663 WFLY-15291 Upgrade jberet-core from 2.0.1.Final to 2.0.2.Final in ee-…
  ee-9/feature-pack/pom.xml
Labels: deps-ok

#14659 [WFLY-15222] Drop JAX-RS model transformers prior to 3.0.0
  jaxrs/src/main/java/org/jboss/as/jaxrs/JaxrsTransformers.java
  jaxrs/src/main/resources/META-INF/services/org.jboss.as.controller.transform.ExtensionTransformerRegistration
  jaxrs/src/test/java/org/jboss/as/jaxrs/JaxrsSubsystemTestCase.java
  jaxrs/src/test/java/org/jboss/as/jaxrs/JaxrsTransformersTestCase.java
Labels: deps-ok

#14656 [WFLY-15219] Drop EE model transformers prior to 6.0.0
  ee/src/main/java/org/jboss/as/ee/subsystem/EETransformers.java
  ee/src/main/resources/META-INF/services/org.jboss.as.controller.transform.ExtensionTransformerRegistration
  ee/src/test/java/org/jboss/as/ee/subsystem/EeSubsystemTestCase.java
  ee/src/test/resources/org/jboss/as/ee/subsystem/subsystem-transformers-discard.xml
  ee/src/test/resources/org/jboss/as/ee/subsystem/subsystem-transformers.xml
  ee/src/test/resources/org/jboss/as/ee/subsystem/subsystem-wf8-transformer.xml
Labels: deps-ok

#14640 [WFLY-15254] Remove unneeded javax.transaction.api dependency from or…
  servlet-feature-pack/common/src/main/resources/modules/system/layers/base/org/wildfly/http-client/common/main/module.xml
  servlet-feature-pack/common/src/main/resources/modules/system/layers/base/org/wildfly/http-client/naming/main/module.xml
Labels: deps-ok

#14622 [WFLY-15216] Drop JSF model transformers prior to 1.1.0
  jsf/subsystem/src/main/java/org/jboss/as/jsf/subsystem/JSFTransformers.java
  jsf/subsystem/src/main/resources/META-INF/services/org.jboss.as.controller.transform.ExtensionTransformerRegistration
  jsf/subsystem/src/test/java/org/jboss/as/jsf/subsystem/JSFSubsystemTransformersTestCase.java
  jsf/subsystem/src/test/resources/jsf-transformers-reject.xml
  jsf/subsystem/src/test/resources/jsf-transformers.xml
Labels: deps-ok

#14624 [WFLY-8124] Unifies arquillian default protocols in testsuite
  testsuite/integration/rts/src/test/config/arq/arquillian.xml
  testsuite/integration/xts/src/test/config/arq/arquillian.xml
Labels: deps-ok

#14611 [WFLY-15207] Compare Strings with equals method (Metrics)
  metrics/src/main/java/org/wildfly/extension/metrics/MetricMetadata.java
  metrics/src/main/java/org/wildfly/extension/metrics/PrometheusExporter.java
Labels: deps-ok

#14610 [WFLY-15207] Compare Strings with equals method (EJB)
  ejb3/src/main/java/org/jboss/as/ejb3/deployment/processors/EjbJndiBindingsDeploymentUnitProcessor.java
Labels: deps-ok

#14609 [WFLY-15206] EJB CalendarBasedTimeoutTestCase assertion type must match
  ejb3/src/test/java/org/jboss/as/ejb3/timer/schedule/CalendarBasedTimeoutTestCase.java
Labels: deps-ok

#14606 [WFLY-15204] Updating JAXP error log processing tests to be JAXP implementation independent
  testsuite/integration/vdx/src/test/java/org/wildfly/test/integration/vdx/domain/HostXmlSmokeTestCase.java
  testsuite/integration/vdx/src/test/java/org/wildfly/test/integration/vdx/domain/JBossWSDomainTestCase.java
  testsuite/integration/vdx/src/test/java/org/wildfly/test/integration/vdx/standalone/InvalidCharactersTestCase.java
  testsuite/integration/vdx/src/test/java/org/wildfly/test/integration/vdx/standalone/JBossWSTestCase.java
  testsuite/integration/vdx/src/test/java/org/wildfly/test/integration/vdx/standalone/LoggingTestCase.java
  testsuite/integration/vdx/src/test/java/org/wildfly/test/integration/vdx/standalone/MissingClosingTagTestCase.java
  testsuite/integration/vdx/src/test/java/org/wildfly/test/integration/vdx/standalone/SmokeStandaloneTestCase.java
Labels: deps-ok

#14568 [WFLY-15044] Avoid Nullpointer (EE)
  ee/src/main/java/org/jboss/as/ee/component/ManagedReferenceMethodInjectionInterceptorFactory.java
  ee/src/main/java/org/jboss/as/ee/component/deployers/ModuleJndiBindingProcessor.java
  ee/src/main/java/org/jboss/as/ee/logging/EeLogger.java
Labels: deps-ok

#14660 [WFLY-15242] Drop Naming model transformers prior to 2.1.0
  naming/src/main/java/org/jboss/as/naming/subsystem/NamingTransformers.java
  naming/src/main/resources/META-INF/services/org.jboss.as.controller.transform.ExtensionTransformerRegistration
  naming/src/test/java/org/jboss/as/naming/subsystem/NamingSubsystemTestCase.java
Labels: deps-ok

#14689 Fix for WFLY-15322, Upgrade bootable jar to 5.0.2.Final
  pom.xml
Labels: deps-ok

#14697 [WFLY-15333] Replace org.wildfly by project.groupId where possible
  ee-feature-pack/common/pom.xml
  microprofile/reactive-messaging-smallrye/kafka/pom.xml
  observability/opentelemetry/pom.xml
  testsuite/integration/elytron-oidc-client/pom.xml
Labels: deps-ok

#14692 [WFLY-15220] Drop EJB3 model transformers prior to 9.0.0
  ejb3/src/main/java/org/jboss/as/ejb3/subsystem/EJBTransformers.java
  ejb3/src/main/resources/META-INF/services/org.jboss.as.controller.transform.ExtensionTransformerRegistration
  ejb3/src/test/java/org/jboss/as/ejb3/subsystem/Ejb3TransformersTestCase.java
  ejb3/src/test/resources/org/jboss/as/ejb3/subsystem/subsystem-ejb3-transform-reject.xml
  ejb3/src/test/resources/org/jboss/as/ejb3/subsystem/subsystem-ejb3-transform.xml
Labels: deps-ok

#14677 [WFLY-15246] Drop Weld model transformers prior to 4.0.0
  weld/subsystem/src/main/java/org/jboss/as/weld/WeldTransformers.java
  weld/subsystem/src/main/resources/META-INF/services/org.jboss.as.controller.transform.ExtensionTransformerRegistration
  weld/subsystem/src/test/java/org/jboss/as/weld/WeldSubsystemTestCase.java
  weld/subsystem/src/test/resources/org/jboss/as/weld/subsystem-reject.xml
  weld/subsystem/src/test/resources/org/jboss/as/weld/subsystem_3_0-transformers.xml
  weld/subsystem/src/test/resources/org/jboss/as/weld/subsystem_4_0-transformers.xml
Labels: deps-ok

#14657 [WFLY-15241] Drop Microprofile Metrics model transformers prior to 2.0.0
  microprofile/metrics-smallrye/src/main/java/org/wildfly/extension/microprofile/metrics/MicroProfileMetricsTransformers.java
  microprofile/metrics-smallrye/src/main/resources/META-INF/services/org.jboss.as.controller.transform.ExtensionTransformerRegistration
Labels: deps-ok

#14696 [WFLY-15332] Fix HostExcludesTestCase and correct the host-exclusion …
  ee-feature-pack/galleon-common/src/main/resources/feature_groups/domain-host-excludes.xml
  testsuite/domain/src/test/java/org/jboss/as/test/integration/domain/HostExcludesTestCase.java
Labels: deps-ok

#14694 [WFLY-15292] / [WFLY-15298] Clean up in the elytron-oidc-client subsystem
  elytron-oidc-client/subsystem/src/main/java/org/wildfly/extension/elytron/oidc/CredentialDefinition.java
  elytron-oidc-client/subsystem/src/main/java/org/wildfly/extension/elytron/oidc/ElytronOidcSubsystemAdd.java
  elytron-oidc-client/subsystem/src/main/java/org/wildfly/extension/elytron/oidc/OidcConfigService.java
  elytron-oidc-client/subsystem/src/main/java/org/wildfly/extension/elytron/oidc/ProviderDefinition.java
  elytron-oidc-client/subsystem/src/main/java/org/wildfly/extension/elytron/oidc/RealmDefinition.java
  elytron-oidc-client/subsystem/src/main/java/org/wildfly/extension/elytron/oidc/RedirectRewriteRuleDefinition.java
  elytron-oidc-client/subsystem/src/main/java/org/wildfly/extension/elytron/oidc/SecureDeploymentDefinition.java
  elytron-oidc-client/subsystem/src/main/java/org/wildfly/extension/elytron/oidc/_private/ElytronOidcLogger.java
Labels: deps-ok

#14633 [WFLY-15218] Drop Agroal model transformers prior to 2.0.0
  datasources-agroal/src/main/java/org/wildfly/extension/datasources/agroal/AgroalTransformers.java
  datasources-agroal/src/main/resources/META-INF/services/org.jboss.as.controller.transform.ExtensionTransformerRegistration
  datasources-agroal/src/test/java/org/wildfly/extension/datasources/agroal/AgroalTransformersTestCase.java
  datasources-agroal/src/test/resources/org/wildfly/extension/datasources/agroal/agroal_2_0-full.xml
  datasources-agroal/src/test/resources/org/wildfly/extension/datasources/agroal/agroal_2_0-reject.xml
  datasources-agroal/src/test/resources/org/wildfly/extension/datasources/agroal/agroal_2_0-transformers.xml
Labels: deps-ok

#14674 [WFLY-15305] Add the OpenTelemetry extension to the set for which the…
  ee-9/feature-pack/wildfly-feature-pack-build.xml
Labels: deps-ok

#14644 [WFLY-15267] Upgrade Netty to 4.1.68.
  pom.xml
Labels: deps-ok

#14700 [WFLY-15336] Correct the list of unused modules for LayersTestCase
  testsuite/layers/src/test/java/org/jboss/as/test/layers/LayersTestCase.java
Labels: deps-ok

#14701 [WFLY-15295] Upgrade HAL from 3.3.7.Final to 3.3.8.Final
  pom.xml
Labels: deps-ok

#14703 WFLY-15183 Upgrade jboss-ejb-client from 4.0.42.Final to 4.0.43.Final
  pom.xml
Labels: deps-ok

#14695 Remove duplicate declaration of picketbox version property and dependencies
  pom.xml
Labels: deps-ok

#14698 [WFLY-15297] Prevent OidcWithDeploymentConfigTest from failing if docker is not available
  testsuite/integration/elytron-oidc-client/src/test/java/org/wildfly/test/integration/elytron/oidc/client/deployment/OidcWithDeploymentConfigTest.java
Labels: deps-ok

#14706 [WFLY-15326] Upgrade RESTEasy to 4.7.2.Final.
  pom.xml
Labels: deps-ok

#14707 [WFLY-15337] Manual Model microprofile tests fail due to missing stan…
  testsuite/integration/manualmode/src/test/java/org/wildfly/test/manual/microprofile/health/MicroProfileHealthDefaultEmptyReadinessTestBase.java
  testsuite/integration/manualmode/src/test/java/org/wildfly/test/manual/microprofile/health/MicroProfileHealthDefaultEmptyStartupTestBase.java
  testsuite/shared/src/main/java/org/jboss/as/test/shared/util/AssumeTestGroupUtil.java
Labels: deps-ok

#14681 [WFLY-15314] Remove JBoss Negotiation.
  pom.xml
  security/subsystem/pom.xml
  security/subsystem/src/main/java/org/jboss/as/security/ModulesMap.java
  servlet-feature-pack/common/pom.xml
  servlet-feature-pack/common/src/main/resources/modules/system/layers/base/org/jboss/as/security/main/module.xml
  servlet-feature-pack/common/src/main/resources/modules/system/layers/base/org/jboss/security/negotiation/main/module.xml
  servlet-feature-pack/common/src/main/resources/modules/system/layers/base/org/wildfly/extension/undertow/main/module.xml
  testsuite/integration/basic/pom.xml
  testsuite/integration/clustering/src/test/java/org/jboss/as/test/clustering/cluster/web/ReplicationForNegotiationAuthenticatorTestCase.java
  testsuite/layers/src/test/java/org/jboss/as/test/layers/LayersTestCase.java
  undertow/src/main/java/org/wildfly/extension/undertow/ServletContainerAdd.java
Labels: deps-changed

#14650 WFLY-15165 Drop deprecated interfaces/classes/methods from wildfly-clustering-service
  clustering/common/src/main/java/org/jboss/as/clustering/controller/IdentityLegacyCapabilityServiceConfigurator.java
  clustering/common/src/main/java/org/jboss/as/clustering/msc/InjectedValueDependency.java
  clustering/common/src/main/java/org/jboss/as/clustering/msc/InjectorDependency.java
  clustering/common/src/main/java/org/jboss/as/clustering/msc/ValueDependency.java
  clustering/server/src/main/java/org/wildfly/clustering/server/singleton/AsynchronousServiceBuilder.java
  clustering/server/src/main/java/org/wildfly/clustering/server/singleton/DistributedSingletonServiceBuilder.java
  clustering/server/src/main/java/org/wildfly/clustering/server/singleton/DistributedSingletonServiceBuilderFactory.java
  clustering/server/src/main/java/org/wildfly/clustering/server/singleton/LocalSingletonServiceBuilderFactory.java
  clustering/service/src/main/java/org/wildfly/clustering/service/ActiveServiceSupplier.java
  clustering/service/src/main/java/org/wildfly/clustering/service/FunctionalValueService.java
  clustering/service/src/main/java/org/wildfly/clustering/service/FunctionalVoidService.java
  clustering/service/src/main/java/org/wildfly/clustering/service/GroupServiceNameFactory.java
  clustering/service/src/main/java/org/wildfly/clustering/service/InjectedValueDependency.java
  clustering/service/src/main/java/org/wildfly/clustering/service/InjectorDependency.java
  clustering/service/src/main/java/org/wildfly/clustering/service/MappedValueService.java
  clustering/service/src/main/java/org/wildfly/clustering/service/OptionalInjectedValue.java
  clustering/service/src/main/java/org/wildfly/clustering/service/PassiveServiceSupplier.java
  clustering/service/src/main/java/org/wildfly/clustering/service/PrivilegedActionSupplier.java
  clustering/service/src/main/java/org/wildfly/clustering/service/ServiceSupplier.java
  clustering/service/src/main/java/org/wildfly/clustering/service/SimpleDependency.java
  clustering/service/src/main/java/org/wildfly/clustering/service/SubGroupServiceNameFactory.java
  clustering/service/src/main/java/org/wildfly/clustering/service/SuppliedValueService.java
  clustering/service/src/main/java/org/wildfly/clustering/service/concurrent/CachedThreadPoolExecutorServiceBuilder.java
  clustering/service/src/main/java/org/wildfly/clustering/service/concurrent/CachedThreadPoolExecutorServiceConfigurator.java
  clustering/service/src/main/java/org/wildfly/clustering/service/concurrent/ClassLoaderThreadFactory.java
  clustering/service/src/main/java/org/wildfly/clustering/service/concurrent/RemoveOnCancelScheduledExecutorServiceBuilder.java
  clustering/service/src/main/java/org/wildfly/clustering/service/concurrent/RemoveOnCancelScheduledExecutorServiceConfigurator.java
  clustering/singleton/extension/src/main/java/org/wildfly/extension/clustering/singleton/AliasServiceBuilder.java
  clustering/singleton/extension/src/main/java/org/wildfly/extension/clustering/singleton/SingletonMetricExecutor.java
  clustering/singleton/extension/src/main/java/org/wildfly/extension/clustering/singleton/SingletonPolicyServiceHandler.java
  clustering/singleton/extension/src/main/java/org/wildfly/extension/clustering/singleton/SingletonServiceHandler.java
  ejb3/src/main/java/org/jboss/as/ejb3/component/stateful/StatefulComponentCreateServiceFactory.java
  messaging-activemq/subsystem/src/test/java/org/wildfly/extension/messaging/activemq/MessagingDependencies.java
Labels: deps-ok

#14713 [WFLY-15351] Fix licenses in EE feature pack
  ee-feature-pack/common/src/main/resources/license/ee-feature-pack-common-licenses.xml
Labels: Critical

#14712 [WFLY-15339] Upgrade ironjacamar to 1.5.2.Final
  pom.xml
Labels: deps-ok

#14704 [WFLY-15325] Reduce log spam
  docs/src/main/asciidoc/_admin-guide/subsystem-configuration/Observability_Tracing.adoc
  galleon-pack/galleon-content/src/main/resources/feature_groups/domain-full-ha.xml
  galleon-pack/galleon-content/src/main/resources/feature_groups/domain-full.xml
  galleon-pack/galleon-content/src/main/resources/feature_groups/domain-ha.xml
  galleon-pack/galleon-content/src/main/resources/feature_groups/domain.xml
  galleon-pack/galleon-content/src/main/resources/feature_groups/standalone-full-ha.xml
  galleon-pack/galleon-content/src/main/resources/feature_groups/standalone-full.xml
  galleon-pack/galleon-content/src/main/resources/feature_groups/standalone-ha.xml
  galleon-pack/galleon-content/src/main/resources/feature_groups/standalone.xml
  observability/opentelemetry-api/src/main/java/org/wildfly/extension/opentelemetry/api/OpenTelemetryContainerFilter.java
  testsuite/integration/basic/src/test/java/org/wildfly/test/integration/observability/opentelemetry/BasicOpenTelemetryTestCase.java
  testsuite/integration/basic/src/test/java/org/wildfly/test/integration/observability/opentelemetry/OpenTelemetrySetupTask.java
  testsuite/integration/basic/src/test/java/org/wildfly/test/integration/observability/opentelemetry/RestClientTestCase.java
  testsuite/integration/manualmode/src/test/java/org/wildfly/test/manual/observability/opentelemetry/ContextPropagationTestCase.java
Labels: deps-ok

#14718 WFLY-15329 Fix intermittent failures in GroupListenerTestCase
  testsuite/integration/clustering/src/test/java/org/jboss/as/test/clustering/cluster/group/GroupListenerTestCase.java
Labels: deps-ok

#14702 WFLY-13859 Clustering TS: Support testing against different Infinispan Server distributions
  docs/src/main/asciidoc/_testsuite/WildFly_Testsuite_Overview.adoc
  testsuite/integration/clustering/pom.xml
  testsuite/integration/clustering/src/test/java/org/jboss/as/test/clustering/cluster/AbstractClusteringTestCase.java
  testsuite/integration/clustering/src/test/resources/infinispan-13.0.xml
Labels: deps-ok

#14635 [WFLY-15238][WFLY-15239][WFLY-15240] Drop transformers and tests for the connector subsystems
  connector/src/main/java/org/jboss/as/connector/subsystems/datasources/DataSourcesTransformers.java
  connector/src/main/java/org/jboss/as/connector/subsystems/jca/JcaTransformers.java
  connector/src/main/java/org/jboss/as/connector/subsystems/resourceadapters/ResourceAdaptersTransformers.java
  connector/src/main/resources/META-INF/services/org.jboss.as.controller.transform.ExtensionTransformerRegistration
  connector/src/test/java/org/jboss/as/connector/subsystems/datasources/DatasourcesSubsystemTestCase.java
  connector/src/test/java/org/jboss/as/connector/subsystems/jca/JcaSubsystemTestCase.java
  connector/src/test/java/org/jboss/as/connector/subsystems/resourceadapters/ResourceAdaptersSubsystemTestCase.java
  connector/src/test/resources/org/jboss/as/connector/subsystems/datasources/datasources-full-expression110.xml
  connector/src/test/resources/org/jboss/as/connector/subsystems/datasources/datasources-full-expression111.xml
  connector/src/test/resources/org/jboss/as/connector/subsystems/datasources/datasources-full-no-tracking.xml
  connector/src/test/resources/org/jboss/as/connector/subsystems/datasources/datasources-full110.xml
  connector/src/test/resources/org/jboss/as/connector/subsystems/datasources/datasources-no-connection-url.xml
  connector/src/test/resources/org/jboss/as/connector/subsystems/datasources/datasources_6_0-reject.xml
  connector/src/test/resources/org/jboss/as/connector/subsystems/datasources/wildfly-datasources_2_0.xml
  connector/src/test/resources/org/jboss/as/connector/subsystems/jca/jca-full-elytron.xml
  connector/src/test/resources/org/jboss/as/connector/subsystems/resourceadapters/resource-adapters-pool-20.xml
  connector/src/test/resources/org/jboss/as/connector/subsystems/resourceadapters/resource-adapters-pool-40.xml
  connector/src/test/resources/org/jboss/as/connector/subsystems/resourceadapters/resource-adapters-pool-elytron-enabled-6_0-reject.xml
  connector/src/test/resources/org/jboss/as/connector/subsystems/resourceadapters/resource-adapters-pool-elytron-enabled.xml
Labels: deps-ok

#14716 [WFLY-15355] Duplicate declaration of maven resources plugin on wildfly-ts-integ-ws
  testsuite/integration/ws/pom.xml
Labels: deps-ok

#14719 [WFLY-15318] Fix OcspTestCase failures with SE17
  testsuite/integration/elytron/src/test/java/org/wildfly/test/integration/elytron/certs/ocsp/TestingOcspServer.java
Labels: deps-ok

#14637 [WFLY-15226] Make ResourceAdapterOperationsUnitTestCase more resistan…
  testsuite/integration/smoke/src/test/java/org/jboss/as/test/smoke/mgmt/resourceadapter/ResourceAdapterOperationsUnitTestCase.java
Labels: deps-ok

#14720 WFLY-15359 - Update Community Docs for OpenTelemetry
  docs/src/main/asciidoc/_admin-guide/subsystem-configuration/Observability_Tracing.adoc
  observability/opentelemetry/src/main/java/org/wildfly/extension/opentelemetry/OpenTelemetryConfigurationConstants.java
  observability/opentelemetry/src/main/java/org/wildfly/extension/opentelemetry/OpenTelemetrySubsystemDefinition.java
  testsuite/integration/manualmode/src/test/java/org/wildfly/test/manual/observability/opentelemetry/deployment1/Service1.java
Labels: deps-ok

#14722 [WFLY-14798] Fix race condition in test
  testsuite/integration/microprofile/src/test/java/org/wildfly/test/integration/microprofile/reactive/messaging/ported/signatures/SubscriberSignatureTestCase.java
Labels: deps-ok

#14724 Temporarily ignore DataSourceMultipleConnStatsTestCase.testClearedDat…
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/jca/statistics/DataSourceMultipleConnStatsTestCase.java
Labels: deps-ok

#14725 [WFLY-15319] Ignore JSFDeploymentProcessorTestCase on SE > 8
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/jsf/version/JSFDeploymentProcessorTestCase.java
  testsuite/shared/src/main/java/org/jboss/as/test/shared/util/AssumeTestGroupUtil.java
Labels: deps-ok

#14726 [WFLY-15368] Upgrade Santuario xmlsec to 2.2.3
  pom.xml
Labels: deps-ok

#14665 [WFLY-15283] Test for Elytron SSL Context in MP reactive messaging
  microprofile/reactive-messaging-smallrye/common/pom.xml
  microprofile/reactive-messaging-smallrye/kafka/pom.xml
  testsuite/integration/microprofile/src/test/java/org/wildfly/test/integration/microprofile/reactive/RunKafkaSetupTask.java
  testsuite/integration/microprofile/src/test/java/org/wildfly/test/integration/microprofile/reactive/messaging/kafka/ssl/Bean.java
  testsuite/integration/microprofile/src/test/java/org/wildfly/test/integration/microprofile/reactive/messaging/kafka/ssl/ConfigureElytronSslContextSetupTask.java
  testsuite/integration/microprofile/src/test/java/org/wildfly/test/integration/microprofile/reactive/messaging/kafka/ssl/ReactiveMessagingKafkaSslTestCase.java
  testsuite/integration/microprofile/src/test/java/org/wildfly/test/integration/microprofile/reactive/messaging/kafka/ssl/RunKafkaWithSslSetupTask.java
  testsuite/integration/microprofile/src/test/java/org/wildfly/test/integration/microprofile/reactive/messaging/kafka/ssl/microprofile-config.properties
  testsuite/integration/microprofile/src/test/resources/org/wildfly/test/integration/microprofile/reactive/messaging/kafka/client.truststore.p12
  testsuite/integration/microprofile/src/test/resources/org/wildfly/test/integration/microprofile/reactive/messaging/kafka/server.keystore.p12
Labels: ready-for-merge, Blocker, deps-ok

#14727 [WFLY-15369] Upgrade kafka-clients to version 2.8.1
  pom.xml
Labels: deps-ok

#14732 [WFLY-15363] Upgrade WildFly Core 17.0.0.Final
  pom.xml
Labels: deps-ok

#14734 [WFLY-15374] Disable unstable test
  testsuite/integration/manualmode/src/test/java/org/wildfly/test/manual/observability/opentelemetry/ContextPropagationTestCase.java
Labels: deps-ok

#14728 [WFLY-15256] Add documentation for the Elytron OIDC Client subsystem
  docs/src/main/asciidoc/_admin-guide/Subsystem_configuration.adoc
  docs/src/main/asciidoc/_admin-guide/subsystem-configuration/Elytron_OIDC_Client.adoc
Labels: deps-ok

#14737 [WFLY-14860] sort attributeRemoved in distributed setup
  clustering/web/undertow/src/main/java/org/wildfly/clustering/web/undertow/session/DistributableSession.java
Labels: 25.x

#14687 WFLY-15278 Upgrade smallrye-open-api to 2.1.15
  pom.xml
Labels: deps-ok, 25.x

#14723 WFLY-15342 EJB Timers out of sync within cluster causing inexistent t…
  ee-feature-pack/common/src/main/resources/modules/system/layers/base/org/jboss/as/ejb3/main/timers/timer-sql.properties
  ejb3/src/main/java/org/jboss/as/ejb3/timerservice/TimerServiceImpl.java
  ejb3/src/main/java/org/jboss/as/ejb3/timerservice/persistence/database/DatabaseTimerPersistence.java
  testsuite/integration/multinode/src/test/java/org/jboss/as/test/multinode/ejb/timer/database/DatabaseTimerServiceRefreshTestCase.java
  testsuite/integration/multinode/src/test/java/org/jboss/as/test/multinode/ejb/timer/database/RefreshBeanBase.java
  testsuite/integration/multinode/src/test/java/org/jboss/as/test/multinode/ejb/timer/database/RefreshIF.java
Labels: deps-ok

#14739 [WFLY-15387] Upgrade to RM 3.10.1
  microprofile/galleon-common/src/main/resources/modules/system/layers/base/org/eclipse/microprofile/reactive-messaging/api/main/module.xml
  pom.xml
Labels: deps-ok

#14735 [WFLY-15376] Remove unused jaeger-client dep
  ee-feature-pack/common/pom.xml
  microprofile/galleon-common/pom.xml
  pom.xml
Labels: deps-changed
