Repository wildfly/wildfly, pull requests merged in 2021-10, with the labels that each got.

#14741 WFLY-15386 Clustering TS: Infinispan Server instances provisioned by testsuite are always killed; leaking resources (e.g. file locks) on Windows platform
  testsuite/integration/clustering/pom.xml
  testsuite/integration/clustering/src/test/java/org/jboss/as/test/clustering/cluster/AbstractClusteringTestCase.java
  testsuite/integration/clustering/src/test/resources/infinispan-12_1.xml
  testsuite/integration/clustering/src/test/resources/infinispan-13_0.xml
Labels: deps-ok

#14743 [WFLY-15396] Override core to roll back to Jandex 2.3.1
  pom.xml
  servlet-feature-pack/common/pom.xml
Labels: deps-changed

#14680 [WFLY-15309] Re-enable some tests in -Dts.ee9 profile that couldn't work due to their use of legacy security
  testsuite/integration/basic/pom.xml
  testsuite/integration/clustering/pom.xml
  testsuite/integration/secman/pom.xml
  testsuite/integration/smoke/pom.xml
  testsuite/integration/web/pom.xml
  testsuite/integration/ws/pom.xml
Labels: deps-ok

#14750 [WFLY-15402] Upgrade WildFly Core 17.0.1.Final
  pom.xml
  servlet-feature-pack/common/pom.xml
Labels: Blocker, deps-changed

#14752 [WFLY-15321] When the -Prelease profile is activate copy all resources into a single "uploads" folder and generate checksums.
  pom.xml
  release/pom.xml
Labels: deps-ok, 25.x

#14751 [WFLY-15362] Security document clean up for WildFly 25
  docs/src/main/asciidoc/Admin_Guide.adoc
  docs/src/main/asciidoc/Getting_Started_Guide.adoc
  docs/src/main/asciidoc/WildFly_Elytron_Security.adoc
  docs/src/main/asciidoc/WildFly_and_WildFly_Preview.adoc
  docs/src/main/asciidoc/_admin-guide/Default_HTTP_Interface_Security.adoc
  docs/src/main/asciidoc/_admin-guide/Domain_Setup.adoc
  docs/src/main/asciidoc/_admin-guide/Management_Clients.adoc
  docs/src/main/asciidoc/_admin-guide/RBAC.adoc
  docs/src/main/asciidoc/_admin-guide/Security_Realms.adoc
  docs/src/main/asciidoc/_admin-guide/Security_Realms_Detailed_Configuration.adoc
  docs/src/main/asciidoc/_admin-guide/Security_Realms_Examples.adoc
  docs/src/main/asciidoc/_admin-guide/Security_Realms_Plugins.adoc
  docs/src/main/asciidoc/_admin-guide/Subsystem_configuration.adoc
  docs/src/main/asciidoc/_admin-guide/add-user-utility.adoc
  docs/src/main/asciidoc/_admin-guide/subsystem-configuration/DataSource.adoc
  docs/src/main/asciidoc/_admin-guide/subsystem-configuration/Messaging.adoc
  docs/src/main/asciidoc/_admin-guide/subsystem-configuration/Resource_adapters.adoc
  docs/src/main/asciidoc/_admin-guide/subsystem-configuration/Security.adoc
  docs/src/main/asciidoc/_developer-guide/Jakarta_XML_Web_Services/Authentication.adoc
  docs/src/main/asciidoc/_elytron/Elytron_Subsystem.adoc
  docs/src/main/asciidoc/_elytron/Using_WildFly_Elytron_with_WildFly.adoc
  docs/src/main/asciidoc/_extending-wildfly/Example_subsystem.adoc
  docs/src/main/asciidoc/_galleon/Galleon_layers.adoc
  docs/src/main/asciidoc/_galleon/Galleon_provisioning.adoc
  docs/src/main/asciidoc/_high-availability/Clustering_and_Domain_Setup_Walkthrough.adoc
Labels: Blocker, deps-ok, 25.x

#14736 WFLY-15372 Remove the use of TimerHandle in ejb timer management oper…
  ejb3/src/main/java/org/jboss/as/ejb3/logging/EjbLogger.java
  ejb3/src/main/java/org/jboss/as/ejb3/subsystem/deployment/TimerResourceDefinition.java
  ejb3/src/main/java/org/jboss/as/ejb3/timerservice/TimerHandleImpl.java
  ejb3/src/main/java/org/jboss/as/ejb3/timerservice/TimerImpl.java
  ejb3/src/main/java/org/jboss/as/ejb3/timerservice/TimerServiceImpl.java
Labels: deps-ok

#14313 [WFLY-14814] Drop unneeded H2 module dependencies; don't bother trans…
  ee-9/feature-pack/pom.xml
  ee-feature-pack/common/src/main/resources/modules/system/layers/base/com/h2database/h2/main/module.xml
Labels: deps-ok

#14446 WFLY-14844 Make appclient dependency on PicketBox Optional
  ee-feature-pack/common/src/main/resources/modules/system/layers/base/org/jboss/as/appclient/main/module.xml
Labels: deps-ok

#14744 Update observability module with a dependency on wildfly-elytron to use individual modules
  ee-feature-pack/common/src/main/resources/modules/system/layers/base/org/wildfly/extension/opentelemetry-api/main/module.xml
  ee-feature-pack/common/src/main/resources/modules/system/layers/base/org/wildfly/extension/opentelemetry/main/module.xml
  observability/opentelemetry-api/pom.xml
  observability/opentelemetry/pom.xml
Labels: deps-ok

#14715 WFLY-15352 Remove obsolete wildfly-clustering-common transformer code
  clustering/common/src/main/java/org/jboss/as/clustering/controller/ResourceDefinitionProvider.java
  clustering/common/src/main/java/org/jboss/as/clustering/controller/RestartParentResourceWriteAttributeHandler.java
  clustering/common/src/main/java/org/jboss/as/clustering/controller/WriteAttributeStepHandler.java
  clustering/common/src/main/java/org/jboss/as/clustering/controller/transform/AttributeOperationTransformer.java
  clustering/common/src/main/java/org/jboss/as/clustering/controller/transform/ChainedOperationTransformer.java
  clustering/common/src/main/java/org/jboss/as/clustering/controller/transform/InitialAttributeValueOperationContextAttachment.java
  clustering/common/src/main/java/org/jboss/as/clustering/controller/transform/LegacyPropertyAddOperationTransformer.java
  clustering/common/src/main/java/org/jboss/as/clustering/controller/transform/LegacyPropertyMapGetOperationTransformer.java
  clustering/common/src/main/java/org/jboss/as/clustering/controller/transform/LegacyPropertyResourceTransformer.java
  clustering/common/src/main/java/org/jboss/as/clustering/controller/transform/LegacyPropertyWriteOperationTransformer.java
  clustering/common/src/main/java/org/jboss/as/clustering/controller/transform/OperationTransformer.java
  clustering/common/src/main/java/org/jboss/as/clustering/controller/transform/PathAddressTransformer.java
  clustering/common/src/main/java/org/jboss/as/clustering/controller/transform/SimpleAddOperationTransformer.java
  clustering/common/src/main/java/org/jboss/as/clustering/controller/transform/SimpleDescribeOperationTransformer.java
  clustering/common/src/main/java/org/jboss/as/clustering/controller/transform/SimpleOperationTransformer.java
  clustering/common/src/main/java/org/jboss/as/clustering/controller/transform/SimplePathOperationTransformer.java
  clustering/common/src/main/java/org/jboss/as/clustering/controller/transform/SimpleReadAttributeOperationTransformer.java
  clustering/common/src/main/java/org/jboss/as/clustering/controller/transform/SimpleRemoveOperationTransformer.java
  clustering/common/src/main/java/org/jboss/as/clustering/controller/transform/SimpleResourceTransformer.java
  clustering/common/src/main/java/org/jboss/as/clustering/controller/transform/SimpleUndefineAttributeOperationTransformer.java
  clustering/common/src/main/java/org/jboss/as/clustering/controller/transform/SimpleWriteAttributeOperationTransformer.java
Labels: ready-for-merge, deps-ok

#14691 [WFLY-15221] Drop IIOP model transformers prior to 2.1.0
  iiop-openjdk/src/main/java/org/wildfly/iiop/openjdk/IIOPTransformers.java
  iiop-openjdk/src/main/resources/META-INF/services/org.jboss.as.controller.transform.ExtensionTransformerRegistration
  iiop-openjdk/src/test/java/org/wildfly/iiop/openjdk/IIOPSubsystemTransformersTestCase.java
  iiop-openjdk/src/test/resources/org/wildfly/iiop/openjdk/iiop-transformers-reject.xml
  iiop-openjdk/src/test/resources/org/wildfly/iiop/openjdk/iiop-transformers.xml
Labels: deps-ok

#14676 [WFLY-15243] Drop Transactions model transformers prior to 6.0.0
  transactions/src/main/java/org/jboss/as/txn/subsystem/TransactionTransformers.java
  transactions/src/main/resources/META-INF/services/org.jboss.as.controller.transform.ExtensionTransformerRegistration
  transactions/src/test/java/org/jboss/as/txn/subsystem/TransactionSubsystemTestCase.java
  transactions/src/test/resources/org/jboss/as/txn/subsystem/full-expressions-transform.xml
  transactions/src/test/resources/org/jboss/as/txn/subsystem/full-expressions.xml
Labels: deps-ok

#14566 [WFLY-15044] Avoid Nullpointer (IIOP)
  iiop-openjdk/src/main/java/org/wildfly/iiop/openjdk/rmi/ValueAnalysis.java
Labels: deps-ok

#14570 [WFLY-15044] Avoid Nullpointer (Connector)
  connector/src/main/java/org/jboss/as/connector/services/resourceadapters/deployment/ResourceAdapterDeploymentService.java
  connector/src/main/java/org/jboss/as/connector/services/workmanager/transport/CommandDispatcherTransport.java
Labels: deps-ok

#14608 [WFLY-15205] AnnotationsTestCase#testProcessConnectorFail never fails
  connector/src/test/java/org/jboss/as/connector/annotations/repository/jandex/AnnotationsTestCase.java
Labels: deps-ok

#14511 [WFLY-15058] Remove trivial empty statements
  appclient/src/main/java/org/jboss/as/appclient/component/ApplicationClientComponentDescription.java
  clustering/web/infinispan/src/main/java/org/wildfly/clustering/web/infinispan/session/InfinispanLegacySessionManagementProviderFactory.java
  ejb3/src/main/java/org/jboss/as/ejb3/timerservice/persistence/TimerPersistence.java
  iiop-openjdk/src/main/java/org/wildfly/iiop/openjdk/naming/jndi/CNNameParser.java
  jpa/hibernate5_3/src/main/java/org/jboss/as/jpa/hibernate5/service/ServiceContributorImpl.java
  jsf/subsystem/src/main/java/org/jboss/as/jsf/deployment/JSFComponentProcessor.java
  legacy/messaging/src/main/java/org/jboss/as/messaging/AttributeMarshallers.java
  legacy/messaging/src/main/java/org/jboss/as/messaging/jms/ConnectionFactoryAttributes.java
  messaging-activemq/subsystem/src/main/java/org/wildfly/extension/messaging/activemq/AbstractTransportDefinition.java
  web-common/src/main/java/org/jboss/as/web/common/ConcurrentReferenceHashMap.java
Labels: deps-ok

#14749 [WFLY-15311] Exclude google guava and opentelemetry artifacts from EE…
  ee-9/feature-pack/pom.xml
Labels: deps-ok

#14757 Update HostExcludesTestCase configuration to work with WF26
  testsuite/domain/src/test/java/org/jboss/as/test/integration/domain/HostExcludesTestCase.java
Labels: deps-ok

#14760 [WFLY-15204] Update HostXmlSmokeTestCase
  testsuite/integration/vdx/src/test/java/org/wildfly/test/integration/vdx/domain/HostXmlSmokeTestCase.java
Labels: deps-ok

#14758 [WFLY-15414] Fix release module to avoid to fail if wildfly-preview d…
  release/pom.xml
Labels: deps-ok

#14745 [WFLY-15071] Remove permissions from test which are no longer needed
  testsuite/integration/microprofile/src/test/java/org/wildfly/test/integration/microprofile/reactive/messaging/rest/channels/ReactiveMessagingChannelsTestCase.java
Labels: deps-ok

#14854 [WFLY-15587] Upgrade eclipselink 2.7.9
  pom.xml
Labels: deps-ok

#14845 [WFLY-15578] Upgrade HornetQ from 2.4.7.Final to 2.4.8.Final
  pom.xml
Labels: deps-ok

#14840 [WFLY-15574] Upgrade com.squareup.okhttp3 3.14.9
  pom.xml
  testsuite/integration/clustering/pom.xml
Labels: deps-ok
