Repository wildfly/wildfly, pull requests merged in 2021-11, with the labels that each got.

#14835 WFLY-15562 Simplify logging and validation in various createTimer met…
  ejb3/src/main/java/org/jboss/as/ejb3/interceptor/server/ServerInterceptorCache.java
  ejb3/src/main/java/org/jboss/as/ejb3/logging/EjbLogger.java
  ejb3/src/main/java/org/jboss/as/ejb3/timerservice/TimerServiceImpl.java
Labels: deps-ok

#14810 [WFLY-15518] Test preparation errors shall cause failure (connector)
  connector/src/test/java/org/jboss/as/connector/annotations/repository/jandex/AnnotationsTestCase.java
  connector/src/test/java/org/jboss/as/connector/deployers/spec/rars/BaseActivationSpec.java
  connector/src/test/java/org/jboss/as/connector/deployers/spec/rars/BaseCciConnection.java
  connector/src/test/java/org/jboss/as/connector/deployers/spec/rars/BaseCciConnectionFactory.java
  connector/src/test/java/org/jboss/as/connector/deployers/spec/rars/BaseConnectionManager.java
  connector/src/test/java/org/jboss/as/connector/deployers/spec/rars/BaseManagedConnection.java
  connector/src/test/java/org/jboss/as/connector/deployers/spec/rars/BaseManagedConnectionFactory.java
  connector/src/test/java/org/jboss/as/connector/deployers/spec/rars/BaseReference.java
  connector/src/test/java/org/jboss/as/connector/deployers/spec/rars/BaseResourceAdapter.java
  connector/src/test/java/org/jboss/as/connector/deployers/spec/rars/MessageListener.java
  connector/src/test/java/org/jboss/as/connector/deployers/spec/rars/TestConnection.java
  connector/src/test/java/org/jboss/as/connector/deployers/spec/rars/TestConnectionInterface.java
  connector/src/test/java/org/jboss/as/connector/deployers/spec/rars/ra16inoutmultianno/TestActivationSpec.java
  connector/src/test/java/org/jboss/as/connector/deployers/spec/rars/ra16inoutmultianno/TestAdminObjectInterface.java
  connector/src/test/java/org/jboss/as/connector/deployers/spec/rars/ra16inoutmultianno/TestManagedConnection.java
  connector/src/test/java/org/jboss/as/connector/deployers/spec/rars/ra16inoutmultianno/TestManagedConnectionFactory.java
  connector/src/test/java/org/jboss/as/connector/deployers/spec/rars/ra16inoutmultianno/TestResourceAdapter.java
  connector/src/test/java/org/jboss/as/connector/deployers/spec/rars/rastandalone/Test2ResourceAdapter.java
  connector/src/test/resources/ra16inoutmultianno.rar/META-INF/ra.xml
Labels: deps-ok

#14868 [WFLY-15608] Add explicit dependencies to testsuite modules instead of relying on transitives coming via wildfly-core-testsuite-shared
  testsuite/integration/clustering/pom.xml
  testsuite/integration/elytron/pom.xml
  testsuite/integration/manualmode/pom.xml
  testsuite/integration/pom.xml
  testsuite/integration/secman/pom.xml
  testsuite/integration/web/pom.xml
  testsuite/integration/ws/pom.xml
Labels: deps-ok

#14870 WFLY-15620 Replace usages of getParameterTypes().length with getParam…
  undertow/src/main/java/org/wildfly/extension/undertow/filters/Filter.java
Labels: deps-ok

#14846 WFLY-15573 State transfer can fail due to ConcurrentModificationException if distributed web session attributes are concurrently modified
  clustering/ee/cache/src/main/java/org/wildfly/clustering/ee/cache/CacheConfiguration.java
  clustering/ee/hotrod/src/main/java/org/wildfly/clustering/ee/hotrod/HotRodConfiguration.java
  clustering/ee/infinispan/src/main/java/org/wildfly/clustering/ee/infinispan/InfinispanConfiguration.java
  clustering/web/hotrod/src/main/java/org/wildfly/clustering/web/hotrod/RemoteCacheConfiguration.java
  clustering/web/hotrod/src/main/java/org/wildfly/clustering/web/hotrod/session/HotRodSessionAttributesFactoryConfiguration.java
  clustering/web/hotrod/src/main/java/org/wildfly/clustering/web/hotrod/session/HotRodSessionFactory.java
  clustering/web/hotrod/src/main/java/org/wildfly/clustering/web/hotrod/session/HotRodSessionManagementConfiguration.java
  clustering/web/hotrod/src/main/java/org/wildfly/clustering/web/hotrod/session/HotRodSessionManagerFactoryConfiguration.java
  clustering/web/hotrod/src/main/java/org/wildfly/clustering/web/hotrod/session/HotRodSessionMetaDataFactory.java
  clustering/web/hotrod/src/main/java/org/wildfly/clustering/web/hotrod/sso/HotRodSSOManagementConfiguration.java
  clustering/web/infinispan/src/main/java/org/wildfly/clustering/web/infinispan/session/AbstractInfinispanSessionMetaDataFactory.java
  clustering/web/infinispan/src/main/java/org/wildfly/clustering/web/infinispan/session/InfinispanSessionAttributesFactoryConfiguration.java
  clustering/web/infinispan/src/main/java/org/wildfly/clustering/web/infinispan/session/InfinispanSessionManagerFactory.java
  clustering/web/infinispan/src/main/java/org/wildfly/clustering/web/infinispan/session/InfinispanSessionManagerFactoryConfiguration.java
  clustering/web/infinispan/src/main/java/org/wildfly/clustering/web/infinispan/session/InfinispanSessionMetaDataFactoryConfiguration.java
  clustering/web/infinispan/src/main/java/org/wildfly/clustering/web/infinispan/session/coarse/CoarseSessionAttributesFactory.java
  clustering/web/infinispan/src/main/java/org/wildfly/clustering/web/infinispan/session/fine/FineSessionAttributesFactory.java
  clustering/web/infinispan/src/main/java/org/wildfly/clustering/web/infinispan/sso/InfinispanSSOFactory.java
  clustering/web/infinispan/src/main/java/org/wildfly/clustering/web/infinispan/sso/InfinispanSSOManagerFactory.java
  clustering/web/infinispan/src/main/java/org/wildfly/clustering/web/infinispan/sso/InfinispanSSOManagerFactoryConfiguration.java
  clustering/web/infinispan/src/main/java/org/wildfly/clustering/web/infinispan/sso/coarse/CoarseSessionsFactory.java
Labels: deps-ok

#14872 WFLY-15618 Replace usages of getParameterTypes().length with getParam…
  iiop-openjdk/src/main/java/org/wildfly/iiop/openjdk/rmi/ContainerAnalysis.java
Labels: deps-ok

#14871 WFLY-15619 Replace usages of getParameterTypes().length with getParam…
  jaxrs/src/main/java/org/jboss/as/jaxrs/JaxrsDeploymentDefinition.java
Labels: deps-ok

#14873 WFLY-15617 Replace usages of getParameterTypes().length with getParam…
  connector/src/main/java/org/jboss/as/connector/util/Injection.java
Labels: deps-ok

#14875 [WFLY-15442] Move WildFly Preview to a native jakarta namespace variant of Elytron Web
  ee-9/feature-pack/pom.xml
  ee-9/pom.xml
Labels: deps-ok

#14876 WFLY-15616 Replace usages of getParameterTypes().length with getParam…
  clustering/jgroups/extension/src/main/java/org/jboss/as/clustering/jgroups/subsystem/ProtocolMetricsHandler.java
Labels: deps-ok

#14877 WFLY-15615 Replace usages of getParameterTypes().length with getParam…
  weld/common/src/main/java/org/jboss/as/weld/util/ResourceInjectionUtilities.java
  weld/ejb/src/main/java/org/jboss/as/weld/services/bootstrap/WeldEjbInjectionServices.java
  weld/subsystem/src/main/java/org/jboss/as/weld/services/bootstrap/WeldResourceInjectionServices.java
Labels: deps-ok

#14879 WFLY-15613 Replace usages of getParameterTypes().length with getParam…
  ee/src/main/java/org/jboss/as/ee/component/ManagedReferenceLifecycleMethodInterceptor.java
  ee/src/main/java/org/jboss/as/ee/component/ViewDescription.java
  ee/src/main/java/org/jboss/as/ee/component/ViewService.java
  ee/src/main/java/org/jboss/as/ee/utils/InjectionUtils.java
  pojo/src/main/java/org/jboss/as/pojo/service/Callback.java
  sar/src/main/java/org/jboss/as/service/ReflectionUtils.java
Labels: deps-ok

#14852 [WFLY-15585] Upgrade istack-commons-runtime 3.0.11
  pom.xml
Labels: deps-ok

#14866 WFLY-15546 Move WildFly Preview to a native Jakarta namespace variant of the jpa subsystem module
  ee-9/feature-pack/pom.xml
  ee-9/feature-pack/src/main/resources/license/preview-feature-pack-licenses.xml
  ee-9/pom.xml
  ee-9/source-transform/jpa/subsystem/pom.xml
  ee-9/source-transform/pom.xml
  ee-feature-pack/common/src/main/resources/modules/system/layers/base/org/jboss/as/jpa/main/module.xml
  jpa/subsystem/src/main/java/org/jboss/as/jpa/classloader/TempClassLoader.java
  jpa/subsystem/src/main/java/org/jboss/as/jpa/service/PersistenceUnitServiceImpl.java
  jpa/subsystem/src/main/java/org/jboss/as/jpa/service/PhaseOnePersistenceUnitServiceImpl.java
  jpa/subsystem/src/test/java/org/jboss/as/jpa/classloader/TempClassLoaderTestCase.java
Labels: deps-ok, EE9

#14883 WFLY-15539 Move WildFly Preview to a native Jakarta namespace variant…
  ee-9/feature-pack/pom.xml
  ee-9/feature-pack/src/main/resources/license/preview-feature-pack-licenses.xml
  ee-9/pom.xml
  ee-9/source-transform/batch-jberet/pom.xml
  ee-9/source-transform/pom.xml
  ee-feature-pack/common/src/main/resources/modules/system/layers/base/org/wildfly/extension/batch/jberet/main/module.xml
Labels: deps-ok, EE9

#14832 [WFLY-15582] Remove unneeded code from legacy security subsystem; prune…
  security/subsystem/pom.xml
  security/subsystem/src/main/java/org/jboss/as/security/ACLResourceDefinition.java
  security/subsystem/src/main/java/org/jboss/as/security/Attribute.java
  security/subsystem/src/main/java/org/jboss/as/security/AuditResourceDefinition.java
  security/subsystem/src/main/java/org/jboss/as/security/AuthorizationResourceDefinition.java
  security/subsystem/src/main/java/org/jboss/as/security/ClassicAuthenticationResourceDefinition.java
  security/subsystem/src/main/java/org/jboss/as/security/ComplexAttributes.java
  security/subsystem/src/main/java/org/jboss/as/security/Constants.java
  security/subsystem/src/main/java/org/jboss/as/security/DigestCredential.java
  security/subsystem/src/main/java/org/jboss/as/security/IdentityTrustResourceDefinition.java
  security/subsystem/src/main/java/org/jboss/as/security/JASPIAuthenticationResourceDefinition.java
  security/subsystem/src/main/java/org/jboss/as/security/JASPIMappingModuleDefinition.java
  security/subsystem/src/main/java/org/jboss/as/security/JSSEResourceDefinition.java
  security/subsystem/src/main/java/org/jboss/as/security/LegacySupport.java
  security/subsystem/src/main/java/org/jboss/as/security/LoginModuleResourceDefinition.java
  security/subsystem/src/main/java/org/jboss/as/security/LoginModuleStackResourceDefinition.java
  security/subsystem/src/main/java/org/jboss/as/security/MappingModuleDefinition.java
  security/subsystem/src/main/java/org/jboss/as/security/MappingProviderModuleDefinition.java
  security/subsystem/src/main/java/org/jboss/as/security/MappingResourceDefinition.java
  security/subsystem/src/main/java/org/jboss/as/security/ModuleFlag.java
  security/subsystem/src/main/java/org/jboss/as/security/ModuleName.java
  security/subsystem/src/main/java/org/jboss/as/security/ModulesMap.java
  security/subsystem/src/main/java/org/jboss/as/security/RealmUsersRolesLoginModule.java
  security/subsystem/src/main/java/org/jboss/as/security/SecurityDomainAdd.java
  security/subsystem/src/main/java/org/jboss/as/security/SecurityDomainResourceDefinition.java
  security/subsystem/src/main/java/org/jboss/as/security/SecurityExtension.java
  security/subsystem/src/main/java/org/jboss/as/security/SecuritySubsystemParser.java
  security/subsystem/src/main/java/org/jboss/as/security/SecuritySubsystemParser_2_0.java
  security/subsystem/src/main/java/org/jboss/as/security/SecuritySubsystemPersister.java
  security/subsystem/src/main/java/org/jboss/as/security/SecuritySubsystemRootResourceDefinition.java
  security/subsystem/src/main/java/org/jboss/as/security/SecurityTransformers.java
  security/subsystem/src/main/java/org/jboss/as/security/VaultResourceDefinition.java
  security/subsystem/src/main/java/org/jboss/as/security/elytron/BasicAddHandler.java
  security/subsystem/src/main/java/org/jboss/as/security/elytron/BasicService.java
  security/subsystem/src/main/java/org/jboss/as/security/elytron/ElytronIntegrationResourceDefinitions.java
  security/subsystem/src/main/java/org/jboss/as/security/logging/SecurityLogger.java
  security/subsystem/src/test/java/org/jboss/as/security/SecurityTransformersTestCase.java
  servlet-feature-pack/common/src/main/resources/modules/system/layers/base/org/jboss/as/security/main/module.xml
  testsuite/integration/clustering/pom.xml
  testsuite/integration/elytron/pom.xml
  testsuite/integration/legacy-ejb-client/pom.xml
  testsuite/integration/manualmode/pom.xml
  testsuite/integration/microprofile-tck/jwt/pom.xml
  testsuite/integration/microprofile-tck/opentracing/pom.xml
  testsuite/integration/microprofile/pom.xml
  testsuite/integration/multinode/pom.xml
  testsuite/integration/rts/pom.xml
  testsuite/integration/secman/src/test/java/org/jboss/as/testsuite/integration/secman/propertypermission/PropertyPermissionExpressionsTestCase.java
  testsuite/integration/web/pom.xml
  testsuite/integration/ws/pom.xml
  testsuite/shared/pom.xml
Labels: deps-ok

#14777 [WFLY-15461] Exclude jasypt from Galleon WildFly plugin transformatio…
  ee-9/feature-pack/pom.xml
Labels: deps-ok, EE9

#14865 WFLY-15597 Can't create a pooled CF with discovery group
  messaging-activemq/subsystem/src/main/java/org/wildfly/extension/messaging/activemq/JGroupsBroadcastGroupAdd.java
  messaging-activemq/subsystem/src/main/java/org/wildfly/extension/messaging/activemq/JGroupsDiscoveryGroupAdd.java
  messaging-activemq/subsystem/src/main/java/org/wildfly/extension/messaging/activemq/MessagingSubsystemAdd.java
Labels: deps-ok

#14888 WFLY-15438 stop transforming dom4j
  ee-9/feature-pack/pom.xml
  ee-feature-pack/common/src/main/resources/modules/system/layers/base/org/dom4j/main/module.xml
  ee-feature-pack/pruned/src/main/resources/modules/system/layers/base/org/eclipse/persistence/main/module.xml
Labels: deps-ok, EE9

#14886 [WFLY-15640]: Upgrade WildFly Galleon plugins to 5.2.5.Final.
  pom.xml
  servlet-feature-pack/common/pom.xml
Labels: deps-ok

#14891 WFLY-15634 Upgrade wildfly-transaction-client from 1.1.14.Final to 2.…
  ee-9/pom.xml
  pom.xml
Labels: deps-ok

#14858 [WFLY-15522] Move WildFly Preview to a native jakarta namespace varia…
  ee-9/feature-pack/pom.xml
  ee-9/pom.xml
Labels: deps-ok, EE9

#14884 [WFLY-15464][WFLY-15520] Exclude more artifacts from unneeded Galleon transformation
  ee-9/feature-pack/pom.xml
Labels: deps-ok, EE9

#14889 WFLY-15555 - Move WildFly Preview to native Jakarta namespace variants of the opentelemetry subsystem modules -
  ee-9/feature-pack/pom.xml
  ee-9/feature-pack/src/main/resources/license/preview-feature-pack-licenses.xml
  ee-9/pom.xml
  ee-9/source-transform/observability/opentelemetry-api/pom.xml
  ee-9/source-transform/observability/opentelemetry/pom.xml
  ee-9/source-transform/pom.xml
  ee-feature-pack/common/src/main/resources/modules/system/layers/base/org/wildfly/extension/opentelemetry-api/main/module.xml
  ee-feature-pack/common/src/main/resources/modules/system/layers/base/org/wildfly/extension/opentelemetry/main/module.xml
Labels: deps-ok, EE9

#14880 WFLY-15028 Move WildFly Preview to a native jakarta namespace variant…
  ee-9/feature-pack/pom.xml
  ee-9/feature-pack/src/main/resources/license/preview-feature-pack-licenses.xml
  ee-9/pom.xml
  ee-feature-pack/common/src/main/resources/modules/system/layers/base/org/jboss/ejb-client/main/module.xml
  pom.xml
Labels: deps-ok, EE9

#14892 WFLY-15030 Move WildFly Preview to a native jakarta namespace variant…
  ee-9/feature-pack/pom.xml
  ee-9/feature-pack/src/main/resources/license/preview-feature-pack-licenses.xml
  ee-9/pom.xml
  ee-feature-pack/common/src/main/resources/modules/system/layers/base/org/wildfly/http-client/ejb/main/module.xml
  ee-feature-pack/common/src/main/resources/modules/system/layers/base/org/wildfly/http-client/transaction/main/module.xml
  pom.xml
Labels: deps-ok, EE9

#14893 [WFLY-15506] Use the correct artifact name in the excluded list
  ee-9/feature-pack/pom.xml
Labels: deps-ok

#14899 WFLY-15550 move Weld subsystem to Jakarta namespace variant
  ee-9/feature-pack/pom.xml
  ee-9/feature-pack/src/main/resources/license/preview-feature-pack-licenses.xml
  ee-9/pom.xml
  ee-9/source-transform/pom.xml
  ee-9/source-transform/weld/jpa/pom.xml
  ee-9/source-transform/weld/subsystem/pom.xml
  ee-feature-pack/common/src/main/resources/modules/system/layers/base/org/jboss/as/weld/jpa/main/module.xml
  ee-feature-pack/common/src/main/resources/modules/system/layers/base/org/jboss/as/weld/main/module.xml
Labels: deps-ok

#14901 [WFLY-15661]: ForwardedHandlerTestCase fails on jdk17.
  testsuite/integration/web/src/test/java/org/jboss/as/test/integration/web/handlers/ForwardedHandlerTestCase.java
  testsuite/integration/web/src/test/java/org/jboss/as/test/integration/web/handlers/ForwardedTestHelperHandler.java
  testsuite/integration/web/src/test/java/org/jboss/as/test/integration/web/handlers/ForwardedTestHelperServlet.java
Labels: deps-ok

#14894 Fix for WFLY-15650, Upgrade galleon plugins to 5.2.6.Final
  pom.xml
Labels: deps-ok

#14864 WFLY-15564 Improve the comparison of ScheduleExpression in TimerServi…
  ejb3/src/main/java/org/jboss/as/ejb3/timerservice/TimerServiceImpl.java
  ejb3/src/main/java/org/jboss/as/ejb3/timerservice/schedule/CalendarBasedTimeout.java
Labels: deps-ok

#14902 WFLY-15669 Distributed web session fails to expire if its last access time is not unique
  clustering/ee/cache/src/main/java/org/wildfly/clustering/ee/cache/scheduler/SortedScheduledEntries.java
  clustering/ee/cache/src/test/java/org/wildfly/clustering/ee/cache/scheduler/AbstractScheduledEntriesTestCase.java
  clustering/ee/cache/src/test/java/org/wildfly/clustering/ee/cache/scheduler/SortedScheduledEntriesTestCase.java
Labels: deps-ok

#14904 [WFLY-15661]: ForwardedHandlerTestCase fails on jdk17.
  testsuite/integration/web/src/test/java/org/jboss/as/test/integration/web/handlers/ForwardedHandlerTestCase.java
  testsuite/integration/web/src/test/java/org/jboss/as/test/integration/web/handlers/ForwardedTestHelperHandler.java
  testsuite/integration/web/src/test/java/org/jboss/as/test/integration/web/handlers/ForwardedTestHelperServlet.java
Labels: deps-ok

#14916 WFLY-15677 Disable simple cache optimization when statistics are enabled
  clustering/infinispan/extension/src/main/java/org/jboss/as/clustering/infinispan/DefaultCache.java
  clustering/infinispan/extension/src/main/java/org/jboss/as/clustering/infinispan/DefaultCacheContainer.java
  clustering/infinispan/extension/src/main/java/org/jboss/as/clustering/infinispan/subsystem/CacheContainerServiceConfigurator.java
  clustering/infinispan/extension/src/test/java/org/jboss/as/clustering/infinispan/DefaultCacheContainerTestCase.java
  clustering/infinispan/spi/src/main/java/org/wildfly/clustering/infinispan/spi/service/ConfigurationServiceConfigurator.java
Labels: deps-ok

#14917 Upgrade Infinispan Server version in test to 13.0.2.Final
  testsuite/integration/clustering/pom.xml
Labels: deps-ok

#14913 [WFLY-15676] The enable-microprofile.xml CLI script fails if dependencies are not already installed
  microprofile/galleon-common/src/main/resources/packages/docs.examples/content/docs/examples/enable-microprofile.cli
Labels: deps-ok

#14911 [WFLY-15674] Upgrade Hibernate ORM to 5.3.24.Final
  pom.xml
Labels: deps-ok

#14910 WFLY-15583 Adjust sql statements during initialization of DatabaseTim…
  ejb3/src/main/java/org/jboss/as/ejb3/timerservice/persistence/database/DatabaseTimerPersistence.java
Labels: deps-ok

#14918 WFLY-15592 Deprecate primary-key attribute of TimerResourceDefinition
  ejb3/src/main/java/org/jboss/as/ejb3/subsystem/deployment/TimerResourceDefinition.java
  ejb3/src/main/resources/org/jboss/as/ejb3/subsystem/LocalDescriptions.properties
Labels: deps-ok

#14912 WFLY-15675 Upgrade mod_cluster to 1.4.4.Final
  pom.xml
Labels: deps-ok

#14924 [WFLY-15714] Status Code in ReverseProxyTestCase should be 504
  testsuite/integration/web/src/test/java/org/jboss/as/test/integration/web/reverseproxy/ReverseProxyTestCase.java
Labels: deps-ok

#14931 WFLY-15677 Fix duplicate logic that causes an NPE
  clustering/infinispan/extension/src/main/java/org/jboss/as/clustering/infinispan/subsystem/CacheContainerServiceConfigurator.java
Labels: deps-ok

#14926 [WFLY-15717] Upgrade WildFly Core 18.0.0.Beta4
  pom.xml
Labels: ready-for-merge, deps-ok

#14919 WFLY-15707 Upgrade jgroups-azure to 1.3.1.Final
  pom.xml
Labels: deps-ok

#14927 [WFLY-15718] Fixing JCETestCase regression on JDK17+
  testsuite/pom.xml
Labels: ready-for-merge, deps-ok

#14922 [WFLY-15712] Upgrade RESTEasy from 4.7.2.Final to 4.7.3.Final
  pom.xml
Labels: ready-for-merge, deps-ok

#14920 [WFLY-15709] Avoid transforming twice the Jakarta native weld subsyst…
  ee-9/source-transform/weld/subsystem/pom.xml
  weld/subsystem/src/main/java/org/jboss/as/weld/CdiAnnotations.java
Labels: ready-for-merge, deps-ok, EE9

#14863 [WFLY-15593] Eliminate JSF dependency on legacy Xalan & Xerces and switch to JDK JAXP implementation.
  ee-feature-pack/common/src/main/resources/modules/system/layers/base/com/sun/jsf-impl/main/module.xml
  jsf/multi-jsf-installer/src/main/resources/mojarra-impl-module.xml
  jsf/multi-jsf-installer/src/main/resources/myfaces-impl-module.xml
  jsf/subsystem/src/test/resources/modules/com/sun/jsf-impl/main/module.xml
  jsf/subsystem/src/test/resources/modules/com/sun/jsf-impl/myfaces/module.xml
  jsf/subsystem/src/test/resources/modules2/com/sun/jsf-impl/myfaces2/module.xml
Labels: ready-for-merge, deps-ok

#14906 WFLY-15573 Always use concurrent data structure - to prevent ConcurrentModificationException during state transfer, even for lockOnRead cache configurations.
  clustering/web/infinispan/src/main/java/org/wildfly/clustering/web/infinispan/session/coarse/CoarseSessionAttributesFactory.java
  clustering/web/infinispan/src/main/java/org/wildfly/clustering/web/infinispan/session/fine/FineSessionAttributesFactory.java
  clustering/web/infinispan/src/main/java/org/wildfly/clustering/web/infinispan/sso/coarse/CoarseSessionsFactory.java
Labels: ready-for-merge, deps-ok

#14944 [WFLY-15735] / [WFLY-15356] Remove the security-api module.
  ee-feature-pack/common/pom.xml
  ee-feature-pack/common/src/main/resources/license/ee-feature-pack-common-licenses.xml
  ee-feature-pack/common/src/main/resources/modules/system/layers/base/org/jboss/as/security-api/main/module.xml
  pom.xml
  security/api/pom.xml
  security/api/src/main/java/org/jboss/as/security/api/ConnectionSecurityContext.java
  security/api/src/main/java/org/jboss/as/security/api/ContextStateCache.java
  security/pom.xml
  testsuite/shared/pom.xml
Labels: ready-for-merge, deps-changed, EE9

#14946 [WFLY-15027] Remove JBoss XACML as a part of PicketBox.
  ee-feature-pack/common/pom.xml
  ee-feature-pack/common/src/main/resources/license/ee-feature-pack-common-licenses.xml
  ee-feature-pack/common/src/main/resources/modules/system/layers/base/org/jboss/security/xacml/main/module.xml
  pom.xml
  testsuite/integration/basic/pom.xml
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/security/xacml/testobjects/config/jboss-ejb3.xml
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/security/xacml/testobjects/config/jbossxacml-config.xml
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/security/xacml/testobjects/config/web-basic-authn.xml
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/security/xacml/testobjects/policies/ejb-xacml-policy.xml
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/security/xacml/testobjects/policies/med-example-policySet.xml
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/security/xacml/testobjects/policies/med-example-policySet2.xml
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/security/xacml/testobjects/policies/web-xacml-policy.xml
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/security/xacml/testobjects/policies/xacml-policy2.xml
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/security/xacml/testobjects/policies/xacml-policy3.xml
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/security/xacml/testobjects/policies/xacml-policy4.xml
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/security/xacml/testobjects/policies/xacml-policy5.xml
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/security/xacml/testobjects/policies/xacml-policySet.xml
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/security/xacml/testobjects/requests/med-example-request.xml
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/security/xacml/testobjects/requests/scenario2-testcase1-request.xml
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/security/xacml/testobjects/requests/scenario2-testcase2-request.xml
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/security/xacml/testobjects/requests/scenario2-testcase3-request.xml
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/security/xacml/testobjects/requests/scenario2-testcase4-request.xml
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/security/xacml/testobjects/requests/scenario2-testcase5-request.xml
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/security/xacml/testobjects/requests/scenario2-testcase6-request.xml
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/security/xacml/testobjects/requests/scenario2-testcase7-request.xml
  testsuite/integration/web/pom.xml
Labels: ready-for-merge, deps-changed, EE9

#14896 [WFLY-15519] Move WildFly Preview to org.jvnet.staxex:stax-ex:2.0.1
  ee-9/feature-pack/pom.xml
  ee-9/pom.xml
Labels: ready-for-merge, deps-ok, EE9

#14934 [WFLY-15730] / [WFLY-15356] Remove the use of security-plugins from webservices.
  ee-feature-pack/common/src/main/resources/modules/system/layers/base/org/jboss/as/webservices/main/module.xml
  webservices/server-integration/pom.xml
  webservices/server-integration/src/main/java/org/jboss/as/webservices/logging/WSLogger.java
  webservices/server-integration/src/main/java/org/jboss/as/webservices/security/SecurityDomainContextImpl.java
  webservices/server-integration/src/main/java/org/jboss/as/webservices/service/EndpointService.java
Labels: ready-for-merge, deps-ok, EE9

#14943 [WFLY-15743] / [WFLY-15356] Remove security-plugins dependency from weld.
  ee-9/source-transform/weld/subsystem/pom.xml
  ee-feature-pack/common/src/main/resources/modules/system/layers/base/org/jboss/as/weld/main/module.xml
  weld/subsystem/pom.xml
  weld/subsystem/src/main/java/org/jboss/as/weld/services/bootstrap/WeldSecurityServices.java
Labels: ready-for-merge, deps-ok, EE9

#14964 [WFLY-15757] Finish updating JCA Smoke / Basic tests to use Elytron c…
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/jca/anno/NoRaAnnoTestCase.java
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/jca/anno/RaAnnoTestCase.java
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/jca/basic/BasicDeployment10TestCase.java
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/jca/basic/BasicDeployment15TestCase.java
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/jca/basic/BasicDeployment16TestCase.java
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/jca/basic/BasicDeployment17TestCase.java
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/jca/basic/BasicDoubleDeployment16TestCase.java
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/jca/basic/BasicDoubleDeploymentFail16_1TestCase.java
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/jca/basic/BasicDoubleDeploymentFail16_2TestCase.java
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/jca/capacitypolicies/ResourceAdapterCapacityPoliciesTestCase.java
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/jca/metrics/RaCfgMetricUnitTestCase.java
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/jca/moduledeployment/BasicFlatTestCase.java
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/jca/moduledeployment/BasicJarTestCase.java
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/jca/moduledeployment/MultiActivationFlatTestCase.java
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/jca/moduledeployment/MultiActivationJarTestCase.java
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/jca/moduledeployment/MultiObjectActivationFlatTestCase.java
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/jca/moduledeployment/MultiObjectActivationJarTestCase.java
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/jca/moduledeployment/PartialObjectActivationFlatTestCase.java
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/jca/moduledeployment/PartialObjectActivationJarTestCase.java
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/jca/moduledeployment/PureFlatTestCase.java
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/jca/moduledeployment/PureJarTestCase.java
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/jca/moduledeployment/TwoModulesFlatTestCase.java
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/jca/moduledeployment/TwoModulesJarTestCase.java
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/jca/moduledeployment/TwoModulesOfDifferentTypeTestCase.java
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/jca/moduledeployment/TwoRaFlatTestCase.java
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/jca/moduledeployment/TwoRaJarTestCase.java
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/jca/poolattributes/ResourceAdapterPoolAttributesTestCase.java
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/jca/security/WildFlyActivationRaWithElytronAuthContextTestCase.java
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/jca/statistics/ResourceAdapterStatisticsTestCase.java
  testsuite/integration/smoke/src/test/java/org/jboss/as/test/smoke/deployment/rar/tests/afterresourcecreation/AfterResourceCreationDeploymentTestCase.java
  testsuite/integration/smoke/src/test/java/org/jboss/as/test/smoke/deployment/rar/tests/configproperty/ConfigPropertyTestCase.java
  testsuite/integration/smoke/src/test/java/org/jboss/as/test/smoke/deployment/rar/tests/earpackage/EarPackagedDeploymentTestCase.java
  testsuite/integration/smoke/src/test/java/org/jboss/as/test/smoke/deployment/rar/tests/multiactivation/MultipleActivationTestCase.java
  testsuite/integration/smoke/src/test/java/org/jboss/as/test/smoke/deployment/rar/tests/multiobjectactivation/MultipleObjectActivationTestCase.java
  testsuite/integration/smoke/src/test/java/org/jboss/as/test/smoke/deployment/rar/tests/multiobjectpartialactivation/MultipleObjectPartialActivationTestCase.java
  testsuite/integration/smoke/src/test/java/org/jboss/as/test/smoke/deployment/rar/tests/raconnection/RaTestConnectionTestCase.java
  testsuite/integration/smoke/src/test/java/org/jboss/as/test/smoke/deployment/rar/tests/redeployment/ReDeploymentTestCase.java
  testsuite/integration/smoke/src/test/java/org/jboss/as/test/smoke/mgmt/resourceadapter/ResourceAdapterOperationsUnitTestCase.java
Labels: ready-for-merge, deps-ok

#14935 [WFLY-15731] / [WFLY-15356] Remove use of security-plugins from the connector subsystem.
  connector/pom.xml
  connector/src/main/java/org/jboss/as/connector/deployers/ds/processors/DsXmlDeploymentInstallProcessor.java
  connector/src/main/java/org/jboss/as/connector/deployers/ra/processors/ParsedRaDeploymentProcessor.java
  connector/src/main/java/org/jboss/as/connector/logging/ConnectorLogger.java
  connector/src/main/java/org/jboss/as/connector/services/resourceadapters/DirectConnectionFactoryActivatorService.java
  connector/src/main/java/org/jboss/as/connector/services/resourceadapters/deployment/AbstractResourceAdapterDeploymentService.java
  connector/src/main/java/org/jboss/as/connector/services/resourceadapters/deployment/ResourceAdapterXmlDeploymentService.java
  connector/src/main/java/org/jboss/as/connector/subsystems/datasources/AbstractDataSourceAdd.java
  connector/src/main/java/org/jboss/as/connector/subsystems/datasources/AbstractDataSourceService.java
  connector/src/main/java/org/jboss/as/connector/subsystems/resourceadapters/ConnectionDefinitionAdd.java
  connector/src/main/java/org/jboss/as/connector/subsystems/resourceadapters/ConnectionDefinitionService.java
  connector/src/main/java/org/jboss/as/connector/subsystems/resourceadapters/ModifiableResourceAdapter.java
  ee-feature-pack/common/src/main/resources/modules/system/layers/base/org/jboss/as/connector/main/module.xml
Labels: ready-for-merge, deps-ok, EE9

#14939 Fix for WFLY-15742, Upgrade bootable jar to 6.1.1.Final
  pom.xml
Labels: deps-ok

#14973 [WFLY-15765] Upgrade WildFly Core 18.0.0.Beta5
  pom.xml
Labels: deps-ok

#14418 [WFCORE-5489] Documentation for overridding the value of an attribute with an env var
  docs/src/main/asciidoc/_admin-guide/Management_resources.adoc
Labels: core-upgrade-needed, Feature-Docs, deps-ok

#14932 WFLY-15724: Bump gson version
  pom.xml
Labels: ready-for-merge, deps-changed

#14954 [WFLY-15657] Documentation for LoginModule compatible security realm.
  docs/src/main/asciidoc/_elytron/Elytron_Subsystem.adoc
  docs/src/main/asciidoc/_elytron/components/JAAS_Security_Realm.adoc
Labels: ready-for-merge, deps-ok

#14969 [WFLY-15673] Upgrade jboss-openjdk-orb to 8.1.7.Final
  pom.xml
Labels: ready-for-merge, deps-ok

#14970 [WFLY-15763] Add unsed modules to LayersTestCase
  testsuite/layers/src/test/java/org/jboss/as/test/layers/LayersTestCase.java
Labels: ready-for-merge, deps-ok

#14976 WFLY-15766: Upgrade HAL to 3.4.1.Final
  pom.xml
Labels: ready-for-merge, deps-ok

#14955 Upgrade SmallRye Config to 2.6.1
  pom.xml
Labels: ready-for-merge, deps-ok
