Repository wildfly/wildfly, pull requests merged in 2021-05, with the labels that each got.

#14253 [WFLY-14738] Improve HostExcludesTestCase to force us to rewrite the list of expected exclusions when necessary
  ee-9/feature-pack/src/main/resources/feature_groups/domain-host-excludes.xml
  galleon-pack/galleon-content/src/main/resources/feature_groups/domain-host-excludes.xml
  testsuite/domain/src/test/java/org/jboss/as/test/integration/domain/HostExcludesTestCase.java
Labels: deps-ok

#14268 WFLY-14756 Upgrade JGroups to 4.2.14.Final
  pom.xml
Labels: deps-ok

#14265 [WFLY-14753] Add a profile to disable compilation to facilitate tes…
  pom.xml
Labels: deps-ok

#14272 Add a profile so the preview transformations can be disabled.
  ee-9/pom.xml
Labels: deps-ok

#14252 WFLY-14436 Improve error for incorrect class for xa-datasource-class, etc.
  connector/src/main/java/org/jboss/as/connector/subsystems/datasources/JdbcDriverAdd.java
Labels: deps-ok

#14275 [WFLY-14764] Update SmallRye Health to 3.0.2
  pom.xml
Labels: deps-ok

#14263 [WFLY-14750] Batch task not restarted after server resumed from suspended state
  batch-jberet/src/main/java/org/wildfly/extension/batch/jberet/deployment/JobOperatorService.java
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/batch/suspend/LongRunningBatchlet.java
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/batch/suspend/SuspendBatchletTestCase.java
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/batch/suspend/suspend-batchlet.xml
Labels: deps-ok

#14278 Remove duplicated string descriptions in distributable-web extension
  clustering/web/extension/src/main/resources/org/wildfly/extension/clustering/web/LocalDescriptions.properties
Labels: deps-ok

#14274 [WFLY-14758] Don't try to use java.security.acl.Group in WS subsystem…
  webservices/server-integration/src/main/java/org/jboss/as/webservices/util/SubjectUtil.java
Labels: deps-ok

#14279 [WFLY-14771] Define commons-io dependency in root pom
  pom.xml
Labels: deps-ok

#14282 [WFLY-14701] Narayana component upgrade to 5.11.2.Final
  pom.xml
Labels: deps-ok

#14212 WFLY-14263 Updating the outdated 'Remote EJB invocations via JNDI - E…
  docs/src/main/asciidoc/Developer_Guide.adoc
  docs/src/main/asciidoc/_developer-guide/Remote_Jakarta_Enterprise_Beans_invocations_via_JNDI_-_Jakarta_Enterprise_Beans_client_API_or_wildfly-naming-client_project.adoc
Labels: deps-ok

#14287 WFLY-14776 Upgrade smallrye-open-api to 2.1.4
  pom.xml
Labels: deps-ok

#14288 [WFLY-14777] Upgrade to SmallRye Metrics 3.0.3
  pom.xml
Labels: deps-ok

#14284 [WFLY-14753] Have noCompile profile disable compilation altogether, n…
  pom.xml
Labels: deps-ok

#14277 WFLY-14766 Fix intermittent failures in HotRod session expiration tests.
  testsuite/integration/clustering/src/test/java/org/jboss/as/test/clustering/cluster/web/expiration/SessionExpirationTestCase.java
  testsuite/integration/clustering/src/test/java/org/jboss/as/test/clustering/cluster/web/remote/CoarseHotRodSessionExpirationTestCase.java
  testsuite/integration/clustering/src/test/java/org/jboss/as/test/clustering/cluster/web/remote/FineHotRodSessionExpirationTestCase.java
Labels: deps-ok

#14283 Update clustering tests to use hotrod protocol version 3.1.
  testsuite/integration/clustering/src/test/java/org/jboss/as/test/clustering/cluster/AbstractClusteringTestCase.java
Labels: deps-ok

#14271 [WFLY-14762] Expose complete-timeout Infinispan transaction setting
  clustering/infinispan/extension/src/main/java/org/jboss/as/clustering/infinispan/subsystem/InfinispanSubsystemXMLReader.java
  clustering/infinispan/extension/src/main/java/org/jboss/as/clustering/infinispan/subsystem/TransactionResourceDefinition.java
  clustering/infinispan/extension/src/main/java/org/jboss/as/clustering/infinispan/subsystem/TransactionServiceConfigurator.java
  clustering/infinispan/extension/src/main/java/org/jboss/as/clustering/infinispan/subsystem/XMLAttribute.java
  clustering/infinispan/extension/src/main/resources/org/jboss/as/clustering/infinispan/subsystem/LocalDescriptions.properties
  clustering/infinispan/extension/src/main/resources/schema/jboss-as-infinispan_13_0.xsd
  clustering/infinispan/extension/src/test/resources/org/jboss/as/clustering/infinispan/subsystem/subsystem-infinispan-13_0.xml
Labels: deps-ok

#14285 [WFLY-14773] Don't add the resteasy-rxjava2 module in the RSO deployer
  microprofile/reactive-streams-operators-smallrye/extension/src/main/java/org/wildfly/extension/microprofile/reactive/streams/operators/deployment/ReactiveStreamsOperatorsDependencyProcessor.java
Labels: deps-ok

#14290 [WFLY-14763]:Upgrade jbossws-cxf to 5.4.4.Final
  pom.xml
Labels: deps-ok

#14294 WFLY-14781 Upgrade Infinispan to 12.1.2.Final
  clustering/infinispan/extension/src/main/java/org/jboss/as/clustering/infinispan/subsystem/TransactionResourceDefinition.java
  clustering/infinispan/extension/src/main/java/org/jboss/as/clustering/infinispan/subsystem/TransactionServiceConfigurator.java
  pom.xml
Labels: deps-ok

#14295 [WFLY-14757] IIOP: remove TrustedIdentityTokenLoginModule class
  iiop-openjdk/src/main/java/org/wildfly/iiop/openjdk/security/TrustedIdentityTokenLoginModule.java
Labels: deps-ok

#14281 WFLY-14767 Upgrade to Hibernate Search 5.10.11.Final
  docs/src/main/asciidoc/_developer-guide/Implicit_module_dependencies_for_deployments.adoc
  ee-feature-pack/common/pom.xml
  ee-feature-pack/common/src/main/resources/license/ee-feature-pack-common-licenses.xml
  ee-feature-pack/common/src/main/resources/modules/system/layers/base/org/apache/avro/main/module.xml
  ee-feature-pack/common/src/main/resources/modules/system/layers/base/org/codehaus/jackson/jackson-core-asl/main/module.xml
  ee-feature-pack/common/src/main/resources/modules/system/layers/base/org/codehaus/jackson/jackson-jaxrs/main/module.xml
  ee-feature-pack/common/src/main/resources/modules/system/layers/base/org/codehaus/jackson/jackson-mapper-asl/main/module.xml
  ee-feature-pack/common/src/main/resources/modules/system/layers/base/org/codehaus/jackson/jackson-xc/main/module.xml
  ee-feature-pack/common/src/main/resources/modules/system/layers/base/org/jboss/as/jaxrs/main/module.xml
  ee-feature-pack/common/src/main/resources/modules/system/layers/base/org/jboss/resteasy/resteasy-jackson-provider/main/module.xml
  jaxrs/src/main/java/org/jboss/as/jaxrs/JaxrsSubsystemDefinition.java
  jaxrs/src/main/java/org/jboss/as/jaxrs/deployment/JaxrsDependencyProcessor.java
  pom.xml
  testsuite/integration/basic/pom.xml
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/jaxrs/jackson/Country.java
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/jaxrs/jackson/Customer.java
Labels: deps-changed

#14298 WFLY-14785 Incorrect javadoc in org.jboss.as.security.logging.Securit…
  security/subsystem/src/main/java/org/jboss/as/security/logging/SecurityLogger.java
Labels: deps-ok

#14286 [WFLY-14775] Add test for Metrics and RBAC
  testsuite/integration/microprofile/src/test/java/org/wildfly/test/integration/microprofile/metrics/TestApplication.java
  testsuite/integration/microprofile/src/test/java/org/wildfly/test/integration/microprofile/metrics/rbac/MicroProfileMetricsRbacTestCase.java
Labels: deps-ok

#14299 Revert "[WFLY-14757] IIOP: remove TrustedIdentityTokenLoginModule class"
  iiop-openjdk/src/main/java/org/wildfly/iiop/openjdk/security/TrustedIdentityTokenLoginModule.java
Labels: deps-ok

#14296 [WFLY-14782] Move WildFly Preview to org.glassfish:jakarta.enterprise…
  ee-9/feature-pack/pom.xml
Labels: deps-ok

#14300 [WFLY-14788] Make use of the imported credential-reference schema in …
  undertow/src/main/resources/schema/wildfly-undertow_12_0.xsd
Labels: deps-ok

#14301 WFLY-14790 Upgrade Infinispan to 12.1.3.Final
  ee-feature-pack/common/src/main/resources/modules/system/layers/base/org/infinispan/client/hotrod/main/module.xml
  pom.xml
Labels: deps-ok

#14302 [WFLY-14791] Upgrade xom to 1.3.7
  ee-feature-pack/common/pom.xml
  ee-feature-pack/common/src/main/resources/license/ee-feature-pack-common-licenses.xml
  ee-feature-pack/common/src/main/resources/modules/system/layers/base/nu/xom/main/module.xml
  pom.xml
  testsuite/domain/pom.xml
Labels: deps-changed

#14276 [WFLY-14580] Upgrade to RSO 2.0
  docs/src/main/asciidoc/_admin-guide/subsystem-configuration/MicroProfile_Reactive_Streams_Operators_SmallRye.adoc
  pom.xml
Labels: Feature, deps-changed

#14254 [WFLY-14742] ServletContext#getResourcePaths returns erroneous additi…
  undertow/src/main/java/org/wildfly/extension/undertow/deployment/ServletResourceManager.java
Labels: deps-ok

#14303 [WFLY-14792] Avoid making unneeded deep reflection calls from ParsedServiceDeploymentProcessor
  sar/src/main/java/org/jboss/as/service/MBeanServices.java
  sar/src/main/java/org/jboss/as/service/ParsedServiceDeploymentProcessor.java
  sar/src/main/java/org/jboss/as/service/ReflectionUtils.java
Labels: deps-ok

#14307 [WFLY-14802] Upgrade jboss-ejb-client to 4.0.40.Final
  pom.xml
Labels: deps-ok

#14306 Fix for WFLY-14801, Upgrade galleon-plugins to 5.2.0.Alpha1
  pom.xml
Labels: deps-ok

#14309 WFLY-14795 Upgrade smallrye-fault-tolerance to 5.1.0
  pom.xml
Labels: deps-ok

#14311 [WFLY-14806] Upgrade wildfly-http-client to 1.1.7.Final
  pom.xml
Labels: deps-ok

#14312 [WFLY-14811] Upgrade Ironjacamar to 1.4.33.Final
  connector/src/main/java/org/jboss/as/connector/util/ModelNodeUtil.java
  pom.xml
Labels: deps-ok

#14250 [WFLY-14655] Add proper ordering of ServiceMBeanSupport postRegister calls
  sar/src/main/java/org/jboss/as/service/MBeanRegistrationService.java
  sar/src/main/java/org/jboss/as/service/MBeanServices.java
  sar/src/main/java/org/jboss/as/service/ServiceNameFactory.java
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/sar/order/LifecycleEmitter.java
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/sar/order/LifecycleEmitterMBean.java
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/sar/order/LifecycleListener.java
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/sar/order/LifecycleListenerMBean.java
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/sar/order/ServiceMBeanSupportOrderingTestCase.java
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/sar/order/jboss-service.xml
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/sar/order/result-jboss-service.xml
Labels: deps-ok

#14293 [WFLY-14780] fix log message at container shutdown when EJB subsystem defines enable-graceful-txn-shutdown
  ejb3/src/main/java/org/jboss/as/ejb3/suspend/EJBSuspendHandlerService.java
Labels: deps-ok

#14314 [WFLY-14815] Temporarily disable broken assertions so Undertow can be…
  testsuite/integration/web/src/test/java/org/jboss/as/test/integration/web/handlers/ForwardedHandlerTestCase.java
Labels: deps-ok

#14317 [WFLY-14818] Require Java 8 when the deploy lifecycle phase is executed.
  pom.xml
Labels: deps-ok

#14315 WFLY-14816 Reduce fragility of EnumSet/EnumMap marshalling
  clustering/marshalling/api/src/test/java/org/wildfly/clustering/marshalling/AbstractUtilTestCase.java
  clustering/marshalling/api/src/test/java/org/wildfly/clustering/marshalling/Empty.java
  clustering/marshalling/protostream/src/main/java/org/wildfly/clustering/marshalling/protostream/util/EnumMapMarshaller.java
  clustering/marshalling/protostream/src/main/java/org/wildfly/clustering/marshalling/protostream/util/EnumSetFieldSetMarshaller.java
  clustering/marshalling/protostream/src/test/java/org/wildfly/clustering/marshalling/protostream/TestSerializationContextInitializer.java
  clustering/marshalling/protostream/src/test/resources/org.wildfly.clustering.marshalling.proto
  clustering/marshalling/spi/src/main/java/org/wildfly/clustering/marshalling/spi/util/EnumMapExternalizer.java
  clustering/marshalling/spi/src/main/java/org/wildfly/clustering/marshalling/spi/util/EnumSetExternalizer.java
Labels: deps-ok

#14316 [WFLY-14807] Upgrade to smallrye-jwt 3.1.1
  pom.xml
Labels: deps-ok

#14289 WFLY-14778 Updated the class with a dependency on http-deprecated Elytron module to no longer rely on deprecated classes
  undertow/src/main/java/org/wildfly/extension/undertow/ApplicationSecurityDomainDefinition.java
Labels: deps-ok

#12224 [WFLY-8449] / [WEJBHTTP-23] EJB contextData not sent back to client in response when using EJB over HTTP
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/ejb/remote/contextdata/ClientInterceptorReturnDataEjbOverHttpTestCase.java
Labels: deps-ok, fixme

#14320 [WFCORE-5406][WFLY-14793] Adding required --add-opens & --add-exports clauses
  pom.xml
Labels: deps-ok

#14305 [WFLY-14799] Upgrade netty to 4.1.65
  pom.xml
Labels: deps-ok, ready-for-merge

#14318 WFLY-14819 Remove some useless marshallers/externalizers
  clustering/marshalling/api/src/main/resources/java.util.proto
  clustering/marshalling/api/src/test/java/org/wildfly/clustering/marshalling/AbstractUtilTestCase.java
  clustering/marshalling/protostream/src/main/java/org/wildfly/clustering/marshalling/protostream/util/UtilMarshallerProvider.java
  clustering/marshalling/spi/src/main/java/org/wildfly/clustering/marshalling/spi/util/UtilExternalizerProvider.java
Labels: deps-ok, ready-for-merge

#14321 [WFLY-14823] Upgrade WildFly Core 16.0.0.Beta4
  pom.xml
Labels: deps-ok
