Repository wildfly/wildfly, pull requests merged in 2021-03, with the labels that each got.

#13428 [WFLY-13700] Add ability to configure stale transaction timeout for l…
  transactions/src/main/java/org/jboss/as/txn/service/LocalTransactionContextService.java
  transactions/src/main/java/org/jboss/as/txn/subsystem/Attribute.java
  transactions/src/main/java/org/jboss/as/txn/subsystem/CommonAttributes.java
  transactions/src/main/java/org/jboss/as/txn/subsystem/Element.java
  transactions/src/main/java/org/jboss/as/txn/subsystem/Namespace.java
  transactions/src/main/java/org/jboss/as/txn/subsystem/TransactionExtension.java
  transactions/src/main/java/org/jboss/as/txn/subsystem/TransactionSubsystem30Parser.java
  transactions/src/main/java/org/jboss/as/txn/subsystem/TransactionSubsystem60Parser.java
  transactions/src/main/java/org/jboss/as/txn/subsystem/TransactionSubsystemAdd.java
  transactions/src/main/java/org/jboss/as/txn/subsystem/TransactionSubsystemRootResourceDefinition.java
  transactions/src/main/java/org/jboss/as/txn/subsystem/TransactionSubsystemXMLPersister.java
  transactions/src/main/java/org/jboss/as/txn/subsystem/TransactionTransformers.java
  transactions/src/main/resources/org/jboss/as/txn/subsystem/LocalDescriptions.properties
  transactions/src/main/resources/schema/wildfly-txn_6_0.xsd
  transactions/src/main/resources/subsystem-templates/transactions.xml
  transactions/src/test/java/org/jboss/as/txn/subsystem/TransactionSubsystemTestCase.java
  transactions/src/test/resources/org/jboss/as/txn/subsystem/full.xml
  transactions/src/test/resources/org/jboss/as/txn/subsystem/subsystem.xml
Labels: 23.x, Feature, deps-ok

#14055 [WFLY-14478] Tidy up the testsuite/scripts handling; allow it to test…
  testsuite/pom.xml
  testsuite/scripts/pom.xml
Labels: deps-ok

#14049 [WFLY-14493]: Add tests to the Microprofile OpenTracing subsystem for
  microprofile/opentracing-extension/src/main/java/org/wildfly/extension/microprofile/opentracing/JaegerTracerConfigurationAddHandler.java
  microprofile/opentracing-extension/src/main/java/org/wildfly/extension/microprofile/opentracing/resolver/JaegerTracerConfiguration.java
  microprofile/opentracing-extension/src/test/java/org/wildfly/extension/microprofile/opentracing/Subsystem_3_0_ParsingTestCase.java
  microprofile/opentracing-extension/src/test/java/org/wildfly/extension/microprofile/opentracing/resolver/JaegerTracerConfigurationTest.java
  microprofile/opentracing-extension/src/test/resources/org/wildfly/extension/microprofile/opentracing/subsystem_3_0_reject_transform.xml
Labels: deps-ok

#14052 WFLY-14495 SchedulerTopologyChangeListener can throw IAE during scale down
  clustering/ee/infinispan/src/main/java/org/wildfly/clustering/ee/infinispan/scheduler/SchedulerTopologyChangeListener.java
Labels: deps-ok

#14022 WFLY-14460 Upgrade netty from 4.1.58.Final to 4.1.59.Final
  pom.xml
Labels: deps-ok

#14051 WFLY-14462 exclude-local-receiver and local-receiver-pass-by-value no…
  docs/src/main/asciidoc/_admin-guide/subsystem-configuration/EJB3.adoc
  ejb3/src/main/resources/schema/wildfly-ejb3_9_0.xsd
  ejb3/src/test/resources/org/jboss/as/ejb3/subsystem/with-expression-subsystem.xml
Labels: deps-ok

#14064 [WFLY-1502] At Undertow subsystem, replace "console-access-log" Strin…
  undertow/src/main/java/org/wildfly/extension/undertow/ConsoleAccessLogDefinition.java
  undertow/src/main/java/org/wildfly/extension/undertow/Constants.java
  undertow/src/test/java/org/wildfly/extension/undertow/UndertowTransformersTestCase.java
Labels: deps-ok

#14066 WFLY-14503 Optimize marshalling of ElytronAuthentication programmatic flag
  clustering/web/undertow/src/main/java/org/wildfly/clustering/web/undertow/sso/elytron/DistributableSingleSignOn.java
  clustering/web/undertow/src/main/java/org/wildfly/clustering/web/undertow/sso/elytron/ElytronAuthentication.java
  clustering/web/undertow/src/main/java/org/wildfly/clustering/web/undertow/sso/elytron/ElytronAuthenticationMarshaller.java
  clustering/web/undertow/src/main/resources/org.wildfly.clustering.web.undertow.sso.elytron.proto
Labels: deps-ok

#14067 WFLY-14504 Refactor DefaultNonBlockingThreadFactory into wildfly-clustering-infinispan-spi
  clustering/infinispan/extension/src/main/java/org/jboss/as/clustering/infinispan/subsystem/ThreadPoolServiceConfigurator.java
  clustering/infinispan/extension/src/main/java/org/jboss/as/clustering/infinispan/subsystem/remote/ClientThreadPoolServiceConfigurator.java
  clustering/infinispan/spi/src/main/java/org/wildfly/clustering/infinispan/spi/DefaultNonBlockingThreadFactory.java
Labels: deps-ok

#14008 [WFLY-14386] Have SecurityBootstrapService set the TCCL to any JACC m…
  security/subsystem/src/main/java/org/jboss/as/security/service/SecurityBootstrapService.java
Labels: deps-ok, ready-for-merge

#14065 [WFLY-12960] Use expressions in subsystem XML for the subsystem test …
  jaxrs/src/test/java/org/jboss/as/jaxrs/JaxrsSubsystem20TestCase.java
  jaxrs/src/test/java/org/jboss/as/jaxrs/JaxrsTransformersTestCase.java
  jaxrs/src/test/resources/org/jboss/as/jaxrs/jaxrs-2.0-expressions.xml
Labels: deps-ok

#14063 [WFLY-14501] Add tests to IIOP subsystem for attributes that allow ex…
  iiop-openjdk/src/test/java/org/wildfly/iiop/openjdk/IIOPSubsystemTestCase.java
  iiop-openjdk/src/test/resources/org/wildfly/iiop/openjdk/subsystem-full-expressions.xml
Labels: deps-ok

#14056 WFLY-14498 ChannelCommandDispatcherFactory needs to use a configurable Contextualizer for created dispatchers
  clustering/common/src/main/java/org/jboss/as/clustering/context/DefaultContextualizer.java
  clustering/server/src/main/java/org/wildfly/clustering/server/dispatcher/ChannelCommandDispatcherFactory.java
  clustering/server/src/main/java/org/wildfly/clustering/server/dispatcher/ChannelCommandDispatcherFactoryConfiguration.java
  clustering/server/src/main/java/org/wildfly/clustering/server/dispatcher/ChannelCommandDispatcherFactoryServiceConfigurator.java
Labels: deps-ok

#14072 [WFLY-14515] Upgrade WildFly Preview's JAX-RS API to org.jboss.spec.j…
  ee-9/feature-pack/pom.xml
  ee-9/feature-pack/src/main/resources/modules/system/layers/base/jakarta/ws/rs/api/main/module.xml
Labels: deps-ok

#14062 [WFLY-14500] Add extra mod-cluster filter to test resources undertow-…
  undertow/src/test/resources/org/wildfly/extension/undertow/undertow-11.0.xml
  undertow/src/test/resources/org/wildfly/extension/undertow/undertow-12.0.xml
Labels: deps-ok

#14074 WFLY-14519 Add EAP 7.3.0 transformers tests for jgroups subsystem
  clustering/jgroups/extension/src/main/java/org/jboss/as/clustering/jgroups/subsystem/JGroupsModel.java
  clustering/jgroups/extension/src/test/java/org/jboss/as/clustering/jgroups/subsystem/JGroupsTransformersTestCase.java
  clustering/jgroups/extension/src/test/resources/org/jboss/as/clustering/jgroups/subsystem/subsystem-jgroups-transform-7_0_0.xml
Labels: deps-ok

#14073 WFLY-14514 Add EAP 7.3.0 transformers tests for singleton subsystem
  clustering/singleton/extension/src/main/java/org/wildfly/extension/clustering/singleton/SingletonModel.java
  clustering/singleton/extension/src/test/java/org/wildfly/extension/clustering/singleton/SingletonTransformersTestCase.java
Labels: deps-ok

#14070 WFLY-14507 HotRod/DatabasePersistenceWebFailoverTestCase should use n…
  testsuite/integration/clustering/src/test/java/org/jboss/as/test/clustering/cluster/web/persistence/AbstractDatabasePersistenceWebFailoverTestCase.java
  testsuite/integration/clustering/src/test/java/org/jboss/as/test/clustering/cluster/web/remote/AbstractHotRodPersistenceWebFailoverTestCase.java
Labels: deps-ok

#14082 Revert "WFLY-14495 SchedulerTopologyChangeListener can throw IAE during scale down"
  clustering/ee/infinispan/src/main/java/org/wildfly/clustering/ee/infinispan/scheduler/SchedulerTopologyChangeListener.java
Labels: deps-ok

#14078 WFLY-14520 Add EAP 7.3.0 transformers tests for infinispan subsystem
  clustering/infinispan/extension/src/test/java/org/jboss/as/clustering/infinispan/subsystem/InfinispanTransformersTestCase.java
  clustering/infinispan/extension/src/test/resources/org/jboss/as/clustering/infinispan/subsystem/subsystem-infinispan-transform-11_0_0.xml
Labels: deps-ok

#14057 WFLY-14316 Replace 'Interceptors' references in java doc with corresp…
  docs/src/main/asciidoc/Getting_Started_Guide.adoc
  docs/src/main/asciidoc/_developer-guide/Jakarta_XML_Web_Services/Apache_CXF_integration.adoc
  ee/src/main/java/org/jboss/as/ee/component/ComponentConfiguration.java
  ee/src/main/java/org/jboss/as/ee/component/interceptors/InterceptorOrder.java
  jpa/subsystem/src/main/java/org/jboss/as/jpa/processor/JPAInterceptorProcessor.java
  weld/common/src/main/java/org/jboss/as/weld/interceptors/Jsr299BindingsInterceptor.java
  weld/subsystem/src/main/java/org/jboss/as/weld/deployment/processors/WeldComponentIntegrationProcessor.java
Labels: deps-ok

#14032 Replace 'Java EE Connector Architecture|JCA' references in java doc w…
  connector/src/main/java/org/jboss/as/connector/logging/ConnectorLogger.java
  connector/src/main/java/org/jboss/as/connector/security/ElytronCallbackHandler.java
  connector/src/main/java/org/jboss/as/connector/services/resourceadapters/deployment/AbstractResourceAdapterDeploymentService.java
  connector/src/main/java/org/jboss/as/connector/services/transactionintegration/TransactionIntegrationService.java
  connector/src/main/java/org/jboss/as/connector/services/workmanager/DistributedWorkManagerService.java
  connector/src/main/java/org/jboss/as/connector/services/workmanager/WorkManagerService.java
  connector/src/main/java/org/jboss/as/connector/subsystems/datasources/GetDataSourceClassInfoOperationHandler.java
  connector/src/main/java/org/jboss/as/connector/subsystems/jca/JcaArchiveValidationWriteHandler.java
  connector/src/main/java/org/jboss/as/connector/subsystems/jca/JcaConfigService.java
  connector/src/main/java/org/jboss/as/connector/subsystems/jca/JcaSubsystemAdd.java
  connector/src/main/resources/org/jboss/as/connector/subsystems/jca/LocalDescriptions.properties
  docs/src/main/asciidoc/JavaEE_Tutorial.adoc
  docs/src/main/asciidoc/_admin-guide/subsystem-configuration/Messaging.adoc
  docs/src/main/asciidoc/_admin-guide/subsystem-configuration/Security.adoc
  docs/src/main/asciidoc/_developer-guide/How_do_I_migrate_my_application_from_AS7_to_WildFly.adoc
  docs/src/main/asciidoc/_developer-guide/Implicit_module_dependencies_for_deployments.adoc
  docs/src/main/asciidoc/_elytron/Credential_Store.adoc
  docs/src/main/asciidoc/_galleon/Galleon_layers.adoc
  docs/src/main/asciidoc/_javaee-guide/Jakarta_Connectors_Architecture.adoc
  docs/src/main/asciidoc/_javaee-guide/JavaEE_Connector_Architecture_(JCA).adoc
  ejb3/src/main/java/org/jboss/as/ejb3/deployment/processors/MessageDrivenComponentDescriptionFactory.java
  messaging-activemq/src/main/java/org/wildfly/extension/messaging/activemq/deployment/JMSConnectionFactoryDefinitionInjectionSource.java
  messaging-activemq/src/main/java/org/wildfly/extension/messaging/activemq/deployment/JMSDestinationDefinitionInjectionSource.java
  testsuite/domain/src/test/java/org/jboss/as/test/integration/domain/ExpressionSupportSmokeTestCase.java
  testsuite/integration/basic/pom.xml
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/ejb/mdb/activationname/ActivationNameTestCase.java
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/jca/JcaTestsUtil.java
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/jca/capacitypolicies/AbstractDatasourceCapacityPoliciesTestCase.java
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/jca/capacitypolicies/DatasourceCapacityPoliciesTestCase.java
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/jca/capacitypolicies/ResourceAdapterCapacityPoliciesTestCase.java
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/jca/capacitypolicies/XADatasourceCapacityPoliciesTestCase.java
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/jca/security/workmanager/WildFlyActivationRaWithWMElytronSecurityDomainWorkManagerElytronDisabledTestCase.java
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/jca/security/workmanager/WildFlyActivationRaWithWMElytronSecurityDomainWorkManagerElytronEnabledTestCase.java
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/jca/security/workmanager/WildFlyActivationRaWithWMSecurityDomainWorkManagerTestCase.java
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/jca/statistics/JcaStatisticsBase.java
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/transaction/inflow/TransactionInflowTestCase.java
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/transaction/inflow/TransactionInflowTextMessage.java
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/transaction/inflow/TransactionInflowWork.java
  transactions/src/main/java/org/jboss/as/txn/integration/JBossContextXATerminator.java
  transactions/src/main/java/org/jboss/as/txn/logging/TransactionLogger.java
  transactions/src/main/java/org/jboss/as/txn/service/internal/tsr/JCAOrderedLastSynchronizationList.java
  transactions/src/main/java/org/jboss/as/txn/service/internal/tsr/TransactionSynchronizationRegistryWrapper.java
  transactions/src/main/java/org/jboss/as/txn/subsystem/TransactionSubsystemRootResourceDefinition.java
  transactions/src/main/resources/org/jboss/as/txn/subsystem/LocalDescriptions.properties
Labels: deps-ok

#14090 [WFLY-14535] Upgrade WildFly Core 15.0.0.Final
  pom.xml
Labels: 23.x, Blocker, deps-ok

#14081 [WFLY-13692] fix weld parsing to swallow elemen
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/weld/ejb/jbossall/JBossAllBean.java
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/weld/ejb/jbossall/JBossAllEjbJarTestCase.java
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/weld/ejb/jbossall/jboss-all.xml
  weld/subsystem/src/main/java/org/jboss/as/weld/AbstractWeldJBossAllParser.java
  weld/subsystem/src/main/java/org/jboss/as/weld/WeldJBossAll10Parser.java
  weld/subsystem/src/main/java/org/jboss/as/weld/WeldJBossAll11Parser.java
Labels: 23.x, deps-ok, ready-for-merge

#14075 WFLY-14474 HHH000431: Unable to determine H2 database version, certain features may not work when using ExampleDS
  ee-feature-pack/common/src/main/resources/modules/system/layers/base/org/hibernate/main/module.xml
Labels: deps-ok

#14080 [WFLY-14516]:SecurityIdentity is not re-used when using SubjectCreatingPolicyInterceptor in a CXF endpoint
  testsuite/integration/ws/pom.xml
  testsuite/integration/ws/src/test/java/org/jboss/as/test/integration/ws/wsse/ElytronUsernameTokenImpl.java
  testsuite/integration/ws/src/test/java/org/jboss/as/test/integration/ws/wsse/trust/WSTrustTestCaseElytronSecuritySetupTask.java
  testsuite/integration/ws/src/test/java/org/jboss/as/test/integration/ws/wsse/usernametoken/UsernameTokenElytronTestCase.java
  testsuite/integration/ws/src/test/java/org/jboss/as/test/integration/ws/wsse/usernametoken/jboss-ejb3-elytron-properties.xml
  testsuite/integration/ws/src/test/java/org/jboss/as/test/integration/ws/wsse/wsdl/UsernameToken.wsdl
  testsuite/integration/ws/src/test/java/org/jboss/as/test/integration/ws/wsse/wsdl/UsernameToken_schema1.xsd
  webservices/server-integration/src/main/java/org/jboss/as/webservices/security/ElytronSecurityDomainContextImpl.java
  webservices/server-integration/src/main/java/org/jboss/as/webservices/util/SubjectUtil.java
Labels: 23.x, deps-ok, ready-for-merge

#14059 WFLY-14388 resolve expression for transaction-support attribute in r-a subsystem.
  connector/src/main/java/org/jboss/as/connector/subsystems/resourceadapters/CommonIronJacamarParser.java
  connector/src/main/java/org/jboss/as/connector/subsystems/resourceadapters/RaOperationUtil.java
  connector/src/main/java/org/jboss/as/connector/subsystems/resourceadapters/ResourceAdapterParser.java
  connector/src/main/java/org/jboss/as/connector/subsystems/resourceadapters/ResourceAdapterSubsystemParser.java
  connector/src/test/resources/org/jboss/as/connector/subsystems/resourceadapters/resource-adapters-xapool-expression.xml
  connector/src/test/resources/org/jboss/as/connector/subsystems/resourceadapters/resource-adapters-xapool-expression2.xml
Labels: deps-ok

#14083 [WFLY-14529] The deployment used by KeystoreRealmTestCase should be marked as "testable=false"
  testsuite/integration/elytron/src/test/java/org/wildfly/test/integration/elytron/certs/realm/KeystoreRealmTestCase.java
Labels: deps-ok

#14069 Document --cli-script introduced by WFCORE-5324
  docs/src/main/asciidoc/Bootable_Guide.adoc
Labels: 23.x, Feature-Docs, deps-ok

#14060 [WFLY-5885] JBOSS_HOME validity check in jconsole sh, ps1 and bat scripts
  ee-feature-pack/common/src/main/resources/content/bin/jconsole.bat
  ee-feature-pack/common/src/main/resources/content/bin/jconsole.ps1
  ee-feature-pack/common/src/main/resources/content/bin/jconsole.sh
Labels: deps-ok

#14076 WFLY-14522 Don't enable near-cache in HotRodSessionManager if max-active-sessions is undefined
  clustering/web/hotrod/src/main/java/org/wildfly/clustering/web/hotrod/session/SessionManagerNearCacheFactory.java
Labels: deps-ok

#14079 [WFLY-14524][WFLY-14525] Prevent vendor metric registry modifications…
  metrics/src/main/java/org/wildfly/extension/metrics/MetricRegistry.java
  metrics/src/main/java/org/wildfly/extension/metrics/MetricsContextService.java
  metrics/src/main/java/org/wildfly/extension/metrics/WildFlyMetricRegistry.java
  microprofile/metrics-smallrye/src/main/java/org/wildfly/extension/microprofile/metrics/MicroProfileMetricsContextService.java
  microprofile/metrics-smallrye/src/main/java/org/wildfly/extension/microprofile/metrics/MicroProfileMetricsSubsystemAdd.java
  microprofile/metrics-smallrye/src/main/java/org/wildfly/extension/microprofile/metrics/MicroProfileVendorMetricRegistry.java
Labels: 23.x, Critical, deps-ok, ready-for-merge

#14030 WFLY-14468 Add support for using Infinispan APIs from a deployment
  docs/src/main/asciidoc/_high-availability/Clustering_API.adoc
  docs/src/main/asciidoc/_high-availability/Subsystem_Support.adoc
  docs/src/main/asciidoc/_high-availability/subsystem-support/Infinispan_Subsystem.adoc
  ee-feature-pack/common/src/main/resources/modules/system/layers/base/org/infinispan/client/hotrod/main/module.xml
  ee-feature-pack/common/src/main/resources/modules/system/layers/base/org/infinispan/commons/main/module.xml
  ee-feature-pack/common/src/main/resources/modules/system/layers/base/org/infinispan/main/module.xml
Labels: 23.x, Feature, deps-ok, missing-reqs

#14094 [WFLY-14388] Document the limited expression support for transaction-…
  connector/src/main/resources/org/jboss/as/connector/subsystems/resourceadapters/LocalDescriptions.properties
Labels: 23.x, deps-ok

#14086 WFLY-14530 InfinispanSessionManager should not expose JNDI contexts to its Infinispan listeners
  clustering/web/infinispan/src/main/java/org/wildfly/clustering/web/infinispan/session/InfinispanSessionManager.java
Labels: 23.x, deps-ok, ready-for-merge

#14092 [WFLY-14537] Upgrade RESTEasy to 3.15.1.Final
  pom.xml
Labels: 23.x, deps-ok

#13982 [WFLY-13779] Require reload when removing config source
  microprofile/config-smallrye/src/main/java/org/wildfly/extension/microprofile/config/smallrye/ClassConfigSourceRegistrationService.java
  microprofile/config-smallrye/src/main/java/org/wildfly/extension/microprofile/config/smallrye/ConfigSourceDefinition.java
  microprofile/config-smallrye/src/main/java/org/wildfly/extension/microprofile/config/smallrye/ConfigSourceProviderDefinition.java
  microprofile/config-smallrye/src/main/java/org/wildfly/extension/microprofile/config/smallrye/ConfigSourceProviderRegistrationService.java
  microprofile/config-smallrye/src/main/java/org/wildfly/extension/microprofile/config/smallrye/PropertiesConfigSourceRegistrationService.java
  microprofile/config-smallrye/src/main/java/org/wildfly/extension/microprofile/config/smallrye/ServiceNames.java
  testsuite/integration/microprofile/src/test/java/org/wildfly/test/integration/microprofile/config/smallrye/SubsystemConfigSourceTask.java
  testsuite/integration/microprofile/src/test/java/org/wildfly/test/integration/microprofile/config/smallrye/management/config_source/ConfigSourceFromClassTestCase.java
  testsuite/integration/microprofile/src/test/java/org/wildfly/test/integration/microprofile/config/smallrye/management/config_source/SetupTask.java
  testsuite/integration/microprofile/src/test/java/org/wildfly/test/integration/microprofile/config/smallrye/management/config_source_provider/SetupTask.java
  testsuite/integration/microprofile/src/test/java/org/wildfly/test/integration/microprofile/opentracing/ConfigHttpPathTask.java
  testsuite/integration/microprofile/src/test/java/org/wildfly/test/integration/microprofile/opentracing/ResourceWithCustomOperationNameBeanTestCase.java
  testsuite/integration/microprofile/src/test/java/org/wildfly/test/integration/microprofile/opentracing/application/WithCustomOperationNameEndpoint.java
Labels: 23.x, deps-ok

#14096 WFLY-14539 Review for expansion expression testing in mod_cluster sub…
  mod_cluster/extension/src/test/resources/org/wildfly/extension/mod_cluster/subsystem-transform-7_0_0.xml
  mod_cluster/extension/src/test/resources/org/wildfly/extension/mod_cluster/subsystem_5_0.xml
Labels: 23.x, deps-ok

#14089 [WFLY-14533][WFLY-13837] Add EE 9 xsds to WildFly Preview
  ee-9/feature-pack/pom.xml
  undertow/src/main/java/org/wildfly/extension/undertow/deployment/WebParsingDeploymentProcessor.java
Labels: 23.x, deps-ok

#14095 WFLY-13063: adjust sizes of id cache and confirmation window
  messaging-activemq/src/main/java/org/wildfly/extension/messaging/activemq/CommonAttributes.java
  messaging-activemq/src/main/java/org/wildfly/extension/messaging/activemq/MessagingTransformerRegistration.java
  messaging-activemq/src/main/java/org/wildfly/extension/messaging/activemq/jms/legacy/LegacyConnectionFactoryDefinition.java
  messaging-activemq/src/test/java/org/wildfly/extension/messaging/activemq/AttributeDefaultsTest.java
Labels: 23.x, deps-ok

#14085 WFLY-14526 Distributable sessions cannot be invalidated via CLI
  clustering/web/cache/src/main/java/org/wildfly/clustering/web/cache/session/ConcurrentSessionManager.java
  clustering/web/hotrod/src/main/java/org/wildfly/clustering/web/hotrod/session/HotRodSessionManager.java
  clustering/web/infinispan/src/main/java/org/wildfly/clustering/web/infinispan/session/InfinispanSessionManager.java
  clustering/web/spi/src/main/java/org/wildfly/clustering/web/session/SessionManager.java
  clustering/web/spi/src/main/java/org/wildfly/clustering/web/session/oob/OOBSession.java
  clustering/web/spi/src/main/java/org/wildfly/clustering/web/session/oob/OOBSessionAttributes.java
  clustering/web/spi/src/main/java/org/wildfly/clustering/web/session/oob/OOBSessionMetaData.java
  clustering/web/spi/src/test/java/org/wildfly/clustering/web/session/oob/OOBSessionAttributesTestCase.java
  clustering/web/spi/src/test/java/org/wildfly/clustering/web/session/oob/OOBSessionMetaDataTestCase.java
  clustering/web/spi/src/test/java/org/wildfly/clustering/web/session/oob/OOBSessionTestCase.java
  clustering/web/undertow/src/main/java/org/wildfly/clustering/web/undertow/session/DistributableSession.java
  clustering/web/undertow/src/main/java/org/wildfly/clustering/web/undertow/session/DistributableSessionManager.java
  clustering/web/undertow/src/main/java/org/wildfly/clustering/web/undertow/session/LocalSessionContextFactory.java
  clustering/web/undertow/src/main/java/org/wildfly/clustering/web/undertow/session/SessionManagerFactoryConfigurationAdapter.java
  clustering/web/undertow/src/main/java/org/wildfly/clustering/web/undertow/session/SimpleSessionConfig.java
  clustering/web/undertow/src/test/java/org/wildfly/clustering/web/undertow/session/DistributableSessionManagerTestCase.java
  clustering/web/undertow/src/test/java/org/wildfly/clustering/web/undertow/session/DistributableSessionTestCase.java
  ee-feature-pack/common/src/main/resources/modules/system/layers/base/org/wildfly/clustering/web/undertow/main/module.xml
  testsuite/integration/clustering/src/test/java/org/jboss/as/test/clustering/single/web/NonHaWebSessionPersistenceTestCase.java
  testsuite/integration/clustering/src/test/java/org/jboss/as/test/clustering/single/web/SimpleServlet.java
Labels: 23.x, deps-ok

#14042 [WFLY-14484] Upgrade JBoss Modules XML schema version to 1.9 for lega…
  dist-legacy/src/distribution/resources/modules/system/layers/base/org/jboss/as/product/main/module.xml
  dist-legacy/src/verifier/verifications.xml
  ee-feature-pack/pruned/src/main/resources/modules/system/layers/base/org/hibernate/4.1/module.xml
  ee-feature-pack/pruned/src/main/resources/modules/system/layers/base/org/hibernate/4.3/module.xml
  ee-feature-pack/pruned/src/main/resources/modules/system/layers/base/org/hibernate/5.0/module.xml
  ee-feature-pack/pruned/src/main/resources/modules/system/layers/base/org/hibernate/jipijapa-hibernate4-3/main/module.xml
  ee-feature-pack/pruned/src/main/resources/modules/system/layers/base/org/jboss/as/jpa/hibernate/4/module.xml
  jsf/subsystem/src/test/resources/modules/com/sun/jsf-impl/myfaces/module.xml
  jsf/subsystem/src/test/resources/modules/javax/faces/api/myfaces/module.xml
  jsf/subsystem/src/test/resources/modules/org/jboss/as/jsf-injection/1.2/module.xml
  jsf/subsystem/src/test/resources/modules/org/jboss/as/jsf-injection/myfaces/module.xml
  jsf/subsystem/src/test/resources/modules2/com/sun/jsf-impl/myfaces2/module.xml
  jsf/subsystem/src/test/resources/modules2/javax/faces/api/myfaces2/module.xml
  jsf/subsystem/src/test/resources/modules2/org/jboss/as/jsf-injection/bogus2/module.xml
  jsf/subsystem/src/test/resources/modules2/org/jboss/as/jsf-injection/myfaces2/module.xml
  servlet-dist-legacy/src/distribution/resources/modules/system/layers/base/org/jboss/as/product/wildfly-web/module.xml
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/deployment/classloading/ear/EarJbossStructureCascadeExclusionsTestCase.java
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/management/cli/DeploymentArchiveTestCase.java
  testsuite/integration/manualmode/src/test/resources/layered/product-module.xml
  testsuite/integration/manualmode/src/test/resources/layered/test-module.xml
Labels: 23.x, deps-ok

#14097 [WFLY-14540] Upgrade MyFaces to 2.3.8 [CVE-2021-26296]
  pom.xml
Labels: 23.x, deps-ok

#14105 WFLY-14554 Deprecate Infinispan hotrod transaction resource
  clustering/infinispan/extension/src/main/java/org/jboss/as/clustering/infinispan/subsystem/InfinispanSchema.java
  clustering/infinispan/extension/src/main/java/org/jboss/as/clustering/infinispan/subsystem/remote/RemoteTransactionResourceDefinition.java
  clustering/infinispan/extension/src/main/java/org/jboss/as/clustering/infinispan/subsystem/remote/RemoteTransactionServiceConfigurator.java
  clustering/infinispan/extension/src/main/resources/org/jboss/as/clustering/infinispan/subsystem/LocalDescriptions.properties
Labels: deps-ok

#14103 [WFLY-14550] Upgrading WildFly Http Client to 1.1.6.Final
  pom.xml
Labels: 24.x, deps-ok

#14122 WFLY-14543 Upgrade Infinispan to 11.0.10.Final
  pom.xml
Labels: deps-ok

#14113 [WFLY-14564] Close EJBClientContext when related service is closed
  ejb3/src/main/java/org/jboss/as/ejb3/remote/EJBClientContextService.java
Labels: deps-ok, ready-for-merge

#14104 WFLY-14551 EJB subsystem should not allow expressions for cache-container/bean-cache in passivation-store resource and client-mappings-clustering-name in remote resource
  ejb3/src/main/java/org/jboss/as/ejb3/subsystem/ClusterPassivationStoreResourceDefinition.java
  ejb3/src/main/java/org/jboss/as/ejb3/subsystem/EJB3RemoteResourceDefinition.java
  ejb3/src/main/java/org/jboss/as/ejb3/subsystem/PassivationStoreResourceDefinition.java
  ejb3/src/test/java/org/jboss/as/ejb3/subsystem/Ejb3SubsystemUnitTestCase.java
  ejb3/src/test/resources/org/jboss/as/ejb3/subsystem/with-expression-subsystem.xml
Labels: 24.x, deps-ok, ready-for-merge

#14107 WFLY-14554 Deprecate Infinispan hotrod transaction resource
  clustering/infinispan/extension/src/main/java/org/jboss/as/clustering/infinispan/subsystem/InfinispanSchema.java
  clustering/infinispan/extension/src/main/java/org/jboss/as/clustering/infinispan/subsystem/remote/RemoteTransactionResourceDefinition.java
  clustering/infinispan/extension/src/main/java/org/jboss/as/clustering/infinispan/subsystem/remote/RemoteTransactionServiceConfigurator.java
  clustering/infinispan/extension/src/main/resources/org/jboss/as/clustering/infinispan/subsystem/LocalDescriptions.properties
Labels: 23.x

#14119 WFLY-14570 HttpSession implementation generated during distributed session events should implement hashCode/equals
  clustering/web/undertow/src/main/java/org/wildfly/clustering/web/undertow/session/UndertowSpecificationProvider.java
Labels: deps-ok

#14100 WFLY-14544 Review for expansion expression testing in singleton subsystem
  clustering/singleton/extension/src/main/java/org/wildfly/extension/clustering/singleton/ElectionPolicyResourceDefinition.java
  clustering/singleton/extension/src/test/resources/org/wildfly/extension/clustering/singleton/subsystem-reject.xml
  clustering/singleton/extension/src/test/resources/org/wildfly/extension/clustering/singleton/subsystem-singleton-1_0.xml
  clustering/singleton/extension/src/test/resources/org/wildfly/extension/clustering/singleton/subsystem-transform.xml
Labels: deps-ok

#14109 [WFLY-14492] Remove duplicate version properties; ensure the right va…
  pom.xml
Labels: 23.x

#14108 [WFLY-14492] Remove duplicate version properties; ensure the right va…
  pom.xml
Labels: deps-ok

#14120 [WFLY-14572] Make servlet-galleon-pack maven resource plugin to overw…
  servlet-feature-pack/galleon-feature-pack/pom.xml
Labels: deps-ok

#14116 [WFLY-14568] Change 'Eclipse MicroProfile' to 'MicroProfile' in docs
  docs/src/main/asciidoc/Bootable_Guide.adoc
  docs/src/main/asciidoc/Installation_Guide.adoc
  docs/src/main/asciidoc/_admin-guide/subsystem-configuration/Health.adoc
  docs/src/main/asciidoc/_admin-guide/subsystem-configuration/Metrics.adoc
  docs/src/main/asciidoc/_admin-guide/subsystem-configuration/MicroProfile_Config_SmallRye.adoc
  docs/src/main/asciidoc/_admin-guide/subsystem-configuration/MicroProfile_Fault_Tolerance_SmallRye.adoc
  docs/src/main/asciidoc/_admin-guide/subsystem-configuration/MicroProfile_Health.adoc
  docs/src/main/asciidoc/_admin-guide/subsystem-configuration/MicroProfile_JWT.adoc
  docs/src/main/asciidoc/_admin-guide/subsystem-configuration/MicroProfile_Metrics.adoc
  docs/src/main/asciidoc/_admin-guide/subsystem-configuration/MicroProfile_OpenAPI.adoc
  docs/src/main/asciidoc/_admin-guide/subsystem-configuration/MicroProfile_OpenTracing_SmallRye.adoc
  docs/src/main/asciidoc/_admin-guide/subsystem-configuration/MicroProfile_Reactive_Messsaging_SmallRye.adoc
  docs/src/main/asciidoc/_admin-guide/subsystem-configuration/MicroProfile_Reactive_Streams_Operators_SmallRye.adoc
  docs/src/main/asciidoc/_galleon/Galleon_provisioning.adoc
Labels: deps-ok

#14117 [23.x][WFLY-14568] Change 'Eclipse MicroProfile' to 'MicroProfile' in docs
  docs/src/main/asciidoc/Bootable_Guide.adoc
  docs/src/main/asciidoc/Installation_Guide.adoc
  docs/src/main/asciidoc/_admin-guide/subsystem-configuration/Health.adoc
  docs/src/main/asciidoc/_admin-guide/subsystem-configuration/Metrics.adoc
  docs/src/main/asciidoc/_admin-guide/subsystem-configuration/MicroProfile_Config_SmallRye.adoc
  docs/src/main/asciidoc/_admin-guide/subsystem-configuration/MicroProfile_Fault_Tolerance_SmallRye.adoc
  docs/src/main/asciidoc/_admin-guide/subsystem-configuration/MicroProfile_Health.adoc
  docs/src/main/asciidoc/_admin-guide/subsystem-configuration/MicroProfile_JWT.adoc
  docs/src/main/asciidoc/_admin-guide/subsystem-configuration/MicroProfile_Metrics.adoc
  docs/src/main/asciidoc/_admin-guide/subsystem-configuration/MicroProfile_OpenAPI.adoc
  docs/src/main/asciidoc/_admin-guide/subsystem-configuration/MicroProfile_OpenTracing_SmallRye.adoc
  docs/src/main/asciidoc/_admin-guide/subsystem-configuration/MicroProfile_Reactive_Messsaging_SmallRye.adoc
  docs/src/main/asciidoc/_admin-guide/subsystem-configuration/MicroProfile_Reactive_Streams_Operators_SmallRye.adoc
  docs/src/main/asciidoc/_galleon/Galleon_provisioning.adoc
Labels: 23.x

#14121 [WFLY-14574] Maintain separation between the artifact id and the vers…
  testsuite/scripts/pom.xml
Labels: deps-ok, ready-for-merge

#14110 [WFLY-14560]:Upgrade velocity to 2.3
  pom.xml
Labels: deps-ok

#14102 [WFLY-14549]: Upgrade artemis-wildfly-integration to 1.0.3
  ee-9/feature-pack/pom.xml
Labels: 24.x, deps-ok

#14128 [WFLY-14586] Upgrading xalan to 2.7.1.jbossorg-5
  pom.xml
Labels: deps-ok

#14133 Fix for WFLY-14597, Upgrade tests to use bootable JAR 4.0.0.Final
  pom.xml
Labels: deps-ok

#14132 WFLY-14575 Upgrade jgroups-kubernetes to 1.0.16.Final
  pom.xml
Labels: deps-ok

#14130 WFLY-14570 HttpSession implementation generated during distributed session events should implement hashCode/equals
  clustering/web/undertow/src/main/java/org/wildfly/clustering/web/undertow/session/UndertowSpecificationProvider.java
Labels: 23.x

#14123 WFLY-14576 Reduce intermediate ByteBuffer/InputStream allocations during ProtoStream unmarshalling
  clustering/marshalling/protostream/src/main/java/org/wildfly/clustering/marshalling/protostream/AnyField.java
  clustering/marshalling/protostream/src/main/java/org/wildfly/clustering/marshalling/protostream/AnyMarshaller.java
  clustering/marshalling/protostream/src/main/java/org/wildfly/clustering/marshalling/protostream/ClassField.java
  clustering/marshalling/protostream/src/main/java/org/wildfly/clustering/marshalling/protostream/ClassMarshaller.java
  clustering/marshalling/protostream/src/main/java/org/wildfly/clustering/marshalling/protostream/DefaultProtoStreamReader.java
  clustering/marshalling/protostream/src/main/java/org/wildfly/clustering/marshalling/protostream/ValueMarshaller.java
Labels: deps-ok

#14131 WFLY-14596 Upgrade Weld to 3.1.7.Final.
  pom.xml
Labels: deps-ok

#14137 [JBTM-3407] Narayana component upgrade 5.11.0.Final
  pom.xml
Labels: deps-ok

#14118 WFLY-14497 HttpSessionActivationListener.sessionWillPassivate method is not triggered on shutdown for local, passivating caches.
  clustering/web/infinispan/src/main/java/org/wildfly/clustering/web/infinispan/session/InfinispanSessionManager.java
Labels: deps-ok

#14114 WFLY-14565 Consolidate OOBSession, OOBSessionMetaData, and OOBSessionAttributes ...
  clustering/web/spi/src/main/java/org/wildfly/clustering/web/session/oob/OOBSession.java
  clustering/web/spi/src/main/java/org/wildfly/clustering/web/session/oob/OOBSessionAttributes.java
  clustering/web/spi/src/main/java/org/wildfly/clustering/web/session/oob/OOBSessionMetaData.java
  clustering/web/spi/src/test/java/org/wildfly/clustering/web/session/oob/OOBSessionAttributesTestCase.java
  clustering/web/spi/src/test/java/org/wildfly/clustering/web/session/oob/OOBSessionMetaDataTestCase.java
  clustering/web/spi/src/test/java/org/wildfly/clustering/web/session/oob/OOBSessionTestCase.java
Labels: deps-ok

#13955 [WFLY-14403] introduce a test case to automatically test configurati…
  testsuite/integration/manualmode/pom.xml
  testsuite/integration/manualmode/src/test/config/arq/arquillian.xml
  testsuite/integration/manualmode/src/test/java/org/jboss/as/test/manualmode/model/AbstractExpressionSupportTestCase.java
  testsuite/integration/manualmode/src/test/java/org/jboss/as/test/manualmode/model/ExpressionSupportSmokeTestCase.java
  testsuite/integration/src/test/scripts/manualmode-build.xml
  testsuite/integration/src/test/xslt/changeLdapStore.xsl
Labels: deps-ok

#14126 Fix for WFLY-14582, Upgrade galleon-plugins to 5.1.1
  pom.xml
Labels: deps-ok

#14127 [23.x]Fix for WFLY-14582, Upgrade galleon-plugins to 5.1.1
  pom.xml
Labels: 23.x

#12889 [WFLY-12945] Refactoring undertow subsystem to use new MSC value API
  mod_cluster/undertow/src/test/java/org/wildfly/mod_cluster/undertow/TestHost.java
  mod_cluster/undertow/src/test/java/org/wildfly/mod_cluster/undertow/TestServer.java
  mod_cluster/undertow/src/test/java/org/wildfly/mod_cluster/undertow/TestUndertowService.java
  mod_cluster/undertow/src/test/java/org/wildfly/mod_cluster/undertow/UndertowConnectorTestCase.java
  mod_cluster/undertow/src/test/java/org/wildfly/mod_cluster/undertow/UndertowEngineTestCase.java
  mod_cluster/undertow/src/test/java/org/wildfly/mod_cluster/undertow/UndertowHostTestCase.java
  mod_cluster/undertow/src/test/java/org/wildfly/mod_cluster/undertow/UndertowServerTestCase.java
  undertow/src/main/java/org/wildfly/extension/undertow/AbstractPersistentSessionManager.java
  undertow/src/main/java/org/wildfly/extension/undertow/AccessLogAdd.java
  undertow/src/main/java/org/wildfly/extension/undertow/AccessLogService.java
  undertow/src/main/java/org/wildfly/extension/undertow/AjpListenerAdd.java
  undertow/src/main/java/org/wildfly/extension/undertow/AjpListenerService.java
  undertow/src/main/java/org/wildfly/extension/undertow/BufferCacheAdd.java
  undertow/src/main/java/org/wildfly/extension/undertow/ConsoleRedirectService.java
  undertow/src/main/java/org/wildfly/extension/undertow/DeploymentServletDefinition.java
  undertow/src/main/java/org/wildfly/extension/undertow/DiskBasedModularPersistentSessionManager.java
  undertow/src/main/java/org/wildfly/extension/undertow/Host.java
  undertow/src/main/java/org/wildfly/extension/undertow/HostAdd.java
  undertow/src/main/java/org/wildfly/extension/undertow/HostSingleSignOnServiceHandler.java
  undertow/src/main/java/org/wildfly/extension/undertow/HttpInvokerDefinition.java
  undertow/src/main/java/org/wildfly/extension/undertow/HttpInvokerHostService.java
  undertow/src/main/java/org/wildfly/extension/undertow/HttpListenerAdd.java
  undertow/src/main/java/org/wildfly/extension/undertow/HttpListenerService.java
  undertow/src/main/java/org/wildfly/extension/undertow/HttpsListenerAdd.java
  undertow/src/main/java/org/wildfly/extension/undertow/HttpsListenerService.java
  undertow/src/main/java/org/wildfly/extension/undertow/InMemoryModularPersistentSessionManager.java
  undertow/src/main/java/org/wildfly/extension/undertow/ListenerAdd.java
  undertow/src/main/java/org/wildfly/extension/undertow/ListenerService.java
  undertow/src/main/java/org/wildfly/extension/undertow/LocationAdd.java
  undertow/src/main/java/org/wildfly/extension/undertow/LocationService.java
  undertow/src/main/java/org/wildfly/extension/undertow/PersistentSessionsDefinition.java
  undertow/src/main/java/org/wildfly/extension/undertow/Server.java
  undertow/src/main/java/org/wildfly/extension/undertow/ServerAdd.java
  undertow/src/main/java/org/wildfly/extension/undertow/ServletContainerAdd.java
  undertow/src/main/java/org/wildfly/extension/undertow/ServletContainerService.java
  undertow/src/main/java/org/wildfly/extension/undertow/SingleSignOnService.java
  undertow/src/main/java/org/wildfly/extension/undertow/UndertowService.java
  undertow/src/main/java/org/wildfly/extension/undertow/UndertowSubsystemAdd.java
  undertow/src/main/java/org/wildfly/extension/undertow/WebHostService.java
  undertow/src/main/java/org/wildfly/extension/undertow/WebServerService.java
  undertow/src/main/java/org/wildfly/extension/undertow/deployment/UndertowDeploymentInfoService.java
  undertow/src/main/java/org/wildfly/extension/undertow/deployment/UndertowDeploymentProcessor.java
  undertow/src/main/java/org/wildfly/extension/undertow/deployment/UndertowDeploymentService.java
  undertow/src/main/java/org/wildfly/extension/undertow/filters/FilterAdd.java
  undertow/src/main/java/org/wildfly/extension/undertow/filters/FilterRef.java
  undertow/src/main/java/org/wildfly/extension/undertow/filters/FilterRefDefinition.java
  undertow/src/main/java/org/wildfly/extension/undertow/filters/FilterService.java
  undertow/src/main/java/org/wildfly/extension/undertow/filters/ModClusterService.java
  undertow/src/main/java/org/wildfly/extension/undertow/handlers/HandlerAdd.java
  undertow/src/main/java/org/wildfly/extension/undertow/handlers/HandlerService.java
  undertow/src/main/java/org/wildfly/extension/undertow/handlers/ReverseProxyHandlerHost.java
  undertow/src/test/java/org/wildfly/extension/undertow/AbstractUndertowSubsystemTestCase.java
Labels: 24.x, deps-ok

#14136 [WFLY-11933] Return properly configured ModelNode when RBAC is enabled
  metrics/src/main/java/org/wildfly/extension/metrics/WildFlyMetric.java
Labels: deps-ok

#14125 WFLY-14547 Review for expansion expression testing in jgroups subsystem + WFLY-14581 JGroups subsystem does not persist client-socket-binding of the transport
  clustering/jgroups/extension/src/main/java/org/jboss/as/clustering/jgroups/logging/JGroupsLogger.java
  clustering/jgroups/extension/src/main/java/org/jboss/as/clustering/jgroups/subsystem/JGroupsSubsystemXMLWriter.java
  clustering/jgroups/extension/src/main/java/org/jboss/as/clustering/jgroups/subsystem/RemoteSiteResourceDefinition.java
  clustering/jgroups/extension/src/main/java/org/jboss/as/clustering/jgroups/subsystem/SocketDiscoveryProtocolResourceDefinition.java
  clustering/jgroups/extension/src/test/resources/org/jboss/as/clustering/jgroups/subsystem/subsystem-jgroups-8_0.xml
  clustering/jgroups/extension/src/test/resources/org/jboss/as/clustering/jgroups/subsystem/subsystem-jgroups-transform-7_0_0.xml
Labels: deps-ok

#14135 [WFLY-14600] Include MP OpenTracing in the docs/examples/enable-micro…
  microprofile/galleon-common/src/main/resources/packages/docs.examples/content/docs/examples/enable-microprofile.cli
Labels: deps-ok

#14144 [WFLY-14613] Add missing java.security.jgss dependency to Kafka client module
  microprofile/galleon-common/src/main/resources/modules/system/layers/base/org/apache/kafka/client/main/module.xml
Labels: deps-ok

#14141 WFLY-14611 Upgrade Weld to 4.0.1.Final in the preview.
  ee-9/feature-pack/pom.xml
Labels: deps-ok

#14111 [WFLY-14560]:Upgrade velocity to 2.3
  pom.xml
Labels: 23.x

#14145 [WFLY-14162]:Upgrade to CXF 3.3.10 & JBossWS CXF 5.4.3.Final
  ee-feature-pack/common/pom.xml
  ee-feature-pack/common/src/main/resources/modules/system/layers/base/org/jboss/as/webservices/main/module.xml
  pom.xml
Labels: deps-changed

#14147 [WFLY-14578] Upgrade yasson from 1.0.5 to 1.0.9
  pom.xml
Labels: deps-ok, ready-for-merge

#14138 [WFLY-14606] Remove unneeded module dependencies on non-JRE modules
  ee-feature-pack/common/src/main/resources/modules/system/layers/base/org/javassist/main/module.xml
  ee-feature-pack/common/src/main/resources/modules/system/layers/base/org/jboss/jts/main/module.xml
Labels: deps-ok

#14139 [23.x][WFLY-14606] Remove unneeded module dependencies on non-JRE modules
  ee-feature-pack/common/src/main/resources/modules/system/layers/base/org/javassist/main/module.xml
  ee-feature-pack/common/src/main/resources/modules/system/layers/base/org/jboss/jts/main/module.xml
Labels: 23.x

#14152 [WFLY-14162]:Upgrade to CXF 3.3.10 & JBossWS CXF 5.4.3.Final
  ee-feature-pack/common/pom.xml
  ee-feature-pack/common/src/main/resources/modules/system/layers/base/org/jboss/as/webservices/main/module.xml
  pom.xml
Labels: 23.x

#14148 [WFLY-14620] Use a unique name for the test directory for KeystoreRealmTestCase so other tests do not affect this one
  testsuite/integration/elytron/src/test/java/org/wildfly/test/integration/elytron/certs/realm/KeystoreRealmTestCase.java
Labels: deps-ok

#14154 [WFLY-14630] Upgrade WildFly Core 16.0.0.Beta1
  ee-feature-pack/common/src/main/resources/content/appclient/configuration/appclient.xml
  ee-feature-pack/common/src/main/resources/content/docs/examples/configs/standalone-minimalistic.xml
  ee-feature-pack/legacy-feature-pack/src/main/resources/configuration/domain/template.xml
  ee-feature-pack/legacy-feature-pack/src/main/resources/configuration/host/host-master.xml
  ee-feature-pack/legacy-feature-pack/src/main/resources/configuration/host/host-slave.xml
  ee-feature-pack/legacy-feature-pack/src/main/resources/configuration/host/host.xml
  ee-feature-pack/legacy-feature-pack/src/main/resources/configuration/standalone/template.xml
  pom.xml
  servlet-feature-pack/legacy-feature-pack/src/main/resources/configuration/domain/template.xml
  servlet-feature-pack/legacy-feature-pack/src/main/resources/configuration/host/host-master.xml
  servlet-feature-pack/legacy-feature-pack/src/main/resources/configuration/host/host-slave.xml
  servlet-feature-pack/legacy-feature-pack/src/main/resources/configuration/host/host.xml
  servlet-feature-pack/legacy-feature-pack/src/main/resources/configuration/standalone/template.xml
  testsuite/domain/src/test/resources/domain-configs/domain-minimal.xml
  testsuite/domain/src/test/resources/domain-configs/domain-rbac.xml
  testsuite/domain/src/test/resources/domain-configs/domain-respawn.xml
  testsuite/domain/src/test/resources/domain-configs/domain-standard-ee.xml
  testsuite/domain/src/test/resources/domain-configs/domain-standard.xml
  testsuite/domain/src/test/resources/host-configs/host-failover1.xml
  testsuite/domain/src/test/resources/host-configs/host-failover2.xml
  testsuite/domain/src/test/resources/host-configs/host-failover3.xml
  testsuite/domain/src/test/resources/host-configs/host-master-elytron.xml
  testsuite/domain/src/test/resources/host-configs/host-master-no-http.xml
  testsuite/domain/src/test/resources/host-configs/host-master-no-local.xml
  testsuite/domain/src/test/resources/host-configs/host-master-rbac-properties.xml
  testsuite/domain/src/test/resources/host-configs/host-master-rbac.xml
  testsuite/domain/src/test/resources/host-configs/host-master.xml
  testsuite/domain/src/test/resources/host-configs/host-secrets.xml
  testsuite/domain/src/test/resources/host-configs/host-slave-discovery-options.xml
  testsuite/domain/src/test/resources/host-configs/host-slave-elytron.xml
  testsuite/domain/src/test/resources/host-configs/host-slave-rbac-properties.xml
  testsuite/domain/src/test/resources/host-configs/host-slave-rbac.xml
  testsuite/domain/src/test/resources/host-configs/host-slave.xml
  testsuite/domain/src/test/resources/host-configs/respawn-master.xml
  testsuite/mixed-domain/src/test/resources/legacy-templates/test-template.xml
  testsuite/mixed-domain/src/test/resources/master-config/domain-minimal.xml
  testsuite/mixed-domain/src/test/resources/master-config/host-master-elytron.xml
  testsuite/mixed-domain/src/test/resources/master-config/host.xml
Labels: deps-changed

#14143 [WFLY-14608] Ensure the CredentialReferenceWriteAttributeHandler gets registered for the credential-reference attributes for datasources
  connector/src/main/java/org/jboss/as/connector/subsystems/datasources/DataSourceDefinition.java
Labels: deps-ok

#14149 Fix for WFLY-14622, Upgrade galleon to 4.2.8.Final
  pom.xml
Labels: deps-ok

#14150 [23.x] Fix for WFLY-14622, Upgrade galleon to 4.2.8.Final
  pom.xml
Labels: 23.x

#13962 [WFLY-14423] Legacy JACC provider changes require restart
  security/subsystem/src/main/java/org/jboss/as/security/SecuritySubsystemRootResourceDefinition.java
  security/subsystem/src/main/java/org/jboss/as/security/logging/SecurityLogger.java
  testsuite/integration/manualmode/src/test/java/org/jboss/as/test/manualmode/security/JaccInitializationTestCase.java
Labels: 24.x, affects_i18n, deps-ok

#13503 [WFLY-13212] Boot messages related to activation of MP subsystems are…
  microprofile/config-smallrye/src/main/java/org/wildfly/extension/microprofile/config/smallrye/_private/MicroProfileConfigLogger.java
  microprofile/health-smallrye/src/main/java/org/wildfly/extension/microprofile/health/_private/MicroProfileHealthLogger.java
  microprofile/jwt-smallrye/src/main/java/org/wildfly/extension/microprofile/jwt/smallrye/_private/MicroProfileJWTLogger.java
  microprofile/metrics-smallrye/src/main/java/org/wildfly/extension/microprofile/metrics/_private/MicroProfileMetricsLogger.java
  microprofile/openapi-smallrye/src/main/java/org/wildfly/extension/microprofile/openapi/logging/MicroProfileOpenAPILogger.java
  microprofile/opentracing-smallrye/src/main/java/org/wildfly/microprofile/opentracing/smallrye/TracingLogger.java
  microprofile/reactive-messaging-smallrye/extension/src/main/java/org/wildfly/extension/microprofile/reactive/messaging/_private/MicroProfileReactiveMessagingLogger.java
  microprofile/reactive-streams-operators-smallrye/extension/src/main/java/org/wildfly/extension/microprofile/reactive/streams/operators/_private/MicroProfileReactiveStreamsOperatorsLogger.java
Labels: deps-ok

#14158 [23.x][WFLY-14608] Ensure the CredentialReferenceWriteAttributeHandler gets registered for the credential-reference attributes for datasources
  connector/src/main/java/org/jboss/as/connector/subsystems/datasources/DataSourceDefinition.java
Labels: 23.x

#14159 [WFLY-14638] Use a separate version property for vertx-kafka-client
  pom.xml
Labels: deps-ok

#14155 [WFLY-14635]: Upgrade artemis-wildfly-integration to 1.0.4 in WildFl…
  ee-9/feature-pack/pom.xml
Labels: deps-ok

#14142 [WFLY-14612] Upgrade netty from 4.1.59.Final to 4.1.60
  pom.xml
Labels: deps-ok

#14140 [WFLY-14599] Update ironjacamar to 4.0.30.Final
  pom.xml
Labels: deps-ok

#14161 [23.x][WFLY-14612] Upgrade netty from 4.1.59.Final to 4.1.60
  pom.xml
Labels: 23.x

#14160 [WFLY-14639] Upgrade Jakarta Mail to 1.6.6
  pom.xml
Labels: deps-ok

#14157 WFLY-14633 Replace IdentifierSerializer with Marshaller<String, ByteBuffer>
  clustering/marshalling/protostream/src/main/java/org/wildfly/clustering/marshalling/protostream/DefaultProtoStreamReader.java
  clustering/marshalling/protostream/src/main/java/org/wildfly/clustering/marshalling/protostream/DefaultProtoStreamWriter.java
  clustering/marshalling/protostream/src/main/java/org/wildfly/clustering/marshalling/protostream/ProtoStreamDataInput.java
  clustering/marshalling/protostream/src/main/java/org/wildfly/clustering/marshalling/protostream/ProtoStreamDataOutput.java
  clustering/marshalling/protostream/src/main/java/org/wildfly/clustering/marshalling/protostream/ProtoStreamReader.java
  clustering/marshalling/protostream/src/main/java/org/wildfly/clustering/marshalling/protostream/ProtoStreamWriter.java
  clustering/marshalling/protostream/src/main/java/org/wildfly/clustering/marshalling/protostream/SizeComputingProtoStreamWriter.java
  clustering/marshalling/protostream/src/test/java/org/wildfly/clustering/marshalling/protostream/ProtoStreamDataStreamTestCase.java
  clustering/web/cache/src/main/java/org/wildfly/clustering/web/cache/SessionIdentifierMarshaller.java
  clustering/web/hotrod/src/test/java/org/wildfly/clustering/web/hotrod/TestIdentifierSerializerProvider.java
  clustering/web/infinispan/src/test/java/org/wildfly/clustering/web/infinispan/TestIdentifierSerializerProvider.java
  clustering/web/spi/src/main/java/org/wildfly/clustering/web/IdentifierMarshaller.java
  clustering/web/spi/src/main/java/org/wildfly/clustering/web/IdentifierMarshallerProvider.java
  clustering/web/spi/src/main/java/org/wildfly/clustering/web/IdentifierSerializer.java
  clustering/web/spi/src/test/java/org/wildfly/clustering/web/session/IdentifierSerializerTestCase.java
  clustering/web/undertow/src/main/java/org/wildfly/clustering/web/undertow/UndertowIdentifierSerializerProvider.java
  clustering/web/undertow/src/main/java/org/wildfly/clustering/web/undertow/session/DistributableSessionManager.java
Labels: deps-ok

#13743 [WFLY-14130] proxy-list attribute ignored in modcluster subsystem
  mod_cluster/extension/src/main/java/org/wildfly/extension/mod_cluster/ProxyConfigurationServiceConfigurator.java
  testsuite/integration/clustering/pom.xml
  testsuite/integration/clustering/src/test/java/org/jboss/as/test/clustering/cluster/modcluster/ModClusterProxyListOptionTestCase.java
Labels: deps-ok

#14167 [WFLY-14642] Upgrade WildFly Core 15.0.1.Final
  pom.xml
Labels: 23.x, Blocker

#14168 Fix for WFLY-14660, Upgrade galleon-plugins to 5.1.2
  pom.xml
Labels: deps-ok

#14170 [23.x][WFLY-14659] Add a dep on org.jboss.modules to org.jboss.ws.cxf.jboss…
  ee-feature-pack/common/src/main/resources/modules/system/layers/base/org/jboss/ws/cxf/jbossws-cxf-client/main/module.xml
Labels: 23.x

#14172 [WFLY-14662]: Calendar testing for marshalling in clustering is wrong.
  clustering/marshalling/api/src/test/java/org/wildfly/clustering/marshalling/AbstractUtilTestCase.java
Labels: 23.x

#14171 [WFLY-14662]: Calendar testing for marshalling in clustering is wrong.
  clustering/marshalling/api/src/test/java/org/wildfly/clustering/marshalling/AbstractUtilTestCase.java
Labels: deps-ok
