Repository wildfly/wildfly, pull requests merged in 2021-12, with the labels that each got.

#14921 [WFLY-14919] Make credential store expression resolution usable for d…
  ee/src/main/java/org/jboss/as/ee/metadata/property/FunctionalResolverProcessor.java
  ee/src/main/java/org/jboss/as/ee/subsystem/EeSubsystemAdd.java
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/ejb/mdb/vaultedproperties/MDB.java
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/ejb/mdb/vaultedproperties/MDBWithVaultedPropertiesTestCase.java
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/messaging/jms/context/VaultedInjectedJMSContextTestCase.java
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/messaging/jms/context/auxiliary/VaultedMessageProducer.java
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/messaging/jms/definitions/JMSResourceDefinitionsTestCase.java
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/messaging/jms/definitions/MessagingBean.java
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/messaging/jms/definitions/ejb-jar.xml
  testsuite/shared/src/main/java/org/wildfly/test/security/common/SecureExpressionUtil.java
Labels: Critical

#14925 WFLY-15704 Move ScheduleExpressionTypeUtil#getType method to Schedule…
  ejb3/src/main/java/org/jboss/as/ejb3/timerservice/schedule/ScheduleExpressionTypeUtil.java
  ejb3/src/main/java/org/jboss/as/ejb3/timerservice/schedule/attribute/IntegerBasedExpression.java
  ejb3/src/main/java/org/jboss/as/ejb3/timerservice/schedule/value/ScheduleExpressionType.java
Labels: ready-for-merge, deps-ok

#14930 WFLY-15713 Remove redundant null checks in TimerHandleImpl constructor.
  ejb3/src/main/java/org/jboss/as/ejb3/logging/EjbLogger.java
  ejb3/src/main/java/org/jboss/as/ejb3/timerservice/TimerHandleImpl.java
Labels: ready-for-merge, deps-ok

#14933 [WFLY-15449] Move WildFly Preview to native jakarta Taglibs
  ee-9/feature-pack/pom.xml
  ee-9/feature-pack/src/main/resources/license/preview-feature-pack-licenses.xml
  ee-9/feature-pack/src/main/resources/modules/system/layers/base/jakarta/servlet/jstl/api/main/module.xml
  ee-9/pom.xml
  ee-feature-pack/common/pom.xml
  ee-feature-pack/common/src/main/resources/license/ee-feature-pack-common-licenses.xml
Labels: ready-for-merge, deps-changed, EE9

#14983 [WFLY-15762] Upgrade Mojarra to 2.3.17.SP01
  pom.xml
Labels: ready-for-merge, deps-ok

#14987 [WFLY-15777] Remove the Apache commons-compress transitive dependency.
  pom.xml
Labels: ready-for-merge, deps-ok

#14988 [WFLY-15779] Upgrade WildFly HTTP Client to 1.1.10.Final
  pom.xml
Labels: ready-for-merge, deps-ok

#14981 [WFLY-15771] Upgrade Yasson
  ee-9/pom.xml
  pom.xml
Labels: ready-for-merge, deps-ok, EE9

#14538 [WFLY-15095] Test cases to verify and validate the uses of jboss.serv…
  docs/src/main/asciidoc/_admin-guide/management-tasks/JVM_settings.adoc
  testsuite/domain/src/test/java/org/jboss/as/test/integration/domain/JVMServerPropertiesTestCase.java
  testsuite/domain/src/test/resources/domain-configs/domain-jvm-properties.xml
  testsuite/domain/src/test/resources/host-configs/host-master-jvm-properties.xml
  testsuite/shared/src/main/java/org/jboss/as/test/integration/management/util/PropertiesServlet.java
Labels: ready-for-merge, Feature, deps-ok

#14942 [WFLY-15733] / [WFLY-15356] Remove security-plugins dependency from messaging.
  ee-9/feature-pack/src/main/resources/modules/system/layers/base/org/apache/activemq/artemis/main/module.xml
  ee-feature-pack/common/src/main/resources/modules/system/layers/base/org/apache/activemq/artemis/main/module.xml
  ee-feature-pack/common/src/main/resources/modules/system/layers/base/org/wildfly/extension/messaging-activemq/main/module.xml
  messaging-activemq/injection/src/main/java/org/wildfly/extension/messaging/activemq/logging/MessagingLogger.java
  messaging-activemq/subsystem/pom.xml
  messaging-activemq/subsystem/src/main/java/org/wildfly/extension/messaging/activemq/ActiveMQServerService.java
  messaging-activemq/subsystem/src/main/java/org/wildfly/extension/messaging/activemq/ServerAdd.java
  messaging-activemq/subsystem/src/main/java/org/wildfly/extension/messaging/activemq/WildFlySecurityManager.java
Labels: ready-for-merge, deps-ok, EE9

#14989 [WFLY-15026]:Move WildFly Preview to a native jakarta namespace varia…
  ee-9/feature-pack/pom.xml
  ee-9/feature-pack/src/main/resources/license/preview-feature-pack-licenses.xml
  ee-9/feature-pack/src/main/resources/modules/system/layers/base/jakarta/xml/soap/api/main/module.xml
  ee-9/pom.xml
Labels: ready-for-merge, deps-ok, EE9

#14993 [WFLY-15786][WFLY-15787] Move WF Preview to enhanced Undertow jakartized components
  ee-9/feature-pack/pom.xml
  ee-9/feature-pack/src/main/resources/license/preview-feature-pack-licenses.xml
  pom.xml
  servlet-feature-pack/common/src/main/resources/modules/system/layers/base/io/undertow/servlet/main/module.xml
  servlet-feature-pack/common/src/main/resources/modules/system/layers/base/io/undertow/websocket/main/module.xml
Labels: ready-for-merge, deps-ok, EE9

#14996 [WFLY-15450] Move WildFly Preview to native jakarta namespace variant of Jastow
  ee-9/feature-pack/pom.xml
  ee-9/feature-pack/src/main/resources/license/preview-feature-pack-licenses.xml
  pom.xml
  servlet-feature-pack/common/src/main/resources/modules/system/layers/base/io/undertow/jsp/main/module.xml
Labels: ready-for-merge, deps-ok

#14990 [WFLY-15024]:Move WildFly Preview to a native jakarta namespace varia…
  ee-9/feature-pack/pom.xml
  ee-9/feature-pack/src/main/resources/license/preview-feature-pack-licenses.xml
  ee-9/feature-pack/src/main/resources/modules/system/layers/base/jakarta/xml/ws/api/main/module.xml
  ee-9/pom.xml
Labels: deps-ok, EE9

#14982 WFLY-15769 Defend against ConcurrentModificationExceptions while marshalling collections/maps
  clustering/marshalling/protostream/src/main/java/org/wildfly/clustering/marshalling/protostream/util/AbstractCollectionMarshaller.java
  clustering/marshalling/protostream/src/main/java/org/wildfly/clustering/marshalling/protostream/util/AbstractMapMarshaller.java
  clustering/marshalling/protostream/src/main/java/org/wildfly/clustering/marshalling/protostream/util/LinkedHashMapMarshaller.java
  clustering/marshalling/spi/src/main/java/org/wildfly/clustering/marshalling/spi/util/CollectionExternalizer.java
  clustering/marshalling/spi/src/main/java/org/wildfly/clustering/marshalling/spi/util/MapExternalizer.java
Labels: ready-for-merge, deps-ok

#14951 [WFLY-15739] Set java.security.manager system property value to "allow" on JDK18+
  pom.xml
Labels: ready-for-merge, deps-ok

#15004 [WFLY-15802] Upgrade jboss-jsf-api_2.3_spec to 3.1.0.SP01
  pom.xml
Labels: Blocker, deps-ok, 26.x

#15003 [WFLY-15294] Remove the org.jboss.resteasy.resteasy-validator-provide…
  ee-feature-pack/common/src/main/resources/modules/system/layers/base/org/jboss/as/jaxrs/main/module.xml
  ee-feature-pack/common/src/main/resources/modules/system/layers/base/org/jboss/resteasy/resteasy-validator-provider-11/main/module.xml
Labels: deps-ok, 26.x

#15002 [WFLY-15774] Add a module dependency to Xerces for the RESTEasy JAXP …
  ee-feature-pack/common/src/main/resources/modules/system/layers/base/org/jboss/resteasy/resteasy-jaxb-provider/main/module.xml
  jaxrs/src/main/java/org/jboss/as/jaxrs/JaxrsAttribute.java
  jaxrs/src/main/java/org/jboss/as/jaxrs/JaxrsConstants.java
  jaxrs/src/main/java/org/jboss/as/jaxrs/JaxrsElement.java
  jaxrs/src/main/java/org/jboss/as/jaxrs/JaxrsServerConfig.java
  jaxrs/src/main/java/org/jboss/as/jaxrs/JaxrsSubsystemAdd.java
  jaxrs/src/main/resources/org/jboss/as/jaxrs/LocalDescriptions.properties
  pom.xml
Labels: Blocker, deps-ok, 26.x

#14953 [WFLY-15754] Upgrade to SmallRye Reactive Messaging 3.13
  microprofile/galleon-common/src/main/resources/modules/system/layers/base/org/wildfly/extension/microprofile/reactive-messaging-smallrye/main/module.xml
  microprofile/reactive-messaging-smallrye/extension/pom.xml
  microprofile/reactive-messaging-smallrye/extension/src/main/java/org/wildfly/extension/microprofile/reactive/messaging/deployment/ReactiveMessagingDependencyProcessor.java
  pom.xml
  testsuite/integration/microprofile/pom.xml
  weld/common/src/main/java/org/jboss/as/weld/WeldCapability.java
  weld/subsystem/src/main/java/org/jboss/as/weld/WeldCapabilityImpl.java
  weld/subsystem/src/main/java/org/jboss/as/weld/deployment/WeldAttachments.java
  weld/subsystem/src/main/java/org/jboss/as/weld/deployment/processors/ExternalBeanArchiveProcessor.java
Labels: Blocker, deps-changed, 26.x

#14986 [WFLY-15776] Remove management identity's security domain configuration from domain mode
  servlet-feature-pack/galleon-common/src/main/resources/feature_groups/host-management-interfaces.xml
Labels: deps-ok

#14790 [WFLY-15236]: Revisit messaging-activemq needing an Elytron domain.
  messaging-activemq/subsystem/src/main/java/org/wildfly/extension/messaging/activemq/ActiveMQServerService.java
  messaging-activemq/subsystem/src/main/java/org/wildfly/extension/messaging/activemq/ServerAdd.java
Labels: deps-ok

#14985 [WFLY-15775]:Add xerces module dependency to webservice deployment
  webservices/server-integration/src/main/java/org/jboss/as/webservices/deployers/WSDependenciesProcessor.java
Labels: Blocker, deps-ok, 26.x

#14999 [WFLY-15794] Remove JaccInitializationTestCase
  testsuite/integration/manualmode/src/test/java/org/jboss/as/test/manualmode/security/JaccInitializationTestCase.java
Labels: deps-ok

#15007 [WFLY-15809] Upgrade WildFly Preview Jakarta Mail from 2.0.0 to 2.0.1
  ee-9/pom.xml
Labels: deps-ok

#15008 [WFLY-15752] Fix incorrect generation of license files
  ee-9/feature-pack/pom.xml
  galleon-pack/galleon-feature-pack/pom.xml
Labels: deps-ok

#15001 [WFLY-15789] Remove no longer needed enable-elytron.cli script file
  ee-feature-pack/common/src/main/resources/content/docs/examples/enable-elytron.cli
Labels: deps-ok

#15010 [WFLY-15287] Upgrade RESTEasy to 6.0.0 for WildFly Preview.
  ee-9/feature-pack/pom.xml
  ee-9/feature-pack/src/main/resources/modules/system/layers/base/org/jboss/resteasy/microprofile/config/main/module.xml
  ee-9/feature-pack/src/main/resources/modules/system/layers/base/org/jboss/resteasy/resteasy-client-microprofile/main/module.xml
  ee-9/pom.xml
Labels: deps-ok, EE9, 26.x

#15014 [WFLY-15817] Upgrade WildFly Galleon Plugins to 5.2.7.Final
  pom.xml
Labels: Blocker, deps-ok, 26.x

#15015 Move WildFly Preview to MicroProfile Platform 5 with Jakarta 9.1 alignment
  ee-9/pom.xml
  pom.xml
  testsuite/integration/microprofile-tck/config/pom.xml
  testsuite/integration/microprofile-tck/config/src/test/jakarta/java/org/wildfly/extension/microprofile/config/test/WildFlyDeploymentExceptionTransformer.java
  testsuite/integration/microprofile-tck/config/src/test/javax/java/org/wildfly/extension/microprofile/config/test/WildFlyDeploymentExceptionTransformer.java
  testsuite/integration/microprofile-tck/fault-tolerance/pom.xml
  testsuite/integration/microprofile-tck/fault-tolerance/src/test/jakarta/java/org/wildfly/extension/microprofile/faulttolerance/tck/CleanupMetricRegistries.java
  testsuite/integration/microprofile-tck/fault-tolerance/src/test/javax/java/org/wildfly/extension/microprofile/faulttolerance/tck/CleanupMetricRegistries.java
  testsuite/integration/microprofile-tck/health/pom.xml
  testsuite/integration/microprofile-tck/jwt/pom.xml
  testsuite/integration/microprofile-tck/metrics/pom.xml
  testsuite/integration/microprofile-tck/openapi/src/test/java/org/wildfly/extension/microprofile/openapi/tck/DeploymentProcessor.java
  testsuite/integration/microprofile-tck/openapi/src/test/java/org/wildfly/extension/microprofile/openapi/tck/WildFlyArquillianExtension.java
  testsuite/integration/microprofile-tck/openapi/src/test/resources/META-INF/services/org.jboss.arquillian.core.spi.LoadableExtension
  testsuite/integration/microprofile-tck/opentracing/pom.xml
  testsuite/integration/microprofile-tck/opentracing/src/test/jakarta/java/io/smallrye/opentracing/ExceptionMapper.java
  testsuite/integration/microprofile-tck/opentracing/src/test/jakarta/java/io/smallrye/opentracing/ResteasyClientTracingRegistrarProvider.java
  testsuite/integration/microprofile-tck/opentracing/src/test/jakarta/java/io/smallrye/opentracing/arquillian/DeploymentProcessor.java
  testsuite/integration/microprofile-tck/opentracing/src/test/javax/java/io/smallrye/opentracing/ExceptionMapper.java
  testsuite/integration/microprofile-tck/opentracing/src/test/javax/java/io/smallrye/opentracing/ResteasyClientTracingRegistrarProvider.java
  testsuite/integration/microprofile-tck/opentracing/src/test/javax/java/io/smallrye/opentracing/arquillian/DeploymentProcessor.java
  testsuite/integration/microprofile-tck/pom.xml
  testsuite/integration/microprofile-tck/reactive-messaging/pom.xml
  testsuite/integration/microprofile-tck/rest-client/module.xml
  testsuite/integration/microprofile-tck/rest-client/pom.xml
  testsuite/integration/microprofile-tck/rest-client/wiremock-bootable.cli
  testsuite/integration/microprofile-tck/rest-client/wiremock.cli
Labels: deps-ok, Critical, 26.x

#15016 [WFLY-15807] Upgrade to WildFly Core 18.0.0.Final
  ee-9/feature-pack/pom.xml
  pom.xml
Labels: deps-ok

#15018 [WFLY-15824] Remove unnecessary resteasy-client-microprofile dependen…
  testsuite/integration/microprofile-tck/rest-client/pom.xml
Labels: deps-ok

#15011 [WFLY-15813] Update io.grpc version
  pom.xml
Labels: deps-ok, 27.x

#15022 [26.x][WFLY-15815] Add documentation of H2 Web Console (non-)integration
  docs/src/main/asciidoc/Developer_Guide.adoc
  docs/src/main/asciidoc/_developer-guide/H2_Web_Console_Integration.adoc
Labels: 26.x

#14914 [WFLY-15688] Eliminate deprecated org.jboss.remoting3.remoting-jmx & org.jboss.remoting3 modules
  ee-feature-pack/common/src/main/resources/modules/system/layers/base/org/jboss/remoting3/main/module.xml
  ee-feature-pack/common/src/main/resources/modules/system/layers/base/org/jboss/remoting3/remoting-jmx/main/module.xml
Labels: ready-for-merge, deps-ok

#15027 [WFLY-15776] Remove management identity's default security domain configuration from testsuite
  testsuite/integration/elytron/enable-elytron.cli
  testsuite/mixed-domain/src/test/resources/master-config/host-master-elytron.xml
  testsuite/shared/enable-elytron-manualmode.cli
  testsuite/shared/enable-elytron.cli
Labels: ready-for-merge, deps-ok

#15026 [WFLY-15830] Update HostExcludesTestCase configuration to work with WF27
  testsuite/domain/src/test/java/org/jboss/as/test/integration/domain/HostExcludesTestCase.java
Labels: ready-for-merge, deps-ok

#15029 WFLY-15835 Upgrade JGroups to 4.2.18.Final
  pom.xml
Labels: ready-for-merge, deps-ok

#15012 WFLY-15791 Simplify CalendarTimer.Builder by using ScheduleExpression…
  ejb3/src/main/java/org/jboss/as/ejb3/timerservice/CalendarTimer.java
  ejb3/src/main/java/org/jboss/as/ejb3/timerservice/TimerServiceImpl.java
  ejb3/src/main/java/org/jboss/as/ejb3/timerservice/persistence/database/DatabaseTimerPersistence.java
  ejb3/src/main/java/org/jboss/as/ejb3/timerservice/persistence/filestore/EjbTimerXmlParser_1_0.java
  ejb3/src/main/java/org/jboss/as/ejb3/timerservice/persistence/filestore/LegacyFileStore.java
Labels: ready-for-merge, deps-ok

#15035 [WFLY-15846] Upgrade WildFly Core 19.0.0.Beta1
  pom.xml
Labels: deps-changed

#14941 [WFLY-15734] / [WFLY-15356] Remove security-plugins dependency from EJB3.
  ee-feature-pack/common/src/main/resources/modules/system/layers/base/org/jboss/as/ejb3/main/module.xml
  ejb3/pom.xml
  ejb3/src/main/java/org/jboss/as/ejb3/component/EJBComponent.java
  ejb3/src/main/java/org/jboss/as/ejb3/component/EJBComponentCreateService.java
  ejb3/src/main/java/org/jboss/as/ejb3/component/EJBComponentDescription.java
  ejb3/src/main/java/org/jboss/as/ejb3/component/interceptors/AsyncFutureInterceptorFactory.java
  ejb3/src/main/java/org/jboss/as/ejb3/component/singleton/SingletonComponentDescription.java
  ejb3/src/main/java/org/jboss/as/ejb3/logging/EjbLogger.java
  ejb3/src/main/java/org/jboss/as/ejb3/remote/AssociationImpl.java
  ejb3/src/main/java/org/jboss/as/ejb3/remote/SecurityActions.java
  ejb3/src/main/java/org/jboss/as/ejb3/security/AuthorizationInterceptor.java
  ejb3/src/main/java/org/jboss/as/ejb3/security/EJBSecurityViewConfigurator.java
  ejb3/src/main/java/org/jboss/as/ejb3/security/SecurityContextInterceptor.java
  ejb3/src/main/java/org/jboss/as/ejb3/security/SecurityContextInterceptorFactory.java
  ejb3/src/main/java/org/jboss/as/ejb3/security/SecurityContextInterceptorHolder.java
Labels: ready-for-merge, deps-ok, EE9

#15028 [WFLY-15793] Add a ts.elytron-oidc-client profile to testsuite/integration/pom.xml
  testsuite/integration/pom.xml
Labels: ready-for-merge, deps-ok

#14684 [WFLY-15244] Drop Undertow model transformers prior to 11.0.0
  undertow/src/main/java/org/wildfly/extension/undertow/UndertowTransformers.java
  undertow/src/main/resources/META-INF/services/org.jboss.as.controller.transform.ExtensionTransformerRegistration
  undertow/src/test/java/org/wildfly/extension/undertow/UndertowTransformersTestCase.java
  undertow/src/test/resources/org/wildfly/extension/undertow/undertow-7.0.0-transformers.xml
  undertow/src/test/resources/org/wildfly/extension/undertow/undertow-7.1.0-transformers.xml
  undertow/src/test/resources/org/wildfly/extension/undertow/undertow-7.2.0-transformers.xml
  undertow/src/test/resources/org/wildfly/extension/undertow/undertow-7.3.0-transformers.xml
  undertow/src/test/resources/org/wildfly/extension/undertow/undertow-reject.xml
Labels: ready-for-merge, deps-ok

#14967 [WFLY-15721] Remove org.apache.commons.cli and org.apache.commons.lang3 modules and update wildfly-elytron-tool.jar
  ee-feature-pack/common/pom.xml
  ee-feature-pack/common/src/main/resources/license/ee-feature-pack-common-licenses.xml
  ee-feature-pack/common/src/main/resources/modules/system/layers/base/org/apache/commons/cli/main/module.xml
  ee-feature-pack/common/src/main/resources/modules/system/layers/base/org/apache/commons/lang3/main/module.xml
  ee-feature-pack/galleon-common/src/main/resources/packages/core-tools/pm/wildfly/tasks.xml
  pom.xml
Labels: core-upgrade-needed, ready-for-merge, deps-changed

#14817 WFLY-15331 Upgrade Infinispan to 13.0.3.Final.
  clustering/infinispan/extension/src/main/java/org/jboss/as/clustering/infinispan/ChannelConfigurator.java
  clustering/infinispan/extension/src/main/java/org/jboss/as/clustering/infinispan/DataSourceConnectionFactory.java
  clustering/infinispan/extension/src/main/java/org/jboss/as/clustering/infinispan/DataSourceConnectionFactoryConfiguration.java
  clustering/infinispan/extension/src/main/java/org/jboss/as/clustering/infinispan/DataSourceConnectionFactoryConfigurationBuilder.java
  clustering/infinispan/extension/src/main/java/org/jboss/as/clustering/infinispan/subsystem/GlobalConfigurationServiceConfigurator.java
  clustering/infinispan/extension/src/main/java/org/jboss/as/clustering/infinispan/subsystem/JDBCStoreResourceDefinition.java
  clustering/infinispan/extension/src/main/java/org/jboss/as/clustering/infinispan/subsystem/JDBCStoreServiceConfigurator.java
  clustering/infinispan/extension/src/main/java/org/jboss/as/clustering/infinispan/subsystem/StoreServiceConfigurator.java
  clustering/infinispan/extension/src/main/java/org/jboss/as/clustering/infinispan/subsystem/StoreWriteBehindServiceConfigurator.java
  clustering/infinispan/extension/src/main/java/org/jboss/as/clustering/infinispan/subsystem/StoreWriteThroughServiceConfigurator.java
  clustering/infinispan/extension/src/main/resources/org/jboss/as/clustering/infinispan/subsystem/LocalDescriptions.properties
  clustering/infinispan/marshalling/src/main/java/org/wildfly/clustering/infinispan/marshalling/AbstractMarshaller.java
  clustering/infinispan/spi/src/main/java/org/wildfly/clustering/infinispan/spi/DataContainerConfiguration.java
  clustering/infinispan/spi/src/main/java/org/wildfly/clustering/infinispan/spi/DataContainerConfigurationBuilder.java
  clustering/infinispan/spi/src/main/java/org/wildfly/clustering/infinispan/spi/GlobalConfigurationManagerFactory.java
  clustering/infinispan/spi/src/main/java/org/wildfly/clustering/infinispan/spi/LocalGlobalConfigurationManager.java
  clustering/infinispan/spi/src/main/java/org/wildfly/clustering/infinispan/spi/WildFlyInfinispanModuleLifecycle.java
  clustering/infinispan/spi/src/main/java/org/wildfly/clustering/infinispan/spi/WildFlyLocalConfigurationStorage.java
  clustering/infinispan/spi/src/main/java/org/wildfly/clustering/infinispan/spi/persistence/IndexedKeyFormatMapper.java
  ee-feature-pack/common/pom.xml
  ee-feature-pack/common/src/main/resources/modules/system/layers/base/org/infinispan/persistence/jdbc/main/module.xml
  pom.xml
  testsuite/integration/clustering/pom.xml
Labels: ready-for-merge, deps-changed

#14885 [WFLY-15636] Move eclipselink from prune to common without deprecated dependencies
  ee-feature-pack/common/pom.xml
  ee-feature-pack/common/src/main/resources/license/ee-feature-pack-common-licenses.xml
  ee-feature-pack/common/src/main/resources/modules/system/layers/base/org/eclipse/persistence/main/module.xml
  ee-feature-pack/pruned/pom.xml
  ee-feature-pack/pruned/src/main/resources/license/ee-feature-pack-legacy-licenses.xml
Labels: ready-for-merge, deps-changed

#14897 [WFLY-15655] Update the Elytron schema version specified in test configs to version 15
  docs/src/main/asciidoc/_admin-guide/Domain_Setup.adoc
  testsuite/domain/src/test/resources/domain-configs/domain-standard-ee.xml
  testsuite/domain/src/test/resources/domain-configs/domain-standard.xml
  testsuite/domain/src/test/resources/host-configs/host-master.xml
  testsuite/domain/src/test/resources/host-configs/host-slave.xml
  testsuite/mixed-domain/src/test/resources/master-config/host.xml
Labels: ready-for-merge, deps-ok

#14929 [WFLY-15720] Remove AssumeTestGroupUtil.assumeElytronProfileEnabled()
  testsuite/integration/manualmode/src/test/java/org/wildfly/test/manual/management/MPScriptTestCase.java
  testsuite/integration/microprofile/src/test/java/org/wildfly/test/integration/microprofile/health/MicroProfileHealthSecuredHTTPEndpointEmptyMgmtUsersTestCase.java
  testsuite/integration/microprofile/src/test/java/org/wildfly/test/integration/microprofile/metrics/secured/MicroProfileMetricsSecuredEndpointEmptyMgmtUsersTestCase.java
  testsuite/shared/src/main/java/org/jboss/as/test/shared/util/AssumeTestGroupUtil.java
Labels: ready-for-merge, deps-ok

#14670 Fix for WFLY-15057, Reactivate SecurityCommands Test
  docs/src/main/asciidoc/_elytron/Using_the_Elytron_Subsystem.adoc
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/management/cli/SecurityAuthCommandsTestCase.java
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/management/cli/SecurityCommandsTestCase.java
Labels: ready-for-merge, deps-ok

#15044 WFLY-15852 TimedObjectInvokerImpl should not be serializable
  ejb3/src/main/java/org/jboss/as/ejb3/timerservice/TimedObjectInvokerImpl.java
Labels: deps-ok

#15038 WFLY-15823 Consolidate log messages and methods used in timer schedul…
  ejb3/src/main/java/org/jboss/as/ejb3/logging/EjbLogger.java
  ejb3/src/main/java/org/jboss/as/ejb3/timerservice/schedule/attribute/DayOfMonth.java
  ejb3/src/main/java/org/jboss/as/ejb3/timerservice/schedule/attribute/IntegerBasedExpression.java
  ejb3/src/main/java/org/jboss/as/ejb3/timerservice/schedule/attribute/Minute.java
  ejb3/src/main/java/org/jboss/as/ejb3/timerservice/schedule/attribute/Month.java
  ejb3/src/main/java/org/jboss/as/ejb3/timerservice/schedule/attribute/Second.java
  ejb3/src/main/java/org/jboss/as/ejb3/timerservice/schedule/value/IncrementValue.java
  ejb3/src/main/java/org/jboss/as/ejb3/timerservice/schedule/value/ListValue.java
  ejb3/src/main/java/org/jboss/as/ejb3/timerservice/schedule/value/RangeValue.java
  ejb3/src/main/java/org/jboss/as/ejb3/timerservice/schedule/value/ScheduleExpressionType.java
Labels: deps-ok

#14991 WFLY-15784 Merge ejb3 ScheduleTimer and AutoTimer classes
  ejb3/src/main/java/org/jboss/as/ejb3/timerservice/AutoTimer.java
  ejb3/src/main/java/org/jboss/as/ejb3/timerservice/TimerServiceImpl.java
  ejb3/src/main/java/org/jboss/as/ejb3/timerservice/spi/ScheduleTimer.java
Labels: deps-ok

#14861 WFLY-15569 Database persistent auto timer are created twice
  ee-feature-pack/common/src/main/resources/modules/system/layers/base/org/jboss/as/ejb3/main/timers/timer-sql.properties
  ejb3/src/main/java/org/jboss/as/ejb3/timerservice/TimerServiceImpl.java
  ejb3/src/main/java/org/jboss/as/ejb3/timerservice/persistence/TimerPersistence.java
  ejb3/src/main/java/org/jboss/as/ejb3/timerservice/persistence/database/DatabaseTimerPersistence.java
  ejb3/src/test/java/org/jboss/as/ejb3/timerservice/persistence/database/DatabaseTimerPersistenceTestCase.java
  testsuite/integration/multinode/src/test/java/org/jboss/as/test/multinode/ejb/timer/database/DatabaseTimerServiceMultiNodeTestCase.java
  testsuite/integration/multinode/src/test/java/org/jboss/as/test/multinode/ejb/timer/database/StartupSingleton.java
Labels: deps-ok

#14923 WFLY-15711 Remove references to entity bean primary key from timer se…
  ejb3/src/main/java/org/jboss/as/ejb3/timerservice/TimerImpl.java
  ejb3/src/main/java/org/jboss/as/ejb3/timerservice/TimerServiceImpl.java
  ejb3/src/main/java/org/jboss/as/ejb3/timerservice/persistence/CalendarTimerEntity.java
  ejb3/src/main/java/org/jboss/as/ejb3/timerservice/persistence/TimerEntity.java
  ejb3/src/main/java/org/jboss/as/ejb3/timerservice/persistence/database/DatabaseTimerPersistence.java
  ejb3/src/main/java/org/jboss/as/ejb3/timerservice/persistence/filestore/EjbTimerXmlParser_1_0.java
  ejb3/src/main/java/org/jboss/as/ejb3/timerservice/persistence/filestore/EjbTimerXmlPersister.java
  ejb3/src/main/java/org/jboss/as/ejb3/timerservice/persistence/filestore/LegacyFileStore.java
Labels: rebase-this, deps-ok

#15048 WFLY-15853 org.jboss.as.ejb3.timerservice.TimerTask need not be gener…
  ejb3/src/main/java/org/jboss/as/ejb3/timerservice/CalendarTimer.java
  ejb3/src/main/java/org/jboss/as/ejb3/timerservice/CalendarTimerTask.java
  ejb3/src/main/java/org/jboss/as/ejb3/timerservice/TimerImpl.java
  ejb3/src/main/java/org/jboss/as/ejb3/timerservice/TimerServiceImpl.java
  ejb3/src/main/java/org/jboss/as/ejb3/timerservice/TimerTask.java
Labels: deps-ok

#15050 WFLY-15856 Upgrade Infinispan to 13.0.5.Final
  clustering/infinispan/extension/src/main/java/org/jboss/as/clustering/infinispan/subsystem/FileStoreServiceConfigurator.java
  clustering/infinispan/extension/src/main/java/org/jboss/as/clustering/infinispan/subsystem/remote/HotRodStore.java
  clustering/infinispan/spi/src/main/java/org/wildfly/clustering/infinispan/spi/persistence/sifs/SoftIndexFileStore.java
  clustering/infinispan/spi/src/main/java/org/wildfly/clustering/infinispan/spi/persistence/sifs/SoftIndexFileStoreConfiguration.java
  clustering/infinispan/spi/src/main/java/org/wildfly/clustering/infinispan/spi/persistence/sifs/SoftIndexFileStoreConfigurationBuilder.java
  pom.xml
  testsuite/integration/clustering/pom.xml
Labels: deps-ok
