Repository wildfly/wildfly, pull requests merged in 2021-04, with the labels that each got.

#14173 [WFLY-14665] Upgrade MyFaces to 2.3.8 in jsf/multi-jsf-installer/pom.xml
  jsf/multi-jsf-installer/pom.xml
Labels: deps-ok

#14174 [23.x][WFLY-14665] Upgrade MyFaces to 2.3.8 in jsf/multi-jsf-installer/pom.xml
  jsf/multi-jsf-installer/pom.xml
Labels: 23.x

#14164 [WFLY-14644][WFLY-14645][WFLY-14646][WFLY-14647] Getting Started Guide improvements
  docs/src/main/asciidoc/Getting_Started_Guide.adoc
Labels: deps-ok

#14176 WFLY-14667 Add a dependency on java.management module in the io.netty
  ee-feature-pack/common/src/main/resources/modules/system/layers/base/io/netty/main/module.xml
Labels: deps-ok

#14163 WFLY-14588 Remove redundant field for negative BitInteger values.
  clustering/marshalling/api/src/main/resources/java.math.proto
  clustering/marshalling/protostream/src/main/java/org/wildfly/clustering/marshalling/protostream/math/BigDecimalMarshaller.java
  clustering/marshalling/protostream/src/main/java/org/wildfly/clustering/marshalling/protostream/math/BigIntegerMarshaller.java
  clustering/marshalling/protostream/src/main/java/org/wildfly/clustering/marshalling/protostream/math/MathMarshallerProvider.java
Labels: deps-ok

#14178 [23.x]WFLY-14667 Add a dependency on java.management module in the io.netty
  ee-feature-pack/common/src/main/resources/modules/system/layers/base/io/netty/main/module.xml
Labels: 23.x

#14175 [WFLY-14609] CLI ...service=timer-service/timer=* throws NullPointerException
  ejb3/src/main/java/org/jboss/as/ejb3/logging/EjbLogger.java
  ejb3/src/main/java/org/jboss/as/ejb3/subsystem/deployment/TimerResourceDefinition.java
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/ejb/timerservice/mgmt/AbstractTimerManagementTestCase.java
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/ejb/timerservice/mgmt/TimerManagementTestCase.java
Labels: deps-ok

#14181 [WFLY-14538] Upgrade WildFly Preview's JAX-RS API to org.jboss.spec.j…
  ee-9/feature-pack/pom.xml
Labels: deps-ok

#14182 [23.x][WFLY-14538] Upgrade WildFly Preview's JAX-RS API to org.jboss.spec.j…
  ee-9/feature-pack/pom.xml
Labels: 23.x

#14183 [WFLY-14675] Mark the messaging-activemq deserialization-white-list a…
  messaging-activemq/src/main/java/org/wildfly/extension/messaging/activemq/jms/ConnectionFactoryAttributes.java
  messaging-activemq/src/main/resources/org/wildfly/extension/messaging/activemq/LocalDescriptions.properties
Labels: deps-ok

#14184 [WFLY-11933] Return properly configured ModelNode when RBAC is enabled
  metrics/src/main/java/org/wildfly/extension/metrics/WildFlyMetric.java
Labels: 23.x

#14188 [WFLY-14567] Add error message when Remoting connector not correctly configured for EJB client invocations.
  ejb3/src/main/java/org/jboss/as/ejb3/logging/EjbLogger.java
  ejb3/src/main/java/org/jboss/as/ejb3/remote/AssociationImpl.java
Labels: deps-ok

#14189 WFLY-14681 Upgrade JGroups to 4.2.12.Final
  pom.xml
Labels: deps-ok

#14191 WFLY-14683: Upgrade HAL to 3.3.2.Final
  pom.xml
Labels: deps-ok

#14204 [WFLY-14688] Add the java.se module dependency to the org.bouncycastl…
  ee-feature-pack/common/src/main/resources/modules/system/layers/base/org/bouncycastle/bcmail/main/module.xml
Labels: deps-ok

#14198 [WFLY-14678] Upgrade netty to 4.1.63.Final
  pom.xml
Labels: deps-ok, ready-for-merge

#14199 [23.x][WFLY-14678] Upgrade netty to 4.1.63.Final
  pom.xml
Labels: 23.x, ready-for-merge

#14196 [WFLY-14673] Utilize o.w.common.Assert for Null-Checks (ee-injection)
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/ee/injection/resource/url/URLConnectionFactoryResourceInjectionTestEJB.java
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/ee/injection/support/servlet/TestReadListener.java
Labels: deps-ok

#14205 [WFLY-14688] Add the java.se module dependency to the org.bouncycastl…
  ee-feature-pack/common/src/main/resources/modules/system/layers/base/org/bouncycastle/bcmail/main/module.xml
Labels: 23.x

#14209 [WFLY-14694] Don't return bad data for unavailable metrics
  microprofile/metrics-smallrye/src/main/java/org/wildfly/extension/microprofile/metrics/MicroProfileVendorMetricRegistry.java
  microprofile/metrics-smallrye/src/main/java/org/wildfly/extension/microprofile/metrics/_private/MicroProfileMetricsLogger.java
Labels: deps-ok

#14210 [WFLY-14694] Don't return bad data for unavailable metrics
  microprofile/metrics-smallrye/src/main/java/org/wildfly/extension/microprofile/metrics/MicroProfileVendorMetricRegistry.java
  microprofile/metrics-smallrye/src/main/java/org/wildfly/extension/microprofile/metrics/_private/MicroProfileMetricsLogger.java
Labels: 23.x

#14187 [WFLY-14673] Utilize o.w.common.Assert for Null-Checks (connector)
  connector/src/main/java/org/jboss/as/connector/annotations/repository/jandex/JandexAnnotationRepositoryImpl.java
  connector/src/main/java/org/jboss/as/connector/services/driver/registry/DriverRegistryImpl.java
  connector/src/main/java/org/jboss/as/connector/services/resourceadapters/deployment/registry/ResourceAdapterDeploymentRegistryImpl.java
  connector/src/main/java/org/jboss/as/connector/util/Injection.java
Labels: deps-ok

#14193 [WFLY-14673] Utilize o.w.common.Assert for Null-Checks (ee-concurrent)
  ee/src/main/java/org/jboss/as/ee/concurrent/service/ManagedExecutorHungTasksPeriodicTerminationService.java
Labels: deps-ok

#14124 [WFLY-14579]: The threadpool name of a workmanager must be the name o…
  connector/src/main/java/org/jboss/as/connector/logging/ConnectorLogger.java
  connector/src/main/java/org/jboss/as/connector/subsystems/jca/JcaWorkManagerDefinition.java
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/jca/workmanager/WorkManagerThreadsCheckTestCase.java
Labels: deps-ok, ready-for-merge

#14202 [WFLY-14673] Utilize org.wildfly.common.Assert for Null-Checks (undertow)
  undertow/pom.xml
  undertow/src/main/java/org/wildfly/extension/undertow/ImportedClassELResolver.java
Labels: deps-ok

#14211 [WFLY-14673] Utilize org.wildfly.common.Assert for Null-Checks (testsuite_misc)
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/pojo/support/TcclChecker.java
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/rar/HelloWorldManagedConnection.java
  testsuite/integration/rts/src/test/java/org/wildfly/test/extension/rts/InboundBridgeUtilities.java
Labels: deps-ok

#14206 [WFLY-14239] Add basic documentation of WildFly Preview
  docs/src/main/asciidoc/Bootable_Guide.adoc
  docs/src/main/asciidoc/Installation_Guide.adoc
  docs/src/main/asciidoc/WildFly_and_WildFly_Preview.adoc
  docs/src/main/asciidoc/_galleon/Galleon_provisioning.adoc
  docs/src/main/asciidoc/index.adoc
Labels: deps-ok

#14207 [23.x][WFLY-14239] Add basic documentation of WildFly Preview
  docs/src/main/asciidoc/Bootable_Guide.adoc
  docs/src/main/asciidoc/Installation_Guide.adoc
  docs/src/main/asciidoc/WildFly_and_WildFly_Preview.adoc
  docs/src/main/asciidoc/_galleon/Galleon_provisioning.adoc
  docs/src/main/asciidoc/index.adoc
Labels: 23.x

#14195 [WFLY-14673] Utilize org.wildfly.common.Assert for Null-Checks (metrics)
  ee-feature-pack/common/src/main/resources/modules/system/layers/base/org/wildfly/extension/metrics/main/module.xml
  metrics/pom.xml
  metrics/src/main/java/org/wildfly/extension/metrics/WildFlyMetricMetadata.java
  metrics/src/main/java/org/wildfly/extension/metrics/jmx/JmxMetricCollector.java
Labels: deps-ok

#14215 [WFLY-14697] Allow null metrics prefix
  metrics/src/main/java/org/wildfly/extension/metrics/WildFlyMetricMetadata.java
Labels: deps-ok

#14219 [WFLY-14708] Upgrade openjdk-orb to 8.1.5.Final
  pom.xml
Labels: deps-ok

#14218 WFLY-14706 Distributed JSF applications should auto-disable "com.sun.faces.enableLazyBeanValidation" by default
  jsf/subsystem/src/main/java/org/jboss/as/jsf/deployment/JSFMetadataProcessor.java
  jsf/subsystem/src/main/java/org/jboss/as/jsf/logging/JSFLogger.java
Labels: deps-ok

#14186 [WFLY-14673] Utilize org.wildfly.common.Assert for Null-Checks (clust…
  clustering/ee/cache/src/main/java9/org/wildfly/clustering/ee/cache/scheduler/FastConcurrentDirectDeque.java
  clustering/infinispan/spi/src/main/java/org/wildfly/clustering/infinispan/spi/persistence/IndexedKeyFormatMapper.java
  ee-feature-pack/common/src/main/resources/modules/system/layers/base/org/wildfly/clustering/infinispan/spi/main/module.xml
  testsuite/integration/clustering/src/test/java/org/jboss/as/test/clustering/cluster/AbstractClusteringTestCase.java
Labels: deps-ok

#14222 [WFLY-13767] Upgrade PicketLink bindings from 2.5.5.SP12-redhat-00012 to 2.5.5.SP12-redhat-00013
  pom.xml
Labels: deps-ok

#14228 [WFLY-14711] In WildFly Preview enable use of an alternate XJC variant
  ee-9/feature-pack/pom.xml
  testsuite/integration/pom.xml
  testsuite/layers/pom.xml
Labels: deps-ok, ready-for-merge

#14229 [23.x][WFLY-14711] In WildFly Preview enable use of an alternate XJC variant
  ee-9/feature-pack/pom.xml
  testsuite/integration/pom.xml
  testsuite/layers/pom.xml
Labels: 23.x

#14227 [23.x][WFLY-14710] Run ws and layers tests when -Dts.ee9 is used
  testsuite/integration/pom.xml
  testsuite/layers/pom.xml
Labels: 23.x

#14233 WFLY-14713: Upgrade HAL to 3.3.4.Final
  pom.xml
Labels: deps-ok

#14234 WFLY-14713: Upgrade HAL to 3.3.4.Final
  pom.xml
Labels: 23.x

#14208 [WFLY-14692] Tests security domain with dots in the name
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/management/api/security/SecurityDomainDotNameServerSetupTask.java
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/management/api/security/SecurityDomainDotNameTestCase.java
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/management/api/security/restricted/errors.jsp
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/management/api/security/restricted/login.html
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/management/api/security/web.xml
Labels: deps-ok, ready-for-merge

#14216 WFLY-14704 Upgrade both Weld versions to latest release.
  ee-9/feature-pack/pom.xml
  pom.xml
Labels: deps-ok

#14239 [WFLY-14723] Upgrade XJC in WildFly Preview to 2.3.3-b02-jbossorg-1
  ee-9/feature-pack/pom.xml
Labels: 23.x

#14242 [WFLY-14731] Upgrade WildFly Core 16.0.0.Beta3
  pom.xml
Labels: deps-ok, ready-for-merge

#14235 WFLY-14722: Upgrade HAL to 3.3.6.Final
  pom.xml
Labels: deps-ok

#14236 WFLY-14722: Upgrade HAL to 3.3.6.Final
  pom.xml
Labels: 23.x

#14241 [WFLY-14728] Use expressions for all attributes that support them in …
  ee/src/test/resources/org/jboss/as/ee/subsystem/subsystem.xml
Labels: deps-ok

#14232 [WFLY-14714] Specify bean-discovery-mode for RSO CDI Provider
  microprofile/reactive-streams-operators-smallrye/cdi-provider/src/main/java/org/wildfly/extension/microprofile/reactive/streams/operators/cdi/ReactiveEngineProvider.java
  microprofile/reactive-streams-operators-smallrye/cdi-provider/src/main/resources/META-INF/beans.xml
Labels: deps-ok

#14194 [WFLY-14673] Utilize o.w.common.Assert for Null-Checks (ejb)
  ejb3/src/main/java/org/jboss/as/ejb3/deployment/EjbDeploymentInformation.java
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/ejb/container/interceptor/security/api/CurrentUserCredential.java
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/ejb/mdb/objectmessage/SimpleMessageInEarLibJar.java
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/ejb/security/securitydomain/EJBContextMultipleSDTestCase.java
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/ejb/security/securitydomain/module/MyPrincipal.java
Labels: deps-ok

#14237 [WFLY-14724] AutomaticSelfSignedCertificateGenerationTestCase and Aut…
  testsuite/integration/elytron/src/test/java/org/wildfly/test/integration/elytron/ssl/AutomaticSelfSignedCertificateGenerationTestCase.java
  testsuite/integration/elytron/src/test/java/org/wildfly/test/integration/elytron/ssl/AutomaticSelfSignedCertificateNotGeneratedTestCase.java
Labels: deps-ok

#14240 [WFLY-14727] Exclude SecurityDomainDotNameTestCase when testing Wildf…
  testsuite/integration/basic/pom.xml
Labels: deps-ok

#14200 [WFLY-14648] resolve expression for enabled attribute in Undertow subsystem
  undertow/src/main/java/org/wildfly/extension/undertow/ListenerResourceDefinition.java
  undertow/src/test/java/org/wildfly/extension/undertow/AbstractUndertowSubsystemTestCase.java
Labels: deps-ok

#14244 [WFLY-14732] Upgrade WildFly Galleon Plugins to 5.1.3.Final
  pom.xml
Labels: deps-ok

#14245 [23.x][WFLY-14732] Upgrade WildFly Galleon Plugins to 5.1.3.Final
  pom.xml
Labels: 23.x

#13793 [WFLY-13981] Remove legacy security configuration from appclient.xml
  ee-9/feature-pack/pom.xml
  ee-feature-pack/common/src/main/resources/content/appclient/configuration/appclient.xml
  ee-feature-pack/common/src/main/resources/modules/system/layers/base/org/jboss/as/appclient/main/module.xml
  ee-feature-pack/common/src/main/resources/modules/system/layers/base/org/jboss/as/security-api/main/module.xml
  security/api/pom.xml
Labels: 24.x, EE9, deps-ok

#14185 [WFLY-14625]: WARN message jaegertracing: FlushCommand execution failed!
  microprofile/galleon-common/src/main/resources/modules/system/layers/base/io/jaegertracing/jaeger/main/module.xml
  microprofile/opentracing-extension/src/main/java/org/wildfly/extension/microprofile/opentracing/spi/sender/WildFlySender.java
  microprofile/opentracing-extension/src/main/java/org/wildfly/extension/microprofile/opentracing/spi/sender/WildFlySenderFactory.java
  microprofile/opentracing-extension/src/main/resources/META-INF/services/io.jaegertracing.spi.SenderFactory
Labels: deps-ok

#14247 [WFLY-14733] Remove commons-io dependency from JDR subsystem
  ee-feature-pack/common/src/main/resources/modules/system/layers/base/org/jboss/as/jdr/main/module.xml
  jdr/jboss-as-jdr/pom.xml
  jdr/jboss-as-jdr/src/main/java/org/jboss/as/jdr/util/Utils.java
  jdr/jboss-as-jdr/src/main/java/org/jboss/as/jdr/util/XMLSanitizer.java
Labels: deps-ok, ready-for-merge

#14213 WFLY-14698 Caching of managed beans in WebInjectionContainer can cause memory leaks in distributed JSF applications following session timeout
  ee/src/main/java/org/jboss/as/ee/component/BasicComponent.java
  ee/src/main/java/org/jboss/as/ee/component/Component.java
  ee/src/main/java/org/jboss/as/ee/component/ComponentRegistry.java
  ee/src/main/java/org/jboss/as/ee/component/EEClassIntrospector.java
  ee/src/main/java/org/jboss/as/ee/component/ReflectiveClassIntrospector.java
  jsf/injection/src/main/java/org/jboss/as/jsf/injection/MyFacesLifecycleProvider.java
  undertow/src/main/java/org/wildfly/extension/undertow/deployment/UndertowDeploymentInfoService.java
  undertow/src/main/java/org/wildfly/extension/undertow/deployment/UndertowDeploymentProcessor.java
  web-common/src/main/java/org/jboss/as/web/common/AbstractWebInjectionContainer.java
  web-common/src/main/java/org/jboss/as/web/common/CachingWebInjectionContainer.java
  web-common/src/main/java/org/jboss/as/web/common/SimpleWebInjectionContainer.java
  web-common/src/main/java/org/jboss/as/web/common/WebInjectionContainer.java
  weld/subsystem/src/main/java/org/jboss/as/weld/deployment/WeldClassIntrospector.java
Labels: deps-ok

#14255 Fix for WFLY-14744, Upgrade tests to use bootable JAR 4.0.3.Final
  pom.xml
Labels: deps-ok

#14256 [WFLY-14745] Update AutomaticSelfSignedCertificateNotGeneratedTestCase to make use of a stronger encryption algorithm when creating the key store in the test setup
  testsuite/integration/elytron/src/test/java/org/wildfly/test/integration/elytron/ssl/AutomaticSelfSignedCertificateNotGeneratedTestCase.java
Labels: deps-ok

#14258 [WFLY-14730] Use expressions in the Agroal config used for the standa…
  datasources-agroal/src/test/resources/org/wildfly/extension/datasources/agroal/agroal_2_0-transformers.xml
Labels: deps-ok

#14203 [WFLY-14673] Utilize o.w.common.Assert for Null-Checks (webservices)
  ee-feature-pack/common/src/main/resources/modules/system/layers/base/org/jboss/as/webservices/main/module.xml
  web-common/src/main/java/org/jboss/as/web/common/ConcurrentReferenceHashMap.java
  webservices/server-integration/src/main/java/org/jboss/as/webservices/deployers/WSEndpointConfigMapping.java
  webservices/server-integration/src/main/java/org/jboss/as/webservices/deployers/deployment/JandexAnnotationsInfo.java
  webservices/server-integration/src/main/java/org/jboss/as/webservices/injection/WSEndpointHandlersMapping.java
Labels: deps-ok

#14101 [WFLY-14546] Restore naming context
  testsuite/integration/basic/src/test/java/org/wildfly/test/integration/weld/asyncobserver/AsyncObserverAccessCompNamespaceTestCase.java
  testsuite/integration/basic/src/test/java/org/wildfly/test/integration/weld/asyncobserver/TestObserver.java
  weld/subsystem/src/main/java/org/jboss/as/weld/services/bootstrap/WeldExecutorServices.java
Labels: deps-ok

#14257 WFLY-14746 Remove deprecated STABLE.stability_delay from jgroups-defaults.xml
  clustering/jgroups/extension/src/main/resources/jgroups-defaults.xml
Labels: deps-ok

#14260 [WFLY-14747] fix issue when generating microprofile-feature-pack-licenses.xml license file
  galleon-pack/galleon-feature-pack/pom.xml
Labels: deps-ok

#14261 [WFLY-14749] sort licenses from microprofile-feature-pack-licenses.xml file
  microprofile/galleon-common/src/main/resources/license/microprofile-feature-pack-licenses.xml
Labels: deps-ok

#14251 WFLY-14739 Upgrade smallrye-open-api to 2.1.3
  pom.xml
Labels: deps-ok

#14246 [WFLY-14279] Don't prematurely validate the appclient file param. Hav…
  appclient/src/main/java/org/jboss/as/appclient/subsystem/AppClientSubsystemAdd.java
  appclient/src/main/java/org/jboss/as/appclient/subsystem/Main.java
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/ee/appclient/basic/AbstractSimpleApplicationClientTestCase.java
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/ee/appclient/util/AppClientWrapper.java
Labels: deps-ok
