Repository wildfly/wildfly, pull requests merged in 2021-07, with the labels that each got.

#14367 WFLY-14870 Remove deprecated EJB EagerEvictionScheduler
  clustering/ejb/infinispan/src/main/java/org/wildfly/clustering/ejb/infinispan/CompositeScheduler.java
  clustering/ejb/infinispan/src/main/java/org/wildfly/clustering/ejb/infinispan/EagerEvictionScheduler.java
  clustering/ejb/infinispan/src/main/java/org/wildfly/clustering/ejb/infinispan/InfinispanBeanManager.java
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/ejb/stateful/passivation/EagerPassivationTestCase.java
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/ejb/stateful/passivation/EagerPassivationTestCaseSetup.java
Labels: 25.x, deps-ok

#14410 [WFLY-14958] Remove old unused private code
  connector/src/main/java/org/jboss/as/connector/subsystems/datasources/DataSourceDefinition.java
  connector/src/main/java/org/jboss/as/connector/subsystems/resourceadapters/IronJacamarResourceCreator.java
  iiop-openjdk/src/main/java/org/wildfly/iiop/openjdk/rmi/Util.java
  legacy/messaging/src/main/java/org/jboss/as/messaging/MigrateOperation.java
  picketlink/src/main/java/org/wildfly/extension/picketlink/idm/model/parser/IDMSubsystemWriter.java
  undertow/src/main/java/org/wildfly/extension/undertow/deployment/UndertowDeploymentInfoService.java
Labels: deps-ok

#14452 [WFLY-14981]: JmsXA connection factory not binding to java:jboss/Defa…
  messaging-activemq/subsystem/src/main/java/org/wildfly/extension/messaging/activemq/deployment/JMSConnectionFactoryDefinitionInjectionSource.java
Labels: deps-ok

#14447 [WFLY-14897] Drop the Java EE 7 guide for WildFly
  docs/src/main/asciidoc/_javaee-guide/Jakarta_Authentication.adoc
  docs/src/main/asciidoc/_javaee-guide/Jakarta_Authorization.adoc
  docs/src/main/asciidoc/_javaee-guide/Jakarta_Bean_Validation.adoc
  docs/src/main/asciidoc/_javaee-guide/Jakarta_Connectors_Architecture.adoc
  docs/src/main/asciidoc/_javaee-guide/Jakarta_Contexts_and_Dependency_Injection.adoc
  docs/src/main/asciidoc/_javaee-guide/Jakarta_Enterprise_Beans.adoc
  docs/src/main/asciidoc/_javaee-guide/Jakarta_Mail.adoc
  docs/src/main/asciidoc/_javaee-guide/Jakarta_Messaging_API.adoc
  docs/src/main/asciidoc/_javaee-guide/Jakarta_Persistence_API.adoc
  docs/src/main/asciidoc/_javaee-guide/Jakarta_RESTful_Web_Services.adoc
  docs/src/main/asciidoc/_javaee-guide/Jakarta_Server_Faces_Technology.adoc
  docs/src/main/asciidoc/_javaee-guide/Jakarta_Servlet_Technology.adoc
  docs/src/main/asciidoc/_javaee-guide/Jakarta_Transactions.adoc
  docs/src/main/asciidoc/_javaee-guide/Jakarta_XML_Web_Services.adoc
  docs/src/main/asciidoc/_javaee-guide/Managed_Beans.adoc
Labels: deps-ok

#14404 [WFLY-14951] public static fields miss final declaration
  connector/src/main/java/org/jboss/as/connector/subsystems/common/pool/Constants.java
  connector/src/main/java/org/jboss/as/connector/subsystems/datasources/Constants.java
  connector/src/main/java/org/jboss/as/connector/subsystems/datasources/DataSourcesSubsystemProviders.java
  connector/src/main/java/org/jboss/as/connector/subsystems/resourceadapters/Constants.java
  ejb3/src/main/java/org/jboss/as/ejb3/subsystem/AllowedChannelOptionTypesValidator.java
  jaxrs/src/main/java/org/jboss/as/jaxrs/DeploymentRestResourcesDefintion.java
  jaxrs/src/main/java/org/jboss/as/jaxrs/JaxrsAttribute.java
  jsf/subsystem/src/main/java/org/jboss/as/jsf/subsystem/JSFResourceDefinition.java
  picketlink/src/main/java/org/wildfly/extension/picketlink/common/model/validator/NotEmptyResourceValidationStepHandler.java
  security/subsystem/src/main/java/org/jboss/as/security/TransactionManagerLocatorService.java
  undertow/src/main/java/org/wildfly/extension/undertow/filters/ModClusterBalancerDefinition.java
  undertow/src/main/java/org/wildfly/extension/undertow/filters/ModClusterContextDefinition.java
  undertow/src/main/java/org/wildfly/extension/undertow/filters/ModClusterLoadBalancingGroupDefinition.java
  undertow/src/main/java/org/wildfly/extension/undertow/filters/ModClusterNodeDefinition.java
Labels: deps-ok

#14403 [WFLY-14950] Use Arrays.toString
  iiop-openjdk/src/main/java/org/wildfly/iiop/openjdk/naming/jndi/CNCtx.java
Labels: deps-ok

#14398 [WFLY-14880] Upgrade Bouncycastle temporary disable tests for CI
  testsuite/integration/elytron/src/test/java/org/wildfly/test/integration/elytron/certs/crl/CertificateRevocationListTestCase.java
  testsuite/integration/elytron/src/test/java/org/wildfly/test/integration/elytron/certs/ocsp/OcspResponderDownTestCase.java
  testsuite/integration/elytron/src/test/java/org/wildfly/test/integration/elytron/certs/ocsp/OcspTestCase.java
Labels: deps-ok

#14441 [WFLY-14972] Check emptiness with Collection.isEmpty() (Legacy)
  legacy/jaxr/src/main/java/org/jboss/as/jaxr/extension/JAXRSubsystemParser.java
  legacy/messaging/src/main/java/org/jboss/as/messaging/AttributeMarshallers.java
  legacy/messaging/src/main/java/org/jboss/as/messaging/MessagingXMLWriter.java
Labels: deps-ok

#14443 [WFLY-14972] Check emptiness with Collection.isEmpty() (JDR)
  jdr/jboss-as-jdr/src/main/java/org/jboss/as/jdr/JdrRunner.java
  jdr/jboss-as-jdr/src/main/java/org/jboss/as/jdr/commands/CallAS7.java
Labels: deps-ok

#14451 [WFLY-14972] Check emptiness with Collection.isEmpty() (Misc)
  ee/src/main/java/org/jboss/as/ee/component/ComponentRegistry.java
  iiop-openjdk/src/main/java/org/wildfly/iiop/openjdk/naming/jndi/IiopUrl.java
Labels: deps-ok

#14411 [WFLY-14960] Upgrade commons-io from 2.5 to 2.10.0
  pom.xml
Labels: deps-ok

#14449 [WFLY-14979] Upgrade the MicroProfile JWT API to 1.2.1
  pom.xml
Labels: deps-ok

#14391 [WFLY-14913] ignore error on container kill command as process is for…
  testsuite/integration/manualmode/src/test/java/org/jboss/as/test/manualmode/ejb/client/outbound/connection/transaction/preparehalt/TransactionPropagationFailureTestCase.java
  testsuite/shared/src/main/java/org/jboss/as/test/integration/transactions/RecoveryExecutor.java
Labels: deps-ok

#14385 [WFCORE-3467] Require existence of the AttributeDefinition in AbstractWriteAttributeHandler
  connector/src/main/java/org/jboss/as/connector/subsystems/resourceadapters/ConfigPropertyResourceDefinition.java
  ee/src/test/java/org/jboss/as/ee/subsystem/EeLegacySubsystemTestCase.java
Labels: deps-ok

#14389 [WFLY-14912] Early PR for Vault Removal
  ee-feature-pack/galleon-content/src/main/resources/packages/vaulttools/package.xml
  ee-feature-pack/pruned/pom.xml
  ee-feature-pack/pruned/src/main/resources/license/ee-feature-pack-legacy-licenses.xml
  ee-feature-pack/pruned/src/main/resources/modules/system/layers/base/org/jboss/as/vault-tool/main/module.xml
  ee/src/main/java/org/jboss/as/ee/metadata/property/VaultPropertyResolver.java
  ee/src/main/java/org/jboss/as/ee/metadata/property/VaultPropertyResolverProcessor.java
  ee/src/main/java/org/jboss/as/ee/subsystem/EeSubsystemAdd.java
  pom.xml
  security/pom.xml
  security/vault-tool/pom.xml
  security/vault-tool/src/main/java/org/jboss/as/security/vault/VaultInteraction.java
  security/vault-tool/src/main/java/org/jboss/as/security/vault/VaultInteractiveSession.java
  security/vault-tool/src/main/java/org/jboss/as/security/vault/VaultLogger.java
  security/vault-tool/src/main/java/org/jboss/as/security/vault/VaultSession.java
  security/vault-tool/src/main/java/org/jboss/as/security/vault/VaultTool.java
  security/vault-tool/src/test/java/org/jboss/as/security/vault/MockRuntimeVaultReader.java
  security/vault-tool/src/test/java/org/jboss/as/security/vault/VaultSessionTestCase.java
  security/vault-tool/src/test/java/org/jboss/as/security/vault/VaultTest.java
  security/vault-tool/src/test/java/org/jboss/as/security/vault/VaultToolTestCase.java
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/ejb/mdb/vaultedproperties/MDB.java
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/ejb/mdb/vaultedproperties/MDBWithVaultedPropertiesTestCase.java
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/messaging/jms/context/VaultedInjectedJMSContextTestCase.java
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/messaging/jms/context/auxiliary/VaultedMessageProducer.java
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/messaging/jms/definitions/JMSResourceDefinitionsTestCase.java
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/messaging/jms/definitions/MessagingBean.java
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/messaging/jms/definitions/ejb-jar.xml
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/security/loginmodules/LdapExtLikeAdvancedLdapLMTestCase.java
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/security/loginmodules/LdapExtLoginModuleTestCase.java
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/security/passwordmasking/PasswordMaskingInContainerTestCase.java
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/security/passwordmasking/PasswordMaskingTestCase.java
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/security/passwordmasking/PasswordMaskingTestServlet.java
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/security/passwordmasking/web.xml
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/security/vault/CheckVaultedPassServlet.java
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/security/vault/ExternalPassword.java
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/security/vault/ExternalPasswordByClassTestCase.java
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/security/vault/ExternalPasswordCommandsTestCase.java
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/security/vault/ExternalPasswordModuleSetupTask.java
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/security/vault/RemoveSecuredAttributeTestCase.java
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/security/vault/VaultDatasourceTestCase.java
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/security/vault/VaultSystemPropertiesTestCase.java
  testsuite/integration/manualmode/src/test/java/org/jboss/as/test/manualmode/security/VaultSystemPropertyOnServerStartTestCase-permissions.xml
  testsuite/integration/manualmode/src/test/java/org/jboss/as/test/manualmode/security/VaultSystemPropertyOnServerStartTestCase.java
  testsuite/integration/rbac/src/test/java/org/jboss/as/test/integration/mgmt/access/AccessConstraintUtilizationTestCase.java
  testsuite/shared/pom.xml
  testsuite/shared/src/main/java/org/jboss/as/test/integration/security/common/BasicVaultServerSetupTask.java
  testsuite/shared/src/main/java/org/jboss/as/test/integration/security/common/VaultHandler.java
Labels: deps-ok

#14354 [WFLY-14876] Upgrade Mail to 1.6.7
  pom.xml
Labels: deps-ok

#14347 [WFLY-14864] Remove "always true" instanceof checks
  ejb3/src/main/java/org/jboss/as/ejb3/component/stateless/StatelessComponentDescription.java
  ejb3/src/main/java/org/jboss/as/ejb3/deployment/processors/MessageDrivenComponentDescriptionFactory.java
  microprofile/opentracing-extension/src/main/java/org/wildfly/extension/microprofile/opentracing/TracingDeploymentProcessor.java
Labels: deps-ok

#14310 [WFLY-14123] Add OSGI Headers for jboss-client.jar
  client/shade/pom.xml
Labels: deps-ok

#14407 WFLY-14946 More efficient way of getting batch job executions by job …
  batch-jberet/src/main/java/org/wildfly/extension/batch/jberet/deployment/BatchJobExecutionResource.java
  batch-jberet/src/main/java/org/wildfly/extension/batch/jberet/deployment/JobOperatorService.java
  batch-jberet/src/main/java/org/wildfly/extension/batch/jberet/deployment/WildFlyJobOperator.java
  batch-jberet/src/main/java/org/wildfly/extension/batch/jberet/job/repository/JobRepositoryService.java
  pom.xml
Labels: deps-ok

#14381 [WFLY-14904]: "WFLYCTL0113: '' is an invalid value for parameter filter" returned when the filter field for listMessages(String) is left empty.
  messaging-activemq/subsystem/src/main/java/org/wildfly/extension/messaging/activemq/BridgeAdd.java
  messaging-activemq/subsystem/src/main/java/org/wildfly/extension/messaging/activemq/CommonAttributes.java
  messaging-activemq/subsystem/src/main/java/org/wildfly/extension/messaging/activemq/DivertAdd.java
  messaging-activemq/subsystem/src/main/java/org/wildfly/extension/messaging/activemq/OperationDefinitionHelper.java
Labels: deps-ok, ready-for-merge

#14423 WFLY-14974 Upgrade Infinispan to 12.1.6.Final
  pom.xml
  testsuite/integration/clustering/pom.xml
Labels: deps-ok, ready-for-merge

#14454 [WFLY-14977] Remove unneccesary number object boxing
  connector/src/main/java/org/jboss/as/connector/deployers/ds/processors/DriverProcessor.java
  ejb3/src/main/java/org/jboss/as/ejb3/remote/EJBClientContextService.java
  ejb3/src/main/java/org/jboss/as/ejb3/subsystem/EJBTransformers.java
  messaging-activemq/subsystem/src/main/java/org/wildfly/extension/messaging/activemq/AddressSettingsResolveHandler.java
  microprofile/metrics-smallrye/src/main/java/org/wildfly/extension/microprofile/metrics/MicroProfileVendorMetricRegistry.java
Labels: deps-ok, ready-for-merge

#14348 [WFLY-14865] XMLXaDataSourceRuntimeHandler related if/else statement …
  connector/src/main/java/org/jboss/as/connector/subsystems/datasources/XMLXaDataSourceRuntimeHandler.java
Labels: deps-ok

#14458 [WFLY-14994] Upgrade WildFly Core 17.0.0.Beta2
  pom.xml
Labels: deps-ok

#14408 [WFLY-14957] Skip the Jakarta transformer if a system property is set.
  ee-9/deployment-transformer/src/main/java/org/wildfly/ee8to9/transformer/DeploymentTransformer.java
Labels: deps-ok, ready-for-merge

#14448 [WFLY-14972] Check emptiness with Collection.isEmpty() (EJB3)
  ejb3/src/main/java/org/jboss/as/ejb3/deployment/processors/EjbIIOPDeploymentUnitProcessor.java
  ejb3/src/main/java/org/jboss/as/ejb3/subsystem/EJBTransformers.java
Labels: deps-ok, ready-for-merge

#14392 [WFLY-14929]: External JMS destination fails to create destination on remote HornetQ broker.
  ee-feature-pack/common/src/main/resources/modules/system/layers/base/org/wildfly/extension/messaging-activemq/main/module.xml
  messaging-activemq/subsystem/src/main/java/org/wildfly/extension/messaging/activemq/jms/DestinationConfiguration.java
  messaging-activemq/subsystem/src/main/java/org/wildfly/extension/messaging/activemq/jms/ExternalJMSQueueService.java
  messaging-activemq/subsystem/src/main/java/org/wildfly/extension/messaging/activemq/jms/ExternalJMSTopicService.java
  messaging-activemq/subsystem/src/main/java/org/wildfly/extension/messaging/activemq/jms/legacy/LegacyConnectionFactoryAdd.java
  messaging-activemq/subsystem/src/main/java/org/wildfly/extension/messaging/activemq/jms/legacy/LegacyConnectionFactoryDefinition.java
Labels: deps-ok, ready-for-merge

#14409 WFLY-5390 Fix ClusteredMessagingTestCase
  testsuite/integration/clustering/pom.xml
  testsuite/integration/clustering/src/test/java/org/jboss/as/test/clustering/cluster/AbstractClusteringTestCase.java
  testsuite/integration/clustering/src/test/java/org/jboss/as/test/clustering/cluster/jms/ClusteredMessagingTestCase.java
Labels: deps-ok, ready-for-merge

#14416 [WFLY-14970]: The management queue password is not properly passed.
  messaging-activemq/subsystem/src/main/java/org/wildfly/extension/messaging/activemq/deployment/JMSDestinationDefinitionInjectionSource.java
Labels: deps-ok, ready-for-merge

#14417 [WFLY-14969]: Routing type is not displayed properly in runtime queues.
  messaging-activemq/subsystem/src/main/java/org/wildfly/extension/messaging/activemq/QueueReadAttributeHandler.java
Labels: deps-ok, ready-for-merge

#14445 [WFLY-14972] Check emptiness with Collection.isEmpty() (JAX-RS)
  jaxrs/src/main/java/org/jboss/as/jaxrs/DeploymentRestResourcesDefintion.java
  jaxrs/src/main/java/org/jboss/as/jaxrs/deployment/JaxrsIntegrationProcessor.java
Labels: deps-ok

#14444 [WF-14978] Upgrade SmallRye OpenApi to 2.1.7
  pom.xml
Labels: deps-ok

#14397 WFLY-14935 Infinispan expiration reaper should be enabled if wakeup interval is > 0
  clustering/infinispan/extension/src/main/java/org/jboss/as/clustering/infinispan/subsystem/ExpirationServiceConfigurator.java
  ee-feature-pack/galleon-common/src/main/resources/feature_groups/infinispan-dist-ejb.xml
  ee-feature-pack/galleon-common/src/main/resources/feature_groups/infinispan-dist-hibernate.xml
  ee-feature-pack/galleon-common/src/main/resources/feature_groups/infinispan-dist-server.xml
  ee-feature-pack/galleon-common/src/main/resources/feature_groups/infinispan-dist-web.xml
  ee-feature-pack/galleon-common/src/main/resources/feature_groups/infinispan-local-ejb.xml
  ee-feature-pack/galleon-common/src/main/resources/feature_groups/infinispan-local-hibernate.xml
  ee-feature-pack/galleon-common/src/main/resources/feature_groups/infinispan-local-server.xml
  ee-feature-pack/galleon-common/src/main/resources/feature_groups/infinispan-local-web.xml
Labels: deps-ok

#14461 [WFLY-14880][WFLY-14998] Bouncycastle upgrade and dep cleanup
  ee-feature-pack/common/pom.xml
  ee-feature-pack/common/src/main/resources/license/ee-feature-pack-common-licenses.xml
  ee-feature-pack/common/src/main/resources/modules/system/layers/base/org/bouncycastle/bcmail/main/module.xml
  testsuite/integration/elytron/pom.xml
  testsuite/integration/elytron/src/test/java/org/wildfly/test/integration/elytron/certs/crl/CertificateRevocationListTestCase.java
  testsuite/integration/elytron/src/test/java/org/wildfly/test/integration/elytron/certs/ocsp/OcspResponderDownTestCase.java
  testsuite/integration/elytron/src/test/java/org/wildfly/test/integration/elytron/certs/ocsp/OcspTestCase.java
Labels: deps-changed

#14357 [WFLY-14880] Upgrade bouncycastle to 1.69 (new transitive dependency)
  ee-feature-pack/common/pom.xml
  ee-feature-pack/common/src/main/resources/modules/system/layers/base/org/bouncycastle/bcmail/main/module.xml
  testsuite/integration/elytron/pom.xml
  testsuite/integration/elytron/src/test/java/org/wildfly/test/integration/elytron/certs/crl/CertificateRevocationListTestCase.java
  testsuite/integration/elytron/src/test/java/org/wildfly/test/integration/elytron/certs/ocsp/OcspResponderDownTestCase.java
  testsuite/integration/elytron/src/test/java/org/wildfly/test/integration/elytron/certs/ocsp/OcspTestCase.java
Labels: hold

#14439 [WFLY-14972] Check emptiness with Collection.isEmpty() (Security)
  security/subsystem/src/main/java/org/jboss/as/security/SecuritySubsystemParser.java
  security/subsystem/src/main/java/org/jboss/as/security/SecuritySubsystemParser_2_0.java
Labels: deps-ok

#14463 [WFLY-14957] Add needed module dep to allow deployment transformer to…
  ee-9/feature-pack/src/main/resources/modules/system/layers/base/org/wildfly/deployment/transformation/main/module.xml
Labels: deps-ok

#14345 WFLY-14862 Session invalidation can leave stale cache entries for non-tx caches if terminated mid expiration
  clustering/web/cache/src/main/java/org/wildfly/clustering/web/cache/session/CompositeSessionFactory.java
  clustering/web/cache/src/test/java/org/wildfly/clustering/web/cache/session/CompositeSessionFactoryTestCase.java
  clustering/web/hotrod/src/main/java/org/wildfly/clustering/web/hotrod/session/HotRodSessionMetaDataFactory.java
  clustering/web/hotrod/src/main/java/org/wildfly/clustering/web/hotrod/session/fine/FineSessionAttributesFactory.java
  clustering/web/infinispan/src/main/java/org/wildfly/clustering/web/infinispan/session/AbstractInfinispanSessionMetaDataFactory.java
  clustering/web/infinispan/src/main/java/org/wildfly/clustering/web/infinispan/session/fine/FineSessionAttributesFactory.java
Labels: 25.x, deps-ok

#14413 [WF-14962] resolve composite indexes for parent deployment units for open api definitions
  microprofile/openapi-smallrye/src/main/java/org/wildfly/extension/microprofile/openapi/deployment/OpenAPIModelServiceConfigurator.java
  testsuite/integration/microprofile/pom.xml
  testsuite/integration/microprofile/src/test/java/org/wildfly/test/integration/microprofile/openapi/OpenAPIMultiModuleDeploymentIndexTestCase.java
  testsuite/integration/microprofile/src/test/java/org/wildfly/test/integration/microprofile/openapi/service/multimodule/TestEjb.java
  testsuite/integration/microprofile/src/test/java/org/wildfly/test/integration/microprofile/openapi/service/multimodule/TestRequest.java
  testsuite/integration/microprofile/src/test/java/org/wildfly/test/integration/microprofile/openapi/service/multimodule/TestResource.java
  testsuite/integration/microprofile/src/test/java/org/wildfly/test/integration/microprofile/openapi/service/multimodule/TestResponse.java
  testsuite/integration/microprofile/src/test/resources/org/wildfly/test/integration/microprofile/openapi/service/multimodule/application.xml
  testsuite/integration/microprofile/src/test/resources/org/wildfly/test/integration/microprofile/openapi/service/multimodule/beans.xml
Labels: deps-ok

#14457 WFLY-14990 Inside EJB remove unnecessary unboxing to clean code
  ejb3/src/main/java/org/jboss/as/ejb3/component/singleton/EJBReadWriteLock.java
  ejb3/src/main/java/org/jboss/as/ejb3/iiop/stub/DynamicIIOPStub.java
  ejb3/src/main/java/org/jboss/as/ejb3/subsystem/EJBTransformers.java
  ejb3/src/main/java/org/jboss/as/ejb3/timerservice/schedule/attribute/DayOfWeek.java
Labels: deps-ok

#14460 [WFLY-14949] Upgrade jakarta.el from 3.0.3.jbossorg-2 to 3.0.3.jbosso…
  pom.xml
Labels: deps-ok

#14466 [WFLY-14809] Add Bouncycastle mail Jakarta version
  ee-9/feature-pack/pom.xml
  ee-9/feature-pack/src/main/resources/license/preview-feature-pack-licenses.xml
  ee-9/feature-pack/src/main/resources/modules/system/layers/base/org/bouncycastle/bcmail/main/module.xml
Labels: deps-ok

#14425 [WFLY-14968] Collapse if-statements (Security)
  security/subsystem/src/main/java/org/jboss/as/security/service/SimpleSecurityManager.java
Labels: deps-ok

#14421 [WFLY-14968] Collapse if-statements (EE)
  ee/src/main/java/org/jboss/as/ee/component/EEApplicationDescription.java
  ee/src/main/java/org/jboss/as/ee/component/ViewDescription.java
  ee/src/main/java/org/jboss/as/ee/component/deployers/AbstractDeploymentDescriptorBindingsProcessor.java
  ee/src/main/java/org/jboss/as/ee/component/deployers/EEModuleNameProcessor.java
  ee/src/main/java/org/jboss/as/ee/component/deployers/EarMessageDestinationProcessor.java
  ee/src/main/java/org/jboss/as/ee/managedbean/processors/ManagedBeanSubDeploymentMarkingProcessor.java
  ee/src/main/java/org/jboss/as/ee/structure/EarStructureProcessor.java
  ee/src/main/java/org/jboss/as/ee/structure/EjbJarDeploymentProcessor.java
  ee/src/main/java/org/jboss/as/ee/subsystem/ManagedExecutorServiceResourceDefinition.java
Labels: deps-ok

#14427 [WFLY-14968] Collapse if-statements (Legacy)
  legacy/web/src/main/java/org/jboss/as/web/WebMigrateOperation.java
  legacy/web/src/main/java/org/jboss/as/web/WebSubsystemParser.java
Labels: deps-ok

#14468 WFLY-14935 Infinispan expiration reaper should be enabled if wakeup interval is > 0
  clustering/infinispan/extension/src/main/java/org/jboss/as/clustering/infinispan/subsystem/ExpirationServiceConfigurator.java
  ee-feature-pack/galleon-common/src/main/resources/feature_groups/infinispan-dist-ejb.xml
  ee-feature-pack/galleon-common/src/main/resources/feature_groups/infinispan-dist-hibernate.xml
  ee-feature-pack/galleon-common/src/main/resources/feature_groups/infinispan-dist-server.xml
  ee-feature-pack/galleon-common/src/main/resources/feature_groups/infinispan-dist-web.xml
  ee-feature-pack/galleon-common/src/main/resources/feature_groups/infinispan-local-ejb.xml
  ee-feature-pack/galleon-common/src/main/resources/feature_groups/infinispan-local-hibernate.xml
  ee-feature-pack/galleon-common/src/main/resources/feature_groups/infinispan-local-server.xml
  ee-feature-pack/galleon-common/src/main/resources/feature_groups/infinispan-local-web.xml
Labels: 24.x

#14419 WFLY-14965 CacheRegistry can leave stale entries after scale down
  clustering/server/src/main/java/org/wildfly/clustering/server/registry/CacheRegistry.java
Labels: deps-ok

#14422 WFLY-14971 Singleton deployment tests still failing intermittently
  clustering/server/src/main/java/org/wildfly/clustering/server/provider/CacheServiceProviderRegistry.java
  clustering/server/src/main/java/org/wildfly/clustering/server/provider/GetLocalServicesCommand.java
  clustering/server/src/main/java/org/wildfly/clustering/server/provider/ServiceProviderRegistrySerializationContextInitializer.java
  clustering/server/src/main/resources/org.wildfly.clustering.server.provider.proto
Labels: deps-ok

#14453 [WFLY-14975] Inappropriate "Collection" key/value issue
  connector/src/main/java/org/jboss/as/connector/util/CopyOnWriteArrayListMultiMap.java
  picketlink/src/main/java/org/wildfly/extension/picketlink/common/model/AbstractResourceDefinition.java
Labels: deps-ok

#14477 [WFLY-14957] Follow up to #14408 to return the correct value for isEn…
  ee-9/deployment-transformer/src/main/java/org/wildfly/ee8to9/transformer/DeploymentTransformer.java
Labels: deps-ok

#14470 [WFLY-14993] Upgrade WildFly HTTP Client to 1.1.8.Final
  pom.xml
Labels: deps-ok

#14474 WFLY-15003 Remove use of deprecated Mockito APIs
  clustering/common/src/test/java/org/jboss/as/clustering/subsystem/ClusteringSubsystemTest.java
  clustering/ee/cache/src/test/java/org/wildfly/clustering/ee/cache/tx/TransactionalBatcherTestCase.java
  clustering/ejb/infinispan/src/test/java/org/wildfly/clustering/ejb/infinispan/group/InfinispanBeanGroupTestCase.java
  clustering/infinispan/extension/src/test/java/org/jboss/as/clustering/infinispan/subsystem/InfinispanSubsystemTestCase.java
  clustering/jgroups/extension/src/test/java/org/jboss/as/clustering/jgroups/subsystem/JGroupsSubsystemTestCase.java
  clustering/singleton/extension/src/test/java/org/wildfly/extension/clustering/singleton/SingletonSubsystemTestCase.java
  clustering/web/cache/src/test/java/org/wildfly/clustering/web/cache/session/CompositeSessionTestCase.java
  clustering/web/cache/src/test/java/org/wildfly/clustering/web/cache/sso/CompositeSSOTestCase.java
  clustering/web/extension/src/test/java/org/wildfly/extension/clustering/web/DistributableWebSubsystemTestCase.java
  clustering/web/infinispan/src/test/java/org/wildfly/clustering/web/infinispan/AffinityIdentifierFactoryTestCase.java
  clustering/web/undertow/src/test/java/org/wildfly/clustering/web/undertow/session/DistributableSessionManagerTestCase.java
  clustering/web/undertow/src/test/java/org/wildfly/clustering/web/undertow/session/UndertowHttpSessionActivationListenerProviderTestCase.java
  clustering/web/undertow/src/test/java/org/wildfly/clustering/web/undertow/session/UndertowHttpSessionFactoryTestCase.java
  clustering/web/undertow/src/test/java/org/wildfly/clustering/web/undertow/sso/DistributableSingleSignOnManagerTestCase.java
  clustering/web/undertow/src/test/java/org/wildfly/clustering/web/undertow/sso/DistributableSingleSignOnTestCase.java
  mod_cluster/extension/src/test/java/org/wildfly/extension/mod_cluster/ModClusterSubsystemTestCase.java
Labels: deps-ok

#14434 [WFLY-14968] Collapse if-statements (Misc)
  appclient/src/main/java/org/jboss/as/appclient/deployment/ApplicationClientDependencyProcessor.java
  datasources-agroal/src/main/java/org/wildfly/extension/datasources/agroal/AgroalTransformers.java
  jsf/subsystem/src/main/java/org/jboss/as/jsf/deployment/JSFMetadataProcessor.java
  jsr77/src/main/java/org/jboss/as/jsr77/managedobject/J2EEDeployedObjectHandlers.java
  microprofile/jwt-smallrye/src/main/java/org/wildfly/extension/microprofile/jwt/smallrye/JwtActivationProcessor.java
  transactions/src/main/java/org/jboss/as/txn/subsystem/TransactionSubsystemRootResourceDefinition.java
  xts/src/main/java/org/jboss/as/xts/txnclient/WildflyTransactionClientTxBridgeIntegrationHandler.java
Labels: deps-ok

#14476 [WFLY-15008] Check null in TracingDeploymentProcessor.close()
  microprofile/opentracing-extension/src/main/java/org/wildfly/extension/microprofile/opentracing/TracingDeploymentProcessor.java
Labels: deps-ok

#14465 WFLY-14991 Inside iiop remove unnecessary unboxing to clean code
  iiop-openjdk/src/main/java/org/wildfly/iiop/openjdk/csiv2/CSIv2IORInterceptor.java
  iiop-openjdk/src/main/java/org/wildfly/iiop/openjdk/csiv2/SASTargetInterceptor.java
  iiop-openjdk/src/main/java/org/wildfly/iiop/openjdk/rmi/Util.java
  iiop-openjdk/src/main/java/org/wildfly/iiop/openjdk/rmi/marshal/CDRStream.java
  iiop-openjdk/src/main/java/org/wildfly/iiop/openjdk/security/SocketFactoryBase.java
Labels: deps-ok

#14429 [WFLY-14968] Collapse if-statements (jax-rs)
  jaxrs/src/main/java/org/jboss/as/jaxrs/deployment/JaxrsIntegrationProcessor.java
  jaxrs/src/main/java/org/jboss/as/jaxrs/deployment/JaxrsMethodParameterProcessor.java
Labels: deps-ok

#14349 [WFLY-14867] Math operands should be cast before assignment
  clustering/infinispan/spi/src/main/java/org/wildfly/clustering/infinispan/spi/persistence/IndexedKeyFormatMapper.java
  connector/src/main/java/org/jboss/as/connector/services/workmanager/StatisticsExecutorImpl.java
  legacy/messaging/src/main/java/org/jboss/as/messaging/MessagingTransformers.java
  undertow/src/main/java/org/wildfly/extension/undertow/WebHostService.java
  undertow/src/main/java/org/wildfly/extension/undertow/handlers/FileHandler.java
Labels: deps-ok

#14433 [WFLY-14968] Collapse if-statements (Weld)
  weld/common/src/main/java/org/jboss/as/weld/util/Reflections.java
  weld/common/src/main/java/org/jboss/as/weld/util/ResourceInjectionUtilities.java
  weld/subsystem/src/main/java/org/jboss/as/weld/deployment/processors/BeanArchiveProcessor.java
Labels: deps-ok

#14479 [WFLY-14957] Correct the default behavior
  ee-9/deployment-transformer/src/main/java/org/wildfly/ee8to9/transformer/DeploymentTransformer.java
Labels: deps-ok

#14480 [24.x] [WFLY-14880] Upgrade Bouncycastle temporary disable tests for CI
  testsuite/integration/elytron/src/test/java/org/wildfly/test/integration/elytron/certs/crl/CertificateRevocationListTestCase.java
  testsuite/integration/elytron/src/test/java/org/wildfly/test/integration/elytron/certs/ocsp/OcspResponderDownTestCase.java
  testsuite/integration/elytron/src/test/java/org/wildfly/test/integration/elytron/certs/ocsp/OcspTestCase.java
Labels: 24.x

#14487 [WFLY-15013] Upgrade netty to 4.1.66
  pom.xml
Labels: deps-ok

#14483 [24.x][WFLY-15034] Upgrade WildFly Core 16.0.1.Final
  pom.xml
Labels: 24.x

#14380 [WFLY-14894] adding admin guide for transactions subsystem
  docs/src/main/asciidoc/_admin-guide/Subsystem_configuration.adoc
  docs/src/main/asciidoc/_admin-guide/subsystem-configuration/Transactions.adoc
  docs/src/main/asciidoc/_developer-guide/Jakarta_Transactions_Reference.adoc
  transactions/src/main/resources/org/jboss/as/txn/subsystem/LocalDescriptions.properties
Labels: deps-ok, ready-for-merge

#14478 [WFLY-15017] Remove unnecessary core-feature-pack licenses files
  servlet-feature-pack/common/src/main/resources/license/core-feature-pack-common-licenses.xml
  servlet-feature-pack/ee-8-api/src/main/resources/license/core-feature-pack-ee-8-api-licenses.xml
Labels: deps-ok

#14455 WFLY-14985 Upgrade smallrye-fault-tolerance to 5.2.1
  microprofile/galleon-common/pom.xml
  microprofile/galleon-common/src/main/resources/license/microprofile-feature-pack-licenses.xml
  microprofile/galleon-common/src/main/resources/modules/system/layers/base/io/smallrye/fault-tolerance/main/module.xml
  pom.xml
Labels: deps-changed

#14420 [WFLY-14968] Collapse if-statements (EJB)
  ejb3/src/main/java/org/jboss/as/ejb3/cache/distributable/DistributableCache.java
  ejb3/src/main/java/org/jboss/as/ejb3/cache/simple/SimpleCache.java
  ejb3/src/main/java/org/jboss/as/ejb3/component/allowedmethods/AllowedMethodsInformation.java
  ejb3/src/main/java/org/jboss/as/ejb3/component/stateful/StatefulSessionComponent.java
  ejb3/src/main/java/org/jboss/as/ejb3/deployment/processors/EjbSuspendInterceptor.java
  ejb3/src/main/java/org/jboss/as/ejb3/deployment/processors/SessionBeanHomeProcessor.java
  ejb3/src/main/java/org/jboss/as/ejb3/deployment/processors/dd/SessionBeanXmlDescriptorProcessor.java
  ejb3/src/main/java/org/jboss/as/ejb3/deployment/processors/merging/AsynchronousMergingProcessor.java
  ejb3/src/main/java/org/jboss/as/ejb3/deployment/processors/merging/EjbDependsOnMergingProcessor.java
  ejb3/src/main/java/org/jboss/as/ejb3/deployment/processors/merging/HomeViewMergingProcessor.java
  ejb3/src/main/java/org/jboss/as/ejb3/deployment/processors/merging/InitMethodMergingProcessor.java
  ejb3/src/main/java/org/jboss/as/ejb3/deployment/processors/merging/MdbDeliveryMergingProcessor.java
  ejb3/src/main/java/org/jboss/as/ejb3/deployment/processors/merging/RunAsMergingProcessor.java
  ejb3/src/main/java/org/jboss/as/ejb3/deployment/processors/merging/StartupMergingProcessor.java
  ejb3/src/main/java/org/jboss/as/ejb3/deployment/processors/merging/TimerMethodMergingProcessor.java
  ejb3/src/main/java/org/jboss/as/ejb3/iiop/EjbCorbaServant.java
  ejb3/src/main/java/org/jboss/as/ejb3/remote/LocalEjbReceiver.java
  ejb3/src/main/java/org/jboss/as/ejb3/security/EJBSecurityViewConfigurator.java
  ejb3/src/main/java/org/jboss/as/ejb3/security/EjbJaccConfigurator.java
  ejb3/src/main/java/org/jboss/as/ejb3/subsystem/AllowedChannelOptionTypesValidator.java
  ejb3/src/main/java/org/jboss/as/ejb3/timerservice/TimerServiceImpl.java
  ejb3/src/main/java/org/jboss/as/ejb3/timerservice/persistence/database/DatabaseTimerPersistence.java
  ejb3/src/main/java/org/jboss/as/ejb3/timerservice/persistence/filestore/FileTimerPersistence.java
  ejb3/src/main/java/org/jboss/as/ejb3/tx/LifecycleCMTTxInterceptor.java
Labels: deps-ok

#14489 WFLY-15037 Update Weld versions for EE 8 and 9 variants.
  ee-9/feature-pack/pom.xml
  pom.xml
Labels: deps-ok

#14482 WFLY-14966 Switch to Jakarta artifacts in batch subsystem and tests
  ee-9/feature-pack/pom.xml
Labels: deps-ok

#14462 [WFLY-14968] Collapse if-statements (Naming)
  naming/src/main/java/org/jboss/as/naming/InMemoryNamingStore.java
  naming/src/main/java/org/jboss/as/naming/ServiceBasedNamingStore.java
Labels: deps-ok

#14450 [WFLY-14972] Check emptiness with Collection.isEmpty() (Connector)
  connector/src/main/java/org/jboss/as/connector/annotations/repository/jandex/JandexAnnotationRepositoryImpl.java
  connector/src/main/java/org/jboss/as/connector/deployers/ds/processors/DsXmlDeploymentInstallProcessor.java
  connector/src/main/java/org/jboss/as/connector/deployers/ra/processors/ParsedRaDeploymentProcessor.java
  connector/src/main/java/org/jboss/as/connector/deployers/ra/processors/RaNativeProcessor.java
  connector/src/main/java/org/jboss/as/connector/metadata/resourceadapter/WorkManagerSecurityImpl.java
  connector/src/main/java/org/jboss/as/connector/services/resourceadapters/IronJacamarActivationResourceService.java
  connector/src/main/java/org/jboss/as/connector/services/resourceadapters/ResourceAdapterActivatorService.java
  connector/src/main/java/org/jboss/as/connector/services/resourceadapters/deployment/ResourceAdapterDeploymentService.java
  connector/src/main/java/org/jboss/as/connector/services/resourceadapters/statistics/AdminObjectStatisticsService.java
  connector/src/main/java/org/jboss/as/connector/services/resourceadapters/statistics/ConnectionDefinitionStatisticsService.java
  connector/src/main/java/org/jboss/as/connector/subsystems/common/pool/PoolOperations.java
  connector/src/main/java/org/jboss/as/connector/subsystems/jca/JcaExtension.java
  connector/src/main/java/org/jboss/as/connector/subsystems/jca/JcaWorkManagerDefinition.java
  connector/src/main/java/org/jboss/as/connector/subsystems/resourceadapters/ResourceAdapterSubsystemParser.java
Labels: deps-ok

#14426 [WFLY-14968] Collapse if-statements (Messaging-ActiveMQ)
  messaging-activemq/subsystem/src/main/java/org/wildfly/extension/messaging/activemq/JGroupsBroadcastGroupAdd.java
  messaging-activemq/subsystem/src/main/java/org/wildfly/extension/messaging/activemq/jms/ConnectionFactoryAttributes.java
  messaging-activemq/subsystem/src/main/java/org/wildfly/extension/messaging/activemq/jms/JMSService.java
  messaging-activemq/subsystem/src/main/java/org/wildfly/extension/messaging/activemq/jms/JMSTopicReadAttributeHandler.java
  messaging-activemq/subsystem/src/main/java/org/wildfly/extension/messaging/activemq/jms/PooledConnectionFactoryStatisticsService.java
Labels: deps-ok

#14438 [WFLY-14972] Check emptiness with Collection.isEmpty() (Transaction)
  transactions/src/main/java/org/jboss/as/txn/deployment/TransactionDependenciesProcessor.java
  transactions/src/main/java/org/jboss/as/txn/subsystem/TransactionSubsystemXMLPersister.java
Labels: deps-ok

#14387 [WFLY-14921] Upgrade ironjacamar to 1.4.38.Final (Project mavenization)
  pom.xml
Labels: deps-ok

#14436 [WFLY-14972] Check emptiness with Collection.isEmpty() (Webservices)
  webservices/server-integration/src/main/java/org/jboss/as/webservices/deployers/WSIntegrationProcessorJAXWS_EJB.java
  webservices/server-integration/src/main/java/org/jboss/as/webservices/deployers/deployment/WSDeploymentBuilder.java
  webservices/server-integration/src/main/java/org/jboss/as/webservices/injection/WSHandlerChainAnnotationProcessor.java
  webservices/server-integration/src/main/java/org/jboss/as/webservices/webserviceref/WSRefDDProcessor.java
Labels: deps-ok

#14435 [WFLY-14972] Check emptiness with Collection.isEmpty() (XTS)
  xts/src/main/java/org/jboss/as/compensations/CompensationsDependenciesDeploymentProcessor.java
  xts/src/main/java/org/jboss/as/xts/XTSDependenciesDeploymentProcessor.java
Labels: deps-ok

#14375 [WFLY-14898] transactions subsystem log-store transactions attributes are read-only
  transactions/src/main/java/org/jboss/as/txn/subsystem/LogStoreTransactionDefinition.java
  transactions/src/main/java/org/jboss/as/txn/subsystem/LogStoreTransactionParticipantDefinition.java
  transactions/src/main/java/org/jboss/as/txn/subsystem/ParticipantWriteAttributeHandler.java
Labels: deps-ok

#14437 [WFLY-14972] Check emptiness with Collection.isEmpty() (Undertow)
  undertow/src/main/java/org/wildfly/extension/undertow/deployment/UndertowDeploymentInfoService.java
  undertow/src/main/java/org/wildfly/extension/undertow/deployment/WarAnnotationDeploymentProcessor.java
  undertow/src/main/java/org/wildfly/extension/undertow/deployment/WarMetaDataProcessor.java
  undertow/src/main/java/org/wildfly/extension/undertow/security/digest/DigestAuthenticationMechanism.java
  undertow/src/main/java/org/wildfly/extension/undertow/security/jacc/WarJACCService.java
Labels: deps-ok

#14481 [24.x][WFLY-14880] Upgrade bouncycastle to 1.69 (new transitive dependency)
  ee-feature-pack/common/pom.xml
  ee-feature-pack/common/src/main/resources/modules/system/layers/base/org/bouncycastle/bcmail/main/module.xml
  testsuite/integration/elytron/pom.xml
Labels: 24.x, core-upgrade-needed

#14490 [WFLY-14809] Add Bouncycastle mail Jakarta version
  ee-9/feature-pack/pom.xml
  ee-9/feature-pack/src/main/resources/license/preview-feature-pack-licenses.xml
  ee-9/feature-pack/src/main/resources/modules/system/layers/base/org/bouncycastle/bcmail/main/module.xml
Labels: 24.x

#14503 [WFLY-15054] Exclude artifacts not used in WF Preview from the featur…
  ee-9/feature-pack/pom.xml
  ee-9/feature-pack/src/main/resources/modules/system/layers/base/org/apache/activemq/artemis/journal/main/module.xml
  ee-9/feature-pack/src/main/resources/modules/system/layers/base/org/apache/activemq/artemis/main/module.xml
  ee-9/feature-pack/src/main/resources/modules/system/layers/base/org/apache/activemq/artemis/ra/main/module.xml
Labels: deps-ok

#14498 [WFLY-15047] EJB (Un)marshaller resource leak
  ejb3/src/main/java/org/jboss/as/ejb3/iiop/EjbCorbaServant.java
  ejb3/src/main/java/org/jboss/as/ejb3/iiop/EjbIIOPService.java
  ejb3/src/main/java/org/jboss/as/ejb3/timerservice/persistence/filestore/EjbTimerXmlParser_1_0.java
  ejb3/src/main/java/org/jboss/as/ejb3/timerservice/persistence/filestore/EjbTimerXmlPersister.java
  ejb3/src/main/java/org/jboss/as/ejb3/timerservice/persistence/filestore/LegacyFileStore.java
Labels: deps-ok

#14497 [WFLY-15015] Package and directory must match
  testsuite/shared/src/main/java/org/wildfly/test/undertow/common/elytron/HttpsListener.java
  testsuite/shared/src/main/java/org/wildfly/test/undertow/common/elytron/SimpleHttpsListener.java
Labels: deps-ok

#14494 WFLY-15043 pom.xml contains duplicate org.jboss.ironjacamar:ironjacamar-common-api dependencies
  pom.xml
Labels: deps-ok

#14499 [WFLY-14956] adding transaction statistics attribute to group
  docs/src/main/asciidoc/_admin-guide/subsystem-configuration/Transactions.adoc
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/transaction/TransactionStatisticsTestCase.java
  testsuite/shared/src/main/java/org/jboss/as/test/integration/transactions/TestXAResource.java
  testsuite/shared/src/main/java/org/jboss/as/test/integration/transactions/TransactionCheckerSingleton.java
  transactions/src/main/java/org/jboss/as/txn/subsystem/CommonAttributes.java
  transactions/src/main/java/org/jboss/as/txn/subsystem/TxStatsHandler.java
Labels: deps-ok

#14486 WFLY-14824 : Upgrade Hibernate ORM to 5.3.21.Final
  pom.xml
Labels: deps-ok

#14442 [WFLY-14972] Check emptiness with Collection.isEmpty() (JPA)
  jpa/hibernate4_1/src/main/java/org/jboss/as/jpa/hibernate4/HibernateAnnotationScanner.java
  jpa/subsystem/src/main/java/org/jboss/as/jpa/container/SFSBCallStack.java
  jpa/subsystem/src/main/java/org/jboss/as/jpa/management/DynamicManagementStatisticsResource.java
  jpa/subsystem/src/main/java/org/jboss/as/jpa/platform/PlatformImpl.java
  jpa/subsystem/src/main/java/org/jboss/as/jpa/processor/HibernateSearchProcessor.java
  jpa/subsystem/src/main/java/org/jboss/as/jpa/processor/PersistenceProviderHandler.java
  jpa/subsystem/src/main/java/org/jboss/as/jpa/processor/PersistenceRefProcessor.java
  jpa/subsystem/src/main/java/org/jboss/as/jpa/processor/PersistenceUnitParseProcessor.java
  jpa/subsystem/src/main/java/org/jboss/as/jpa/processor/PersistenceUnitServiceHandler.java
Labels: deps-ok

#14430 [WFLY-14968] Collapse if-statements (iiop)
  iiop-openjdk/src/main/java/org/wildfly/iiop/openjdk/ConfigValidator.java
  iiop-openjdk/src/main/java/org/wildfly/iiop/openjdk/rmi/ContainerAnalysis.java
  iiop-openjdk/src/main/java/org/wildfly/iiop/openjdk/rmi/RmiIdlUtil.java
  iiop-openjdk/src/main/java/org/wildfly/iiop/openjdk/rmi/Util.java
  iiop-openjdk/src/main/java/org/wildfly/iiop/openjdk/rmi/ValueAnalysis.java
  iiop-openjdk/src/main/java/org/wildfly/iiop/openjdk/rmi/ir/ContainerImplDelegate.java
Labels: deps-ok

#14456 WFLY-14988 Inside clustering remove unnecessary unboxing to clean code
  clustering/common/src/main/java/org/jboss/as/clustering/controller/AddStepHandler.java
  clustering/ee/cache/src/main/java/org/wildfly/clustering/ee/cache/ConcurrentManager.java
  clustering/ee/spi/src/test/java/org/wildfly/clustering/ee/immutable/DefaultImmutabilityTestCase.java
  clustering/infinispan/client/src/main/java/org/wildfly/clustering/infinispan/client/near/SimpleNearCacheFactory.java
  clustering/jgroups/extension/src/main/java/org/jboss/as/clustering/jgroups/subsystem/ProtocolMetricsHandler.java
  clustering/marshalling/api/src/test/java/org/wildfly/clustering/marshalling/MarshallingTester.java
  clustering/marshalling/protostream/src/main/java/org/wildfly/clustering/marshalling/protostream/AnyField.java
  clustering/marshalling/protostream/src/main/java/org/wildfly/clustering/marshalling/protostream/Scalar.java
  clustering/marshalling/protostream/src/main/java/org/wildfly/clustering/marshalling/protostream/util/EnumSetFieldSetMarshaller.java
  clustering/marshalling/spi/src/main/java/org/wildfly/clustering/marshalling/spi/BooleanExternalizer.java
  clustering/marshalling/spi/src/main/java/org/wildfly/clustering/marshalling/spi/util/LinkedHashMapExternalizer.java
  clustering/server/src/main/java/org/wildfly/clustering/server/group/CacheGroup.java
  clustering/server/src/main/java/org/wildfly/clustering/server/singleton/AbstractDistributedSingletonService.java
  clustering/server/src/main/java/org/wildfly/clustering/server/singleton/SingletonElectionCommand.java
  clustering/server/src/main/java/org/wildfly/clustering/server/singleton/SingletonElectionCommandMarshaller.java
  clustering/web/hotrod/src/main/java/org/wildfly/clustering/web/hotrod/session/SessionManagerNearCacheFactory.java
  clustering/web/undertow/src/test/java/org/wildfly/clustering/web/undertow/session/DistributableSessionTestCase.java
Labels: deps-ok

#14506 [WFLY-15056] Upgrade jboss-ejb-client to 4.0.42.Final
  pom.xml
Labels: deps-ok

#14471 WFLY-14989 Inside naming remove unnecessary unboxing to clean code
  naming/src/main/java/org/jboss/as/naming/ExternalContextObjectFactory.java
  naming/src/test/java/org/jboss/as/naming/ServiceBasedNamingStoreTestCase.java
Labels: deps-ok

#14432 [WFLY-14968] Collapse if-statements (Webservices)
  webservices/server-integration/src/main/java/org/jboss/as/webservices/deployers/WSClassVerificationProcessor.java
  webservices/server-integration/src/main/java/org/jboss/as/webservices/metadata/AbstractMetaDataBuilderPOJO.java
  webservices/server-integration/src/main/java/org/jboss/as/webservices/metadata/ContainerMetaDataDeploymentAspect.java
Labels: deps-ok

#14510 WFLY-14847: Clean up licenses
  ee-9/feature-pack/src/main/resources/license/preview-feature-pack-licenses.xml
  ee-feature-pack/common/src/main/resources/content/docs/licenses/apache license 1.1.txt
  ee-feature-pack/common/src/main/resources/content/docs/licenses/bsd 2-clause simplified license.txt
  ee-feature-pack/common/src/main/resources/content/docs/licenses/common development and distribution license 1.0.txt
  ee-feature-pack/common/src/main/resources/content/docs/licenses/gnu general public license, version 2 with the classpath exception.txt
  ee-feature-pack/common/src/main/resources/content/docs/licenses/licenses.xsl
  ee-feature-pack/common/src/main/resources/content/docs/licenses/public domain.txt
  ee-feature-pack/common/src/main/resources/content/docs/licenses/the asm bsd license.txt
  ee-feature-pack/common/src/main/resources/license/ee-feature-pack-common-licenses.xml
  ee-feature-pack/ee-8-api/src/main/resources/license/ee-feature-pack-ee-8-api-licenses.xml
  ee-feature-pack/galleon-common/src/main/resources/packages/docs.licenses.merge/content/docs/licenses/licenses.xsl
  ee-feature-pack/pruned/src/main/resources/license/ee-feature-pack-legacy-licenses.xml
  microprofile/galleon-common/src/main/resources/packages/docs.licenses/content/docs/licenses/gnu lesser general public license v2.1 or later.html
  microprofile/galleon-common/src/main/resources/packages/docs.licenses/content/docs/licenses/licenses.xsl
  servlet-feature-pack/common/src/main/resources/content/docs/licenses/common development and distribution license 1.0.txt
  servlet-feature-pack/common/src/main/resources/content/docs/licenses/gnu general public license v2.0 only.html
  servlet-feature-pack/common/src/main/resources/content/docs/licenses/gnu general public license, version 2 with the classpath exception.txt
  servlet-feature-pack/common/src/main/resources/license/servlet-feature-pack-common-licenses.xml
  servlet-feature-pack/ee-8-api/src/main/resources/license/servlet-feature-pack-ee-8-api-licenses.xml
Labels: deps-ok

#14501 [WFLY-11566] EJB: make a bean class a superclass to a proxy
  ee/src/main/java/org/jboss/as/ee/component/DefaultComponentViewConfigurator.java
Labels: deps-ok

#14431 [WFLY-14968] Collapse if-statements (Connector)
  connector/src/main/java/org/jboss/as/connector/services/datasources/statistics/DataSourceStatisticsService.java
  connector/src/main/java/org/jboss/as/connector/subsystems/resourceadapters/ConnectionDefinitionAdd.java
  connector/src/main/java/org/jboss/as/connector/subsystems/resourceadapters/RaRemove.java
  connector/src/main/java/org/jboss/as/connector/util/Injection.java
  connector/src/main/java/org/jboss/as/connector/util/RaServicesFactory.java
Labels: deps-ok

#14512 [WFLY-15060] Remove leftover dependencies of MP Opentracing from EE FP
  ee-feature-pack/common/pom.xml
  ee-feature-pack/common/src/main/resources/license/ee-feature-pack-common-licenses.xml
  microprofile/galleon-common/pom.xml
  microprofile/galleon-common/src/main/resources/license/microprofile-feature-pack-licenses.xml
  microprofile/galleon-common/src/main/resources/modules/system/layers/base/com/squareup/okhttp3/main/module.xml
Labels: deps-ok

#14516 [WFLY-15042] Upgrade WildFly Core 17.0.0.Beta3
  pom.xml
Labels: deps-ok

#14500 [WFLY-15048] Dynamically determine the expected vendor metric prefix …
  testsuite/integration/microprofile/src/test/java/org/wildfly/test/integration/microprofile/metrics/MetricsHelper.java
  testsuite/integration/microprofile/src/test/java/org/wildfly/test/integration/microprofile/metrics/application/MicroProfileMetricsApplicationTestCase.java
  testsuite/integration/microprofile/src/test/java/org/wildfly/test/integration/microprofile/metrics/rbac/MicroProfileMetricsRbacTestCase.java
Labels: deps-ok

#14514 WFLY-11817 CDI @Resource(lookup=...) processing does not start corresponding binder service
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/ee/injection/resource/infinispan/InfinispanCdiBean.java
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/ee/injection/resource/infinispan/InfinispanCdiTestCase.java
  weld/subsystem/pom.xml
  weld/subsystem/src/main/java/org/jboss/as/weld/injection/ResourceLookupDependenciesProvider.java
Labels: deps-ok, ready-for-merge

#14505 [WFLY-15055] Use javax module alias instead of the jakarta modules on…
  ee-9/feature-pack/src/main/resources/modules/system/layers/base/org/bouncycastle/bcmail/main/module.xml
Labels: deps-ok

#14517 Revert "[WFLY-11566] EJB: make a bean class a superclass to a proxy"
  ee/src/main/java/org/jboss/as/ee/component/DefaultComponentViewConfigurator.java
Labels: deps-ok

#14509 [WFLY-15044] Avoid Nullpointer (Mail)
  mail/src/main/java/org/jboss/as/mail/extension/MailSessionAdd.java
Labels: deps-ok
