Repository wildfly/wildfly, pull requests merged in 2022-07, with the labels that each got.

#15593 [WFLY-16422] Run the VDX testsuite against WildFly Preview
  testsuite/integration/pom.xml
  testsuite/integration/vdx/pom.xml
  testsuite/integration/vdx/src/test/java/org/wildfly/test/integration/vdx/domain/MessagingDomainTestCase.java
  testsuite/integration/vdx/src/test/java/org/wildfly/test/integration/vdx/domain/SmokeDomainTestCase.java
  testsuite/integration/vdx/src/test/java/org/wildfly/test/integration/vdx/standalone/MessagingTestCase.java
  testsuite/integration/vdx/src/test/java/org/wildfly/test/integration/vdx/standalone/SmokeStandaloneTestCase.java
  testsuite/integration/vdx/src/test/resources/configurations/domain/duplicate-attribute.xml
Labels: ready-for-merge, deps-ok

#15684 Standardize the surefire output parameter.
  pom.xml
  testsuite/domain/pom.xml
  testsuite/integration/basic/pom.xml
  testsuite/integration/clustering/pom.xml
  testsuite/integration/microprofile-tck/rest-client/pom.xml
  testsuite/integration/pom.xml
  testsuite/integration/smoke/pom.xml
  testsuite/integration/web/pom.xml
  testsuite/integration/ws/pom.xml
  testsuite/mixed-domain/pom.xml
  testsuite/pom.xml
  testsuite/preview/basic/pom.xml
  testsuite/preview/pom.xml
  testsuite/preview/source-transform/smoke/pom.xml
  testsuite/preview/source-transform/web/pom.xml
  testsuite/scripts/pom.xml
Labels: ready-for-merge, deps-ok

#15691 [WFLY-16290] Tests @Timeout method called with the Oracle database persistent timer
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/ejb/timerservice/database/OracleDatabaseTimerServerSetup.java
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/ejb/timerservice/database/OracleDatabaseTimerServiceTestCase.java
Labels: ready-for-merge, deps-ok

#15704 Fix for WFLY-16544, Upgrade to Galleon plugins 6.0.0.Alpha6
  pom.xml
Labels: ready-for-merge, deps-ok

#15709 [WFLY-16541] remove unnecessary manual stub generation for IBM JDK 11
  testsuite/integration/basic/pom.xml
Labels: ready-for-merge, deps-ok

#15729 [WFLY-16574] Upgrading Jakarta WebSocket to 2.1.0-jbossorg-2 in WildFly Preview
  pom.xml
Labels: ready-for-merge, deps-ok

#15731 [WFLY-16575] Upgrade WildFly Core to 19.0.0.Beta13
  pom.xml
Labels: ready-for-merge, deps-ok

#15727 [WFLY-16572] Disable the Galleon transformer for the WildFly Preview …
  ee-9/build/pom.xml
  ee-9/dist/pom.xml
  ee-9/feature-pack/pom.xml
  pom.xml
  testsuite/domain/pom.xml
  testsuite/integration/basic/pom.xml
  testsuite/integration/clustering/pom.xml
  testsuite/integration/elytron-oidc-client/pom.xml
  testsuite/integration/elytron/pom.xml
  testsuite/integration/microprofile-tck/pom.xml
  testsuite/integration/microprofile/pom.xml
  testsuite/integration/secman/pom.xml
  testsuite/integration/smoke/pom.xml
  testsuite/integration/web/pom.xml
  testsuite/layers/pom.xml
  testsuite/preview/basic/pom.xml
  testsuite/preview/source-transform/smoke/pom.xml
  testsuite/preview/source-transform/web/pom.xml
  testsuite/scripts/pom.xml
Labels: ready-for-merge, big-bang

#15717 [WFLY-16387] Test to demonstrate being able to call the platform mbea…
  testsuite/integration/basic/src/test/java/org/wildfly/test/integration/jmx/rbac/AbstractJmxAccessFromDeploymentWithRbacTest.java
  testsuite/integration/basic/src/test/java/org/wildfly/test/integration/jmx/rbac/JmxAccessFromNonSecuredDeploymentWithRbacUsingUserRoleMapping.java
  testsuite/integration/basic/src/test/java/org/wildfly/test/integration/jmx/rbac/JmxAccessFromSecuredDeploymentWithRbacUsingIdentityRoles.java
  testsuite/integration/basic/src/test/java/org/wildfly/test/integration/jmx/rbac/JmxAccessFromSecuredDeploymentWithRbacUsingUserRoleMapping.java
  testsuite/integration/basic/src/test/java/org/wildfly/test/integration/jmx/rbac/application-roles.properties
  testsuite/integration/basic/src/test/java/org/wildfly/test/integration/jmx/rbac/application-users.properties
  testsuite/integration/basic/src/test/java/org/wildfly/test/integration/jmx/rbac/deployment/ApplicationClass.java
  testsuite/integration/basic/src/test/java/org/wildfly/test/integration/jmx/rbac/deployment/IdentityFilter.java
  testsuite/integration/basic/src/test/java/org/wildfly/test/integration/jmx/rbac/deployment/JmxResource.java
  testsuite/integration/basic/src/test/java/org/wildfly/test/integration/jmx/rbac/jboss-web.xml
  testsuite/integration/basic/src/test/java/org/wildfly/test/integration/jmx/rbac/mgmt-groups.properties
  testsuite/integration/basic/src/test/java/org/wildfly/test/integration/jmx/rbac/mgmt-users.properties
  testsuite/integration/basic/src/test/java/org/wildfly/test/integration/jmx/rbac/web.xml
  testsuite/integration/basic/src/test/resources/org/wildfly/test/integration/jmx/rbac/jboss-deployment-structure.xml
Labels: ready-for-merge, deps-ok, big-bang

#15410 [WFLY-16247]: Dump of Artemis cluster topology is hard to read.
  messaging-activemq/subsystem/src/main/java/org/wildfly/extension/messaging/activemq/ClusterConnectionControlHandler.java
  messaging-activemq/subsystem/src/test/java/org/wildfly/extension/messaging/activemq/ClusterConnectionControlHandlerTest.java
Labels: ready-for-merge, deps-ok

#15718 [WFLY-16556] wildfly-webservices-server-integration is not excluded o…
  ee-9/source-transform/xts/pom.xml
Labels: ready-for-merge, deps-ok, EE10

#15733 Fix for WFLY-16578, Upgrade to Galleon 5.0.3.Final
  pom.xml
Labels: ready-for-merge, deps-ok

#15734 [WFLY-16567] EJB response contains ContextData that has been removed in the server side interceptors
  ejb3/src/main/java/org/jboss/as/ejb3/remote/AssociationImpl.java
Labels: ready-for-merge, deps-ok

#15723 [WFLY-16569] Avoid Jandex 2.4.3.Final deprecated methods
  ee/src/main/java/org/jboss/as/ee/component/deployers/AroundInvokeAnnotationParsingProcessor.java
  ejb3/src/main/java/org/jboss/as/ejb3/deployment/processors/SessionBeanComponentDescriptionFactory.java
  jaxrs/src/main/java/org/jboss/as/jaxrs/deployment/JaxrsMethodParameterProcessor.java
  jaxrs/src/main/java/org/jboss/as/jaxrs/deployment/JaxrsScanningProcessor.java
  rts/src/main/java/org/wildfly/extension/rts/deployment/InboundBridgeDeploymentProcessor.java
  webservices/server-integration/src/main/java/org/jboss/as/webservices/deployers/AbstractIntegrationProcessorJAXWS.java
  webservices/server-integration/src/main/java/org/jboss/as/webservices/deployers/ConfigResolver.java
  webservices/server-integration/src/main/java/org/jboss/as/webservices/deployers/WSClassVerificationProcessor.java
  webservices/server-integration/src/main/java/org/jboss/as/webservices/deployers/WSIntegrationProcessorJAXWS_EJB.java
  webservices/server-integration/src/main/java/org/jboss/as/webservices/injection/WSHandlerChainAnnotationProcessor.java
  webservices/server-integration/src/main/java/org/jboss/as/webservices/util/ASHelper.java
  weld/subsystem/src/main/java/org/jboss/as/weld/deployment/processors/ExternalBeanArchiveProcessor.java
  weld/subsystem/src/main/java/org/jboss/as/weld/discovery/AnnotationType.java
  weld/subsystem/src/main/java/org/jboss/as/weld/discovery/WeldClassFileInfo.java
  weld/subsystem/src/main/java/org/jboss/as/weld/discovery/WeldClassFileServices.java
  xts/src/main/java/org/jboss/as/xts/XTSDependenciesDeploymentProcessor.java
Labels: ready-for-merge

#15737 WFLY-16582 Remove unused org.jboss.ejb.remote.protocol module
  ee-feature-pack/common/src/main/resources/modules/system/layers/base/org/jboss/ejb/remote/protocol/main/module.xml
Labels: ready-for-merge, deps-ok

#15720 [WFLY-16560] Remove the wildfly-servlet feature pack and the servlet-…
  dist/src/verifier/verifications.xml
  ee-9/dist/src/verifier/verifications.xml
  ee-9/feature-pack/pom.xml
  ee-9/galleon-content-microprofile/src/main/resources/feature_groups/domain-ha-profile.xml
  ee-9/galleon-content/src/main/resources/feature_groups/domain-ha-profile.xml
  ee-dist/src/verifier/verifications.xml
  ee-feature-pack/common/src/main/resources/license/ee-feature-pack-common-licenses.xml
  pom.xml
  release/pom.xml
  servlet-build/assembly.xml
  servlet-build/pom.xml
  servlet-build/src/verifier/verifications.xml
  servlet-dist/assembly-src.xml
  servlet-dist/assembly.xml
  servlet-dist/pom.xml
  servlet-dist/src/verifier/verifications.xml
  servlet-feature-pack/galleon-feature-pack/pom.xml
  servlet-feature-pack/galleon-feature-pack/src/main/resources/configs/domain/domain.xml/config.xml
  servlet-feature-pack/galleon-feature-pack/src/main/resources/configs/host/host-primary.xml/config.xml
  servlet-feature-pack/galleon-feature-pack/src/main/resources/configs/host/host-secondary.xml/config.xml
  servlet-feature-pack/galleon-feature-pack/src/main/resources/configs/host/host.xml/config.xml
  servlet-feature-pack/galleon-feature-pack/src/main/resources/configs/standalone/standalone-load-balancer.xml/config.xml
  servlet-feature-pack/galleon-feature-pack/src/main/resources/configs/standalone/standalone.xml/config.xml
  servlet-feature-pack/galleon-feature-pack/src/main/resources/feature_groups/basic-profile.xml
  servlet-feature-pack/galleon-feature-pack/src/main/resources/feature_groups/domain-profile.xml
  servlet-feature-pack/galleon-feature-pack/src/main/resources/feature_groups/host-primary.xml
  servlet-feature-pack/galleon-feature-pack/src/main/resources/feature_groups/host-secondary.xml
  servlet-feature-pack/galleon-feature-pack/src/main/resources/feature_groups/host.xml
  servlet-feature-pack/galleon-feature-pack/src/main/resources/feature_groups/standalone-profile.xml
  servlet-feature-pack/galleon-feature-pack/src/main/resources/feature_groups/standalone-sockets.xml
  servlet-feature-pack/galleon-feature-pack/src/main/resources/packages/docs.licenses/pm/wildfly/tasks.xml
  servlet-feature-pack/galleon-feature-pack/src/main/resources/packages/misc.common/package.xml
  servlet-feature-pack/galleon-feature-pack/src/main/resources/packages/misc.domain/package.xml
  servlet-feature-pack/galleon-feature-pack/src/main/resources/packages/misc.standalone/package.xml
  servlet-feature-pack/galleon-feature-pack/src/main/resources/packages/product.conf/content/bin/product.conf
  servlet-feature-pack/galleon-feature-pack/src/main/resources/packages/product.conf/content/modules/system/layers/base/org/jboss/as/product/wildfly-web/module.xml
  servlet-feature-pack/galleon-feature-pack/src/main/resources/packages/product.conf/package.xml
  servlet-feature-pack/galleon-feature-pack/src/main/resources/packages/product.conf/pm/wildfly/resources/modules/system/layers/base/org/jboss/as/product/wildfly-web/dir/META-INF/MANIFEST.MF
  servlet-feature-pack/galleon-feature-pack/src/main/resources/packages/product.conf/pm/wildfly/tasks.xml
  servlet-feature-pack/galleon-feature-pack/wildfly-feature-pack-build.xml
  servlet-feature-pack/pom.xml
  testsuite/integration/elytron-oidc-client/pom.xml
  testsuite/integration/microprofile-tck/pom.xml
  testsuite/integration/microprofile-tck/reactive-messaging/pom.xml
  testsuite/integration/microprofile-tck/reactive-streams-operators/pom.xml
  testsuite/integration/microprofile-tck/rest-client/pom.xml
  testsuite/integration/microprofile/pom.xml
  testsuite/integration/web/pom.xml
  testsuite/layers/pom.xml
  testsuite/layers/src/test/java/org/jboss/as/test/layers/LayersTestCase.java
Labels: deps-ok

#15721 [WFLY-16527] Faces 4 fails if CDI isn't enabled for the deployment
  ee-feature-pack/galleon-common/src/main/resources/layers/standalone/jsf/layer-spec.xml
  jsf/subsystem/src/main/java/org/jboss/as/jsf/deployment/JSFComponentProcessor.java
  jsf/subsystem/src/main/java/org/jboss/as/jsf/deployment/JSFDependencyProcessor.java
  jsf/subsystem/src/main/java/org/jboss/as/jsf/deployment/JSFVersionProcessor.java
  jsf/subsystem/src/main/java/org/jboss/as/jsf/subsystem/JSFResourceDefinition.java
  jsf/subsystem/src/test/java/org/jboss/as/jsf/subsystem/JSFSubsystemTestCase.java
  testsuite/integration/basic/pom.xml
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/jsf/testurl/ForbiddenUrlTestCase.java
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/jsf/version/JSFDeploymentProcessorTestCase.java
  weld/common/src/main/java/org/jboss/as/weld/WeldCapability.java
  weld/subsystem/src/main/java/org/jboss/as/weld/WeldCapabilityImpl.java
Labels: deps-ok, EE10

#15745 WFLY-16592 Remove duplicate module org.apache.httpcomponents in module.xml
  ee-feature-pack/common/src/main/resources/modules/system/layers/base/org/elasticsearch/client/rest-client/main/module.xml
Labels: ready-for-merge, deps-ok

#15584 WFLY-15968 New implementation of CLIServerSetupTask that can define multiple batches
  testsuite/integration/clustering/src/test/java/org/jboss/as/test/clustering/NodeUtil.java
  testsuite/integration/clustering/src/test/java/org/jboss/as/test/clustering/cluster/AbstractClusteringTestCase.java
  testsuite/integration/clustering/src/test/java/org/jboss/as/test/clustering/cluster/ejb2/stateful/failover/RemoteEJBClientStatefulFailoverTestBase.java
  testsuite/integration/clustering/src/test/java/org/jboss/as/test/clustering/cluster/xsite/XSiteSimpleTestCase.java
  testsuite/shared/src/main/java/org/jboss/as/test/shared/CLIServerSetupTask.java
  testsuite/shared/src/main/java/org/jboss/as/test/shared/ManagementServerSetupTask.java
Labels: ready-for-merge, deps-ok

#15753 [WFLY-16597] Upgrade to JBoss Metadata 15.1.0.Alpha2
  pom.xml
Labels: deps-ok

#15755 [WFLY-16604] Upgrade Batavia to 1.0.15.Final. With this upgrade there…
  ee-9/source-transform/clustering/web/undertow/pom.xml
  ee-9/source-transform/jsf/injection/pom.xml
  ee-9/source-transform/jsf/subsystem/pom.xml
  ee-9/source-transform/microprofile/opentracing-extension/pom.xml
  ee-9/source-transform/microprofile/opentracing-smallrye/pom.xml
  ee-9/source-transform/pom.xml
  ee-9/source-transform/undertow/pom.xml
  testsuite/preview/source-transform/pom.xml
Labels: deps-ok

#15758 [WFLY-16539] Create a WildFly Preview based version of the wildfly-te…
  pom.xml
  testsuite/test-feature-pack-preview/pom.xml
  testsuite/test-feature-pack-preview/wildfly-feature-pack-build.xml
Labels: deps-ok

#15764 [big-bang] This should fix the Galleon Linux failures on big bang
  testsuite/integration/microprofile/pom.xml
Labels: big-bang

#15561 [WFLY-15431] Add elytron-oidc-client to the EE feature pack
  ee-build/src/verifier/verifications.xml
  ee-dist/src/verifier/verifications.xml
  ee-feature-pack/common/src/main/resources/modules/system/layers/base/org/bitbucket/jose4j/main/module.xml
  ee-feature-pack/galleon-common/src/main/resources/feature_groups/domain-host-excludes.xml
  ee-feature-pack/galleon-content/src/main/resources/feature_groups/standalone-full-ha.xml
  ee-feature-pack/galleon-content/src/main/resources/feature_groups/standalone-full.xml
  ee-feature-pack/galleon-content/src/main/resources/feature_groups/standalone-ha.xml
  ee-feature-pack/galleon-content/src/main/resources/feature_groups/standalone-profile.xml
  ee-feature-pack/galleon-content/src/main/resources/feature_groups/standalone.xml
  ee-feature-pack/galleon-feature-pack/pom.xml
  ee-feature-pack/galleon-feature-pack/wildfly-feature-pack-build.xml
  elytron-oidc-client/galleon-common/pom.xml
  elytron-oidc-client/galleon-common/src/main/resources/license/elytron-oidc-feature-pack-licenses.xml
  galleon-pack/galleon-feature-pack/pom.xml
  microprofile/galleon-common/pom.xml
  microprofile/galleon-common/src/main/resources/license/microprofile-feature-pack-licenses.xml
  testsuite/domain/src/test/java/org/jboss/as/test/integration/domain/HostExcludesTestCase.java
Labels: Feature, deps-changed

#15759 [WFLY-16621] Add test utility methods for checking the test environme…
  testsuite/shared/src/main/java/org/jboss/as/test/shared/util/AssumeTestGroupUtil.java
Labels: ready-for-merge, deps-ok

#15725 [WFLY-16527-followup] Unignore test
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/jsf/testurl/ForbiddenUrlTestCase.java
Labels: big-bang

#15765 Sync Main to big-bang
  ee-build/src/verifier/verifications.xml
  ee-dist/src/verifier/verifications.xml
  ee-feature-pack/common/src/main/resources/modules/system/layers/base/io/opentelemetry/trace/main/module.xml
  ee-feature-pack/common/src/main/resources/modules/system/layers/base/org/bitbucket/jose4j/main/module.xml
  ee-feature-pack/galleon-common/src/main/resources/feature_groups/domain-host-excludes.xml
  ee-feature-pack/galleon-content/src/main/resources/feature_groups/standalone-full-ha.xml
  ee-feature-pack/galleon-content/src/main/resources/feature_groups/standalone-full.xml
  ee-feature-pack/galleon-content/src/main/resources/feature_groups/standalone-ha.xml
  ee-feature-pack/galleon-content/src/main/resources/feature_groups/standalone-profile.xml
  ee-feature-pack/galleon-content/src/main/resources/feature_groups/standalone.xml
  ee-feature-pack/galleon-feature-pack/pom.xml
  ee-feature-pack/galleon-feature-pack/wildfly-feature-pack-build.xml
  elytron-oidc-client/galleon-common/pom.xml
  elytron-oidc-client/galleon-common/src/main/resources/license/elytron-oidc-feature-pack-licenses.xml
  galleon-pack/galleon-feature-pack/pom.xml
  microprofile/galleon-common/pom.xml
  microprofile/galleon-common/src/main/resources/license/microprofile-feature-pack-licenses.xml
  testsuite/domain/src/test/java/org/jboss/as/test/integration/domain/HostExcludesTestCase.java
  testsuite/shared/src/main/java/org/jboss/as/test/shared/util/AssumeTestGroupUtil.java
Labels: big-bang

#15767 [WFLY-16609] Convert testsuite/integration/domain to the jakarta.* na…
  testsuite/domain/pom.xml
  testsuite/domain/src/test/java/org/jboss/as/test/integration/domain/JVMServerPropertiesTestCase.java
  testsuite/domain/src/test/java/org/jboss/as/test/integration/domain/TaskSchedulerServletContextListener.java
  testsuite/domain/src/test/java/org/jboss/as/test/integration/domain/management/cli/DeployAllServerGroupsTestCase.java
  testsuite/domain/src/test/java/org/jboss/as/test/integration/domain/management/cli/DeploySingleServerGroupTestCase.java
  testsuite/domain/src/test/java/org/jboss/as/test/integration/domain/management/cli/DomainDeployWithRuntimeNameTestCase.java
  testsuite/domain/src/test/java/org/jboss/as/test/integration/domain/management/cli/DomainDeploymentOverlayTestCase.java
  testsuite/domain/src/test/java/org/jboss/as/test/integration/domain/management/cli/RolloutPlanTestCase.java
  testsuite/domain/src/test/java/org/jboss/as/test/integration/domain/management/cli/RolloutPlanTestServlet.java
  testsuite/domain/src/test/java/org/jboss/as/test/integration/domain/suites/DeploymentOverlayServlet.java
  testsuite/domain/src/test/java/org/jboss/as/test/integration/domain/suites/DeploymentOverlayTestCase.java
  testsuite/domain/src/test/java/org/jboss/as/test/integration/domain/suites/EnvironmentTestServlet.java
  testsuite/domain/src/test/java/org/jboss/as/test/integration/domain/suites/GlobalDirectoryDeployment.java
  testsuite/domain/src/test/java/org/jboss/as/test/integration/domain/suites/GlobalDirectoryDomainTestCase.java
  testsuite/domain/src/test/java/org/jboss/as/test/integration/domain/suites/ModelPersistenceTestCase.java
  testsuite/domain/src/test/java/org/jboss/as/test/integration/domain/suites/ReadEnvironmentVariablesTestCase.java
  testsuite/domain/src/test/java/org/jboss/as/test/integration/domain/util/EENamespaceTransformer.java
  testsuite/domain/src/test/resources/cli/deployment-overlay/override.xml
  testsuite/domain/src/test/resources/cli/deployment-overlay/web.xml
  testsuite/domain/src/test/resources/deploymentoverlay/override.xml
  testsuite/domain/src/test/resources/deploymentoverlay/web.xml
  testsuite/domain/src/test/resources/deploymentoverlay/wildcard-override.xml
Labels: EE10, big-bang

#15752 [WFLY-16596] Proofreading suggestions
  docs/src/main/asciidoc/_elytron/General_Elytron_Architecture.adoc
Labels: ready-for-merge, deps-ok

#15773 [WFLY-16609] Enable the testsuite/integration/domain for all relevant…
  testsuite/domain/pom.xml
  testsuite/domain/src/test/java/org/jboss/as/test/integration/domain/HostExcludesTestCase.java
Labels: EE10, big-bang

#15774 WFLY-16630 Mixed domain tests error traces due to unknown Infinispan module name
  clustering/infinispan/extension/src/main/java/org/jboss/as/clustering/infinispan/subsystem/CacheContainerResourceTransformer.java
  clustering/infinispan/extension/src/test/resources/org/jboss/as/clustering/infinispan/subsystem/subsystem-infinispan-transform-14_0_0.xml
Labels: deps-ok

#15775 Main into big-bang
  docs/src/main/asciidoc/_elytron/General_Elytron_Architecture.adoc
  testsuite/layers/pom.xml
Labels: big-bang

#15772 [WFLY-16631] Fix NoClassDefFoundError: org/jboss/as/process/protocol/StreamUtils stoping mixed domain test hosts
  testsuite/mixed-domain/pom.xml
Labels: ready-for-merge, deps-ok

#15779 [WFLY-16638] Upgrade WildFly Core to 19.0.0.Beta14
  pom.xml
Labels: deps-ok

#15781 [WFLY-16639] Use the correct embedded broker config in WFP's standalo…
  ee-9/galleon-content/src/main/resources/feature_groups/standalone-full-ha.xml
  ee-9/galleon-content/src/main/resources/feature_groups/standalone-full.xml
  testsuite/integration/clustering/pom.xml
Labels: big-bang

#15756 [WFLY-16607] WFLYEJB0275: Could not resolve corresponding ejbCreate or @Init method for home interface
  ejb3/src/main/java/org/jboss/as/ejb3/deployment/processors/SessionBeanHomeProcessor.java
Labels: ready-for-merge, deps-ok

#15782 WFLY-10099 ClusteredJPA2LCTestCase fails intermittently
  testsuite/integration/clustering/src/test/java/org/jboss/as/test/clustering/cluster/jpa/ClusteredJPA2LCTestCase.java
Labels: deps-ok

#15777 [WFLY-16635] Add a wildfly-client-all-jakarta artifact
  .gitignore
  ee-9/common/pom.xml
  ee-9/feature-pack/pom.xml
  ee-9/galleon-content/src/main/resources/packages/tools/pm/wildfly/tasks.xml
  ee-9/pom.xml
  ee-9/source-transform/client/shade/pom.xml
  ee-9/source-transform/pom.xml
Labels: ready-for-merge, deps-ok

#15794 WFLY-16649 Fix regression in execution time of OrderedChildResourcesTestCase
  testsuite/domain/src/test/java/org/jboss/as/test/integration/domain/BuildConfigurationTestBase.java
  testsuite/domain/src/test/java/org/jboss/as/test/integration/domain/DefaultConfigSmokeTestCase.java
  testsuite/domain/src/test/java/org/jboss/as/test/integration/domain/OrderedChildResourcesTestCase.java
Labels: deps-ok

#15788 [WFLY-16645] Upgrade to SmallRye Reactive Messaging 3.18.0
  pom.xml
Labels: ready-for-merge, deps-ok

#15776 [WFLY-16636] Always clean the source-transform modules
  ee-9/source-transform/pom.xml
  testsuite/preview/source-transform/pom.xml
Labels: deps-ok

#15786 [WFLY-16610] Convert testsuite/mixed-domain to the jakarta.* namespace
  testsuite/mixed-domain/pom.xml
  testsuite/mixed-domain/src/test/java/org/jboss/as/test/integration/domain/mixed/MixedDomainDeploymentTest.java
  testsuite/mixed-domain/src/test/java/org/jboss/as/test/integration/domain/mixed/eap740/LegacyConfig740TestSuite.java
  testsuite/mixed-domain/src/test/java/org/jboss/as/test/integration/domain/mixed/jsf/Bean.java
  testsuite/mixed-domain/src/test/resources/jsf-test/WEB-INF/beans.xml
  testsuite/mixed-domain/src/test/resources/jsf-test/WEB-INF/faces-config.xml
  testsuite/mixed-domain/src/test/resources/jsf-test/home.xhtml
  testsuite/mixed-domain/src/test/resources/jsf-test/index.html
Labels: EE10, big-bang

#15796 [WFLT-16600] Convert the secman testsuite to the jakarta.* namespace.
  testsuite/integration/secman/pom.xml
  testsuite/integration/secman/src/test/java/org/jboss/as/testsuite/integration/secman/ejbs/ReadSystemPropertyBean.java
  testsuite/integration/secman/src/test/java/org/jboss/as/testsuite/integration/secman/propertypermission/AbstractPPTestsWithJSP.java
  testsuite/integration/secman/src/test/java/org/jboss/as/testsuite/integration/secman/propertypermission/AbstractPPTestsWithLibrary.java
  testsuite/integration/secman/src/test/java/org/jboss/as/testsuite/integration/secman/propertypermission/AbstractPropertyPermissionTests.java
  testsuite/integration/secman/src/test/java/org/jboss/as/testsuite/integration/secman/propertypermission/EarModulesPPTestCase.java
  testsuite/integration/secman/src/test/java/org/jboss/as/testsuite/integration/secman/propertypermission/PropertyPermissionExpressionsTestCase.java
  testsuite/integration/secman/src/test/java/org/jboss/as/testsuite/integration/secman/propertypermission/WarPPTestCase.java
  testsuite/integration/secman/src/test/java/org/jboss/as/testsuite/integration/secman/servlets/CallPermissionUtilServlet.java
  testsuite/integration/secman/src/test/java/org/jboss/as/testsuite/integration/secman/servlets/ForwardServlet.java
  testsuite/integration/secman/src/test/java/org/jboss/as/testsuite/integration/secman/servlets/JSMCheckServlet.java
  testsuite/integration/secman/src/test/java/org/jboss/as/testsuite/integration/secman/servlets/PrintSystemPropertyServlet.java
  testsuite/integration/secman/src/test/java/org/jboss/as/testsuite/integration/secman/subsystem/MaximumPermissionsTestCase.java
  testsuite/integration/secman/src/test/java/org/jboss/as/testsuite/integration/secman/subsystem/MinimumPermissionsTestCase.java
Labels: big-bang

#15793 [WFLY-16616] Convert testsuite/integration/multinode to the jakarta.*…
  testsuite/integration/multinode/pom.xml
  testsuite/integration/multinode/src/test/java/org/jboss/as/test/multinode/batch/stoprestart/BatchClientBean.java
  testsuite/integration/multinode/src/test/java/org/jboss/as/test/multinode/batch/stoprestart/BatchClientIF.java
  testsuite/integration/multinode/src/test/java/org/jboss/as/test/multinode/batch/stoprestart/Batchlet1.java
  testsuite/integration/multinode/src/test/java/org/jboss/as/test/multinode/batch/stoprestart/StopFromDifferentNodeTestCase.java
  testsuite/integration/multinode/src/test/java/org/jboss/as/test/multinode/clientinterceptor/StatelessBean.java
  testsuite/integration/multinode/src/test/java/org/jboss/as/test/multinode/clientinterceptor/secured/SecuredBean.java
  testsuite/integration/multinode/src/test/java/org/jboss/as/test/multinode/clientinterceptor/secured/SecuredBeanClientInterceptorTestCase.java
  testsuite/integration/multinode/src/test/java/org/jboss/as/test/multinode/ejb/http/StatelessBean.java
  testsuite/integration/multinode/src/test/java/org/jboss/as/test/multinode/ejb/http/StatelessLocal.java
  testsuite/integration/multinode/src/test/java/org/jboss/as/test/multinode/ejb/http/StatelessRemote.java
  testsuite/integration/multinode/src/test/java/org/jboss/as/test/multinode/ejb/timer/database/CollectionSingleton.java
  testsuite/integration/multinode/src/test/java/org/jboss/as/test/multinode/ejb/timer/database/Collector.java
  testsuite/integration/multinode/src/test/java/org/jboss/as/test/multinode/ejb/timer/database/RefreshBean1.java
  testsuite/integration/multinode/src/test/java/org/jboss/as/test/multinode/ejb/timer/database/RefreshBean2.java
  testsuite/integration/multinode/src/test/java/org/jboss/as/test/multinode/ejb/timer/database/RefreshBeanBase.java
  testsuite/integration/multinode/src/test/java/org/jboss/as/test/multinode/ejb/timer/database/RefreshIF.java
  testsuite/integration/multinode/src/test/java/org/jboss/as/test/multinode/ejb/timer/database/RefreshInterceptor.java
  testsuite/integration/multinode/src/test/java/org/jboss/as/test/multinode/ejb/timer/database/RemoteTimedBean.java
  testsuite/integration/multinode/src/test/java/org/jboss/as/test/multinode/ejb/timer/database/StartupSingleton.java
  testsuite/integration/multinode/src/test/java/org/jboss/as/test/multinode/ejb/timer/database/TimedObjectTimerServiceBean.java
  testsuite/integration/multinode/src/test/java/org/jboss/as/test/multinode/remotecall/RemoteLocalCallProfileTestCase.java
  testsuite/integration/multinode/src/test/java/org/jboss/as/test/multinode/remotecall/RemoteLocalCallTestCase.java
  testsuite/integration/multinode/src/test/java/org/jboss/as/test/multinode/remotecall/StatefulBean.java
  testsuite/integration/multinode/src/test/java/org/jboss/as/test/multinode/remotecall/StatefulLocal.java
  testsuite/integration/multinode/src/test/java/org/jboss/as/test/multinode/remotecall/StatefulLocalHome.java
  testsuite/integration/multinode/src/test/java/org/jboss/as/test/multinode/remotecall/StatefulRemote.java
  testsuite/integration/multinode/src/test/java/org/jboss/as/test/multinode/remotecall/StatefulRemoteHome.java
  testsuite/integration/multinode/src/test/java/org/jboss/as/test/multinode/remotecall/StatelessBean.java
  testsuite/integration/multinode/src/test/java/org/jboss/as/test/multinode/remotecall/StatelessLocal.java
  testsuite/integration/multinode/src/test/java/org/jboss/as/test/multinode/remotecall/StatelessLocalHome.java
  testsuite/integration/multinode/src/test/java/org/jboss/as/test/multinode/remotecall/StatelessRemote.java
  testsuite/integration/multinode/src/test/java/org/jboss/as/test/multinode/remotecall/StatelessRemoteHome.java
  testsuite/integration/multinode/src/test/java/org/jboss/as/test/multinode/remotecall/scoped/context/StatefulBeanA.java
  testsuite/integration/multinode/src/test/java/org/jboss/as/test/multinode/remotecall/scoped/context/StatefulBeanOnOtherServer.java
  testsuite/integration/multinode/src/test/java/org/jboss/as/test/multinode/remotecall/scoped/context/StatefulRemoteHomeForBeanOnOtherServer.java
  testsuite/integration/multinode/src/test/java/org/jboss/as/test/multinode/remotecall/scoped/context/StatelessBeanOnOtherServer.java
  testsuite/integration/multinode/src/test/java/org/jboss/as/test/multinode/transaction/ClientEjb.java
  testsuite/integration/multinode/src/test/java/org/jboss/as/test/multinode/transaction/TransactionInvocationTestCase.java
  testsuite/integration/multinode/src/test/java/org/jboss/as/test/multinode/transaction/TransactionalStatefulBean.java
  testsuite/integration/multinode/src/test/java/org/jboss/as/test/multinode/transaction/TransactionalStatelessBean.java
  testsuite/integration/multinode/src/test/java/org/jboss/as/test/multinode/transaction/async/ClientBean.java
  testsuite/integration/multinode/src/test/java/org/jboss/as/test/multinode/transaction/async/TransactionalMandatory.java
  testsuite/integration/multinode/src/test/java/org/jboss/as/test/multinode/transaction/async/TransactionalRemote.java
  testsuite/integration/multinode/src/test/java/org/jboss/as/test/multinode/transaction/async/TransactionalStatusByManager.java
  testsuite/integration/multinode/src/test/java/org/jboss/as/test/multinode/transaction/async/TransactionalStatusByRegistry.java
  testsuite/integration/multinode/src/test/java/org/jboss/as/test/multinode/transaction/nooutbound/ClientStatelessBean.java
  testsuite/integration/multinode/src/test/java/org/jboss/as/test/multinode/transaction/nooutbound/ServerMandatoryStatelessBean.java
  testsuite/integration/multinode/src/test/java/org/jboss/as/test/multinode/transaction/nooutbound/ServerNeverStatelessBean.java
  testsuite/integration/multinode/src/test/java/org/jboss/as/test/multinode/transaction/nooutbound/TransactionContextRemoteCallTestCase.java
Labels: EE10, big-bang

#15804 [WFLY-16599] Convert the elytron-oidc-client testsuite to the jakarta* namespace.
  testsuite/integration/elytron-oidc-client/pom.xml
Labels: big-bang

#15805 [WFLY-16655] Add secman back into the modules to run for -Dts.ee9
  testsuite/integration/pom.xml
  testsuite/integration/secman/pom.xml
Labels: big-bang

#15803 WFLY-16654 Upgrade smallrye-fault-tolerance to 6.0.0-RC4
  pom.xml
Labels: deps-ok

#15798 WFLY-16647 Upgrade smallrye-fault-tolerance to 5.5.0
  pom.xml
Labels: deps-ok

#15791 [WFLY-16387] Convert the test resources to use Jakarta REST 3.1. Also…
  testsuite/integration/basic/pom.xml
  testsuite/integration/basic/src/test/java/org/wildfly/test/integration/jmx/rbac/AbstractJmxAccessFromDeploymentWithRbacTest.java
  testsuite/integration/basic/src/test/java/org/wildfly/test/integration/jmx/rbac/JmxAccessFromNonSecuredDeploymentWithRbacUsingUserRoleMappingTestCase.java
  testsuite/integration/basic/src/test/java/org/wildfly/test/integration/jmx/rbac/JmxAccessFromSecuredDeploymentWithRbacUsingIdentityRolesTestCase.java
  testsuite/integration/basic/src/test/java/org/wildfly/test/integration/jmx/rbac/JmxAccessFromSecuredDeploymentWithRbacUsingUserRoleMappingTestCase.java
  testsuite/integration/basic/src/test/java/org/wildfly/test/integration/jmx/rbac/deployment/ApplicationClass.java
  testsuite/integration/basic/src/test/java/org/wildfly/test/integration/jmx/rbac/deployment/JmxResource.java
  testsuite/integration/basic/src/test/resources/org/wildfly/test/integration/jmx/rbac/jboss-deployment-structure.xml
Labels: big-bang

#15787 [WFLY-16615] Move MP TCKs to test against preview/jakarta.*
  pom.xml
  testsuite/integration/microprofile-tck/config/pom.xml
  testsuite/integration/microprofile-tck/config/src/test/java/org/wildfly/extension/microprofile/config/test/WildFlyDeploymentExceptionTransformer.java
  testsuite/integration/microprofile-tck/config/src/test/javax/java/org/wildfly/extension/microprofile/config/test/WildFlyDeploymentExceptionTransformer.java
  testsuite/integration/microprofile-tck/config/src/test/resources/configure-weld-subsystem.cli
  testsuite/integration/microprofile-tck/fault-tolerance/pom.xml
  testsuite/integration/microprofile-tck/fault-tolerance/src/test/java/org/wildfly/extension/microprofile/faulttolerance/tck/CleanupMetricRegistries.java
  testsuite/integration/microprofile-tck/fault-tolerance/src/test/javax/java/org/wildfly/extension/microprofile/faulttolerance/tck/CleanupMetricRegistries.java
  testsuite/integration/microprofile-tck/health/pom.xml
  testsuite/integration/microprofile-tck/jwt/pom.xml
  testsuite/integration/microprofile-tck/metrics/pom.xml
  testsuite/integration/microprofile-tck/metrics/src/test/resources/configure-weld-subsystem.cli
  testsuite/integration/microprofile-tck/openapi/pom.xml
  testsuite/integration/microprofile-tck/opentracing/pom.xml
  testsuite/integration/microprofile-tck/opentracing/src/test/java/io/smallrye/opentracing/ExceptionMapper.java
  testsuite/integration/microprofile-tck/opentracing/src/test/java/io/smallrye/opentracing/MockTracerResolver.java
  testsuite/integration/microprofile-tck/opentracing/src/test/java/io/smallrye/opentracing/ResteasyClientTracingRegistrarProvider.java
  testsuite/integration/microprofile-tck/opentracing/src/test/java/io/smallrye/opentracing/arquillian/DeploymentProcessor.java
  testsuite/integration/microprofile-tck/opentracing/src/test/javax/java/io/smallrye/opentracing/ExceptionMapper.java
  testsuite/integration/microprofile-tck/opentracing/src/test/javax/java/io/smallrye/opentracing/MockTracerResolver.java
  testsuite/integration/microprofile-tck/opentracing/src/test/javax/java/io/smallrye/opentracing/ResteasyClientTracingRegistrarProvider.java
  testsuite/integration/microprofile-tck/opentracing/src/test/javax/java/io/smallrye/opentracing/arquillian/DeploymentProcessor.java
  testsuite/integration/microprofile-tck/pom.xml
  testsuite/integration/microprofile-tck/reactive-messaging/pom.xml
  testsuite/integration/microprofile-tck/reactive-messaging/src/test/java/org/wildfly/test/integration/mp/tck/reactive/messaging/WildFlyDeploymentExceptionTransformer.java
  testsuite/integration/microprofile-tck/reactive-messaging/src/test/javax/java/org/wildfly/test/integration/mp/tck/reactive/messaging/WildFlyDeploymentExceptionTransformer.java
  testsuite/integration/microprofile-tck/reactive-messaging/src/test/resources/configure-weld-subsystem.cli
  testsuite/integration/microprofile-tck/reactive-streams-operators/pom.xml
  testsuite/integration/microprofile-tck/rest-client/pom.xml
Labels: big-bang

#15812 [WFLY-16613] Migrate the RBAC integration tests.
  testsuite/integration/pom.xml
  testsuite/integration/rbac/pom.xml
Labels: big-bang

#15818 [WFLY-16662] Upgrade keycloak version to 17.0.1
  pom.xml
Labels: deps-ok

#15820 Only include the testsuite/test-feature-pack-preview module if -Dskip…
  pom.xml
Labels: deps-ok

#15715 [WFLY-16554] Increase JVM heap max-size to 100m for JVMServerPropertiesTestCase
  testsuite/domain/src/test/resources/domain-configs/domain-jvm-properties.xml
  testsuite/domain/src/test/resources/domain-configs/domain-standard-ee.xml
  testsuite/domain/src/test/resources/domain-configs/domain-standard.xml
Labels: deps-ok

#15819 [WFLY-16618] Migrate the XTS testsuite for Jakarta EE 10.
  testsuite/integration/xts/pom.xml
  testsuite/integration/xts/src/test/java/org/jboss/as/test/txbridge/fromjta/BridgeFromJTATestCase.java
  testsuite/integration/xts/src/test/java/org/jboss/as/test/txbridge/fromjta/FirstClient.java
  testsuite/integration/xts/src/test/java/org/jboss/as/test/txbridge/fromjta/service/FirstCounterEntity.java
  testsuite/integration/xts/src/test/java/org/jboss/as/test/txbridge/fromjta/service/FirstServiceAT.java
  testsuite/integration/xts/src/test/java/org/jboss/as/test/txbridge/fromjta/service/FirstServiceATImpl.java
  testsuite/integration/xts/src/test/java/org/jboss/as/test/txbridge/fromjta/service/FirstServiceATService.java
  testsuite/integration/xts/src/test/java/org/jboss/as/test/xts/annotation/client/CompensatableClient.java
  testsuite/integration/xts/src/test/java/org/jboss/as/test/xts/annotation/client/CompensatableTestCase.java
  testsuite/integration/xts/src/test/java/org/jboss/as/test/xts/annotation/client/TransactionalClient.java
  testsuite/integration/xts/src/test/java/org/jboss/as/test/xts/annotation/client/TransactionalTestCase.java
  testsuite/integration/xts/src/test/java/org/jboss/as/test/xts/annotation/compensationscoped/CompensationScopedTestCase.java
  testsuite/integration/xts/src/test/java/org/jboss/as/test/xts/annotation/service/CompensatableService.java
  testsuite/integration/xts/src/test/java/org/jboss/as/test/xts/annotation/service/CompensatableServiceImpl.java
  testsuite/integration/xts/src/test/java/org/jboss/as/test/xts/annotation/service/TransactionalService.java
  testsuite/integration/xts/src/test/java/org/jboss/as/test/xts/annotation/service/TransactionalServiceImpl.java
  testsuite/integration/xts/src/test/java/org/jboss/as/test/xts/base/BaseFunctionalTest.java
  testsuite/integration/xts/src/test/java/org/jboss/as/test/xts/suspend/ExecutorService.java
  testsuite/integration/xts/src/test/java/org/jboss/as/test/xts/suspend/Helpers.java
  testsuite/integration/xts/src/test/java/org/jboss/as/test/xts/suspend/RemoteService.java
  testsuite/integration/xts/src/test/java/org/jboss/as/test/xts/suspend/wsat/AtomicTransactionExecutionService.java
  testsuite/integration/xts/src/test/java/org/jboss/as/test/xts/suspend/wsat/AtomicTransactionRemoteService.java
  testsuite/integration/xts/src/test/java/org/jboss/as/test/xts/suspend/wsat/AtomicTransactionSuspendTestCase.java
  testsuite/integration/xts/src/test/java/org/jboss/as/test/xts/suspend/wsba/BusinessActivityExecutionService.java
  testsuite/integration/xts/src/test/java/org/jboss/as/test/xts/suspend/wsba/BusinessActivityRemoteService.java
  testsuite/integration/xts/src/test/java/org/jboss/as/test/xts/suspend/wsba/BusinessActivitySuspendTestCase.java
  testsuite/integration/xts/src/test/java/org/jboss/as/test/xts/util/DeploymentHelper.java
  testsuite/integration/xts/src/test/java/org/jboss/as/test/xts/util/EventLog.java
  testsuite/integration/xts/src/test/java/org/jboss/as/test/xts/wsat/client/ATClient.java
  testsuite/integration/xts/src/test/java/org/jboss/as/test/xts/wsat/client/ATTestCase.java
  testsuite/integration/xts/src/test/java/org/jboss/as/test/xts/wsat/service/AT.java
  testsuite/integration/xts/src/test/java/org/jboss/as/test/xts/wsat/service/ATService1.java
  testsuite/integration/xts/src/test/java/org/jboss/as/test/xts/wsat/service/ATService2.java
  testsuite/integration/xts/src/test/java/org/jboss/as/test/xts/wsat/service/ATService3.java
  testsuite/integration/xts/src/test/java/org/jboss/as/test/xts/wsat/service/ATSuperService.java
  testsuite/integration/xts/src/test/java/org/jboss/as/test/xts/wsba/coordinatorcompletion/client/BACoordinatorCompletionClient.java
  testsuite/integration/xts/src/test/java/org/jboss/as/test/xts/wsba/coordinatorcompletion/client/BACoordinatorCompletionTestCase.java
  testsuite/integration/xts/src/test/java/org/jboss/as/test/xts/wsba/coordinatorcompletion/service/BACoordinatorCompletion.java
  testsuite/integration/xts/src/test/java/org/jboss/as/test/xts/wsba/coordinatorcompletion/service/BACoordinatorCompletionService1.java
  testsuite/integration/xts/src/test/java/org/jboss/as/test/xts/wsba/coordinatorcompletion/service/BACoordinatorCompletionService2.java
  testsuite/integration/xts/src/test/java/org/jboss/as/test/xts/wsba/coordinatorcompletion/service/BACoordinatorCompletionService3.java
  testsuite/integration/xts/src/test/java/org/jboss/as/test/xts/wsba/coordinatorcompletion/service/BACoordinatorCompletionSuperService.java
  testsuite/integration/xts/src/test/java/org/jboss/as/test/xts/wsba/participantcompletion/client/BAParticipantCompletionClient.java
  testsuite/integration/xts/src/test/java/org/jboss/as/test/xts/wsba/participantcompletion/client/BAParticipantCompletionTestCase.java
  testsuite/integration/xts/src/test/java/org/jboss/as/test/xts/wsba/participantcompletion/service/BAParticipantCompletion.java
  testsuite/integration/xts/src/test/java/org/jboss/as/test/xts/wsba/participantcompletion/service/BAParticipantCompletionService1.java
  testsuite/integration/xts/src/test/java/org/jboss/as/test/xts/wsba/participantcompletion/service/BAParticipantCompletionService2.java
  testsuite/integration/xts/src/test/java/org/jboss/as/test/xts/wsba/participantcompletion/service/BAParticipantCompletionService3.java
  testsuite/integration/xts/src/test/java/org/jboss/as/test/xts/wsba/participantcompletion/service/BAParticipantCompletionSuperService.java
Labels: big-bang

#15830 [WFLY-15685] Sync ResourceDefinitionInjectionSource; fix subclassing …
  ee/src/main/java/org/jboss/as/ee/resource/definition/ResourceDefinitionInjectionSource.java
  messaging-activemq/subsystem/src/main/java/org/wildfly/extension/messaging/activemq/deployment/JMSDestinationDefinitionInjectionSource.java
Labels: Blocker, deps-ok

#15831 [big-bang][WFLY-15685] Sync ResourceDefinitionInjectionSource; fix subclassing issue
  ee/src/main/java/org/jboss/as/ee/resource/definition/ResourceDefinitionInjectionSource.java
  messaging-activemq/subsystem/src/main/java/org/wildfly/extension/messaging/activemq/deployment/JMSDestinationDefinitionInjectionSource.java
Labels: Blocker, big-bang

#15834 WFLY-16674/WFLY-16675 Upgrade smallrye-open-api to 2.1.22/3.0.0-CR2
  pom.xml
Labels: deps-ok

#15835 WFLY-16669: Upgrade HAL to 3.6.2.Final
  pom.xml
Labels: deps-ok

#15844 Main into big bang
  pom.xml
Labels: big-bang

#15850 [WFLY-16697][WFLY-16698] Smallrye upgrades
  pom.xml
Labels: deps-ok

#15853 [WFLY-16682] remove ee-8-api modules
  boms/standard-ee/pom.xml
  ee-feature-pack/common/pom.xml
  ee-feature-pack/ee-8-api/assembly.xml
  ee-feature-pack/ee-8-api/pom.xml
  ee-feature-pack/ee-8-api/src/main/resources/license/ee-feature-pack-ee-8-api-licenses.xml
  ee-feature-pack/ee-8-api/src/main/resources/modules/system/layers/base/javax/batch/api/main/module.xml
  ee-feature-pack/ee-8-api/src/main/resources/modules/system/layers/base/javax/ejb/api/main/module.xml
  ee-feature-pack/ee-8-api/src/main/resources/modules/system/layers/base/javax/faces/api/main/module.xml
  ee-feature-pack/ee-8-api/src/main/resources/modules/system/layers/base/javax/jms/api/main/module.xml
  ee-feature-pack/ee-8-api/src/main/resources/modules/system/layers/base/javax/jws/api/main/module.xml
  ee-feature-pack/ee-8-api/src/main/resources/modules/system/layers/base/javax/mail/api/main/module.xml
  ee-feature-pack/ee-8-api/src/main/resources/modules/system/layers/base/javax/persistence/api/main/module.xml
  ee-feature-pack/ee-8-api/src/main/resources/modules/system/layers/base/javax/resource/api/main/module.xml
  ee-feature-pack/ee-8-api/src/main/resources/modules/system/layers/base/javax/security/enterprise/api/main/module.xml
  ee-feature-pack/ee-8-api/src/main/resources/modules/system/layers/base/javax/ws/rs/api/main/module.xml
  ee-feature-pack/ee-8-api/src/main/resources/modules/system/layers/base/javax/xml/soap/api/main/module.xml
  ee-feature-pack/ee-8-api/src/main/resources/modules/system/layers/base/javax/xml/ws/api/main/module.xml
  ee-feature-pack/pom.xml
  pom.xml
  servlet-feature-pack/ee-8-api/assembly.xml
  servlet-feature-pack/ee-8-api/pom.xml
  servlet-feature-pack/ee-8-api/src/main/resources/license/servlet-feature-pack-ee-8-api-licenses.xml
  servlet-feature-pack/ee-8-api/src/main/resources/modules/system/layers/base/javax/activation/api/main/module.xml
  servlet-feature-pack/ee-8-api/src/main/resources/modules/system/layers/base/javax/annotation/api/main/module.xml
  servlet-feature-pack/ee-8-api/src/main/resources/modules/system/layers/base/javax/el/api/main/module.xml
  servlet-feature-pack/ee-8-api/src/main/resources/modules/system/layers/base/javax/enterprise/api/main/module.xml
  servlet-feature-pack/ee-8-api/src/main/resources/modules/system/layers/base/javax/enterprise/concurrent/api/main/module.xml
  servlet-feature-pack/ee-8-api/src/main/resources/modules/system/layers/base/javax/inject/api/main/module.xml
  servlet-feature-pack/ee-8-api/src/main/resources/modules/system/layers/base/javax/json/bind/api/main/module.xml
  servlet-feature-pack/ee-8-api/src/main/resources/modules/system/layers/base/javax/servlet/api/main/module.xml
  servlet-feature-pack/ee-8-api/src/main/resources/modules/system/layers/base/javax/servlet/jsp/api/main/module.xml
  servlet-feature-pack/ee-8-api/src/main/resources/modules/system/layers/base/javax/servlet/jstl/api/main/module.xml
  servlet-feature-pack/ee-8-api/src/main/resources/modules/system/layers/base/javax/transaction/api/main/module.xml
  servlet-feature-pack/ee-8-api/src/main/resources/modules/system/layers/base/javax/validation/api/main/module.xml
  servlet-feature-pack/ee-8-api/src/main/resources/modules/system/layers/base/javax/websocket/api/main/module.xml
  servlet-feature-pack/pom.xml
Labels: deps-ok

#15836 WFLY-16689 Add default container configuration support to ManagementServerSetupTask
  testsuite/shared/src/main/java/org/jboss/as/test/shared/ManagementServerSetupTask.java
Labels: deps-ok

#15856 [WFLY-16690] Upgrade RESTEasy to 6.1.0.Beta3.
  pom.xml
Labels: deps-ok

#15828 WFLY-16666 Do not use component class as superclass for local home interface proxy
  ejb3/src/main/java/org/jboss/as/ejb3/component/EJBViewDescription.java
Labels: deps-ok, Critical

#15854 WFLY-16666 Do not use component class as superclass for local home in…
  ejb3/src/main/java/org/jboss/as/ejb3/component/EJBViewDescription.java
Labels: 26.x

#15852 [WFLY-16710] Remove the org.javassist and internal.jakarta.transactio…
  ee-feature-pack/common/pom.xml
  ee-feature-pack/common/src/main/resources/license/ee-feature-pack-common-licenses.xml
  ee-feature-pack/common/src/main/resources/modules/system/layers/base/internal/jakarta/transaction/api/main/module.xml
  ee-feature-pack/common/src/main/resources/modules/system/layers/base/org/javassist/main/module.xml
  pom.xml
  testsuite/layers/src/test/java/org/jboss/as/test/layers/LayersTestCase.java
Labels: deps-changed

#15845 WFLY-16695 Avoid unnecessary replication of Mojarra's SessionHelper on read
  clustering/faces/mojarra/pom.xml
  clustering/faces/mojarra/src/main/java/org/wildfly/clustering/faces/mojarra/context/flash/FlashImmutability.java
  clustering/faces/mojarra/src/main/java/org/wildfly/clustering/faces/mojarra/context/flash/Reflect.java
  clustering/faces/mojarra/src/main/java/org/wildfly/clustering/faces/mojarra/context/flash/SessionHelperMarshaller.java
  clustering/web/extension/src/main/java/org/wildfly/extension/clustering/web/deployment/DistributableWebDeploymentProcessor.java
  clustering/web/undertow/src/main/java/org/wildfly/clustering/web/undertow/session/SessionManagerFactoryConfigurationAdapter.java
  ee-9/source-transform/clustering/faces/mojarra/pom.xml
  ee-feature-pack/common/src/main/resources/modules/system/layers/base/org/wildfly/clustering/faces/mojarra/main/module.xml
Labels: deps-ok

#15859 WFLY-16719 TCP-based stacks require UFC to avoid async senders from overwhelming receiver.
  ee-feature-pack/galleon-common/src/main/resources/feature_groups/jgroups.xml
Labels: deps-ok

#15842 WFLY-16664 Upgrade Narayana to 5.13.0.Final
  pom.xml
  testsuite/integration/xts/src/test/java/org/jboss/as/test/xts/annotation/client/CompensatableTestCase.java
  testsuite/integration/xts/src/test/java/org/jboss/as/test/xts/annotation/compensationscoped/CompensationScopedTestCase.java
Labels: deps-ok

#15858 [WFLY-16685] Prune the legacy dependency set
  boms/legacy-ee/pom.xml
  boms/legacy-expansion/pom.xml
  boms/standard-ee/pom.xml
  pom.xml
Labels: deps-ok

#15857 [WFLY-16684] Add legacy bom dep mgmt entries for javax.* stuff curren…
  boms/legacy-ee/pom.xml
  pom.xml
Labels: deps-ok
