Repository wildfly/wildfly, pull requests merged in 2022-09, with the labels that each got.

#15990 WFLY-16913 Modify description in weld of subsystem to its correct sentence
  weld/subsystem/src/main/resources/org/jboss/as/weld/LocalDescriptions.properties
Labels: deps-ok

#15992 WFLY-16856 Revert default marshaller back to LEGACY
  clustering/infinispan/embedded/spi/src/main/java/org/wildfly/clustering/infinispan/marshall/InfinispanMarshallerFactory.java
  clustering/infinispan/extension/src/main/java/org/jboss/as/clustering/infinispan/subsystem/CacheContainerResourceDefinition.java
  clustering/infinispan/extension/src/main/java/org/jboss/as/clustering/infinispan/subsystem/CacheContainerResourceTransformer.java
  clustering/infinispan/extension/src/main/java/org/jboss/as/clustering/infinispan/subsystem/remote/HotRodMarshallerFactory.java
  clustering/infinispan/extension/src/main/java/org/jboss/as/clustering/infinispan/subsystem/remote/RemoteCacheContainerResourceDefinition.java
  clustering/infinispan/extension/src/main/java/org/jboss/as/clustering/infinispan/subsystem/remote/RemoteCacheContainerResourceTransformer.java
  clustering/infinispan/extension/src/main/resources/schema/jboss-as-infinispan_14_0.xsd
  testsuite/integration/clustering/src/test/java/org/jboss/as/test/clustering/cluster/infinispan/remote/RemoteInfinispanCacheTestCase.java
Labels: Blocker, deps-ok, 27.x

#15993 [WFLY-16919] remove obsolete comments containing project version
  testsuite/integration/basic/pom.xml
  testsuite/integration/legacy/pom.xml
  testsuite/integration/rbac/pom.xml
  testsuite/integration/smoke/pom.xml
  testsuite/integration/web/pom.xml
  testsuite/integration/ws/pom.xml
  testsuite/preview/basic/pom.xml
Labels: deps-ok

#15998 WFLY-16928: Upgrade HAL to 3.6.4.Final
  pom.xml
Labels: deps-ok

#15827 [WFLY-16667, WFLY-16921] Upgrade galleon-plugins to 6.0.0.Beta1
  ee-feature-pack/galleon-common/src/main/resources/packages/docs.licenses.merge/pm/wildfly/tasks.xml
  ee-feature-pack/galleon-common/src/main/resources/packages/docs.licenses/pm/wildfly/tasks.xml
  ee-feature-pack/galleon-feature-pack/wildfly-feature-pack-build.xml
  microprofile/galleon-common/src/main/resources/packages/docs.licenses.merge/pm/wildfly/tasks.xml
  microprofile/galleon-common/src/main/resources/packages/docs.licenses/pm/wildfly/tasks.xml
  pom.xml
  servlet-feature-pack/galleon-common/src/main/resources/packages/docs.licenses.merge/pm/wildfly/tasks.xml
Labels: deps-ok, Critical

#15978 WFLY-14419 Add tests for naming subsystem for attributes that allow expression
  naming/src/test/java/org/jboss/as/naming/subsystem/NamingSubsystemTestCase.java
  naming/src/test/resources/org/jboss/as/naming/subsystem/subsystem_expression.xml
Labels: deps-ok

#15989 [WFLY-16918] EJB: Add pools description to admin documentation
  docs/src/main/asciidoc/_admin-guide/subsystem-configuration/Jakarta_Enterprise_Beans_3.adoc
Labels: deps-ok

#16004 [WFLY-16937] Remove use of WildFlyConversationAwareViewHandler
  jsf/injection/src/main/java/org/jboss/as/jsf/injection/weld/WildFlyConversationAwareViewHandler.java
  jsf/injection/src/main/resources/META-INF/faces-config.xml
Labels: deps-ok

#16002 [WFLY-16820][WFLY-16821] Smallrye upgrades
  pom.xml
Labels: deps-ok

#16000 [WFLY-16934]: Count messages is not working properly for JMS Queues.
  messaging-activemq/subsystem/src/main/java/org/wildfly/extension/messaging/activemq/jms/JMSQueueControlHandler.java
Labels: deps-ok

#15923 WFLY-16797 Drop jakarta transformation of wildfly-microprofile-fault-tolerance-smallrye modules
  boms/legacy-expansion/pom.xml
  boms/standard-expansion/pom.xml
  ee-9/common-microprofile/src/main/resources/license/preview-feature-pack-common-microprofile-licenses.xml
  ee-9/source-transform/microprofile/fault-tolerance-smallrye/executor/pom.xml
  ee-9/source-transform/microprofile/fault-tolerance-smallrye/extension/pom.xml
  ee-9/source-transform/microprofile/fault-tolerance-smallrye/pom.xml
  ee-9/source-transform/microprofile/pom.xml
  microprofile/fault-tolerance-smallrye/executor/pom.xml
  microprofile/fault-tolerance-smallrye/executor/src/main/java/org/wildfly/extension/microprofile/faulttolerance/FaultToleranceContainerExecutorFactory.java
  microprofile/fault-tolerance-smallrye/extension/pom.xml
  microprofile/fault-tolerance-smallrye/extension/src/main/java/org/wildfly/extension/microprofile/faulttolerance/MicroProfileFaultToleranceModel.java
  microprofile/fault-tolerance-smallrye/extension/src/main/java/org/wildfly/extension/microprofile/faulttolerance/MicroProfileFaultToleranceSchema.java
  microprofile/galleon-common/pom.xml
  microprofile/galleon-common/src/main/resources/license/microprofile-feature-pack-licenses.xml
  microprofile/galleon-common/src/main/resources/modules/system/layers/base/io/smallrye/fault-tolerance/main/module.xml
  microprofile/galleon-common/src/main/resources/modules/system/layers/base/org/wildfly/extension/microprofile/fault-tolerance-smallrye/main/module.xml
  microprofile/galleon-common/src/main/resources/modules/system/layers/base/org/wildfly/microprofile/fault-tolerance-smallrye/executor/main/module.xml
  microprofile/pom.xml
  pom.xml
Labels: deps-changed

#15942 WFLY-16824 Drop jakarta transformation of wildfly-mod_cluster-undertow-jakarta module
  boms/common-ee/pom.xml
  boms/legacy-ee/pom.xml
  boms/standard-ee/pom.xml
  ee-9/common/src/main/resources/license/preview-feature-pack-common-licenses.xml
  ee-9/source-transform/mod_cluster/undertow/pom.xml
  ee-9/source-transform/pom.xml
  ee-feature-pack/common/pom.xml
  ee-feature-pack/common/src/main/resources/license/ee-feature-pack-common-licenses.xml
  ee-feature-pack/common/src/main/resources/modules/system/layers/base/org/jboss/mod_cluster/core/main/module.xml
  ee-feature-pack/common/src/main/resources/modules/system/layers/base/org/wildfly/mod_cluster/undertow/main/module.xml
  mod_cluster/pom.xml
  mod_cluster/undertow/pom.xml
  mod_cluster/undertow/src/main/java/org/wildfly/mod_cluster/undertow/UndertowContext.java
  mod_cluster/undertow/src/test/java/org/wildfly/mod_cluster/undertow/TestUndertowService.java
  mod_cluster/undertow/src/test/java/org/wildfly/mod_cluster/undertow/UndertowConnectorTestCase.java
  mod_cluster/undertow/src/test/java/org/wildfly/mod_cluster/undertow/UndertowContextTestCase.java
  mod_cluster/undertow/src/test/java/org/wildfly/mod_cluster/undertow/UndertowEngineTestCase.java
Labels: deps-changed

#16006 [WFLY-16885] Modify description in ee of subsystem to its correct sen…
  ee/src/main/resources/org/jboss/as/ee/subsystem/LocalDescriptions.properties
Labels: deps-ok

#16008 [WFLY-16815][WFLY-16816] Upgrade SR Metrics and Opentracing
  pom.xml
Labels: deps-ok

#16009 [WFLY-16941][WFLY-16942] Upgrade Jastow to 2.2.3.Final and Eclipse JDT ECJ to 3.30.0
  pom.xml
Labels: deps-ok

#16011 [WFLY-16943] Upgrading jsoup to 1.15.3
  pom.xml
Labels: deps-ok

#16005 [WFLY-16939] Update Ironjacamar to 1.5.8.Final
  pom.xml
Labels: deps-ok

#15917 WFLY-16709 Standardize the maven module descriptions.
  boms/common-ee/pom.xml
  boms/common-expansion/pom.xml
  boms/legacy-ee/pom.xml
  boms/legacy-expansion/pom.xml
  boms/preview-ee/pom.xml
  boms/preview-expansion/pom.xml
  boms/standard-ee/pom.xml
  boms/standard-expansion/pom.xml
  ee-9/pom.xml
  ee-9/source-transform/pom.xml
  ee-feature-pack/galleon-common/pom.xml
  ee-feature-pack/galleon-content/pom.xml
  ee-feature-pack/pom.xml
  galleon-pack/galleon-content/pom.xml
  galleon-pack/pom.xml
  jpa/eclipselink/pom.xml
  jpa/hibernate5/pom.xml
  jpa/hibernate5_3/pom.xml
  jpa/hibernate6/pom.xml
  jpa/openjpa/pom.xml
  jpa/spi/pom.xml
  servlet-feature-pack/pom.xml
  testsuite/scripts/pom.xml
Labels: deps-ok

#16017 [WFLY-16948] Workaround flaw in WeldExpressionFactory.equals by using a WeldExpressionFactory subclass
  jsf/injection/src/main/java/org/jboss/as/jsf/injection/weld/WeldApplication.java
  testsuite/integration/basic/pom.xml
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/jsf/el/ElServlet.java
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/jsf/el/FacesExpressionFactoryTestCase.java
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/jsf/el/beans.xml
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/jsf/el/faces-config.xml
  weld/subsystem/src/main/java/org/jboss/as/weld/deployment/WeldDeployment.java
Labels: deps-ok

#16014 [WFLY-16933] Cleaner use of Maps in messaging module
  legacy/messaging/src/main/java/org/jboss/as/messaging/MessagingExtension.java
  legacy/messaging/src/main/java/org/jboss/as/messaging/jms/cli/CreateJMSResourceHandler.java
  messaging-activemq/subsystem/src/main/java/org/wildfly/extension/messaging/activemq/deployment/JMSConnectionFactoryDefinitionInjectionSource.java
  messaging-activemq/subsystem/src/main/java/org/wildfly/extension/messaging/activemq/jms/cli/CreateJMSResourceHandler.java
  messaging-activemq/subsystem/src/main/java/org/wildfly/extension/messaging/activemq/jms/legacy/LegacyConnectionFactoryService.java
Labels: deps-ok

#16024 [WFLY-16957] Ensure we allow any ExpressionFactoryWrappers to execute…
  undertow/src/main/java/org/wildfly/extension/undertow/deployment/JspApplicationContextWrapper.java
Labels: deps-ok

#16027 WFLY-16960 Change single quote to double quote in docs cli sample com…
  docs/src/main/asciidoc/_developer-guide/ejb3/Jakarta_Enterprise_Beans_Database_Persistent_Timers.adoc
  docs/src/main/asciidoc/_developer-guide/ejb3/Jakarta_Enterprise_Beans_over_HTTP.adoc
  docs/src/main/asciidoc/_high-availability/load-balancing/Ranked_Affinity.adoc
Labels: deps-ok

#16015 WFLY-16927 Update the OIDC tests to use the 19.0.1 version of quay.io/keycloak/keycloak
  testsuite/integration/elytron-oidc-client/src/test/java/org/wildfly/test/integration/elytron/oidc/client/KeycloakContainer.java
Labels: deps-ok

#16021 [WFLY-16954] Construct ImmediateValue directly instead of using Values.immediateValue() factory method
  ee-9/source-transform/ee/src/main/java/org/jboss/as/ee/component/EnvEntryInjectionSource.java
  ee-9/source-transform/ee/src/main/java/org/jboss/as/ee/component/ViewDescription.java
  ee-9/source-transform/ee/src/main/java/org/jboss/as/ee/naming/ApplicationContextProcessor.java
  ee-9/source-transform/ee/src/main/java/org/jboss/as/ee/naming/InApplicationClientBindingProcessor.java
  ee-9/source-transform/ee/src/main/java/org/jboss/as/ee/naming/ModuleContextProcessor.java
  ee/src/main/java/org/jboss/as/ee/component/EnvEntryInjectionSource.java
  ee/src/main/java/org/jboss/as/ee/component/ViewDescription.java
  ee/src/main/java/org/jboss/as/ee/naming/ApplicationContextProcessor.java
  ee/src/main/java/org/jboss/as/ee/naming/InApplicationClientBindingProcessor.java
  ee/src/main/java/org/jboss/as/ee/naming/ModuleContextProcessor.java
  ejb3/src/main/java/org/jboss/as/ejb3/deployment/processors/EjbJndiBindingsDeploymentUnitProcessor.java
  iiop-openjdk/src/main/java/org/wildfly/iiop/openjdk/service/CorbaServiceUtil.java
  messaging-activemq/subsystem/src/main/java/org/wildfly/extension/messaging/activemq/BinderServiceUtil.java
  naming/src/test/java/org/jboss/as/naming/ServiceBasedNamingStoreTestCase.java
Labels: deps-ok

#16022 [WFLY-16817] Upgrade SmallRye JWT to 4.0.0
  pom.xml
Labels: deps-ok

#16020 [WFLY-16953]:Upgrade jbossws-cxf to 6.1.0.Final
  pom.xml
Labels: deps-ok

#16029 [WFLY-16962][WFLY-16963][WFLY-16964] Jaxb upgrades
  pom.xml
Labels: deps-changed

#16030 [WFLY-16818] Upgrade Smallrye Health to 4.0.0
  pom.xml
Labels: deps-ok

#16036 @Ignore singleton deployment tests until WFLY-16973 is resolved.
  testsuite/integration/clustering/src/test/java/org/jboss/as/test/clustering/cluster/singleton/SingletonDeploymentDescriptorTestCase.java
  testsuite/integration/clustering/src/test/java/org/jboss/as/test/clustering/cluster/singleton/SingletonDeploymentJBossAllTestCase.java
Labels: deps-ok

#16034 WFLY-16949 Clean up invalid 'zip/' type dependencies from the WildFly…
  pom.xml
Labels: deps-ok

#16043 [WFLY-16976]: Upgrade jboss metadata to 15.2.0.Beta1
  pom.xml
Labels: deps-ok, EE10

#15977 WFLY-16874 Mark Lucene, Elasticsearch REST client, GSON as public modules
  ee-feature-pack/common/src/main/resources/modules/system/layers/base/com/google/code/gson/main/module.xml
  ee-feature-pack/common/src/main/resources/modules/system/layers/base/org/apache/lucene/main/module.xml
  ee-feature-pack/common/src/main/resources/modules/system/layers/base/org/elasticsearch/client/rest-client/main/module.xml
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/hibernate/search/backend/elasticsearch/extension/HibernateSearchElasticsearchGsonDependencyTestCase.java
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/hibernate/search/backend/lucene/extension/HibernateSearchLuceneDependencyTestCase.java
Labels: deps-ok

#16049 [WFLY-16981] Test Suite: Set buffer-pooling to false to both
  testsuite/domain/src/test/resources/domain-configs/domain-standard-ee.xml
  testsuite/domain/src/test/resources/domain-configs/domain-standard.xml
Labels: deps-ok

#15957 WFLY-16253 Undertow subsystem model for WF27 should be 12.0.0, not 13.0.0.
  undertow/src/main/java/org/wildfly/extension/undertow/HostSingleSignOnDefinition.java
  undertow/src/main/java/org/wildfly/extension/undertow/UndertowExtension.java
Labels: Blocker, deps-ok, 27.x

#16051 [WFLY-16983] Upgrade WildFly Core to 19.0.0.Beta17
  pom.xml
  testsuite/domain/pom.xml
  testsuite/domain/src/test/java/org/jboss/as/test/integration/domain/BuildConfigurationTestBase.java
  testsuite/domain/src/test/java/org/jboss/as/test/integration/domain/DefaultConfigSmokeTestCase.java
  testsuite/domain/src/test/java/org/jboss/as/test/integration/domain/EEConcurrencyExecutorShutdownTestCase.java
  testsuite/domain/src/test/java/org/jboss/as/test/integration/domain/JVMServerPropertiesTestCase.java
  testsuite/domain/src/test/java/org/jboss/as/test/integration/domain/OrderedChildResourcesTestCase.java
  testsuite/domain/src/test/java/org/jboss/as/test/integration/domain/management/cli/DomainDeploymentOverlayTestCase.java
  testsuite/domain/src/test/java/org/jboss/as/test/integration/domain/management/cli/RolloutPlanTestCase.java
  testsuite/domain/src/test/java/org/jboss/as/test/integration/domain/suites/CLITestSuite.java
  testsuite/domain/src/test/java/org/jboss/as/test/integration/domain/suites/DatasourceTestCase.java
  testsuite/domain/src/test/java/org/jboss/as/test/integration/domain/suites/DeploymentManagementTestCase.java
  testsuite/domain/src/test/java/org/jboss/as/test/integration/domain/suites/DeploymentOverlayTestCase.java
  testsuite/domain/src/test/java/org/jboss/as/test/integration/domain/suites/GlobalDirectoryDomainTestCase.java
  testsuite/domain/src/test/java/org/jboss/as/test/integration/domain/suites/JcaCCMRuntimeOnlyProfileOpsTestCase.java
  testsuite/domain/src/test/java/org/jboss/as/test/integration/domain/suites/ModelPersistenceTestCase.java
  testsuite/domain/src/test/java/org/jboss/as/test/integration/domain/suites/ReadEnvironmentVariablesTestCase.java
  testsuite/domain/src/test/resources/host-configs/admin-only-discovery.xml
  testsuite/domain/src/test/resources/host-configs/admin-only-no-discovery.xml
  testsuite/domain/src/test/resources/host-configs/host-failover1.xml
  testsuite/domain/src/test/resources/host-configs/host-failover2.xml
  testsuite/domain/src/test/resources/host-configs/host-failover3.xml
  testsuite/domain/src/test/resources/host-configs/host-primary-elytron.xml
  testsuite/domain/src/test/resources/host-configs/host-primary-jvm-properties.xml
  testsuite/domain/src/test/resources/host-configs/host-primary-no-http.xml
  testsuite/domain/src/test/resources/host-configs/host-primary-no-local.xml
  testsuite/domain/src/test/resources/host-configs/host-primary-rbac-properties.xml
  testsuite/domain/src/test/resources/host-configs/host-primary-rbac.xml
  testsuite/domain/src/test/resources/host-configs/host-primary.xml
  testsuite/domain/src/test/resources/host-configs/host-secondary-discovery-options.xml
  testsuite/domain/src/test/resources/host-configs/host-secondary-elytron.xml
  testsuite/domain/src/test/resources/host-configs/host-secondary-rbac-properties.xml
  testsuite/domain/src/test/resources/host-configs/host-secondary-rbac.xml
  testsuite/domain/src/test/resources/host-configs/host-secondary.xml
  testsuite/domain/src/test/resources/host-configs/host-secrets.xml
  testsuite/domain/src/test/resources/host-configs/respawn-primary.xml
  testsuite/mixed-domain/pom.xml
  testsuite/mixed-domain/src/test/java/org/jboss/as/test/integration/domain/mixed/DomainAdjuster.java
  testsuite/mixed-domain/src/test/java/org/jboss/as/test/integration/domain/mixed/DomainHostExcludesTest.java
  testsuite/mixed-domain/src/test/java/org/jboss/as/test/integration/domain/mixed/ElytronOnlyMasterTestSuite.java
  testsuite/mixed-domain/src/test/java/org/jboss/as/test/integration/domain/mixed/LegacyConfigTest.java
  testsuite/mixed-domain/src/test/java/org/jboss/as/test/integration/domain/mixed/MixedDomainTestSupport.java
  testsuite/mixed-domain/src/test/java/org/jboss/as/test/integration/domain/mixed/RBACConfigTestCase.java
  testsuite/mixed-domain/src/test/java/org/jboss/as/test/integration/domain/mixed/SimpleMixedDomainTest.java
  testsuite/mixed-domain/src/test/java/org/jboss/as/test/integration/domain/mixed/Version.java
  testsuite/mixed-domain/src/test/java/org/jboss/as/test/integration/domain/mixed/WildcardReadsTestCase.java
  testsuite/mixed-domain/src/test/java/org/jboss/as/test/integration/domain/mixed/eap740/MixedDomainOverlay740TestSuite.java
  testsuite/mixed-domain/src/test/resources/master-config/host-primary-elytron.xml
  testsuite/mixed-domain/src/test/resources/master-config/host.xml
  testsuite/mixed-domain/src/test/resources/slave-config/host-secondary-overlay.xml
  testsuite/mixed-domain/src/test/resources/slave-config/host-secondary.xml
  testsuite/shared/src/main/java/org/jboss/as/test/integration/domain/management/util/JBossAsManagedConfiguration.java
Labels: deps-ok

#16042 [WFLY-16865 & WFLY-16228] Upgrade RESTEasy 6.2.0.Beta1 and Jackson to…
  boms/common-ee/pom.xml
  boms/standard-ee/pom.xml
  docs/src/main/asciidoc/_developer-guide/Implicit_module_dependencies_for_deployments.adoc
  ee-feature-pack/common/pom.xml
  ee-feature-pack/common/src/main/resources/modules/system/layers/base/com/fasterxml/jackson/jakarta/jackson-jakarta-json-provider/main/module.xml
  ee-feature-pack/common/src/main/resources/modules/system/layers/base/com/fasterxml/jackson/jaxrs/jackson-jaxrs-json-provider/main/module.xml
  ee-feature-pack/common/src/main/resources/modules/system/layers/base/org/jboss/resteasy/jose-jwt/main/module.xml
  ee-feature-pack/common/src/main/resources/modules/system/layers/base/org/jboss/resteasy/resteasy-jackson2-provider/main/module.xml
  pom.xml
  testsuite/integration/basic/pom.xml
Labels: deps-changed

#16044 Docs: add mod_cluster to the galleon docs + minor fixes.
  docs/src/main/asciidoc/_galleon/Galleon_layers.adoc
Labels: deps-ok

#16038 [WFLY-16945] Cleaner use of Maps in testsuite module
  testsuite/domain/src/test/java/org/jboss/as/test/integration/domain/management/cli/DeployAllServerGroupsTestCase.java
  testsuite/domain/src/test/java/org/jboss/as/test/integration/domain/management/cli/DeploySingleServerGroupTestCase.java
  testsuite/domain/src/test/java/org/jboss/as/test/integration/domain/management/cli/DomainDeployWithRuntimeNameTestCase.java
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/batch/common/AbstractBatchTestCase.java
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/ejb/security/LifecycleTestCase.java
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/jca/capacitypolicies/AbstractDatasourceCapacityPoliciesTestCase.java
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/logging/config/AbstractConfigTestCase.java
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/messaging/jms/deployment/MessagingServlet.java
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/messaging/jms/external/MessagingServlet.java
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/messaging/jms/external/prefix/AnnotatedLegacyPrefixMessagingServlet.java
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/messaging/jms/external/prefix/AnnotatedMessagingServlet.java
  testsuite/integration/clustering/src/test/java/org/jboss/as/test/clustering/EJBClientContextSelector.java
  testsuite/integration/clustering/src/test/java/org/jboss/as/test/clustering/cluster/ejb2/stateless/RemoteStatelessFailoverTestCase.java
  testsuite/integration/elytron-oidc-client/src/test/java/org/wildfly/test/integration/elytron/oidc/client/KeycloakConfiguration.java
  testsuite/integration/web/src/test/java/org/jboss/as/test/integration/web/handlers/RequestDumpingHandlerTestImpl.java
  testsuite/integration/xts/src/test/java/org/jboss/as/test/xts/wsba/participantcompletion/service/BAParticipantCompletionSuperService.java
  testsuite/scripts/src/test/java/org/wildfly/test/common/ServerHelper.java
  testsuite/shared/src/main/java/org/jboss/as/test/integration/common/jms/ActiveMQProviderJMSOperations.java
  testsuite/shared/src/main/java/org/jboss/as/test/integration/common/jms/RemoteActiveMQProviderJMSOperations.java
Labels: deps-ok

#16010 [WFLY-16460] Workaround MP JWT TCK regression caused by AES default key size change since JDK19
  testsuite/integration/microprofile-tck/jwt/pom.xml
Labels: deps-ok

#16033 [WFLY-16958]: Operations may fail on JMS Topic.
  messaging-activemq/subsystem/src/main/java/org/wildfly/extension/messaging/activemq/jms/JMSTopicControlHandler.java
Labels: deps-ok

#16025 [WFLY-16738] Replace the overridden dependencies that should be driven by WildFly Core
  boms/standard-ee/pom.xml
  pom.xml
Labels: deps-ok

#15991 [WFLY-16833]: Upgrade Apache Artemis to 2.25.0
  messaging-activemq/subsystem/src/main/java/org/wildfly/extension/messaging/activemq/AddressControlHandler.java
  messaging-activemq/subsystem/src/main/java/org/wildfly/extension/messaging/activemq/CoreAddressDefinition.java
  pom.xml
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/messaging/mgmt/AddressControlManagementTestCase.java
Labels: deps-ok

#16026 WFLY-16959 Upgrade smallrye-open-api to 3.0.0-RC4
  pom.xml
Labels: deps-ok

#16039 [WFLY-16713][WFLY-16552] Upgrade to Hibernate ORM 6.1.3 to address envers test failures
  pom.xml
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/jpa/hibernate/entitytest/EntityTestCase.java
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/jpa/hibernate/envers/AuditJoinTableoverBidirectionalTest.java
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/jpa/hibernate/envers/AuditJoinTableoverOnetoManyJoinColumnTest.java
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/jpa/hibernate/envers/basicenverstest/BasicEnversTestCase.java
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/jpa/hibernate/envers/basicselectiveenverstest/BasicSelectiveEnversTestCase.java
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/jpa/hibernate/envers/implementvalidityauditstrategytest/ImplementValidityAuditStrategyTestCase.java
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/jpa/hibernate/envers/validityauditstrategyoninheritancetest/ValidityAuditStrategyonInheritanceTestCase.java
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/jpa/hibernate/sessionfactorytest/SessionFactoryTestCase.java
Labels: deps-ok

#16040 [WFLY-16944] Clean up references to JSoup
  ee-feature-pack/common/src/main/resources/modules/system/layers/base/org/hibernate/validator/main/module.xml
  pom.xml
Labels: deps-ok

#16064 [WFLY-16805][WFLY-17000][WFLY-17001] Elytron component upgrades
  pom.xml
Labels: deps-ok

#16062 WFLY-16998 Upgrade Infinispan to 13.0.11.Final
  pom.xml
Labels: deps-ok

#16059 WFLY-16993 Drop support for very very old Infinispan subsystem schemas
  clustering/infinispan/extension/src/main/java/org/jboss/as/clustering/infinispan/subsystem/InfinispanSchema.java
  clustering/infinispan/extension/src/main/java/org/jboss/as/clustering/infinispan/subsystem/InfinispanSubsystemXMLReader.java
  clustering/infinispan/extension/src/main/java/org/jboss/as/clustering/infinispan/subsystem/XMLAttribute.java
  clustering/infinispan/extension/src/main/java/org/jboss/as/clustering/infinispan/subsystem/XMLElement.java
  clustering/infinispan/extension/src/test/resources/org/jboss/as/clustering/infinispan/subsystem/subsystem-infinispan-1_0.xml
  clustering/infinispan/extension/src/test/resources/org/jboss/as/clustering/infinispan/subsystem/subsystem-infinispan-1_1.xml
  clustering/infinispan/extension/src/test/resources/org/jboss/as/clustering/infinispan/subsystem/subsystem-infinispan-1_2.xml
  clustering/infinispan/extension/src/test/resources/org/jboss/as/clustering/infinispan/subsystem/subsystem-infinispan-1_3.xml
  clustering/infinispan/extension/src/test/resources/org/jboss/as/clustering/infinispan/subsystem/subsystem-infinispan-1_4.xml
Labels: deps-ok

#16050 [WFLY-16984] Refactoring Batch Subsystem to use new MSC value API
  batch-jberet/src/main/java/org/wildfly/extension/batch/jberet/BatchConfigurationService.java
  batch-jberet/src/main/java/org/wildfly/extension/batch/jberet/BatchSubsystemDefinition.java
  batch-jberet/src/main/java/org/wildfly/extension/batch/jberet/deployment/ArtifactFactoryService.java
  batch-jberet/src/main/java/org/wildfly/extension/batch/jberet/deployment/BatchEnvironmentProcessor.java
  batch-jberet/src/main/java/org/wildfly/extension/batch/jberet/deployment/BatchEnvironmentService.java
  batch-jberet/src/main/java/org/wildfly/extension/batch/jberet/deployment/JobOperatorService.java
  batch-jberet/src/main/java/org/wildfly/extension/batch/jberet/job/repository/InMemoryJobRepositoryDefinition.java
  batch-jberet/src/main/java/org/wildfly/extension/batch/jberet/job/repository/InMemoryJobRepositoryService.java
  batch-jberet/src/main/java/org/wildfly/extension/batch/jberet/job/repository/JdbcJobRepositoryDefinition.java
  batch-jberet/src/main/java/org/wildfly/extension/batch/jberet/job/repository/JdbcJobRepositoryService.java
  batch-jberet/src/main/java/org/wildfly/extension/batch/jberet/job/repository/JobRepositoryService.java
  batch-jberet/src/main/java/org/wildfly/extension/batch/jberet/thread/pool/BatchThreadPoolResourceDefinition.java
  batch-jberet/src/main/java/org/wildfly/extension/batch/jberet/thread/pool/JobExecutorService.java
Labels: deps-ok

#16001 WFLY-16935: add EnterpiseDB to recongized dialects, throw exception i…
  ejb3/src/main/java/org/jboss/as/ejb3/timerservice/persistence/database/DatabaseTimerPersistence.java
Labels: deps-ok

#15965 WFLY-16862 Hibernate Search engine module should have optional dependencies to other modules
  ee-feature-pack/common/src/main/resources/modules/system/layers/base/org/hibernate/search/engine/main/module.xml
  ee-feature-pack/common/src/main/resources/modules/system/layers/base/org/hibernate/search/mapper/orm/main/module.xml
  ee-feature-pack/common/src/main/resources/modules/system/layers/base/org/hibernate/search/mapper/pojo/main/module.xml
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/hibernate/search/backend/lucene/massindexer/HibernateSearchLuceneEarMassIndexerTestCase.java
  testsuite/layers/src/test/java/org/jboss/as/test/layers/LayersTestCase.java
Labels: deps-ok

#16063 [WFLY-16738] Replace the overridden dependencies that should be driven by WildFly Core
  ee-9/feature-pack/pom.xml
  ee-feature-pack/common/src/main/resources/license/ee-feature-pack-common-licenses.xml
  ee-feature-pack/common/src/main/resources/modules/system/layers/base/org/eclipse/parsson/main/module.xml
  ee-feature-pack/common/src/main/resources/modules/system/layers/base/org/wildfly/security/jakarta/authentication/main/module.xml
  ee-feature-pack/common/src/main/resources/modules/system/layers/base/org/wildfly/security/jakarta/authorization/main/module.xml
  ee-feature-pack/ee-10-api/src/main/resources/license/ee-feature-pack-ee-10-api-licenses.xml
  ee-feature-pack/ee-10-api/src/main/resources/modules/system/layers/base/jakarta/interceptor/api/main/module.xml
  ee-feature-pack/ee-10-api/src/main/resources/modules/system/layers/base/jakarta/json/api/main/module.xml
  ee-feature-pack/ee-10-api/src/main/resources/modules/system/layers/base/jakarta/security/auth/message/api/main/module.xml
  ee-feature-pack/ee-10-api/src/main/resources/modules/system/layers/base/jakarta/security/jacc/api/main/module.xml
  ee-feature-pack/galleon-feature-pack/pom.xml
Labels: deps-ok

#16068 WFLY-16998 ProtoStream/RxJava upgrades for Infinispan 13.0.11.Final
  pom.xml
Labels: deps-ok

#16019 WFLY-10912 CodecSessionConfig#findSessionId() causes an incorrect JSESSIONID Set-Cookie header
  clustering/web/undertow/src/main/java/org/wildfly/clustering/web/undertow/session/DistributableSessionManager.java
  undertow/src/main/java/org/wildfly/extension/undertow/session/CodecSessionConfig.java
  undertow/src/test/java/org/wildfly/extension/undertow/session/CodecSessionConfigTestCase.java
Labels: deps-ok

#16070 [WFLY-17007] Upgrade JBoss Metadata to 15.2.0.Beta2
  pom.xml
Labels: deps-ok

#16056 [WFLY-16989] Cleaner use of Maps in Undertow module
  undertow/src/main/java/org/wildfly/extension/undertow/WebServerService.java
  undertow/src/main/java/org/wildfly/extension/undertow/deployment/UndertowDeploymentProcessor.java
  undertow/src/main/java/org/wildfly/extension/undertow/deployment/WarMetaDataProcessor.java
Labels: deps-ok

#16073 Fix for WFLY-17013, Upgrade Galleon plugins to 6.1.0.Final
  pom.xml
Labels: deps-ok

#16072 WFLY-17010 Upgrade to Hibernate Search 6.1.7.Final
  pom.xml
Labels: deps-ok

#16041 WFLY-16931 Drop source transformation for batch-jberet subsystem
  batch-jberet/pom.xml
  batch-jberet/src/main/java/org/wildfly/extension/batch/jberet/DefaultBatchEnvironment.java
  batch-jberet/src/main/java/org/wildfly/extension/batch/jberet/_private/BatchLogger.java
  batch-jberet/src/main/java/org/wildfly/extension/batch/jberet/deployment/ArtifactFactoryService.java
  batch-jberet/src/main/java/org/wildfly/extension/batch/jberet/deployment/BatchDependencyProcessor.java
  batch-jberet/src/main/java/org/wildfly/extension/batch/jberet/deployment/BatchDeploymentResourceDefinition.java
  batch-jberet/src/main/java/org/wildfly/extension/batch/jberet/deployment/BatchEnvironmentProcessor.java
  batch-jberet/src/main/java/org/wildfly/extension/batch/jberet/deployment/BatchEnvironmentService.java
  batch-jberet/src/main/java/org/wildfly/extension/batch/jberet/deployment/BatchJobExecutionResource.java
  batch-jberet/src/main/java/org/wildfly/extension/batch/jberet/deployment/BatchJobExecutionResourceDefinition.java
  batch-jberet/src/main/java/org/wildfly/extension/batch/jberet/deployment/JobOperationReadOnlyStepHandler.java
  batch-jberet/src/main/java/org/wildfly/extension/batch/jberet/deployment/JobOperationStepHandler.java
  batch-jberet/src/main/java/org/wildfly/extension/batch/jberet/deployment/JobOperatorService.java
  batch-jberet/src/main/java/org/wildfly/extension/batch/jberet/deployment/WildFlyJobOperator.java
  batch-jberet/src/main/java/org/wildfly/extension/batch/jberet/job/repository/JobRepositoryService.java
  boms/legacy-ee/pom.xml
  boms/standard-ee/pom.xml
  docs/src/main/asciidoc/_admin-guide/subsystem-configuration/Jakarta_Batch.adoc
  docs/src/main/asciidoc/_developer-guide/Implicit_module_dependencies_for_deployments.adoc
  docs/src/main/asciidoc/_elytron/Elytron_Subsystem.adoc
  ee-9/common/src/main/resources/license/preview-feature-pack-common-licenses.xml
  ee-9/source-transform/batch-jberet/pom.xml
  ee-9/source-transform/pom.xml
  ee-feature-pack/common/pom.xml
  ee-feature-pack/common/src/main/resources/license/ee-feature-pack-common-licenses.xml
  ee-feature-pack/common/src/main/resources/modules/system/layers/base/org/jberet/jberet-core/main/module.xml
  ee-feature-pack/common/src/main/resources/modules/system/layers/base/org/wildfly/extension/batch/jberet/main/module.xml
  ee-feature-pack/ee-10-api/src/main/resources/modules/system/layers/base/jakarta/batch/api/main/module.xml
  pom.xml
  testsuite/integration/basic/pom.xml
  testsuite/integration/elytron/pom.xml
Labels: deps-changed

#15986 [WFLY-16916] Wrong description of enable-graceful-txn-shutdown attribute
  ejb3/src/main/resources/org/jboss/as/ejb3/subsystem/LocalDescriptions.properties
Labels: deps-ok

#16079 [WFLY-17017] Upgrade Undertow to 2.3.0.Beta1
  pom.xml
Labels: deps-ok, Critical

#16075 [WFLY-16812] Upgrade MP Reactive Streams Operators to 3.0
  pom.xml
Labels: Blocker, deps-ok

#16061 [WFLY-16992]: WFLYJCA0073: Failed to load module for RA [org.jboss.genericjms].
  ee-feature-pack/common/src/main/resources/modules/system/layers/base/org/jboss/genericjms/main/META-INF/ra.xml
  testsuite/integration/basic/pom.xml
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/messaging/mgmt/GenericJmsResourceAdpterTestCase.java
Labels: Blocker, deps-ok, 27.x

#14614 [WFCORE-5343]: Preparing YAML Support
  appclient/src/main/java/org/jboss/as/appclient/subsystem/CommandLineArgumentUsageImpl.java
  appclient/src/main/java/org/jboss/as/appclient/subsystem/Main.java
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/ee/appclient/basic/DescriptorClientMain.java
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/ee/appclient/basic/SimpleApplicationClientTestCase.java
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/ee/appclient/basic/SimpleApplicationClientTestCase2.java
  testsuite/integration/basic/src/test/resources/app-client.yml
Labels: Feature, deps-ok, Critical

#15983 [WFLY-16792] Connector: remove config-properties attribute from resou…
  connector/src/main/java/org/jboss/as/connector/subsystems/resourceadapters/CommonAttributes.java
Labels: deps-ok, Critical

#16046 WFLY-16434 ArtifactFactoryService class should invoke AbstractArtifac…
  batch-jberet/src/main/java/org/wildfly/extension/batch/jberet/deployment/ArtifactFactoryService.java
Labels: deps-ok

#16074 [WFLY-17014] Make Galleon provisioning content zips unique per release
  ee-9/common-microprofile/assembly.xml
  ee-9/common/assembly.xml
  ee-9/feature-pack/pom.xml
  ee-9/galleon-content-microprofile/assembly.xml
  ee-9/galleon-content/assembly.xml
  ee-feature-pack/common/assembly.xml
  ee-feature-pack/ee-10-api/assembly.xml
  ee-feature-pack/galleon-common/assembly.xml
  ee-feature-pack/galleon-content/assembly.xml
  ee-feature-pack/galleon-feature-pack/pom.xml
  ee-feature-pack/pruned/assembly.xml
  galleon-pack/galleon-content/assembly.xml
  servlet-feature-pack/common/assembly.xml
  servlet-feature-pack/galleon-common/assembly.xml
  servlet-feature-pack/galleon-pruned/assembly.xml
Labels: deps-ok, Critical

#15979 WFLY-16951 Add necessary individual elytron component jars to jboss-client.jar
  client/shade/pom.xml
Labels: deps-ok, Critical

#16086 [WFLY-16813] [WFLY-17022] Upgrade to MP RM 3.0 and SR RM 4.0.0.RC3
  microprofile/galleon-common/src/main/resources/modules/system/layers/base/io/smallrye/reactive/messaging/main/module.xml
  microprofile/galleon-common/src/main/resources/modules/system/layers/base/org/eclipse/microprofile/reactive-messaging/api/main/module.xml
  pom.xml
Labels: deps-ok

#16077 [WFLY-17004] Add a hibernate-search layer
  docs/src/main/asciidoc/_galleon/Galleon_layers.adoc
  ee-9/galleon-content/src/main/resources/layers/standalone/hibernate-search/layer-spec.xml
  ee-feature-pack/galleon-content/src/main/resources/layers/standalone/hibernate-search/layer-spec.xml
  testsuite/integration/basic/pom.xml
  testsuite/layers/pom.xml
  testsuite/layers/src/test/java/org/jboss/as/test/layers/LayersTestCase.java
  testsuite/pom.xml
  testsuite/preview/basic/pom.xml
  testsuite/preview/pom.xml
Labels: deps-ok, Critical

#16054 [WFLY-16228] Don't duplicate Jackson jakarta-rs deps between common-ee and standard-ee
  boms/common-ee/pom.xml
Labels: ready-for-merge, deps-ok

#15608 [WFLY-14693]: Support ActiveMQ Artemis' "auto-delete-created-queue" property.
  messaging-activemq/subsystem/src/main/java/org/wildfly/extension/messaging/activemq/AddressSettingAdd.java
  messaging-activemq/subsystem/src/main/java/org/wildfly/extension/messaging/activemq/AddressSettingDefinition.java
  messaging-activemq/subsystem/src/main/java/org/wildfly/extension/messaging/activemq/AddressSettingsResolveHandler.java
  messaging-activemq/subsystem/src/main/java/org/wildfly/extension/messaging/activemq/MessagingSubsystemParser_14_0.java
  messaging-activemq/subsystem/src/main/java/org/wildfly/extension/messaging/activemq/MessagingTransformerRegistration.java
  messaging-activemq/subsystem/src/main/resources/org/wildfly/extension/messaging/activemq/LocalDescriptions.properties
  messaging-activemq/subsystem/src/main/resources/schema/wildfly-messaging-activemq_14_0.xsd
Labels: Feature, deps-ok, Critical

#16058 [WFLY-16987] Use Undertow related artifacts brought in by wildfly-cor…
  boms/standard-ee/pom.xml
  pom.xml
Labels: deps-ok

#16088 WFLY-16952 JsonSchemaValidationTest failed with a java.lang.NoClassDefFoundError
  testsuite/integration/microprofile-tck/health/pom.xml
Labels: deps-ok

#16071 [WFLY-16969] ValueManagedReference must use java.util.function.Supplier instead of org.jboss.msc.value.Value
  connector/src/main/java/org/jboss/as/connector/services/resourceadapters/AdminObjectReferenceFactoryService.java
  connector/src/main/java/org/jboss/as/connector/services/resourceadapters/ConnectionFactoryReferenceFactoryService.java
  connector/src/main/java/org/jboss/as/connector/services/resourceadapters/deployment/AbstractResourceAdapterDeploymentService.java
  connector/src/main/java/org/jboss/as/connector/subsystems/datasources/DataSourceReferenceFactoryService.java
  ejb3/src/main/java/org/jboss/as/ejb3/component/EJBContainerInterceptorsViewConfigurator.java
  ejb3/src/main/java/org/jboss/as/ejb3/component/RemoteHomeViewInstanceFactory.java
  ejb3/src/main/java/org/jboss/as/ejb3/component/session/StatelessRemoteViewInstanceFactory.java
  ejb3/src/main/java/org/jboss/as/ejb3/component/stateful/StatefulRemoteViewInstanceFactory.java
  ejb3/src/main/java/org/jboss/as/ejb3/interceptor/server/ServerInterceptorCache.java
  ejb3/src/main/java/org/jboss/as/ejb3/remote/RemoteViewManagedReferenceFactory.java
  jpa/subsystem/src/main/java/org/jboss/as/jpa/injectors/PersistenceContextInjectionSource.java
  jpa/subsystem/src/main/java/org/jboss/as/jpa/injectors/PersistenceUnitInjectionSource.java
  mail/src/main/java/org/jboss/as/mail/extension/MailSessionManagedReferenceFactory.java
  messaging-activemq/subsystem/src/main/java/org/wildfly/extension/messaging/activemq/BinderServiceUtil.java
  messaging-activemq/subsystem/src/main/java/org/wildfly/extension/messaging/activemq/deployment/MessagingJMSDestinationManagedReferenceFactory.java
  naming/src/main/java/org/jboss/as/naming/ValueManagedReference.java
  weld/subsystem/src/main/java/org/jboss/as/weld/deployment/processors/WeldBeanManagerServiceProcessor.java
Labels: deps-ok

#16081 [WFLY-16923] Correct problematic language in the Credential Store doc…
  docs/src/main/asciidoc/_elytron/Credential_Store.adoc
Labels: ready-for-merge

#16082 [WFLY-16238] Don't export traces by default
  microprofile/opentracing-extension/src/main/java/org/wildfly/extension/microprofile/opentracing/TracerAttributes.java
  microprofile/opentracing-extension/src/main/java/org/wildfly/extension/microprofile/opentracing/TracingExtensionLogger.java
  microprofile/opentracing-extension/src/main/java/org/wildfly/extension/microprofile/opentracing/spi/sender/WildFlySenderFactory.java
Labels: Blocker, deps-ok

#16091 [WFLY-17002]:Upgrade to jaxb-ri 4.0.1
  pom.xml
Labels: deps-ok, Critical

#15741 [WFLY-16591] Remove the org.jboss.resteasy.jose-jwt module
  boms/standard-ee/pom.xml
  ee-feature-pack/common/pom.xml
  ee-feature-pack/common/src/main/resources/license/ee-feature-pack-common-licenses.xml
  ee-feature-pack/common/src/main/resources/modules/system/layers/base/org/jboss/resteasy/jose-jwt/main/module.xml
  testsuite/integration/microprofile-tck/jwt/pom.xml
  testsuite/layers/src/test/java/org/jboss/as/test/layers/LayersTestCase.java
Labels: deps-changed, Critical

#16097 [WFLY-17037] Upgrade ironjacamar to 1.5.9.Final
  pom.xml
Labels: deps-ok

#16067 [WFLY-16988]:Remove xalan dependency
  boms/common-ee/pom.xml
  ee-9/galleon-content/src/main/resources/configs/standalone/model.xml
  ee-feature-pack/common/src/main/resources/modules/system/layers/base/org/apache/santuario/xmlsec/main/module.xml
  ee-feature-pack/common/src/main/resources/modules/system/layers/base/org/apache/ws/security/main/module.xml
  ee-feature-pack/common/src/main/resources/modules/system/layers/base/org/jboss/as/appclient/main/module.xml
  ee-feature-pack/common/src/main/resources/modules/system/layers/base/org/jboss/as/webservices/server/integration/main/module.xml
  jdr/pom.xml
  pom.xml
  servlet-feature-pack/common/pom.xml
  servlet-feature-pack/common/src/main/resources/license/servlet-feature-pack-common-licenses.xml
  servlet-feature-pack/common/src/main/resources/modules/system/layers/base/org/apache/xalan/main/module.xml
  servlet-feature-pack/galleon-common/src/main/resources/configs/standalone/model.xml
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/ejb/remote/requestdeserialization/AbstactUnmarshallingFilterTestCase.java
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/ejb/remote/requestdeserialization/UnmarshallingFilterDisabledTestCase.java
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/ejb/remote/requestdeserialization/UnmarshallingFilterTestCase.java
Labels: deps-changed, Critical

#16095 [WFLY-16970] ValueManagedReferenceFactory must use j.u.f.Supplier instead of o.j.m.v.Value
  bean-validation/src/main/java/org/jboss/as/ee/beanvalidation/BeanValidationFactoryDeployer.java
  bean-validation/src/main/java/org/jboss/as/ee/beanvalidation/BeanValidationFactoryResourceReferenceProcessor.java
  ee-9/source-transform/ee/src/main/java/org/jboss/as/ee/component/EnvEntryInjectionSource.java
  ee-9/source-transform/ee/src/main/java/org/jboss/as/ee/naming/ApplicationContextProcessor.java
  ee-9/source-transform/ee/src/main/java/org/jboss/as/ee/naming/InApplicationClientBindingProcessor.java
  ee-9/source-transform/ee/src/main/java/org/jboss/as/ee/naming/ModuleContextProcessor.java
  ee/src/main/java/org/jboss/as/ee/component/EnvEntryInjectionSource.java
  ee/src/main/java/org/jboss/as/ee/naming/ApplicationContextProcessor.java
  ee/src/main/java/org/jboss/as/ee/naming/InApplicationClientBindingProcessor.java
  ee/src/main/java/org/jboss/as/ee/naming/ModuleContextProcessor.java
  ejb3/src/main/java/org/jboss/as/ejb3/deployment/processors/IIOPJndiBindingProcessor.java
  iiop-openjdk/src/main/java/org/wildfly/iiop/openjdk/service/CorbaServiceUtil.java
  jpa/subsystem/src/main/java/org/jboss/as/jpa/processor/PersistenceUnitServiceHandler.java
  messaging-activemq/subsystem/src/main/java/org/wildfly/extension/messaging/activemq/BinderServiceUtil.java
  naming/src/main/java/org/jboss/as/naming/ManagedReferenceInjector.java
  naming/src/main/java/org/jboss/as/naming/ValueManagedReferenceFactory.java
  naming/src/main/java/org/jboss/as/naming/subsystem/NamingBindingAdd.java
  naming/src/test/java/org/jboss/as/naming/ServiceBasedNamingStoreTestCase.java
  transactions/src/main/java/org/jboss/as/txn/subsystem/TransactionSubsystemAdd.java
Labels: deps-ok

#16028 WFLY-15859 Re-authentication after reboot, even though HttpSession are persisted
  clustering/web/extension/src/main/java/org/wildfly/extension/clustering/web/deployment/DistributableWebDeploymentProcessor.java
  clustering/web/undertow/pom.xml
  clustering/web/undertow/src/main/java/org/wildfly/clustering/web/undertow/UndertowSerializationContextInitializer.java
  clustering/web/undertow/src/main/java/org/wildfly/clustering/web/undertow/UndertowSerializationContextInitializerProvider.java
  clustering/web/undertow/src/main/java/org/wildfly/clustering/web/undertow/elytron/CachedIdentityMarshaller.java
  clustering/web/undertow/src/main/java/org/wildfly/clustering/web/undertow/elytron/ElytronUndertowSerializationContextInitializer.java
  clustering/web/undertow/src/main/java/org/wildfly/clustering/web/undertow/elytron/IdentityContainerMarshaller.java
  clustering/web/undertow/src/main/java/org/wildfly/clustering/web/undertow/elytron/SecurityCacheSerializationContextInitializer.java
  clustering/web/undertow/src/main/java/org/wildfly/clustering/web/undertow/session/DistributableSession.java
  clustering/web/undertow/src/main/java/org/wildfly/clustering/web/undertow/sso/elytron/DistributableSingleSignOn.java
  clustering/web/undertow/src/main/java/org/wildfly/clustering/web/undertow/sso/elytron/DistributableSingleSignOnManager.java
  clustering/web/undertow/src/main/java/org/wildfly/clustering/web/undertow/sso/elytron/DistributableSingleSignOnManagerServiceConfigurator.java
  clustering/web/undertow/src/main/resources/org.wildfly.clustering.web.undertow.sso.elytron.proto
  clustering/web/undertow/src/main/resources/org.wildfly.elytron.web.undertow.server.servlet.proto
  clustering/web/undertow/src/main/resources/org.wildfly.security.cache.proto
  clustering/web/undertow/src/test/java/org/wildfly/clustering/web/undertow/elytron/CachedIdentityMarshallingTestCase.java
  clustering/web/undertow/src/test/java/org/wildfly/clustering/web/undertow/elytron/IdentityContainerMarshallerTestCase.java
  clustering/web/undertow/src/test/java/org/wildfly/clustering/web/undertow/session/DistributableSessionTestCase.java
  ee-feature-pack/common/src/main/resources/modules/system/layers/base/org/wildfly/clustering/web/undertow/main/module.xml
  testsuite/integration/clustering/pom.xml
  testsuite/integration/clustering/src/test/java/org/jboss/as/test/clustering/cluster/web/authentication/BasicAuthenticationWebFailoverTestCase.java
  testsuite/integration/clustering/src/test/java/org/jboss/as/test/clustering/cluster/web/authentication/CustomAuthenticationWebFailoverTestCase.java
  testsuite/integration/clustering/src/test/java/org/jboss/as/test/clustering/cluster/web/authentication/ElytronDomainServerSetupTask.java
  testsuite/integration/clustering/src/test/java/org/jboss/as/test/clustering/cluster/web/authentication/FormAuthenticationWebFailoverTestCase.java
  testsuite/integration/clustering/src/test/java/org/jboss/as/test/clustering/cluster/web/authentication/custom/CustomAuthenticationMechanism.java
  testsuite/integration/clustering/src/test/java/org/jboss/as/test/clustering/cluster/web/authentication/custom/ElytronIdentityStore.java
  testsuite/integration/clustering/src/test/java/org/jboss/as/test/clustering/cluster/web/authentication/custom/LogoutServlet.java
  testsuite/integration/clustering/src/test/java/org/jboss/as/test/clustering/cluster/web/authentication/custom/SecuredServlet.java
  testsuite/integration/clustering/src/test/java/org/jboss/as/test/clustering/cluster/web/authentication/distributable-web.xml
  testsuite/integration/clustering/src/test/resources/beans.xml
Labels: deps-ok, Critical

#16037 [WFLY-16956] Move jboss-ejb-client-legacy to the standard-ee bom as s…
  boms/standard-ee/pom.xml
  pom.xml
Labels: deps-ok

#16099 [WFLY-17020] Upgrade RESTEasy to 6.2.0.Final.
  pom.xml
  testsuite/integration/basic/src/test/java/org/wildfly/test/integration/observability/opentelemetry/BasicOpenTelemetryTestCase.java
  testsuite/integration/basic/src/test/java/org/wildfly/test/integration/observability/opentelemetry/OpenTelemetryNoCdiTestCase.java
  testsuite/integration/manualmode/src/test/java/org/jboss/as/test/manualmode/server/nongraceful/NongracefulStartTestCase.java
  testsuite/integration/manualmode/src/test/java/org/wildfly/test/manual/observability/opentelemetry/ContextPropagationTestCase.java
  testsuite/integration/microprofile/src/test/java/org/wildfly/test/integration/microprofile/opentracing/SimpleRestClientTestCase.java
Labels: deps-ok, Critical

#16101 [WFLY-16296] Re-enable the testsuite/integration/legacy-ejb-client EJ…
  testsuite/integration/legacy-ejb-client/pom.xml
  testsuite/integration/legacy-ejb-client/src/test/java/org/jboss/as/test/integration/legacy/ejb/remote/client/api/EJBClientAPIUsageTestCase.java
Labels: deps-ok

#16104 [WFLY-16808] Upgrade RESTEasy MicroProfile dependencies to 2.0.0.Final.
  pom.xml
Labels: deps-ok, Critical

#16100 [WFLY-16992] Move the generic JMS ra.xml to Connectors 2.1
  ee-feature-pack/common/src/main/resources/modules/system/layers/base/org/jboss/genericjms/main/META-INF/ra.xml
Labels: deps-ok, Critical

#16112 [WFLY-17045] Move RESTEasy Spring to WildFly Preview as there is not …
  boms/preview-ee/pom.xml
  boms/standard-ee/pom.xml
  ee-9/common/pom.xml
  ee-9/common/src/main/resources/license/preview-feature-pack-common-licenses.xml
  ee-9/common/src/main/resources/modules/system/layers/base/org/jboss/resteasy/resteasy-spring/main/module.xml
  ee-9/galleon-content/src/main/resources/feature_groups/jaxrs.xml
  ee-9/galleon-content/src/main/resources/packages/org.jboss.resteasy.resteasy-spring/pm/wildfly/tasks.xml
  ee-feature-pack/common/pom.xml
  ee-feature-pack/common/src/main/resources/license/ee-feature-pack-common-licenses.xml
  jaxrs/src/main/java/org/jboss/as/jaxrs/JaxrsSubsystemDefinition.java
  pom.xml
Labels: deps-changed, Critical

#16111 [WFLY-16854] [WFLY-17023] [WFLY-17024] Update dependencies for Opentelemetry and MicroProfile OpenTracing
  boms/common-ee/pom.xml
  ee-feature-pack/common/pom.xml
  ee-feature-pack/common/src/main/resources/license/ee-feature-pack-common-licenses.xml
  ee-feature-pack/common/src/main/resources/modules/system/layers/base/com/squareup/okhttp3/main/module.xml
  ee-feature-pack/common/src/main/resources/modules/system/layers/base/io/opentelemetry/trace/main/module.xml
  ee-feature-pack/common/src/main/resources/modules/system/layers/base/org/jetbrains/kotlin/kotlin-stdlib/main/module.xml
  pom.xml
  testsuite/layers/src/test/java/org/jboss/as/test/layers/LayersTestCase.java
Labels: deps-changed, Critical

#16089 [WFLY-17023] OpenTracing support is missing kotlin-stdlib
  boms/common-ee/pom.xml
  ee-feature-pack/common/pom.xml
  ee-feature-pack/common/src/main/resources/modules/system/layers/base/com/squareup/okhttp3/main/module.xml
  ee-feature-pack/common/src/main/resources/modules/system/layers/base/org/jetbrains/kotlin/kotlin-stdlib/main/module.xml
  pom.xml
Labels: hold, deps-changed, Critical

#16090 [WFLY-17024] Bump okio version
  pom.xml
Labels: hold, deps-changed, Critical

#15961 [WFLY-16854] Update dependencies for Opentelemetry
  boms/common-ee/pom.xml
  ee-feature-pack/common/pom.xml
  ee-feature-pack/common/src/main/resources/license/ee-feature-pack-common-licenses.xml
  ee-feature-pack/common/src/main/resources/modules/system/layers/base/com/squareup/okhttp3/main/module.xml
  ee-feature-pack/common/src/main/resources/modules/system/layers/base/io/opentelemetry/trace/main/module.xml
  pom.xml
  testsuite/layers/src/test/java/org/jboss/as/test/layers/LayersTestCase.java
Labels: hold, deps-changed

#16102 [WFLY-16988] Limit the JPMS setting needed by AbstactUnmarshallingFil…
  pom.xml
  testsuite/integration/basic/pom.xml
  testsuite/pom.xml
Labels: deps-ok

#16108 [WFLY-17046] Deprecate and reject remaining security-realm references in the Undertow subsystem.
  undertow/src/main/java/org/wildfly/extension/undertow/HttpInvokerDefinition.java
  undertow/src/main/java/org/wildfly/extension/undertow/HttpsListenerAdd.java
  undertow/src/main/java/org/wildfly/extension/undertow/filters/ModClusterService.java
  undertow/src/main/java/org/wildfly/extension/undertow/handlers/ReverseProxyHandlerHost.java
  undertow/src/main/java/org/wildfly/extension/undertow/logging/UndertowLogger.java
  undertow/src/main/resources/org/wildfly/extension/undertow/LocalDescriptions.properties
  undertow/src/main/resources/schema/wildfly-undertow_13_0.xsd
Labels: Blocker, deps-ok, 27.x

#15458 WFLY-16291 WARN if invalid 'database' specified for EJB Database Time…
  ejb3/src/main/java/org/jboss/as/ejb3/logging/EjbLogger.java
  ejb3/src/main/java/org/jboss/as/ejb3/timerservice/persistence/database/DatabaseTimerPersistence.java
Labels: deps-ok

#16096 [WFLY-16629]: Remove org.glassfish:jakarta.json from wildfly-client-all.
  client/shade/pom.xml
Labels: deps-ok, Critical

#14909 WFLY-14947 - Implement the Observability policy - Metrics
  boms/preview-ee/pom.xml
  docs/src/main/asciidoc/_admin-guide/subsystem-configuration/Metrics.adoc
  ee-9/common/pom.xml
  ee-9/common/src/main/resources/modules/system/layers/base/io/micrometer/main/module.xml
  ee-9/common/src/main/resources/modules/system/layers/base/io/prometheus/main/module.xml
  ee-9/common/src/main/resources/modules/system/layers/base/org/latencyutils/main/module.xml
  ee-9/common/src/main/resources/modules/system/layers/base/org/wildfly/extension/micrometer-api/main/module.xml
  ee-9/common/src/main/resources/modules/system/layers/base/org/wildfly/extension/micrometer/main/module.xml
  ee-9/feature-pack/wildfly-feature-pack-build.xml
  ee-9/galleon-content-microprofile/src/main/resources/feature_groups/domain-host-excludes.xml
  ee-9/galleon-content-microprofile/src/main/resources/feature_groups/standalone-ha.xml
  ee-9/galleon-content-microprofile/src/main/resources/feature_groups/standalone-profile.xml
  ee-9/galleon-content/src/main/resources/feature_groups/domain-host-excludes.xml
  ee-9/galleon-content/src/main/resources/feature_groups/micrometer.xml
  ee-9/galleon-content/src/main/resources/feature_groups/standalone-ha.xml
  ee-9/galleon-content/src/main/resources/feature_groups/standalone-profile.xml
  ee-9/galleon-content/src/main/resources/layers/standalone/micrometer/layer-spec.xml
  ee-9/pom.xml
  observability/micrometer-api/pom.xml
  observability/micrometer-api/src/main/java/org/wildfly/extension/micrometer/api/MicrometerCdiExtension.java
  observability/micrometer-api/src/main/resources/META-INF/services/jakarta.enterprise.inject.spi.Extension
  observability/micrometer/pom.xml
  observability/micrometer/src/main/java/org/wildfly/extension/micrometer/MicrometerCollectorService.java
  observability/micrometer/src/main/java/org/wildfly/extension/micrometer/MicrometerContextService.java
  observability/micrometer/src/main/java/org/wildfly/extension/micrometer/MicrometerDependencyProcessor.java
  observability/micrometer/src/main/java/org/wildfly/extension/micrometer/MicrometerDeploymentService.java
  observability/micrometer/src/main/java/org/wildfly/extension/micrometer/MicrometerExtensionLogger.java
  observability/micrometer/src/main/java/org/wildfly/extension/micrometer/MicrometerParser.java
  observability/micrometer/src/main/java/org/wildfly/extension/micrometer/MicrometerRegistryService.java
  observability/micrometer/src/main/java/org/wildfly/extension/micrometer/MicrometerSubsystemAdd.java
  observability/micrometer/src/main/java/org/wildfly/extension/micrometer/MicrometerSubsystemDefinition.java
  observability/micrometer/src/main/java/org/wildfly/extension/micrometer/MicrometerSubsystemExtension.java
  observability/micrometer/src/main/java/org/wildfly/extension/micrometer/deployment/MicrometerSubsystemDeploymentProcessor.java
  observability/micrometer/src/main/java/org/wildfly/extension/micrometer/jmx/JmxMetricMetadata.java
  observability/micrometer/src/main/java/org/wildfly/extension/micrometer/jmx/JmxMicrometerCollector.java
  observability/micrometer/src/main/java/org/wildfly/extension/micrometer/metrics/Metric.java
  observability/micrometer/src/main/java/org/wildfly/extension/micrometer/metrics/MetricID.java
  observability/micrometer/src/main/java/org/wildfly/extension/micrometer/metrics/MetricMetadata.java
  observability/micrometer/src/main/java/org/wildfly/extension/micrometer/metrics/MetricRegistration.java
  observability/micrometer/src/main/java/org/wildfly/extension/micrometer/metrics/MicrometerCollector.java
  observability/micrometer/src/main/java/org/wildfly/extension/micrometer/metrics/WildFlyMetric.java
  observability/micrometer/src/main/java/org/wildfly/extension/micrometer/metrics/WildFlyMetricMetadata.java
  observability/micrometer/src/main/java/org/wildfly/extension/micrometer/metrics/WildFlyRegistry.java
  observability/micrometer/src/main/java/org/wildfly/extension/micrometer/model/MicrometerModel.java
  observability/micrometer/src/main/java/org/wildfly/extension/micrometer/model/MicrometerSchema.java
  observability/micrometer/src/main/resources/META-INF/services/org.jboss.as.controller.Extension
  observability/micrometer/src/main/resources/org/wildfly/extension/micrometer/LocalDescriptions.properties
  observability/micrometer/src/main/resources/org/wildfly/extension/micrometer/jmx/jmx-metrics.properties
  observability/micrometer/src/main/resources/schema/wildfly-micrometer_1_0.xsd
  observability/micrometer/src/test/java/org/wildfly/extension/micrometer/SubsystemParsingTestCase.java
  observability/pom.xml
  pom.xml
  testsuite/domain/src/test/java/org/jboss/as/test/integration/domain/HostExcludesTestCase.java
  testsuite/integration/basic/src/test/java/org/wildfly/test/integration/metrics/MetricsFromWildFlyManagementModelTestCase.java
  testsuite/layers/pom.xml
  testsuite/layers/src/test/java/org/jboss/as/test/layers/LayersTestCase.java
  testsuite/preview/basic/pom.xml
  testsuite/preview/basic/src/test/java/org/wildfly/test/preview/observability/micrometer/BasicMicrometerTestCase.java
  testsuite/preview/basic/src/test/java/org/wildfly/test/preview/observability/micrometer/MetricResource.java
  testsuite/preview/pom.xml
Labels: Feature, deps-ok, Critical, 27.x

#16116 WFLY-17049 jboss-ejb-timer-service_2_0.xsd schema is invalid
  ejb3/src/main/resources/schema/jboss-ejb-timer-service_2_0.xsd
Labels: deps-ok

#16117 [WFLY-17021]: Upgrade jboss metadata to 15.2.0.Beta3
  ejb3/src/main/java/org/jboss/as/ejb3/cache/EJBBoundCacheParser.java
  ejb3/src/main/java/org/jboss/as/ejb3/deliveryactive/parser/EJBBoundMdbDeliveryMetaDataParser20.java
  ejb3/src/main/java/org/jboss/as/ejb3/deployment/processors/EjbJarParsingDeploymentUnitProcessor.java
  ejb3/src/main/java/org/jboss/as/ejb3/interceptor/ContainerInterceptorsParser.java
  ejb3/src/main/java/org/jboss/as/ejb3/pool/EJBBoundPoolParser.java
  ejb3/src/main/java/org/jboss/as/ejb3/resourceadapterbinding/parser/EJBBoundResourceAdapterBindingMetaDataParser.java
  ejb3/src/main/java/org/jboss/as/ejb3/security/parser/EJBBoundSecurityMetaDataParser20.java
  ejb3/src/main/java/org/jboss/as/ejb3/security/parser/SecurityRoleMetaDataParser.java
  ejb3/src/main/java/org/jboss/as/ejb3/timerservice/TimerServiceMetaDataSchema.java
  ejb3/src/main/resources/schema/jboss-ejb-cache_2_0.xsd
  ejb3/src/main/resources/schema/jboss-ejb-clustering_2_0.xsd
  ejb3/src/main/resources/schema/jboss-ejb-container-interceptors_2_0.xsd
  ejb3/src/main/resources/schema/jboss-ejb-delivery-active_2_0.xsd
  ejb3/src/main/resources/schema/jboss-ejb-pool_2_0.xsd
  ejb3/src/main/resources/schema/jboss-ejb-resource-adapter-binding_2_0.xsd
  ejb3/src/main/resources/schema/jboss-ejb-security-role_2_0.xsd
  ejb3/src/main/resources/schema/jboss-ejb-security_2_0.xsd
  ejb3/src/main/resources/schema/jboss-ejb-timer-service_3_0.xsd
  pom.xml
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/deployment/classloading/ear/EarManifestDependencyPropagatedTestCase.java
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/deployment/classloading/ear/EjbJarCanAccessOtherEjbJarTestCase.java
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/deployment/classloading/ear/WarCanAccessEjbJarTestCase.java
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/deployment/classloading/transientdependencies/web.xml
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/deployment/dependencies/ear/application.xml
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/deployment/dependencies/ear/web.xml
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/deployment/deploymentoverlay/override.xml
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/deployment/deploymentoverlay/update.xml
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/ee/injection/resource/resourceref/jboss-ejb3.xml
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/ee/injection/resource/resourceref/jboss-web.xml
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/ejb/iiop/naming/jboss-ejb3-naming.xml
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/ejb/iiop/naming/jboss-ejb3.xml
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/ejb/mdb/resourceadapter/jboss-ejb3-relative-path.xml
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/ejb/mdb/resourceadapter/jboss-ejb3.xml
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/ejb/security/callerprincipal/jboss-ejb3.xml
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/ejb/security/ejb-jar.xml
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/ejb/security/jboss-ejb3.xml
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/ejb/servlet/jboss-ejb3.xml
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/messaging/jms/definitions/JMSResourceManagementTestCase.java
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/messaging/jms/definitions/ejb-jar.xml
  testsuite/integration/basic/src/test/resources/org/wildfly/test/integration/weld/builtinBeans/jboss-ejb3.xml
  testsuite/shared/src/main/java/org/wildfly/test/distribution/validation/AbstractValidationUnitTest.java
Labels: deps-ok, Critical

#16084 [WFLY-17021]: Upgrade jboss metadata to 15.2.0.Beta3
  ejb3/src/main/java/org/jboss/as/ejb3/cache/EJBBoundCacheParser.java
  ejb3/src/main/java/org/jboss/as/ejb3/deliveryactive/parser/EJBBoundMdbDeliveryMetaDataParser20.java
  ejb3/src/main/java/org/jboss/as/ejb3/deployment/processors/EjbJarParsingDeploymentUnitProcessor.java
  ejb3/src/main/java/org/jboss/as/ejb3/interceptor/ContainerInterceptorsParser.java
  ejb3/src/main/java/org/jboss/as/ejb3/pool/EJBBoundPoolParser.java
  ejb3/src/main/java/org/jboss/as/ejb3/resourceadapterbinding/parser/EJBBoundResourceAdapterBindingMetaDataParser.java
  ejb3/src/main/java/org/jboss/as/ejb3/security/parser/EJBBoundSecurityMetaDataParser20.java
  ejb3/src/main/java/org/jboss/as/ejb3/security/parser/SecurityRoleMetaDataParser.java
  ejb3/src/main/java/org/jboss/as/ejb3/timerservice/TimerServiceMetaDataSchema.java
  ejb3/src/main/resources/schema/jboss-ejb-cache_2_0.xsd
  ejb3/src/main/resources/schema/jboss-ejb-clustering_2_0.xsd
  ejb3/src/main/resources/schema/jboss-ejb-container-interceptors_2_0.xsd
  ejb3/src/main/resources/schema/jboss-ejb-delivery-active_2_0.xsd
  ejb3/src/main/resources/schema/jboss-ejb-pool_2_0.xsd
  ejb3/src/main/resources/schema/jboss-ejb-resource-adapter-binding_2_0.xsd
  ejb3/src/main/resources/schema/jboss-ejb-security-role_2_0.xsd
  ejb3/src/main/resources/schema/jboss-ejb-security_2_0.xsd
  ejb3/src/main/resources/schema/jboss-ejb-timer-service_3_0.xsd
  pom.xml
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/deployment/classloading/ear/EarManifestDependencyPropagatedTestCase.java
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/deployment/classloading/ear/EjbJarCanAccessOtherEjbJarTestCase.java
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/deployment/classloading/ear/WarCanAccessEjbJarTestCase.java
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/deployment/classloading/transientdependencies/web.xml
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/deployment/dependencies/ear/application.xml
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/deployment/dependencies/ear/web.xml
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/deployment/deploymentoverlay/override.xml
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/deployment/deploymentoverlay/update.xml
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/ee/injection/resource/resourceref/jboss-ejb3.xml
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/ee/injection/resource/resourceref/jboss-web.xml
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/ejb/iiop/naming/jboss-ejb3-naming.xml
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/ejb/iiop/naming/jboss-ejb3.xml
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/ejb/mdb/resourceadapter/jboss-ejb3-relative-path.xml
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/ejb/mdb/resourceadapter/jboss-ejb3.xml
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/ejb/security/callerprincipal/jboss-ejb3.xml
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/ejb/security/ejb-jar.xml
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/ejb/security/jboss-ejb3.xml
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/ejb/servlet/jboss-ejb3.xml
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/messaging/jms/definitions/JMSResourceManagementTestCase.java
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/messaging/jms/definitions/ejb-jar.xml
  testsuite/integration/basic/src/test/resources/org/wildfly/test/integration/weld/builtinBeans/jboss-ejb3.xml
  testsuite/shared/src/main/java/org/wildfly/test/distribution/validation/AbstractValidationUnitTest.java
Labels: deps-ok, Critical

#15813 [WFLY-16658] Update some obsolete contents in wildfly extension documentation
  docs/src/main/asciidoc/_extending-wildfly/Example_subsystem.adoc
  docs/src/main/asciidoc/downloads/acme-subsystem.zip
Labels: deps-changed

#16119 WFLY-17054 Remove superfluous jboss-ejb-timer-service_3_0.xsd
  ejb3/src/main/java/org/jboss/as/ejb3/timerservice/TimerServiceMetaDataSchema.java
  ejb3/src/main/resources/schema/jboss-ejb-timer-service_2_0.xsd
  ejb3/src/main/resources/schema/jboss-ejb-timer-service_3_0.xsd
Labels: deps-ok

#16122 [WFLY-17019] Remove build.shibboleth.net from the repository set
  pom.xml
Labels: deps-ok

#16105 GitHub Workflows security hardening
  .github/workflows/cloud-test-pr-trigger.yml
  .github/workflows/dep-diff-workflow_run.yml
Labels: deps-changed

#16126 [WFLY-17053] Drop source transformation for Mail subsystem
  boms/standard-ee/pom.xml
  ee-9/common/src/main/resources/license/preview-feature-pack-common-licenses.xml
  ee-9/source-transform/mail/pom.xml
  ee-9/source-transform/pom.xml
  ee-feature-pack/common/pom.xml
  ee-feature-pack/common/src/main/resources/license/ee-feature-pack-common-licenses.xml
  ee-feature-pack/common/src/main/resources/modules/system/layers/base/org/jboss/as/mail/main/module.xml
  mail/pom.xml
  mail/src/main/java/org/jboss/as/mail/extension/DirectMailSessionService.java
  mail/src/main/java/org/jboss/as/mail/extension/MailDependenciesProcessor.java
  mail/src/main/java/org/jboss/as/mail/extension/MailLogger.java
  mail/src/main/java/org/jboss/as/mail/extension/MailSessionDefinition.java
  mail/src/main/java/org/jboss/as/mail/extension/MailSessionDefinitionAnnotationProcessor.java
  mail/src/main/java/org/jboss/as/mail/extension/MailSessionService.java
  mail/src/main/java/org/jboss/as/mail/extension/SessionProvider.java
  mail/src/main/java/org/jboss/as/mail/extension/SessionProviderFactory.java
  mail/src/test/java/org/jboss/as/mail/extension/MailSubsystem20TestCase.java
  mail/src/test/java/org/jboss/as/mail/extension/MailSubsystem30TestCase.java
  mail/src/test/java/org/jboss/as/mail/extension/MailSubsystem40TestCase.java
  mail/src/test/java/org/jboss/as/mail/extension/MailSubsystemTestBase.java
Labels: deps-changed

#16128 WFLY-17055 Upgrade Infinispan to 14.0.0.Final
  pom.xml
Labels: deps-ok

#16127 [WFLY-15271]: Update test org.wildfly.test.integration.vdx.standalone…
  testsuite/integration/vdx/src/test/java/org/wildfly/test/integration/vdx/standalone/MessagingTestCase.java
  testsuite/integration/vdx/src/test/resources/org/wildfly/test/integration/vdx/transformations/messaging/AddSecurityElementToEndOfSubsystem.groovy
Labels: deps-ok
