Repository wildfly/wildfly, pull requests merged in 2022-01, with the labels that each got.

#15051 WFLY-15857 Improve org.jboss.as.ejb3.deployment.processors.annotation…
  ejb3/src/main/java/org/jboss/as/ejb3/deployment/processors/annotation/ScheduleAnnotationInformationFactory.java
  ejb3/src/main/java/org/jboss/as/ejb3/logging/EjbLogger.java
Labels: ready-for-merge, deps-ok

#15042 [WFLY-9566] Update EclipseLink module add dependency on javax.json.api
  ee-feature-pack/common/src/main/resources/modules/system/layers/base/org/eclipse/persistence/main/module.xml
Labels: ready-for-merge, deps-ok

#15037 [WFLY-15657] Add more information to jaas-realm documentation
  docs/src/main/asciidoc/_elytron/Elytron_Subsystem.adoc
  docs/src/main/asciidoc/_elytron/Subsystem_Component_Documentation.adoc
  docs/src/main/asciidoc/_elytron/components/JAAS_Security_Realm.adoc
Labels: ready-for-merge, deps-ok

#15000 WFLY-15792 Simplify getTimeZone in CalendarBasedTimeout and remove re…
  ejb3/src/main/java/org/jboss/as/ejb3/logging/EjbLogger.java
  ejb3/src/main/java/org/jboss/as/ejb3/timerservice/schedule/CalendarBasedTimeout.java
Labels: ready-for-merge, deps-ok

#14928 [WFLY-15719] Disabling ScriptAssertTestCase on JDK15+ because JavaScript engine have been removed since JDK15 including
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/beanvalidation/hibernate/scriptassert/ScriptAssertTestCase.java
Labels: ready-for-merge, deps-ok

#14412 [WFLY-13793]: Allow remote jms queue/topic not to use legacy amq1 prefix.
  docs/src/main/asciidoc/_admin-guide/subsystem-configuration/Messaging_Connect_a_pooled-connection-factory_to_a_Remote_Artemis_Server.adoc
  messaging-activemq/subsystem/src/main/java/org/wildfly/extension/messaging/activemq/MessagingSubsystemParser_14_0.java
  messaging-activemq/subsystem/src/main/java/org/wildfly/extension/messaging/activemq/MessagingTransformerRegistration.java
  messaging-activemq/subsystem/src/main/java/org/wildfly/extension/messaging/activemq/deployment/JMSDestinationDefinitionInjectionSource.java
  messaging-activemq/subsystem/src/main/java/org/wildfly/extension/messaging/activemq/jms/DestinationConfiguration.java
  messaging-activemq/subsystem/src/main/java/org/wildfly/extension/messaging/activemq/jms/ExternalJMSQueueAdd.java
  messaging-activemq/subsystem/src/main/java/org/wildfly/extension/messaging/activemq/jms/ExternalJMSQueueDefinition.java
  messaging-activemq/subsystem/src/main/java/org/wildfly/extension/messaging/activemq/jms/ExternalJMSQueueService.java
  messaging-activemq/subsystem/src/main/java/org/wildfly/extension/messaging/activemq/jms/ExternalJMSTopicAdd.java
  messaging-activemq/subsystem/src/main/java/org/wildfly/extension/messaging/activemq/jms/ExternalJMSTopicDefinition.java
  messaging-activemq/subsystem/src/main/java/org/wildfly/extension/messaging/activemq/jms/ExternalJMSTopicService.java
  messaging-activemq/subsystem/src/main/resources/org/wildfly/extension/messaging/activemq/LocalDescriptions.properties
  messaging-activemq/subsystem/src/main/resources/schema/wildfly-messaging-activemq_14_0.xsd
  messaging-activemq/subsystem/src/test/java/org/wildfly/extension/messaging/activemq/MessagingActiveMQSubsystem_14_0_TestCase.java
  messaging-activemq/subsystem/src/test/resources/org/wildfly/extension/messaging/activemq/subsystem_14_0.xml
  messaging-activemq/subsystem/src/test/resources/org/wildfly/extension/messaging/activemq/subsystem_14_0_reject_transform.xml
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/messaging/jms/external/prefix/AnnotatedLegacyPrefixMessagingServlet.java
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/messaging/jms/external/prefix/AnnotatedMessagingServlet.java
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/messaging/jms/external/prefix/ExternalJMSDestinationDefinitionLegacyPrefixMessagingDeploymentTestCase.java
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/messaging/jms/external/prefix/ExternalJMSDestinationDefinitionMessagingDeploymentTestCase.java
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/messaging/jms/external/prefix/QueueMDB.java
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/messaging/jms/external/prefix/TopicMDB.java
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/messaging/mgmt/ExternalJMSDestinationManagementTestCase.java
  testsuite/shared/src/main/java/org/jboss/as/test/integration/common/jms/ActiveMQProviderJMSOperations.java
  testsuite/shared/src/main/java/org/jboss/as/test/integration/common/jms/JMSOperations.java
  testsuite/shared/src/main/java/org/jboss/as/test/integration/common/jms/RemoteActiveMQProviderJMSOperations.java
Labels: ready-for-merge, deps-ok

#14243 [WFLY-14121] mod_cluster undertow context is not started if server is
  mod_cluster/undertow/src/main/java/org/wildfly/mod_cluster/undertow/LocationContext.java
  mod_cluster/undertow/src/main/java/org/wildfly/mod_cluster/undertow/UndertowContext.java
  mod_cluster/undertow/src/main/java/org/wildfly/mod_cluster/undertow/UndertowEventHandlerAdapterService.java
  mod_cluster/undertow/src/main/java/org/wildfly/mod_cluster/undertow/UndertowHost.java
  mod_cluster/undertow/src/test/java/org/wildfly/mod_cluster/undertow/UndertowContextTestCase.java
  testsuite/integration/clustering/pom.xml
  testsuite/integration/clustering/src/test/java/org/jboss/as/test/clustering/cluster/modcluster/StartWorkersInSuspendedModeTestCase.java
  testsuite/shared/src/main/java/org/jboss/as/test/shared/ServerReload.java
  undertow/src/main/java/org/wildfly/extension/undertow/Host.java
Labels: ready-for-merge, deps-ok

#14806 [WFLY-15514] "ThreadLocal" variables clean up (jsf)
  jsf/injection/src/main/java/org/jboss/as/jsf/injection/MyFacesInjectionProvider.java
  jsf/injection/src/main/java/org/jboss/as/jsf/injection/MyFacesInjectionProviderFactory.java
  jsf/injection/src/main/java/org/jboss/as/jsf/injection/MyFacesLifecycleProvider.java
  jsf/injection/src/main/java/org/jboss/as/jsf/injection/MyFacesLifecycleProviderFactory.java
  web-common/src/main/java/org/jboss/as/web/common/StartupContext.java
Labels: ready-for-merge, deps-ok

#14890 [WFLY-10862] Log warning when MP Health reports DOWN
  microprofile/health-smallrye/src/main/java/org/wildfly/extension/microprofile/health/MicroProfileHealthReporter.java
  microprofile/health-smallrye/src/main/java/org/wildfly/extension/microprofile/health/_private/MicroProfileHealthLogger.java
Labels: ready-for-merge, deps-ok

#14469 [WFLY-15004] Use Arquillian 1.7.0.Alpha10 and the WildFly Arquillian …
  pom.xml
  testsuite/integration/basic/pom.xml
  testsuite/integration/rts/pom.xml
  testsuite/integration/rts/src/test/config/arq/arquillian.xml
  testsuite/integration/xts/pom.xml
  testsuite/integration/xts/src/test/config/arq/arquillian.xml
Labels: ready-for-merge, deps-ok

#15064 [WFLY-15441] / [WFLY-15821] / [WFLY-15878] Move WildFly Preview to a native jakarta namespace variant of Elytron and also upgrade Elytron EE and Elytron Web
  ee-9/common/pom.xml
  ee-9/common/src/main/resources/license/preview-feature-pack-common-licenses.xml
  ee-9/common/src/main/resources/modules/system/layers/base/org/wildfly/security/jakarta/client/resteasy/main/module.xml
  ee-9/common/src/main/resources/modules/system/layers/base/org/wildfly/security/jakarta/client/webservices/main/module.xml
  ee-9/feature-pack/pom.xml
  ee-9/pom.xml
Labels: ready-for-merge, deps-ok

#15066 [WFLY-15874] Change default behaviour to resolve jboss parent pom
  pom.xml
Labels: deps-ok

#15058 WFLY-15851 Weld - fix UrlScanner to correctly reference child file instead of parent directory
  weld/subsystem/src/main/java/org/jboss/as/weld/deployment/processors/UrlScanner.java
Labels: deps-ok

#15067 [WFLY-15876] Add IntelliJ IDEA import maven hint to doc
  docs/src/main/asciidoc/_hacking/contributing.adoc
Labels: deps-ok

#15046 Fix for WFLY-15854, Upgrade bootable jar to 7.0.0.Final
  pom.xml
Labels: deps-ok

#15045 [26.x] Fix for WFLY-15854, Upgrade bootable jar to 7.0.0.Final
  pom.xml
Labels: 26.x

#15034 [WFLY-15845] Upgrade WildFly Core 18.0.1.Final
  pom.xml
Labels: ready-for-merge, 26.x

#15063 Upgrade SmallRye Config and RESTEasy MicroProfile to MP 5.0 implementations
  ee-9/pom.xml
  pom.xml
  testsuite/integration/microprofile-tck/pom.xml
  testsuite/integration/microprofile-tck/rest-client/pom.xml
Labels: deps-ok

#15054 WFLY-15864 Replace new Date().getTime() with System.currentTimeMillis()
  ejb3/src/main/java/org/jboss/as/ejb3/timerservice/TimerTask.java
  jdr/jboss-as-jdr/src/main/java/org/jboss/as/jdr/JdrReport.java
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/ejb/interceptor/annotatedejbclient/AnnotatedEJBClientInterceptorTestCase.java
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/ejb/security/runas/TimerTesterBean.java
Labels: ready-for-merge, deps-ok

#15049 [WFLY-15410] Modify SecurityAuthCommandsTestCase for WFCORE-5602
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/management/cli/SecurityAuthCommandsTestCase.java
Labels: ready-for-merge, deps-ok

#14887 [WFLY-15524]: Upgrade netty from 4.1.68 to 4.1.70.
  client/shade/pom.xml
  clustering/infinispan/extension/pom.xml
  ee-9/common/src/main/resources/modules/system/layers/base/org/apache/activemq/artemis/main/module.xml
  ee-9/common/src/main/resources/modules/system/layers/base/org/apache/activemq/artemis/ra/main/module.xml
  ee-feature-pack/common/pom.xml
  ee-feature-pack/common/src/main/resources/license/ee-feature-pack-common-licenses.xml
  ee-feature-pack/common/src/main/resources/modules/system/layers/base/io/netty/netty-buffer/main/module.xml
  ee-feature-pack/common/src/main/resources/modules/system/layers/base/io/netty/netty-codec-http/main/module.xml
  ee-feature-pack/common/src/main/resources/modules/system/layers/base/io/netty/netty-codec-socks/main/module.xml
  ee-feature-pack/common/src/main/resources/modules/system/layers/base/io/netty/netty-codec/main/module.xml
  ee-feature-pack/common/src/main/resources/modules/system/layers/base/io/netty/netty-common/main/module.xml
  ee-feature-pack/common/src/main/resources/modules/system/layers/base/io/netty/netty-handler-proxy/main/module.xml
  ee-feature-pack/common/src/main/resources/modules/system/layers/base/io/netty/netty-handler/main/module.xml
  ee-feature-pack/common/src/main/resources/modules/system/layers/base/io/netty/netty-resolver/main/module.xml
  ee-feature-pack/common/src/main/resources/modules/system/layers/base/io/netty/netty-transport-native-epoll/main/module.xml
  ee-feature-pack/common/src/main/resources/modules/system/layers/base/io/netty/netty-transport-native-kqueue/main/module.xml
  ee-feature-pack/common/src/main/resources/modules/system/layers/base/io/netty/netty-transport-native-unix-common/main/module.xml
  ee-feature-pack/common/src/main/resources/modules/system/layers/base/io/netty/netty-transport/main/module.xml
  ee-feature-pack/common/src/main/resources/modules/system/layers/base/org/apache/activemq/artemis/journal/main/module.xml
  ee-feature-pack/common/src/main/resources/modules/system/layers/base/org/apache/activemq/artemis/main/module.xml
  ee-feature-pack/common/src/main/resources/modules/system/layers/base/org/apache/activemq/artemis/protocol/amqp/main/module.xml
  ee-feature-pack/common/src/main/resources/modules/system/layers/base/org/apache/activemq/artemis/protocol/hornetq/main/module.xml
  ee-feature-pack/common/src/main/resources/modules/system/layers/base/org/apache/activemq/artemis/protocol/stomp/main/module.xml
  ee-feature-pack/common/src/main/resources/modules/system/layers/base/org/apache/activemq/artemis/ra/main/module.xml
  ee-feature-pack/common/src/main/resources/modules/system/layers/base/org/hornetq/client/main/module.xml
  ee-feature-pack/common/src/main/resources/modules/system/layers/base/org/infinispan/client/hotrod/main/module.xml
  ee-feature-pack/common/src/main/resources/modules/system/layers/base/org/jboss/as/clustering/infinispan/main/module.xml
  ee-feature-pack/common/src/main/resources/modules/system/layers/base/org/jboss/xnio/netty/netty-xnio-transport/main/module.xml
  ee-feature-pack/common/src/main/resources/modules/system/layers/base/org/wildfly/extension/messaging-activemq/main/module.xml
  ee-feature-pack/galleon-common/src/main/resources/packages/io.netty.netty-transport-native-epoll/pm/wildfly/tasks.xml
  ee-feature-pack/galleon-common/src/main/resources/packages/io.netty.netty-transport-native-kqueue/pm/wildfly/tasks.xml
  messaging-activemq/subsystem/pom.xml
  microprofile/galleon-common/pom.xml
  microprofile/galleon-common/src/main/resources/modules/system/layers/base/io/netty/netty-codec-dns/main/module.xml
  microprofile/galleon-common/src/main/resources/modules/system/layers/base/io/netty/netty-codec-http2/main/module.xml
  microprofile/galleon-common/src/main/resources/modules/system/layers/base/io/netty/netty-resolver-dns/main/module.xml
  microprofile/galleon-common/src/main/resources/modules/system/layers/base/io/vertx/core/main/module.xml
  microprofile/reactive-messaging-smallrye/extension/pom.xml
  pom.xml
  testsuite/integration/basic/pom.xml
  testsuite/integration/elytron/pom.xml
  testsuite/integration/smoke/pom.xml
  testsuite/shared/pom.xml
  webservices/tests-integration/pom.xml
Labels: ready-for-merge, deps-changed

#14850 [WFLY-15579] Upgrade google guava 31.0.1-jre
  pom.xml
Labels: ready-for-merge, deps-changed

#15073 [WFLY-15881]: ExternalJMSDestinationDefinitionLegacyPrefixMessagingDe…
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/messaging/jms/external/prefix/ExternalJMSDestinationDefinitionLegacyPrefixMessagingDeploymentTestCase.java
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/messaging/jms/external/prefix/ExternalJMSDestinationDefinitionMessagingDeploymentTestCase.java
Labels: deps-ok

#15076 WFLY-15886 Using Objects.equals() in ejb3 DeploymentModuleIdentifier.equals()
  ejb3/src/main/java/org/jboss/as/ejb3/deployment/DeploymentModuleIdentifier.java
Labels: deps-ok

#15065 [WFLY-15879] Exclude the log4j-api JAR from getting transformed.
  ee-9/feature-pack/pom.xml
Labels: deps-ok

#15078 [WFLY-15899] Upgrade WildFly Core 19.0.0.Beta2
  pom.xml
Labels: deps-ok

#15074 [WFLY-15883] Upgrade protobuf version to 3.19.2
  pom.xml
Labels: hold, deps-ok

#15047 [WFLY-15855] MP Health subsytem property empty-startup-checks-status …
  microprofile/galleon-common/src/main/resources/layers/standalone/microprofile-health/layer-spec.xml
  microprofile/galleon-common/src/main/resources/packages/docs.examples/content/docs/examples/enable-microprofile.cli
  testsuite/shared/src/main/java/org/wildfly/test/distribution/validation/AbstractValidationUnitTest.java
Labels: deps-ok

#15094 [main] [WFLY-15903] Remove Jaeger dep from OpenTelemetry module
  ee-feature-pack/common/src/main/resources/modules/system/layers/base/io/opentelemetry/trace/main/module.xml
Labels: deps-ok

#15095 WFLY-15917: Upgrade HAL to 3.4.4.Final
  pom.xml
Labels: deps-ok

#15086 [WFLY-15904] Update test depedency nimbus-jose-jwt from 8.11 to 8.23
  pom.xml
Labels: deps-ok

#15083 [26.x][WFLY-15883] Update protobuf to 3.19.2 (resolves CVE-2021-22569)
  pom.xml
Labels: 26.x

#15085 WFLY-15894: Upgrade HAL to 3.4.4.Final
  pom.xml
Labels: 26.x

#15077 WFLY-10886: change AbstractJMSContext.getContext from synchronized me…
  messaging-activemq/injection/pom.xml
  messaging-activemq/injection/src/main/java/org/wildfly/extension/messaging/activemq/deployment/injection/AbstractJMSContext.java
  messaging-activemq/injection/src/test/java/org/wildfly/extension/messaging/activemq/deployment/injection/AbstractJMSContextTestCase.java
Labels: deps-ok

#15059 [WFLY-15873] Remove Elytron OIDC Client dependencies from WildFly
  pom.xml
Labels: deps-ok

#15060 [26.x][WFLY-15873] Remove Elytron OIDC Client dependencies from WildFly
  pom.xml
Labels: core-upgrade-needed, 26.x

#15104 [WFLY-15902] Upgrade WildFly Core 18.0.3.Final
  pom.xml
Labels: Blocker, 26.x

#15100 [WFLY-15925] Upgrade RESTEasy to 6.0.0.Final for WildFly Preview.
  ee-9/pom.xml
  testsuite/integration/microprofile-tck/pom.xml
Labels: deps-ok, EE9

#15080 WFLY-15897 Messaging BroadcastGroupDefinition & DiscoveryGroupDefinition fixes
  messaging-activemq/injection/src/main/java/org/wildfly/extension/messaging/activemq/logging/MessagingLogger.java
  messaging-activemq/subsystem/src/main/java/org/wildfly/extension/messaging/activemq/BroadcastGroupDefinition.java
  messaging-activemq/subsystem/src/main/java/org/wildfly/extension/messaging/activemq/BroadcastGroupWriteAttributeHandler.java
  messaging-activemq/subsystem/src/main/java/org/wildfly/extension/messaging/activemq/SocketBroadcastGroupAdd.java
  messaging-activemq/subsystem/src/main/java/org/wildfly/extension/messaging/activemq/SocketDiscoveryGroupAdd.java
  messaging-activemq/subsystem/src/main/java/org/wildfly/extension/messaging/activemq/shallow/TranslatedWriteAttributeHandler.java
Labels: deps-ok

#15098 [WFLY-10975] Fix chapter agroal in the admin guide
  docs/src/main/asciidoc/_admin-guide/subsystem-configuration/Datasources_Agroal.adoc
Labels: deps-ok

#15062 [WFLY-15732] / [WFLY-15356] Remove use of security-plugins from Undertow subsystem.
  clustering/web/undertow/src/main/java/org/wildfly/clustering/web/undertow/sso/AuthenticatedSessionExternalizer.java
  clustering/web/undertow/src/main/java/org/wildfly/clustering/web/undertow/sso/AuthenticatedSessionMarshaller.java
  clustering/web/undertow/src/main/java/org/wildfly/clustering/web/undertow/sso/DistributableSingleSignOn.java
  clustering/web/undertow/src/main/java/org/wildfly/clustering/web/undertow/sso/DistributableSingleSignOnManager.java
  clustering/web/undertow/src/main/java/org/wildfly/clustering/web/undertow/sso/DistributableSingleSignOnManagerServiceConfigurator.java
  clustering/web/undertow/src/main/java/org/wildfly/clustering/web/undertow/sso/InvalidatableSingleSignOn.java
  clustering/web/undertow/src/main/java/org/wildfly/clustering/web/undertow/sso/SessionIdGeneratorServiceConfigurator.java
  clustering/web/undertow/src/main/java/org/wildfly/clustering/web/undertow/sso/SessionListenerServiceConfigurator.java
  clustering/web/undertow/src/main/java/org/wildfly/clustering/web/undertow/sso/SessionManagerRegistry.java
  clustering/web/undertow/src/main/java/org/wildfly/clustering/web/undertow/sso/SessionManagerRegistryServiceConfigurator.java
  clustering/web/undertow/src/main/java/org/wildfly/clustering/web/undertow/sso/UndertowSecuritySerializationContextInitializer.java
  clustering/web/undertow/src/main/java/org/wildfly/clustering/web/undertow/sso/UndertowSingleSignOnManagementProvider.java
  clustering/web/undertow/src/main/resources/io.undertow.security.api.proto
  clustering/web/undertow/src/test/java/org/wildfly/clustering/web/undertow/sso/DistributableSingleSignOnManagerTestCase.java
  clustering/web/undertow/src/test/java/org/wildfly/clustering/web/undertow/sso/DistributableSingleSignOnTestCase.java
  clustering/web/undertow/src/test/java/org/wildfly/clustering/web/undertow/sso/UndertowSecurityMarshallingTestCase.java
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/security/jacc/context/PolicyContextTestCase.java
  undertow/pom.xml
  undertow/src/main/java/org/wildfly/extension/undertow/HostSingleSignOnDefinition.java
  undertow/src/main/java/org/wildfly/extension/undertow/HostSingleSignOnServiceHandler.java
  undertow/src/main/java/org/wildfly/extension/undertow/ServletContainerAdd.java
  undertow/src/main/java/org/wildfly/extension/undertow/ServletContainerService.java
  undertow/src/main/java/org/wildfly/extension/undertow/UndertowRootDefinition.java
  undertow/src/main/java/org/wildfly/extension/undertow/UndertowService.java
  undertow/src/main/java/org/wildfly/extension/undertow/deployment/LogoutSessionListener.java
  undertow/src/main/java/org/wildfly/extension/undertow/deployment/SecurityActions.java
  undertow/src/main/java/org/wildfly/extension/undertow/deployment/SecurityDomainResolvingProcessor.java
  undertow/src/main/java/org/wildfly/extension/undertow/deployment/UndertowDeploymentInfoService.java
  undertow/src/main/java/org/wildfly/extension/undertow/deployment/UndertowDeploymentProcessor.java
  undertow/src/main/java/org/wildfly/extension/undertow/logging/UndertowLogger.java
  undertow/src/main/java/org/wildfly/extension/undertow/security/AccountImpl.java
  undertow/src/main/java/org/wildfly/extension/undertow/security/AuditNotificationReceiver.java
  undertow/src/main/java/org/wildfly/extension/undertow/security/JAASIdentityManagerImpl.java
  undertow/src/main/java/org/wildfly/extension/undertow/security/JbossAuthorizationManager.java
  undertow/src/main/java/org/wildfly/extension/undertow/security/LogoutNotificationReceiver.java
  undertow/src/main/java/org/wildfly/extension/undertow/security/RunAsLifecycleInterceptor.java
  undertow/src/main/java/org/wildfly/extension/undertow/security/SecurityActions.java
  undertow/src/main/java/org/wildfly/extension/undertow/security/SecurityContextAssociationHandler.java
  undertow/src/main/java/org/wildfly/extension/undertow/security/SecurityContextThreadSetupAction.java
  undertow/src/main/java/org/wildfly/extension/undertow/security/UndertowSecurityAttachments.java
  undertow/src/main/java/org/wildfly/extension/undertow/security/digest/DigestAuthenticationMechanism.java
  undertow/src/main/java/org/wildfly/extension/undertow/security/digest/DigestAuthenticationMechanismFactory.java
  undertow/src/main/java/org/wildfly/extension/undertow/security/digest/DigestCredential.java
  undertow/src/main/java/org/wildfly/extension/undertow/security/jacc/HttpServletRequestPolicyContextHandler.java
  undertow/src/main/java/org/wildfly/extension/undertow/security/jaspi/JASPICAuthenticationMechanism.java
  undertow/src/main/java/org/wildfly/extension/undertow/security/jaspi/JASPICContext.java
  undertow/src/main/java/org/wildfly/extension/undertow/security/jaspi/JASPICSecureResponseHandler.java
  undertow/src/main/java/org/wildfly/extension/undertow/security/jaspi/JASPICSecurityContext.java
  undertow/src/main/java/org/wildfly/extension/undertow/security/jaspi/JASPICSecurityContextFactory.java
  undertow/src/main/java/org/wildfly/extension/undertow/security/jaspi/SecurityActions.java
  undertow/src/main/java/org/wildfly/extension/undertow/security/jaspi/modules/HTTPSchemeServerAuthModule.java
  undertow/src/main/java/org/wildfly/extension/undertow/sso/InMemorySingleSignOnManagerServiceConfigurator.java
  undertow/src/main/java/org/wildfly/extension/undertow/sso/NonDistributableSingleSignOnManagementProvider.java
  undertow/src/main/resources/org/wildfly/extension/undertow/LocalDescriptions.properties
Labels: deps-ok, EE9

#15114 [WFLY-15356] Remove the security-plugins module.
  pom.xml
  security/plugins/pom.xml
  security/plugins/src/main/java/org/jboss/as/core/security/AbstractRealmPrincipal.java
  security/plugins/src/main/java/org/jboss/as/core/security/AccountPrincipal.java
  security/plugins/src/main/java/org/jboss/as/core/security/GroupPrincipal.java
  security/plugins/src/main/java/org/jboss/as/core/security/RealmGroup.java
  security/plugins/src/main/java/org/jboss/as/core/security/RealmPrincipal.java
  security/plugins/src/main/java/org/jboss/as/core/security/RealmRole.java
  security/plugins/src/main/java/org/jboss/as/core/security/RealmUser.java
  security/plugins/src/main/java/org/jboss/as/core/security/RolePrincipal.java
  security/plugins/src/main/java/org/jboss/as/core/security/SecurityRealmPrincipal.java
  security/plugins/src/main/java/org/jboss/as/core/security/ServerSecurityManager.java
  security/plugins/src/main/java/org/jboss/as/core/security/SimplePrincipal.java
  security/plugins/src/main/java/org/jboss/as/core/security/api/AccountPrincipal.java
  security/plugins/src/main/java/org/jboss/as/core/security/api/GroupPrincipal.java
  security/plugins/src/main/java/org/jboss/as/core/security/api/RealmPrincipal.java
  security/plugins/src/main/java/org/jboss/as/core/security/api/UserPrincipal.java
  security/plugins/src/main/java/org/jboss/as/security/_private/SecurityLogger.java
  security/plugins/src/main/java/org/jboss/as/security/lru/ConcurrentDirectDeque.java
  security/plugins/src/main/java/org/jboss/as/security/lru/FastConcurrentDirectDeque.java
  security/plugins/src/main/java/org/jboss/as/security/lru/LRUCache.java
  security/plugins/src/main/java/org/jboss/as/security/lru/PortableConcurrentDirectDeque.java
  security/plugins/src/main/java/org/jboss/as/security/lru/RemoveCallback.java
  security/plugins/src/main/java/org/jboss/as/security/plugins/AuthenticationCacheFactory.java
  security/plugins/src/main/java/org/jboss/as/security/plugins/DefaultAuthenticationCacheFactory.java
  security/plugins/src/main/java/org/jboss/as/security/plugins/JNDIBasedSecurityManagement.java
  security/plugins/src/main/java/org/jboss/as/security/plugins/ModuleClassLoaderLocator.java
  security/plugins/src/main/java/org/jboss/as/security/plugins/SecurityActions.java
  security/plugins/src/main/java/org/jboss/as/security/plugins/SecurityDomainContext.java
  security/plugins/src/main/java/org/jboss/as/security/remoting/RemoteConnection.java
  security/plugins/src/main/java/org/jboss/as/security/remoting/RemotingConnectionCredential.java
  security/plugins/src/main/java/org/jboss/as/security/remoting/RemotingContext.java
  security/plugins/src/main/java/org/jboss/as/security/remoting/RemotingLoginModule.java
  security/plugins/src/main/java/org/jboss/as/security/remoting/RemotingPermission.java
  security/plugins/src/main/java/org/jboss/as/security/remoting/SecurityActions.java
  security/pom.xml
  servlet-feature-pack/common/pom.xml
  servlet-feature-pack/common/src/main/resources/license/servlet-feature-pack-common-licenses.xml
  servlet-feature-pack/common/src/main/resources/modules/system/layers/base/org/jboss/as/security-plugins/main/module.xml
  testsuite/integration/basic/pom.xml
Labels: deps-changed

#15113 [WFLY-15932] Adding missing permission to RemoteLocalCallProfileTestC…
  testsuite/integration/multinode/src/test/java/org/jboss/as/test/multinode/remotecall/RemoteLocalCallProfileTestCase.java
Labels: deps-ok

#15116 [26.x][WFLY-15932] Adding missing permission to RemoteLocalCallProfileTestC…
  testsuite/integration/multinode/src/test/java/org/jboss/as/test/multinode/remotecall/RemoteLocalCallProfileTestCase.java
Labels: 26.x

#15115 WFLY-15931 Intermittent RejectedExecutionException on redeploy
  clustering/infinispan/extension/src/main/java/org/jboss/as/clustering/infinispan/subsystem/CacheContainerServiceConfigurator.java
Labels: deps-ok

#15109 WFLY-15912 Replace deprecated EnumValidator constructors and methods (Transactions)
  transactions/src/main/java/org/jboss/as/txn/subsystem/LogStoreConstants.java
Labels: ready-for-merge, deps-ok

#14974 Upgrade Narayana to 5.12.4.Final
  pom.xml
Labels: hold, rebase-this, deps-ok

#15124 [WFLY-15942] Upgrade WildFly Core 18.0.4.Final
  pom.xml
Labels: Blocker, 26.x

#15123 WFLY-15921 JobOperator.getJobNames() does only return Names of Jobs t…
  batch-jberet/src/main/java/org/wildfly/extension/batch/jberet/deployment/JobOperatorService.java
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/batch/batchlet/SimpleCounterBatchletTestCase.java
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/batch/batchlet/inactive-job.xml
Labels: deps-ok

#15117 [WFLY-15935]: Artemis Journal module is missing a netty dependency
  ee-feature-pack/common/src/main/resources/modules/system/layers/base/org/apache/activemq/artemis/journal/main/module.xml
Labels: deps-ok

#15112 WFLY-15905 Replace deprecated EnumValidator constructors and methods (EE)
  ee/src/main/java/org/jboss/as/ee/subsystem/ManagedExecutorServiceResourceDefinition.java
  ee/src/main/java/org/jboss/as/ee/subsystem/ManagedScheduledExecutorServiceResourceDefinition.java
Labels: deps-ok

#15102 [WFLY-15924] Add missing deps to testsuite modules to replace transit…
  testsuite/integration/microprofile-tck/jwt/pom.xml
  testsuite/integration/microprofile-tck/opentracing/pom.xml
  testsuite/integration/microprofile/pom.xml
  testsuite/integration/rts/pom.xml
  testsuite/integration/secman/pom.xml
  testsuite/integration/web/pom.xml
  testsuite/integration/ws/pom.xml
  testsuite/mixed-domain/pom.xml
  testsuite/mixed-domain/src/test/java/org/jboss/as/test/integration/domain/mixed/MixedDeploymentOverlayTestCase.java
  testsuite/shared/pom.xml
Labels: ready-for-merge, deps-ok

#15096 [WFLY-15918] Use java.transaction.xa JPMS module together with java.sql module where necessary
  ee-9/common/src/main/resources/modules/system/layers/base/org/apache/activemq/artemis/main/module.xml
  ee-9/ee-9-api/src/main/resources/modules/system/layers/base/jakarta/resource/api/main/module.xml
  ee-feature-pack/common/src/main/resources/modules/system/layers/base/com/h2database/h2/main/module.xml
  ee-feature-pack/common/src/main/resources/modules/system/layers/base/org/apache/activemq/artemis/main/module.xml
  ee-feature-pack/common/src/main/resources/modules/system/layers/base/org/hibernate/main/module.xml
  ee-feature-pack/common/src/main/resources/modules/system/layers/base/org/jboss/as/clustering/infinispan/main/module.xml
  ee-feature-pack/common/src/main/resources/modules/system/layers/base/org/jboss/as/connector/main/module.xml
  ee-feature-pack/common/src/main/resources/modules/system/layers/base/org/jboss/as/ejb3/main/module.xml
  ee-feature-pack/common/src/main/resources/modules/system/layers/base/org/jboss/ironjacamar/jdbcadapters/main/module.xml
  ee-feature-pack/common/src/main/resources/modules/system/layers/base/org/jboss/jts/main/module.xml
  ee-feature-pack/common/src/main/resources/modules/system/layers/base/org/wildfly/extension/messaging-activemq/main/module.xml
  ee-feature-pack/ee-8-api/src/main/resources/modules/system/layers/base/javax/resource/api/main/module.xml
Labels: deps-ok

#15070 [WFLY-14967] Move WildFly Preview to a native Jakarta namespace varia…
  ee-9/common/pom.xml
  ee-9/common/src/main/resources/license/preview-feature-pack-common-licenses.xml
  ee-9/feature-pack/pom.xml
  ee-9/pom.xml
  ee-9/source-transform/jpa/eclipselink/pom.xml
  ee-9/source-transform/pom.xml
  ee-feature-pack/common/src/main/resources/modules/system/layers/base/org/eclipse/persistence/main/module.xml
Labels: deps-ok

#15093 [26.x][WFLY-15890] Add a section on multi-tenancy to the Elytron OpenID Connect Client subsystem documentation
  docs/src/main/asciidoc/_admin-guide/subsystem-configuration/Elytron_OIDC_Client.adoc
Labels: core-upgrade-needed, 26.x

#15119 [WFLY-15549] Move WildFly Preview to native Jakarta namespace variant of the Undertow subsystem module
  ee-9/common/pom.xml
  ee-9/common/src/main/resources/license/preview-feature-pack-common-licenses.xml
  ee-9/feature-pack/pom.xml
  ee-9/pom.xml
  ee-9/source-transform/jaxrs/pom.xml
  ee-9/source-transform/pom.xml
  ee-9/source-transform/undertow/pom.xml
  servlet-feature-pack/common/src/main/resources/modules/system/layers/base/org/wildfly/extension/undertow/main/module.xml
Labels: ready-for-merge, deps-ok, EE9

#15129 [WFLY-15951] Reserve logging ids
  microprofile/config-smallrye/src/main/java/org/wildfly/extension/microprofile/config/smallrye/_private/MicroProfileConfigLogger.java
  microprofile/health-smallrye/src/main/java/org/wildfly/extension/microprofile/health/_private/MicroProfileHealthLogger.java
  microprofile/metrics-smallrye/src/main/java/org/wildfly/extension/microprofile/metrics/_private/MicroProfileMetricsLogger.java
  microprofile/opentracing-extension/src/main/java/org/wildfly/extension/microprofile/opentracing/TracingExtensionLogger.java
Labels: ready-for-merge, deps-ok

#15128 [26.x] WFLY-15931 Intermittent RejectedExecutionException on redeploy
  clustering/infinispan/extension/src/main/java/org/jboss/as/clustering/infinispan/subsystem/CacheContainerServiceConfigurator.java
Labels: 26.x

#15017 [WFLY-15544] iiop-openjdk subsystem transformation to Jakarta
  ee-9/pom.xml
  ee-9/source-transform/iiop-openjdk/pom.xml
  ee-9/source-transform/pom.xml
  pom.xml
Labels: deps-ok

#15131 [WFCORE-5590]: Provide a separate javax.* namespace Jakarta JSON api.
  testsuite/integration/basic/pom.xml
  testsuite/layers/src/test/java/org/jboss/as/test/layers/LayersTestCase.java
Labels: deps-ok, EE9

#15111 WFLY-15914 Replace deprecated EnumValidator constructors and methods (Web Services)
  webservices/server-integration/src/main/java/org/jboss/as/webservices/dmr/Attributes.java
Labels: deps-ok

#15110 WFLY-15913 Replace deprecated EnumValidator constructors and methods (Undertow)
  undertow/src/main/java/org/wildfly/extension/undertow/HttpsListenerResourceDefinition.java
  undertow/src/main/java/org/wildfly/extension/undertow/ServletContainerDefinition.java
  undertow/src/main/java/org/wildfly/extension/undertow/filters/ModClusterDefinition.java
Labels: deps-ok

#15088 WFLY-15906 Replace deprecated EnumValidator constructors and methods (EJB)
  ejb3/src/main/java/org/jboss/as/ejb3/subsystem/StrictMaxPoolResourceDefinition.java
Labels: deps-ok

#15036 [WFLY-10886] improve performance from AbstractJMSContext.getContext
  messaging-activemq/injection/pom.xml
  messaging-activemq/injection/src/main/java/org/wildfly/extension/messaging/activemq/deployment/injection/AbstractJMSContext.java
  messaging-activemq/injection/src/test/java/org/wildfly/extension/messaging/activemq/deployment/injection/AbstractJMSContextTestCase.java
Labels: 26.x

#15082 [26.x][WFLY-15903] Remove Jaeger dep from OpenTelemetry module
  ee-feature-pack/common/src/main/resources/modules/system/layers/base/io/opentelemetry/trace/main/module.xml
Labels: 26.x

#15101 [WFLY-15925] Upgrade RESTEasy to 6.0.0.Final for WildFly Preview.
  ee-9/pom.xml
  testsuite/integration/microprofile-tck/pom.xml
Labels: EE9, 26.x

#14837 [WFLY-15570] Upgrade joda-time 2.10.12
  pom.xml
Labels: deps-ok

#14839 [WFLY-15572] Upgrade fastinfoset 1.2.18
  pom.xml
Labels: rebase-this, deps-ok

#14978 [WFLY-15767] Update OpenTelemetry to 1.9.1
  ee-9/source-transform/observability/opentelemetry/pom.xml
  ee-feature-pack/common/pom.xml
  ee-feature-pack/common/src/main/resources/modules/system/layers/base/io/opentelemetry/trace/main/module.xml
  observability/opentelemetry/pom.xml
  pom.xml
Labels: deps-changed

#15071 [WFLY-15880] Adjust chmod to 644 for dev content
  ee-9/common/src/main/resources/modules/system/layers/base/org/bouncycastle/bcmail/main/module.xml
  ee-9/ee-9-api/src/main/resources/modules/system/layers/base/jakarta/ws/rs/api/main/module.xml
  ee-9/ee-9-api/src/main/resources/modules/system/layers/base/javax/ws/rs/api/main/module.xml
  ee-feature-pack/common/src/main/resources/content/bin/appclient.sh
  ee-feature-pack/common/src/main/resources/content/bin/jconsole.bat
  ee-feature-pack/common/src/main/resources/content/bin/jconsole.sh
  ee-feature-pack/common/src/main/resources/content/bin/wsconsume.sh
  ee-feature-pack/common/src/main/resources/content/bin/wsprovide.sh
  ee-feature-pack/common/src/main/resources/modules/system/layers/base/com/fasterxml/jackson/core/jackson-annotations/main/module.xml
  ee-feature-pack/common/src/main/resources/modules/system/layers/base/com/fasterxml/jackson/core/jackson-core/main/module.xml
  ee-feature-pack/common/src/main/resources/modules/system/layers/base/com/fasterxml/jackson/core/jackson-databind/main/module.xml
  ee-feature-pack/common/src/main/resources/modules/system/layers/base/com/fasterxml/jackson/datatype/jackson-datatype-jsr310/main/module.xml
  ee-feature-pack/common/src/main/resources/modules/system/layers/base/com/fasterxml/jackson/jaxrs/jackson-jaxrs-json-provider/main/module.xml
  ee-feature-pack/common/src/main/resources/modules/system/layers/base/com/github/fge/btf/main/module.xml
  ee-feature-pack/common/src/main/resources/modules/system/layers/base/com/github/fge/jackson-coreutils/main/module.xml
  ee-feature-pack/common/src/main/resources/modules/system/layers/base/com/github/fge/json-patch/main/module.xml
  ee-feature-pack/common/src/main/resources/modules/system/layers/base/com/github/fge/msg-simple/main/module.xml
  ee-feature-pack/common/src/main/resources/modules/system/layers/base/org/bouncycastle/bcmail/main/module.xml
  ee-feature-pack/common/src/main/resources/modules/system/layers/base/org/jboss/resteasy/jose-jwt/main/module.xml
  ee-feature-pack/common/src/main/resources/modules/system/layers/base/org/jboss/resteasy/resteasy-cdi/main/module.xml
  ee-feature-pack/common/src/main/resources/modules/system/layers/base/org/jboss/resteasy/resteasy-crypto/main/module.xml
  ee-feature-pack/common/src/main/resources/modules/system/layers/base/org/jboss/resteasy/resteasy-jackson2-provider/main/module.xml
  ee-feature-pack/common/src/main/resources/modules/system/layers/base/org/jboss/resteasy/resteasy-jaxrs/main/module.xml
  ee-feature-pack/common/src/main/resources/modules/system/layers/base/org/jboss/resteasy/resteasy-json-p-provider/main/module.xml
  ee-feature-pack/common/src/main/resources/modules/system/layers/base/org/jboss/resteasy/resteasy-rxjava2/main/module.xml
  ee-feature-pack/common/src/main/resources/modules/system/layers/base/org/jboss/resteasy/resteasy-spring/main/module.xml
  ee-feature-pack/common/src/main/resources/modules/system/layers/base/org/jboss/resteasy/resteasy-validator-provider/main/module.xml
  ee-feature-pack/common/src/main/resources/modules/system/layers/base/org/reactivestreams/main/module.xml
  ee-feature-pack/ee-8-api/src/main/resources/modules/system/layers/base/javax/ws/rs/api/main/module.xml
  ee/src/main/java/org/jboss/as/ee/concurrent/ContextServiceImpl.java
  ee/src/main/java/org/jboss/as/ee/subsystem/ContextServiceAdd.java
  jaxrs/src/main/java/org/jboss/as/jaxrs/deployment/JaxrsDependencyProcessor.java
  jaxrs/src/main/java/org/jboss/as/jaxrs/deployment/JaxrsIntegrationProcessor.java
  jaxrs/src/main/java/org/jboss/as/jaxrs/deployment/JaxrsScanningProcessor.java
  jaxrs/src/main/java/org/jboss/as/jaxrs/deployment/ResteasyDeploymentData.java
  jpa/hibernate5/src/test/java/org/hibernate/jpa/test/pack/Item.java
  jpa/hibernate5_3/src/test/java/org/hibernate/jpa/test/pack/Item.java
  microprofile/galleon-common/src/main/resources/modules/system/layers/base/org/jboss/resteasy/resteasy-client-microprofile/main/module.xml
  testsuite/compat/src/test/java/org/jboss/as/test/compat/jpa/hibernate/transformer/MonetaryAmount.java
  testsuite/compat/src/test/java/org/jboss/as/test/compat/jpa/hibernate/transformer/MonetaryAmountUserType.java
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/jaxrs/validator/ValidatorResource.java
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/jaxrs/validator/cdi/OrderResource.java
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/weld/modules/PortableExtension.java
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/weld/modules/PortableExtensionInExternalModuleTestCase.java
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/weld/modules/PortableExtensionLibraryLookup.java
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/weld/modules/PortableExtensionLookup.java
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/weld/modules/PortableExtensionModuleLookup.java
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/weld/modules/PortableExtensionSubdeploymentLookup.java
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/weld/modules/portable-extension-module.xml
  testsuite/integration/web/src/test/java/org/jboss/as/test/integration/web/sso/SingleSignOnUnitTestCase.java
  testsuite/shared/src/main/java/org/jboss/as/test/integration/web/sso/interfaces/ReturnData.java
  testsuite/shared/src/main/resources/org/jboss/as/test/integration/web/sso/resources/application.xml
  transactions/src/main/java/org/jboss/as/txn/service/ArjunaRecoveryManagerService.java
  transactions/src/main/java/org/jboss/as/txn/service/JTAEnvironmentBeanService.java
  transactions/src/test/java/org/jboss/as/txn/subsystem/TransactionSubsystemTestCase.java
  transactions/src/test/resources/org/jboss/as/txn/subsystem/full-1.5.0.xml
Labels: deps-ok

#15087 WFLY-15915 Replace deprecated EnumValidator constructors and methods (JCA)
  connector/src/main/java/org/jboss/as/connector/subsystems/common/pool/Constants.java
  connector/src/main/java/org/jboss/as/connector/subsystems/jca/JcaDistributedWorkManagerDefinition.java
  connector/src/main/java/org/jboss/as/connector/subsystems/resourceadapters/Constants.java
Labels: deps-ok

#15089 WFLY-15907 Replace deprecated EnumValidator constructors and methods (IIOP)
  iiop-openjdk/src/main/java/org/wildfly/iiop/openjdk/IIOPRootDefinition.java
  legacy/jacorb/src/main/java/org/jboss/as/jacorb/IORASContextDefinition.java
  legacy/jacorb/src/main/java/org/jboss/as/jacorb/IORSASContextDefinition.java
  legacy/jacorb/src/main/java/org/jboss/as/jacorb/IORTransportConfigDefinition.java
  legacy/jacorb/src/main/java/org/jboss/as/jacorb/JacORBSubsystemDefinitions.java
Labels: deps-ok

#15090 WFLY-15908 Replace deprecated EnumValidator constructors and methods (JPA)
  jpa/subsystem/src/main/java/org/jboss/as/jpa/subsystem/JPADefinition.java
Labels: deps-ok

#15091 WFLY-15909 Replace deprecated EnumValidator constructors and methods (Messaging)
  legacy/messaging/src/main/java/org/jboss/as/messaging/AddressSettingDefinition.java
  legacy/messaging/src/main/java/org/jboss/as/messaging/CommonAttributes.java
  legacy/messaging/src/main/java/org/jboss/as/messaging/GroupingHandlerDefinition.java
  legacy/messaging/src/main/java/org/jboss/as/messaging/jms/ConnectionFactoryType.java
  legacy/messaging/src/main/java/org/jboss/as/messaging/jms/bridge/JMSBridgeDefinition.java
  messaging-activemq/subsystem/src/main/java/org/wildfly/extension/messaging/activemq/AddressSettingDefinition.java
  messaging-activemq/subsystem/src/main/java/org/wildfly/extension/messaging/activemq/ClusterConnectionDefinition.java
  messaging-activemq/subsystem/src/main/java/org/wildfly/extension/messaging/activemq/GroupingHandlerDefinition.java
  messaging-activemq/subsystem/src/main/java/org/wildfly/extension/messaging/activemq/ServerDefinition.java
  messaging-activemq/subsystem/src/main/java/org/wildfly/extension/messaging/activemq/jms/ConnectionFactoryType.java
Labels: deps-ok

#15097 [WFLY-15923] Upgrade Agroal 1.14
  ee-feature-pack/pruned/src/main/resources/modules/system/layers/base/io/agroal/main/module.xml
  pom.xml
Labels: deps-ok

#15126 [WFLY-15943]: Can't create an external connection factory using a discovery group with socket binding.
  messaging-activemq/subsystem/src/main/java/org/wildfly/extension/messaging/activemq/ActiveMQResourceAdapter.java
  messaging-activemq/subsystem/src/main/java/org/wildfly/extension/messaging/activemq/MessagingServices.java
  messaging-activemq/subsystem/src/main/java/org/wildfly/extension/messaging/activemq/deployment/JMSConnectionFactoryDefinitionInjectionSource.java
  messaging-activemq/subsystem/src/main/java/org/wildfly/extension/messaging/activemq/deployment/JMSDestinationDefinitionInjectionSource.java
  messaging-activemq/subsystem/src/main/java/org/wildfly/extension/messaging/activemq/jms/ConnectionFactoryRemove.java
  messaging-activemq/subsystem/src/main/java/org/wildfly/extension/messaging/activemq/jms/ExternalConnectionFactoryAdd.java
  messaging-activemq/subsystem/src/main/java/org/wildfly/extension/messaging/activemq/jms/ExternalPooledConnectionFactoryRemove.java
Labels: deps-ok

#15132 [WFLY-15457] Eliminating unsupported and experimental Undertow JS component
  ee-feature-pack/common/pom.xml
  ee-feature-pack/common/src/main/resources/license/ee-feature-pack-common-licenses.xml
  ee-feature-pack/common/src/main/resources/modules/system/layers/base/io/undertow/js/main/module.xml
  ee-feature-pack/galleon-common/src/main/resources/layers/standalone/undertow/layer-spec.xml
  pom.xml
  undertow/src/main/java/org/wildfly/extension/undertow/deployment/UndertowDependencyProcessor.java
Labels: deps-changed, EE9

#15139 [WFLY-14841] / [WFLY-13889] Remove PicketBox dependency from Web Services.
  ee-feature-pack/common/src/main/resources/modules/system/layers/base/org/jboss/as/webservices/main/module.xml
  ee-feature-pack/common/src/main/resources/modules/system/layers/base/org/jboss/ws/cxf/jbossws-cxf-client/main/module.xml
  ee-feature-pack/common/src/main/resources/modules/system/layers/base/org/jboss/ws/cxf/jbossws-cxf-server/main/module.xml
  ee-feature-pack/common/src/main/resources/modules/system/layers/base/org/jboss/ws/jaxws-client/main/module.xml
  webservices/server-integration/src/main/java/org/jboss/as/webservices/security/SecurityAdaptorFactoryImpl.java
  webservices/server-integration/src/main/java/org/jboss/as/webservices/security/SecurityAdaptorImpl.java
  webservices/server-integration/src/main/java/org/jboss/as/webservices/service/EndpointService.java
  webservices/server-integration/src/main/resources/META-INF/services/org.jboss.wsf.spi.invocation.SecurityAdaptorFactory
Labels: deps-ok

#15136 [WFLY-15747] / [WFLY-13889] Remove PicketBox dependency from iiop-openjdk.
  ee-feature-pack/common/src/main/resources/modules/system/layers/base/org/wildfly/iiop-openjdk/main/module.xml
  iiop-openjdk/pom.xml
  iiop-openjdk/src/main/java/org/wildfly/iiop/openjdk/IIOPInitializer.java
  iiop-openjdk/src/main/java/org/wildfly/iiop/openjdk/IIOPSubsystemAdd.java
  iiop-openjdk/src/main/java/org/wildfly/iiop/openjdk/csiv2/ElytronSASClientInterceptor.java
  iiop-openjdk/src/main/java/org/wildfly/iiop/openjdk/csiv2/SASClientIdentityInterceptor.java
  iiop-openjdk/src/main/java/org/wildfly/iiop/openjdk/csiv2/SASClientInitializer.java
  iiop-openjdk/src/main/java/org/wildfly/iiop/openjdk/csiv2/SASClientInterceptor.java
  iiop-openjdk/src/main/java/org/wildfly/iiop/openjdk/csiv2/SASInitializer.java
  iiop-openjdk/src/main/java/org/wildfly/iiop/openjdk/csiv2/SecurityActions.java
  iiop-openjdk/src/main/java/org/wildfly/iiop/openjdk/logging/IIOPLogger.java
  iiop-openjdk/src/main/java/org/wildfly/iiop/openjdk/security/LegacySSLSocketFactory.java
  iiop-openjdk/src/main/java/org/wildfly/iiop/openjdk/security/TrustedIdentityTokenLoginModule.java
  iiop-openjdk/src/main/java/org/wildfly/iiop/openjdk/security/Util.java
  legacy/jacorb/src/test/java/org/jboss/as/jacorb/JacORBMigrateTestCase.java
  testsuite/integration/src/test/xslt/enableJTS.xsl
Labels: deps-ok

#14900 WFLY-15607 Remove the Hibernate ORM 5.1 => 5.3 bytecode transformer
  docs/src/main/asciidoc/_developer-guide/Jakarta_Persistence_Reference_Guide.adoc
  ee-9/source-transform/jpa/subsystem/pom.xml
  ee-feature-pack/common/pom.xml
  ee-feature-pack/common/src/main/resources/license/ee-feature-pack-common-licenses.xml
  ee-feature-pack/common/src/main/resources/modules/system/layers/base/org/hibernate/bytecodetransformer/main/module.xml
  ee-feature-pack/common/src/main/resources/modules/system/layers/base/org/jboss/as/jpa/main/module.xml
  jpa/hibernate-transformer/pom.xml
  jpa/hibernate-transformer/src/main/java/org/jboss/as/hibernate/Hibernate51CompatibilityTransformer.java
  jpa/hibernate-transformer/src/main/java/org/jboss/as/hibernate/MethodAdapter.java
  jpa/hibernate-transformer/src/main/java/org/jboss/as/hibernate/TransformedState.java
  jpa/hibernate-transformer/src/test/java/org/jboss/as/hibernate/test/BitSetType.java
  jpa/hibernate-transformer/src/test/java/org/jboss/as/hibernate/test/BitSetTypeDescriptor.java
  jpa/hibernate-transformer/src/test/java/org/jboss/as/hibernate/test/Hibernate51CompatibilityTransformerTest.java
  jpa/hibernate-transformer/src/test/java/org/jboss/as/hibernate/test/MyPersistentCollection.java
  jpa/hibernate-transformer/src/test/java/org/jboss/as/hibernate/test/ProcedureParameterExtractionAwareType.java
  jpa/hibernate-transformer/src/test/java/org/jboss/as/hibernate/test/ProcedureParameterNamedBinderType.java
  jpa/pom.xml
  jpa/subsystem/pom.xml
  jpa/subsystem/src/main/java/org/jboss/as/jpa/messages/JpaLogger.java
  jpa/subsystem/src/main/java/org/jboss/as/jpa/processor/JPAClassFileTransformerProcessor.java
  jpa/subsystem/src/main/java/org/jboss/as/jpa/processor/JPADependencyProcessor.java
  pom.xml
  testsuite/compat/src/test/java/org/jboss/as/test/compat/jpa/hibernate/transformer/AbstractVerifyHibernate51CompatibilityTestCase.java
  testsuite/compat/src/test/java/org/jboss/as/test/compat/jpa/hibernate/transformer/BitSetType.java
  testsuite/compat/src/test/java/org/jboss/as/test/compat/jpa/hibernate/transformer/BitSetTypeDescriptor.java
  testsuite/compat/src/test/java/org/jboss/as/test/compat/jpa/hibernate/transformer/BooleanAbstractStandardBasicType.java
  testsuite/compat/src/test/java/org/jboss/as/test/compat/jpa/hibernate/transformer/BooleanSingleColumnType.java
  testsuite/compat/src/test/java/org/jboss/as/test/compat/jpa/hibernate/transformer/BooleanType.java
  testsuite/compat/src/test/java/org/jboss/as/test/compat/jpa/hibernate/transformer/Gene.java
  testsuite/compat/src/test/java/org/jboss/as/test/compat/jpa/hibernate/transformer/IntegerType.java
  testsuite/compat/src/test/java/org/jboss/as/test/compat/jpa/hibernate/transformer/IntegerUserVersionType.java
  testsuite/compat/src/test/java/org/jboss/as/test/compat/jpa/hibernate/transformer/MonetaryAmount.java
  testsuite/compat/src/test/java/org/jboss/as/test/compat/jpa/hibernate/transformer/MonetaryAmountUserType.java
  testsuite/compat/src/test/java/org/jboss/as/test/compat/jpa/hibernate/transformer/MutualFund.java
  testsuite/compat/src/test/java/org/jboss/as/test/compat/jpa/hibernate/transformer/PersistentQueue.java
  testsuite/compat/src/test/java/org/jboss/as/test/compat/jpa/hibernate/transformer/Product.java
  testsuite/compat/src/test/java/org/jboss/as/test/compat/jpa/hibernate/transformer/QueueOwner.java
  testsuite/compat/src/test/java/org/jboss/as/test/compat/jpa/hibernate/transformer/QueueType.java
  testsuite/compat/src/test/java/org/jboss/as/test/compat/jpa/hibernate/transformer/SFSBHibernateSessionFactory.java
  testsuite/compat/src/test/java/org/jboss/as/test/compat/jpa/hibernate/transformer/StackOverFlowTestClass.java
  testsuite/compat/src/test/java/org/jboss/as/test/compat/jpa/hibernate/transformer/State.java
  testsuite/compat/src/test/java/org/jboss/as/test/compat/jpa/hibernate/transformer/StateType.java
  testsuite/compat/src/test/java/org/jboss/as/test/compat/jpa/hibernate/transformer/Student.java
  testsuite/compat/src/test/java/org/jboss/as/test/compat/jpa/hibernate/transformer/VerifyHibernate51CompatibilityJDSEnabledTransformerTestCase.java
  testsuite/compat/src/test/java/org/jboss/as/test/compat/jpa/hibernate/transformer/VerifyHibernate51CompatibilityPropertyAndJDSEnabledTransformerTestCase.java
  testsuite/compat/src/test/java/org/jboss/as/test/compat/jpa/hibernate/transformer/VerifyHibernate51CompatibilityPropertyEnabledTransformerTestCase.java
  testsuite/compat/src/test/java/org/jboss/as/test/compat/jpa/hibernate/transformer/jboss-deployment-structure.xml
Labels: deps-changed

#14270 WFLY-13044: fix extension matching in security constraints
  undertow/src/main/java/org/wildfly/extension/undertow/security/jacc/WarJACCService.java
  undertow/src/test/java/org/wildfly/extension/undertow/security/jacc/WarJACCServiceTest.java
Labels: deps-ok

#14513 [WFLY-15045] Tests if the default servlet serves content from any directories starting with WEB-INF or META-INF
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/web/response/DefaultServletTestCase.java
Labels: deps-ok

#15148 [WFLY-15971] Upgrade WildFly Core 19.0.0.Beta3
  pom.xml
Labels: deps-ok

#15144 [WFLY-14841] / [WFLY-13889] Remove PicketBox dependency from WS - eliminating java.security.acl package usages
  webservices/server-integration/src/main/java/org/jboss/as/webservices/util/SimpleGroup.java
  webservices/server-integration/src/main/java/org/jboss/as/webservices/util/SubjectUtil.java
Labels: ready-for-merge, deps-ok

#15120 [WFLY-15748] / [WFLY-13889] Remove PicketBox from the testsuite.
  testsuite/domain/pom.xml
  testsuite/integration/basic/pom.xml
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/ejb/security/callerprincipal/GetCallerPrincipalTestCase.java
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/ejb/security/securitydomain/ejb/BaseHello.java
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/ejb/security/securitydomain/ejb/Hello.java
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/ejb/security/securitydomain/ejb/HelloOneBean.java
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/ejb/security/securitydomain/ejb/HelloTwoBean.java
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/ejb/security/securitydomain/ejb/Info.java
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/ejb/security/securitydomain/ejb/jboss-ejb3.xml
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/ejb/security/securitydomain/module/MyPrincipal.java
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/ejb/security/securitydomain/module/NonValidatingLoginModule.java
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/security/loginmodules/common/CounterLoginModule.java
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/security/loginmodules/common/CustomEjbAccessingLoginModule.java
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/security/loginmodules/common/CustomLoginModule1.java
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/security/loginmodules/common/CustomLoginModule2.java
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/security/loginmodules/common/CustomTestLoginModule.java
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/security/loginmodules/common/PrepareLoginModule.java
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/security/loginmodules/common/SimpleSecuredEJB.java
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/security/loginmodules/common/SimpleSecuredEJBImpl.java
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/security/loginmodules/deployments/IdentityLoginModule/dep1/jboss-web.xml
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/security/loginmodules/deployments/IdentityLoginModule/dep2/jboss-web.xml
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/security/loginmodules/deployments/IdentityLoginModule/web.xml
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/security/loginmodules/deployments/RunAsLoginModule/jboss-web.xml
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/security/loginmodules/deployments/RunAsLoginModule/web.xml
  testsuite/integration/manualmode/src/test/java/org/jboss/as/test/manualmode/web/ssl/HTTPSWebConnectorTestCase.java
  testsuite/integration/web/src/test/java/org/jboss/as/test/integration/web/formauth/SecureServlet.java
  testsuite/integration/web/src/test/java/org/jboss/as/test/integration/web/security/cert/WebSecurityCERTTestCase.java
  testsuite/integration/web/src/test/java/org/jboss/as/test/integration/web/security/external/Credentials.java
  testsuite/integration/web/src/test/java/org/jboss/as/test/integration/web/security/external/ExternalAuthSecurityDomainSetup.java
  testsuite/integration/web/src/test/java/org/jboss/as/test/integration/web/security/external/ExternalLoginModule.java
  testsuite/integration/web/src/test/java/org/jboss/as/test/integration/web/security/external/UserHandler.java
  testsuite/integration/web/src/test/java/org/jboss/as/test/integration/web/security/external/UserHandlerExtension.java
  testsuite/integration/web/src/test/java/org/jboss/as/test/integration/web/security/external/WebSecurityExternalAuthTestCase.java
  testsuite/integration/web/src/test/java/org/jboss/as/test/integration/web/security/external/jboss-web.xml
  testsuite/integration/web/src/test/java/org/jboss/as/test/integration/web/security/external/web.xml
  testsuite/integration/ws/src/test/java/org/jboss/as/test/integration/ws/authentication/EJBEndpointSecuredWSDLAccessTestCase.java
  testsuite/shared/pom.xml
  testsuite/shared/src/main/java/org/jboss/as/test/integration/security/common/AddRoleLoginModule.java
  testsuite/shared/src/main/java/org/jboss/as/test/integration/security/common/Utils.java
  testsuite/shared/src/main/java/org/jboss/as/test/shared/integration/ejb/security/Util.java
Labels: deps-ok

#15143 WFLY-15966 Move WildFly Preview to native Jakarta namespace variant of the wildfly-clustering-web-undertow module
  ee-9/common/pom.xml
  ee-9/common/src/main/resources/license/preview-feature-pack-common-licenses.xml
  ee-9/feature-pack/pom.xml
  ee-9/pom.xml
  ee-9/source-transform/clustering/pom.xml
  ee-9/source-transform/clustering/web/pom.xml
  ee-9/source-transform/clustering/web/undertow/pom.xml
  ee-9/source-transform/pom.xml
  ee-feature-pack/common/src/main/resources/modules/system/layers/base/org/wildfly/clustering/web/undertow/main/module.xml
Labels: deps-ok

#15142 [WFLY-15965]: ExternalJMSDestinationDefinitionLegacyPrefixMessagingDe…
  testsuite/integration/basic/pom.xml
Labels: deps-ok

#15121 [WFLY-15756] / [WFLY-13889] Remove PicketBox dependencies from ActiveMQ.
  ee-9/common/src/main/resources/modules/system/layers/base/org/apache/activemq/artemis/main/module.xml
  ee-feature-pack/common/src/main/resources/modules/system/layers/base/org/apache/activemq/artemis/main/module.xml
  ee-feature-pack/common/src/main/resources/modules/system/layers/base/org/wildfly/extension/messaging-activemq/main/module.xml
Labels: ready-for-merge, deps-ok

#15138 WFLY-15954 getJobInstances, getJobInstanceCount, getRunningExecutions…
  batch-jberet/src/main/java/org/wildfly/extension/batch/jberet/job/repository/JobRepositoryService.java
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/batch/batchlet/SimpleCounterBatchletTestCase.java
Labels: deps-ok

#15149 [WFLY-15924] Follow-up commit to add missing dependency to testsuite/…
  testsuite/layers/pom.xml
Labels: deps-ok

#15141 WFLY-15944 Upgrade smallrye-open-api to 2.1.17
  pom.xml
Labels: deps-ok

#15140 [WFLY-15964] OpenTelemetry ratio-based sampler should not accept value bigger than 1.0.
  observability/opentelemetry/src/main/java/org/wildfly/extension/opentelemetry/OpenTelemetrySubsystemDefinition.java
Labels: ready-for-merge, deps-ok

#15153 WFLY-15939 Upgrade Infinispan to 13.0.6.Final.
  clustering/infinispan/extension/src/main/java/org/jboss/as/clustering/infinispan/subsystem/FileStoreServiceConfigurator.java
  clustering/infinispan/spi/src/main/java/org/wildfly/clustering/infinispan/spi/persistence/sifs/SoftIndexFileStore.java
  clustering/infinispan/spi/src/main/java/org/wildfly/clustering/infinispan/spi/persistence/sifs/SoftIndexFileStoreConfiguration.java
  clustering/infinispan/spi/src/main/java/org/wildfly/clustering/infinispan/spi/persistence/sifs/SoftIndexFileStoreConfigurationBuilder.java
  pom.xml
Labels: ready-for-merge, deps-ok

#15154 WFLY-15947 Upgrade Narayana to 5.12.5.Final
  pom.xml
Labels: ready-for-merge, deps-ok
