Repository wildfly/wildfly, pull requests merged in 2022-06, with the labels that each got.

#15602 [WFLY-16121]: Intermittent failure in ExternalJMSDestinationDefinitionLegacyPrefixMessagingDeploymentTestCase
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/messaging/jms/external/prefix/ExternalJMSDestinationDefinitionLegacyPrefixMessagingDeploymentTestCase.java
Labels: deps-ok

#15594 [WFLY-16424] Upgrade Netty from 4.1.76.Final to 4.1.77.Final
  pom.xml
Labels: deps-ok

#15606 Remove the override for the maven-help-plugin.
  pom.xml
Labels: deps-ok

#15603 [WFLY-16126/WFLY-16250]: Problematic Language usage for messaging subsystem
  ee-9/galleon-content-microprofile/src/main/resources/feature_groups/standalone-activemq-colocated.xml
  ee-feature-pack/galleon-content/src/main/resources/feature_groups/standalone-activemq-colocated.xml
  legacy/messaging/src/test/java/org/jboss/as/messaging/test/MigrateTestCase.java
  legacy/messaging/src/test/resources/org/jboss/as/messaging/test/subsystem_migration_ha.xml
  messaging-activemq/subsystem/src/main/java/org/wildfly/extension/messaging/activemq/CommonAttributes.java
  messaging-activemq/subsystem/src/main/java/org/wildfly/extension/messaging/activemq/MessagingExtension.java
  messaging-activemq/subsystem/src/main/java/org/wildfly/extension/messaging/activemq/MessagingSubsystemParser_10_0.java
  messaging-activemq/subsystem/src/main/java/org/wildfly/extension/messaging/activemq/MessagingSubsystemParser_11_0.java
  messaging-activemq/subsystem/src/main/java/org/wildfly/extension/messaging/activemq/MessagingSubsystemParser_12_0.java
  messaging-activemq/subsystem/src/main/java/org/wildfly/extension/messaging/activemq/MessagingSubsystemParser_13_0.java
  messaging-activemq/subsystem/src/main/java/org/wildfly/extension/messaging/activemq/MessagingSubsystemParser_13_1.java
  messaging-activemq/subsystem/src/main/java/org/wildfly/extension/messaging/activemq/MessagingSubsystemParser_14_0.java
  messaging-activemq/subsystem/src/main/java/org/wildfly/extension/messaging/activemq/MessagingSubsystemParser_1_0.java
  messaging-activemq/subsystem/src/main/java/org/wildfly/extension/messaging/activemq/MessagingSubsystemParser_2_0.java
  messaging-activemq/subsystem/src/main/java/org/wildfly/extension/messaging/activemq/MessagingSubsystemParser_3_0.java
  messaging-activemq/subsystem/src/main/java/org/wildfly/extension/messaging/activemq/MessagingSubsystemParser_4_0.java
  messaging-activemq/subsystem/src/main/java/org/wildfly/extension/messaging/activemq/MessagingSubsystemParser_5_0.java
  messaging-activemq/subsystem/src/main/java/org/wildfly/extension/messaging/activemq/MessagingSubsystemParser_6_0.java
  messaging-activemq/subsystem/src/main/java/org/wildfly/extension/messaging/activemq/MessagingSubsystemParser_7_0.java
  messaging-activemq/subsystem/src/main/java/org/wildfly/extension/messaging/activemq/MessagingSubsystemParser_8_0.java
  messaging-activemq/subsystem/src/main/java/org/wildfly/extension/messaging/activemq/MessagingSubsystemParser_9_0.java
  messaging-activemq/subsystem/src/main/java/org/wildfly/extension/messaging/activemq/MessagingTransformerRegistration.java
  messaging-activemq/subsystem/src/main/java/org/wildfly/extension/messaging/activemq/ServerDefinition.java
  messaging-activemq/subsystem/src/main/java/org/wildfly/extension/messaging/activemq/ha/HAPolicyConfigurationBuilder.java
  messaging-activemq/subsystem/src/main/java/org/wildfly/extension/messaging/activemq/ha/ReplicationColocatedDefinition.java
  messaging-activemq/subsystem/src/main/java/org/wildfly/extension/messaging/activemq/ha/ReplicationPrimaryDefinition.java
  messaging-activemq/subsystem/src/main/java/org/wildfly/extension/messaging/activemq/ha/ReplicationSecondaryDefinition.java
  messaging-activemq/subsystem/src/main/java/org/wildfly/extension/messaging/activemq/ha/SharedStoreColocatedDefinition.java
  messaging-activemq/subsystem/src/main/java/org/wildfly/extension/messaging/activemq/ha/SharedStorePrimaryDefinition.java
  messaging-activemq/subsystem/src/main/java/org/wildfly/extension/messaging/activemq/ha/SharedStoreSecondaryDefinition.java
  messaging-activemq/subsystem/src/main/java/org/wildfly/extension/messaging/activemq/jms/ConnectionFactoryAdd.java
  messaging-activemq/subsystem/src/main/java/org/wildfly/extension/messaging/activemq/jms/ConnectionFactoryAttributes.java
  messaging-activemq/subsystem/src/main/java/org/wildfly/extension/messaging/activemq/jms/ConnectionFactoryDefinition.java
  messaging-activemq/subsystem/src/main/java/org/wildfly/extension/messaging/activemq/jms/ExternalConnectionFactoryAdd.java
  messaging-activemq/subsystem/src/main/java/org/wildfly/extension/messaging/activemq/jms/ExternalConnectionFactoryDefinition.java
  messaging-activemq/subsystem/src/main/java/org/wildfly/extension/messaging/activemq/jms/ExternalPooledConnectionFactoryAdd.java
  messaging-activemq/subsystem/src/main/java/org/wildfly/extension/messaging/activemq/jms/ExternalPooledConnectionFactoryDefinition.java
  messaging-activemq/subsystem/src/main/java/org/wildfly/extension/messaging/activemq/jms/PooledConnectionFactoryAdd.java
  messaging-activemq/subsystem/src/main/java/org/wildfly/extension/messaging/activemq/jms/PooledConnectionFactoryDefinition.java
  messaging-activemq/subsystem/src/main/resources/org/wildfly/extension/messaging/activemq/LocalDescriptions.properties
  messaging-activemq/subsystem/src/main/resources/schema/wildfly-messaging-activemq_14_0.xsd
  messaging-activemq/subsystem/src/test/java/org/wildfly/extension/messaging/activemq/MessagingActiveMQSubsystem_10_0_TestCase.java
  messaging-activemq/subsystem/src/test/java/org/wildfly/extension/messaging/activemq/MessagingActiveMQSubsystem_13_1_TestCase.java
  messaging-activemq/subsystem/src/test/java/org/wildfly/extension/messaging/activemq/MessagingActiveMQSubsystem_14_0_TestCase.java
  messaging-activemq/subsystem/src/test/java/org/wildfly/extension/messaging/activemq/MessagingActiveMQSubsystem_2_0_TestCase.java
  messaging-activemq/subsystem/src/test/java/org/wildfly/extension/messaging/activemq/MessagingDependencies.java
  messaging-activemq/subsystem/src/test/resources/org/wildfly/extension/messaging/activemq/subsystem_14_0.xml
  messaging-activemq/subsystem/src/test/resources/org/wildfly/extension/messaging/activemq/subsystem_14_0_ha-policy.xml
  messaging-activemq/subsystem/src/test/resources/org/wildfly/extension/messaging/activemq/subsystem_14_0_reject_transform.xml
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/messaging/security/DeserializationBlockListTestCase.java
  testsuite/integration/manualmode/src/test/java/org/jboss/as/test/manualmode/messaging/ha/ReplicatedFailoverTestCase.java
  testsuite/integration/manualmode/src/test/java/org/jboss/as/test/manualmode/messaging/ha/ReplicatedNettyFailoverTestCase.java
  testsuite/integration/manualmode/src/test/java/org/jboss/as/test/manualmode/messaging/ha/SharedStoreFailoverTestCase.java
  testsuite/integration/vdx/src/test/java/org/wildfly/test/integration/vdx/standalone/MessagingTestCase.java
Labels: deps-ok

#15607 [WFLY-16121-reopen]: Intermittent failure in
  messaging-activemq/subsystem/src/main/java/org/wildfly/extension/messaging/activemq/jms/ExternalJMSQueueService.java
Labels: deps-ok

#15496 [WFLY-16323] Upgrade net.bytebuddy to 1.12.9
  pom.xml
Labels: deps-ok

#15326 [WFLY-16129] [allowlist/blocklist] Problematic Language usage depreca…
  docs/src/main/asciidoc/_admin-guide/subsystem-configuration/MicroProfile_JWT.adoc
Labels: deps-ok

#15611 WFLY-16448 Duplicate key in LocalDescriptions.properties file
  iiop-openjdk/src/main/resources/org/wildfly/iiop/openjdk/LocalDescriptions.properties
Labels: deps-ok

#15564 WFLY-16384/WFLY-16390 Drop old JGroups subsystem schemas and resource/attributes/operations deprecated since WF23
  clustering/common/src/main/java/org/jboss/as/clustering/controller/descriptions/ChildResourceDescriptionResolver.java
  clustering/jgroups/extension/src/main/java/org/jboss/as/clustering/jgroups/logging/JGroupsLogger.java
  clustering/jgroups/extension/src/main/java/org/jboss/as/clustering/jgroups/subsystem/AbstractProtocolResourceDefinition.java
  clustering/jgroups/extension/src/main/java/org/jboss/as/clustering/jgroups/subsystem/ChannelMetric.java
  clustering/jgroups/extension/src/main/java/org/jboss/as/clustering/jgroups/subsystem/ChannelResourceDefinition.java
  clustering/jgroups/extension/src/main/java/org/jboss/as/clustering/jgroups/subsystem/ChannelResourceTransformer.java
  clustering/jgroups/extension/src/main/java/org/jboss/as/clustering/jgroups/subsystem/GenericProtocolResourceDefinition.java
  clustering/jgroups/extension/src/main/java/org/jboss/as/clustering/jgroups/subsystem/JGroupsModel.java
  clustering/jgroups/extension/src/main/java/org/jboss/as/clustering/jgroups/subsystem/JGroupsSchema.java
  clustering/jgroups/extension/src/main/java/org/jboss/as/clustering/jgroups/subsystem/JGroupsSubsystemResourceDefinition.java
  clustering/jgroups/extension/src/main/java/org/jboss/as/clustering/jgroups/subsystem/JGroupsSubsystemXMLReader.java
  clustering/jgroups/extension/src/main/java/org/jboss/as/clustering/jgroups/subsystem/JGroupsSubsystemXMLWriter.java
  clustering/jgroups/extension/src/main/java/org/jboss/as/clustering/jgroups/subsystem/PropertyResourceDefinition.java
  clustering/jgroups/extension/src/main/java/org/jboss/as/clustering/jgroups/subsystem/ProtocolRegistration.java
  clustering/jgroups/extension/src/main/java/org/jboss/as/clustering/jgroups/subsystem/RelayResourceDefinition.java
  clustering/jgroups/extension/src/main/java/org/jboss/as/clustering/jgroups/subsystem/RemoteSiteResourceDefinition.java
  clustering/jgroups/extension/src/main/java/org/jboss/as/clustering/jgroups/subsystem/StackResourceDefinition.java
  clustering/jgroups/extension/src/main/java/org/jboss/as/clustering/jgroups/subsystem/ThreadPoolResourceDefinition.java
  clustering/jgroups/extension/src/main/java/org/jboss/as/clustering/jgroups/subsystem/TransportResourceDefinition.java
  clustering/jgroups/extension/src/main/java/org/jboss/as/clustering/jgroups/subsystem/XMLAttribute.java
  clustering/jgroups/extension/src/main/java/org/jboss/as/clustering/jgroups/subsystem/XMLElement.java
  clustering/jgroups/extension/src/main/resources/org/jboss/as/clustering/jgroups/subsystem/LocalDescriptions.properties
  clustering/jgroups/extension/src/main/resources/schema/jboss-as-jgroups_1_0.xsd
  clustering/jgroups/extension/src/main/resources/schema/jboss-as-jgroups_1_1.xsd
  clustering/jgroups/extension/src/main/resources/schema/jboss-as-jgroups_2_0.xsd
  clustering/jgroups/extension/src/main/resources/schema/jboss-as-jgroups_3_0.xsd
  clustering/jgroups/extension/src/main/resources/schema/jboss-as-jgroups_4_0.xsd
  clustering/jgroups/extension/src/main/resources/schema/jboss-as-jgroups_5_0.xsd
  clustering/jgroups/extension/src/main/resources/schema/jboss-as-jgroups_9_0.xsd
  clustering/jgroups/extension/src/test/java/org/jboss/as/clustering/jgroups/subsystem/JGroupsSubsystemTestCase.java
  clustering/jgroups/extension/src/test/java/org/jboss/as/clustering/jgroups/subsystem/OperationSequencesTestCase.java
  clustering/jgroups/extension/src/test/java/org/jboss/as/clustering/jgroups/subsystem/OperationTestCaseBase.java
  clustering/jgroups/extension/src/test/java/org/jboss/as/clustering/jgroups/subsystem/OperationsTestCase.java
  clustering/jgroups/extension/src/test/resources/org/jboss/as/clustering/jgroups/subsystem/subsystem-jgroups-1_0.xml
  clustering/jgroups/extension/src/test/resources/org/jboss/as/clustering/jgroups/subsystem/subsystem-jgroups-1_1.xml
  clustering/jgroups/extension/src/test/resources/org/jboss/as/clustering/jgroups/subsystem/subsystem-jgroups-2_0.xml
  clustering/jgroups/extension/src/test/resources/org/jboss/as/clustering/jgroups/subsystem/subsystem-jgroups-3_0.xml
  clustering/jgroups/extension/src/test/resources/org/jboss/as/clustering/jgroups/subsystem/subsystem-jgroups-4_0.xml
  clustering/jgroups/extension/src/test/resources/org/jboss/as/clustering/jgroups/subsystem/subsystem-jgroups-6_0.xml
  clustering/jgroups/extension/src/test/resources/org/jboss/as/clustering/jgroups/subsystem/subsystem-jgroups-7_0.xml
  clustering/jgroups/extension/src/test/resources/org/jboss/as/clustering/jgroups/subsystem/subsystem-jgroups-8_0.xml
  clustering/jgroups/extension/src/test/resources/org/jboss/as/clustering/jgroups/subsystem/subsystem-jgroups-9_0.xml
  clustering/jgroups/extension/src/test/resources/org/jboss/as/clustering/jgroups/subsystem/subsystem-jgroups-transform-8_0_0.xml
  clustering/jgroups/extension/src/test/resources/org/jboss/as/clustering/jgroups/subsystem/subsystem-jgroups-transform-reject.xml
  testsuite/domain/src/test/java/org/jboss/as/test/integration/domain/LegacyJGroupsProtocolsTestCase.java
  testsuite/domain/src/test/resources/domain-configs/domain-standard-ee.xml
  testsuite/domain/src/test/resources/domain-configs/domain-standard.xml
  testsuite/integration/clustering/clustering-all.cli
  testsuite/integration/clustering/clustering-bootable.cli
  testsuite/integration/clustering/clustering-mp.cli
  testsuite/integration/clustering/src/test/java/org/jboss/as/test/clustering/cluster/xsite/XSiteSimpleTestCase.java
Labels: deps-ok

#15586 WFLY-16392 Drop deprecated mod_cluster subsystem resources/attributes and schemas since WF16 or earlier
  mod_cluster/extension/src/main/java/org/wildfly/extension/mod_cluster/DynamicLoadProviderResourceDefinition.java
  mod_cluster/extension/src/main/java/org/wildfly/extension/mod_cluster/LegacyMetricOperationsRegistration.java
  mod_cluster/extension/src/main/java/org/wildfly/extension/mod_cluster/LegacyProxyHandler.java
  mod_cluster/extension/src/main/java/org/wildfly/extension/mod_cluster/LegacyProxyOperation.java
  mod_cluster/extension/src/main/java/org/wildfly/extension/mod_cluster/LoadMetricEnum.java
  mod_cluster/extension/src/main/java/org/wildfly/extension/mod_cluster/ModClusterLogger.java
  mod_cluster/extension/src/main/java/org/wildfly/extension/mod_cluster/ModClusterModel.java
  mod_cluster/extension/src/main/java/org/wildfly/extension/mod_cluster/ModClusterSchema.java
  mod_cluster/extension/src/main/java/org/wildfly/extension/mod_cluster/ModClusterSubsystemResourceDefinition.java
  mod_cluster/extension/src/main/java/org/wildfly/extension/mod_cluster/ModClusterSubsystemServiceHandler.java
  mod_cluster/extension/src/main/java/org/wildfly/extension/mod_cluster/ModClusterSubsystemXMLReader.java
  mod_cluster/extension/src/main/java/org/wildfly/extension/mod_cluster/ModClusterSubsystemXMLWriter.java
  mod_cluster/extension/src/main/java/org/wildfly/extension/mod_cluster/ProxyConfigurationResourceDefinition.java
  mod_cluster/extension/src/main/java/org/wildfly/extension/mod_cluster/ProxyConfigurationServiceConfigurator.java
  mod_cluster/extension/src/main/java/org/wildfly/extension/mod_cluster/SSLResourceDefinition.java
  mod_cluster/extension/src/main/java/org/wildfly/extension/mod_cluster/XMLAttribute.java
  mod_cluster/extension/src/main/java/org/wildfly/extension/mod_cluster/XMLElement.java
  mod_cluster/extension/src/main/java/org/wildfly/extension/mod_cluster/ZeroToNegativeOneParameterCorrector.java
  mod_cluster/extension/src/main/resources/org/wildfly/extension/mod_cluster/LocalDescriptions.properties
  mod_cluster/extension/src/main/resources/schema/jboss-as-mod-cluster_1_0.xsd
  mod_cluster/extension/src/main/resources/schema/jboss-as-mod-cluster_1_1.xsd
  mod_cluster/extension/src/main/resources/schema/jboss-as-mod-cluster_1_2.xsd
  mod_cluster/extension/src/main/resources/schema/jboss-as-mod-cluster_2_0.xsd
  mod_cluster/extension/src/main/resources/schema/jboss-as-mod-cluster_3_0.xsd
  mod_cluster/extension/src/main/resources/schema/jboss-as-mod-cluster_6_0.xsd
  mod_cluster/extension/src/test/java/org/wildfly/extension/mod_cluster/ModClusterOperationsTestCase.java
  mod_cluster/extension/src/test/java/org/wildfly/extension/mod_cluster/ModClusterTransformersTestCase.java
  mod_cluster/extension/src/test/resources/org/wildfly/extension/mod_cluster/subsystem-operations.xml
  mod_cluster/extension/src/test/resources/org/wildfly/extension/mod_cluster/subsystem-reject.xml
  mod_cluster/extension/src/test/resources/org/wildfly/extension/mod_cluster/subsystem-transform-7_0_0.xml
  mod_cluster/extension/src/test/resources/org/wildfly/extension/mod_cluster/subsystem_1_0.xml
  mod_cluster/extension/src/test/resources/org/wildfly/extension/mod_cluster/subsystem_1_1.xml
  mod_cluster/extension/src/test/resources/org/wildfly/extension/mod_cluster/subsystem_1_2.xml
  mod_cluster/extension/src/test/resources/org/wildfly/extension/mod_cluster/subsystem_2_0.xml
  mod_cluster/extension/src/test/resources/org/wildfly/extension/mod_cluster/subsystem_3_0.xml
  mod_cluster/extension/src/test/resources/org/wildfly/extension/mod_cluster/subsystem_5_0.xml
  mod_cluster/extension/src/test/resources/org/wildfly/extension/mod_cluster/subsystem_6_0.xml
  testsuite/domain/src/test/resources/domain-configs/domain-jvm-properties.xml
  testsuite/domain/src/test/resources/domain-configs/domain-standard-ee.xml
  testsuite/domain/src/test/resources/domain-configs/domain-standard.xml
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/mod_cluster/ModClusterSubsystemTestCase.java
  testsuite/integration/clustering/src/test/java/org/jboss/as/test/clustering/cluster/modcluster/ModClusterProxyListOptionTestCase.java
  testsuite/integration/vdx/src/test/resources/configurations/domain/domain-to-damage.xml
  testsuite/integration/vdx/src/test/resources/configurations/domain/duplicate-attribute.xml
  testsuite/integration/vdx/src/test/resources/configurations/standalone/standalone-full-ha-to-damage.xml
Labels: deps-ok

#15610 [WFLY-16439] Remove testsuite use of javax.faces.bean annotations
  testsuite/integration/basic/pom.xml
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/jsf/beanvalidation/cdi/BeanValidationCdiIntegrationTestCase.java
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/jsf/beanvalidation/cdi/Team.java
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/jsf/beanvalidation/cdi/faces-config.xml
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/jsf/doctype/Bean.java
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/jsf/duplicateid/DuplicateIDIntegrationTestCase.java
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/jsf/duplicateid/deployment/IncludeBean.java
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/jsf/managedbean/annotation/AnnotatedManagedBeanTestCase.java
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/jsf/managedbean/annotation/SimpleJsfManagedBean.java
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/jsf/managedbean/gc/CountBean.java
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/jsf/managedbean/gc/CountBeanViewScoped.java
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/jsf/managedbean/gc/GCPreDestroyTestCase.java
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/jsf/managedbean/gc/InitBean.java
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/jsf/managedbean/gc/InitBeanViewScoped.java
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/jsf/managedbean/gc/TestResultsBean.java
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/jsf/managedbean/gc/sessionscoped.xhtml
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/jsf/managedbean/gc/viewscoped.xhtml
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/jsf/managedbean/xml/SimpleJsfXmlManagedBean.java
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/jsf/managedbean/xml/XmlManagedBeanTestCase.java
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/jsf/resourceResolver/CustomResourceResolver.java
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/jsf/resourceResolver/FaceletsResourceResolverTestCase.java
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/jsf/resourceResolver/index.xhtml
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/jsf/version/JSFDeploymentProcessorTestCase.java
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/jsf/version/war/JSFMyFaces.java
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/xerces/JSFManagedBean.java
Labels: deps-ok

#15269 [WFLY-15075] Add encryption support to FilesystemSecurityRealm
  docs/src/main/asciidoc/_elytron/Using_the_Elytron_Subsystem.adoc
  docs/src/main/asciidoc/_elytron/components/Filesystem_Security_Realm.adoc
  testsuite/integration/elytron/src/test/java/org/wildfly/test/integration/elytron/realm/FilesystemRealmEncryptedTestCase.java
Labels: Blocker, Feature-Docs, deps-ok

#15620 Upgrade Undertow to 2.3.0.Alpha1 in WildFly Preview
  ee-9/common/pom.xml
  ee-9/common/src/main/resources/license/preview-feature-pack-common-licenses.xml
  ee-9/ee-9-api/pom.xml
  ee-9/ee-9-api/src/main/resources/modules/system/layers/base/jakarta/websocket/api/main/module.xml
  ee-9/feature-pack/pom.xml
  ee-9/pom.xml
  ee-9/source-transform/clustering/web/undertow/pom.xml
  ee-9/source-transform/clustering/web/undertow/src/main/java/org/wildfly/clustering/web/undertow/session/UndertowSpecificationProvider.java
  ee-9/source-transform/jaxrs/pom.xml
  ee-9/source-transform/microprofile/openapi-smallrye/pom.xml
  ee-9/source-transform/mod_cluster/undertow/pom.xml
  ee-9/source-transform/undertow/pom.xml
  ee-9/source-transform/undertow/src/main/java/org/wildfly/extension/undertow/deployment/JspPropertyGroupDescriptorImpl.java
  pom.xml
  servlet-feature-pack/common/src/main/resources/modules/system/layers/base/io/undertow/jsp/main/module.xml
  servlet-feature-pack/common/src/main/resources/modules/system/layers/base/io/undertow/servlet/main/module.xml
  servlet-feature-pack/common/src/main/resources/modules/system/layers/base/io/undertow/websocket/main/module.xml
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/security/securitycontext/MyDummyTokenHandler.java
  testsuite/integration/web/src/test/java/org/jboss/as/test/integration/web/cookie/DefaultCookieVersionTestCase.java
  testsuite/preview/source-transform/web/pom.xml
Labels: deps-ok, EE10

#15617 [WFLY-16459] Move WildFly Preview from Jakarta Faces 4.0.0-M6 to 4.0.0
  pom.xml
Labels: deps-ok, EE10

#15618 [WFLY-16462] Fixing CoreBridgeCallTimeoutTestCase byteman rule file to properly match method signature
  testsuite/integration/manualmode/src/test/resources/byteman/CoreBridgeCallTimeoutTestCase.btm
Labels: deps-ok

#15621 [WFLY-16079] Update BV version
  pom.xml
Labels: deps-ok, EE10

#15625 [WFLY-15702]:Upgrade Jakarta XML Web Services 4.0 in WildFly Preview
  ee-9/ee-9-api/pom.xml
  ee-9/ee-9-api/src/main/resources/modules/system/layers/base/jakarta/jws/api/main/module.xml
  ee-9/ee-9-api/src/main/resources/modules/system/layers/base/jakarta/xml/ws/api/main/module.xml
  ee-9/ee-9-api/src/main/resources/modules/system/layers/base/javax/jws/api/main/module.xml
  ee-9/pom.xml
  pom.xml
Labels: deps-ok

#15627 [WFLY-15703] Upgrade Jakarta XML Binding to 4.0.0.
  ee-9/common/src/main/resources/modules/system/layers/base/com/sun/xml/bind/main/module.xml
  ee-9/common/src/main/resources/modules/system/layers/base/org/glassfish/jaxb/main/module.xml
  ee-9/common/src/main/resources/modules/system/layers/base/org/hibernate/main/module.xml
  ee-9/common/src/main/resources/modules/system/layers/base/org/jboss/ws/cxf/jbossws-cxf-client/main/module.xml
  ee-9/ee-9-api/src/main/resources/license/preview-feature-pack-ee-9-api-licenses.xml
  ee-9/ee-9-api/src/main/resources/modules/system/layers/base/jakarta/xml/bind/api/main/module.xml
  ee-9/feature-pack/pom.xml
  pom.xml
  testsuite/integration/basic/pom.xml
Labels: deps-ok

#15624 [WFLY-16457]:Upgrade CXF to 3.2.5-jbossorg-2 and CXF xjc utils to 4.0…
  pom.xml
Labels: deps-ok

#15328 [WFLY-16158]: Deployment submodel should be runtime
  connector/src/main/java/org/jboss/as/connector/subsystems/datasources/DataSourcesSubsystemRootDefinition.java
  connector/src/main/java/org/jboss/as/connector/subsystems/resourceadapters/ResourceAdaptersExtension.java
  ejb3/src/main/java/org/jboss/as/ejb3/subsystem/EJB3Extension.java
  jaxrs/src/main/java/org/jboss/as/jaxrs/JaxrsDeploymentDefinition.java
  jpa/subsystem/src/main/java/org/jboss/as/jpa/subsystem/JPADefinition.java
  messaging-activemq/subsystem/src/main/java/org/wildfly/extension/messaging/activemq/MessagingExtension.java
  microprofile/opentracing-extension/src/main/java/org/wildfly/extension/microprofile/opentracing/TracingDeploymentDefinition.java
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/jca/ijdeployment/IronJacamarDeploymentTestCase.java
  undertow/src/main/java/org/wildfly/extension/undertow/DeploymentDefinition.java
  webservices/server-integration/src/main/java/org/jboss/as/webservices/dmr/WSExtension.java
Labels: deps-ok

#15616 [WFLY-16456] Restore WildFly Preview execution of tests disabled by W…
  testsuite/integration/basic/pom.xml
Labels: deps-ok

#15600 [WFLY-16429] Remove component-matrix-builder
  component-matrix-builder/pom.xml
  pom.xml
Labels: deps-ok

#15632 [WFLY-16415] Move artifacts overridden in the wildfly-preview build b…
  ee-9/pom.xml
  ee-feature-pack/pom.xml
  galleon-pack/pom.xml
  jsf/injection/pom.xml
  jsf/pom.xml
  jsf/subsystem/pom.xml
  pom.xml
Labels: deps-ok

#15631 [WFLY-16474] Upgrade Weld in WildFly Preview to 5.0.0.SP2
  pom.xml
Labels: deps-ok

#15615 [WFLY-16458] Fix duplicate plugin declaration warn in testsuite/previ…
  testsuite/preview/basic/pom.xml
Labels: deps-ok

#15597 RTS (jakarta): WFLY-15447 and WFLY-15545
  ee-9/common/pom.xml
  ee-9/common/src/main/resources/license/preview-feature-pack-common-licenses.xml
  ee-9/feature-pack/pom.xml
  ee-9/pom.xml
  ee-9/source-transform/pom.xml
  ee-9/source-transform/rts/pom.xml
  ee-feature-pack/common/src/main/resources/modules/system/layers/base/org/jboss/narayana/rts/main/module.xml
  rts/src/main/java/org/wildfly/extension/rts/logging/RTSLogger.java
Labels: ready-for-merge, deps-ok

#15612 [WFLY-16449] Upgrade ASM to 9.3
  pom.xml
Labels: ready-for-merge, deps-ok

#15634 [WFLY-16427] Remove inappropriate language usage on elytron-oidc-clie…
  elytron-oidc-client/subsystem/src/test/java/org/wildfly/extension/elytron/oidc/OidcTestCase.java
  elytron-oidc-client/subsystem/src/test/resources/org/wildfly/extension/elytron/oidc/oidc-expressions.xml
  elytron-oidc-client/subsystem/src/test/resources/org/wildfly/extension/elytron/oidc/oidc.xml
  elytron-oidc-client/subsystem/src/test/resources/org/wildfly/extension/elytron/oidc/subsystem_1_0.xml
Labels: ready-for-merge, deps-ok

#15641 [WFLY-16415] Exclude community versions of transitive dependencies
  ee-feature-pack/pom.xml
  jaxrs/pom.xml
  undertow/pom.xml
Labels: ready-for-merge, deps-ok

#15643 WFLY-16099 Prune unnecessary dependencies from org.wildfly.clustering.singleton.server module
  clustering/singleton/server/pom.xml
  ee-feature-pack/common/src/main/resources/modules/system/layers/base/org/wildfly/clustering/singleton/server/main/module.xml
Labels: ready-for-merge, deps-ok

#15638 WFLY-16476 Upgrade jakarta.ejb-api from 4.0.0 to 4.0.1
  pom.xml
Labels: ready-for-merge, deps-ok, EE10

#15640 [WFLY-15696] Jakarta Faces 4.0 in WildFly Preview
  pom.xml
Labels: ready-for-merge, deps-ok

#15645 Jakarta Authentication and Authorization for EE10
  pom.xml
Labels: deps-ok

#15650 WFLY-16464 Modifying attributes of single-sign-on resource doesn't ma…
  clustering/common/src/main/java/org/jboss/as/clustering/controller/WriteAttributeStepHandler.java
  undertow/src/test/java/org/wildfly/extension/undertow/SecurityDomainSingleSignOnAttributesTestCase.java
Labels: deps-ok

#15646 [WFLY-16437] Remove duplicate dependency declaration to fix maven warn
  testsuite/preview/source-transform/smoke/pom.xml
Labels: deps-ok

#15652 [WFLY-16483] Eliminate undertow-*-jakarta dependencies from pom.xml files
  ee-9/source-transform/rts/pom.xml
  testsuite/preview/source-transform/smoke/pom.xml
Labels: deps-ok

#15649 [WFLY-15701]:Jakarta SOAP with Attachments 3.0 in WildFly Preview
  ee-9/ee-9-api/pom.xml
  ee-9/ee-9-api/src/main/resources/license/preview-feature-pack-ee-9-api-licenses.xml
  ee-9/ee-9-api/src/main/resources/modules/system/layers/base/jakarta/xml/soap/api/main/module.xml
  ee-9/pom.xml
  pom.xml
  testsuite/preview/source-transform/smoke/pom.xml
Labels: deps-ok

#15648 [WFLY-15559]:Move WildFly Preview to a native Jakarta namespace varia…
  ee-9/common/pom.xml
  ee-9/common/src/main/resources/license/preview-feature-pack-common-licenses.xml
  ee-9/pom.xml
  ee-9/source-transform/pom.xml
  ee-9/source-transform/webservices/pom.xml
  ee-9/source-transform/webservices/server-integration/pom.xml
  ee-feature-pack/common/src/main/resources/modules/system/layers/base/org/jboss/as/webservices/main/module.xml
  ee-feature-pack/pom.xml
  pom.xml
Labels: deps-ok

#15654 [Minor change]:Fix the preview-feature-pack-common-licenses.xml and j…
  ee-9/common/src/main/resources/license/preview-feature-pack-common-licenses.xml
  ee-9/source-transform/jaxrs/pom.xml
Labels: deps-ok

#15644 [WFLY-16479] Upgrade WildFly Preview to org.jboss.spec.jakarta.el:jbo…
  pom.xml
Labels: deps-ok, EE10

#15635 WFLY-16475: Upgrade HAL to 3.6.0.Final
  pom.xml
Labels: deps-ok

#15639 [WFLY-16477]: Upgrade Artemis to 2.23.0
  pom.xml
  testsuite/preview/basic/README.md
  testsuite/preview/basic/pom.xml
  testsuite/preview/basic/src/test/java/org/jboss/as/test/integration/messaging/jms/definitions/JMSResourceDefinitionsTestCase.java
  testsuite/preview/basic/src/test/java/org/jboss/as/test/integration/messaging/jms/definitions/MessagingBean.java
  testsuite/preview/basic/src/test/java/org/jboss/as/test/integration/messaging/jms/definitions/ejb-jar.xml
  testsuite/preview/basic/src/test/java/org/jboss/as/test/integration/messaging/jms/deployment/DependentMessagingDeploymentTestCase.java
  testsuite/preview/basic/src/test/java/org/jboss/as/test/integration/messaging/jms/deployment/MessagingServlet.java
  testsuite/preview/basic/src/test/java/org/jboss/as/test/integration/messaging/jms/deployment/QueueMDB.java
  testsuite/preview/basic/src/test/java/org/jboss/as/test/integration/messaging/jms/deployment/TopicMDB.java
Labels: deps-ok

#15659 [WFLY-16490] Remove duplicate declaration of wildfly-rts-jakarta arti…
  ee-9/pom.xml
Labels: deps-ok

#15622 [WFLY-16467] Move the JDR subsystem maven module up a level
  jdr/jboss-as-jdr/pom.xml
  jdr/jboss-as-jdr/src/test/resources/org/jboss/as/jdr/subsystem.xml
  jdr/pom.xml
  jdr/src/main/java/org/jboss/as/jdr/CommandLineMain.java
  jdr/src/main/java/org/jboss/as/jdr/CommonAttributes.java
  jdr/src/main/java/org/jboss/as/jdr/JdrReport.java
  jdr/src/main/java/org/jboss/as/jdr/JdrReportCollector.java
  jdr/src/main/java/org/jboss/as/jdr/JdrReportExtension.java
  jdr/src/main/java/org/jboss/as/jdr/JdrReportRequestHandler.java
  jdr/src/main/java/org/jboss/as/jdr/JdrReportService.java
  jdr/src/main/java/org/jboss/as/jdr/JdrReportSubsystemAdd.java
  jdr/src/main/java/org/jboss/as/jdr/JdrReportSubsystemDefinition.java
  jdr/src/main/java/org/jboss/as/jdr/JdrReportSubsystemParser.java
  jdr/src/main/java/org/jboss/as/jdr/JdrReportSubsystemRemove.java
  jdr/src/main/java/org/jboss/as/jdr/JdrRunner.java
  jdr/src/main/java/org/jboss/as/jdr/Namespace.java
  jdr/src/main/java/org/jboss/as/jdr/commands/CallAS7.java
  jdr/src/main/java/org/jboss/as/jdr/commands/CollectFiles.java
  jdr/src/main/java/org/jboss/as/jdr/commands/DeploymentDependencies.java
  jdr/src/main/java/org/jboss/as/jdr/commands/JarCheck.java
  jdr/src/main/java/org/jboss/as/jdr/commands/JdrCommand.java
  jdr/src/main/java/org/jboss/as/jdr/commands/JdrEnvironment.java
  jdr/src/main/java/org/jboss/as/jdr/commands/LocalModuleDependencies.java
  jdr/src/main/java/org/jboss/as/jdr/commands/SystemProperties.java
  jdr/src/main/java/org/jboss/as/jdr/commands/TreeCommand.java
  jdr/src/main/java/org/jboss/as/jdr/logger/JdrLogger.java
  jdr/src/main/java/org/jboss/as/jdr/plugins/AS7Plugin.java
  jdr/src/main/java/org/jboss/as/jdr/plugins/JdrPlugin.java
  jdr/src/main/java/org/jboss/as/jdr/plugins/PluginId.java
  jdr/src/main/java/org/jboss/as/jdr/util/AbstractSanitizer.java
  jdr/src/main/java/org/jboss/as/jdr/util/FSTree.java
  jdr/src/main/java/org/jboss/as/jdr/util/JdrZipFile.java
  jdr/src/main/java/org/jboss/as/jdr/util/PatternSanitizer.java
  jdr/src/main/java/org/jboss/as/jdr/util/Sanitizer.java
  jdr/src/main/java/org/jboss/as/jdr/util/Sanitizers.java
  jdr/src/main/java/org/jboss/as/jdr/util/Utils.java
  jdr/src/main/java/org/jboss/as/jdr/util/WildcardPattern.java
  jdr/src/main/java/org/jboss/as/jdr/util/XMLSanitizer.java
  jdr/src/main/java/org/jboss/as/jdr/vfs/Filters.java
  jdr/src/main/resources/META-INF/services/org.jboss.as.controller.Extension
  jdr/src/main/resources/org/jboss/as/jdr/LocalDescriptions.properties
  jdr/src/main/resources/schema/jboss-as-jdr_1_0.xsd
  jdr/src/test/java/org/jboss/as/jdr/FSTreeTest.java
  jdr/src/test/java/org/jboss/as/jdr/JdrSubsystemTestCase.java
  jdr/src/test/java/org/jboss/as/jdr/JdrTestCase.java
Labels: deps-ok

#15642 Upgrade Jakarta Connectors spec to 2.1 + TCK fix
  connector/src/main/java/org/jboss/as/connector/subsystems/jca/Constants.java
  connector/src/main/java/org/jboss/as/connector/subsystems/jca/JcaDistributedWorkManagerDefinition.java
  connector/src/main/java/org/jboss/as/connector/subsystems/jca/JcaExtension.java
  connector/src/main/java/org/jboss/as/connector/subsystems/jca/JcaWorkManagerDefinition.java
  connector/src/main/java/org/jboss/as/connector/subsystems/jca/Namespace.java
  connector/src/main/resources/schema/wildfly-jca_6_0.xsd
  connector/src/test/java/org/jboss/as/connector/subsystems/jca/JcaSubsystemTestCase.java
  connector/src/test/resources/org/jboss/as/connector/subsystems/complextestcases/jca.xml
  connector/src/test/resources/org/jboss/as/connector/subsystems/complextestcases/minimal-jca.xml
  connector/src/test/resources/org/jboss/as/connector/subsystems/jca/jca-full-expression.xml
  connector/src/test/resources/org/jboss/as/connector/subsystems/jca/jca-full.xml
  connector/src/test/resources/org/jboss/as/connector/subsystems/jca/jca-minimal.xml
  connector/src/test/resources/org/jboss/as/connector/subsystems/jca/jca.xml
  pom.xml
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/jca/security/workmanager/WildFlyActivationRaWithWMElytronSecurityDomainWorkManagerElytronUnconfiguredTestCase.java
Labels: deps-ok

#15656 WFLY-16485 Use @Deprecated(forRemoval=true) where appropriate
  clustering/common/src/main/java/org/jboss/as/clustering/msc/InjectedValueDependency.java
  clustering/common/src/main/java/org/jboss/as/clustering/msc/InjectorDependency.java
  clustering/common/src/main/java/org/jboss/as/clustering/msc/ValueDependency.java
  clustering/service/src/main/java/org/wildfly/clustering/service/Builder.java
  clustering/service/src/main/java/org/wildfly/clustering/service/ServiceNameRegistry.java
  clustering/service/src/main/java/org/wildfly/clustering/service/concurrent/Executor.java
  clustering/service/src/main/java/org/wildfly/clustering/service/concurrent/ServiceExecutor.java
  clustering/service/src/main/java/org/wildfly/clustering/service/concurrent/StampedLockServiceExecutor.java
  clustering/singleton/api/src/main/java/org/wildfly/clustering/singleton/SingletonCacheRequirement.java
  clustering/singleton/api/src/main/java/org/wildfly/clustering/singleton/SingletonDefaultCacheRequirement.java
  clustering/singleton/api/src/main/java/org/wildfly/clustering/singleton/SingletonDefaultRequirement.java
  clustering/singleton/api/src/main/java/org/wildfly/clustering/singleton/SingletonPolicy.java
  clustering/singleton/api/src/main/java/org/wildfly/clustering/singleton/SingletonRequirement.java
  clustering/singleton/api/src/main/java/org/wildfly/clustering/singleton/SingletonService.java
  clustering/singleton/api/src/main/java/org/wildfly/clustering/singleton/SingletonServiceBuilder.java
  clustering/singleton/api/src/main/java/org/wildfly/clustering/singleton/SingletonServiceBuilderFactory.java
  clustering/singleton/service/src/main/java/org/wildfly/clustering/singleton/service/SingletonCacheRequirement.java
  clustering/singleton/service/src/main/java/org/wildfly/clustering/singleton/service/SingletonDefaultCacheRequirement.java
Labels: deps-ok

#15663 Simple documentation change to add a section link to the headers. Thi…
  docs/pom.xml
Labels: deps-ok

#15660 Update to jakarta common annotations 2.1.1 to pick up the deprecated …
  pom.xml
Labels: deps-ok

#15664 [WFLY-16440] Upgrade WildFly HTTP Client to 1.1.12.Final
  pom.xml
Labels: deps-ok

#15653 [WFLY-16481]:EndpointService throws NPE when publish ws endpint with …
  webservices/server-integration/src/main/java/org/jboss/as/webservices/service/EndpointService.java
Labels: deps-ok

#15666 [WFLY-16493] Upgrade WildFly Core to 19.0.0.Beta12
  pom.xml
Labels: deps-ok

#15651 WFLY-16370 Drop redundant org.jboss.as.clustering.controller.Operations methods in favor of WFCORE-5906 methods.
  clustering/common/src/main/java/org/jboss/as/clustering/controller/AddStepHandler.java
  clustering/common/src/main/java/org/jboss/as/clustering/controller/MetricHandler.java
  clustering/common/src/main/java/org/jboss/as/clustering/controller/OperationHandler.java
  clustering/common/src/main/java/org/jboss/as/clustering/controller/Operations.java
  clustering/common/src/main/java/org/jboss/as/clustering/controller/ReadAttributeTranslationHandler.java
  clustering/common/src/main/java/org/jboss/as/clustering/controller/WriteAttributeTranslationHandler.java
  clustering/infinispan/extension/src/test/java/org/jboss/as/clustering/infinispan/subsystem/OperationTestCaseBase.java
  clustering/infinispan/extension/src/test/java/org/jboss/as/clustering/infinispan/subsystem/OperationsTestCase.java
  clustering/jgroups/extension/src/main/java/org/jboss/as/clustering/jgroups/subsystem/LegacyProtocolResourceDefinition.java
  clustering/jgroups/extension/src/main/java/org/jboss/as/clustering/jgroups/subsystem/ProtocolMetricsHandler.java
  clustering/jgroups/extension/src/main/java/org/jboss/as/clustering/jgroups/subsystem/ProtocolResourceDefinition.java
  clustering/jgroups/extension/src/main/java/org/jboss/as/clustering/jgroups/subsystem/StackOperationHandler.java
  clustering/jgroups/extension/src/test/java/org/jboss/as/clustering/jgroups/subsystem/JGroupsSubsystemTestCase.java
  clustering/jgroups/extension/src/test/java/org/jboss/as/clustering/jgroups/subsystem/OperationSequencesTestCase.java
  clustering/jgroups/extension/src/test/java/org/jboss/as/clustering/jgroups/subsystem/OperationTestCaseBase.java
  messaging-activemq/subsystem/src/test/java/org/wildfly/extension/messaging/activemq/ChangeToTrueConfig.java
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/ejb/stateless/callerprincipal/Ejb2GetCallerPrincipalServerSetupTask.java
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/jca/statistics/DataSourceMultipleConnStatsServerSetupTask.java
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/jca/statistics/DataSourceMultipleConnStatsTestCase.java
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/management/console/HttpManagementConstantHeadersTestCase.java
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/web/headers/authentication/ResponseHeaderAuthenticationServerSetupTask.java
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/web/security/authentication/BasicAuthMechanismServerSetupTask.java
  testsuite/integration/manualmode/pom.xml
  testsuite/integration/manualmode/src/test/java/org/jboss/as/test/manualmode/web/ssl/HTTPSWebConnectorTestCase.java
  testsuite/integration/ws/pom.xml
  testsuite/integration/ws/src/test/java/org/jboss/as/test/integration/ws/wsse/trust/WSTrustTestCaseElytronSecuritySetupTask.java
  testsuite/integration/ws/src/test/java/org/jboss/as/test/integration/ws/wsse/trust/WSTrustTestCaseSecuritySetupTask.java
  undertow/src/test/java/org/wildfly/extension/undertow/SecurityDomainSingleSignOnAttributesTestCase.java
Labels: deps-ok

#15671 Transformation fixes
  ee-9/common/src/main/resources/modules/system/layers/base/org/infinispan/hibernate-cache/main/module.xml
  ee-9/feature-pack/pom.xml
  ee-9/pom.xml
  ee-feature-pack/common/src/main/resources/modules/system/layers/base/org/jboss/narayana/compensations/main/module.xml
  ee-feature-pack/common/src/main/resources/modules/system/layers/base/org/jboss/narayana/txframework/main/module.xml
  ee-feature-pack/common/src/main/resources/modules/system/layers/base/org/wildfly/extension/rts/main/module.xml
  ee-feature-pack/pruned/src/main/resources/modules/system/layers/base/org/hibernate/jipijapa-hibernate5-3/main/module.xml
  jpa/hibernate6/src/main/java/org/jboss/as/jpa/hibernate/service/WildFlyCustomRegionFactoryInitiator.java
Labels: deps-ok

#15668 [WFLY-16470] OpenTelemetry Instance Leak in OpenTelemetryClientRequestFilter
  observability/opentelemetry-api/src/main/java/org/wildfly/extension/opentelemetry/api/OpenTelemetryClientRequestFilter.java
Labels: ready-for-merge, deps-ok

#15680 WFLY-16489 Clustering TS: Include node name in clustering console log messages
  testsuite/integration/clustering/clustering-all.cli
  testsuite/integration/clustering/clustering-bootable.cli
  testsuite/integration/clustering/clustering-mp.cli
Labels: ready-for-merge, deps-ok

#15677 [WFLY-16504] / [WFLY-16505] Upgrade Elytron EE to 3.0.0.Beta2 and Elytron Web to 3.0.0.Beta1
  pom.xml
Labels: ready-for-merge, deps-ok, EE10

#15679 MicroProfile Reactive Messaging 3.17.0 and MP Config 3.10.1 Upgrades
  pom.xml
Labels: ready-for-merge, deps-ok

#15681 MicroProfile Upgrades for WildFly Preview
  pom.xml
Labels: ready-for-merge, deps-ok

#15658 [WFLY-16486] upgraded Hibernate ORM to 5.3.27.Final
  pom.xml
Labels: ready-for-merge, deps-ok

#15588 WFLY-16417 Add MP certification page generation script
  pom.xml
  testsuite/integration/microprofile-tck/certification/microprofile-certification.sh
  testsuite/integration/microprofile-tck/certification/pom.xml
  testsuite/integration/microprofile-tck/pom.xml
Labels: deps-ok

#15683 WFLY-16515 Fix inadvertent removal of Infinispan JDBC store's table prefix property
  clustering/infinispan/extension/src/main/java/org/jboss/as/clustering/infinispan/subsystem/InfinispanSubsystemXMLReader.java
  clustering/infinispan/extension/src/main/resources/schema/jboss-as-infinispan_14_0.xsd
  clustering/infinispan/extension/src/test/resources/org/jboss/as/clustering/infinispan/subsystem/subsystem-infinispan-14_0.xml
Labels: deps-ok

#15687 [WFLY-15445] Migrate WildFly Preview to org.jboss.openjdk-orb:openjdk…
  ee-9/common/pom.xml
  ee-9/common/src/main/resources/license/preview-feature-pack-common-licenses.xml
  ee-9/feature-pack/pom.xml
  ee-9/pom.xml
  ee-9/source-transform/ejb3/pom.xml
  ee-9/source-transform/iiop-openjdk/pom.xml
  ee-9/source-transform/transactions/pom.xml
  ee-feature-pack/common/src/main/resources/modules/system/layers/base/javax/orb/api/main/module.xml
  ee-feature-pack/pom.xml
  legacy/jacorb/pom.xml
  pom.xml
Labels: ready-for-merge, deps-ok, EE10

#15689 More WildFly Preview Transformation Fixes
  ee-9/ee-9-api/pom.xml
  ee-9/feature-pack/pom.xml
  ee-feature-pack/pruned/src/main/resources/modules/system/layers/base/javax/xml/bind/api/main/module.xml
Labels: ready-for-merge, deps-ok

#15692 WFLY-16524 Add missing static container initialization causing test to fail when run individually.
  clustering/weld/core/src/test/java/org/wildfly/clustering/weld/bean/ManagedBeanIdentifierMarshallerTestCase.java
Labels: deps-ok

#15686 Resolve CNFE in upstream weld in-container tests.
  clustering/weld/ejb/src/main/java/org/wildfly/clustering/weld/ejb/SerializedStatefulSessionObjectMarshaller.java
  ee-feature-pack/common/src/main/resources/modules/system/layers/base/org/jboss/as/weld/main/module.xml
  weld/common/src/main/java/org/jboss/as/weld/util/ServiceLoaders.java
  weld/ejb/src/main/java/org/jboss/as/weld/ejb/SerializedStatefulSessionObject.java
  weld/subsystem/src/main/java/org/jboss/as/weld/deployment/processors/ExternalBeanArchiveProcessor.java
  weld/subsystem/src/main/java/org/jboss/as/weld/deployment/processors/WeldDeploymentProcessor.java
Labels: deps-ok

#15678 [WFLY-16445][WFLY-16446] CDI @Resource injection of values configured via deploym…
  testsuite/integration/basic/src/test/java/org/wildfly/test/integration/weld/resource/EnvEntryInjectionBean.java
  testsuite/integration/basic/src/test/java/org/wildfly/test/integration/weld/resource/SimpleEnvEntryResourceInjectionTestCase.java
  testsuite/integration/basic/src/test/java/org/wildfly/test/integration/weld/resource/jboss-web.xml
  weld/subsystem/src/main/java/org/jboss/as/weld/WeldSubsystemAdd.java
  weld/subsystem/src/main/java/org/jboss/as/weld/deployment/processors/SimpleEnvEntryCdiResourceInjectionProcessor.java
Labels: ready-for-merge, deps-ok, EE10

#15661 [WFLY-16492] Use 6.0.0 as the new ModelVersion; add domain transforma…
  connector/src/main/java/org/jboss/as/connector/subsystems/jca/DistributedWorkManagerAdd.java
  connector/src/main/java/org/jboss/as/connector/subsystems/jca/JcaDistributedWorkManagerDefinition.java
  connector/src/main/java/org/jboss/as/connector/subsystems/jca/JcaExtension.java
  connector/src/main/java/org/jboss/as/connector/subsystems/jca/JcaTransformers.java
  connector/src/main/java/org/jboss/as/connector/subsystems/jca/JcaWorkManagerDefinition.java
  connector/src/main/java/org/jboss/as/connector/subsystems/jca/WorkManagerAdd.java
  connector/src/main/resources/META-INF/services/org.jboss.as.controller.transform.ExtensionTransformerRegistration
  connector/src/test/java/org/jboss/as/connector/subsystems/jca/JcaSubsystemTestCase.java
  connector/src/test/resources/org/jboss/as/connector/subsystems/jca/jca-default-elytron.xml
  connector/src/test/resources/org/jboss/as/connector/subsystems/jca/jca_5_0.xml
Labels: deps-ok

#15675 WFLY-16495: exclude wildfly-cli:client from transformation, WFLY-16500: upgrade galleon-plugins
  ee-9/feature-pack/pom.xml
  pom.xml
Labels: deps-ok

#15244 [WFLY-16058] Add utilities to provide empty deployments for tests tha…
  testsuite/shared/src/main/java/org/jboss/as/test/shared/util/AssumeTestGroupUtil.java
Labels: deps-ok

#15694 WFLY-16496 narayana component upgrade
  ee-9/feature-pack/pom.xml
  pom.xml
Labels: deps-ok

#15697 WFLY-16537 Upgrade jakarta batch api from 2.1.0 to 2.1.1
  pom.xml
Labels: deps-ok, EE10

#15696 WFLY-16526 Remove deprecated WeldDeploymentMarker, keep its private version in different package
  ee/src/main/java/org/jboss/as/ee/weld/WeldDeploymentMarker.java
  weld/subsystem/src/main/java/org/jboss/as/weld/_private/WeldDeploymentMarker.java
Labels: deps-ok

#15695 [WFLY-16531]: Upgrade Apache Artemis to 2.23.1
  pom.xml
Labels: deps-ok

#15674 [WFLY-15435]:Move WildFly Preview to a native jakarta namespace varia…
  ee-9/pom.xml
  ee-feature-pack/common/pom.xml
  ee-feature-pack/common/src/main/resources/license/ee-feature-pack-common-licenses.xml
  ee-feature-pack/common/src/main/resources/modules/system/layers/base/org/jboss/ws/jaxws-client/main/module.xml
  ee-feature-pack/pom.xml
  pom.xml
Labels: deps-changed

#15702 [WFLY-16540] Adding missing JPMS open privileges required by JCETestCase
  testsuite/integration/basic/pom.xml
Labels: deps-ok

#15713 [WFLY-16550] Upgrading Undertow Jastow to 2.2.1.Final
  pom.xml
Labels: deps-ok

#15708 Add more exclusions for transformed libraries
  ee-9/feature-pack/pom.xml
Labels: deps-ok

#15719 Remove stray System.outs in clustering modules
  clustering/ejb/extension/src/test/java/org/wildfly/extension/clustering/ejb/DistributableEjbSubsystemTestCase.java
  clustering/weld/core/src/main/java/org/wildfly/clustering/weld/annotated/slim/AnnotatedTypeMarshaller.java
Labels: deps-ok

#15716 WFLY-16557 Update Weld to 5.0.1.Final
  pom.xml
Labels: deps-ok

#15714 [WFLY-16441] Eliminating unsupported scenarios since Servlet API 6.0 version
  testsuite/integration/web/src/test/java/org/jboss/as/test/integration/web/cookie/DefaultCookieVersionTestCase.java
Labels: deps-ok

#15710 WFLY-16548 Upgrade smallrye-fault-tolerance to 5.4.1
  pom.xml
Labels: deps-ok

#15711 [WFLY-16549] Update HV to 8.0.0.CR1
  pom.xml
Labels: deps-ok, EE10

#15673 [WFLY-16499] Temporarily restore use of the embedded messaging broker…
  ee-9/galleon-content-microprofile/src/main/resources/feature_groups/standalone-full.xml
  ee-9/galleon-content/src/main/resources/feature_groups/standalone-full-ha.xml
Labels: big-bang

#15698 [WFLY-16538] Remove support for log4j 1.x. Removed dependencies and d…
  docs/src/main/asciidoc/_admin-guide/subsystem-configuration/EE.adoc
  docs/src/main/asciidoc/_admin-guide/subsystem-configuration/EE_Application_Deployment_Configuration.adoc
  docs/src/main/asciidoc/_admin-guide/subsystem-configuration/Logging.adoc
  docs/src/main/asciidoc/_admin-guide/subsystem-configuration/Logging_How_To.adoc
  docs/src/main/asciidoc/_developer-guide/Implicit_module_dependencies_for_deployments.adoc
  docs/src/main/asciidoc/_developer-guide/Migrate_Order_Application_from_EAP5.adoc
  ee-feature-pack/common/src/main/resources/modules/system/layers/base/org/jboss/as/appclient/main/module.xml
  ee-feature-pack/common/src/main/resources/modules/system/layers/base/org/jboss/ws/jaxws-client/main/module.xml
  ee-feature-pack/common/src/main/resources/modules/system/layers/base/org/jboss/ws/tools/common/main/module.xml
  ee/src/test/java/org/jboss/as/ee/subsystem/EeLegacySubsystemTestCase.java
  ee/src/test/resources/org/jboss/as/ee/subsystem/subsystem.xml
  ee/src/test/resources/org/jboss/as/ee/subsystem/subsystem_1_2.xml
  ee/src/test/resources/org/jboss/as/ee/subsystem/subsystem_3_0.xml
  ee/src/test/resources/org/jboss/as/ee/subsystem/subsystem_4_0.xml
  ee/src/test/resources/org/jboss/as/ee/subsystem/subsystem_5_0.xml
  microprofile/galleon-common/src/main/resources/modules/system/layers/base/io/vertx/client/kafka/main/module.xml
  microprofile/galleon-common/src/main/resources/modules/system/layers/base/io/vertx/core/main/module.xml
  pom.xml
  testsuite/integration/basic/pom.xml
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/management/console/HttpManagementConstantHeadersTestCase.java
  testsuite/integration/manualmode/pom.xml
  testsuite/integration/rts/pom.xml
  testsuite/integration/smoke/pom.xml
Labels: ready-for-merge, deps-ok

#15705 [WFLY-16428] LegacyCompliantPrincipalPropagationTestCase fails in Windows
  testsuite/integration/manualmode/src/test/java/org/jboss/as/test/manualmode/weld/builtinBeans/LegacyCompliantPrincipalPropagationTestCase.java
Labels: ready-for-merge, deps-ok
