Repository wildfly/wildfly, pull requests merged in 2022-12, with the labels that each got.

#16319 [WFLY-17335] Removing dead code in PooledConnectionFactoryService
  messaging-activemq/subsystem/src/main/java/org/wildfly/extension/messaging/activemq/jms/PooledConnectionFactoryService.java
Labels: deps-ok

#16336 Add a simple build job for validating a PR builds in a clean environm…
  .github/workflows/build-only.yml
Labels: deps-ok

#16337 WFLY-17352 Fix inadvertent service loading on the request thread.
  clustering/web/undertow/src/main/java/org/wildfly/clustering/web/undertow/session/SessionManagerFactoryConfigurationAdapter.java
Labels: deps-ok, 28.x

#16338 WFLY-17352 Fix inadvertent service loading on the request thread.
  clustering/web/undertow/src/main/java/org/wildfly/clustering/web/undertow/session/SessionManagerFactoryConfigurationAdapter.java
Labels: 27.x

#16320 [WFLY-17336] Eliminating usage of deprecated org.jboss.msc.inject.MapInjector
  mail/src/main/java/org/jboss/as/mail/extension/DirectMailSessionService.java
  mail/src/main/java/org/jboss/as/mail/extension/MailSessionAdd.java
  mail/src/main/java/org/jboss/as/mail/extension/MailSessionService.java
  mail/src/main/java/org/jboss/as/mail/extension/SessionProviderFactory.java
Labels: deps-ok

#16340 [WFLY-17354] Remove the jsf/multi-installer module
  docs/src/main/asciidoc/_admin-guide/Subsystem_configuration.adoc
  docs/src/main/asciidoc/_admin-guide/subsystem-configuration/Jakarta_Server_Faces.adoc
  jsf/multi-jsf-installer/pom.xml
  jsf/multi-jsf-installer/src/main/assembly/src.xml
  jsf/multi-jsf-installer/src/main/resources/mojarra-api-module.xml
  jsf/multi-jsf-installer/src/main/resources/mojarra-deploy.scr
  jsf/multi-jsf-installer/src/main/resources/mojarra-impl-module.xml
  jsf/multi-jsf-installer/src/main/resources/mojarra-injection-module.xml
  jsf/multi-jsf-installer/src/main/resources/mojarra-undeploy.scr
  jsf/multi-jsf-installer/src/main/resources/myfaces-api-module.xml
  jsf/multi-jsf-installer/src/main/resources/myfaces-deploy.scr
  jsf/multi-jsf-installer/src/main/resources/myfaces-digester-module.xml
  jsf/multi-jsf-installer/src/main/resources/myfaces-impl-module.xml
  jsf/multi-jsf-installer/src/main/resources/myfaces-injection-module.xml
  jsf/multi-jsf-installer/src/main/resources/myfaces-undeploy.scr
  jsf/pom.xml
Labels: ready-for-merge, deps-ok

#16341 WFLY-17355 Upgrade Infinispan to 14.0.3.Final
  pom.xml
  testsuite/integration/clustering/pom.xml
  testsuite/integration/clustering/src/test/java/org/jboss/as/test/clustering/cluster/infinispan/lock/deployment/InfinispanLockServlet.java
  testsuite/integration/clustering/src/test/java/org/jboss/as/test/clustering/single/infinispan/InfinispanModulesTestSuite.java
  testsuite/integration/clustering/src/test/java/org/jboss/as/test/clustering/single/infinispan/cdi/embedded/DuplicatedDomainsCdiTestCase.java
  testsuite/integration/clustering/src/test/java/org/jboss/as/test/clustering/single/infinispan/cdi/embedded/GreetingCacheManagerTestCase.java
  testsuite/integration/clustering/src/test/java/org/jboss/as/test/clustering/single/infinispan/cdi/embedded/deployment/GreetingCacheManager.java
  testsuite/integration/clustering/src/test/java/org/jboss/as/test/clustering/single/infinispan/embedded/InfinispanCoreTestCase.java
  testsuite/integration/clustering/src/test/java/org/jboss/as/test/clustering/single/infinispan/query/ContainerManagedHotRodClientTestCase.java
  testsuite/integration/clustering/src/test/java/org/jboss/as/test/clustering/single/infinispan/query/ContainerRemoteQueryTestCase.java
  testsuite/integration/clustering/src/test/java/org/jboss/as/test/clustering/single/infinispan/query/RemoteQueryTestCase.java
Labels: ready-for-merge, deps-ok

#16342 [WFLY-17359] Update protobuf to 3.19.6 (resolves CVE-2022-3171)
  pom.xml
Labels: ready-for-merge, deps-ok

#16343 [27.x][WFLY-17359] Update protobuf to 3.19.6 (resolves CVE-2022-3171)
  pom.xml
Labels: 27.x

#16294 WFLY-16807 - Update `resteasy-spring` to `3.0.0.Final`
  boms/preview-ee/pom.xml
  boms/standard-ee/pom.xml
  docs/src/main/asciidoc/_developer-guide/Jakarta_RESTful_Web_Services_Reference_Guide.adoc
  ee-9/common/pom.xml
  ee-9/common/src/main/resources/license/preview-feature-pack-common-licenses.xml
  ee-9/galleon-content/src/main/resources/feature_groups/jaxrs.xml
  ee-feature-pack/common/pom.xml
  ee-feature-pack/common/src/main/resources/license/ee-feature-pack-common-licenses.xml
  ee-feature-pack/common/src/main/resources/modules/system/layers/base/org/jboss/resteasy/resteasy-spring/main/module.xml
  ee-feature-pack/galleon-content/src/main/resources/packages/org.jboss.resteasy.resteasy-spring/pm/wildfly/tasks.xml
  jaxrs/src/main/java/org/jboss/as/jaxrs/JaxrsSubsystemDefinition.java
  pom.xml
Labels: deps-changed

#16355 [WFLY-17374] Upgrade apache xerces from 2.12.0.SP04 to 2.12.0.SP05
  pom.xml
Labels: deps-ok

#16360 [WFLY-17367]:Add NPE guard in WSEndpointMetrics
  webservices/server-integration/src/main/java/org/jboss/as/webservices/dmr/WSEndpointMetrics.java
Labels: 27.x

#16339 [27.x] [WFLY-16807] Upgrade RESTEasy Spring to 3.0.0.Final and migrate back to WildFly from WildFly Preview
  boms/preview-ee/pom.xml
  boms/standard-ee/pom.xml
  docs/src/main/asciidoc/_developer-guide/Jakarta_RESTful_Web_Services_Reference_Guide.adoc
  ee-9/common/pom.xml
  ee-9/common/src/main/resources/license/preview-feature-pack-common-licenses.xml
  ee-9/galleon-content/src/main/resources/feature_groups/jaxrs.xml
  ee-feature-pack/common/pom.xml
  ee-feature-pack/common/src/main/resources/license/ee-feature-pack-common-licenses.xml
  ee-feature-pack/common/src/main/resources/modules/system/layers/base/org/jboss/resteasy/resteasy-spring/main/module.xml
  ee-feature-pack/galleon-content/src/main/resources/packages/org.jboss.resteasy.resteasy-spring/pm/wildfly/tasks.xml
  jaxrs/src/main/java/org/jboss/as/jaxrs/JaxrsSubsystemDefinition.java
  pom.xml
Labels: 27.x

#16352 [WFLY-17370] Upgrade WildFly Core to 20.0.0.Beta4
  pom.xml
Labels: deps-ok

#16351 [WFLY-17363]: Upgrade artemis-wildfly-integration from 1.0.6 to 1.0.7
  pom.xml
Labels: deps-ok

#16357 WFLY-17375: Upgrade HAL to 3.6.5.Final
  pom.xml
Labels: deps-ok

#16364 [WFLY-17383] Excluding LDAP server tests on JDK20+ for now
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/naming/ExternalContextBindingTestCase.java
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/naming/ldap/LdapUrlInSearchBaseTestCase.java
  testsuite/integration/elytron/src/test/java/org/wildfly/test/integration/elytron/realm/LdapRealmTestCase.java
Labels: deps-ok

#16354 WFLY-17373 Upgrade to Hibernate ORM 6.1.6.Final
  pom.xml
Labels: deps-ok

#16349 [WFLY-17270] Drop source transformation for undertow
  boms/legacy-ee/pom.xml
  ee-9/source-transform/pom.xml
  ee-9/source-transform/undertow/pom.xml
  ee-9/source-transform/undertow/src/main/java/org/wildfly/extension/undertow/deployment/JspPropertyGroupDescriptorImpl.java
  pom.xml
  undertow/pom.xml
  undertow/src/main/java/org/wildfly/extension/undertow/ImportedClassELResolver.java
  undertow/src/main/java/org/wildfly/extension/undertow/WebHostService.java
  undertow/src/main/java/org/wildfly/extension/undertow/deployment/JspApplicationContextWrapper.java
  undertow/src/main/java/org/wildfly/extension/undertow/deployment/JspConfigDescriptorImpl.java
  undertow/src/main/java/org/wildfly/extension/undertow/deployment/JspInitializationListener.java
  undertow/src/main/java/org/wildfly/extension/undertow/deployment/JspPropertyGroupDescriptorImpl.java
  undertow/src/main/java/org/wildfly/extension/undertow/deployment/ScisMetaData.java
  undertow/src/main/java/org/wildfly/extension/undertow/deployment/ServletContainerInitializerDeploymentProcessor.java
  undertow/src/main/java/org/wildfly/extension/undertow/deployment/TaglibDescriptorImpl.java
  undertow/src/main/java/org/wildfly/extension/undertow/deployment/UndertowDeploymentInfoService.java
  undertow/src/main/java/org/wildfly/extension/undertow/deployment/UndertowDeploymentProcessor.java
  undertow/src/main/java/org/wildfly/extension/undertow/deployment/UndertowDeploymentService.java
  undertow/src/main/java/org/wildfly/extension/undertow/deployment/UndertowJSRWebSocketDeploymentProcessor.java
  undertow/src/main/java/org/wildfly/extension/undertow/deployment/WarAnnotationDeploymentProcessor.java
  undertow/src/main/java/org/wildfly/extension/undertow/deployment/WarMetaDataProcessor.java
  undertow/src/main/java/org/wildfly/extension/undertow/deployment/WebComponentProcessor.java
  undertow/src/main/java/org/wildfly/extension/undertow/security/jacc/JACCAuthorizationManager.java
  undertow/src/main/java/org/wildfly/extension/undertow/security/jacc/JACCContextIdHandler.java
  undertow/src/main/java/org/wildfly/extension/undertow/security/jacc/WarJACCService.java
Labels: deps-ok

#16334 [WFLY-17342] Upgrade ironjacamar to 1.5.10.Final
  pom.xml
Labels: deps-ok

#16358 WFLY-17376: Upgrade HAL to 3.6.5.Final (WildFly 27.0.1.Final)
  pom.xml
Labels: 27.x

#16344 [WFLY-17186] Fix exception handling by ManagedScheduledExecutorServic…
  ee-9/source-transform/ee/src/main/java/org/jboss/as/ee/concurrent/ControlPointUtils.java
  ee-9/source-transform/ee/src/main/java/org/jboss/as/ee/logging/EeLogger.java
  ee/src/main/java/org/jboss/as/ee/concurrent/ControlPointUtils.java
  ee/src/main/java/org/jboss/as/ee/logging/EeLogger.java
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/ee/concurrent/ManagedScheduledExecutorExceptionTestCase.java
Labels: deps-ok

#16345 [27.x][WFLY-17186] Fix exception handling by ManagedScheduledExecutorServic…
  ee-9/source-transform/ee/src/main/java/org/jboss/as/ee/concurrent/ControlPointUtils.java
  ee-9/source-transform/ee/src/main/java/org/jboss/as/ee/logging/EeLogger.java
  ee/src/main/java/org/jboss/as/ee/concurrent/ControlPointUtils.java
  ee/src/main/java/org/jboss/as/ee/logging/EeLogger.java
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/ee/concurrent/ManagedScheduledExecutorExceptionTestCase.java
Labels: 27.x

#16333 [27.x][WFLY-17350] Custom mail providers are not loaded
  mail/src/main/java/org/jboss/as/mail/extension/SessionProviderFactory.java
  servlet-feature-pack/common/src/main/resources/modules/system/layers/base/org/jboss/as/naming/main/module.xml
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/mail/providers/MailSessionCustomProviderTestCase.java
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/mail/providers/javamail.providers
Labels: 27.x

#16240 [WFLY-17228] Upgrade ASM to 9.4
  pom.xml
Labels: deps-ok

#16321 [WFLY-17337] Eliminating usage of deprecated org.jboss.msc.inject.CastingInjector
  jpa/subsystem/src/main/java/org/jboss/as/jpa/processor/PersistenceUnitServiceHandler.java
  jpa/subsystem/src/main/java/org/jboss/as/jpa/service/JPAUserTransactionListenerService.java
Labels: deps-ok

#16318 [WFLY-17334] Eliminating usage of deprecated org.jboss.msc.inject.ConcurrentMapInjector
  connector/src/main/java/org/jboss/as/connector/subsystems/datasources/AbstractDataSourceAdd.java
  connector/src/main/java/org/jboss/as/connector/subsystems/datasources/DataSourceConfigService.java
  connector/src/main/java/org/jboss/as/connector/subsystems/datasources/XADataSourceConfigService.java
Labels: deps-ok

#16368 WFLY-17393 Remove unreferenced static HashMaps from Undertow subsystem
  undertow/src/main/java/org/wildfly/extension/undertow/CrawlerSessionManagementDefinition.java
  undertow/src/main/java/org/wildfly/extension/undertow/JspDefinition.java
  undertow/src/main/java/org/wildfly/extension/undertow/MimeMappingDefinition.java
  undertow/src/main/java/org/wildfly/extension/undertow/Namespace.java
  undertow/src/main/java/org/wildfly/extension/undertow/PersistentSessionsDefinition.java
  undertow/src/main/java/org/wildfly/extension/undertow/SessionCookieDefinition.java
  undertow/src/main/java/org/wildfly/extension/undertow/WelcomeFileDefinition.java
Labels: deps-ok

#16347 WFLY-17348 A distributed web application request coinciding with leaving of the primary session owner can cause an NPE
  clustering/ee/infinispan/src/main/java/org/wildfly/clustering/ee/infinispan/PrimaryOwnerLocator.java
  clustering/ee/infinispan/src/test/java/org/wildfly/clustering/ee/infinispan/PrimaryOwnerLocatorTestCase.java
  clustering/server/extension/src/main/java/org/wildfly/extension/clustering/server/group/AbstractLocalGroupServiceConfigurator.java
  clustering/server/extension/src/main/java/org/wildfly/extension/clustering/server/group/CacheGroupServiceConfigurator.java
  clustering/server/extension/src/main/java/org/wildfly/extension/clustering/server/group/LocalCacheGroupServiceConfigurator.java
  clustering/server/extension/src/main/java/org/wildfly/extension/clustering/server/group/LocalCacheGroupServiceConfiguratorProvider.java
  clustering/server/extension/src/main/java/org/wildfly/extension/clustering/server/group/LocalGroupServiceConfigurator.java
  clustering/server/extension/src/main/java/org/wildfly/extension/clustering/server/provider/CacheServiceProviderRegistryServiceConfigurator.java
  clustering/server/extension/src/main/java/org/wildfly/extension/clustering/server/registry/CacheRegistryFactoryServiceConfigurator.java
  clustering/server/infinispan/src/main/java/org/wildfly/clustering/server/infinispan/dispatcher/ChannelCommandDispatcher.java
  clustering/server/infinispan/src/main/java/org/wildfly/clustering/server/infinispan/dispatcher/ChannelCommandDispatcherFactory.java
  clustering/server/infinispan/src/main/java/org/wildfly/clustering/server/infinispan/dispatcher/ViewMembership.java
  clustering/server/infinispan/src/main/java/org/wildfly/clustering/server/infinispan/group/AbstractLocalGroup.java
  clustering/server/infinispan/src/main/java/org/wildfly/clustering/server/infinispan/group/Addressable.java
  clustering/server/infinispan/src/main/java/org/wildfly/clustering/server/infinispan/group/AddressableNode.java
  clustering/server/infinispan/src/main/java/org/wildfly/clustering/server/infinispan/group/AutoCloseableGroup.java
  clustering/server/infinispan/src/main/java/org/wildfly/clustering/server/infinispan/group/CacheGroup.java
  clustering/server/infinispan/src/main/java/org/wildfly/clustering/server/infinispan/group/CacheMembership.java
  clustering/server/infinispan/src/main/java/org/wildfly/clustering/server/infinispan/group/InfinispanAddressResolver.java
  clustering/server/infinispan/src/main/java/org/wildfly/clustering/server/infinispan/group/JGroupsAddressResolver.java
  clustering/server/infinispan/src/main/java/org/wildfly/clustering/server/infinispan/group/LocalCacheGroup.java
  clustering/server/infinispan/src/main/java/org/wildfly/clustering/server/infinispan/group/LocalGroup.java
  clustering/server/infinispan/src/main/java/org/wildfly/clustering/server/infinispan/provider/AutoCloseableServiceProviderRegistry.java
  clustering/server/infinispan/src/main/java/org/wildfly/clustering/server/infinispan/provider/CacheServiceProviderRegistry.java
  clustering/server/infinispan/src/main/java/org/wildfly/clustering/server/infinispan/provider/LocalServiceProviderRegistry.java
  clustering/server/infinispan/src/main/java/org/wildfly/clustering/server/infinispan/registry/CacheRegistry.java
  clustering/server/infinispan/src/main/java/org/wildfly/clustering/server/infinispan/registry/CacheRegistryConfiguration.java
  clustering/server/spi/src/main/java/org/wildfly/clustering/server/NodeFactory.java
  clustering/web/infinispan/src/main/java/org/wildfly/clustering/web/infinispan/routing/RankedRouteLocator.java
Labels: deps-ok

#16371 [27.x][WFLY-17406] Upgrade WildFly Core to 19.0.1.Final
  pom.xml
Labels: 27.x

#16369 WFLY-17262 - Drop source transformation for jsf subsystem
  ee-9/source-transform/jsf/injection/pom.xml
  ee-9/source-transform/jsf/injection/src/main/java/org/jboss/as/jsf/injection/AnnotationMap.java
  ee-9/source-transform/jsf/pom.xml
  ee-9/source-transform/jsf/subsystem/pom.xml
  ee-9/source-transform/jsf/subsystem/src/main/java/org/jboss/as/jsf/deployment/FacesAnnotation.java
  ee-9/source-transform/pom.xml
  jsf/injection/pom.xml
  jsf/injection/src/main/java/org/jboss/as/jsf/injection/AnnotationMap.java
  jsf/injection/src/main/java/org/jboss/as/jsf/injection/JSFInjectionProvider.java
  jsf/injection/src/main/java/org/jboss/as/jsf/injection/JandexAnnotationProvider.java
  jsf/injection/src/main/java/org/jboss/as/jsf/injection/MyFacesAnnotationProvider.java
  jsf/injection/src/main/java/org/jboss/as/jsf/injection/MyFacesContainerInitializer.java
  jsf/injection/src/main/java/org/jboss/as/jsf/injection/MyFacesInjectionProviderFactory.java
  jsf/injection/src/main/java/org/jboss/as/jsf/injection/MyFacesLifecycleProvider.java
  jsf/injection/src/main/java/org/jboss/as/jsf/injection/MyFacesLifecycleProviderFactory.java
  jsf/injection/src/main/java/org/jboss/as/jsf/injection/weld/DummyELResolver.java
  jsf/injection/src/main/java/org/jboss/as/jsf/injection/weld/ForwardingApplicationFactory.java
  jsf/injection/src/main/java/org/jboss/as/jsf/injection/weld/ForwardingELResolver.java
  jsf/injection/src/main/java/org/jboss/as/jsf/injection/weld/WeldApplication.java
  jsf/injection/src/main/java/org/jboss/as/jsf/injection/weld/WeldApplicationFactory.java
  jsf/injection/src/main/java/org/jboss/as/jsf/injection/weld/legacy/ForwardingApplication.java
  jsf/injection/src/main/java/org/jboss/as/jsf/injection/weld/legacy/WeldApplicationFactoryLegacy.java
  jsf/injection/src/main/java/org/jboss/as/jsf/injection/weld/legacy/WeldApplicationLegacy.java
  jsf/pom.xml
  jsf/subsystem/pom.xml
  jsf/subsystem/src/main/java/org/jboss/as/jsf/deployment/FacesAnnotation.java
  jsf/subsystem/src/main/java/org/jboss/as/jsf/deployment/JSFAnnotationProcessor.java
  jsf/subsystem/src/main/java/org/jboss/as/jsf/deployment/JSFBeanValidationFactoryProcessor.java
  jsf/subsystem/src/main/java/org/jboss/as/jsf/deployment/JSFComponentProcessor.java
  jsf/subsystem/src/main/java/org/jboss/as/jsf/deployment/JSFDependencyProcessor.java
  jsf/subsystem/src/main/java/org/jboss/as/jsf/deployment/JSFMetadataProcessor.java
  jsf/subsystem/src/main/java/org/jboss/as/jsf/deployment/JSFModuleIdFactory.java
  jsf/subsystem/src/main/java/org/jboss/as/jsf/deployment/JSFPassivatingViewScopedCdiExtension.java
  jsf/subsystem/src/main/java/org/jboss/as/jsf/deployment/JSFVersionProcessor.java
  jsf/subsystem/src/test/java/org/jboss/as/jsf/deployment/JSFModuleIdFactoryTestCase.java
  pom.xml
Labels: deps-ok

#16348 [WFLY-17266] Drop source transformation for rso/cdi-provider
  boms/legacy-expansion/pom.xml
  ee-9/source-transform/microprofile/pom.xml
  ee-9/source-transform/microprofile/reactive-streams-operators-smallrye/cdi-provider/pom.xml
  microprofile/reactive-streams-operators-smallrye/cdi-provider/pom.xml
  microprofile/reactive-streams-operators-smallrye/cdi-provider/src/main/java/org/wildfly/extension/microprofile/reactive/streams/operators/cdi/ReactiveEngineProvider.java
  microprofile/reactive-streams-operators-smallrye/pom.xml
  pom.xml
Labels: deps-ok

#16350 [WFLY-17365] Failed deployment is not removed from Undertow ServletContainer's deployments map
  undertow/src/main/java/org/wildfly/extension/undertow/deployment/UndertowDeploymentService.java
Labels: deps-ok

#16376 [WFLY-17410]:Upgrade CXF to 3.5.2-jbossorg-4
  pom.xml
Labels: deps-ok

#16377 [WFLY-17410]:Upgrade CXF to 3.5.2-jbossorg-4
  pom.xml
Labels: 27.x

#16374 Add dependabot for GitHub Actions.
  .github/dependabot.yml
Labels: deps-ok

#16381 [WFLY-17256] Drop source transformation for the microprofile-jwt-smal…
  boms/legacy-expansion/pom.xml
  ee-9/source-transform/microprofile/jwt-smallrye/pom.xml
  ee-9/source-transform/microprofile/pom.xml
  ee-9/source-transform/pom.xml
  microprofile/config-smallrye/pom.xml
  microprofile/fault-tolerance-smallrye/pom.xml
  microprofile/galleon-common/pom.xml
  microprofile/health-smallrye/pom.xml
  microprofile/jwt-smallrye/pom.xml
  microprofile/jwt-smallrye/src/main/java/org/wildfly/extension/microprofile/jwt/smallrye/JwtActivationProcessor.java
  microprofile/metrics-smallrye/pom.xml
  microprofile/openapi-smallrye/pom.xml
  microprofile/opentracing-extension/pom.xml
  microprofile/opentracing-smallrye/pom.xml
  microprofile/pom.xml
  microprofile/reactive-messaging-smallrye/pom.xml
  microprofile/reactive-streams-operators-smallrye/pom.xml
  pom.xml
Labels: deps-ok

#16390 [WFLY-17414] Remove use of deprecated PersistentResourceXmlDescriptio…
  bean-validation/src/main/java/org/wildfly/extension/beanvalidation/BeanValidationSubsystemParser.java
  jsf/subsystem/src/main/java/org/jboss/as/jsf/subsystem/JSFExtension.java
  legacy/jacorb/src/main/java/org/jboss/as/jacorb/IORSettingsParser.java
  legacy/jsr77/src/main/java/org/jboss/as/jsr77/subsystem/JSR77ManagementExtension.java
  weld/subsystem/src/main/java/org/jboss/as/weld/WeldSubsystem20Parser.java
  weld/subsystem/src/main/java/org/jboss/as/weld/WeldSubsystem30Parser.java
  weld/subsystem/src/main/java/org/jboss/as/weld/WeldSubsystem40Parser.java
  weld/subsystem/src/main/java/org/jboss/as/weld/WeldSubsystem50Parser.java
Labels: deps-ok

#16389 [WFLY-17413] remove constructor uses deprecated PersistentResourceDef…
  undertow/src/main/java/org/wildfly/extension/undertow/AbstractHandlerDefinition.java
Labels: deps-ok

#16380 [WFLY-17408] Manage the plexus-utils dependency in full WildFly's own…
  pom.xml
Labels: deps-ok

#16367 [WFLY-17338]: Upgrade to JBoss Metadata 15.3.0.FInal
  connector/src/main/java/org/jboss/as/connector/deployers/ds/DsXmlParser.java
  connector/src/main/java/org/jboss/as/connector/deployers/ds/processors/DsXmlDeploymentParsingProcessor.java
  ee-9/source-transform/ee/src/main/java/org/jboss/as/ee/metadata/property/Attachments.java
  ee-9/source-transform/ee/src/main/java/org/jboss/as/ee/metadata/property/DeploymentPropertyResolverProcessor.java
  ee-9/source-transform/ee/src/main/java/org/jboss/as/ee/metadata/property/FunctionalResolverProcessor.java
  ee-9/source-transform/ee/src/main/java/org/jboss/as/ee/metadata/property/PropertyResolverProcessor.java
  ee-9/source-transform/ee/src/main/java/org/jboss/as/ee/metadata/property/SystemPropertyResolverProcessor.java
  ee-9/source-transform/ee/src/main/java/org/jboss/as/ee/subsystem/EeSubsystemAdd.java
  ee/src/main/java/org/jboss/as/ee/metadata/property/Attachments.java
  ee/src/main/java/org/jboss/as/ee/metadata/property/DeploymentPropertyResolverProcessor.java
  ee/src/main/java/org/jboss/as/ee/metadata/property/FunctionalResolverProcessor.java
  ee/src/main/java/org/jboss/as/ee/metadata/property/PropertyResolverProcessor.java
  ee/src/main/java/org/jboss/as/ee/metadata/property/SystemPropertyResolverProcessor.java
  ee/src/main/java/org/jboss/as/ee/subsystem/EeSubsystemAdd.java
  pom.xml
Labels: ready-for-merge, deps-ok

#16375 [WFLY-17328] Further AbstractAddStepHandler deprecation cleanup.
  undertow/src/main/java/org/wildfly/extension/undertow/ServerAdd.java
Labels: ready-for-merge, deps-ok

#16383 [WFLY-17271] Drop source transformation for the web-common module
  boms/legacy-ee/pom.xml
  ee-9/source-transform/pom.xml
  ee-9/source-transform/web-common/pom.xml
  pom.xml
  web-common/pom.xml
  web-common/src/main/java/org/jboss/as/web/common/ExpressionFactoryWrapper.java
  web-common/src/main/java/org/jboss/as/web/common/ServletContextAttribute.java
  web-common/src/main/java/org/jboss/as/web/host/ServletBuilder.java
Labels: ready-for-merge, deps-ok

#16395 WFLY-17422 Eliminate static references to appclient ResourceDefinition instances
  appclient/src/main/java/org/jboss/as/appclient/subsystem/AppClientExtension.java
  appclient/src/main/java/org/jboss/as/appclient/subsystem/AppClientSubsystemResourceDefinition.java
Labels: ready-for-merge, deps-ok

#16370 [WFLY-17407] Update the H2 Web Console Integration doc to use the cor…
  docs/src/main/asciidoc/_developer-guide/H2_Web_Console_Integration.adoc
Labels: deps-ok

#16403 [WFLY-17415] Upgrading WildFly HTTP Client version to 2.0.1.Final
  pom.xml
Labels: deps-ok

#16391 Fix for WFLY-17416, Upgrade to Galleon 5.0.7.Final, Galleon plugins 6.2.2.Final
  pom.xml
Labels: deps-ok

#16388 [WFLY-17263] Drop source transformation for bean-validation subsystem
  bean-validation/pom.xml
  bean-validation/src/main/java/org/jboss/as/ee/beanvalidation/BeanValidationAttachments.java
  bean-validation/src/main/java/org/jboss/as/ee/beanvalidation/BeanValidationFactoryDeployer.java
  bean-validation/src/main/java/org/jboss/as/ee/beanvalidation/BeanValidationFactoryResourceReferenceProcessor.java
  bean-validation/src/main/java/org/jboss/as/ee/beanvalidation/BeanValidationResourceReferenceProcessor.java
  bean-validation/src/main/java/org/jboss/as/ee/beanvalidation/LazyValidatorFactory.java
  bean-validation/src/main/java/org/jboss/as/ee/beanvalidation/ValidatorJndiInjectable.java
  bean-validation/src/main/java/org/jboss/as/ee/beanvalidation/WildFlyProviderResolver.java
  bean-validation/src/test/java/org/jboss/as/ee/beanvalidation/LazyValidatorFactoryTestCase.java
  bean-validation/src/test/java/org/jboss/as/ee/beanvalidation/WildFlyProviderResolverTestCase.java
  bean-validation/src/test/java/org/jboss/as/ee/beanvalidation/testprovider/AnotherValidationProvider.java
  bean-validation/src/test/java/org/jboss/as/ee/beanvalidation/testprovider/MyConfiguration.java
  bean-validation/src/test/java/org/jboss/as/ee/beanvalidation/testprovider/MyValidationProvider.java
  bean-validation/src/test/java/org/jboss/as/ee/beanvalidation/testprovider/MyValidatorFactoryImpl.java
  bean-validation/src/test/java/org/jboss/as/ee/beanvalidation/testprovider/MyValidatorImpl.java
  bean-validation/src/test/resources/META-INF/services/jakarta.validation.spi.ValidationProvider
  boms/legacy-ee/pom.xml
  ee-9/source-transform/bean-validation/pom.xml
  ee-9/source-transform/bean-validation/src/test/resources/META-INF/services/jakarta.validation.spi.ValidationProvider
  ee-9/source-transform/pom.xml
  pom.xml
Labels: deps-ok

#16396 WFLY-17423 Eliminate static references to batch-jberet ResourceDefinition instances
  batch-jberet/src/main/java/org/wildfly/extension/batch/jberet/BatchSubsystemExtension.java
  batch-jberet/src/main/java/org/wildfly/extension/batch/jberet/deployment/BatchJobResourceDefinition.java
Labels: deps-ok

#16400 WFLY-17427 Eliminate static references to EE subsystem ResourceDefinition instances
  ee/src/main/java/org/jboss/as/ee/subsystem/ContextServiceResourceDefinition.java
  ee/src/main/java/org/jboss/as/ee/subsystem/EeExtension.java
  ee/src/main/java/org/jboss/as/ee/subsystem/GlobalDirectoryResourceDefinition.java
  ee/src/main/java/org/jboss/as/ee/subsystem/ManagedThreadFactoryResourceDefinition.java
Labels: ready-for-merge, deps-ok

#16406 WFLY-17436 Eliminate static references to JDR subsystem ResourceDefinition instances
  jdr/src/main/java/org/jboss/as/jdr/JdrReportExtension.java
  jdr/src/main/java/org/jboss/as/jdr/JdrReportSubsystemDefinition.java
Labels: ready-for-merge

#16418 WFLY-17449 Github workflow Unhandled error: TypeError: Cannot read properties of undefined listWorkflowRunArtifacts
  .github/workflows/dep-diff-workflow_run.yml
Labels: ready-for-merge

#16419 WFLY-17450 Upgrade github actions to avoid github action warnings
  .github/workflows/cloud-test-pr-trigger.yml
  .github/workflows/dep-diff-pull_request.yml
  .github/workflows/dep-diff-workflow_run.yml
Labels: ready-for-merge

#16423 [WFLY-17453] Upgrade Jastow to 2.2.5.Final
  pom.xml
Labels: ready-for-merge

#16425 WFLY-17460 Upgrade JGroups to 5.2.11.Final
  pom.xml
Labels: ready-for-merge

#16258 [WFLY-17254] Add a global client interceptors for EJB deployments that will runAs the current security identity to activate any outflow identities
  ee-9/source-transform/ee/src/main/java/org/jboss/as/ee/component/interceptors/InterceptorOrder.java
  ee/src/main/java/org/jboss/as/ee/component/interceptors/InterceptorOrder.java
  ejb3/src/main/java/org/jboss/as/ejb3/security/IdentityEJBClientInterceptor.java
  ejb3/src/main/java/org/jboss/as/ejb3/security/IdentityInterceptor.java
  ejb3/src/main/java/org/jboss/as/ejb3/security/IdentityUtil.java
  ejb3/src/main/java/org/jboss/as/ejb3/subsystem/ClientInterceptorsBindingsProcessor.java
  ejb3/src/main/java/org/jboss/as/ejb3/subsystem/EJB3SubsystemAdd.java
  ejb3/src/main/java/org/jboss/as/ejb3/subsystem/IdentityInterceptorProcessor.java
  testsuite/integration/elytron/src/test/java/org/wildfly/test/integration/elytron/ejb/IdentityPropagationTestCase.java
  testsuite/integration/elytron/src/test/java/org/wildfly/test/integration/elytron/ejb/ejbroles.properties
  testsuite/integration/elytron/src/test/java/org/wildfly/test/integration/elytron/ejb/ejbusers.properties
  testsuite/integration/elytron/src/test/java/org/wildfly/test/integration/elytron/ejb/propagation/local/ComplexServletLocal.java
  testsuite/integration/elytron/src/test/java/org/wildfly/test/integration/elytron/ejb/propagation/local/EntryBeanLocal.java
  testsuite/integration/elytron/src/test/java/org/wildfly/test/integration/elytron/ejb/propagation/local/EntryLocal.java
  testsuite/integration/elytron/src/test/java/org/wildfly/test/integration/elytron/ejb/propagation/local/ManagementBeanLocal.java
  testsuite/integration/elytron/src/test/java/org/wildfly/test/integration/elytron/ejb/propagation/local/ServletOnlyLocal.java
  testsuite/integration/elytron/src/test/java/org/wildfly/test/integration/elytron/ejb/propagation/local/SimpleServletLocal.java
  testsuite/integration/elytron/src/test/java/org/wildfly/test/integration/elytron/ejb/propagation/local/WhoAmIBeanLocal.java
  testsuite/integration/elytron/src/test/java/org/wildfly/test/integration/elytron/ejb/propagation/local/WhoAmILocal.java
  testsuite/integration/elytron/src/test/java/org/wildfly/test/integration/elytron/ejb/propagation/remote/ComplexServletRemote.java
  testsuite/integration/elytron/src/test/java/org/wildfly/test/integration/elytron/ejb/propagation/remote/EntryBeanRemote.java
  testsuite/integration/elytron/src/test/java/org/wildfly/test/integration/elytron/ejb/propagation/remote/EntryRemote.java
  testsuite/integration/elytron/src/test/java/org/wildfly/test/integration/elytron/ejb/propagation/remote/ManagementBeanRemote.java
  testsuite/integration/elytron/src/test/java/org/wildfly/test/integration/elytron/ejb/propagation/remote/ServletOnlyRemote.java
  testsuite/integration/elytron/src/test/java/org/wildfly/test/integration/elytron/ejb/propagation/remote/SimpleServletRemote.java
  testsuite/integration/elytron/src/test/java/org/wildfly/test/integration/elytron/ejb/propagation/remote/WhoAmIBeanRemote.java
  testsuite/integration/elytron/src/test/java/org/wildfly/test/integration/elytron/ejb/propagation/remote/WhoAmIRemote.java
Labels: deps-ok
