Repository wildfly/wildfly, pull requests merged in 2022-05, with the labels that each got.

#15511 [WFLY-14787] Move WildFly Preview to a native jakarta namespace variant of Soteria
  ee-9/pom.xml
Labels: deps-ok, EE9

#15456 [WFLY-16290] DatabaseTimerPersistence loadSqlProperties should be cal…
  ejb3/src/main/java/org/jboss/as/ejb3/timerservice/persistence/database/DatabaseTimerPersistence.java
Labels: deps-ok

#15520 WFLY-16340 Upgrade Infinispan to 13.0.10.Final
  pom.xml
Labels: deps-ok

#15512 [WFLY-15696] Start Faces 4 integration
  ee-9/pom.xml
  ee-9/source-transform/jsf/injection/pom.xml
  ee-9/source-transform/jsf/injection/src/main/java/org/jboss/as/jsf/injection/AnnotationMap.java
  ee-9/source-transform/jsf/pom.xml
  ee-9/source-transform/jsf/subsystem/pom.xml
  ee-9/source-transform/jsf/subsystem/src/main/java/org/jboss/as/jsf/deployment/FacesAnnotation.java
  ee-9/source-transform/pom.xml
  jsf/subsystem/src/main/java/org/jboss/as/jsf/deployment/FacesAnnotation.java
  jsf/subsystem/src/main/java/org/jboss/as/jsf/deployment/JSFAnnotationProcessor.java
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/jsf/duplicateid/DuplicateIDIntegrationTestCase.java
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/jsf/flash/FlashScopeDistributedSessionTestCase.java
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/jsf/managedbean/annotation/AnnotatedManagedBeanTestCase.java
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/jsf/managedbean/managedproperty/ManagedPropertyManagedBeanTestCase.java
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/jsf/managedbean/xml/XmlManagedBeanTestCase.java
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/jsf/resourceResolver/FaceletsResourceResolverTestCase.java
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/jsf/unsupportedwar/FaceletsViewMappingsTestCase.java
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/jsf/unsupportedwar/web.xml
  testsuite/shared/src/main/java/org/jboss/as/test/shared/util/AssumeTestGroupUtil.java
Labels: deps-ok

#15517 [WFLY-16338] Upgrade JBoss Metadata to 15.1.0.Alpha1
  pom.xml
  undertow/src/main/java/org/wildfly/extension/undertow/deployment/WebParsingDeploymentProcessor.java
Labels: deps-changed, EE10

#15474 WFLY-15687 Add support for CDI 4 Build compatible extensions
  ee-9/common/pom.xml
  ee-9/common/src/main/resources/license/preview-feature-pack-common-licenses.xml
  ee-9/common/src/main/resources/modules/system/layers/base/org/jboss/weld/core/main/module.xml
  ee-9/ee-9-api/pom.xml
  ee-9/ee-9-api/src/main/resources/license/preview-feature-pack-ee-9-api-licenses.xml
  ee-9/ee-9-api/src/main/resources/modules/system/layers/base/jakarta/enterprise/api/main/module.xml
  ee-9/pom.xml
  ee-9/source-transform/weld/subsystem/pom.xml
  ee-9/source-transform/weld/subsystem/src/main/resources/META-INF/services/jakarta.enterprise.inject.build.compatible.spi.BuildServices
  weld/subsystem/src/main/java/org/jboss/as/weld/deployment/processors/BeanArchiveProcessor.java
  weld/subsystem/src/main/java/org/jboss/as/weld/deployment/processors/WeldPortableExtensionProcessor.java
Labels: deps-ok, EE10

#15521 WFLY-16340 Upgrade Infinispan to 13.0.10.Final
  clustering/marshalling/protostream/src/main/java/org/wildfly/clustering/marshalling/protostream/AbstractProtoStreamWriter.java
  clustering/marshalling/protostream/src/main/java/org/wildfly/clustering/marshalling/protostream/DefaultProtoStreamReader.java
  clustering/marshalling/protostream/src/main/java/org/wildfly/clustering/marshalling/protostream/ProtoStreamWriter.java
  pom.xml
Labels: 26.x

#15526 [WFLY-16346] Upgrade to MP RSO 3.0-RC1
  testsuite/integration/microprofile-tck/reactive-streams-operators/pom.xml
Labels: deps-ok

#15530 WFLY-16352 Conscious Language in Singleton subsystem
  clustering/singleton/extension/src/main/resources/org/wildfly/extension/clustering/singleton/LocalDescriptions.properties
  clustering/singleton/server/src/main/java/org/wildfly/clustering/singleton/server/SingletonLogger.java
Labels: deps-ok

#15528 [WFLY-16348] Upgrade WildFly Preview to org.jboss.spec.jakarta.el:jbo…
  ee-9/ee-9-api/pom.xml
  ee-9/ee-9-api/src/main/resources/license/preview-feature-pack-ee-9-api-licenses.xml
  ee-9/ee-9-api/src/main/resources/modules/system/layers/base/jakarta/el/api/main/module.xml
  ee-9/pom.xml
  ee-9/source-transform/bean-validation/pom.xml
  ee-9/source-transform/connector/pom.xml
  ee-9/source-transform/ee/pom.xml
  ee-9/source-transform/jsf/injection/pom.xml
  ee-9/source-transform/jsf/subsystem/pom.xml
  ee-9/source-transform/undertow/pom.xml
  ee-9/source-transform/web-common/pom.xml
  ee-9/source-transform/weld/subsystem/pom.xml
Labels: deps-ok

#15525 [WFLY-16341] Remove outdated WFP test excludes from testsuite/integra…
  testsuite/integration/basic/pom.xml
Labels: ready-for-merge, deps-ok

#15527 WFLY-16004 Merge ejb method interface enum in ejb3 subsystem and meta…
  ee-9/source-transform/weld/ejb/pom.xml
  ee-feature-pack/common/src/main/resources/modules/system/layers/base/org/jboss/as/weld/ejb/main/module.xml
  ejb3/src/main/java/org/jboss/as/ejb3/component/EJBBusinessMethod.java
  ejb3/src/main/java/org/jboss/as/ejb3/component/EJBComponent.java
  ejb3/src/main/java/org/jboss/as/ejb3/component/EJBComponentCreateService.java
  ejb3/src/main/java/org/jboss/as/ejb3/component/EJBComponentDescription.java
  ejb3/src/main/java/org/jboss/as/ejb3/component/EJBViewConfiguration.java
  ejb3/src/main/java/org/jboss/as/ejb3/component/EJBViewDescription.java
  ejb3/src/main/java/org/jboss/as/ejb3/component/Ejb2xViewType.java
  ejb3/src/main/java/org/jboss/as/ejb3/component/EjbHomeViewDescription.java
  ejb3/src/main/java/org/jboss/as/ejb3/component/MethodIntf.java
  ejb3/src/main/java/org/jboss/as/ejb3/component/MethodIntfHelper.java
  ejb3/src/main/java/org/jboss/as/ejb3/component/MethodTransactionAttributeKey.java
  ejb3/src/main/java/org/jboss/as/ejb3/component/messagedriven/MessageDrivenComponent.java
  ejb3/src/main/java/org/jboss/as/ejb3/component/messagedriven/MessageDrivenComponentDescription.java
  ejb3/src/main/java/org/jboss/as/ejb3/component/session/SessionBeanComponentCreateService.java
  ejb3/src/main/java/org/jboss/as/ejb3/component/session/SessionBeanComponentDescription.java
  ejb3/src/main/java/org/jboss/as/ejb3/component/singleton/SingletonComponentDescription.java
  ejb3/src/main/java/org/jboss/as/ejb3/component/stateful/StatefulComponentDescription.java
  ejb3/src/main/java/org/jboss/as/ejb3/component/stateless/StatelessComponentDescription.java
  ejb3/src/main/java/org/jboss/as/ejb3/deployment/ApplicableMethodInformation.java
  ejb3/src/main/java/org/jboss/as/ejb3/deployment/processors/DeploymentRepositoryProcessor.java
  ejb3/src/main/java/org/jboss/as/ejb3/deployment/processors/EJBComponentSuspendDeploymentUnitProcessor.java
  ejb3/src/main/java/org/jboss/as/ejb3/deployment/processors/EjbInjectionSource.java
  ejb3/src/main/java/org/jboss/as/ejb3/deployment/processors/EjbJndiBindingsDeploymentUnitProcessor.java
  ejb3/src/main/java/org/jboss/as/ejb3/deployment/processors/SessionBeanHomeProcessor.java
  ejb3/src/main/java/org/jboss/as/ejb3/deployment/processors/StartupAwaitDeploymentUnitProcessor.java
  ejb3/src/main/java/org/jboss/as/ejb3/deployment/processors/merging/AbstractMergingProcessor.java
  ejb3/src/main/java/org/jboss/as/ejb3/deployment/processors/merging/MethodPermissionsMergingProcessor.java
  ejb3/src/main/java/org/jboss/as/ejb3/deployment/processors/merging/TransactionAttributeMergingProcessor.java
  ejb3/src/main/java/org/jboss/as/ejb3/iiop/EjbIIOPTransactionInterceptor.java
  ejb3/src/main/java/org/jboss/as/ejb3/logging/EjbLogger.java
  ejb3/src/main/java/org/jboss/as/ejb3/security/EJBSecurityViewConfigurator.java
  ejb3/src/main/java/org/jboss/as/ejb3/security/EjbJaccConfigurator.java
  ejb3/src/main/java/org/jboss/as/ejb3/security/JaccInterceptor.java
  ejb3/src/main/java/org/jboss/as/ejb3/subsystem/deployment/AbstractEJBComponentRuntimeHandler.java
  ejb3/src/main/java/org/jboss/as/ejb3/timerservice/TimedObjectInvokerImpl.java
  ejb3/src/main/java/org/jboss/as/ejb3/tx/CMTTxInterceptor.java
  ejb3/src/main/java/org/jboss/as/ejb3/tx/LifecycleCMTTxInterceptor.java
  weld/ejb/src/main/java/org/jboss/as/weld/ejb/EjbDescriptorImpl.java
Labels: deps-ok

#15534 [WFLY-16354] Upgrade WildFly Core 19.0.0.Beta9
  ee-9/feature-pack/pom.xml
  pom.xml
Labels: deps-ok

#15531 [WFLY-16354] Upgrade WildFly Core 19.0.0.Beta9
  pom.xml
Labels: deps-ok

#15532 [WFLY-16339] Add testsuite/domain to the ts.ee9 profile
  ee-9/galleon-content-microprofile/src/main/resources/feature_groups/domain-host-excludes.xml
  testsuite/domain/pom.xml
  testsuite/domain/src/test/java/org/jboss/as/test/integration/domain/HostExcludesTestCase.java
  testsuite/domain/src/test/java/org/jboss/as/test/integration/domain/JVMServerPropertiesTestCase.java
  testsuite/domain/src/test/java/org/jboss/as/test/integration/domain/management/cli/DeployAllServerGroupsTestCase.java
  testsuite/domain/src/test/java/org/jboss/as/test/integration/domain/management/cli/DeploySingleServerGroupTestCase.java
  testsuite/domain/src/test/java/org/jboss/as/test/integration/domain/management/cli/DomainDeployWithRuntimeNameTestCase.java
  testsuite/domain/src/test/java/org/jboss/as/test/integration/domain/management/cli/DomainDeploymentOverlayTestCase.java
  testsuite/domain/src/test/java/org/jboss/as/test/integration/domain/management/cli/RolloutPlanTestCase.java
  testsuite/domain/src/test/java/org/jboss/as/test/integration/domain/suites/DeploymentOverlayTestCase.java
  testsuite/domain/src/test/java/org/jboss/as/test/integration/domain/suites/GlobalDirectoryDomainTestCase.java
  testsuite/domain/src/test/java/org/jboss/as/test/integration/domain/suites/ModelPersistenceTestCase.java
  testsuite/domain/src/test/java/org/jboss/as/test/integration/domain/suites/ReadEnvironmentVariablesTestCase.java
  testsuite/domain/src/test/java/org/jboss/as/test/integration/domain/util/EENamespaceTransformer.java
  testsuite/pom.xml
Labels: deps-ok, EE9

#15485 [WFLY-16299] Migrate to Jakarta EE variant of the Elytron subsystem.
  ee-9/common/src/main/resources/modules/system/layers/base/org/wildfly/extension/elytron/main/module.xml
  ee-9/feature-pack/pom.xml
Labels: core-upgrade-needed, EE9

#15133 [WFLY-15598] WebServices UsernameToken profile integration with Elytron
  ee-feature-pack/common/src/main/resources/modules/system/layers/base/org/jboss/as/webservices/server/integration/main/module.xml
  ee-feature-pack/common/src/main/resources/modules/system/layers/base/org/jboss/ws/cxf/jbossws-cxf-server/main/module.xml
  pom.xml
  webservices/server-integration/src/main/java/org/jboss/as/webservices/security/ElytronSecurityDomainContextImpl.java
Labels: ready-for-merge, deps-ok, EE9

#15372 [WFLY-16193] Upgrade netty from 4.1.72 to 4.1.76
  pom.xml
Labels: deps-ok

#15482 [26.x][WFLY-16193] Upgrade netty to 4.1.76
  pom.xml
Labels: 26.x

#15479 [26.x][WFLY-16307] Upgrade io.smallrye.config to 2.10.0
  pom.xml
Labels: 26.x

#15536 [WFLY-16357] hibernate 6 should not be included when -Dskip.preview i…
  jpa/pom.xml
Labels: deps-ok

#15504 [WFLY-16329] Upgrade Apache MyFaces 2.3.9
  pom.xml
Labels: deps-ok

#15505 [26.x][WFLY-16329] Upgrade Apache MyFaces 2.3.9
  pom.xml
Labels: 26.x

#15506 [WFLY-16330] Upgrade Apache Qpid ProtonJ 0.33.10
  pom.xml
Labels: ready-for-merge, deps-ok

#15529 [WFLY-16349] Upgrade to jakarta.* versions of MP reactive messaging
  ee-9/pom.xml
  testsuite/integration/microprofile-tck/reactive-messaging/pom.xml
  testsuite/integration/microprofile-tck/reactive-messaging/src/test/jakarta/java/org/wildfly/test/integration/mp/tck/reactive/messaging/WildFlyDeploymentExceptionTransformer.java
  testsuite/integration/microprofile-tck/reactive-messaging/src/test/javax/java/org/wildfly/test/integration/mp/tck/reactive/messaging/WildFlyDeploymentExceptionTransformer.java
Labels: ready-for-merge, deps-ok

#15537 [WFLY-16358] add missing AttributeDefinition to ReloadRequiredWriteAttributeHandler in modcluster subsystem.
  mod_cluster/extension/src/main/java/org/wildfly/extension/mod_cluster/ProxyConfigurationResourceDefinition.java
  mod_cluster/extension/src/main/java/org/wildfly/extension/mod_cluster/SSLResourceDefinition.java
Labels: ready-for-merge, deps-ok

#15548 [WFLY-16372] Wrong mechanism realm name in host.xml test configurations.
  testsuite/domain/src/test/resources/host-configs/host-master-elytron.xml
  testsuite/domain/src/test/resources/host-configs/host-slave-elytron.xml
  testsuite/integration/manualmode/src/test/resources/legacy-configs/host/eap-7-1-0.xml
  testsuite/integration/manualmode/src/test/resources/legacy-configs/host/eap-7-2-0.xml
  testsuite/integration/manualmode/src/test/resources/legacy-configs/host/eap-7-3-0.xml
  testsuite/integration/manualmode/src/test/resources/legacy-configs/host/eap-7-4-0.xml
  testsuite/mixed-domain/src/test/resources/master-config/host-master-elytron.xml
Labels: deps-ok

#15510 [WFLY-16275] Revert "[WFLY-16274] Temporarily include two modules that come in fro…
  ee-9/common/src/main/resources/modules/system/layers/base/internal/javax/json/api/ee8/main/module.xml
  ee-9/common/src/main/resources/modules/system/layers/base/org/jboss/logmanager/main/module.xml
Labels: deps-ok

#15538 [WFLY-16358] add missing AttributeDefinition to ReloadRequiredWriteAt…
  mod_cluster/extension/src/main/java/org/wildfly/extension/mod_cluster/ProxyConfigurationResourceDefinition.java
  mod_cluster/extension/src/main/java/org/wildfly/extension/mod_cluster/SSLResourceDefinition.java
Labels: 26.x

#15471 [26.x][WFLY-16304] Upgrade Apache james to 0.8.7
  pom.xml
Labels: 26.x

#15470 [WFLY-16304] Upgrade Apache james to 0.8.7
  pom.xml
Labels: deps-ok

#15450 [26.x][WFLY-16222] Upgrade commons-io 2.11.0
  pom.xml
Labels: 26.x

#15545 [WFLY-16369] Remove unused commons-cli version property
  pom.xml
Labels: deps-ok

#15533 [WFLY-15563] added module ref,org.codehaus.woodstox to module org.jbo…
  ee-feature-pack/common/src/main/resources/modules/system/layers/base/org/jboss/as/webservices/server/integration/main/module.xml
Labels: deps-ok

#15539 WFLY-16361 Upgrade to Hibernate ORM 6.0.1.Final and align with dependency updates (Antlr 4.10 + Hibernate Common Annotations 6.0.1.Final)
  ee-9/pom.xml
Labels: deps-ok

#15553 WFLY-16376 Upgrade jberet-core from 2.0.4.Final to 2.1.0.Beta1 in ee-…
  ee-9/pom.xml
Labels: deps-ok, EE10

#15552 [WFLY-16374] Default configuration for domain uses BASIC as a http-authentication-factory mechanism
  testsuite/domain/src/test/resources/host-configs/host-master-elytron.xml
  testsuite/domain/src/test/resources/host-configs/host-slave-elytron.xml
  testsuite/mixed-domain/src/test/resources/master-config/host-master-elytron.xml
Labels: deps-ok

#15549 WFLY-16371 HotRodStore prone to false cache misses
  clustering/infinispan/extension/src/main/java/org/jboss/as/clustering/infinispan/subsystem/remote/HotRodStore.java
  clustering/infinispan/extension/src/main/java/org/jboss/as/clustering/infinispan/subsystem/remote/HotRodStoreServiceConfigurator.java
Labels: deps-ok

#15555 WFLY-16378 Upgrade to Hibernate Search 6.1.5.Final
  ee-9/pom.xml
  testsuite/preview/pom.xml
Labels: deps-ok

#15473 [26.x][WFLY-16305] Upgrade cryptacular to 1.2.5
  pom.xml
Labels: ready-for-merge, 26.x

#15472 [WFLY-16305] Upgrade cryptacular to 1.2.5
  pom.xml
Labels: ready-for-merge, deps-ok

#15489 [26.x][WFLY-16311] Upgrade joda-time 2.10.14
  pom.xml
Labels: ready-for-merge, 26.x

#15486 [WFLY-16311] Upgrade joda-time 2.10.14
  pom.xml
Labels: ready-for-merge, deps-ok

#15503 [26.x][WFLY-16328] Upgrade Apache HttpAsyncClient 4.1.5
  pom.xml
Labels: ready-for-merge, 26.x

#15502 [WFLY-16328] Upgrade Apache HttpAsyncClient 4.1.5
  pom.xml
Labels: ready-for-merge, deps-ok

#15507 [26.x][WFLY-16330] Upgrade Apache Qpid ProtonJ 0.33.10
  pom.xml
Labels: ready-for-merge, 26.x

#15514 [26.x][WFLY-16336] Upgrade istack-commons-runtime 3.0.12
  pom.xml
Labels: ready-for-merge, 26.x

#15513 [WFLY-16336] Upgrade istack-commons-runtime 3.0.12
  pom.xml
Labels: ready-for-merge, deps-ok

#15544 [26.x][WFLY-15998] Change EJBComponent#incomingRunAsIdentity to a ThreadLocal to fix CVE-2022-0866
  ejb3/src/main/java/org/jboss/as/ejb3/component/EJBComponent.java
Labels: ready-for-merge, Blocker, 26.x

#15543 [WFLY-15998] Change EJBComponent#incomingRunAsIdentity to a ThreadLocal to fix CVE-2022-0866
  ejb3/src/main/java/org/jboss/as/ejb3/component/EJBComponent.java
Labels: ready-for-merge, deps-ok

#15554 [WFLY-16375] Upgrade WildFly Core 18.1.1.Final
  pom.xml
Labels: ready-for-merge, 26.x

#15501 [26.x][WFLY-16327] Upgrade Apache Avro to 1.10.2
  pom.xml
Labels: ready-for-merge, 26.x

#15546 WFLY-16368 Reduce heap size of ResourceDescriptor instances
  clustering/common/src/main/java/org/jboss/as/clustering/controller/ResourceDescriptor.java
Labels: deps-ok

#15565 [WFLY-16393] Update Mojarra to 4.0.0-M7
  ee-9/pom.xml
Labels: deps-ok

#15567 [WFLY-16395] Upgrade WildFly Preview's Jakarta to 5.0.0 and move its …
  ee-9/common/pom.xml
  ee-9/common/src/main/resources/license/preview-feature-pack-common-licenses.xml
  ee-9/common/src/main/resources/modules/system/layers/base/org/glassfish/expressly/main/module.xml
  ee-9/common/src/main/resources/modules/system/layers/base/org/glassfish/jakarta/el/main/module.xml
  ee-9/feature-pack/pom.xml
  ee-9/pom.xml
  ee-9/source-transform/bean-validation/pom.xml
  ee-9/source-transform/web-common/pom.xml
Labels: deps-ok

#15535 [WFLY-16355]: Upgrading Artemis to 2.22.0
  ee-9/source-transform/messaging-activemq/subsystem/pom.xml
  messaging-activemq/subsystem/src/main/java/org/wildfly/extension/messaging/activemq/jms/JMSServerControlHandler.java
  messaging-activemq/subsystem/src/test/java/org/wildfly/extension/messaging/activemq/AttributeDefaultsTest.java
  pom.xml
  testsuite/integration/basic/pom.xml
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/messaging/mgmt/NetworkHealthTestCase.java
  testsuite/scripts/pom.xml
Labels: deps-ok

#15566 [WFLY-16396] Zip up the MP Metrics TCK surefire reports for easy down…
  testsuite/integration/microprofile-tck/metrics/assembly.xml
  testsuite/integration/microprofile-tck/metrics/pom.xml
Labels: deps-ok

#15571 [WFLY-16401] Upgrade WildFly Core 19.0.0.Beta10
  pom.xml
Labels: deps-ok

#15551 [WFLY-16177] [primary/secondary] Problematic Language usage deprecati…
  clustering/infinispan/extension/src/main/java/org/jboss/as/clustering/infinispan/InfinispanLogger.java
  clustering/jgroups/extension/src/main/java/org/jboss/as/clustering/jgroups/logging/JGroupsLogger.java
  clustering/jgroups/extension/src/test/java/org/jboss/as/clustering/jgroups/subsystem/JGroupsSubsystemTestCase.java
  mod_cluster/extension/src/main/java/org/wildfly/extension/mod_cluster/ModClusterLogger.java
  testsuite/domain/src/test/java/org/jboss/as/test/integration/domain/LegacyJGroupsProtocolsTestCase.java
  testsuite/mixed-domain/src/test/java/org/jboss/as/test/integration/domain/mixed/DomainHostExcludesTest.java
  testsuite/mixed-domain/src/test/java/org/jboss/as/test/integration/domain/mixed/MixedDomainDeploymentTest.java
  testsuite/mixed-domain/src/test/java/org/jboss/as/test/integration/domain/mixed/MixedDomainTestSupport.java
  testsuite/mixed-domain/src/test/java/org/jboss/as/test/integration/domain/mixed/SimpleMixedDomainTest.java
  testsuite/mixed-domain/src/test/java/org/jboss/as/test/integration/domain/mixed/WildcardReadsTestCase.java
  testsuite/mixed-domain/src/test/java/org/jboss/as/test/integration/domain/mixed/eap740/DomainAdjuster740.java
Labels: deps-ok

#15573 [WFLY-16403] Move WildFly Preview to a native Jakarta namespace varia…
  ee-9/common/pom.xml
  ee-9/common/src/main/resources/license/preview-feature-pack-common-licenses.xml
  ee-9/feature-pack/pom.xml
  ee-9/pom.xml
  ee-9/source-transform/datasources-agroal/pom.xml
  ee-9/source-transform/pom.xml
  ee-feature-pack/common/pom.xml
  ee-feature-pack/common/src/main/resources/license/ee-feature-pack-common-licenses.xml
  ee-feature-pack/common/src/main/resources/modules/system/layers/base/io/agroal/main/module.xml
  ee-feature-pack/common/src/main/resources/modules/system/layers/base/org/wildfly/extension/datasources-agroal/main/module.xml
  ee-feature-pack/pruned/pom.xml
  ee-feature-pack/pruned/src/main/resources/license/ee-feature-pack-legacy-licenses.xml
  pom.xml
  testsuite/domain/src/test/java/org/jboss/as/test/integration/domain/HostExcludesTestCase.java
Labels: deps-changed

#15578 [WFLY-15699] Upgrading JSTL from 2.0.0 to 3.0.0
  ee-9/pom.xml
Labels: deps-ok

#15577 Fix for WFLY-16408, Upgrade to Galleon 5.0.1.Final and Galleon plugins 6.0.0.Alpha2
  pom.xml
Labels: deps-ok

#15574 [WFLY-16396] Don't zip up JUnit reports if test execution was skipped
  testsuite/integration/microprofile-tck/metrics/pom.xml
Labels: deps-ok

#15451 [WFLY-16285] Upgrade commons-lang3 3.12.0
  pom.xml
Labels: deps-ok

#15467 [WFLY-16302] Upgrade Apache cxf to 3.5.2
  pom.xml
Labels: deps-ok

#15515 [WFLY-16337] Sync the WildFly Preview microprofile-tck dependencyMana…
  ee-9/common/pom.xml
  ee-9/common/src/main/resources/license/preview-feature-pack-common-licenses.xml
  ee-9/pom.xml
  ee-9/source-transform/microprofile/health-smallrye/pom.xml
  ee-9/source-transform/microprofile/opentracing-smallrye/pom.xml
  microprofile/health-smallrye/pom.xml
  microprofile/opentracing-smallrye/pom.xml
  pom.xml
  testsuite/integration/microprofile-tck/health/pom.xml
  testsuite/integration/microprofile-tck/opentracing/pom.xml
  testsuite/integration/microprofile-tck/pom.xml
  testsuite/integration/microprofile-tck/reactive-messaging/pom.xml
  testsuite/integration/microprofile-tck/reactive-streams-operators/pom.xml
  testsuite/integration/microprofile-tck/rest-client/pom.xml
  testsuite/integration/microprofile/pom.xml
  testsuite/preview/basic/pom.xml
  testsuite/preview/pom.xml
Labels: deps-ok, EE10

#15579 [WFLY-16410] Upgrade Eclipse Yasson to 1.0.11/3.0.0.RC2
  pom.xml
Labels: deps-ok

#15580 WFLY-16411 Upgrade to Hibernate ORM 6.0.2
  pom.xml
Labels: deps-ok

#15585 WFLY-16409 Upgrade jberet-core Jakarta Batch 2.1 Impl from 2.1.0.Beta…
  pom.xml
Labels: deps-ok, EE10

#15592 [WFLY-16420] Exclude CXF artifacts from being transformed. These tran…
  ee-9/feature-pack/pom.xml
Labels: deps-ok

#15591 [WFLY-16419] Exclude com.github.fge:json-patch from being transformed…
  ee-9/feature-pack/pom.xml
Labels: deps-ok

#15598 WFLY-16240 Component Upgrade of Narayana to 5.12.6.Final
  pom.xml
Labels: deps-ok

#15590 [WFLY-15666] Ignore transforming log4j 1.x. This is set for removal i…
  ee-9/feature-pack/pom.xml
Labels: deps-ok

#15387 [WFLY-16226] Upgrade com.fasterxml.woodstox 6.2.8
  pom.xml
Labels: deps-ok

#15570 Fix for WFLY-16398, Add new tests to cover Galleon update
  pom.xml
  testsuite/galleon/pom.xml
  testsuite/galleon/update/pom.xml
  testsuite/galleon/update/run-test.sh
  testsuite/pom.xml
Labels: deps-ok
