Repository wildfly/wildfly, pull requests merged in 2023-07, with the labels that each got.

#16994 [WFLY-18206] Typo preventing galleon state from being generated
  ee-dist/pom.xml
Labels: deps-ok

#16953 WFLY-18123 Remove use of deprecated VersionedURN subclasses
  bean-validation/src/main/java/org/wildfly/extension/beanvalidation/BeanValidationSubsystemSchema.java
  clustering/ejb/extension/src/main/java/org/wildfly/extension/clustering/ejb/DistributableEjbSubsystemSchema.java
  clustering/infinispan/extension/src/main/java/org/jboss/as/clustering/infinispan/subsystem/InfinispanSubsystemSchema.java
  clustering/jgroups/extension/src/main/java/org/jboss/as/clustering/jgroups/subsystem/JGroupsSubsystemSchema.java
  clustering/singleton/extension/src/main/java/org/wildfly/extension/clustering/singleton/SingletonSubsystemSchema.java
  clustering/singleton/extension/src/main/java/org/wildfly/extension/clustering/singleton/deployment/SingletonDeploymentSchema.java
  clustering/web/extension/src/main/java/org/wildfly/extension/clustering/web/DistributableWebSubsystemSchema.java
  clustering/web/extension/src/main/java/org/wildfly/extension/clustering/web/deployment/DistributableWebDeploymentSchema.java
  ee-security/src/main/java/org/wildfly/extension/eesecurity/EESecuritySubsystemSchema.java
  ejb3/src/main/java/org/jboss/as/ejb3/clustering/ClusteringSchema.java
  ejb3/src/main/java/org/jboss/as/ejb3/timerservice/TimerServiceMetaDataSchema.java
  health/src/main/java/org/wildfly/extension/health/HealthSubsystemSchema.java
  jdr/src/main/java/org/jboss/as/jdr/JdrReportSubsystemSchema.java
  microprofile/fault-tolerance-smallrye/extension/src/main/java/org/wildfly/extension/microprofile/faulttolerance/MicroProfileFaultToleranceSchema.java
  microprofile/jwt-smallrye/src/main/java/org/wildfly/extension/microprofile/jwt/smallrye/MicroProfileJWTSubsystemSchema.java
  microprofile/lra/coordinator/src/main/java/org/wildfly/extension/microprofile/lra/coordinator/MicroProfileLRACoordinatorSubsystemSchema.java
  microprofile/lra/participant/src/main/java/org/wildfly/extension/microprofile/lra/participant/MicroProfileLRAParticipantSubsystemSchema.java
  microprofile/openapi-smallrye/src/main/java/org/wildfly/extension/microprofile/openapi/MicroProfileOpenAPISubsystemSchema.java
  microprofile/reactive-messaging-smallrye/extension/src/main/java/org/wildfly/extension/microprofile/reactive/messaging/MicroProfileReactiveMessagingSubsystemSchema.java
  microprofile/reactive-streams-operators-smallrye/extension/src/main/java/org/wildfly/extension/microprofile/reactive/streams/operators/MicroProfileReactiveStreamsOperatorsSubsystemSchema.java
  microprofile/telemetry-smallrye/extension/src/main/java/org/wildfly/extension/microprofile/telemetry/MicroProfileTelemetrySubsystemSchema.java
  mod_cluster/extension/src/main/java/org/wildfly/extension/mod_cluster/ModClusterSubsystemSchema.java
  observability/micrometer/src/main/java/org/wildfly/extension/micrometer/MicrometerSubsystemSchema.java
  observability/opentelemetry/src/main/java/org/wildfly/extension/opentelemetry/OpenTelemetrySubsystemSchema.java
  pojo/src/main/java/org/jboss/as/pojo/PojoSubsystemSchema.java
  pojo/src/main/java/org/jboss/as/pojo/descriptor/BeanDeploymentSchema.java
  sar/src/main/java/org/jboss/as/service/SarSubsystemSchema.java
  undertow/src/main/java/org/wildfly/extension/undertow/UndertowSubsystemSchema.java
  undertow/src/main/java/org/wildfly/extension/undertow/session/SharedSessionConfigSchema.java
Labels: ready-for-merge, deps-ok, 29.x

#16968 Put org.glassfish:jakarta-faces in the correct spot in licenses.xml
  ee-feature-pack/galleon-shared/src/main/resources/license/licenses.xml
Labels: deps-ok, 29.x

#16990 [WFLY-18204] Upgrade WildFly Core to 21.1.0.Beta2
  pom.xml
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/bc/BouncyCastleModuleTestCase.java
Labels: deps-changed, 29.x

#16991 [WFLY-18176] Check the suspend-state when probing the readiness of the server
  health/src/main/java/org/wildfly/extension/health/ServerProbes.java
  health/src/main/java/org/wildfly/extension/health/ServerProbesService.java
  testsuite/integration/basic/src/test/java/org/wildfly/test/integration/health/HealthHTTPEndpointTestCase.java
Labels: ready-for-merge, deps-ok, 29.x

#16995 [WFLY-18207] Upgrade RESTEasy MicroProfile to 2.1.2.Final.
  pom.xml
Labels: deps-ok, 29.x

#16984 WFLY-18200 Upgrade to Hibernate ORM 6.2.6.Final release
  pom.xml
Labels: deps-ok, 29.x

#16992 [WFLY-18205] Update SmallRye Reactive Messaging to 3.7.0
  pom.xml
Labels: deps-ok, 29.x

#17000 [WFLY-18171] Refresh ClientCompatibilityUnitTestCase with newer client versions.
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/management/api/ClientCompatibilityUnitTestCase.java
Labels: deps-ok

#16934 WFLY-18109 Migrate MicroProfile LRA subsystem tests to use AbstractSubsystemSchemaTest from wildfly-core
  microprofile/lra/coordinator/src/main/java/org/wildfly/extension/microprofile/lra/coordinator/MicroProfileLRACoordinatorExtension.java
  microprofile/lra/coordinator/src/test/java/org/wildfly/extension/microprofile/lra/coordinator/MicroprofileLRACoordinatorSubsystemTestCase.java
  microprofile/lra/coordinator/src/test/resources/org/wildfly/extension/microprofile/lra/coordinator/microprofile-lra-coordinator-1.0.xml
  microprofile/lra/participant/src/main/java/org/wildfly/extension/microprofile/lra/participant/MicroProfileLRAParticipantExtension.java
  microprofile/lra/participant/src/test/java/org/wildfly/extension/microprofile/lra/participant/MicroprofileLRAParticipantSubsystemTestCase.java
  microprofile/lra/participant/src/test/resources/org/wildfly/extension/microprofile/lra/participant/microprofile-lra-participant-1.0.xml
Labels: deps-ok

#16976 [WFLY-16528] JSFDeploymentProcessorTestCase fails with Faces 4
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/jsf/version/JSFDeploymentProcessorTestCase.java
Labels: ready-for-merge, deps-ok

#16999 WFLY-18213 asciidoctor-maven-plugin attribute sourceHighlighter shoul…
  pom.xml
Labels: ready-for-merge, deps-ok

#17004 WFLY-18225 Upgrade smallrye-open-api to 3.4.0
  microprofile/openapi-smallrye/src/main/java/org/wildfly/extension/microprofile/openapi/deployment/OpenAPIModelServiceConfigurator.java
  pom.xml
  testsuite/integration/microprofile-tck/openapi/src/test/java/org/wildfly/extension/microprofile/openapi/tck/DeploymentProcessor.java
Labels: ready-for-merge, deps-ok

#17006 WFLY-18227 Upgrade to Hibernate Search 6.2.0.Final
  pom.xml
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/hibernate/search/backend/elasticsearch/util/ElasticsearchServerSetupObserver.java
Labels: deps-changed

#17009 WFLY-18239 Upgrade Infinispan to 14.0.12.Final
  pom.xml
Labels: ready-for-merge, deps-ok

#17008 [WFLY-18238] Upgrade Byteman to 4.0.21
  pom.xml
Labels: deps-ok

#17010 WFLY-18242 Upgrade Weld to 5.1.1.SP1
  pom.xml
Labels: deps-ok

#16993 WFLY-18150 DistributableTimerService.getTimers() collection may omit timers during concurrent rescheduling process
  clustering/ejb/infinispan/src/main/java/org/wildfly/clustering/ejb/infinispan/timer/InfinispanTimerManager.java
  clustering/ejb/infinispan/src/main/java/org/wildfly/clustering/ejb/infinispan/timer/TimerSerializationContextInitializer.java
  clustering/ejb/infinispan/src/main/resources/org.wildfly.clustering.ejb.infinispan.timer.proto
  ejb3/src/main/java/org/jboss/as/ejb3/timerservice/distributable/DistributableTimerService.java
Labels: deps-ok

#17013 [WFLY-18222] Optimise Kafka layer rule
  galleon-pack/galleon-shared/src/main/resources/layers/standalone/microprofile-reactive-messaging-kafka/layer-spec.xml
Labels: deps-ok

#17011 [WFLY-18243] Upgrade guava to 32.1.1-jre (resolves CVE-2023-2976)
  pom.xml
Labels: deps-changed

#17014 [WFLY-17850] Upgrade nimbus-jose-jwt to 9.31
  pom.xml
Labels: deps-ok

#17003 [WFLY-18223] Upgrade ironjacamar to 3.0.3.Final
  pom.xml
Labels: deps-ok

#16845 [WFLY-16013]: Print more informative failure messages when working with broadcast/discovery group resources
  messaging-activemq/injection/src/main/java/org/wildfly/extension/messaging/activemq/logging/MessagingLogger.java
  messaging-activemq/subsystem/src/main/java/org/wildfly/extension/messaging/activemq/BroadcastGroupAdd.java
  messaging-activemq/subsystem/src/main/java/org/wildfly/extension/messaging/activemq/BroadcastGroupDefinition.java
  messaging-activemq/subsystem/src/main/java/org/wildfly/extension/messaging/activemq/DiscoveryGroupAdd.java
  messaging-activemq/subsystem/src/main/java/org/wildfly/extension/messaging/activemq/DiscoveryGroupDefinition.java
  messaging-activemq/subsystem/src/main/java/org/wildfly/extension/messaging/activemq/shallow/ShallowResourceDefinition.java
  messaging-activemq/subsystem/src/main/java/org/wildfly/extension/messaging/activemq/shallow/TranslatedWriteAttributeHandler.java
  messaging-activemq/subsystem/src/test/java/org/wildfly/extension/messaging/activemq/ShallowResourcesTestCase.java
Labels: deps-ok

#16851 [WFLY-18026]: Configuration applied on ServerAdd shouldn't apply runtime changes on boot for the sub resources.
  messaging-activemq/subsystem/src/main/java/org/wildfly/extension/messaging/activemq/AddressSettingAdd.java
  messaging-activemq/subsystem/src/main/java/org/wildfly/extension/messaging/activemq/AddressSettingRemove.java
  messaging-activemq/subsystem/src/main/java/org/wildfly/extension/messaging/activemq/AddressSettingsWriteHandler.java
  messaging-activemq/subsystem/src/main/java/org/wildfly/extension/messaging/activemq/DivertAdd.java
  messaging-activemq/subsystem/src/main/java/org/wildfly/extension/messaging/activemq/GroupingHandlerAdd.java
  messaging-activemq/subsystem/src/main/java/org/wildfly/extension/messaging/activemq/QueueAdd.java
  messaging-activemq/subsystem/src/main/java/org/wildfly/extension/messaging/activemq/SecurityRoleAdd.java
  messaging-activemq/subsystem/src/main/java/org/wildfly/extension/messaging/activemq/SecurityRoleRemove.java
  messaging-activemq/subsystem/src/main/java/org/wildfly/extension/messaging/activemq/SecuritySettingAdd.java
  messaging-activemq/subsystem/src/main/java/org/wildfly/extension/messaging/activemq/SecuritySettingRemove.java
  messaging-activemq/subsystem/src/main/java/org/wildfly/extension/messaging/activemq/ServerAdd.java
Labels: deps-ok

#17017 [WFLY-18247] Upgrade to SmallRye Reactive Messaging 4.8.0
  pom.xml
Labels: deps-ok

#17021 [WFLY-18252] Add environment variables to get the Hibernate ElasticSe…
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/hibernate/search/backend/elasticsearch/util/ElasticsearchServerSetupObserver.java
Labels: deps-ok

#16916 WFLY-18098 Upgrade JGroups AWS to 3.0.0.Final; expand documentation.
  boms/common-ee/pom.xml
  docs/src/main/asciidoc/_high-availability/jgroups/AWS-Discovery.adoc
  ee-feature-pack/galleon-shared/pom.xml
  ee-feature-pack/galleon-shared/src/main/resources/license/licenses.xml
  ee-feature-pack/galleon-shared/src/main/resources/modules/system/layers/base/com/amazon/aws/core/main/module.xml
  ee-feature-pack/galleon-shared/src/main/resources/modules/system/layers/base/com/amazon/aws/jmespath/main/module.xml
  ee-feature-pack/galleon-shared/src/main/resources/modules/system/layers/base/com/amazon/aws/kms/main/module.xml
  ee-feature-pack/galleon-shared/src/main/resources/modules/system/layers/base/com/amazon/aws/s3/main/module.xml
  ee-feature-pack/galleon-shared/src/main/resources/modules/system/layers/base/com/amazon/ion/main/module.xml
  ee-feature-pack/galleon-shared/src/main/resources/modules/system/layers/base/com/fasterxml/jackson/dataformat/jackson-dataformat-cbor/main/module.xml
  ee-feature-pack/galleon-shared/src/main/resources/modules/system/layers/base/org/jgroups/aws/main/module.xml
  ee-feature-pack/galleon-shared/src/main/resources/modules/system/layers/base/software/amazon/awssdk/s3/main/module.xml
  pom.xml
  testsuite/shared/src/main/java/org/jboss/as/test/shared/LayersTestBase.java
Labels: deps-changed, 29.x

#17023 [WFLY-18256] Update line endings when generating wildfly-ee-feature-pack-licenses.html
  ee-feature-pack/galleon-local/src/main/resources/packages/docs.licenses/pm/wildfly/tasks.xml
  galleon-pack/galleon-local/src/main/resources/packages/docs.licenses/pm/wildfly/tasks.xml
  preview/galleon-local/src/main/resources/packages/docs.licenses/pm/wildfly/tasks.xml
Labels: deps-ok

#17007 WFLY-18179 & WFLY-18230 Avoid redundant no-op runtime steps in undertow and security subsystems
  ee/src/main/java/org/jboss/as/ee/subsystem/GlobalDirectoryResourceDefinition.java
  ee/src/test/java/org/jboss/as/ee/subsystem/EeLegacySubsystemTestCase.java
  ejb3/src/main/java/org/jboss/as/ejb3/subsystem/MdbDeliveryGroupResourceDefinition.java
  elytron-oidc-client/src/main/java/org/wildfly/extension/elytron/oidc/OidcConfigService.java
  elytron-oidc-client/src/main/java/org/wildfly/extension/elytron/oidc/SecureDeploymentDefinition.java
  jaxrs/src/main/java/org/jboss/as/jaxrs/JaxrsExtension.java
  jaxrs/src/main/java/org/jboss/as/jaxrs/JaxrsSubsystemDefinition.java
  legacy/keycloak/src/test/java/org/keycloak/subsystem/adapter/extension/MigrateOperationTestCase.java
  legacy/opentracing-extension/src/test/java/org/wildfly/extension/microprofile/opentracing/MigrateOperationTestCase.java
  microprofile/lra/participant/src/main/java/org/wildfly/extension/microprofile/lra/participant/MicroProfileLRAParticipantSubsystemDefinition.java
  microprofile/metrics-smallrye/src/main/java/org/wildfly/extension/microprofile/metrics/MicroProfileMetricsSubsystemDefinition.java
  microprofile/reactive-messaging-smallrye/extension/src/main/java/org/wildfly/extension/microprofile/reactive/messaging/MicroProfileReactiveMessagingSubsystemDefinition.java
  microprofile/reactive-streams-operators-smallrye/extension/src/main/java/org/wildfly/extension/microprofile/reactive/streams/operators/MicroProfileReactiveStreamsOperatorsSubsystemDefinition.java
  microprofile/telemetry-smallrye/extension/src/main/java/org/wildfly/extension/microprofile/telemetry/MicroProfileTelemetrySubsystemDefinition.java
  security/subsystem/src/main/java/org/jboss/as/security/MappingModuleDefinition.java
  security/subsystem/src/main/java/org/jboss/as/security/elytron/ElytronIntegrationResourceDefinitions.java
  undertow/src/main/java/org/wildfly/extension/undertow/MimeMappingDefinition.java
  undertow/src/main/java/org/wildfly/extension/undertow/WelcomeFileDefinition.java
  undertow/src/main/java/org/wildfly/extension/undertow/filters/FilterDefinitions.java
  undertow/src/main/java/org/wildfly/extension/undertow/handlers/HandlerDefinitions.java
Labels: deps-ok

#17022 WFLY-18254 NullPointerException during rebalance (workaround for JGRP-2702)
  clustering/ee/infinispan/src/main/java/org/wildfly/clustering/ee/infinispan/PrimaryOwnerLocator.java
Labels: deps-ok

#17027 [WFLY-18263] Upgrade WildFly Core to 21.1.0.Final
  pom.xml
Labels: Blocker, deps-ok, 29.x

#16988 [WFLY-17394] Update WildFly Faces docs for Multi JSF Support
  docs/src/main/asciidoc/Getting_Started_Developing_Applications_Guide.adoc
  docs/src/main/asciidoc/Getting_Started_Guide.adoc
  docs/src/main/asciidoc/_admin-guide/Subsystem_configuration.adoc
  docs/src/main/asciidoc/_admin-guide/subsystem-configuration/Jakarta_Faces.adoc
  docs/src/main/asciidoc/_developer-guide/Implicit_module_dependencies_for_deployments.adoc
  docs/src/main/asciidoc/_extras/Developing_Jakarta_Faces_Project_Using_Maven_and_IntelliJ.adoc
  docs/src/main/asciidoc/_extras/Getting_Started_Developing_Applications_Presentation_Demo.adoc
  docs/src/main/asciidoc/_galleon/Galleon_layers.adoc
  docs/src/main/asciidoc/index.adoc
Labels: deps-ok

#17032 [WFLY-18270] Temporarily mark the org.apache.activemq.artemis module …
  ee-feature-pack/galleon-shared/src/main/resources/modules/system/layers/base/org/apache/activemq/artemis/main/module.xml
Labels: deps-ok

#17028 WFLY-18264 Convert TimerAttributeDefinition to ObjectListAttributeDefinition
  ejb3/src/main/java/org/jboss/as/ejb3/logging/EjbLogger.java
  ejb3/src/main/java/org/jboss/as/ejb3/subsystem/deployment/AbstractEJBComponentResourceDefinition.java
  ejb3/src/main/java/org/jboss/as/ejb3/subsystem/deployment/AbstractEJBComponentRuntimeHandler.java
  ejb3/src/main/java/org/jboss/as/ejb3/subsystem/deployment/TimerAttributeDefinition.java
  ejb3/src/main/java/org/jboss/as/ejb3/subsystem/deployment/TimerResourceDefinition.java
Labels: deps-ok, 30.x

#17034 WFLY-18276 Update OidcActivationProcessorTest to use mock DeploymentPhaseContext/DeploymentUnit objects
  elytron-oidc-client/pom.xml
  elytron-oidc-client/src/test/java/org/wildfly/extension/elytron/oidc/OidcActivationProcessorTest.java
Labels: deps-ok

#17038 WFLY-18279 Update HostExcludesTestCase configuration to work with WF30
  testsuite/domain/pom.xml
  testsuite/domain/src/test/java/org/jboss/as/test/integration/domain/HostExcludesTestCase.java
Labels: deps-ok

#17025 [WFLY-18261] Add a SECURITY.md
  SECURITY.md
Labels: deps-ok

#17035 WFLY-18278 Upgrade metainf-services from 1.8 to 1.11
  pom.xml
Labels: deps-ok

#17040 [WFLY-18282] Update the version for the keycloak-saml-adapter-galleon-pack to 22.0.1
  docs/src/main/asciidoc/_elytron/Keycloak_SAML_Integration.adoc
Labels: deps-ok

#17036 WFLY-18277 Upgrade Infinispan to 14.0.13.Final
  clustering/infinispan/extension/src/main/java/org/jboss/as/clustering/infinispan/persistence/hotrod/HotRodStore.java
  pom.xml
Labels: deps-ok

#17039 WFLY-18280 Upgrade mod_cluster to 2.0.2.Final
  pom.xml
Labels: deps-ok
