Repository wildfly/wildfly, pull requests merged in 2023-10, with the labels that each got.

#17237 WFLY-18568 Disable cache operation client events if near cache is disabled
  clustering/web/extension/src/main/java/org/wildfly/extension/clustering/web/session/hotrod/HotRodSessionManagerFactoryServiceConfigurator.java
  clustering/web/hotrod/src/main/java/org/wildfly/clustering/web/hotrod/session/HotRodSessionFactory.java
Labels: deps-ok

#17239 [WFLY-18571] Upgrade Upgrade H2 to 2.2.220
  pom.xml
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/jca/metrics/data-sources/complex-driver.xml
Labels: deps-ok

#17228 [WFLY-16156] Upgrade SmallRye JWT version from 4.2.1 to 4.3.1
  pom.xml
Labels: deps-ok

#17227 [WFLY-11574] reduced permissions for wsse trust test-cases
  testsuite/integration/ws/src/test/java/org/jboss/as/test/integration/ws/wsse/trust/META-INF/permissions.xml
  testsuite/integration/ws/src/test/java/org/jboss/as/test/integration/ws/wsse/trust/WEB-INF/permissions.xml
Labels: deps-ok

#17240 WFLY-18575 Remote caches used by HotRod cache store should never trigger client listeners
  clustering/infinispan/extension/src/main/java/org/jboss/as/clustering/infinispan/persistence/hotrod/HotRodStore.java
Labels: deps-ok

#17238 WFLY-18572 Reduce number of cache operations required for ATTRIBUTE granularity sessions
  clustering/ee/cache/src/main/java/org/wildfly/clustering/ee/cache/function/AbstractFunction.java
  clustering/ee/cache/src/main/java/org/wildfly/clustering/ee/cache/function/CollectionAddFunction.java
  clustering/ee/cache/src/main/java/org/wildfly/clustering/ee/cache/function/CollectionFunction.java
  clustering/ee/cache/src/main/java/org/wildfly/clustering/ee/cache/function/CollectionFunctionMarshaller.java
  clustering/ee/cache/src/main/java/org/wildfly/clustering/ee/cache/function/CollectionOperations.java
  clustering/ee/cache/src/main/java/org/wildfly/clustering/ee/cache/function/CollectionRemoveFunction.java
  clustering/ee/cache/src/main/java/org/wildfly/clustering/ee/cache/function/ConcurrentMapOperations.java
  clustering/ee/cache/src/main/java/org/wildfly/clustering/ee/cache/function/ConcurrentMapPutFunction.java
  clustering/ee/cache/src/main/java/org/wildfly/clustering/ee/cache/function/ConcurrentMapRemoveFunction.java
  clustering/ee/cache/src/main/java/org/wildfly/clustering/ee/cache/function/ConcurrentSetAddFunction.java
  clustering/ee/cache/src/main/java/org/wildfly/clustering/ee/cache/function/ConcurrentSetOperations.java
  clustering/ee/cache/src/main/java/org/wildfly/clustering/ee/cache/function/ConcurrentSetRemoveFunction.java
  clustering/ee/cache/src/main/java/org/wildfly/clustering/ee/cache/function/CopyOnWriteMapOperations.java
  clustering/ee/cache/src/main/java/org/wildfly/clustering/ee/cache/function/CopyOnWriteMapPutFunction.java
  clustering/ee/cache/src/main/java/org/wildfly/clustering/ee/cache/function/CopyOnWriteMapRemoveFunction.java
  clustering/ee/cache/src/main/java/org/wildfly/clustering/ee/cache/function/CopyOnWriteSetAddFunction.java
  clustering/ee/cache/src/main/java/org/wildfly/clustering/ee/cache/function/CopyOnWriteSetOperations.java
  clustering/ee/cache/src/main/java/org/wildfly/clustering/ee/cache/function/CopyOnWriteSetRemoveFunction.java
  clustering/ee/cache/src/main/java/org/wildfly/clustering/ee/cache/function/FunctionSerializationContextInitializer.java
  clustering/ee/cache/src/main/java/org/wildfly/clustering/ee/cache/function/MapComputeFunction.java
  clustering/ee/cache/src/main/java/org/wildfly/clustering/ee/cache/function/MapComputeFunctionMarshaller.java
  clustering/ee/cache/src/main/java/org/wildfly/clustering/ee/cache/function/MapFunction.java
  clustering/ee/cache/src/main/java/org/wildfly/clustering/ee/cache/function/MapOperations.java
  clustering/ee/cache/src/main/java/org/wildfly/clustering/ee/cache/function/MapPutFunction.java
  clustering/ee/cache/src/main/java/org/wildfly/clustering/ee/cache/function/MapRemoveFunction.java
  clustering/ee/cache/src/main/java/org/wildfly/clustering/ee/cache/function/Operations.java
  clustering/ee/cache/src/main/java/org/wildfly/clustering/ee/cache/function/SetAddFunction.java
  clustering/ee/cache/src/main/java/org/wildfly/clustering/ee/cache/function/SetOperations.java
  clustering/ee/cache/src/main/java/org/wildfly/clustering/ee/cache/function/SetRemoveFunction.java
  clustering/ee/cache/src/main/resources/org.wildfly.clustering.ee.cache.function.proto
  clustering/ee/cache/src/test/java/org/wildfly/clustering/ee/cache/function/FunctionTestCase.java
  clustering/ee/hotrod/src/main/java/org/wildfly/clustering/ee/hotrod/RemoteCacheMap.java
  clustering/server/infinispan/src/main/java/org/wildfly/clustering/server/infinispan/group/CacheGroup.java
  clustering/server/infinispan/src/main/java/org/wildfly/clustering/server/infinispan/group/InfinispanAddressMarshaller.java
  clustering/server/infinispan/src/main/java/org/wildfly/clustering/server/infinispan/provider/AddressSetAddFunction.java
  clustering/server/infinispan/src/main/java/org/wildfly/clustering/server/infinispan/provider/AddressSetFunctionMarshaller.java
  clustering/server/infinispan/src/main/java/org/wildfly/clustering/server/infinispan/provider/AddressSetRemoveFunction.java
  clustering/server/infinispan/src/main/java/org/wildfly/clustering/server/infinispan/provider/CacheServiceProviderRegistry.java
  clustering/server/infinispan/src/main/java/org/wildfly/clustering/server/infinispan/provider/ConcurrentAddressSetAddFunction.java
  clustering/server/infinispan/src/main/java/org/wildfly/clustering/server/infinispan/provider/ConcurrentAddressSetRemoveFunction.java
  clustering/server/infinispan/src/main/java/org/wildfly/clustering/server/infinispan/provider/CopyOnWriteAddressSetAddFunction.java
  clustering/server/infinispan/src/main/java/org/wildfly/clustering/server/infinispan/provider/CopyOnWriteAddressSetRemoveFunction.java
  clustering/server/infinispan/src/main/java/org/wildfly/clustering/server/infinispan/provider/ServiceProviderRegistrySerializationContextInitializer.java
  clustering/server/infinispan/src/main/resources/org.wildfly.clustering.server.infinispan.provider.proto
  clustering/server/infinispan/src/test/java/org/wildfly/clustering/server/infinispan/provider/AddressSetFunctionMarshallerTestCase.java
  clustering/web/cache/src/main/java/org/wildfly/clustering/web/cache/session/fine/ConcurrentSessionAttributeMapPutFunction.java
  clustering/web/cache/src/main/java/org/wildfly/clustering/web/cache/session/fine/ConcurrentSessionAttributeMapRemoveFunction.java
  clustering/web/cache/src/main/java/org/wildfly/clustering/web/cache/session/fine/CopyOnWriteSessionAttributeMapPutFunction.java
  clustering/web/cache/src/main/java/org/wildfly/clustering/web/cache/session/fine/CopyOnWriteSessionAttributeMapRemoveFunction.java
  clustering/web/cache/src/main/java/org/wildfly/clustering/web/cache/session/fine/FineImmutableSessionAttributes.java
  clustering/web/cache/src/main/java/org/wildfly/clustering/web/cache/session/fine/FineSessionAttributes.java
  clustering/web/cache/src/main/java/org/wildfly/clustering/web/cache/session/fine/FineSessionAttributesSerializationContextInitializer.java
  clustering/web/cache/src/main/resources/org.wildfly.clustering.web.cache.session.fine.proto
  clustering/web/cache/src/test/java/org/wildfly/clustering/web/cache/session/fine/SessionAttributeMapFunctionMarshallerTestCase.java
  clustering/web/hotrod/src/main/java/org/wildfly/clustering/web/hotrod/session/fine/FineSessionAttributesFactory.java
  clustering/web/infinispan/src/main/java/org/wildfly/clustering/web/infinispan/session/fine/FineSessionAttributesFactory.java
  testsuite/integration/clustering/pom.xml
  testsuite/integration/clustering/src/test/java/org/jboss/as/test/clustering/cluster/web/passivation/SessionPassivationTestCase.java
  testsuite/integration/clustering/src/test/java/org/jboss/as/test/clustering/single/web/passivation/LocalSessionPassivationTestCase.java
  testsuite/integration/clustering/src/test/java/org/jboss/as/test/clustering/single/web/passivation/SessionOperationServlet.java
Labels: deps-ok

#17247 [WFLY-18593] Upgrade Eclipse Yasson to 3.0.3
  pom.xml
Labels: deps-ok

#17243 WFLY-18457 Eliminate new ThreadGroup creation in connector, naming modules
  connector/src/main/java/org/jboss/as/connector/services/resourceadapters/deployment/AbstractResourceAdapterDeploymentService.java
  naming/src/main/java/org/jboss/as/naming/NamingEventCoordinator.java
Labels: ready-for-merge, deps-ok

#17241 [WFLY-18347] Removing PermissionUtils
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/ejb/security/RunAsPrincipalTestCase.java
  testsuite/integration/manualmode/src/test/java/org/jboss/as/test/manualmode/ejb/client/outbound/connection/transaction/preparehalt/TransactionPropagationFailureTestCase.java
  testsuite/integration/multinode/src/test/java/org/jboss/as/test/multinode/ejb/http/EjbOverHttpDescriptorTestCase.java
  testsuite/integration/multinode/src/test/java/org/jboss/as/test/multinode/ejb/http/EjbOverHttpTestCase.java
  testsuite/integration/multinode/src/test/java/org/jboss/as/test/multinode/ejb/http/EjbOverHttpWrongCredentialsTestCase.java
  testsuite/integration/multinode/src/test/java/org/jboss/as/test/multinode/remotecall/RemoteLocalCallProfileTestCase.java
  testsuite/integration/multinode/src/test/java/org/jboss/as/test/multinode/remotecall/RemoteLocalCallTestCase.java
  testsuite/integration/multinode/src/test/java/org/jboss/as/test/multinode/transaction/TransactionInvocationTestCase.java
  testsuite/integration/multinode/src/test/java/org/jboss/as/test/multinode/transaction/async/TransactionPropagationTestCase.java
  testsuite/integration/multinode/src/test/java/org/jboss/as/test/multinode/transaction/nooutbound/TransactionContextRemoteCallTestCase.java
  testsuite/shared/src/main/java/org/jboss/as/test/shared/integration/ejb/security/PermissionUtils.java
Labels: deps-ok

#17242 WFLY-18583 Upgrade to Hibernate Search 6.2.2.Final / WFLY-18579 Upgrade Apache Avro to 1.11.3 / WFLY-18584 Upgrade to Elasticsearch client 8.10.2
  pom.xml
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/hibernate/search/backend/elasticsearch/util/ElasticsearchServerSetupObserver.java
Labels: ready-for-merge, deps-ok

#17246 [WFLY-18590] Upgrade wildfly-transaction-client to 3.0.2.Final
  pom.xml
Labels: deps-ok

#17249 WFLY-18599 Upgrade smallrye-open-api to 3.6.2
  galleon-pack/galleon-shared/src/main/resources/modules/system/layers/base/org/wildfly/extension/microprofile/openapi-smallrye/main/module.xml
  microprofile/openapi-smallrye/src/main/java/org/wildfly/extension/microprofile/openapi/deployment/OpenAPIDocumentProcessor.java
  microprofile/openapi-smallrye/src/main/java/org/wildfly/extension/microprofile/openapi/deployment/OpenAPIModelServiceConfigurator.java
  pom.xml
Labels: deps-ok, 30.x

#17256 WFLY-18603 Upgrade Weld to 5.1.2.Final
  pom.xml
Labels: deps-ok

#17262 WFLY-18609 Hibernate ORM 6.2.12.Final
  pom.xml
Labels: deps-ok

#17106 WFLY-18351 Optimize metadata mapping for distributed @Stateful EJBs
  clustering/ejb/cache/src/main/java/org/wildfly/clustering/ejb/cache/bean/BeanAccessMetaData.java
  clustering/ejb/cache/src/main/java/org/wildfly/clustering/ejb/cache/bean/BeanAccessMetaDataKey.java
  clustering/ejb/cache/src/main/java/org/wildfly/clustering/ejb/cache/bean/BeanMetaDataEntry.java
  clustering/ejb/cache/src/main/java/org/wildfly/clustering/ejb/cache/bean/BeanMetaDataEntryFunction.java
  clustering/ejb/cache/src/main/java/org/wildfly/clustering/ejb/cache/bean/BeanMetaDataKey.java
  clustering/ejb/cache/src/main/java/org/wildfly/clustering/ejb/cache/bean/BeanSerializationContextInitializer.java
  clustering/ejb/cache/src/main/java/org/wildfly/clustering/ejb/cache/bean/CompositeBeanMetaData.java
  clustering/ejb/cache/src/main/java/org/wildfly/clustering/ejb/cache/bean/CompositeImmutableBeanMetaData.java
  clustering/ejb/cache/src/main/java/org/wildfly/clustering/ejb/cache/bean/DefaultBeanMetaData.java
  clustering/ejb/cache/src/main/java/org/wildfly/clustering/ejb/cache/bean/DefaultBeanMetaDataEntry.java
  clustering/ejb/cache/src/main/java/org/wildfly/clustering/ejb/cache/bean/DefaultBeanMetaDataEntryMarshaller.java
  clustering/ejb/cache/src/main/java/org/wildfly/clustering/ejb/cache/bean/DefaultImmutableBeanMetaData.java
  clustering/ejb/cache/src/main/java/org/wildfly/clustering/ejb/cache/bean/ImmortalBeanAccessMetaData.java
  clustering/ejb/cache/src/main/java/org/wildfly/clustering/ejb/cache/bean/ImmortalBeanMetaData.java
  clustering/ejb/cache/src/main/java/org/wildfly/clustering/ejb/cache/bean/ImmutableBeanAccessMetaData.java
  clustering/ejb/cache/src/main/java/org/wildfly/clustering/ejb/cache/bean/ImmutableBeanMetaDataEntry.java
  clustering/ejb/cache/src/main/java/org/wildfly/clustering/ejb/cache/bean/MutableBeanAccessMetaData.java
  clustering/ejb/cache/src/main/java/org/wildfly/clustering/ejb/cache/bean/MutableBeanMetaDataEntry.java
  clustering/ejb/cache/src/main/java/org/wildfly/clustering/ejb/cache/bean/RemappableBeanMetaDataEntry.java
  clustering/ejb/cache/src/main/java/org/wildfly/clustering/ejb/cache/bean/SimpleBeanAccessMetaData.java
  clustering/ejb/cache/src/main/java/org/wildfly/clustering/ejb/cache/bean/SimpleBeanCreationMetaData.java
  clustering/ejb/cache/src/main/resources/org.wildfly.clustering.ejb.cache.bean.proto
  clustering/ejb/cache/src/test/java/org/wildfly/clustering/ejb/cache/bean/AbstractBeanMetaDataEntryTestCase.java
  clustering/ejb/cache/src/test/java/org/wildfly/clustering/ejb/cache/bean/BeanMetaDataEntryFunctionTestCase.java
  clustering/ejb/cache/src/test/java/org/wildfly/clustering/ejb/cache/bean/DefaultBeanMetaDataEntryMarshallerTestCase.java
  clustering/ejb/cache/src/test/java/org/wildfly/clustering/ejb/cache/bean/DefaultBeanMetaDataEntryTestCase.java
  clustering/ejb/cache/src/test/java/org/wildfly/clustering/ejb/cache/bean/MutableBeanMetaDataEntryTestCase.java
  clustering/ejb/cache/src/test/java/org/wildfly/clustering/ejb/cache/bean/SimpleBeanAccessMetaDataMarshallerTestCase.java
  clustering/ejb/cache/src/test/java/org/wildfly/clustering/ejb/cache/bean/SimpleBeanCreationMetaDataMarshallerTestCase.java
  clustering/ejb/infinispan/src/main/java/org/wildfly/clustering/ejb/infinispan/bean/InfinispanBeanCreationMetaDataKey.java
  clustering/ejb/infinispan/src/main/java/org/wildfly/clustering/ejb/infinispan/bean/InfinispanBeanGroupListenerServiceConfigurator.java
  clustering/ejb/infinispan/src/main/java/org/wildfly/clustering/ejb/infinispan/bean/InfinispanBeanManager.java
  clustering/ejb/infinispan/src/main/java/org/wildfly/clustering/ejb/infinispan/bean/InfinispanBeanManagerFactory.java
  clustering/ejb/infinispan/src/main/java/org/wildfly/clustering/ejb/infinispan/bean/InfinispanBeanMetaDataFactory.java
  clustering/ejb/infinispan/src/main/java/org/wildfly/clustering/ejb/infinispan/bean/InfinispanBeanMetaDataFilter.java
  clustering/ejb/infinispan/src/main/java/org/wildfly/clustering/ejb/infinispan/bean/InfinispanBeanMetaDataKey.java
  clustering/ejb/infinispan/src/main/java/org/wildfly/clustering/ejb/infinispan/bean/InfinispanBeanSerializationContextInitializer.java
  clustering/ejb/infinispan/src/main/java/org/wildfly/clustering/ejb/infinispan/bean/SessionIDKeySerializer.java
  clustering/ejb/infinispan/src/main/resources/org.wildfly.clustering.ejb.infinispan.bean.proto
  clustering/ejb/infinispan/src/test/java/org/wildfly/clustering/ejb/infinispan/bean/BeanKeyMapperTestCase.java
  clustering/ejb/infinispan/src/test/java/org/wildfly/clustering/ejb/infinispan/bean/InfinispanBeanAccessMetaDataKeyTestCase.java
  clustering/ejb/infinispan/src/test/java/org/wildfly/clustering/ejb/infinispan/bean/InfinispanBeanMetaDataKeyTestCase.java
  clustering/ejb/spi/src/main/java/org/wildfly/clustering/ejb/bean/BeanMetaData.java
  ee-feature-pack/galleon-shared/src/main/resources/modules/system/layers/base/org/wildfly/clustering/ejb/infinispan/main/module.xml
Labels: deps-ok, 30.x

#17257 WFLY-18575 (Revised) Remote caches used by HotRod cache store should never trigger client listeners
  clustering/infinispan/extension/src/main/java/org/jboss/as/clustering/infinispan/persistence/hotrod/HotRodStore.java
Labels: deps-ok, 30.x

#17260 WFLY-18568 (Revised) Disable cache operation client events if near cache is disabled.
  clustering/ee/hotrod/src/main/java/org/wildfly/clustering/ee/hotrod/HotRodConfiguration.java
  clustering/ee/hotrod/src/main/java/org/wildfly/clustering/ee/hotrod/RemoteCacheComputeMutatorFactory.java
  clustering/ee/hotrod/src/main/java/org/wildfly/clustering/ee/hotrod/RemoteCacheEntryComputeMutator.java
  clustering/ee/hotrod/src/main/java/org/wildfly/clustering/ee/hotrod/RemoteCacheEntryMutator.java
  clustering/ee/hotrod/src/main/java/org/wildfly/clustering/ee/hotrod/RemoteCacheMutatorFactory.java
  clustering/web/extension/src/main/java/org/wildfly/extension/clustering/web/session/hotrod/HotRodSessionManagerFactoryServiceConfigurator.java
  clustering/web/extension/src/main/java/org/wildfly/extension/clustering/web/sso/hotrod/HotRodSSOManagerFactoryServiceConfigurator.java
  clustering/web/hotrod/src/main/java/org/wildfly/clustering/web/hotrod/session/HotRodSessionFactory.java
  clustering/web/hotrod/src/main/java/org/wildfly/clustering/web/hotrod/session/attributes/CoarseSessionAttributesFactory.java
  clustering/web/hotrod/src/main/java/org/wildfly/clustering/web/hotrod/session/attributes/FineSessionAttributesFactory.java
  clustering/web/hotrod/src/main/java/org/wildfly/clustering/web/hotrod/session/metadata/HotRodSessionMetaDataFactory.java
  clustering/web/hotrod/src/main/java/org/wildfly/clustering/web/hotrod/sso/HotRodSSOFactory.java
  clustering/web/hotrod/src/main/java/org/wildfly/clustering/web/hotrod/sso/HotRodSSOManagerFactory.java
  clustering/web/hotrod/src/main/java/org/wildfly/clustering/web/hotrod/sso/HotRodSSOManagerFactoryConfiguration.java
  clustering/web/hotrod/src/main/java/org/wildfly/clustering/web/hotrod/sso/coarse/CoarseSessionsFactory.java
Labels: deps-ok, 30.x

#17265 [WFLY-18613] Upgrade WildFly Core to 22.0.0.Final
  picketlink/src/test/java/org/wildfly/extension/picketlink/subsystem/InvalidAttributeManagerDeclarationUnitTestCase.java
  picketlink/src/test/java/org/wildfly/extension/picketlink/subsystem/RoleGeneratorDeclarationUnitTestCase.java
  pom.xml
Labels: deps-ok

#17197 [WFLY-18522] handle BootOperationFailedException if KernelServicesBui…
  picketlink/src/test/java/org/wildfly/extension/picketlink/subsystem/InvalidAttributeManagerDeclarationUnitTestCase.java
  picketlink/src/test/java/org/wildfly/extension/picketlink/subsystem/RoleGeneratorDeclarationUnitTestCase.java
Labels: core-upgrade-needed, deps-ok

#17258 [WFLY-18602] Add security manager testing support for script tests
  ee-feature-pack/galleon-shared/src/main/resources/content/bin/appclient.bat
  ee-feature-pack/galleon-shared/src/main/resources/content/bin/appclient.sh
  testsuite/scripts/src/test/java/org/wildfly/test/scripts/AppClientScriptTestCase.java
  testsuite/scripts/src/test/java/org/wildfly/test/scripts/ScriptProcess.java
  testsuite/scripts/src/test/java/org/wildfly/test/scripts/ScriptTestCase.java
Labels: deps-ok

#17234 WFLY-18557 appclient -secmgr should be allowed under Java 21
  ee-feature-pack/galleon-shared/src/main/resources/content/bin/appclient.bat
  ee-feature-pack/galleon-shared/src/main/resources/content/bin/appclient.sh
Labels: deps-ok, 30.x

#17267 WFLY-18616 SEVERE log noise when deplying a JSF application - JSF1030…
  jsf/injection/src/main/resources/META-INF/services/com.sun.faces.spi.injectionprovider
Labels: deps-ok

#17263 [WFLY-18590] SimpleTimerMDBTestCase: change waiting time
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/ejb/mdb/timerservice/SimpleTimerMDBTestCase.java
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/ejb/mdb/timerservice/TimedObjectTimerServiceMDB.java
Labels: deps-ok

#17269 [WFLY-18617] Clean out spurious copyright/license headers
  bean-validation/src/test/resources/META-INF/services/jakarta.validation.spi.ValidationProvider
  clustering/marshalling/protostream/src/test/resources/META-INF/services/org.infinispan.protostream.SerializationContextInitializer
  ee-feature-pack/galleon-shared/src/main/resources/content/docs/licenses/bsd 2-clause simplified license.html
  ee-feature-pack/galleon-shared/src/main/resources/content/docs/licenses/bsd 3-clause new or revised license.html
  ee-feature-pack/galleon-shared/src/main/resources/content/docs/licenses/creative commons attribution 2.5.html
  ee-feature-pack/galleon-shared/src/main/resources/content/docs/licenses/fsf all permissive license.html
  ee-feature-pack/galleon-shared/src/main/resources/content/docs/licenses/indiana university extreme lab software license 1.1.1.html
  ee-feature-pack/galleon-shared/src/main/resources/content/docs/licenses/mit-0.html
  ee-feature-pack/galleon-shared/src/main/resources/content/docs/licenses/mozilla public license 2.0.html
  jpa/eclipselink/src/main/resources/META-INF/services/org.jipijapa.plugin.spi.PersistenceProviderAdaptor
  jpa/hibernate6/src/main/resources/META-INF/services/org.hibernate.service.spi.ServiceContributor
  jpa/hibernate6/src/main/resources/META-INF/services/org.jipijapa.plugin.spi.PersistenceProviderAdaptor
  jpa/hibernatesearch/src/main/resources/META-INF/services/org.jipijapa.plugin.spi.PersistenceProviderIntegratorAdaptor
  jsf/injection/src/main/resources/META-INF/services/com.sun.faces.spi.annotationprovider
  messaging-activemq/subsystem/src/main/resources/META-INF/services/org.apache.activemq.artemis.service.extensions.transactions.TransactionManagerLocator
  messaging-activemq/subsystem/src/main/resources/META-INF/services/org.apache.activemq.artemis.service.extensions.xa.ActiveMQXAResourceWrapperFactory
  messaging-activemq/subsystem/src/main/resources/META-INF/services/org.jboss.as.cli.CommandHandlerProvider
  weld/bean-validation/src/main/resources/META-INF/services/org.jboss.as.weld.spi.DeploymentUnitProcessorProvider
  weld/ejb/src/main/resources/META-INF/services/org.jboss.as.weld.spi.BeanDeploymentArchiveServicesProvider
  weld/ejb/src/main/resources/META-INF/services/org.jboss.as.weld.spi.ComponentDescriptionProcessor
  weld/ejb/src/main/resources/META-INF/services/org.jboss.as.weld.spi.ComponentIntegrator
  weld/ejb/src/main/resources/META-INF/services/org.jboss.as.weld.spi.ComponentInterceptorSupport
  weld/ejb/src/main/resources/META-INF/services/org.jboss.as.weld.spi.ComponentSupport
  weld/ejb/src/main/resources/META-INF/services/org.jboss.as.weld.spi.ImplicitBeanArchiveDetector
  weld/ejb/src/main/resources/META-INF/services/org.jboss.as.weld.spi.ModuleServicesProvider
  weld/jpa/src/main/resources/META-INF/services/org.jboss.as.weld.spi.DeploymentUnitDependenciesProvider
  weld/jpa/src/main/resources/META-INF/services/org.jboss.as.weld.spi.ModuleServicesProvider
  weld/subsystem/src/main/resources/META-INF/services/jakarta.enterprise.inject.build.compatible.spi.BuildServices
  weld/subsystem/src/main/resources/META-INF/services/jakarta.enterprise.inject.spi.CDIProvider
  weld/subsystem/src/main/resources/META-INF/services/org.jboss.as.controller.Extension
  weld/subsystem/src/main/resources/META-INF/services/org.jboss.as.controller.transform.ExtensionTransformerRegistration
  weld/subsystem/src/main/resources/META-INF/services/org.jboss.as.weld.spi.BootstrapDependencyInstaller
  weld/subsystem/src/main/resources/META-INF/services/org.jboss.as.weld.spi.ComponentSupport
  weld/subsystem/src/main/resources/META-INF/services/org.jboss.as.weld.spi.ImplicitBeanArchiveDetector
  weld/subsystem/src/main/resources/META-INF/services/org.jboss.as.weld.spi.ModuleServicesProvider
  weld/transactions/src/main/resources/META-INF/services/org.jboss.as.weld.spi.BootstrapDependencyInstaller
  weld/webservices/src/main/resources/META-INF/services/org.jboss.as.weld.spi.ComponentSupport
  weld/webservices/src/main/resources/META-INF/services/org.jboss.as.weld.spi.ModuleServicesProvider
  weld/webservices/src/main/resources/META-INF/services/org.jboss.as.weld.spi.ResourceInjectionResolver
Labels: deps-ok, 30.x

#17268 [WFLY-18593] Revert Yasson back to 3.0.2. The version 3.0.3 contains …
  pom.xml
Labels: Blocker, deps-ok, 30.x

#17274 Allow for 60 minutes for the build-only jobs to complete. When downlo…
  .github/workflows/build-only.yml
Labels: deps-ok

#17275 [WFLY-18622] Add a PropertyPermission to the SimpleTimerMDBTestCase d…
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/ejb/mdb/timerservice/SimpleTimerMDBTestCase.java
Labels: deps-ok

#17273 [WFLY-18619] Add missing search for WARNING to Windows package availa…
  ee-feature-pack/galleon-shared/src/main/resources/content/bin/common.bat
  ee-feature-pack/galleon-shared/src/main/resources/content/bin/common.ps1
Labels: deps-ok, 30.x

#17277 WFLY-18625 CVE-2023-44487 Upgrade Netty to 4.1.100.Final
  pom.xml
Labels: Blocker, deps-ok, 30.x

#17279 [WFLY-18627] Upgrade to Vert.x 4.4.6
  pom.xml
Labels: deps-ok

#17280 WFLY-18629 Upgrade to Hibernate ORM 6.2.13.Final
  pom.xml
Labels: deps-ok

#17276 WFLY-18624 Remove obsolete Namespace class from Undertow subsystem
  undertow/src/main/java/org/wildfly/extension/undertow/Namespace.java
Labels: deps-ok

#17285 WFLY-18635 Drop support for scattered cache
  clustering/infinispan/extension/src/main/java/org/jboss/as/clustering/infinispan/subsystem/ScatteredCacheServiceConfigurator.java
Labels: deps-ok, 30.x

#17291 [WFLY-18643]:Upgrade jbossws-cxf to 7.0.0.Final;This upgrade includes…
  pom.xml
Labels: deps-changed

#17286 WFLY-18638 The `telnetServer` is null during test randomly.
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/ejb/mdb/dynamic/adapter/TelnetResourceAdapter.java
Labels: deps-ok

#17297 Fix for WFLY-18648, Upgrade Galleon to 5.2.1.Final and Galleon plugins to 6.5.0.Final
  pom.xml
Labels: deps-ok

#17315 [WFLY-18668]: WARN message from Artemis when starting WildFly.
  messaging-activemq/subsystem/src/main/java/org/wildfly/extension/messaging/activemq/AddressSettingAdd.java
Labels: deps-ok

#17318 [WFLY-18556] Enable DataSourceDefinitionJPATestCase
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/jpa/datasourcedefinition/DataSourceDefinitionJPATestCase.java
Labels: deps-ok

#17319 [WFLY-18675] Upgrade WildFly Core to 22.0.1.Final
  pom.xml
Labels: Blocker, deps-ok, 30.x

#17295 [WFLY-18644] Removing xerces from distribution
  boms/common-ee/pom.xml
  ee-feature-pack/galleon-shared/pom.xml
  ee-feature-pack/galleon-shared/src/main/resources/license/licenses.xml
  ee-feature-pack/galleon-shared/src/main/resources/modules/system/layers/base/org/apache/xerces/main/module.xml
  pom.xml
  testsuite/integration/basic/pom.xml
  webservices/tests-integration/pom.xml
Labels: deps-changed

#17334 WFLY-18683 Ensure JDBC key/entry iteration happens on a single thread.
  clustering/infinispan/extension/src/main/java/org/jboss/as/clustering/infinispan/persistence/jdbc/JDBCStore.java
  clustering/infinispan/extension/src/main/java/org/jboss/as/clustering/infinispan/persistence/jdbc/JDBCStoreConfiguration.java
  clustering/infinispan/extension/src/main/java/org/jboss/as/clustering/infinispan/persistence/jdbc/JDBCStoreConfigurationBuilder.java
  clustering/infinispan/extension/src/main/java/org/jboss/as/clustering/infinispan/subsystem/JDBCStoreServiceConfigurator.java
Labels: deps-ok

#17321 [WFLY-16887] - Modify description in jaxrs of subsystem
  jaxrs/src/main/resources/org/jboss/as/jaxrs/LocalDescriptions.properties
Labels: deps-ok

#17292 WFLY-18639 Improve resiliency of reflection based-externalizers and marshallers
  clustering/marshalling/protostream/src/main/java/org/wildfly/clustering/marshalling/protostream/reflect/Reflect.java
  clustering/marshalling/spi/src/main/java/org/wildfly/clustering/marshalling/spi/DecoratorExternalizer.java
Labels: deps-ok

#17328 [WFLY-18645] Upgrade openjdk-orb to 10.0.0.Final
  pom.xml
Labels: deps-changed

#17300 [WFLY-18673] GitHub Actions Run Reductions
  .github/workflows/build-manual.yml
  .github/workflows/build-only.yml
  .github/workflows/cloud-test-pr-trigger.yml
  .github/workflows/dep-diff-pull_request.yml
  .github/workflows/jdk-jre-build.yml
Labels: deps-ok

#17329 [WFLY-16929] ForwardedHandlerTestCase fails with security manager
  testsuite/integration/web/src/test/java/org/jboss/as/test/integration/web/handlers/ForwardedHandlerTestCase.java
Labels: deps-ok

#17342 [WFLY-18651] Remove obsolete pre-Galleon WildFly build and provisioning tools. Remove unused LegacySubsystemConfigurationUtil class
  pom.xml
  testsuite/mixed-domain/pom.xml
  testsuite/mixed-domain/src/test/java/org/jboss/as/test/integration/domain/mixed/LegacySubsystemConfigurationUtil.java
Labels: deps-ok

#17335 [WFLY-18685]:Upgrade santuario to 3.0.3
  pom.xml
Labels: deps-ok

#17336 [WFLY-18685]:Upgrade santuario to 3.0.3
  pom.xml
Labels: 30.x

#17301 [WFLY-18653] i18n of exception messages in ApplicationClientParsingDeploymentProcessor
  appclient/src/main/java/org/jboss/as/appclient/deployment/ApplicationClientParsingDeploymentProcessor.java
Labels: deps-ok

#17296 [WFLY-18646] Upgrading Jastow to 2.2.7.Final and Eclipse ECJ Compiler to 3.32.0
  pom.xml
Labels: deps-ok

#17304 [WFLY-18657] Fix i18n of exception messages in ee
  ee/src/main/java/org/jboss/as/ee/component/deployers/MessageDestinationInjectionSource.java
  ee/src/main/java/org/jboss/as/ee/concurrent/service/ManagedExecutorHungTasksPeriodicTerminationService.java
  ee/src/main/java/org/jboss/as/ee/logging/EeLogger.java
  ee/src/main/java/org/jboss/as/ee/metadata/EJBClientDescriptorMetaData.java
Labels: deps-ok

#17337 [WFLY-18677] Disable testsuite/layers[-expansion] provisioning if -DskipTests is set
  testsuite/layers-expansion/pom.xml
  testsuite/layers/pom.xml
Labels: deps-ok

#17314 [WFLY-18667] Fix i18n of exception messages in xts
  xts/src/main/java/org/jboss/as/xts/XTSHandlerDeploymentProcessor.java
  xts/src/main/java/org/jboss/as/xts/jandex/BridgeType.java
  xts/src/main/java/org/jboss/as/xts/logging/XtsAsLogger.java
Labels: deps-ok

#17305 [WFLY-18658] Fix i18n of exception messages in ejb3
  ejb3/src/main/java/org/jboss/as/ejb3/component/interceptors/EjbExceptionTransformingInterceptorFactories.java
  ejb3/src/main/java/org/jboss/as/ejb3/iiop/EjbCorbaServant.java
  ejb3/src/main/java/org/jboss/as/ejb3/inflow/MessageEndpointInvocationHandler.java
  ejb3/src/main/java/org/jboss/as/ejb3/logging/EjbLogger.java
  ejb3/src/main/java/org/jboss/as/ejb3/remote/LocalTransportProvider.java
Labels: deps-ok

#17313 [WFLY-18666] Fix i18n of exception messages in weld
  weld/common/src/main/java/org/jboss/as/weld/logging/WeldLogger.java
  weld/common/src/main/java/org/jboss/as/weld/util/ServiceLoaders.java
  weld/subsystem/src/main/java/org/jboss/as/weld/deployment/WeldEEModuleDescriptor.java
  weld/subsystem/src/main/java/org/jboss/as/weld/deployment/processors/UrlScanner.java
  weld/subsystem/src/main/java/org/jboss/as/weld/discovery/WeldClassFileInfo.java
  weld/subsystem/src/main/java/org/jboss/as/weld/services/bootstrap/ProxyServicesImpl.java
Labels: deps-ok

#17302 [WFLY-18654] i18n of exception message in WildFlyJobXmlResolver
  batch-jberet/src/main/java/org/wildfly/extension/batch/jberet/_private/BatchLogger.java
  batch-jberet/src/main/java/org/wildfly/extension/batch/jberet/deployment/WildFlyJobXmlResolver.java
Labels: deps-ok

#17303 [WFLY-18656] i18n of exception messages in connector.
  connector/src/main/java/org/jboss/as/connector/ConnectorServices.java
  connector/src/main/java/org/jboss/as/connector/logging/ConnectorLogger.java
  connector/src/main/java/org/jboss/as/connector/security/ElytronCallbackHandler.java
  connector/src/main/java/org/jboss/as/connector/subsystems/jca/JcaExtension.java
Labels: deps-ok

#17306 [WFLY-18659] Fix i18n of exception messages in jpa
  jpa/hibernate6/src/main/java/org/jboss/as/jpa/hibernate/JpaLogger.java
  jpa/hibernate6/src/main/java/org/jboss/as/jpa/hibernate/VirtualFileInputStreamAccess.java
  jpa/subsystem/src/main/java/org/jboss/as/jpa/container/EntityManagerUnwrappedTargetInvocationHandler.java
  jpa/subsystem/src/main/java/org/jboss/as/jpa/messages/JpaLogger.java
Labels: deps-ok

#17309 [WFLY-18662] Fix i18n of exception messages in pojo
  pojo/src/main/java/org/jboss/as/pojo/descriptor/AbstractConfigVisitorNode.java
  pojo/src/main/java/org/jboss/as/pojo/logging/PojoLogger.java
Labels: deps-ok

#17312 [WFLY-18665] Fix i18n of exception messages in webservices
  webservices/server-integration/src/main/java/org/jboss/as/webservices/logging/WSLogger.java
  webservices/server-integration/src/main/java/org/jboss/as/webservices/security/ElytronSecurityDomainContextImpl.java
Labels: deps-ok

#17308 [WFLY-18661] Fix i18n of exception messages in naming
  naming/src/main/java/org/jboss/as/naming/logging/NamingLogger.java
  naming/src/main/java/org/jboss/as/naming/remote/RemoteNamingServerService.java
Labels: deps-ok

#17333 [WFLY-18682] Upgrading WildFly Http Client to 2.0.5.Final
  ee-feature-pack/galleon-shared/src/main/resources/modules/system/layers/base/org/wildfly/http-client/naming/main/module.xml
  pom.xml
Labels: deps-ok

#17339 WFLY-18688 Update JBeret to 2.1.3.Final
  pom.xml
Labels: deps-ok

#17261 [WFLY-18605][WFLY-18606] reevaluated test excludes pro ts.preview and ts.bootable…
  testsuite/integration/elytron/pom.xml
  testsuite/integration/elytron/src/test/java/org/wildfly/test/integration/elytron/jaspi/ConfiguredAdHocJaspiTestCase.java
  testsuite/integration/elytron/src/test/java/org/wildfly/test/integration/elytron/jaspi/ConfiguredJaspiTestCase.java
  testsuite/integration/elytron/src/test/java/org/wildfly/test/integration/elytron/jaspi/ConfiguredSelfValidatingJaspiTestCase.java
  testsuite/integration/web/pom.xml
Labels: deps-ok

#17341 [WFLY-18690] Upgrade the Jakarta XML Binding API to 4.0.1, the implem…
  pom.xml
Labels: ready-for-merge, deps-ok

#17350 [WFLY-18702] Ensure the wildfly-preview feature pack's jaxrs-server layer can provision MicroProfile REST Client
  ee-feature-pack/galleon-local/src/main/resources/layers/standalone/jaxrs-server/layer-spec.xml
  galleon-pack/galleon-local/src/main/resources/layers/standalone/jaxrs-server/layer-spec.xml
  preview/galleon-local/src/main/resources/layers/standalone/jaxrs-server/layer-spec.xml
  testsuite/integration/microprofile-tck/rest-client/pom.xml
  testsuite/integration/microprofile/pom.xml
  testsuite/integration/pom.xml
Labels: 30.x

#17345 [WFLY-18697] Switch ejb subsystem test dep from groovy-all to groovy
  boms/standard-test/pom.xml
  ejb3/pom.xml
  pom.xml
Labels: deps-ok

#17354 [WFLY-18704]: Upgrade Apache Artemis to 2.31.2
  pom.xml
Labels: deps-ok
