Repository wildfly/wildfly, pull requests merged in 2023-08, with the labels that each got.

#17045 WFLY-18291 Upgrade SmallRye Fault Tolerance to 6.2.6
  pom.xml
Labels: deps-ok

#17052 WFLY-18299 Upgrade smallrye-open-api to 3.5.0
  pom.xml
Labels: deps-ok

#17046 [WFLY-18293] Upgrade HAL to 3.6.12.Final
  pom.xml
Labels: deps-ok

#17055 WFLY-18192 Upgrade JGroups to 5.2.17.Final
  pom.xml
Labels: deps-ok

#17056 Fix incorrect <dependencies> element placement in licenses.xml and fix indentation.
  ee-feature-pack/galleon-shared/src/main/resources/license/licenses.xml
Labels: deps-ok

#17058 Drop out of date "in progress" note from the docs.
  docs/src/main/asciidoc/index.adoc
Labels: deps-ok

#17042 [WFLY-18258] AssumeTestGroupUtil should log exception if docker is unavailable and not assume false is ok
  testsuite/shared/src/main/java/org/jboss/as/test/shared/util/AssumeTestGroupUtil.java
Labels: deps-ok

#17043 [WFLY-18289] Correct GAV handling
  appclient/pom.xml
  boms/standard-expansion/pom.xml
  dist/pom.xml
  legacy/opentracing-extension/pom.xml
  microprofile/config-smallrye/pom.xml
  microprofile/health-smallrye/pom.xml
  microprofile/lra/coordinator/pom.xml
  microprofile/lra/participant/pom.xml
  microprofile/metrics-smallrye/pom.xml
  microprofile/reactive-messaging-smallrye/extension/pom.xml
  microprofile/reactive-streams-operators-smallrye/extension/pom.xml
  microprofile/telemetry-smallrye/extension/pom.xml
  microprofile/telemetry-smallrye/pom.xml
  observability/micrometer-api/pom.xml
  observability/micrometer/pom.xml
  observability/opentelemetry-api/pom.xml
  observability/opentelemetry/pom.xml
  observability/pom.xml
  pom.xml
  testsuite/integration/microprofile-tck/lra/pom.xml
  testsuite/integration/microprofile-tck/pom.xml
  testsuite/integration/microprofile-tck/rest-client/pom.xml
  testsuite/integration/microprofile/pom.xml
  testsuite/layers-expansion/pom.xml
  testsuite/pom.xml
Labels: deps-ok

#17031 WFLY-18268 MicroProfile LRA participant layer must depend on the MicroProfile Config
  galleon-pack/galleon-shared/src/main/resources/modules/system/layers/base/org/jboss/narayana/rts/lra-participant/main/module.xml
  testsuite/integration/microprofile-tck/lra/pom.xml
Labels: deps-ok

#17062 Mark FaultToleranceMicrometerIntegrationTestCase as intermittently failing effectively @Ignore-ing it.
  testsuite/integration/microprofile/src/test/java/org/wildfly/test/integration/microprofile/faulttolerance/micrometer/FaultToleranceMicrometerIntegrationTestCase.java
Labels: ready-for-merge, deps-ok

#17050 [WFLY-18296] Remove the org.jboss.jts dependency on jdk.console
  ee-feature-pack/galleon-shared/src/main/resources/modules/system/layers/base/org/jboss/jts/main/module.xml
Labels: deps-ok

#17026 WFLY-18262 Upgrade Narayana to 7.0.0.Final
  pom.xml
Labels: deps-changed

#17070 [WFLY-18311] Eliminate Hibernate Validator dependency on legacy Xerces
  ee-feature-pack/galleon-shared/src/main/resources/modules/system/layers/base/org/hibernate/validator/main/module.xml
Labels: deps-ok

#17069 WFLY-18322 Upgrade JGroups to 5.2.18.Final
  pom.xml
Labels: deps-ok

#17071 [WFLY-18301] Upgrade okio to 3.4.0
  pom.xml
Labels: deps-ok

#17066 [WFLY-18319] Upgrade to SmallRye Config 3.3.3
  pom.xml
Labels: deps-ok

#17063 WFLY-18312: JCA: fix ResourceAdaptersSubsystemAdd file name typo
  connector/src/main/java/org/jboss/as/connector/subsystems/resourceadapters/ResourceAdaptersSubsystemAdd.java
Labels: deps-ok

#17068 [WFLY-18320] Upgrade to SmallRye Reactive Messaging 4.9.0
  pom.xml
Labels: deps-ok

#17054 [WFLY-18194] JCA: fix datasource security xsd schema
  connector/src/main/resources/schema/wildfly-datasources_5_0.xsd
  connector/src/main/resources/schema/wildfly-datasources_6_0.xsd
  connector/src/main/resources/schema/wildfly-datasources_7_0.xsd
Labels: deps-ok

#17015 [WFLY-16168] Remove the Apache Xerces module dependency from the REST…
  ee-feature-pack/galleon-shared/src/main/resources/modules/system/layers/base/org/jboss/resteasy/resteasy-jaxb-provider/main/module.xml
Labels: deps-ok

#17041 [WFLY-18171] Refresh ClientCompatibilityUnitTestCase for WildFly 29.0.0.Final
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/management/api/ClientCompatibilityUnitTestCase.java
Labels: deps-ok

#17049 [WFLY-16683][WFLY-17064] Clean up references to EE 9; switch WFP prof…
  pom.xml
  preview/build/pom.xml
  preview/dist/pom.xml
  preview/galleon-local/pom.xml
  preview/pom.xml
  testsuite/domain/pom.xml
  testsuite/integration/basic/pom.xml
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/hibernate/Hibernate2LCacheStatsTestCase.java
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/hibernate/Hibernate4NativeAPIProviderTestCase.java
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/hibernate/HibernateNativeAPITransactionTestCase.java
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/hibernate/envers/Hibernate4NativeAPIEnversTestCase.java
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/hibernate/naturalid/HibernateNativeAPINaturalIdTestCase.java
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/hibernate/secondlevelcache/HibernateSecondLevelCacheTestCase.java
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/jpa/hibernate/entitytest/EntityTestCase.java
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/jpa/hibernate/sessionfactorytest/SessionFactoryTestCase.java
  testsuite/integration/clustering/pom.xml
  testsuite/integration/clustering/src/test/java/org/jboss/as/test/clustering/single/web/NonHaWebSessionPersistenceTestCase.java
  testsuite/integration/elytron-oidc-client/pom.xml
  testsuite/integration/elytron/pom.xml
  testsuite/integration/microprofile-tck/config/pom.xml
  testsuite/integration/microprofile-tck/fault-tolerance/pom.xml
  testsuite/integration/microprofile-tck/health/pom.xml
  testsuite/integration/microprofile-tck/jwt/pom.xml
  testsuite/integration/microprofile-tck/lra/pom.xml
  testsuite/integration/microprofile-tck/openapi/pom.xml
  testsuite/integration/microprofile-tck/pom.xml
  testsuite/integration/microprofile-tck/reactive-messaging/pom.xml
  testsuite/integration/microprofile-tck/reactive-streams-operators/pom.xml
  testsuite/integration/microprofile-tck/rest-client/pom.xml
  testsuite/integration/microprofile-tck/telemetry/pom.xml
  testsuite/integration/microprofile/pom.xml
  testsuite/integration/pom.xml
  testsuite/integration/secman/pom.xml
  testsuite/integration/smoke/pom.xml
  testsuite/integration/vdx/pom.xml
  testsuite/integration/web/pom.xml
  testsuite/layers-expansion/pom.xml
  testsuite/layers/pom.xml
  testsuite/pom.xml
  testsuite/preview/basic/pom.xml
  testsuite/preview/pom.xml
  testsuite/scripts/pom.xml
  testsuite/shared/src/main/java/org/jboss/as/test/shared/util/AssumeTestGroupUtil.java
Labels: deps-ok

#17078 WFLY-18328 Upgrade Weld to 5.1.1.SP2
  pom.xml
Labels: deps-ok

#17076 [WFLY-18296]:change the jdk.compiler dependency as optional as this i…
  ee-feature-pack/galleon-shared/src/main/resources/modules/system/layers/base/org/glassfish/jaxb/main/module.xml
Labels: deps-ok

#17057 [WFLY-18305] Enable dependabot for patch release upgrades.
  .github/dependabot.yml
Labels: deps-ok

#17079 [WFLY-18329][WFLY-18317] Upgrade WildFly Core to 22.0.0.Beta1 and fix BouncyCastleModuleTestCase
  pom.xml
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/bc/BouncyCastleModuleTestCase.java
Labels: deps-changed

#17060 WFLY-18306 Default Infinispan remote-timeout should not be less than the default lock-timeout
  clustering/infinispan/extension/src/main/java/org/jboss/as/clustering/infinispan/subsystem/ClusteredCacheResourceDefinition.java
  clustering/infinispan/extension/src/main/java/org/jboss/as/clustering/infinispan/subsystem/ClusteredCacheResourceTransformer.java
  clustering/infinispan/extension/src/main/java/org/jboss/as/clustering/infinispan/subsystem/InfinispanSubsystemModel.java
  clustering/infinispan/extension/src/main/resources/schema/jboss-as-infinispan_14_0.xsd
Labels: deps-ok

#17064 WFLY-17801 Re-enable HotRodPersistentTimerTestCase
  testsuite/integration/clustering/src/test/java/org/jboss/as/test/clustering/cluster/ejb/timer/remote/HotRodPersistentTimerServiceTestCase.java
Labels: deps-ok

#17080 [WFLY-18330] Upgrade okio to 3.4.0
  pom.xml
Labels: 29.x

#16986 [WFLY-18201] Require Remote HTTP Invoker to participate in EE interoperability handshake.
  undertow/src/main/java/org/wildfly/extension/undertow/RemoteHttpInvokerService.java
Labels: deps-ok

#17090 [WFLY-18245] Move the org.apache.avro module from the wildfly-ee feat…
  boms/common-ee/pom.xml
  boms/preview-ee/pom.xml
  ee-feature-pack/galleon-shared/pom.xml
  ee-feature-pack/galleon-shared/src/main/resources/license/licenses.xml
  preview/galleon-local/pom.xml
  preview/galleon-local/src/main/resources/license/licenses.xml
  preview/galleon-local/src/main/resources/modules/system/layers/base/org/apache/avro/main/module.xml
  testsuite/shared/src/main/java/org/jboss/as/test/shared/LayersTestBase.java
Labels: deps-changed

#17075 [WFLY-18047]:Remove legacy Xerces dependency from webservice modules
  ee-feature-pack/galleon-shared/src/main/resources/modules/system/layers/base/com/sun/xml/messaging/saaj/main/module.xml
  ee-feature-pack/galleon-shared/src/main/resources/modules/system/layers/base/org/jboss/as/webservices/server/integration/main/module.xml
  ee-feature-pack/galleon-shared/src/main/resources/modules/system/layers/base/org/jboss/ws/common/main/module.xml
  testsuite/shared/src/main/java/org/jboss/as/test/shared/LayersTestBase.java
  webservices/server-integration/src/main/java/org/jboss/as/webservices/deployers/WSDependenciesProcessor.java
Labels: deps-ok

#17091 WFLY-18341 Restore incorrectly updated copyright dates in Jipijapa
  boms/common-ee/pom.xml
  ee-feature-pack/galleon-shared/src/main/resources/modules/system/layers/base/org/hibernate/search/engine/main/module.xml
  ee-feature-pack/galleon-shared/src/main/resources/modules/system/layers/base/org/hibernate/search/mapper/orm/main/module.xml
  ee-feature-pack/galleon-shared/src/main/resources/modules/system/layers/base/org/hibernate/search/mapper/pojo/main/module.xml
  jpa/subsystem/src/main/java/org/jboss/as/jpa/config/Configuration.java
  jpa/subsystem/src/main/java/org/jboss/as/jpa/messages/JpaLogger.java
  jpa/subsystem/src/main/java/org/jboss/as/jpa/processor/HibernateSearchProcessor.java
  jpa/subsystem/src/main/java/org/jboss/as/jpa/processor/JpaAttachments.java
  jpa/subsystem/src/main/java/org/jboss/as/jpa/processor/PersistenceProviderAdaptorLoader.java
  jpa/subsystem/src/main/java/org/jboss/as/jpa/processor/PersistenceUnitServiceHandler.java
  jpa/subsystem/src/main/java/org/jboss/as/jpa/service/PersistenceUnitServiceImpl.java
  pom.xml
Labels: deps-ok

#17092 WFLY-18341 Restore incorrectly updated copyright dates in Jipijapa
  boms/common-ee/pom.xml
  ee-feature-pack/galleon-shared/src/main/resources/modules/system/layers/base/org/hibernate/search/engine/main/module.xml
  ee-feature-pack/galleon-shared/src/main/resources/modules/system/layers/base/org/hibernate/search/mapper/orm/main/module.xml
  ee-feature-pack/galleon-shared/src/main/resources/modules/system/layers/base/org/hibernate/search/mapper/pojo/main/module.xml
  jpa/subsystem/src/main/java/org/jboss/as/jpa/config/Configuration.java
  jpa/subsystem/src/main/java/org/jboss/as/jpa/messages/JpaLogger.java
  jpa/subsystem/src/main/java/org/jboss/as/jpa/processor/HibernateSearchProcessor.java
  jpa/subsystem/src/main/java/org/jboss/as/jpa/processor/JpaAttachments.java
  jpa/subsystem/src/main/java/org/jboss/as/jpa/processor/PersistenceProviderAdaptorLoader.java
  jpa/subsystem/src/main/java/org/jboss/as/jpa/processor/PersistenceUnitServiceHandler.java
  jpa/subsystem/src/main/java/org/jboss/as/jpa/service/PersistenceUnitServiceImpl.java
  pom.xml
Labels: 29.x

#17059 WFLY-18304 Enable manual start of github actions CI workflow [skip ci]
  .github/workflows/build-manual.yml
  .github/workflows/build-only.yml
Labels: deps-ok

#17102 [29.x][WFLY-18350] Constrain the testsuite/galleon/update testing to the minor channel associated with the branch.
  pom.xml
  testsuite/galleon/update/pom.xml
  testsuite/galleon/update/run-test.sh
Labels: ready-for-merge, 29.x

#17097 [WFLY-18345] added jdk.security.jgss to module
  ee-feature-pack/galleon-shared/src/main/resources/modules/system/layers/base/org/apache/ws/security/main/module.xml
Labels: deps-ok

#17104 [WFLY-18353] Update TestCustomPrincipalTransformer to no longer rely on the Elytron subsystem
  testsuite/integration/elytron/pom.xml
  testsuite/integration/elytron/src/test/java/org/wildfly/test/integration/elytron/application/CredentialStoreI18NTestCase.java
  testsuite/integration/elytron/src/test/java/org/wildfly/test/integration/elytron/application/CredentialStoreTestCase.java
  testsuite/integration/elytron/src/test/java/org/wildfly/test/integration/elytron/securityapi/TestCustomPrincipalTransformer.java
Labels: deps-ok

#17113 Put the @ in the security@wildfly.org mail address
  SECURITY.md
Labels: deps-ok

#17051 [WFLY-18296] Remove the org.jboss.jts dependency on jdk.console
  ee-feature-pack/galleon-shared/src/main/resources/modules/system/layers/base/org/glassfish/jaxb/main/module.xml
  ee-feature-pack/galleon-shared/src/main/resources/modules/system/layers/base/org/jboss/jts/main/module.xml
Labels: ready-for-merge, Blocker, 29.x

#17129 [WFLY-18378] Upgrade resteasy-microprofile to 2.1.3.Final.
  pom.xml
Labels: Blocker, deps-ok

#17130 [29.x] [WFLY-18378] Upgrade resteasy-microprofile to 2.1.3.Final.
  pom.xml
Labels: Blocker, 29.x

#17126 [WFLY-18376] Upgrade RESTEasy to 6.2.5.Final
  pom.xml
Labels: deps-ok

#17127 [29.x] [WFLY-18376] Upgrade RESTEasy to 6.2.5.Final
  pom.xml
Labels: 29.x

#17131 WFLY-18379 Upgrade WildFly Core to 21.1.1.Final
  pom.xml
Labels: 29.x

#17114 WFLY-18367 Upgrade version.org.jboss.arquillian.core from 1.7.0.Final to 1.7.1.Final
  pom.xml
Labels: deps-ok

#17121 WFLY-18374 + WFLY-18375 Upgrade to Hibernate Search 6.2.1.Final
  pom.xml
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/hibernate/search/backend/elasticsearch/util/ElasticsearchServerSetupObserver.java
Labels: deps-ok

#16781 [WFLY-17842] Update documentation due to removal of sun.jdk as implicit dependency
  docs/src/main/asciidoc/_developer-guide/Implicit_module_dependencies_for_deployments.adoc
Labels: deps-ok
