Repository wildfly/wildfly, pull requests merged in 2023-01, with the labels that each got.

#16394 WFLY-17421 Eliminate static references to Weld ResourceDefinition instances
  weld/subsystem/src/main/java/org/jboss/as/weld/WeldExtension.java
  weld/subsystem/src/main/java/org/jboss/as/weld/WeldResourceDefinition.java
  weld/subsystem/src/main/java/org/jboss/as/weld/WeldSubsystem20Parser.java
  weld/subsystem/src/main/java/org/jboss/as/weld/WeldSubsystem30Parser.java
  weld/subsystem/src/main/java/org/jboss/as/weld/WeldSubsystem40Parser.java
  weld/subsystem/src/main/java/org/jboss/as/weld/WeldSubsystem50Parser.java
Labels: deps-ok

#16401 WFLY-17428 Eliminate static references to EE-security subsystem ResourceDefinition instances
  ee-security/src/main/java/org/wildfly/extension/eesecurity/EESecurityExtension.java
  ee-security/src/main/java/org/wildfly/extension/eesecurity/EESecuritySubsystemDefinition.java
  ee-security/src/main/java/org/wildfly/extension/eesecurity/EESecuritySubsystemParser_1_0.java
Labels: deps-ok

#16436 [WFLY-17457] Upgrade jboss-ejb-client from 4.0.49.Final to 4.0.50.Final
  pom.xml
Labels: deps-ok

#16397 WFLY-17424 Eliminate static references to datasources ResourceDefinition instances
  connector/src/main/java/org/jboss/as/connector/subsystems/datasources/ConnectionPropertyDefinition.java
  connector/src/main/java/org/jboss/as/connector/subsystems/datasources/DataSourceDefinition.java
  connector/src/main/java/org/jboss/as/connector/subsystems/datasources/DataSourcesSubsystemRootDefinition.java
  connector/src/main/java/org/jboss/as/connector/subsystems/datasources/JdbcDriverDefinition.java
  connector/src/main/java/org/jboss/as/connector/subsystems/datasources/XaDataSourceDefinition.java
  connector/src/main/java/org/jboss/as/connector/subsystems/datasources/XaDataSourcePropertyDefinition.java
Labels: deps-ok

#16398 WFLY-17425 Eliminate static references to JCA ResourceDefinition instances
  connector/src/main/java/org/jboss/as/connector/subsystems/jca/JcaArchiveValidationDefinition.java
  connector/src/main/java/org/jboss/as/connector/subsystems/jca/JcaBeanValidationDefinition.java
  connector/src/main/java/org/jboss/as/connector/subsystems/jca/JcaBootstrapContextDefinition.java
  connector/src/main/java/org/jboss/as/connector/subsystems/jca/JcaCachedConnectionManagerDefinition.java
  connector/src/main/java/org/jboss/as/connector/subsystems/jca/JcaSubsystemRootDefinition.java
  connector/src/main/java/org/jboss/as/connector/subsystems/jca/TracerDefinition.java
Labels: deps-ok

#16410 WFLY-17440 Eliminate static references to messaging-activemq subsystem ResourceDefinition instances
  messaging-activemq/subsystem/src/main/java/org/wildfly/extension/messaging/activemq/AddressSettingDefinition.java
  messaging-activemq/subsystem/src/main/java/org/wildfly/extension/messaging/activemq/ConnectorServiceDefinition.java
  messaging-activemq/subsystem/src/main/java/org/wildfly/extension/messaging/activemq/CoreAddressDefinition.java
  messaging-activemq/subsystem/src/main/java/org/wildfly/extension/messaging/activemq/DivertDefinition.java
  messaging-activemq/subsystem/src/main/java/org/wildfly/extension/messaging/activemq/GroupingHandlerDefinition.java
  messaging-activemq/subsystem/src/main/java/org/wildfly/extension/messaging/activemq/HTTPAcceptorDefinition.java
  messaging-activemq/subsystem/src/main/java/org/wildfly/extension/messaging/activemq/MessagingExtension.java
  messaging-activemq/subsystem/src/main/java/org/wildfly/extension/messaging/activemq/MessagingSubsystemParser_10_0.java
  messaging-activemq/subsystem/src/main/java/org/wildfly/extension/messaging/activemq/MessagingSubsystemParser_11_0.java
  messaging-activemq/subsystem/src/main/java/org/wildfly/extension/messaging/activemq/MessagingSubsystemParser_12_0.java
  messaging-activemq/subsystem/src/main/java/org/wildfly/extension/messaging/activemq/MessagingSubsystemParser_13_0.java
  messaging-activemq/subsystem/src/main/java/org/wildfly/extension/messaging/activemq/MessagingSubsystemParser_13_1.java
  messaging-activemq/subsystem/src/main/java/org/wildfly/extension/messaging/activemq/MessagingSubsystemParser_14_0.java
  messaging-activemq/subsystem/src/main/java/org/wildfly/extension/messaging/activemq/MessagingSubsystemParser_1_0.java
  messaging-activemq/subsystem/src/main/java/org/wildfly/extension/messaging/activemq/MessagingSubsystemParser_2_0.java
  messaging-activemq/subsystem/src/main/java/org/wildfly/extension/messaging/activemq/MessagingSubsystemParser_3_0.java
  messaging-activemq/subsystem/src/main/java/org/wildfly/extension/messaging/activemq/MessagingSubsystemParser_4_0.java
  messaging-activemq/subsystem/src/main/java/org/wildfly/extension/messaging/activemq/MessagingSubsystemParser_5_0.java
  messaging-activemq/subsystem/src/main/java/org/wildfly/extension/messaging/activemq/MessagingSubsystemParser_6_0.java
  messaging-activemq/subsystem/src/main/java/org/wildfly/extension/messaging/activemq/MessagingSubsystemParser_7_0.java
  messaging-activemq/subsystem/src/main/java/org/wildfly/extension/messaging/activemq/MessagingSubsystemParser_8_0.java
  messaging-activemq/subsystem/src/main/java/org/wildfly/extension/messaging/activemq/MessagingSubsystemParser_9_0.java
  messaging-activemq/subsystem/src/main/java/org/wildfly/extension/messaging/activemq/PathDefinition.java
  messaging-activemq/subsystem/src/main/java/org/wildfly/extension/messaging/activemq/SecurityRoleDefinition.java
  messaging-activemq/subsystem/src/main/java/org/wildfly/extension/messaging/activemq/SecuritySettingDefinition.java
  messaging-activemq/subsystem/src/main/java/org/wildfly/extension/messaging/activemq/ServerDefinition.java
  messaging-activemq/subsystem/src/main/java/org/wildfly/extension/messaging/activemq/ha/LiveOnlyDefinition.java
  messaging-activemq/subsystem/src/main/java/org/wildfly/extension/messaging/activemq/ha/ReplicationColocatedDefinition.java
  messaging-activemq/subsystem/src/main/java/org/wildfly/extension/messaging/activemq/ha/ReplicationPrimaryDefinition.java
  messaging-activemq/subsystem/src/main/java/org/wildfly/extension/messaging/activemq/ha/ReplicationSecondaryDefinition.java
  messaging-activemq/subsystem/src/main/java/org/wildfly/extension/messaging/activemq/ha/SharedStoreColocatedDefinition.java
  messaging-activemq/subsystem/src/main/java/org/wildfly/extension/messaging/activemq/ha/SharedStorePrimaryDefinition.java
  messaging-activemq/subsystem/src/main/java/org/wildfly/extension/messaging/activemq/ha/SharedStoreSecondaryDefinition.java
  messaging-activemq/subsystem/src/main/java/org/wildfly/extension/messaging/activemq/jms/ExternalPooledConnectionFactoryDefinition.java
  messaging-activemq/subsystem/src/main/java/org/wildfly/extension/messaging/activemq/jms/PooledConnectionFactoryDefinition.java
  messaging-activemq/subsystem/src/main/java/org/wildfly/extension/messaging/activemq/jms/bridge/JMSBridgeDefinition.java
  messaging-activemq/subsystem/src/main/java/org/wildfly/extension/messaging/activemq/jms/legacy/LegacyConnectionFactoryDefinition.java
Labels: deps-ok

#16438 WFLY-17471 write-attribute operation handler used by clustering subsystems apply wrong values to runtime during rollback
  clustering/common/src/main/java/org/jboss/as/clustering/controller/WriteAttributeStepHandler.java
Labels: deps-ok

#16429 [WFLY-17269] Drop source transformation for the weld/common and weld/…
  boms/legacy-ee/pom.xml
  ee-9/source-transform/pom.xml
  ee-9/source-transform/weld/common/pom.xml
  ee-9/source-transform/weld/spi/pom.xml
  weld/bean-validation/pom.xml
  weld/common/pom.xml
  weld/common/src/main/java/org/jboss/as/weld/WeldCapability.java
  weld/common/src/main/java/org/jboss/as/weld/deployment/WeldPortableExtensions.java
  weld/common/src/main/java/org/jboss/as/weld/ejb/EjbRequestScopeActivationInterceptor.java
  weld/common/src/main/java/org/jboss/as/weld/interceptors/Jsr299BindingsInterceptor.java
  weld/common/src/main/java/org/jboss/as/weld/interceptors/WeldInterceptorInstances.java
  weld/common/src/main/java/org/jboss/as/weld/logging/WeldLogger.java
  weld/common/src/main/java/org/jboss/as/weld/services/bootstrap/AbstractResourceInjectionServices.java
  weld/common/src/main/java/org/jboss/as/weld/util/ResourceInjectionUtilities.java
  weld/ejb/pom.xml
  weld/jpa/pom.xml
  weld/pom.xml
  weld/spi/pom.xml
  weld/spi/src/main/java/org/jboss/as/weld/spi/ComponentInterceptorSupport.java
  weld/spi/src/main/java/org/jboss/as/weld/spi/ComponentSupport.java
  weld/spi/src/main/java/org/jboss/as/weld/spi/InterceptorInstances.java
  weld/subsystem/pom.xml
  weld/transactions/pom.xml
  weld/webservices/pom.xml
Labels: deps-ok

#16441 [WFLY-17475] Eliminating usage of deprecated org.jboss.msc.service.AbstractService
  transactions/src/main/java/org/jboss/as/txn/service/TransactionManagerService.java
  transactions/src/main/java/org/jboss/as/txn/service/TransactionSynchronizationRegistryService.java
  transactions/src/main/java/org/jboss/as/txn/service/UserTransactionService.java
  xts/src/main/java/org/jboss/as/xts/TxBridgeInboundRecoveryService.java
  xts/src/main/java/org/jboss/as/xts/TxBridgeOutboundRecoveryService.java
  xts/src/main/java/org/jboss/as/xts/XTSHandlersService.java
  xts/src/main/java/org/jboss/as/xts/XTSManagerService.java
Labels: deps-ok

#16437 [WFLY-17468] Upgrade jboss-ejb-client to 5.0.2.Final
  pom.xml
Labels: deps-ok

#16444 WFLY-17472 Add comment expounding the importance of defining the initial mode of the parent service within the associated ResourceServiceConfigurator.
  clustering/common/src/main/java/org/jboss/as/clustering/controller/RestartParentResourceRegistrar.java
Labels: deps-ok, Trivial

#16440 [WFLY-17474]:Upgrade CXF to 3.4.10
  pom.xml
Labels: 26.x

#16445 [WFLY-17479] Correct the package for the EE subsystem test case.
  ee-security/src/test/java/org/wildfly/extension/eesecurity/EESecuritySubsystemTestCase.java
Labels: deps-ok

#16426 [WFLY-17462] Use REPORT_DIRECTORY.validateAndSet instead of a direct …
  connector/src/main/java/org/jboss/as/connector/subsystems/resourceadapters/ResourceAdaptersSubSystemAdd.java
Labels: deps-ok

#16393 WFLY-17420 Eliminate static references to bean-validation ResourceDefinition instances
  bean-validation/src/main/java/org/wildfly/extension/beanvalidation/BeanValidationExtension.java
  bean-validation/src/main/java/org/wildfly/extension/beanvalidation/BeanValidationRootDefinition.java
  bean-validation/src/main/java/org/wildfly/extension/beanvalidation/BeanValidationSubsystemParser.java
Labels: deps-ok

#16392 WFLY-17419 Eliminate static references to JSF ResourceDefinition instances
  jsf/subsystem/src/main/java/org/jboss/as/jsf/subsystem/JSFExtension.java
  jsf/subsystem/src/main/java/org/jboss/as/jsf/subsystem/JSFResourceDefinition.java
Labels: deps-ok

#16300 [WFLY-16990]: The broker roles are not displayed in the proper format.
  messaging-activemq/subsystem/src/main/java/org/wildfly/extension/messaging/activemq/ActiveMQServerControlHandler.java
  messaging-activemq/subsystem/src/main/java/org/wildfly/extension/messaging/activemq/ManagementUtil.java
  messaging-activemq/subsystem/src/main/java/org/wildfly/extension/messaging/activemq/SecurityRoleDefinition.java
  messaging-activemq/subsystem/src/main/resources/org/wildfly/extension/messaging/activemq/LocalDescriptions.properties
Labels: deps-ok

#16453 [26.x][WFLY-17494] Upgrade jaxb-ri to 2.3.3-b02-jbossorg-2
  ee-9/pom.xml
  pom.xml
Labels: 26.x

#16461 [WFLY-17508] Upgrade Jakarta Mail to 2.1.1
  pom.xml
Labels: deps-ok

#16462 [WFLY-17509] Upgrade Jakarta Activation to 2.1.1
  pom.xml
Labels: deps-ok

#16399 WFLY-17426 Eliminate static references to datasource-agroal ResourceDefinition instances
  datasources-agroal/src/main/java/org/wildfly/extension/datasources/agroal/AbstractDataSourceDefinition.java
  datasources-agroal/src/main/java/org/wildfly/extension/datasources/agroal/AgroalExtension.java
  datasources-agroal/src/main/java/org/wildfly/extension/datasources/agroal/AgroalSubsystemDefinition.java
  datasources-agroal/src/main/java/org/wildfly/extension/datasources/agroal/AgroalSubsystemParser_1_0.java
  datasources-agroal/src/main/java/org/wildfly/extension/datasources/agroal/AgroalSubsystemParser_2_0.java
  datasources-agroal/src/main/java/org/wildfly/extension/datasources/agroal/DataSourceDefinition.java
  datasources-agroal/src/main/java/org/wildfly/extension/datasources/agroal/DriverDefinition.java
  datasources-agroal/src/main/java/org/wildfly/extension/datasources/agroal/XADataSourceDefinition.java
Labels: deps-ok

#16466 [WFLY-17506] Use deployment-transformer-feature-pack jar in the wildf…
  boms/preview-ee/pom.xml
  boms/standard-ee/pom.xml
  ee-9/common/pom.xml
  ee-9/common/src/main/resources/license/preview-feature-pack-common-licenses.xml
  ee-9/common/src/main/resources/modules/system/layers/base/org/wildfly/deployment/transformation/main/module.xml
  ee-9/deployment-transformer/pom.xml
  ee-9/deployment-transformer/src/main/java/org/wildfly/ee8to9/transformer/DeploymentTransformer.java
  ee-9/deployment-transformer/src/main/resources/META-INF/services/org.jboss.as.server.deployment.transformation.DeploymentTransformer
  ee-9/pom.xml
  pom.xml
Labels: deps-ok

#16472 WFLY-17540 Upgrade Infinispan to 14.0.6.Final
  pom.xml
Labels: deps-ok

#16468 [WFLY-17520] Upgrade WildFly Core to 20.0.0.Beta5
  pom.xml
Labels: deps-ok

#16475 WFLY-17544 Upgrade JGroups to 5.2.12.Final
  pom.xml
Labels: deps-ok

#16459 [WFLY-17504] Upgrade joda-time 2.12.1
  pom.xml
Labels: deps-ok

#16464 [WFLY-17332] Upgrade Narayana to 6.0.0.CR1
  boms/legacy-ee/pom.xml
  boms/standard-ee/pom.xml
  connector/pom.xml
  ee-feature-pack/common/pom.xml
  ee-feature-pack/common/src/main/resources/license/ee-feature-pack-common-licenses.xml
  ee-feature-pack/common/src/main/resources/modules/system/layers/base/org/jboss/jts/integration/main/module.xml
  ee-feature-pack/common/src/main/resources/modules/system/layers/base/org/jboss/jts/main/module.xml
  ee-feature-pack/common/src/main/resources/modules/system/layers/base/org/jboss/narayana/compensations/main/module.xml
  ee-feature-pack/common/src/main/resources/modules/system/layers/base/org/jboss/narayana/rts/main/module.xml
  ee-feature-pack/common/src/main/resources/modules/system/layers/base/org/jboss/xts/main/module.xml
  ejb3/pom.xml
  iiop-openjdk/pom.xml
  pom.xml
  preview/common/src/main/resources/license/preview-feature-pack-common-licenses.xml
  rts/pom.xml
  testsuite/integration/basic/pom.xml
  testsuite/integration/iiop/pom.xml
  testsuite/integration/legacy-ejb-client/pom.xml
  testsuite/integration/manualmode/pom.xml
  testsuite/integration/rts/pom.xml
  testsuite/integration/xts/pom.xml
  testsuite/shared/pom.xml
  transactions/pom.xml
  xts/pom.xml
Labels: deps-changed

#16450 WFLY-17242 Add a CONTRIBUTING.md
  CONTRIBUTING.md
  README.md
  docs/src/main/asciidoc/_hacking/contributing.adoc
Labels: deps-ok

#16471 [WFLY-17412] Create a testbom
  boms/standard-test/pom.xml
  pom.xml
  testsuite/pom.xml
  testsuite/shared/pom.xml
Labels: deps-ok

#16454 WFLY-17385 Static and final method verification for bean superclasses
  ejb3/src/main/java/org/jboss/as/ejb3/component/EJBValidationConfigurator.java
  ejb3/src/main/java/org/jboss/as/ejb3/util/EjbValidationsUtil.java
Labels: ready-for-merge, deps-ok

#16479 [WFLY-17555] Remove the javax.xml.rpc.api.internal module
  ee-feature-pack/common/src/main/resources/modules/system/layers/base/org/jboss/as/ejb3/main/module.xml
  ee-feature-pack/ee-10-api/src/main/resources/modules/system/layers/base/javax/xml/rpc/api/internal/main/module.xml
Labels: deps-ok

#16480 WFLY-17557 Fix TopologyChangeListenerBean failing with CNFE; remove u…
  testsuite/integration/clustering/src/test/java/org/jboss/as/test/clustering/TopologyChangeListenerBean.java
Labels: deps-ok

#16478 [WFLY-17553] Remove the 'jakarta' maven resource plugin filtering of …
  ee-feature-pack/common/src/main/resources/modules/system/layers/base/javax/orb/api/main/module.xml
  ee-feature-pack/common/src/main/resources/modules/system/layers/base/org/apache/activemq/artemis/main/module.xml
  ee-feature-pack/common/src/main/resources/modules/system/layers/base/org/apache/activemq/artemis/ra/main/module.xml
  ee-feature-pack/common/src/main/resources/modules/system/layers/base/org/hornetq/client/main/module.xml
  ee-feature-pack/common/src/main/resources/modules/system/layers/base/org/infinispan/client/hotrod/main/module.xml
  ee-feature-pack/common/src/main/resources/modules/system/layers/base/org/infinispan/commons/main/module.xml
  ee-feature-pack/common/src/main/resources/modules/system/layers/base/org/infinispan/main/module.xml
  ee-feature-pack/common/src/main/resources/modules/system/layers/base/org/infinispan/persistence/jdbc/main/module.xml
  ee-feature-pack/common/src/main/resources/modules/system/layers/base/org/jboss/iiop-client/main/module.xml
  ee-feature-pack/common/src/main/resources/modules/system/layers/base/org/jboss/ironjacamar/api/main/module.xml
  ee-feature-pack/common/src/main/resources/modules/system/layers/base/org/jboss/ironjacamar/impl/main/module.xml
  ee-feature-pack/common/src/main/resources/modules/system/layers/base/org/jboss/ironjacamar/jdbcadapters/main/module.xml
  ee-feature-pack/common/src/main/resources/modules/system/layers/base/org/jboss/jboss-transaction-spi/main/module.xml
  ee-feature-pack/common/src/main/resources/modules/system/layers/base/org/jboss/metadata/ejb/main/module.xml
  ee-feature-pack/common/src/main/resources/modules/system/layers/base/org/wildfly/extension/messaging-activemq/main/module.xml
  ee-feature-pack/galleon-feature-pack/pom.xml
  galleon-pack/galleon-feature-pack/pom.xml
  pom.xml
  preview/feature-pack/pom.xml
  servlet-feature-pack/common/src/main/resources/modules/system/layers/base/org/jboss/metadata/common/main/module.xml
Labels: deps-ok

#16465 [WFLY-17514] NPE when -ds.xml file included in deployment contains va…
  connector/src/main/java/org/jboss/as/connector/subsystems/datasources/XMLDataSourceRuntimeHandler.java
  connector/src/main/java/org/jboss/as/connector/subsystems/datasources/XMLXaDataSourceRuntimeHandler.java
Labels: deps-ok

#16482 WFLY-17503 Remove unused method org.jboss.as.ejb3.util.EjbValidations…
  ejb3/src/main/java/org/jboss/as/ejb3/util/EjbValidationsUtil.java
  ejb3/src/test/java/org/jboss/as/ejb3/util/EjbValidationsUtilTest.java
Labels: deps-ok

#16483 WFLY-15053 Remove the methods that have been removed from Jakarta Ent…
  ejb3/src/main/java/org/jboss/as/ejb3/context/EJBContextImpl.java
  ejb3/src/main/java/org/jboss/as/ejb3/logging/EjbLogger.java
Labels: deps-ok

#16449 WFLY-17493 Drop support for Undertow subsystem schemas prior to WildFly 10.1
  undertow/src/main/java/org/wildfly/extension/undertow/UndertowExtension.java
  undertow/src/main/java/org/wildfly/extension/undertow/UndertowSubsystemParser_1_0.java
  undertow/src/main/java/org/wildfly/extension/undertow/UndertowSubsystemParser_1_1.java
  undertow/src/main/java/org/wildfly/extension/undertow/UndertowSubsystemParser_1_2.java
  undertow/src/main/java/org/wildfly/extension/undertow/UndertowSubsystemParser_2_0.java
  undertow/src/main/java/org/wildfly/extension/undertow/UndertowSubsystemParser_3_0.java
  undertow/src/main/resources/schema/wildfly-undertow_1_0.xsd
  undertow/src/main/resources/schema/wildfly-undertow_1_1.xsd
  undertow/src/main/resources/schema/wildfly-undertow_1_2.xsd
  undertow/src/main/resources/schema/wildfly-undertow_2_0.xsd
  undertow/src/main/resources/schema/wildfly-undertow_3_0.xsd
  undertow/src/test/java/org/wildfly/extension/undertow/UndertowSubsystem10TestCase.java
  undertow/src/test/java/org/wildfly/extension/undertow/UndertowSubsystem11TestCase.java
  undertow/src/test/java/org/wildfly/extension/undertow/UndertowSubsystem12TestCase.java
  undertow/src/test/java/org/wildfly/extension/undertow/UndertowSubsystem20TestCase.java
  undertow/src/test/java/org/wildfly/extension/undertow/UndertowSubsystem30TestCase.java
Labels: deps-ok

#16487 WFLY-17567 Transaction logic in WebJPATestCase servlet masks root cause of test failures
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/jpa/webtxem/TestServlet.java
Labels: deps-ok

#16382 WFLY-17411 Fix incorrect MSC usage by ModClusterResource
  undertow/src/main/java/org/wildfly/extension/undertow/filters/ModClusterBalancerDefinition.java
  undertow/src/main/java/org/wildfly/extension/undertow/filters/ModClusterBalancerResource.java
  undertow/src/main/java/org/wildfly/extension/undertow/filters/ModClusterContextDefinition.java
  undertow/src/main/java/org/wildfly/extension/undertow/filters/ModClusterDefinition.java
  undertow/src/main/java/org/wildfly/extension/undertow/filters/ModClusterLoadBalancingGroupDefinition.java
  undertow/src/main/java/org/wildfly/extension/undertow/filters/ModClusterNodeDefinition.java
  undertow/src/main/java/org/wildfly/extension/undertow/filters/ModClusterNodeResource.java
  undertow/src/main/java/org/wildfly/extension/undertow/filters/ModClusterResource.java
  undertow/src/main/java/org/wildfly/extension/undertow/filters/ModClusterService.java
  undertow/src/main/java/org/wildfly/extension/undertow/filters/ModClusterServiceNameProvider.java
  undertow/src/test/java/org/wildfly/extension/undertow/AbstractUndertowSubsystemTestCase.java
Labels: deps-ok

#16456 [WFLY-17499] Upgrade Apache mime4j from 0.8.7 to 0.8.9 (resolves
  pom.xml
Labels: deps-ok

#16451 WFLY-17495 - Update `resteasy-spring` to `3.0.1.Final`
  pom.xml
Labels: deps-ok

#16485 Fix for WFLY-17565, Upgrade galleon-plugins to 6.2.3.Final
  pom.xml
Labels: deps-ok

#16362 WFLY-17292 Upgrade smallrye-open-api to 3.1.2
  boms/standard-test/pom.xml
  pom.xml
  testsuite/integration/microprofile-tck/openapi/pom.xml
Labels: deps-ok

#16484 WFLY-17561 Move test dependency which is dependent on the WFCORE
  boms/standard-test/pom.xml
Labels: deps-ok

#16486 WFLY-17562 upgrade to org.jboss.spec.jakarta.el:jboss-el-api_5.0_spec:4.0.1.Final
  pom.xml
Labels: deps-ok

#16430 [WFLY-17464] Asciidoctor attribute sourceHighlighter position
  pom.xml
Labels: deps-ok

#16372 [WFLY-17404] Upgrade RESTEasy to 6.2.2.Final
  ee-feature-pack/common/src/main/resources/modules/system/layers/base/org/jboss/resteasy/resteasy-core-spi/main/module.xml
  ee-feature-pack/common/src/main/resources/modules/system/layers/base/org/jboss/resteasy/resteasy-core/main/module.xml
  jaxrs/src/main/java/org/jboss/as/jaxrs/deployment/JaxrsIntegrationProcessor.java
  jaxrs/src/main/java/org/jboss/as/jaxrs/deployment/WildFlyConfigurationFactory.java
  jaxrs/src/main/java/org/jboss/as/jaxrs/logging/JaxrsLogger.java
  jaxrs/src/main/resources/META-INF/services/org.jboss.resteasy.spi.config.ConfigurationFactory
  pom.xml
Labels: deps-ok

#16491 [WFLY-17356] [testsuite] Remove master from NonDefaultRemoteWorkerTestCase and other minor classes in the testsuite
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/ejb/remote/worker/NonDefaultRemoteWorkerTestCase.java
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/jpa/epcpropagation/EPCPropagationTestCase.java
  testsuite/integration/elytron-oidc-client/src/test/java/org/wildfly/test/integration/elytron/oidc/client/KeycloakConfiguration.java
  testsuite/integration/manualmode/src/test/java/org/jboss/as/test/manualmode/messaging/ha/FailoverTestCase.java
  testsuite/integration/manualmode/src/test/java/org/jboss/as/test/manualmode/messaging/ha/ReplicatedFailoverTestCase.java
  testsuite/integration/manualmode/src/test/java/org/jboss/as/test/manualmode/messaging/ha/ReplicatedNettyFailoverTestCase.java
Labels: deps-ok

#16477 WFLY-17552 MDC from 'default task' Thread copied to 'Batch Thread' on…
  batch-jberet/src/main/java/org/wildfly/extension/batch/jberet/deployment/BatchEnvironmentService.java
  batch-jberet/src/main/java/org/wildfly/extension/batch/jberet/deployment/DiagnosticContextHandle.java
Labels: deps-ok

#16447 [WFLY-17487] Remove usage of legacy InitialContextFactory from integr…
  docs/src/main/asciidoc/_developer-guide/How_do_I_migrate_my_application_from_AS7_to_WildFly.adoc
  docs/src/main/asciidoc/_developer-guide/JNDI_Remote_Reference.adoc
  docs/src/main/asciidoc/_developer-guide/Jakarta_XML_Web_Services/SOAP_over_Jakarta_Messaging.adoc
  docs/src/main/asciidoc/_elytron/migrate/Application_Client_Migration.adoc
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/deployment/deploymentoverlay/jar/JarOverlayTestBase.java
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/ejb/mdb/cdi/MDBRAScopeCdiIntegrationTestCase.java
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/management/deploy/runtime/StatefulEJBRemoteHomeRuntimeNameTestCase.java
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/management/deploy/runtime/StatelessEJBRemoteHomeRuntimeNameTestCase.java
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/management/deploy/runtime/TimerEJBRuntimeNameTestCase.java
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/naming/connector/JMXConnectorTestCase.java
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/naming/remote/ejb/RemoteNamingEjbTestCase.java
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/naming/remote/multiple/CallEjbServlet.java
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/naming/remote/multiple/MyEjbBean.java
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/naming/remote/multiple/RunRmiServlet.java
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/naming/remote/simple/RemoteNamingTestCase.java
  testsuite/integration/manualmode/src/test/java/org/jboss/as/test/manualmode/messaging/CoreBridgeCallTimeoutTestCase.java
  testsuite/integration/manualmode/src/test/java/org/jboss/as/test/manualmode/messaging/CoreBridgeQueueToTopicTestCase.java
  testsuite/integration/manualmode/src/test/java/org/jboss/as/test/manualmode/messaging/CorruptedLogTestCase.java
  testsuite/integration/manualmode/src/test/java/org/jboss/as/test/manualmode/messaging/CriticalAnalyzerTestCase.java
  testsuite/integration/manualmode/src/test/java/org/jboss/as/test/manualmode/messaging/RuntimeJMSTopicManagementTestCase.java
  testsuite/integration/manualmode/src/test/java/org/jboss/as/test/manualmode/messaging/ha/AbstractMessagingHATestCase.java
  testsuite/integration/multinode/src/test/java/org/jboss/as/test/multinode/clientinterceptor/protocol/RemoteProtocolChangeClientInterceptorTestCase.java
  testsuite/integration/multinode/src/test/java/org/jboss/as/test/multinode/ejb/timer/database/DatabaseTimerServiceMultiNodeExecutionDisabledTestCase.java
Labels: deps-ok

#16433 [WFLY-17465] Testsuite POM lacks "version.ant.junit" property
  pom.xml
Labels: deps-ok

#16434 [WFLY-17466] Various AsciiDoc issues
  docs/src/main/asciidoc/Getting_Started_Developing_Applications_Guide.adoc
  docs/src/main/asciidoc/_admin-guide/management-api/The_native_management_API.adoc
  docs/src/main/asciidoc/_admin-guide/subsystem-configuration/Datasources_Agroal.adoc
  docs/src/main/asciidoc/_elytron/Using_the_Elytron_Subsystem.adoc
Labels: deps-ok

#16476 [WFLY-17545] Empty out the legacy boms
  boms/common-ee/pom.xml
  boms/legacy-ee/pom.xml
  boms/legacy-expansion/pom.xml
  boms/legacy-test/pom.xml
  boms/standard-ee/pom.xml
  boms/standard-expansion/pom.xml
  ee-feature-pack/common/src/main/resources/license/ee-feature-pack-common-licenses.xml
  ee-feature-pack/ee-10-api/src/main/resources/modules/system/layers/base/jakarta/faces/api/main/module.xml
  ee-feature-pack/ee-10-api/src/main/resources/modules/system/layers/base/jakarta/jms/api/main/module.xml
  ee-feature-pack/ee-10-api/src/main/resources/modules/system/layers/base/jakarta/resource/api/main/module.xml
  ee-feature-pack/ee-10-api/src/main/resources/modules/system/layers/base/jakarta/servlet/api/main/module.xml
  ee-feature-pack/ee-10-api/src/main/resources/modules/system/layers/base/jakarta/servlet/jsp/api/main/module.xml
  jdr/pom.xml
  jpa/subsystem/pom.xml
  jsf/injection/pom.xml
  legacy/jsr77/pom.xml
  legacy/keycloak/pom.xml
  microprofile/reactive-streams-operators-smallrye/cdi-provider/pom.xml
  naming/pom.xml
  picketlink/pom.xml
  pojo/pom.xml
  pom.xml
  preview/common/src/main/resources/license/preview-feature-pack-common-licenses.xml
  servlet-feature-pack/pom.xml
  testsuite/integration/basic/pom.xml
  testsuite/integration/legacy/pom.xml
Labels: deps-ok

#16490 WFLY-17571 Upgrade to Hibernate Commons Annotations 6.0.6.Final
  pom.xml
Labels: deps-ok

#16500 [WFLY-17579] Add missing module dependency to org.apache.james.mime4j…
  ee-feature-pack/common/src/main/resources/modules/system/layers/base/org/apache/james/mime4j/main/module.xml
  ee-feature-pack/common/src/main/resources/modules/system/layers/base/org/jboss/resteasy/resteasy-client/main/module.xml
  ee-feature-pack/ee-10-api/src/main/resources/modules/system/layers/base/jakarta/ws/rs/api/main/module.xml
Labels: deps-ok
