Repository wildfly/wildfly, pull requests merged in 2023-04, with the labels that each got.

#16677 [WFLY-17818] Update EJBDefaultSecurityDomainProcessor#isVirtualDomain to handle the case where the defined security domain is empty
  ejb3/src/main/java/org/jboss/as/ejb3/deployment/processors/EJBDefaultSecurityDomainProcessor.java
Labels: deps-ok

#16572 [WFLY-17686] Move ibm.jdk module into unsuded modules in LayersTestCase
  testsuite/layers/src/test/java/org/jboss/as/test/layers/LayersTestCase.java
Labels: deps-ok

#16690 [WFLY-17837] Upgrade jboss-ejb-client 5.0.4.Final
  pom.xml
Labels: deps-ok

#16682 Fixes for WFLY-17808, WFLY-12816, WFLY-17820, WFLY-17821, Licenses generation fixes
  ee-feature-pack/common/pom.xml
  ee-feature-pack/common/src/main/resources/license/ee-feature-pack-common-licenses.xml
  ee-feature-pack/ee-10-api/src/main/resources/modules/system/layers/base/jakarta/transaction/api/main/module.xml
  ee-feature-pack/galleon-common/src/main/resources/packages/docs.licenses/pm/wildfly/tasks.xml
  ee-feature-pack/galleon-feature-pack/pom.xml
  ee-feature-pack/galleon-shared/src/main/resources/configs/standalone/model.xml
  galleon-pack/galleon-content/src/main/resources/configs/standalone/model.xml
  galleon-pack/galleon-feature-pack/pom.xml
  galleon-pack/galleon-feature-pack/wildfly-feature-pack-build.xml
  microprofile/galleon-common/src/main/resources/license/microprofile-feature-pack-licenses.xml
  microprofile/galleon-common/src/main/resources/modules/system/layers/base/org/eclipse/microprofile/reactive-messaging/api/main/module.xml
  microprofile/galleon-common/src/main/resources/packages/docs.licenses/pm/wildfly/tasks.xml
  pom.xml
  preview/galleon-content/src/main/resources/configs/standalone/model.xml
Labels: deps-changed

#16659 [WFLY-15349] Use batch statement when creating ejb timer table in DatabaseTimerPersistence
  ejb3/src/main/java/org/jboss/as/ejb3/timerservice/persistence/database/DatabaseTimerPersistence.java
Labels: deps-ok

#16687 WFLY-17836 Global module default values in ee subsystem xsd do not match attribute definition
  ee/src/main/resources/schema/jboss-as-ee_6_0.xsd
Labels: deps-ok

#16686 [WFLY-17829] Wrong link to Custom Components in Elytron docs
  docs/src/main/asciidoc/_elytron/Using_the_Elytron_Subsystem.adoc
Labels: deps-ok

#16563 [WFLY-17666] Deployments using JNDI over RMI must define dependency on jdk.naming.rmi JPMS module
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/naming/connector/JMXConnectorTestCase.java
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/naming/rmi/RmiContextLookupTestCase.java
Labels: deps-ok

#16689 [WFLY-17839] Update mutiny vertx client to 3.0.0
  pom.xml
Labels: deps-changed

#16666 [WFLY-17600] add missing validators for some allowed values
  elytron-oidc-client/src/main/java/org/wildfly/extension/elytron/oidc/ProviderAttributeDefinitions.java
  elytron-oidc-client/src/test/java/org/wildfly/extension/elytron/oidc/OidcTestCase.java
  elytron-oidc-client/src/test/resources/org/wildfly/extension/elytron/oidc/oidc-expressions.xml
  legacy/keycloak/pom.xml
  legacy/opentracing-extension/src/main/java/org/wildfly/extension/microprofile/opentracing/TracerAttributes.java
  messaging-activemq/subsystem/src/main/java/org/wildfly/extension/messaging/activemq/ActiveMQServerControlHandler.java
  messaging-activemq/subsystem/src/main/java/org/wildfly/extension/messaging/activemq/ServerDefinition.java
  microprofile/health-smallrye/src/main/java/org/wildfly/extension/microprofile/health/MicroProfileHealthSubsystemDefinition.java
  observability/opentelemetry/src/main/java/org/wildfly/extension/opentelemetry/OpenTelemetrySubsystemDefinition.java
Labels: deps-ok

#16692 [WFLY-17841] Update documentation due to removal of javax.api and org…
  docs/src/main/asciidoc/_developer-guide/Implicit_module_dependencies_for_deployments.adoc
Labels: deps-ok

#16695 [WFLY-17846] Upgrade WildFly Core to 20.0.0.Final
  pom.xml
Labels: deps-ok

#16691 [WFLY-17673] Replace javax API module identifiers in DUPs with the ja…
  bean-validation/src/main/java/org/jboss/as/ee/beanvalidation/BeanValidationDeploymentDependenciesProcessor.java
  connector/src/main/java/org/jboss/as/connector/deployers/ra/processors/RarDependencyProcessor.java
  connector/src/main/java/org/jboss/as/connector/subsystems/resourceadapters/ResourceAdaptersRootResourceDefinition.java
  ee-security/src/main/java/org/wildfly/extension/eesecurity/EESecurityDependencyProcessor.java
  ee/src/main/java/org/jboss/as/ee/managedbean/processors/JavaEEDependencyProcessor.java
  ee/src/main/java/org/jboss/as/ee/subsystem/EeSubsystemRootResource.java
  jaxrs/src/main/java/org/jboss/as/jaxrs/JaxrsSubsystemDefinition.java
  jsf/subsystem/src/main/java/org/jboss/as/jsf/deployment/JSFModuleIdFactory.java
  jsf/subsystem/src/test/resources/modules/jakarta/faces/api/main/module.xml
  jsf/subsystem/src/test/resources/modules/jakarta/faces/api/myfaces/module.xml
  jsf/subsystem/src/test/resources/modules2/jakarta/faces/api/myfaces2/module.xml
  messaging-activemq/subsystem/src/main/java/org/wildfly/extension/messaging/activemq/deployment/MessagingDependencyProcessor.java
  microprofile/jwt-smallrye/src/main/java/org/wildfly/extension/microprofile/jwt/smallrye/JwtDependencyProcessor.java
  security/subsystem/src/main/java/org/jboss/as/security/SecuritySubsystemRootResourceDefinition.java
  transactions/src/main/java/org/jboss/as/txn/deployment/TransactionDependenciesProcessor.java
  undertow/src/main/java/org/wildfly/extension/undertow/deployment/UndertowDependencyProcessor.java
  webservices/server-integration/src/main/java/org/jboss/as/webservices/deployers/WSDependenciesProcessor.java
  weld/subsystem/src/main/java/org/jboss/as/weld/WeldResourceDefinition.java
  weld/subsystem/src/main/java/org/jboss/as/weld/deployment/processors/WeldDependencyProcessor.java
Labels: deps-ok

#16542 [WFLY-14307] Warning if wrong annotation is added to a Servlet
  undertow/src/main/java/org/wildfly/extension/undertow/deployment/WarAnnotationDeploymentProcessor.java
  undertow/src/main/java/org/wildfly/extension/undertow/logging/UndertowLogger.java
Labels: deps-ok

#16684 WFLY-17558 Upgrade to Hibernate ORM 6.2.0.Final
  pom.xml
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/jpa/hibernate/sessionfactorytest/SessionFactoryTestCase.java
Labels: deps-ok

#16696 [WFLY-17845] Upgrade nimbus-jose-jwt to 9.24.4 (CVE-2023-1370)
  pom.xml
Labels: deps-ok

#16693 WFLY-17835: Consolidate license resources
  ee-feature-pack/common/src/main/resources/content/docs/licenses/apache license 2.0.txt
  ee-feature-pack/common/src/main/resources/content/docs/licenses/common development and distribution license 1.1.txt
  ee-feature-pack/common/src/main/resources/content/docs/licenses/eclipse distribution license, version 1.0.txt
  ee-feature-pack/common/src/main/resources/content/docs/licenses/eclipse public license 1.0.txt
  ee-feature-pack/common/src/main/resources/content/docs/licenses/eclipse public license 2.0.txt
  ee-feature-pack/common/src/main/resources/content/docs/licenses/gnu lesser general public license v2.1 only.txt
  ee-feature-pack/common/src/main/resources/content/docs/licenses/gnu lesser general public license v2.1 or later.txt
  ee-feature-pack/common/src/main/resources/content/docs/licenses/licenses.css
  ee-feature-pack/common/src/main/resources/content/docs/licenses/licenses.xsl
  ee-feature-pack/galleon-common/src/main/resources/packages/docs.licenses.merge/content/docs/licenses/licenses.xsl
  ee-feature-pack/galleon-common/src/main/resources/packages/docs.licenses.merge/package.xml
  ee-feature-pack/galleon-common/src/main/resources/packages/docs.licenses.merge/pm/wildfly/merger.xsl
  ee-feature-pack/galleon-common/src/main/resources/packages/docs.licenses.merge/pm/wildfly/tasks.xml
  ee-feature-pack/galleon-feature-pack/pom.xml
  ee-feature-pack/galleon-shared/src/main/resources/content/docs/licenses/apache license 1.1.txt
  ee-feature-pack/galleon-shared/src/main/resources/content/docs/licenses/bsd 3-clause new or revised license.html
  ee-feature-pack/galleon-shared/src/main/resources/content/docs/licenses/bsd 3-clause no nuclear license.html
  ee-feature-pack/galleon-shared/src/main/resources/content/docs/licenses/common public license 1.0.txt
  ee-feature-pack/galleon-shared/src/main/resources/content/docs/licenses/creative commons attribution 2.5.html
  ee-feature-pack/galleon-shared/src/main/resources/content/docs/licenses/creative commons zero v1.0 universal.txt
  ee-feature-pack/galleon-shared/src/main/resources/content/docs/licenses/fsf all permissive license.html
  ee-feature-pack/galleon-shared/src/main/resources/content/docs/licenses/gnu general public license v2.0 only.html
  ee-feature-pack/galleon-shared/src/main/resources/content/docs/licenses/gnu general public license, version 2 with the classpath exception.txt
  ee-feature-pack/galleon-shared/src/main/resources/content/docs/licenses/gnu lesser general public license v3.0 only.txt
  ee-feature-pack/galleon-shared/src/main/resources/content/docs/licenses/gnu lesser general public license v3.0 or later.txt
  ee-feature-pack/galleon-shared/src/main/resources/content/docs/licenses/gnu library general public license v2 only.txt
  ee-feature-pack/galleon-shared/src/main/resources/content/docs/licenses/indiana university extreme lab software license 1.1.1.html
  ee-feature-pack/galleon-shared/src/main/resources/content/docs/licenses/licenses.xsl
  ee-feature-pack/galleon-shared/src/main/resources/content/docs/licenses/mit license.txt
  ee-feature-pack/galleon-shared/src/main/resources/content/docs/licenses/mozilla public license 1.1.txt
  ee-feature-pack/galleon-shared/src/main/resources/content/docs/licenses/mozilla public license 2.0.html
  ee-feature-pack/galleon-shared/src/main/resources/content/docs/licenses/plexus classworlds license.html
  ee-feature-pack/galleon-shared/src/main/resources/content/docs/licenses/public domain.txt
  ee-feature-pack/galleon-shared/src/main/resources/content/docs/licenses/the antlr 2.7.7 license.txt
  ee-feature-pack/galleon-shared/src/main/resources/content/docs/licenses/the bsd license.txt
  ee-feature-pack/galleon-shared/src/main/resources/content/docs/licenses/the jsoup mit license.html
  ee-feature-pack/galleon-shared/src/main/resources/packages/docs.licenses.merge/pm/wildfly/merger.xsl
  ee-feature-pack/galleon-shared/src/main/resources/packages/docs.licenses/content/docs/licenses/licenses.xsl
  ee-feature-pack/galleon-shared/src/main/resources/packages/docs.licenses/pm/wildfly/tasks.xml
  galleon-pack/galleon-feature-pack/pom.xml
  microprofile/galleon-common/pom.xml
  microprofile/galleon-common/src/main/resources/packages/docs.licenses.merge/package.xml
  microprofile/galleon-common/src/main/resources/packages/docs.licenses.merge/pm/wildfly/merger.xsl
  microprofile/galleon-common/src/main/resources/packages/docs.licenses.merge/pm/wildfly/tasks.xml
  microprofile/galleon-common/src/main/resources/packages/docs.licenses/content/docs/licenses/apache license 2.0.txt
  microprofile/galleon-common/src/main/resources/packages/docs.licenses/content/docs/licenses/licenses.xsl
Labels: deps-ok

#16694 [WFLY-17844] remove code that configures JBossWS-trust-sts in obsolet…
  testsuite/integration/ws/src/test/java/org/jboss/as/test/integration/ws/wsse/trust/WSTrustTestCaseSecuritySetupTask.java
Labels: deps-ok

#16510 [WFLY-17599] validate NamingBindingResourceDefinition.TYPE from allow…
  naming/src/main/java/org/jboss/as/naming/subsystem/NamingBindingResourceDefinition.java
Labels: deps-ok, 28.x

#16700 [WFLY-17858] IIOP: make sure registering attributes performs capabili…
  iiop-openjdk/src/main/java/org/wildfly/iiop/openjdk/IIOPRootDefinition.java
Labels: deps-ok

#16702 WFLY-17339 Restore tests previously @Ignored due to WFCORE-6145 and WFCORE-6146
  clustering/jgroups/extension/src/test/java/org/jboss/as/clustering/jgroups/ManagedSocketFactoryTestCase.java
Labels: deps-ok

#16538 [WFLY-17640]: Messaging ActiveMQ server cannot be created in management model because it requires dependency on legacy security domain.
  messaging-activemq/injection/src/main/java/org/wildfly/extension/messaging/activemq/logging/MessagingLogger.java
  messaging-activemq/subsystem/src/main/java/org/wildfly/extension/messaging/activemq/ActiveMQServerControlWriteHandler.java
  messaging-activemq/subsystem/src/main/java/org/wildfly/extension/messaging/activemq/SecurityDomainCheckHandler.java
  messaging-activemq/subsystem/src/main/java/org/wildfly/extension/messaging/activemq/ServerAdd.java
  messaging-activemq/subsystem/src/main/java/org/wildfly/extension/messaging/activemq/ServerDefinition.java
Labels: deps-ok, 28.x

#16704 [WFLY-17774] Update SmallRye OpenTelemetry to a version with Issue #223 fixed
  pom.xml
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/jaxrs/subresource/SubResourceTestCase.java
  testsuite/integration/basic/src/test/java/org/wildfly/test/integration/observability/opentelemetry/BaseOpenTelemetryTest.java
  testsuite/integration/basic/src/test/java/org/wildfly/test/integration/observability/opentelemetry/ContextPropagationTestCase.java
Labels: deps-ok, Critical, 28.x

#16711 [WFLY-17802] Upgrade ironjacamar to 3.0.2.Final
  pom.xml
Labels: deps-ok

#16699 Fix for WFLY-17854, WFLY-17855, Upgrade Galleon to 5.1.0.Final, Galleon Plugins to 6.4.0.Final and Bootable JAR to 9.0.0.Final
  pom.xml
Labels: deps-ok, 28.x

#16701 WFLY-17859 Channel add operations created by legacy parser can fail if run before jgroups subsystem is added
  clustering/infinispan/extension/src/main/java/org/jboss/as/clustering/infinispan/subsystem/InfinispanSubsystemXMLReader.java
  clustering/jgroups/extension/src/main/java/org/jboss/as/clustering/jgroups/subsystem/JGroupsSubsystemResourceDefinition.java
Labels: deps-ok

#16713 [WFLY-17856] The undertow-servlet module needs a dependency on the Elytron EE Jakarta Authorization module
  ee-feature-pack/galleon-shared/src/main/resources/modules/system/layers/base/org/wildfly/security/elytron-web/undertow-server-servlet/main/module.xml
Labels: deps-ok

#16706 WFLY-17843 Upgrade Infinispan to 14.0.8.Final
  boms/common-ee/pom.xml
  boms/standard-ee/pom.xml
  clustering/marshalling/protostream/src/main/java/org/wildfly/clustering/marshalling/protostream/AbstractProtoStreamWriter.java
  ee-feature-pack/common/pom.xml
  ee-feature-pack/common/src/main/resources/modules/system/layers/base/org/infinispan/hibernate-cache/main/module.xml
  jpa/hibernate6/src/main/java/org/jboss/as/jpa/hibernate/HibernateSecondLevelCache.java
  jpa/hibernate6/src/main/java/org/jboss/as/jpa/hibernate/service/WildFlyCustomRegionFactoryInitiator.java
  pom.xml
Labels: deps-changed

#16715 WFLY-17875 Channels added by ancient Infinispan schema can fail if no stack was defined
  clustering/infinispan/extension/src/main/java/org/jboss/as/clustering/infinispan/subsystem/InfinispanSubsystemXMLReader.java
  clustering/jgroups/extension/src/main/java/org/jboss/as/clustering/jgroups/subsystem/ChannelResourceDefinition.java
  clustering/jgroups/extension/src/main/java/org/jboss/as/clustering/jgroups/subsystem/JGroupsSubsystemResourceDefinition.java
Labels: deps-ok

#16717 [WFLY-17876] Have the MicroProfile LRA subsystems fully clean up afte…
  microprofile/lra/coordinator/src/main/java/org/wildfly/extension/microprofile/lra/coordinator/_private/MicroProfileLRACoordinatorLogger.java
  microprofile/lra/coordinator/src/main/java/org/wildfly/extension/microprofile/lra/coordinator/service/LRACoordinatorService.java
  microprofile/lra/participant/src/main/java/org/wildfly/extension/microprofile/lra/participant/MicroProfileLRAParticipantAdd.java
  microprofile/lra/participant/src/main/java/org/wildfly/extension/microprofile/lra/participant/MicroProfileLRAParticipantSubsystemDefinition.java
  microprofile/lra/participant/src/main/java/org/wildfly/extension/microprofile/lra/participant/_private/MicroProfileLRAParticipantLogger.java
  microprofile/lra/participant/src/main/java/org/wildfly/extension/microprofile/lra/participant/service/LRAParticipantService.java
  testsuite/integration/microprofile/src/test/java/org/wildfly/test/integration/microprofile/lra/participant/smoke/LRAParticipantSmokeTestCase.java
  testsuite/integration/microprofile/src/test/resources/logging.properties
Labels: deps-ok

#16720 [WFLY-17878] Replace org.wildfly by project.groupId where possible
  batch-jberet/pom.xml
  bean-validation/pom.xml
  clustering/pom.xml
  connector/pom.xml
  datasources-agroal/pom.xml
  dist/pom.xml
  ee-dist/pom.xml
  ee-security/pom.xml
  ee/pom.xml
  ejb3/pom.xml
  elytron-oidc-client/pom.xml
  health/pom.xml
  jaxrs/pom.xml
  jdr/pom.xml
  jpa/hibernate6/pom.xml
  jpa/subsystem/pom.xml
  legacy/jsr77/pom.xml
  legacy/messaging/pom.xml
  legacy/opentracing-extension/pom.xml
  legacy/web/pom.xml
  mail/pom.xml
  messaging-activemq/injection/pom.xml
  messaging-activemq/subsystem/pom.xml
  metrics/pom.xml
  microprofile/config-smallrye/pom.xml
  microprofile/health-smallrye/pom.xml
  microprofile/lra/coordinator/pom.xml
  microprofile/lra/participant/pom.xml
  microprofile/metrics-smallrye/pom.xml
  microprofile/reactive-messaging-smallrye/extension/pom.xml
  microprofile/reactive-streams-operators-smallrye/extension/pom.xml
  microprofile/telemetry-smallrye/extension/pom.xml
  mod_cluster/extension/pom.xml
  mod_cluster/undertow/pom.xml
  naming/pom.xml
  observability/micrometer/pom.xml
  observability/opentelemetry/pom.xml
  pojo/pom.xml
  preview/dist/pom.xml
  sar/pom.xml
  security/subsystem/pom.xml
  testsuite/shared/pom.xml
  undertow/pom.xml
  web-common/pom.xml
  webservices/server-integration/pom.xml
  weld/subsystem/pom.xml
Labels: deps-ok

#16716 WFLY-17874 Drop obsolete dependency on wildfly-clustering-infinispan-client-api from wildfly-clustering-web-hotrod
  clustering/web/hotrod/pom.xml
  ee-feature-pack/common/src/main/resources/modules/system/layers/base/org/wildfly/clustering/web/cache/main/module.xml
  ee-feature-pack/common/src/main/resources/modules/system/layers/base/org/wildfly/clustering/web/hotrod/main/module.xml
  ee-feature-pack/common/src/main/resources/modules/system/layers/base/org/wildfly/clustering/web/infinispan/main/module.xml
Labels: deps-ok

#16721 WFLY-17880 Upgrade SmallRye Fault Tolerance to 6.2.2
  pom.xml
Labels: deps-ok

#16710 [WFLY-17868] Replace uses of ServiceName SocketBinding.JBOSS_BINDING_…
  rts/src/main/java/org/wildfly/extension/rts/RTSSubsystemAdd.java
  rts/src/main/java/org/wildfly/extension/rts/RTSSubsystemDefinition.java
  rts/src/main/java/org/wildfly/extension/rts/service/AbstractRTSService.java
  rts/src/main/java/org/wildfly/extension/rts/service/CoordinatorService.java
  rts/src/main/java/org/wildfly/extension/rts/service/ParticipantService.java
  rts/src/main/java/org/wildfly/extension/rts/service/VolatileParticipantService.java
Labels: deps-ok

#16679 [WFLY-17739] Remove uses of deprecated AbstractRemoveStepHandler methods
  connector/src/main/java/org/jboss/as/connector/subsystems/datasources/DataSourceRemove.java
  ejb3/src/main/java/org/jboss/as/ejb3/subsystem/PassivationStoreRemove.java
  ejb3/src/main/java/org/jboss/as/ejb3/subsystem/PassivationStoreResourceDefinition.java
  ejb3/src/main/java/org/jboss/as/ejb3/subsystem/RemotingProfileResourceDefinition.java
  ejb3/src/main/java/org/jboss/as/ejb3/subsystem/StrictMaxPoolResourceDefinition.java
  messaging-activemq/subsystem/src/main/java/org/wildfly/extension/messaging/activemq/ServerRemove.java
  naming/src/main/java/org/jboss/as/naming/subsystem/RemoteNamingRemove.java
  security/subsystem/src/main/java/org/jboss/as/security/elytron/BasicResourceDefinition.java
  undertow/src/main/java/org/wildfly/extension/undertow/ApplicationSecurityDomainDefinition.java
Labels: deps-ok

#16725 WFLY-17843 Update caffeine to 3.1.6.
  pom.xml
Labels: deps-ok

#16727 WFLY-17884 Upgrade smallrye-open-api to 3.3.2
  pom.xml
Labels: deps-ok

#16709 [WFLY-17869] Replace uses of ServiceName SocketBinding.JBOSS_BINDING_…
  transactions/src/main/java/org/jboss/as/txn/service/CoreEnvironmentService.java
  transactions/src/main/java/org/jboss/as/txn/subsystem/TransactionSubsystemAdd.java
  transactions/src/main/java/org/jboss/as/txn/subsystem/TransactionSubsystemRootResourceDefinition.java
Labels: deps-ok

#16724 WFLY-17883 Drop unreferenced LegacyTimerManagementProviderFactory
  clustering/ejb/infinispan/pom.xml
  clustering/ejb/infinispan/src/main/java/org/wildfly/clustering/ejb/infinispan/timer/InfinispanLegacyTimerManagementProviderFactory.java
  clustering/ejb/spi/src/main/java/org/wildfly/clustering/ejb/timer/LegacyTimerManagementProviderFactory.java
  ee-feature-pack/common/src/main/resources/modules/system/layers/base/org/wildfly/clustering/ejb/infinispan/main/module.xml
Labels: deps-ok

#16734 [WFLY-17833] Make Angus Activation services visible to org.jboss.as.s…
  ee-feature-pack/common/src/main/resources/modules/system/layers/base/org/jboss/as/sar/main/module.xml
Labels: deps-ok

#16728 WFLY-17885 Remove the unused Hibernate 6.0 module
  ee-feature-pack/common/src/main/resources/modules/system/layers/base/org/hibernate/6.0/module.xml
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/deployment/moduleslisting/DeploymentModulesListTestCase.java
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/jpa/jarfile/persistence.xml
Labels: deps-ok

#16708 [WFLY-17867] Replace uses of ServiceName SocketBinding.JBOSS_BINDING_…
  ee-feature-pack/common/src/main/resources/modules/system/layers/base/org/wildfly/iiop-openjdk/main/module.xml
  iiop-openjdk/src/main/java/org/wildfly/iiop/openjdk/IIOPRootDefinition.java
  iiop-openjdk/src/main/java/org/wildfly/iiop/openjdk/IIOPSubsystemAdd.java
  iiop-openjdk/src/main/java/org/wildfly/iiop/openjdk/service/CorbaORBService.java
Labels: deps-ok

#16722 [WFLY-1766] Upgrade smallrye-jwt to 4.2.1 and add test for mp.jwt.verify.clock.skew property
  pom.xml
  testsuite/integration/microprofile/src/test/java/org/wildfly/test/integration/microprofile/jwt/ClockSkewTest.java
  testsuite/integration/microprofile/src/test/resources/jwt/microprofile-config-with-clock-skew.properties
Labels: deps-ok, 28.x

#16733 [WFLY-17894] Upgrade testcontainers to 1.18.0
  boms/standard-test/pom.xml
  pom.xml
Labels: deps-ok

#16731 [WFLY-17892] Upgrade wildfly-ee-9-deployment-transformer to 1.0.0.Final
  pom.xml
Labels: Blocker, deps-ok, 28.x

#16732 [WFLY-17886] IIOP: make sure that configuration of client security ty…
  iiop-openjdk/src/main/java/org/wildfly/iiop/openjdk/IIOPRootDefinition.java
  iiop-openjdk/src/main/java/org/wildfly/iiop/openjdk/IIOPSubsystemAdd.java
  iiop-openjdk/src/main/resources/org/wildfly/iiop/openjdk/LocalDescriptions.properties
Labels: deps-ok

#16726 [WFLY-17860]: Convert ServerAdd.InstallServerHandler to CapabilityServiceTarget.
  legacy/messaging/pom.xml
  messaging-activemq/subsystem/src/main/java/org/wildfly/extension/messaging/activemq/ActiveMQServerService.java
  messaging-activemq/subsystem/src/main/java/org/wildfly/extension/messaging/activemq/Capabilities.java
  messaging-activemq/subsystem/src/main/java/org/wildfly/extension/messaging/activemq/MessagingServices.java
  messaging-activemq/subsystem/src/main/java/org/wildfly/extension/messaging/activemq/MessagingSubsystemAdd.java
  messaging-activemq/subsystem/src/main/java/org/wildfly/extension/messaging/activemq/ServerAdd.java
  messaging-activemq/subsystem/src/main/java/org/wildfly/extension/messaging/activemq/jms/ExternalConnectionFactoryAdd.java
  messaging-activemq/subsystem/src/main/java/org/wildfly/extension/messaging/activemq/jms/ExternalPooledConnectionFactoryService.java
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/messaging/jms/external/ExternalMessagingDeploymentTestCase.java
Labels: deps-ok

#16735 WFLY-17895 Upgrade to Hibernate ORM 6.2.1.Final and enable SessionFactoryTestCase testInjectPUIntoHibernateSessionFactory
  pom.xml
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/jpa/hibernate/sessionfactorytest/SessionFactoryTestCase.java
Labels: deps-ok

#16738 WFLY-17901 Duplicated dependencies in module.xml files
  galleon-pack/common/src/main/resources/modules/system/layers/base/io/opentelemetry/exporter/main/module.xml
  microprofile/galleon-common/src/main/resources/modules/system/layers/base/org/jboss/narayana/rts/lra-coordinator/main/module.xml
Labels: deps-ok

#16739 [WFLY-17882] Replace uses of ServiceName virtualHostName with use of …
  rts/src/main/java/org/wildfly/extension/rts/RTSSubsystemAdd.java
Labels: deps-ok

#16730 [WFLY-17890] forces jacorb's migrate() op to use elytron security
  legacy/jacorb/src/main/java/org/jboss/as/jacorb/JacORBSubsystemConstants.java
  legacy/jacorb/src/main/java/org/jboss/as/jacorb/TransformUtils.java
Labels: deps-ok

#16280 WFLY-17288: deprecate driver-name attribute in JDBC driver definition…
  connector/src/main/java/org/jboss/as/connector/subsystems/datasources/Constants.java
  connector/src/main/java/org/jboss/as/connector/subsystems/datasources/DataSourcesExtension.java
  connector/src/main/java/org/jboss/as/connector/subsystems/datasources/DsParser.java
  connector/src/main/java/org/jboss/as/connector/subsystems/datasources/GetInstalledDriverOperationHandler.java
  connector/src/main/java/org/jboss/as/connector/subsystems/datasources/InstalledDriversListOperationHandler.java
  connector/src/main/java/org/jboss/as/connector/subsystems/datasources/JdbcDriverAdd.java
  connector/src/main/java/org/jboss/as/connector/subsystems/datasources/JdbcDriverDefinition.java
  connector/src/main/java/org/jboss/as/connector/subsystems/datasources/JdbcDriverRemove.java
  connector/src/main/resources/org/jboss/as/connector/subsystems/datasources/LocalDescriptions.properties
Labels: deps-ok, 28.x

#16742 [WFLY-17904] Upgrade the RESTEasy Tracing API to 2.0.1.Final.
  pom.xml
Labels: Blocker, deps-ok, 28.x

#16737 [WFLY-17897] Ensure wildscribe content is generated for newer subsyst…
  docs/pom.xml
Labels: deps-ok, Critical, 28.x

#16736 WFLY-17898 Deploy fails when legacy SSO is configured
  clustering/common/src/main/java/org/jboss/as/clustering/controller/AdminOnlyOperationStepHandlerTransformer.java
  clustering/common/src/main/java/org/jboss/as/clustering/logging/ClusteringLogger.java
  undertow/src/main/java/org/wildfly/extension/undertow/HostAdd.java
  undertow/src/main/java/org/wildfly/extension/undertow/HostSingleSignOnDefinition.java
  undertow/src/main/java/org/wildfly/extension/undertow/SingleSignOnService.java
  undertow/src/main/java/org/wildfly/extension/undertow/UndertowService.java
  undertow/src/main/java/org/wildfly/extension/undertow/deployment/UndertowDeploymentProcessor.java
  undertow/src/test/java/org/wildfly/extension/undertow/AbstractUndertowSubsystemTestCase.java
  undertow/src/test/resources/org/wildfly/extension/undertow/undertow-14.0.xml
Labels: Blocker, deps-ok, 28.x

#16698 [WFLY-17852] Annotations in resource adapter module are not processed
  connector/src/main/java/org/jboss/as/connector/deployers/ra/processors/ParsedRaDeploymentProcessor.java
  connector/src/main/java/org/jboss/as/connector/subsystems/resourceadapters/RaOperationUtil.java
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/jca/anno/RaAnnoEmptyRaXmlFromModuleTestCase.java
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/jca/anno/ramodule.xml
Labels: deps-ok

#16740 [WFLY-17903] Upgrade WildFly Core to 20.0.1.Final
  pom.xml
Labels: deps-ok, Critical, 28.x

#16744 [WFLY-17890] JacORB migration: add security migration to Elytron warning
  legacy/jacorb/src/main/java/org/jboss/as/jacorb/TransformUtils.java
  legacy/jacorb/src/main/java/org/jboss/as/jacorb/logging/JacORBLogger.java
Labels: deps-ok, 28.x

#16746 [WFLY-17906] Remove invalid dependency io.opentelemetry:opentelemetry-sdk-extension
  boms/common-expansion/pom.xml
  galleon-pack/common/src/main/resources/license/licenses.xml
Labels: deps-ok

#16685 [WFLY-17810] Add more testing for the Micrometer extension
  observability/micrometer/src/main/java/org/wildfly/extension/micrometer/MicrometerSubsystemSchema.java
  observability/micrometer/src/main/java/org/wildfly/extension/micrometer/WildFlyMicrometerConfig.java
  observability/micrometer/src/main/java/org/wildfly/extension/micrometer/jmx/JmxMicrometerCollector.java
  observability/micrometer/src/test/java/org/wildfly/extension/micrometer/SubsystemParsingTestCase.java
  observability/micrometer/src/test/resources/org/wildfly/extension/micrometer/micrometer.xml
  testsuite/integration/microprofile/pom.xml
  testsuite/integration/microprofile/src/test/java/org/wildfly/test/integration/observability/micrometer/BasicMicrometerTestCase.java
  testsuite/integration/microprofile/src/test/java/org/wildfly/test/integration/observability/micrometer/MicrometerOtelIntegrationTestCase.java
  testsuite/integration/microprofile/src/test/java/org/wildfly/test/integration/observability/micrometer/MicrometerSetupTask.java
  testsuite/integration/microprofile/src/test/java/org/wildfly/test/integration/observability/micrometer/OpenTelemetryCollectorContainer.java
  testsuite/integration/microprofile/src/test/resources/org/wildfly/test/integration/observability/micrometer/otel-collector-config.yaml
Labels: deps-ok

#16705 [WFLY-17781] Ensure a virtual SecurityDomain is created if necessary when an EJB references a virtual security domain
  docs/src/main/asciidoc/_admin-guide/subsystem-configuration/Elytron_OIDC_Client.adoc
  ejb3/src/main/java/org/jboss/as/ejb3/deployment/processors/EJBDefaultSecurityDomainProcessor.java
  elytron-oidc-client/src/main/java/org/wildfly/extension/elytron/oidc/ElytronOidcSubsystemAdd.java
  elytron-oidc-client/src/main/java/org/wildfly/extension/elytron/oidc/ElytronOidcSubsystemDefinition.java
  elytron-oidc-client/src/main/java/org/wildfly/extension/elytron/oidc/OidcVirtualSecurityDomainCreationService.java
  elytron-oidc-client/src/main/java/org/wildfly/extension/elytron/oidc/VirtualHttpServerMechanismFactoryProcessor.java
  testsuite/integration/elytron-oidc-client/src/test/java/org/wildfly/test/integration/elytron/oidc/client/propagation/OidcIdentityPropagationTestCase.java
  testsuite/integration/elytron-oidc-client/src/test/java/org/wildfly/test/integration/elytron/oidc/client/propagation/annotation/ComplexServletRemote.java
  testsuite/integration/elytron-oidc-client/src/test/java/org/wildfly/test/integration/elytron/oidc/client/propagation/annotation/EntryBeanRemote.java
  testsuite/integration/elytron-oidc-client/src/test/java/org/wildfly/test/integration/elytron/oidc/client/propagation/annotation/EntryRemote.java
  testsuite/integration/elytron-oidc-client/src/test/java/org/wildfly/test/integration/elytron/oidc/client/propagation/annotation/ManagementBeanRemote.java
  testsuite/integration/elytron-oidc-client/src/test/java/org/wildfly/test/integration/elytron/oidc/client/propagation/annotation/ServletOnlyRemote.java
  testsuite/integration/elytron-oidc-client/src/test/java/org/wildfly/test/integration/elytron/oidc/client/propagation/annotation/SimpleServletRemote.java
  testsuite/integration/elytron-oidc-client/src/test/java/org/wildfly/test/integration/elytron/oidc/client/propagation/annotation/WhoAmIBeanRemote.java
  testsuite/integration/elytron-oidc-client/src/test/java/org/wildfly/test/integration/elytron/oidc/client/propagation/annotation/WhoAmIRemote.java
Labels: core-upgrade-needed, 28.x

#16748 [WFLY-17909] Eliminating deprecated ibm.jdk module usages
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/deployment/moduleslisting/DeploymentModulesListTestCase.java
Labels: deps-ok

#16751 WFLY-17911 Upgrade JGroups to 5.2.14.Final
  pom.xml
Labels: deps-ok, 28.x

#16752 [WFLY-17377] Upgrade MP JWT to 2.1
  pom.xml
Labels: Blocker, deps-ok, 28.x

#16632 WFLY-13978 Update YAML doc for system properties and configuration customization
  docs/src/main/asciidoc/_admin-guide/management-tasks/YAML_Configuration_file.adoc
Labels: deps-ok, 28.x

#16756 [WFLY-16975] Removing TokenUtilsEncryptTest workaround after upgrade to MP JWT 2.1
  testsuite/integration/microprofile-tck/jwt/pom.xml
Labels: deps-ok, 29.Alpha1

#16767 Add a shared WildFly Build workflow. This workflow will upload a Mave…
  .github/workflows/shared-wildfly-build.yml
Labels: deps-ok

#16769 [WFLY-17939] Update HostExcludesTestCase configuration to work with WF29
  testsuite/domain/src/test/java/org/jboss/as/test/integration/domain/HostExcludesTestCase.java
Labels: deps-ok

#16707 [WFLY-17556] Revert "[WFLY-15780] Mechanism to skip precalculated Jan…
  microprofile/galleon-common/src/main/resources/modules/system/layers/base/org/wildfly/extension/microprofile/reactive-messaging-smallrye/main/module.xml
  microprofile/reactive-messaging-smallrye/extension/pom.xml
  microprofile/reactive-messaging-smallrye/extension/src/main/java/org/wildfly/extension/microprofile/reactive/messaging/deployment/ReactiveMessagingDependencyProcessor.java
  weld/common/src/main/java/org/jboss/as/weld/WeldCapability.java
  weld/subsystem/src/main/java/org/jboss/as/weld/WeldCapabilityImpl.java
  weld/subsystem/src/main/java/org/jboss/as/weld/deployment/WeldAttachments.java
  weld/subsystem/src/main/java/org/jboss/as/weld/deployment/processors/ExternalBeanArchiveProcessor.java
Labels: deps-ok

#16764 [WFLY-17936] Upgrade to SmallRye Reactive Messaging 4.5.0
  pom.xml
Labels: ready-for-merge, deps-ok, 29.Alpha1

#16770 [WFLY-17940] Remove batch subsystem use of RequestController.SERVICE_…
  batch-jberet/src/main/java/org/wildfly/extension/batch/jberet/BatchServiceNames.java
  batch-jberet/src/main/java/org/wildfly/extension/batch/jberet/BatchSubsystemDefinition.java
  batch-jberet/src/main/java/org/wildfly/extension/batch/jberet/deployment/BatchEnvironmentProcessor.java
Labels: ready-for-merge, deps-ok, 29.Alpha1

#16771 [WFLY-17943] Use SystemExiter.abort instead of deprecated exit variant
  appclient/src/main/java/org/jboss/as/appclient/subsystem/Main.java
Labels: ready-for-merge, deps-ok, 29.Alpha1

#16773 [WFLY-17941] Remove use of deprecated SimpleOperationDefinition APIs
  jpa/subsystem/src/main/java/org/jboss/as/jpa/management/ManagementResourceDefinition.java
  messaging-activemq/subsystem/src/main/java/org/wildfly/extension/messaging/activemq/jms/AbstractUpdateJndiHandler.java
  transactions/src/main/java/org/jboss/as/txn/subsystem/LogStoreTransactionDefinition.java
  transactions/src/main/java/org/jboss/as/txn/subsystem/LogStoreTransactionParticipantDefinition.java
Labels: ready-for-merge, deps-ok, 29.Alpha1

#16774 [WFLY-17942] Remove use of deprecated SimpleResourceDefinition APIs
  ejb3/src/main/java/org/jboss/as/ejb3/subsystem/LegacyCacheFactoryResourceDefinition.java
  ejb3/src/main/java/org/jboss/as/ejb3/subsystem/LegacyPassivationStoreResourceDefinition.java
  ejb3/src/main/java/org/jboss/as/ejb3/subsystem/deployment/TimerResourceDefinition.java
  ejb3/src/main/java/org/jboss/as/ejb3/subsystem/deployment/TimerServiceResourceDefinition.java
  legacy/jacorb/src/main/java/org/jboss/as/jacorb/JacORBSubsystemResource.java
  transactions/src/main/java/org/jboss/as/txn/subsystem/LogStoreDefinition.java
Labels: ready-for-merge, deps-ok, 29.Alpha1

#16776 [WFLY-17951] Upgrade the wildfly-maven-plugin to 4.1.0.Fina.
  pom.xml
Labels: ready-for-merge, deps-ok, 29.Alpha1

#16778 [WFLY-17953] Migrate to using the Shrinkwrap Resolvers for resolving …
  boms/standard-test/pom.xml
  pom.xml
  testsuite/integration/basic/pom.xml
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/jsf/version/JSFDeploymentProcessorTestCase.java
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/xerces/unit/XercesUsageTestCase.java
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/xerces/ws/unit/XercesUsageInWebServiceTestCase.java
  testsuite/integration/microprofile-tck/lra/pom.xml
Labels: deps-ok, 29.Alpha1

#16779 [WFLY-17907] Increase test timeout
  testsuite/integration/microprofile/src/test/java/org/wildfly/test/integration/microprofile/reactive/RunKafkaSetupTask.java
  testsuite/integration/microprofile/src/test/java/org/wildfly/test/integration/microprofile/reactive/messaging/kafka/api/ReactiveMessagingKafkaUserApiTestCase.java
  testsuite/integration/microprofile/src/test/java/org/wildfly/test/integration/microprofile/reactive/messaging/kafka/ssl/RunKafkaWithSslSetupTask.java
  testsuite/integration/microprofile/src/test/java/org/wildfly/test/integration/microprofile/reactive/messaging/kafka/tx/ReactiveMessagingKafkaTestCase.java
Labels: deps-ok, 29.Alpha1

#16763 [WFLY-17790] removed org.jboss.as.test.integration.logging.syslogserv…
  testsuite/shared/pom.xml
  testsuite/shared/src/main/java/org/jboss/as/test/integration/logging/syslogserver/BlockedSyslogServerEventHandler.java
  testsuite/shared/src/main/java/org/jboss/as/test/integration/logging/syslogserver/Rfc5424SyslogEvent.java
  testsuite/shared/src/main/java/org/jboss/as/test/integration/logging/syslogserver/TCPSyslogServer.java
  testsuite/shared/src/main/java/org/jboss/as/test/integration/logging/syslogserver/TCPSyslogServerConfig.java
  testsuite/shared/src/main/java/org/jboss/as/test/integration/logging/syslogserver/TCPSyslogSocketHandler.java
  testsuite/shared/src/main/java/org/jboss/as/test/integration/logging/syslogserver/TLSSyslogServer.java
  testsuite/shared/src/main/java/org/jboss/as/test/integration/logging/syslogserver/TLSSyslogServerConfig.java
  testsuite/shared/src/main/java/org/jboss/as/test/integration/logging/syslogserver/UDPSyslogServer.java
  testsuite/shared/src/main/java/org/jboss/as/test/integration/logging/syslogserver/UDPSyslogServerConfig.java
Labels: ready-for-merge, deps-ok, 29.Alpha1

#16747 [WFLY-17908] Removing JDK 8 specific excludes from maven enforcer plugin configurations
  ee-feature-pack/common/pom.xml
  ee-feature-pack/ee-10-api/pom.xml
  ee-feature-pack/galleon-feature-pack/pom.xml
  ee-feature-pack/pruned/pom.xml
  galleon-pack/common/pom.xml
  galleon-pack/galleon-feature-pack/pom.xml
  microprofile/galleon-common/pom.xml
  preview/common-microprofile/pom.xml
  preview/common/pom.xml
  preview/feature-pack/pom.xml
  preview/galleon-content-microprofile/pom.xml
  preview/galleon-content/pom.xml
  testsuite/test-feature-pack-preview/pom.xml
  testsuite/test-feature-pack/pom.xml
Labels: deps-ok, 29.Alpha1

#16791 [WFLY-17955]: Upgrade to Smallrye opentelemetry 2.3.2.
  pom.xml
Labels: deps-ok, 29.Alpha1

#16793 [WFLY-17955] [28.x] Upgrade to Smallrye opentelemetry 2.3.2
  pom.xml
Labels: 28.x

#16772 [WFLY-17945] Replace uses of ModelController.createClient with ModelControllerClientFactory
  appclient/src/main/java/org/jboss/as/appclient/deployment/ApplicationClientStartProcessor.java
  appclient/src/main/java/org/jboss/as/appclient/service/ApplicationClientDeploymentService.java
  appclient/src/main/java/org/jboss/as/appclient/service/ApplicationClientStartService.java
  appclient/src/main/java/org/jboss/as/appclient/subsystem/AppClientSubsystemAdd.java
  appclient/src/main/java/org/jboss/as/appclient/subsystem/AppClientSubsystemResourceDefinition.java
  jdr/src/main/java/org/jboss/as/jdr/CommandLineMain.java
  jdr/src/main/java/org/jboss/as/jdr/JdrReportExtension.java
  jdr/src/main/java/org/jboss/as/jdr/JdrReportRequestHandler.java
  jdr/src/main/java/org/jboss/as/jdr/JdrReportService.java
  jdr/src/main/java/org/jboss/as/jdr/JdrReportSubsystemAdd.java
  jdr/src/main/java/org/jboss/as/jdr/JdrReportSubsystemDefinition.java
  jdr/src/main/java/org/jboss/as/jdr/JdrReportSubsystemRemove.java
  jdr/src/test/java/org/jboss/as/jdr/JdrSubsystemTestCase.java
Labels: deps-ok, 29.Alpha1

#16785 [WFLY-17960] Do not register the org.jboss.resteasy.plugins.server.se…
  microprofile/lra/coordinator/src/main/java/org/wildfly/extension/microprofile/lra/coordinator/service/LRACoordinatorService.java
  microprofile/lra/participant/src/main/java/org/wildfly/extension/microprofile/lra/participant/service/LRAParticipantService.java
Labels: 28.x

#16797 WFLY-17914 Upgrade to Hibernate 6.2.2.final release that maps Character[]/Byte[] to SQL Array by default unless DB doesn't allow
  jpa/hibernate6/src/main/java/org/jboss/as/jpa/hibernate/HibernatePersistenceProviderAdaptor.java
  pom.xml
Labels: ready-for-merge, Blocker, deps-ok, 29.Alpha1

#16794 WFLY-17970 Adjust MP certification script to mention selected MP spec…
  pom.xml
  testsuite/integration/microprofile-tck/certification/microprofile-certification.sh
  testsuite/integration/microprofile-tck/pom.xml
Labels: ready-for-merge, deps-ok, 29.Alpha1

#16800 WFLY-12631 Server doesn't start when DNS_PING is configured (REVISED)
  clustering/jgroups/extension/src/main/java/org/jboss/as/clustering/jgroups/JChannelFactory.java
  ee-feature-pack/common/src/main/resources/modules/system/layers/base/org/jgroups/main/module.xml
  ee-feature-pack/galleon-shared/src/main/resources/modules/system/layers/base/org/wildfly/clustering/service/main/module.xml
Labels: deps-ok

#16782 WFLY-17958 Persistence container bytecode enhancement should be enabled by default
  jpa/subsystem/src/main/java/org/jboss/as/jpa/config/Configuration.java
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/jpa/hibernate/classfiletransformertest/ClassFileTransformerTestCase.java
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/jpa/resourcelocal/persistence.xml
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/jpa/webnontxem/persistence.xml
Labels: deps-ok, 29.Alpha1

#16795 [WFLY-17972] Replace use of MountHandle constructor with MountHandle.…
  appclient/src/main/java/org/jboss/as/appclient/deployment/ApplicationClientStructureProcessor.java
  connector/src/main/java/org/jboss/as/connector/deployers/ra/processors/RaStructureProcessor.java
  connector/src/main/java/org/jboss/as/connector/subsystems/resourceadapters/RaOperationUtil.java
  ee/src/main/java/org/jboss/as/ee/structure/EarStructureProcessor.java
  jaxrs/src/main/java/org/jboss/as/jaxrs/deployment/JaxrsSpringProcessor.java
  sar/src/main/java/org/jboss/as/service/SarStructureProcessor.java
  undertow/src/main/java/org/wildfly/extension/undertow/deployment/WarStructureDeploymentProcessor.java
Labels: deps-ok, 29.Alpha1

#16796 [WFLY-17973] Clean up appclient Main
  appclient/src/main/java/org/jboss/as/appclient/subsystem/Main.java
Labels: deps-ok, 29.Alpha1

#16760 [WFLY-15358] Refactor PolicyContextTestCase so it tests access to HttpServletRequest in Servlet and EJB containers.
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/security/jacc/context/PolicyContextTestBean.java
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/security/jacc/context/PolicyContextTestCase.java
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/security/jacc/context/PolicyContextTestServlet.java
Labels: deps-ok, 29.Alpha1
