Repository wildfly/wildfly, pull requests merged in 2023-11, with the labels that each got.

#17357 [WFLY-18707] Upgrade WildFly Core to 23.0.0.Beta1
  pom.xml
Labels: deps-changed

#17310 [WFLY-18663] Fix i18n of exception messages in sar
  sar/src/main/java/org/jboss/as/service/PropertySupplier.java
  sar/src/main/java/org/jboss/as/service/ValueFactorySupplier.java
  sar/src/main/java/org/jboss/as/service/logging/SarLogger.java
Labels: deps-ok

#17340 [WFLY-18691] Add documentation for adding integrity checking for an existing filesystem realm to wildfly docs
  docs/src/main/asciidoc/_elytron/components/Filesystem_Security_Realm.adoc
Labels: deps-ok

#17266 [WFLY-14769] Access checking for txn namespace lookup
  ejb3/pom.xml
  ejb3/src/main/java/org/jboss/as/ejb3/subsystem/EJB3SubsystemAdd.java
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/ejb/transaction/txnaccess/BMTSLSB.java
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/ejb/transaction/txnaccess/CMTSLSB.java
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/ejb/transaction/txnaccess/TransactionNamespaceAccessTestCase.java
Labels: deps-ok, 31.x

#17338 Fix for WFLY-18687, Some add-ons in Galleon layer metadata are missing a description
  ee-feature-pack/galleon-shared/src/main/resources/layers/standalone/core-tools/layer-spec.xml
  ee-feature-pack/galleon-shared/src/main/resources/layers/standalone/ejb-http-invoker/layer-spec.xml
  ee-feature-pack/galleon-shared/src/main/resources/layers/standalone/embedded-activemq/layer-spec.xml
  ee-feature-pack/galleon-shared/src/main/resources/layers/standalone/h2-datasource/layer-spec.xml
  ee-feature-pack/galleon-shared/src/main/resources/layers/standalone/h2-default-datasource/layer-spec.xml
  ee-feature-pack/galleon-shared/src/main/resources/layers/standalone/health/layer-spec.xml
  ee-feature-pack/galleon-shared/src/main/resources/layers/standalone/iiop-openjdk/layer-spec.xml
  ee-feature-pack/galleon-shared/src/main/resources/layers/standalone/jdr/layer-spec.xml
  ee-feature-pack/galleon-shared/src/main/resources/layers/standalone/jgroups-aws/layer-spec.xml
  ee-feature-pack/galleon-shared/src/main/resources/layers/standalone/metrics/layer-spec.xml
  ee-feature-pack/galleon-shared/src/main/resources/layers/standalone/mod_cluster/layer-spec.xml
  ee-feature-pack/galleon-shared/src/main/resources/layers/standalone/remote-activemq/layer-spec.xml
  ee-feature-pack/galleon-shared/src/main/resources/layers/standalone/undertow-https/layer-spec.xml
  ee-feature-pack/galleon-shared/src/main/resources/layers/standalone/undertow-load-balancer/layer-spec.xml
  galleon-pack/galleon-shared/src/main/resources/layers/standalone/micrometer/layer-spec.xml
  galleon-pack/galleon-shared/src/main/resources/layers/standalone/microprofile-lra-coordinator/layer-spec.xml
  galleon-pack/galleon-shared/src/main/resources/layers/standalone/microprofile-openapi/layer-spec.xml
  galleon-pack/galleon-shared/src/main/resources/layers/standalone/microprofile-reactive-messaging-kafka/layer-spec.xml
  galleon-pack/galleon-shared/src/main/resources/layers/standalone/microprofile-telemetry/layer-spec.xml
  galleon-pack/galleon-shared/src/main/resources/layers/standalone/opentelemetry/layer-spec.xml
Labels: deps-ok

#16826 [WFLY-18009] Add jars needed for compression of Kafka
  boms/common-expansion/pom.xml
  galleon-pack/galleon-shared/pom.xml
  galleon-pack/galleon-shared/src/main/resources/license/licenses.xml
  galleon-pack/galleon-shared/src/main/resources/modules/system/layers/base/com/github/luben/zstd-jni/main/module.xml
  galleon-pack/galleon-shared/src/main/resources/modules/system/layers/base/org/apache/kafka/client/main/module.xml
  galleon-pack/galleon-shared/src/main/resources/modules/system/layers/base/org/lz4/lz4-java/main/module.xml
  galleon-pack/galleon-shared/src/main/resources/modules/system/layers/base/org/xerial/snappy/snappy-java/main/module.xml
  pom.xml
  testsuite/integration/microprofile/pom.xml
  testsuite/integration/microprofile/src/test/java/org/wildfly/test/integration/microprofile/reactive/messaging/kafka/compression/CompressionMessagingBean.java
  testsuite/integration/microprofile/src/test/java/org/wildfly/test/integration/microprofile/reactive/messaging/kafka/compression/ReactiveMessagingKafkaCompressionTestCase.java
  testsuite/integration/microprofile/src/test/java/org/wildfly/test/integration/microprofile/reactive/messaging/kafka/compression/microprofile-config.properties
Labels: deps-changed

#17366 [WFLY-18713] Upgrade RESTEasy to 6.2.6.Final.
  pom.xml
Labels: deps-ok

#17367 [30.x] [WFLY-18713] Upgrade RESTEasy to 6.2.6.Final.
  pom.xml
Labels: 30.x

#17368 [WFLY-18714] Upgrade Galleon to 5.2.2.Final and Galleon plugins to 6.…
  pom.xml
Labels: deps-ok

#17369 WFLY-18630 Upgrade Infinispan to 14.0.20.Final
  clustering/infinispan/extension/src/main/java/org/jboss/as/clustering/infinispan/client/ManagedRemoteCacheContainer.java
  pom.xml
  testsuite/integration/clustering/src/test/java/org/jboss/as/test/clustering/cluster/jsf/AbstractJSFFailoverTestCase.java
Labels: deps-ok

#17379 [WFLY-18704]: Upgrade Apache Artemis to 2.31.2
  pom.xml
Labels: 30.x

#17148 [WFLY-18332] Update LayersTestBase and LayersTestCase(s)
  jpa/subsystem/src/main/java/org/jboss/as/jpa/subsystem/JPADefinition.java
  testsuite/layers-expansion/pom.xml
  testsuite/layers-expansion/src/test/java/org/jboss/as/test/layers/expansion/LayersTestCase.java
  testsuite/layers/pom.xml
  testsuite/layers/src/test/java/org/jboss/as/test/layers/base/LayersTestCase.java
  testsuite/shared/src/main/java/org/jboss/as/test/shared/LayersTestBase.java
Labels: deps-ok, 31.x

#17374 [WFLY-18533] Do not register the resteasy-validator-provider on deplo…
  ee-feature-pack/galleon-shared/src/main/resources/modules/system/layers/base/org/jboss/resteasy/resteasy-core/main/module.xml
  jaxrs/pom.xml
  jaxrs/src/main/java/org/jboss/as/jaxrs/deployment/JaxrsDependencyProcessor.java
Labels: deps-ok

#17377 [30.x] [WFLY-18533] Do not register the resteasy-validator-provider on deplo…
  ee-feature-pack/galleon-shared/src/main/resources/modules/system/layers/base/org/jboss/resteasy/resteasy-core/main/module.xml
  jaxrs/pom.xml
  jaxrs/src/main/java/org/jboss/as/jaxrs/deployment/JaxrsDependencyProcessor.java
Labels: 30.x

#17381 [WFLY-18725] Upgrading WildFly Http Client to 2.0.6.Final
  pom.xml
Labels: deps-ok

#17383 [WFLY-18725] Upgrading WildFly Http Client to 2.0.6.Final
  ee-feature-pack/galleon-shared/src/main/resources/modules/system/layers/base/org/wildfly/http-client/naming/main/module.xml
  pom.xml
Labels: 30.x

#17343 [WFLY-18693] Upgrade to SmallRye Reactive Messaging 4.11.0
  pom.xml
Labels: deps-ok

#17278 WFLY-17755: clean up license config files
  ee-feature-pack/galleon-shared/src/main/resources/license/licenses.xml
  galleon-pack/galleon-shared/src/main/resources/license/licenses.xml
  pom.xml
  preview/galleon-local/src/main/resources/license/licenses.xml
Labels: deps-ok

#17390 WFLY-18727 ATTRIBUTE granularity distributed sessions should always replicate on setAttribute(...)
  clustering/web/cache/src/main/java/org/wildfly/clustering/web/cache/session/attributes/fine/FineSessionAttributes.java
Labels: 30.x

#17384 WFLY-18630 Upgrade Infinispan to 14.0.20.Final
  clustering/infinispan/extension/src/main/java/org/jboss/as/clustering/infinispan/client/ManagedRemoteCacheContainer.java
  pom.xml
  testsuite/integration/clustering/src/test/java/org/jboss/as/test/clustering/cluster/jsf/AbstractJSFFailoverTestCase.java
Labels: 30.x

#17375 [WFLY-18448] Update SmallRye OpenTelemetry to 2.5.1
  boms/common-expansion/pom.xml
  ee-feature-pack/galleon-shared/src/main/resources/modules/system/layers/base/org/jboss/resteasy/resteasy-core-spi/main/module.xml
  galleon-pack/galleon-shared/pom.xml
  galleon-pack/galleon-shared/src/main/resources/modules/system/layers/base/io/opentelemetry/api/main/module.xml
  galleon-pack/galleon-shared/src/main/resources/modules/system/layers/base/io/opentelemetry/exporter/main/module.xml
  galleon-pack/galleon-shared/src/main/resources/modules/system/layers/base/io/opentelemetry/otlp/main/module.xml
  galleon-pack/galleon-shared/src/main/resources/modules/system/layers/base/io/smallrye/opentelemetry/main/module.xml
  galleon-pack/layer-metadata-tests/pom.xml
  microprofile/telemetry-smallrye/cdi-provider/pom.xml
  microprofile/telemetry-smallrye/extension/pom.xml
  observability/opentelemetry-api/pom.xml
  observability/opentelemetry/pom.xml
  pom.xml
  testsuite/integration/microprofile-tck/telemetry/pom.xml
  testsuite/integration/microprofile-tck/telemetry/src/test/java/io/smallrye/opentelemetry/arquillian/DeploymentProcessor.java
  testsuite/integration/microprofile-tck/telemetry/src/test/resources/tck-suite.xml
Labels: deps-changed

#17400 WFLY-18740 On cache writes, Infinispan store=hotrod throws ISE: Only byte[] instances are supported currently
  clustering/infinispan/extension/src/main/java/org/jboss/as/clustering/infinispan/persistence/hotrod/HotRodStore.java
Labels: 30.x

#17398 [WFLY-18738] Upgrade to Mojarra 4.0.5
  pom.xml
Labels: deps-ok

#17393 [WFLY-18732] Upgrade SmallRye Config to 3.4.3
  galleon-pack/galleon-shared/src/main/resources/modules/system/layers/base/org/wildfly/reactive/messaging/kafka/main/module.xml
  microprofile/reactive-messaging-smallrye/kafka/pom.xml
  microprofile/reactive-messaging-smallrye/kafka/src/main/java/org/wildfly/microprofile/reactive/messaging/config/kafka/ssl/context/ReactiveMessagingSslConfigProcessor.java
  pom.xml
Labels: deps-ok

#17423 [WFLY-18767] Upgrade Byteman to 4.0.22
  pom.xml
Labels: deps-ok

#17418 WFLY-18760 Upgrade smallrye-open-api to 3.7.0
  pom.xml
Labels: deps-ok

#17429 [WFLY-18771] Remove libthrift from dependencyManagement
  boms/common-expansion/pom.xml
  pom.xml
Labels: deps-ok

#17442 WFLY-18782 wildfly-model-test & commons-text should only be present in test scope
  testsuite/integration/pom.xml
Labels: deps-ok

#17436 [WFLY-18759] Move MicroProfile tck artifacts from boms/common-expansion to boms/standard-test-expansion
  boms/common-expansion/pom.xml
  boms/standard-test-expansion/pom.xml
Labels: deps-ok

#17431 WFLY-18774 Upgrade Infinispan to 14.0.21.Final
  clustering/infinispan/extension/src/main/java/org/jboss/as/clustering/infinispan/subsystem/ThreadPoolServiceConfigurator.java
  pom.xml
Labels: deps-ok

#17376 [WFLY-18295] Update the documentation of differences between standard…
  docs/src/main/asciidoc/WildFly_and_WildFly_Preview.adoc
Labels: Blocker

#17141 [WFLY-18406] Upgrade ironjacamar to 3.0.6.Final
  connector/src/main/java/org/jboss/as/connector/services/workmanager/NamedDistributedWorkManager.java
  connector/src/main/java/org/jboss/as/connector/services/workmanager/NamedWorkManager.java
  connector/src/main/java/org/jboss/as/connector/services/workmanager/StatisticsExecutorImpl.java
  connector/src/main/java/org/jboss/as/connector/services/workmanager/WildflyWorkWrapper.java
  pom.xml
Labels: deps-ok

#17445 [WFLY-18499] adds resteasy mp client useful artifacts to WildFly BOMs
  boms/user/microprofile/pom.xml
Labels: deps-ok

#17437 [WFLY-18779] Upgrade WildFly Core to 23.0.0.Beta2
  pom.xml
Labels: deps-ok
