Repository wildfly/wildfly, pull requests merged in 2023-12, with the labels that each got.

#17460 [WFLY-18808] Remove uses of deprecated ModuleSpecification API
  appclient/src/main/java/org/jboss/as/appclient/deployment/ApplicationClientDependencyProcessor.java
  webservices/server-integration/src/main/java/org/jboss/as/webservices/deployers/WSClassVerificationProcessor.java
  weld/subsystem/src/main/java/org/jboss/as/weld/deployment/processors/WeldDeploymentProcessor.java
Labels: ready-for-merge

#17477 [WFLY-18836] Upgrade WildFly Core to 23.0.0.Beta3
  pom.xml
Labels: deps-ok

#17476 [WFLY-18833] Upgrade ironjacamar to 3.0.7.Final
  pom.xml
Labels: deps-ok

#17485 [WFLY-18845] Upgrade wildfly-transaction-client to 3.0.3.Final
  pom.xml
Labels: ready-for-merge, deps-ok

#17484 WFLY-18842 Upgrade mod_cluster to 2.0.4.Final
  pom.xml
Labels: ready-for-merge, deps-ok

#17236 [WFLY-18544] managed deployment in content repository duplicated in tmp/vfs/temp directory
  appclient/src/main/java/org/jboss/as/appclient/deployment/ApplicationClientStructureProcessor.java
  connector/src/main/java/org/jboss/as/connector/deployers/ra/processors/RaStructureProcessor.java
  connector/src/main/java/org/jboss/as/connector/subsystems/resourceadapters/RaOperationUtil.java
  ee/src/main/java/org/jboss/as/ee/structure/EarStructureProcessor.java
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/deployment/DeploymentDuplicationTestCase.java
  undertow/src/main/java/org/wildfly/extension/undertow/deployment/WarStructureDeploymentProcessor.java
Labels: deps-ok

#17397 [WFLY-18736] Remove okhttp dependency
  boms/common-expansion/pom.xml
  docs/src/main/asciidoc/_admin-guide/subsystem-configuration/Observability_Tracing.adoc
  galleon-pack/galleon-shared/pom.xml
  galleon-pack/galleon-shared/src/main/resources/modules/system/layers/base/com/squareup/okhttp3/main/module.xml
  galleon-pack/galleon-shared/src/main/resources/modules/system/layers/base/io/grpc/main/module.xml
  galleon-pack/galleon-shared/src/main/resources/modules/system/layers/base/io/opentelemetry/api/main/module.xml
  galleon-pack/galleon-shared/src/main/resources/modules/system/layers/base/io/opentelemetry/exporter/main/module.xml
  galleon-pack/galleon-shared/src/main/resources/modules/system/layers/base/io/opentelemetry/otlp/main/module.xml
  galleon-pack/galleon-shared/src/main/resources/modules/system/layers/base/io/opentelemetry/sdk/main/module.xml
  galleon-pack/galleon-shared/src/main/resources/modules/system/layers/base/io/smallrye/opentelemetry/main/module.xml
  galleon-pack/galleon-shared/src/main/resources/modules/system/layers/base/io/vertx/grpc-client/main/module.xml
  galleon-pack/galleon-shared/src/main/resources/modules/system/layers/base/io/vertx/grpc-common/main/module.xml
  galleon-pack/galleon-shared/src/main/resources/modules/system/layers/base/org/jetbrains/kotlin/kotlin-stdlib/main/module.xml
  galleon-pack/galleon-shared/src/main/resources/modules/system/layers/base/org/wildfly/extension/opentelemetry/main/module.xml
  microprofile/telemetry-smallrye/cdi-provider/src/main/java/org/wildfly/extension/microprofile/telemetry/api/MicroProfileTelemetryCdiExtension.java
  observability/micrometer-api/src/main/java/org/wildfly/extension/micrometer/api/MicrometerCdiExtension.java
  observability/micrometer/src/main/java/org/wildfly/extension/micrometer/MicrometerDeploymentProcessor.java
  observability/micrometer/src/main/java/org/wildfly/extension/micrometer/metrics/MetricRegistration.java
  observability/micrometer/src/main/java/org/wildfly/extension/micrometer/registry/WildFlyOtlpRegistry.java
  observability/micrometer/src/main/java/org/wildfly/extension/micrometer/registry/WildFlyRegistry.java
  observability/opentelemetry-api/pom.xml
  observability/opentelemetry-api/src/main/java/org/wildfly/extension/opentelemetry/api/OpenTelemetryCdiExtension.java
  observability/opentelemetry-api/src/main/java/org/wildfly/extension/opentelemetry/api/WildFlyOpenTelemetryConfig.java
  observability/opentelemetry/pom.xml
  observability/opentelemetry/src/main/java/org/wildfly/extension/opentelemetry/OpenTelemetryConfigurationConstants.java
  observability/opentelemetry/src/main/java/org/wildfly/extension/opentelemetry/OpenTelemetryDeploymentProcessor.java
  observability/opentelemetry/src/main/java/org/wildfly/extension/opentelemetry/OpenTelemetryExtensionLogger.java
  observability/opentelemetry/src/main/java/org/wildfly/extension/opentelemetry/OpenTelemetryExtensionTransformerRegistration.java
  observability/opentelemetry/src/main/java/org/wildfly/extension/opentelemetry/OpenTelemetrySubsystemAdd.java
  observability/opentelemetry/src/main/java/org/wildfly/extension/opentelemetry/OpenTelemetrySubsystemDefinition.java
  observability/opentelemetry/src/main/java/org/wildfly/extension/opentelemetry/OpenTelemetrySubsystemModel.java
  observability/opentelemetry/src/main/java/org/wildfly/extension/opentelemetry/OpenTelemetrySubsystemSchema.java
  observability/opentelemetry/src/main/resources/schema/wildfly-opentelemetry_1_1.xsd
  observability/opentelemetry/src/test/java/org/wildfly/extension/opentelemetry/SubsystemParsingTestCase.java
  observability/opentelemetry/src/test/java/org/wildfly/extension/opentelemetry/SubsystemTransformersTestCase.java
  observability/opentelemetry/src/test/resources/org/wildfly/extension/opentelemetry/expressions.xml
  observability/opentelemetry/src/test/resources/org/wildfly/extension/opentelemetry/opentelemetry-1.1.xml
  observability/opentelemetry/src/test/resources/org/wildfly/extension/opentelemetry/transform-1_0_0.xml
  pom.xml
  testsuite/integration/microprofile/src/test/java/org/wildfly/test/integration/observability/micrometer/OpenTelemetryCollectorContainer.java
  testsuite/integration/microprofile/src/test/java/org/wildfly/test/integration/observability/opentelemetry/ContextPropagationTestCase.java
  testsuite/integration/microprofile/src/test/java/org/wildfly/test/integration/observability/opentelemetry/application/TestOpenTelemetryConfig.java
  testsuite/integration/microprofile/src/test/java/org/wildfly/test/integration/observability/opentelemetry/exporter/InMemorySpanExporter.java
Labels: deps-changed

#17473 [WFLY-18791][WFLY-18792][WFLY-18793] Channel-based provisioning testing
  build/pom.xml
  build/src/verifier/verifications.xml
  dist/pom.xml
  dist/src/verifier/verifications.xml
  ee-build/pom.xml
  ee-build/src/verifier/verifications.xml
  ee-dist/pom.xml
  ee-dist/src/verifier/verifications.xml
  ee-feature-pack/galleon-shared/src/main/resources/packages/docs.licenses.merge/pm/wildfly/merger.xsl
  preview/build/pom.xml
  preview/build/src/verifier/verifications.xml
  preview/dist/pom.xml
  preview/dist/src/verifier/verifications.xml
  testsuite/integration/manualmode-expansion/pom.xml
  testsuite/integration/manualmode-expansion/src/test/java/org/wildfly/test/manual/management/ProvisioningConsistencyTestCase.java
  testsuite/integration/manualmode/pom.xml
  testsuite/integration/manualmode/src/test/java/org/wildfly/test/manual/management/ProvisioningConsistencyTestCase.java
  testsuite/pom.xml
  testsuite/shared/src/main/java/org/wildfly/test/distribution/validation/ProvisioningConsistencyBaseTest.java
Labels: deps-ok

#16281 [WFLY-15405] AMQP Connector for reactive messaging
  boms/common-expansion/pom.xml
  docs/src/main/asciidoc/_admin-guide/subsystem-configuration/MicroProfile_Reactive_Messsaging_SmallRye.adoc
  galleon-pack/galleon-shared/pom.xml
  galleon-pack/galleon-shared/src/main/resources/layers/standalone/microprofile-reactive-messaging-amqp/layer-spec.xml
  galleon-pack/galleon-shared/src/main/resources/modules/system/layers/base/io/smallrye/reactive/messaging/connector/amqp/main/module.xml
  galleon-pack/galleon-shared/src/main/resources/modules/system/layers/base/io/smallrye/reactive/messaging/connector/main/module.xml
  galleon-pack/galleon-shared/src/main/resources/modules/system/layers/base/io/smallrye/reactive/mutiny/vertx-amqp-client/main/module.xml
  galleon-pack/galleon-shared/src/main/resources/modules/system/layers/base/io/vertx/client/amqp/main/module.xml
  galleon-pack/galleon-shared/src/main/resources/modules/system/layers/base/io/vertx/proton/main/module.xml
  galleon-pack/galleon-shared/src/main/resources/modules/system/layers/base/org/eclipse/microprofile/reactive-messaging/api/main/module.xml
  galleon-pack/galleon-shared/src/main/resources/modules/system/layers/base/org/wildfly/extension/microprofile/reactive-messaging-smallrye/main/module.xml
  galleon-pack/galleon-shared/src/main/resources/modules/system/layers/base/org/wildfly/reactive/messaging/amqp/main/module.xml
  galleon-pack/galleon-shared/src/main/resources/modules/system/layers/base/org/wildfly/reactive/messaging/common/main/module.xml
  microprofile/reactive-messaging-smallrye/amqp/pom.xml
  microprofile/reactive-messaging-smallrye/amqp/src/main/java/org/wildfly/microprofile/reactive/messaging/config/amqp/ssl/context/AmqpDynamicDeploymentProcessorAdder.java
  microprofile/reactive-messaging-smallrye/amqp/src/main/java/org/wildfly/microprofile/reactive/messaging/config/amqp/ssl/context/AmqpReactiveMessagingCdiExtension.java
  microprofile/reactive-messaging-smallrye/amqp/src/main/java/org/wildfly/microprofile/reactive/messaging/config/amqp/ssl/context/AmqpReactiveMessagingSslConfigProcessor.java
  microprofile/reactive-messaging-smallrye/amqp/src/main/java/org/wildfly/microprofile/reactive/messaging/config/amqp/ssl/context/_private/MicroProfileReactiveMessagingAmqpLogger.java
  microprofile/reactive-messaging-smallrye/amqp/src/main/resources/META-INF/beans.xml
  microprofile/reactive-messaging-smallrye/amqp/src/main/resources/META-INF/services/org.wildfly.microprofile.reactive.messaging.common.DynamicDeploymentProcessorAdder
  microprofile/reactive-messaging-smallrye/common/pom.xml
  microprofile/reactive-messaging-smallrye/common/src/main/java/org/wildfly/microprofile/reactive/messaging/common/_private/MicroProfileReactiveMessagingCommonLogger.java
  microprofile/reactive-messaging-smallrye/common/src/main/java/org/wildfly/microprofile/reactive/messaging/common/security/BaseReactiveMessagingSslConfigProcessor.java
  microprofile/reactive-messaging-smallrye/common/src/main/java/org/wildfly/microprofile/reactive/messaging/common/security/ElytronSSLContextRegistry.java
  microprofile/reactive-messaging-smallrye/config/src/main/java/org/wildfly/microprofile/reactive/messaging/config/ReactiveMessagingConfigSource.java
  microprofile/reactive-messaging-smallrye/extension/src/main/java/org/wildfly/extension/microprofile/reactive/messaging/MicroProfileReactiveMessagingSubsystemDefinition.java
  microprofile/reactive-messaging-smallrye/kafka/pom.xml
  microprofile/reactive-messaging-smallrye/kafka/src/main/java/org/wildfly/microprofile/reactive/messaging/config/kafka/ssl/context/KafkaDynamicDeploymentProcessorAdder.java
  microprofile/reactive-messaging-smallrye/kafka/src/main/java/org/wildfly/microprofile/reactive/messaging/config/kafka/ssl/context/KafkaReactiveMessagingSslConfigProcessor.java
  microprofile/reactive-messaging-smallrye/kafka/src/main/java/org/wildfly/microprofile/reactive/messaging/config/kafka/ssl/context/ReactiveMessagingSslConfigProcessor.java
  microprofile/reactive-messaging-smallrye/kafka/src/main/java/org/wildfly/microprofile/reactive/messaging/config/kafka/ssl/context/WildFlyKafkaSSLEngineFactory.java
  microprofile/reactive-messaging-smallrye/pom.xml
  testsuite/integration/microprofile/pom.xml
  testsuite/integration/microprofile/src/test/java/org/wildfly/test/integration/microprofile/reactive/ConfigureElytronSslContextSetupTask.java
  testsuite/integration/microprofile/src/test/java/org/wildfly/test/integration/microprofile/reactive/KeystoreUtil.java
  testsuite/integration/microprofile/src/test/java/org/wildfly/test/integration/microprofile/reactive/RunArtemisAmqpSetupTask.java
  testsuite/integration/microprofile/src/test/java/org/wildfly/test/integration/microprofile/reactive/RunKafkaSetupTask.java
  testsuite/integration/microprofile/src/test/java/org/wildfly/test/integration/microprofile/reactive/messaging/amqp/AnonymousAmqpTestCase.java
  testsuite/integration/microprofile/src/test/java/org/wildfly/test/integration/microprofile/reactive/messaging/amqp/ConsumingBean.java
  testsuite/integration/microprofile/src/test/java/org/wildfly/test/integration/microprofile/reactive/messaging/amqp/ProducingBean.java
  testsuite/integration/microprofile/src/test/java/org/wildfly/test/integration/microprofile/reactive/messaging/amqp/SslAmqpWithSslConfiguredGloballyTestCase.java
  testsuite/integration/microprofile/src/test/java/org/wildfly/test/integration/microprofile/reactive/messaging/amqp/SslAmqpWithSslConfiguredOnConnectorTestCase.java
  testsuite/integration/microprofile/src/test/java/org/wildfly/test/integration/microprofile/reactive/messaging/amqp/TestResource.java
  testsuite/integration/microprofile/src/test/java/org/wildfly/test/integration/microprofile/reactive/messaging/amqp/microprofile-config-no-ssl.properties
  testsuite/integration/microprofile/src/test/java/org/wildfly/test/integration/microprofile/reactive/messaging/amqp/microprofile-config-ssl-connector.properties
  testsuite/integration/microprofile/src/test/java/org/wildfly/test/integration/microprofile/reactive/messaging/amqp/microprofile-config-ssl-global.properties
  testsuite/integration/microprofile/src/test/java/org/wildfly/test/integration/microprofile/reactive/messaging/amqp/web.xml
  testsuite/integration/microprofile/src/test/java/org/wildfly/test/integration/microprofile/reactive/messaging/kafka/ssl/ReactiveMessagingKafkaSslTestCase.java
  testsuite/integration/microprofile/src/test/java/org/wildfly/test/integration/microprofile/reactive/messaging/kafka/ssl/RunKafkaWithSslSetupTask.java
  testsuite/integration/microprofile/src/test/java/org/wildfly/test/integration/microprofile/reactive/messaging/tx/web.xml
  testsuite/integration/microprofile/src/test/resources/org/wildfly/test/integration/microprofile/reactive/messaging/amqp/broker-ssl.xml
  testsuite/integration/microprofile/src/test/resources/org/wildfly/test/integration/microprofile/reactive/messaging/amqp/broker.xml
  testsuite/layers-expansion/pom.xml
Labels: Feature, missing-reqs, deps-changed

#17496 [WFLY-18555][WFLY-18804][WFLY-18805][WFLY-18806] Hibernate upgrades
  boms/common-ee/pom.xml
  boms/preview-ee/pom.xml
  boms/user/ee/pom.xml
  ee-feature-pack/galleon-shared/pom.xml
  ee-feature-pack/galleon-shared/src/main/resources/modules/system/layers/base/org/apache/lucene/main/module.xml
  ee-feature-pack/galleon-shared/src/main/resources/modules/system/layers/base/org/hibernate/search/engine/main/module.xml
  ee-feature-pack/galleon-shared/src/main/resources/modules/system/layers/base/org/hibernate/search/mapper/orm/main/module.xml
  jpa/hibernatesearch/pom.xml
  jpa/subsystem/src/main/java/org/jboss/as/jpa/config/Configuration.java
  jpa/subsystem/src/main/java/org/jboss/as/jpa/processor/HibernateSearchProcessor.java
  pom.xml
  preview/galleon-local/pom.xml
  preview/galleon-local/src/main/resources/layers/standalone/hibernate-search/layer-spec.xml
  preview/galleon-local/src/main/resources/modules/system/layers/base/org/hibernate/search/mapper/orm/coordination/outboxpolling/main/module.xml
  preview/galleon-local/src/main/resources/modules/system/layers/base/org/hibernate/search/mapper/orm/outboxpolling/main/module.xml
  testsuite/integration/basic/pom.xml
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/hibernate/search/backend/elasticsearch/util/ElasticsearchServerSetupObserver.java
  testsuite/preview/basic/pom.xml
Labels: deps-changed

#17458 WFLY-18804 + WFLY-18805 + WFLY-18806 Upgrade to Hibernate Search 7.0
  boms/common-ee/pom.xml
  boms/preview-ee/pom.xml
  boms/user/ee/pom.xml
  ee-feature-pack/galleon-shared/pom.xml
  ee-feature-pack/galleon-shared/src/main/resources/modules/system/layers/base/org/apache/lucene/main/module.xml
  ee-feature-pack/galleon-shared/src/main/resources/modules/system/layers/base/org/hibernate/search/engine/main/module.xml
  ee-feature-pack/galleon-shared/src/main/resources/modules/system/layers/base/org/hibernate/search/mapper/orm/main/module.xml
  jpa/hibernatesearch/pom.xml
  jpa/subsystem/src/main/java/org/jboss/as/jpa/config/Configuration.java
  jpa/subsystem/src/main/java/org/jboss/as/jpa/processor/HibernateSearchProcessor.java
  pom.xml
  preview/galleon-local/pom.xml
  preview/galleon-local/src/main/resources/layers/standalone/hibernate-search/layer-spec.xml
  preview/galleon-local/src/main/resources/modules/system/layers/base/org/hibernate/search/mapper/orm/coordination/outboxpolling/main/module.xml
  preview/galleon-local/src/main/resources/modules/system/layers/base/org/hibernate/search/mapper/orm/outboxpolling/main/module.xml
  testsuite/integration/basic/pom.xml
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/hibernate/search/backend/elasticsearch/util/ElasticsearchServerSetupObserver.java
  testsuite/preview/basic/pom.xml
Labels: deps-changed

#17156 [[WFLY-18442]] Upgrade to MP Config 3.1
  pom.xml
Labels: ready-for-merge, deps-ok

#17497 Fix for WFLY-18858, Do not deploy channel manifests
  ee-feature-pack/galleon-feature-pack/pom.xml
  galleon-pack/galleon-feature-pack/pom.xml
  pom.xml
  preview/feature-pack/pom.xml
Labels: deps-ok

#17490 [WFLY-18838] Preview support for Jakarta MVC 2.1
  boms/preview-ee/pom.xml
  docs/src/main/asciidoc/Getting_Started_Guide.adoc
  docs/src/main/asciidoc/WildFly_and_WildFly_Preview.adoc
  docs/src/main/asciidoc/_admin-guide/subsystem-configuration/Simple_configuration_subsystems.adoc
  docs/src/main/asciidoc/_galleon/Galleon_layers.adoc
  pom.xml
  preview/feature-pack/pom.xml
  preview/feature-pack/wildfly-feature-pack-build.xml
  preview/galleon-local/src/main/resources/feature_groups/domain-host-excludes.xml
  testsuite/domain/src/test/java/org/jboss/as/test/integration/domain/HostExcludesTestCase.java
  testsuite/layers-expansion/pom.xml
  testsuite/layers/pom.xml
  testsuite/pom.xml
  testsuite/preview/basic/pom.xml
  testsuite/preview/basic/src/test/java/org/wildfly/test/preview/mvc/CdiBean.java
  testsuite/preview/basic/src/test/java/org/wildfly/test/preview/mvc/MVCKrazoApplication.java
  testsuite/preview/basic/src/test/java/org/wildfly/test/preview/mvc/MVCKrazoSmokeController.java
  testsuite/preview/basic/src/test/java/org/wildfly/test/preview/mvc/MVCKrazoSmokeTestCase.java
  testsuite/preview/basic/src/test/resources/logging.properties
  testsuite/shared/src/main/java/org/jboss/as/test/shared/LayersTestBase.java
Labels: Feature, deps-ok

#17502 WFLY-18866 Update feature packs to use appropriate stability-level.
  ee-feature-pack/galleon-feature-pack/wildfly-feature-pack-build.xml
  galleon-pack/galleon-feature-pack/wildfly-feature-pack-build.xml
  preview/feature-pack/wildfly-feature-pack-build.xml
Labels: ready-for-merge
