Repository wildfly/wildfly, pull requests merged in 2023-05, with the labels that each got.

#16806 WFLY-17981 Upgrade Infinispan to 14.0.9.Final
  clustering/ee/infinispan/pom.xml
  clustering/infinispan/embedded/api/pom.xml
  clustering/infinispan/embedded/service/pom.xml
  clustering/infinispan/extension/src/test/java/org/jboss/as/clustering/infinispan/subsystem/InfinispanSubsystemTestCase.java
  clustering/server/infinispan/pom.xml
  pom.xml
  testsuite/integration/clustering/pom.xml
Labels: deps-ok, 29.Alpha1

#16805 [WFLY-17934] Eliminating deprecated javax.xml.stream.api module usages
  ee-feature-pack/common/src/main/resources/modules/system/layers/base/com/sun/xml/fastinfoset/main/module.xml
  ee-feature-pack/common/src/main/resources/modules/system/layers/base/com/sun/xml/messaging/saaj/main/module.xml
  ee-feature-pack/common/src/main/resources/modules/system/layers/base/javax/orb/api/main/module.xml
  ee-feature-pack/common/src/main/resources/modules/system/layers/base/org/apache/cxf/impl/main/module.xml
  ee-feature-pack/common/src/main/resources/modules/system/layers/base/org/apache/cxf/main/module.xml
  ee-feature-pack/common/src/main/resources/modules/system/layers/base/org/apache/cxf/services-sts/main/module.xml
  ee-feature-pack/common/src/main/resources/modules/system/layers/base/org/apache/cxf/ws-security/main/module.xml
  ee-feature-pack/common/src/main/resources/modules/system/layers/base/org/apache/neethi/main/module.xml
  ee-feature-pack/common/src/main/resources/modules/system/layers/base/org/glassfish/jaxb/main/module.xml
  ee-feature-pack/common/src/main/resources/modules/system/layers/base/org/jboss/as/jacorb/main/module.xml
  ee-feature-pack/common/src/main/resources/modules/system/layers/base/org/jboss/as/jsr77/main/module.xml
  ee-feature-pack/common/src/main/resources/modules/system/layers/base/org/jboss/as/messaging/main/module.xml
  ee-feature-pack/common/src/main/resources/modules/system/layers/base/org/jboss/as/web/main/module.xml
  ee-feature-pack/common/src/main/resources/modules/system/layers/base/org/jboss/ironjacamar/jdbcadapters/main/module.xml
  ee-feature-pack/common/src/main/resources/modules/system/layers/base/org/jboss/ws/common/main/module.xml
  ee-feature-pack/common/src/main/resources/modules/system/layers/base/org/jboss/ws/cxf/jbossws-cxf-server/main/module.xml
  ee-feature-pack/common/src/main/resources/modules/system/layers/base/org/jboss/ws/spi/main/module.xml
  ee-feature-pack/common/src/main/resources/modules/system/layers/base/org/jboss/xts/main/module.xml
  ee-feature-pack/common/src/main/resources/modules/system/layers/base/org/wildfly/extension/datasources-agroal/main/module.xml
  ee-feature-pack/common/src/main/resources/modules/system/layers/base/org/wildfly/extension/picketlink/main/module.xml
  ee-feature-pack/ee-10-api/src/main/resources/modules/system/layers/base/jakarta/transaction/api/main/module.xml
  ee-feature-pack/ee-10-api/src/main/resources/modules/system/layers/base/jakarta/xml/bind/api/main/module.xml
  ee-feature-pack/galleon-shared/src/main/resources/modules/system/layers/base/org/eclipse/yasson/main/module.xml
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/ee/globalmodules/module.xml
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/jca/moduledeployment/module.xml
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/weld/multideployment/module.xml
  testsuite/integration/web/src/test/java/org/jboss/as/test/integration/web/annotationsmodule/module.xml
  testsuite/layers/src/test/java/org/jboss/as/test/layers/LayersTestCase.java
Labels: deps-ok, 29.Alpha1

#16789 [WFLY-17965] Delete copy-test-libs.xml
  testsuite/integration/src/test/scripts/copy-test-libs.xml
Labels: deps-ok, 29.Alpha1

#16811 [WFLY-17990] Ensure foundational layers have an application-security-domain in the undertow subsystem.
  docs/src/main/asciidoc/_galleon/Galleon_layers.adoc
  ee-feature-pack/galleon-common/src/main/resources/layers/standalone/datasources-web-server/layer-spec.xml
  ee-feature-pack/galleon-common/src/main/resources/layers/standalone/ee-core-profile-server/layer-spec.xml
Labels: ready-for-merge, deps-ok

#16809 [WFLY-17962] do not register ResteasyBootstrap listener on AbstractRT…
  rts/src/main/java/org/wildfly/extension/rts/service/AbstractRTSService.java
Labels: deps-ok

#16807 [WFLY-17983] Upgrade Jakarta Activation to 2.1.2
  pom.xml
Labels: deps-ok

#16808 [WFLY-17983][WFLY-17984] Upgrade Jakarta Activation 2.1.2 and Angus Activation 2.0.1
  pom.xml
Labels: deps-ok

#16815 WFLY-18003 Upgrade smallrye-open-api to 3.3.3
  pom.xml
Labels: deps-ok, 29.Alpha1

#16819 WFLY-17958 Persistence container bytecode enhancement should be disabled by default
  jpa/subsystem/src/main/java/org/jboss/as/jpa/config/Configuration.java
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/jpa/hibernate/classfiletransformertest/ClassFileTransformerTestCase.java
Labels: deps-ok

#16812 [WFLY-17991] / [WFLY-17976] ee-security should depend on elytron and ensure the JACC policy is enabled by default.
  docs/src/main/asciidoc/_elytron/Elytron_and_Jakarta_Authorization.adoc
  docs/src/main/asciidoc/_galleon/Galleon_layers.adoc
  ee-feature-pack/galleon-common/src/main/resources/feature_groups/jacc-policy.xml
  ee-feature-pack/galleon-common/src/main/resources/feature_groups/unsecured-basic-profile.xml
  ee-feature-pack/galleon-common/src/main/resources/layers/standalone/ee-security/layer-spec.xml
  microprofile/galleon-common/src/main/resources/layers/standalone/microprofile-jwt/layer-spec.xml
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/security/jacc/context/PolicyContextTestCase.java
  testsuite/integration/clustering/src/test/java/org/jboss/as/test/clustering/cluster/web/authentication/CustomAuthenticationWebFailoverTestCase.java
  testsuite/integration/elytron/src/test/java/org/wildfly/test/integration/elytron/securityapi/EESecurityAuthMechanismMultiConstraintsTestCase.java
  testsuite/integration/elytron/src/test/java/org/wildfly/test/integration/elytron/securityapi/EESecurityInjectionEnabledElytronTestCase.java
  testsuite/integration/elytron/src/test/java/org/wildfly/test/integration/elytron/securityapi/EESecurityInjectionEnabledJakartaTestCase.java
  testsuite/integration/elytron/src/test/java/org/wildfly/test/integration/elytron/securityapi/Policy.java
  testsuite/integration/elytron/src/test/java/org/wildfly/test/integration/elytron/securityapi/SecurityAPITestCase.java
Labels: ready-for-merge, deps-ok

#16820 Fix for WFLY-18008, Upgrade Galleon plugins to 6.4.2.Final
  pom.xml
Labels: deps-ok, 29.Alpha1

#16557 [WFLY-17566] Deprecate legacy security attributes in resource adapter subsystem
  connector/src/main/java/org/jboss/as/connector/deployers/datasource/DataSourceDefinitionInjectionSource.java
  connector/src/main/java/org/jboss/as/connector/deployers/ds/DsXmlParser.java
  connector/src/main/java/org/jboss/as/connector/deployers/ds/processors/DsXmlDeploymentInstallProcessor.java
  connector/src/main/java/org/jboss/as/connector/logging/ConnectorLogger.java
  connector/src/main/java/org/jboss/as/connector/metadata/api/common/Credential.java
  connector/src/main/java/org/jboss/as/connector/metadata/api/common/Security.java
  connector/src/main/java/org/jboss/as/connector/metadata/api/common/SecurityMetadata.java
  connector/src/main/java/org/jboss/as/connector/metadata/api/ds/DsSecurity.java
  connector/src/main/java/org/jboss/as/connector/metadata/common/CredentialImpl.java
  connector/src/main/java/org/jboss/as/connector/metadata/common/SecurityImpl.java
  connector/src/main/java/org/jboss/as/connector/metadata/ds/DsSecurityImpl.java
  connector/src/main/java/org/jboss/as/connector/services/resourceadapters/DirectConnectionFactoryActivatorService.java
  connector/src/main/java/org/jboss/as/connector/services/resourceadapters/deployment/ResourceAdapterXmlDeploymentService.java
  connector/src/main/java/org/jboss/as/connector/subsystems/datasources/AbstractDataSourceService.java
  connector/src/main/java/org/jboss/as/connector/subsystems/datasources/DataSourceModelNodeUtil.java
  connector/src/main/java/org/jboss/as/connector/subsystems/datasources/XMLDataSourceRuntimeHandler.java
  connector/src/main/java/org/jboss/as/connector/subsystems/datasources/XMLXaDataSourceRuntimeHandler.java
  connector/src/main/java/org/jboss/as/connector/subsystems/resourceadapters/ConnectionDefinitionAdd.java
  connector/src/main/java/org/jboss/as/connector/subsystems/resourceadapters/Constants.java
  connector/src/main/java/org/jboss/as/connector/subsystems/resourceadapters/IronJacamarResourceCreator.java
  connector/src/main/java/org/jboss/as/connector/subsystems/resourceadapters/RaAdd.java
  connector/src/main/java/org/jboss/as/connector/subsystems/resourceadapters/RaOperationUtil.java
  connector/src/main/resources/org/jboss/as/connector/subsystems/resourceadapters/LocalDescriptions.properties
  messaging-activemq/subsystem/src/main/java/org/wildfly/extension/messaging/activemq/jms/ExternalPooledConnectionFactoryService.java
  messaging-activemq/subsystem/src/main/java/org/wildfly/extension/messaging/activemq/jms/PooledConnectionFactoryService.java
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/jca/metrics/RaCfgMetricUnitTestCase.java
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/jca/metrics/ra/bool-pres-properties-set.xml
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/jca/metrics/ra/bool-pres-properties.xml
  testsuite/integration/smoke/src/test/java/org/jboss/as/test/smoke/mgmt/resourceadapter/ResourceAdapterOperationsUnitTestCase.java
Labels: deps-ok, 29.Alpha1

#16813 WFLY-18002 ExpirationMetaData.isExpired() should return true if expiration time is exactly now.
  clustering/ee/spi/src/main/java/org/wildfly/clustering/ee/expiration/ExpirationMetaData.java
Labels: deps-ok, 29.Alpha1

#16788 WFLY-17964 Upgrade Narayana to 6.0.1.Final
  microprofile/galleon-common/src/main/resources/modules/system/layers/base/org/jboss/narayana/rts/lra-coordinator/main/module.xml
  pom.xml
Labels: deps-ok, 29.Alpha1

#16766 [WFLY-17811] converted ee concurrent tests to jar packages
  testsuite/integration/basic/pom.xml
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/ee/concurrent/DefaultContextServiceTestCase.java
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/ee/concurrent/DefaultManagedExecutorServiceTestCase.java
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/ee/concurrent/DefaultManagedScheduledExecutorServiceTestCase.java
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/ee/concurrent/DefaultManagedThreadFactoryTestCase.java
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/ee/concurrent/ManagedScheduledExecutorExceptionTestCase.java
Labels: deps-ok, 29.Alpha1

#16829 [WFLY-18010] Upgrade jose4j to 0.9.3
  pom.xml
Labels: deps-ok, 29.Alpha1

#16830 [28.x][WFLY-18010] Upgrade jose4j to 0.9.3
  pom.xml
Labels: 28.x

#16831 [WFLY-18007] Upgrade xalan to 2.7.3 (CVE-2022-34169)
  testsuite/pom.xml
Labels: deps-ok, 29.Alpha1

#16832 [28.x][WFLY-18007] Upgrade xalan to 2.7.3 (CVE-2022-34169)
  testsuite/pom.xml
Labels: 28.x

#16838 [WFLY-18012] Do not attempt to load the ConfigurationFactory during u…
  jaxrs/src/main/java/org/jboss/as/jaxrs/deployment/JaxrsIntegrationProcessor.java
Labels: deps-ok, 29.Alpha1

#16839 [28.x] [WFLY-18012] Do not attempt to load the ConfigurationFactory during u…
  jaxrs/src/main/java/org/jboss/as/jaxrs/deployment/JaxrsIntegrationProcessor.java
Labels: 28.x

#16835 [WFLY-18011] Adding java.base/java.net package to recommended client side JPMS settings
  pom.xml
Labels: deps-ok, 29.Alpha1

#16836 [WFLY-18011] Adding java.base/java.net package to recommended client side JPMS settings
  pom.xml
Labels: 28.x

#16843 [WFLY-18005] Upgrade RESTEasy to 6.2.4.Final
  pom.xml
Labels: deps-ok

#16844 [28.x] [WFLY-18005] Upgrade RESTEasy to 6.2.4.Final
  pom.xml
Labels: 28.x

#16850 [28.x] [WFLY-18022] WildFly Core to 20.0.2.Final
  pom.xml
Labels: 28.x

#16847 WFLY-18023 @SessionScoped EJBs are replicating proxy placeholders unnecessarily
  ejb3/src/main/java/org/jboss/as/ejb3/component/stateful/StatefulSessionBeanImmutability.java
Labels: deps-ok, 29.Alpha1

#16743 [WFLY-17905] Clean out unneeded xalan references
  boms/common-ee/pom.xml
  boms/standard-test/pom.xml
  pom.xml
Labels: deps-ok, 29.Alpha1

#16753 [WFLY-16705] Deprecate Context Service ResourceDefinition attribute u…
  ee-feature-pack/galleon-common/src/main/resources/feature_groups/transactions-all.xml
  ee-feature-pack/galleon-common/src/main/resources/feature_groups/unsecured-basic-profile.xml
  ee-feature-pack/galleon-shared/src/main/resources/feature_groups/ee-concurrency.xml
  ee/src/main/java/org/jboss/as/ee/subsystem/ContextServiceAdd.java
  ee/src/main/java/org/jboss/as/ee/subsystem/ContextServiceResourceDefinition.java
  ee/src/main/resources/org/jboss/as/ee/subsystem/LocalDescriptions.properties
Labels: Blocker, deps-ok, 29.Alpha1

#16810 [WFLY-17994] The management layer is not optional for jmx-remoting.
  docs/src/main/asciidoc/_galleon/Galleon_layers.adoc
Labels: core-upgrade-needed, deps-ok, 29.Alpha1

#16842 [WFLY-18018] Clean up the root pom dependency data
  boms/common-ee/pom.xml
  boms/common-expansion/pom.xml
  boms/preview-ee/pom.xml
  boms/standard-ee/pom.xml
  boms/standard-expansion/pom.xml
  boms/standard-test/pom.xml
  clustering/infinispan/embedded/spi/pom.xml
  ee-feature-pack/ee-10-api/src/main/resources/modules/system/layers/base/jakarta/annotation/api/main/module.xml
  jsf/subsystem/pom.xml
  pom.xml
  preview/common/pom.xml
  preview/feature-pack/pom.xml
  testsuite/integration/elytron-oidc-client/pom.xml
  testsuite/integration/microprofile/pom.xml
  testsuite/integration/microprofile/src/test/java/org/wildfly/test/integration/microprofile/config/smallrye/converter/SetupTask.java
  undertow/pom.xml
Labels: deps-ok, 29.Alpha1

#16852 WFLY-18031 Upgrade to Hibernate 6.2.3.final release to address TCK failures (HHH-16541)
  pom.xml
Labels: deps-ok

#16861 WFLY-18038 JGroups transport thread pool configuration is ignored
  clustering/jgroups/extension/src/main/java/org/jboss/as/clustering/jgroups/subsystem/QueuelessThreadPoolFactory.java
  clustering/jgroups/extension/src/main/java/org/jboss/as/clustering/jgroups/subsystem/ThreadPoolFactory.java
  clustering/jgroups/extension/src/main/java/org/jboss/as/clustering/jgroups/subsystem/ThreadPoolFactoryServiceConfigurator.java
  clustering/jgroups/extension/src/main/java/org/jboss/as/clustering/jgroups/subsystem/ThreadPoolResourceDefinition.java
  clustering/jgroups/extension/src/main/java/org/jboss/as/clustering/jgroups/subsystem/TransportConfigurationServiceConfigurator.java
Labels: deps-ok, 29.Alpha1

#16867 [WFLY-18045] Remove uses of deprecated ManagementResourceRegistration…
  connector/src/main/java/org/jboss/as/connector/services/datasources/statistics/DataSourceStatisticsService.java
  messaging-activemq/subsystem/src/main/java/org/wildfly/extension/messaging/activemq/jms/PooledConnectionFactoryStatisticsService.java
Labels: deps-ok, 29.Alpha1

#16777 [WFLY-17102] / [WFLY-17849] Attempt to fix the intermittent failures in the OIDC tests and unignore them
  testsuite/integration/elytron-oidc-client/src/test/java/org/wildfly/test/integration/elytron/oidc/client/KeycloakConfiguration.java
  testsuite/integration/elytron-oidc-client/src/test/java/org/wildfly/test/integration/elytron/oidc/client/KeycloakContainer.java
  testsuite/integration/elytron-oidc-client/src/test/java/org/wildfly/test/integration/elytron/oidc/client/OidcBaseTest.java
  testsuite/integration/elytron-oidc-client/src/test/java/org/wildfly/test/integration/elytron/oidc/client/deployment/OidcWithDeploymentConfigTest.java
  testsuite/integration/elytron-oidc-client/src/test/java/org/wildfly/test/integration/elytron/oidc/client/propagation/OidcIdentityPropagationTestCase.java
  testsuite/integration/elytron-oidc-client/src/test/java/org/wildfly/test/integration/elytron/oidc/client/subsystem/OidcWithSubsystemConfigTest.java
Labels: deps-ok, 29.Alpha1

#16860 WFLY-18037 Upgrade smallrye-open-api to 3.3.4.
  pom.xml
Labels: deps-ok

#16870 [WFLY-18053] Remove uses of deprecated ConfigurationPersister and Sub…
  appclient/src/main/java/org/jboss/as/appclient/subsystem/ApplicationClientConfigurationPersister.java
Labels: deps-ok, Critical, 29.Alpha1

#16864 [WFLY-18039] Remove uses of deprecated AttributeDefinition API
  connector/src/main/java/org/jboss/as/connector/subsystems/resourceadapters/ResourceAdapterParser.java
  ee/src/main/java/org/jboss/as/ee/subsystem/GlobalModulesDefinition.java
  ejb3/src/main/java/org/jboss/as/ejb3/subsystem/EJB3Subsystem11Parser.java
  ejb3/src/main/java/org/jboss/as/ejb3/subsystem/EJB3Subsystem12Parser.java
  ejb3/src/main/java/org/jboss/as/ejb3/subsystem/EJB3Subsystem15Parser.java
  ejb3/src/main/java/org/jboss/as/ejb3/subsystem/EJB3Subsystem20Parser.java
  ejb3/src/main/java/org/jboss/as/ejb3/subsystem/EJB3Subsystem50Parser.java
  ejb3/src/main/java/org/jboss/as/ejb3/subsystem/EJB3SubsystemXMLPersister.java
  ejb3/src/main/java/org/jboss/as/ejb3/subsystem/IdentityResourceDefinition.java
  ejb3/src/main/java/org/jboss/as/ejb3/subsystem/StaticEJBDiscoveryDefinition.java
  jaxrs/src/main/java/org/jboss/as/jaxrs/JaxrsSubsystemParser_3_0.java
  messaging-activemq/subsystem/src/main/java/org/wildfly/extension/messaging/activemq/CommonAttributes.java
  messaging-activemq/subsystem/src/main/java/org/wildfly/extension/messaging/activemq/deployment/MessagingDeploymentParser_1_0.java
  naming/src/main/java/org/jboss/as/naming/subsystem/NamingSubsystem11Parser.java
  naming/src/main/java/org/jboss/as/naming/subsystem/NamingSubsystem12Parser.java
  undertow/src/main/java/org/wildfly/extension/undertow/filters/CustomFilterDefinition.java
  undertow/src/test/resources/org/wildfly/extension/undertow/undertow-14.0.xml
  webservices/server-integration/src/main/java/org/jboss/as/webservices/dmr/WSSubsystemWriter.java
Labels: deps-ok, Critical, 29.Alpha1

#16865 [WFLY-18042][WFLY-17783] Upgrade reactive messaging to 4.6.0 and reenable test
  pom.xml
  testsuite/integration/microprofile/src/test/java/org/wildfly/test/integration/microprofile/reactive/messaging/kafka/api/ReactiveMessagingKafkaUserApiTestCase.java
Labels: ready-for-merge, deps-ok, 29.Alpha1

#16849 [WFLY-18025] Upgrade Arquillian to 1.7.0.Final and WildFly Arquillian…
  pom.xml
Labels: ready-for-merge, deps-ok, dependencies, 29.Alpha1

#16798 [WFLY-14721] Add tests to XTS and transactions(JTA) subsystem for attributes that allow expression
  transactions/src/main/java/org/jboss/as/txn/subsystem/CMResourceResourceDefinition.java
  transactions/src/test/resources/org/jboss/as/txn/subsystem/full-expressions.xml
Labels: ready-for-merge, deps-ok, 29.Alpha1

#16271 WFLY-8718: remove xa-datasource-class from JDBC driver definition
  connector/src/main/java/org/jboss/as/connector/subsystems/datasources/Constants.java
  connector/src/main/resources/org/jboss/as/connector/subsystems/datasources/LocalDescriptions.properties
Labels: ready-for-merge, deps-ok, affects_i18n, 29.Alpha1

#16859 WFLY-18036 Marshalling optimizations are not getting applied to @SessionScoped @Stateful EJBs
  clustering/web/extension/src/main/java/org/wildfly/extension/clustering/web/JBossMarshallingVersion.java
  clustering/web/extension/src/main/java/org/wildfly/extension/clustering/web/deployment/DistributableWebDeploymentProcessor.java
  ejb3/src/main/java/org/jboss/as/ejb3/deployment/processors/EjbDependencyDeploymentUnitProcessor.java
  undertow/src/main/java/org/wildfly/extension/undertow/deployment/UndertowDependencyProcessor.java
Labels: ready-for-merge, deps-ok, 29.Alpha1

#16877 [WFLY-18057][WFLY-18056] Upgrade Jakarta Mail Api and Angus Mail to the latest versions
  pom.xml
Labels: ready-for-merge, deps-ok, dependencies, 29.Alpha1

#16866 [WFLY-18040] EJB: make system wide client interceptors a static part …
  ejb3/src/main/java/org/jboss/as/ejb3/remote/EJBClientContextService.java
  ejb3/src/main/java/org/jboss/as/ejb3/subsystem/IdentityInterceptorProcessor.java
Labels: ready-for-merge, deps-ok, 29.Alpha1

#16862 [WFLY-17563] Return back *module.xml necessary for manual steps of installing different jsf implementation
  jsf/multi-jsf-installer/src/main/resources/mojarra-api-module.xml
  jsf/multi-jsf-installer/src/main/resources/mojarra-deploy.scr
  jsf/multi-jsf-installer/src/main/resources/mojarra-impl-module.xml
  jsf/multi-jsf-installer/src/main/resources/mojarra-injection-module.xml
  jsf/multi-jsf-installer/src/main/resources/mojarra-undeploy.scr
  jsf/multi-jsf-installer/src/main/resources/myfaces-api-module.xml
  jsf/multi-jsf-installer/src/main/resources/myfaces-deploy.scr
  jsf/multi-jsf-installer/src/main/resources/myfaces-digester-module.xml
  jsf/multi-jsf-installer/src/main/resources/myfaces-impl-module.xml
  jsf/multi-jsf-installer/src/main/resources/myfaces-injection-module.xml
  jsf/multi-jsf-installer/src/main/resources/myfaces-undeploy.scr
Labels: ready-for-merge, deps-ok, 29.Alpha1

#16366 [WFLY-16306] Add documentation that explains how to use the Keycloak feature pack that provides the SAML adapter
  docs/src/main/asciidoc/WildFly_Elytron_Security.adoc
  docs/src/main/asciidoc/_elytron/Keycloak_SAML_Integration.adoc
Labels: ready-for-merge, deps-ok, 29.Alpha1

#16803 [WFLY-17931] Eliminating deprecated javax.api module usages
  docs/src/main/asciidoc/_admin-guide/subsystem-configuration/Messaging.adoc
  docs/src/main/asciidoc/_admin-guide/subsystem-configuration/Transactions.adoc
  docs/src/main/asciidoc/_extending-wildfly/Example_subsystem.adoc
  ee-feature-pack/galleon-shared/src/main/resources/modules/system/layers/base/jakarta/resource/api/main/module.xml
  ee-feature-pack/galleon-shared/src/main/resources/modules/system/layers/base/jakarta/security/enterprise/api/main/module.xml
  ee-feature-pack/galleon-shared/src/main/resources/modules/system/layers/base/org/apache/cxf/main/module.xml
  ee-feature-pack/galleon-shared/src/main/resources/modules/system/layers/base/org/apache/cxf/services-sts/main/module.xml
  ee-feature-pack/galleon-shared/src/main/resources/modules/system/layers/base/org/apache/cxf/ws-security/main/module.xml
  ee-feature-pack/galleon-shared/src/main/resources/modules/system/layers/base/org/glassfish/jaxb/main/module.xml
  ee-feature-pack/galleon-shared/src/main/resources/modules/system/layers/base/org/glassfish/soteria/main/module.xml
  ee-feature-pack/galleon-shared/src/main/resources/modules/system/layers/base/org/jboss/as/webservices/server/integration/main/module.xml
  ee-feature-pack/galleon-shared/src/main/resources/modules/system/layers/base/org/joda/time/main/module.xml
  ee-feature-pack/galleon-shared/src/main/resources/modules/system/layers/base/org/wildfly/naming-client/main/module.xml
  ee-feature-pack/galleon-shared/src/main/resources/modules/system/layers/base/org/wildfly/security/jakarta/security/main/module.xml
  ee/src/main/java/org/jboss/as/ee/managedbean/processors/JavaEEDependencyProcessor.java
  jsf/subsystem/src/test/resources/modules/com/sun/jsf-impl/main/module.xml
  jsf/subsystem/src/test/resources/modules/com/sun/jsf-impl/myfaces/module.xml
  jsf/subsystem/src/test/resources/modules/org/jboss/as/jsf-injection/1.2/module.xml
  jsf/subsystem/src/test/resources/modules/org/jboss/as/jsf-injection/main/module.xml
  jsf/subsystem/src/test/resources/modules/org/jboss/as/jsf-injection/myfaces/module.xml
  jsf/subsystem/src/test/resources/modules2/com/sun/jsf-impl/myfaces2/module.xml
  jsf/subsystem/src/test/resources/modules2/org/jboss/as/jsf-injection/bogus2/module.xml
  jsf/subsystem/src/test/resources/modules2/org/jboss/as/jsf-injection/myfaces2/module.xml
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/deployment/jcedeployment/jboss-deployment-structure.xml
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/ee/globalmodules/module.xml
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/jca/moduledeployment/module-jar.xml
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/jca/moduledeployment/module.xml
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/jca/moduledeployment/module1-jar.xml
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/jca/moduledeployment/module1.xml
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/naming/ObjectFactoryWithEnvironmentBindingTestCase-module.xml
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/weld/multideployment/module.xml
  testsuite/integration/basic/src/test/resources/org/wildfly/test/integration/web/annotationsmodule/jboss-deployment-structure1.xml
  testsuite/integration/elytron/src/test/java/org/wildfly/test/integration/elytron/jaspi/ConfiguredJaspiTestBase.java
  testsuite/integration/microprofile-tck/rest-client/module.xml
  testsuite/integration/src/test/xslt/module.xml
  testsuite/integration/web/src/test/java/org/jboss/as/test/integration/web/annotationsmodule/module.xml
  testsuite/layers/src/test/java/org/jboss/as/test/layers/LayersTestCase.java
Labels: ready-for-merge, deps-ok, 29.Alpha1

#16802 [WFLY-17932] Eliminating deprecated sun.jdk module usages
  docs/src/main/asciidoc/_developer-guide/Implicit_module_dependencies_for_deployments.adoc
  ee-feature-pack/galleon-shared/src/main/resources/modules/system/layers/base/com/github/ben-manes/caffeine/main/module.xml
  ee-feature-pack/galleon-shared/src/main/resources/modules/system/layers/base/com/google/code/gson/main/module.xml
  ee-feature-pack/galleon-shared/src/main/resources/modules/system/layers/base/io/reactivex/rxjava2/rxjava/main/module.xml
  ee-feature-pack/galleon-shared/src/main/resources/modules/system/layers/base/io/reactivex/rxjava3/rxjava/main/module.xml
  ee-feature-pack/galleon-shared/src/main/resources/modules/system/layers/base/io/undertow/jsp/main/module.xml
  ee-feature-pack/galleon-shared/src/main/resources/modules/system/layers/base/io/undertow/servlet/main/module.xml
  ee-feature-pack/galleon-shared/src/main/resources/modules/system/layers/base/javax/orb/api/main/module.xml
  ee-feature-pack/galleon-shared/src/main/resources/modules/system/layers/base/net/bytebuddy/main/module.xml
  ee-feature-pack/galleon-shared/src/main/resources/modules/system/layers/base/org/apache/activemq/artemis/journal/main/module.xml
  ee-feature-pack/galleon-shared/src/main/resources/modules/system/layers/base/org/apache/activemq/artemis/main/module.xml
  ee-feature-pack/galleon-shared/src/main/resources/modules/system/layers/base/org/hibernate/validator/main/module.xml
  ee-feature-pack/galleon-shared/src/main/resources/modules/system/layers/base/org/infinispan/main/module.xml
  ee-feature-pack/galleon-shared/src/main/resources/modules/system/layers/base/org/jboss/as/connector/main/module.xml
  ee-feature-pack/galleon-shared/src/main/resources/modules/system/layers/base/org/jboss/as/naming/main/module.xml
  ee-feature-pack/galleon-shared/src/main/resources/modules/system/layers/base/org/jboss/ironjacamar/impl/main/module.xml
  ee-feature-pack/galleon-shared/src/main/resources/modules/system/layers/base/org/jboss/jts/main/module.xml
  ee-feature-pack/galleon-shared/src/main/resources/modules/system/layers/base/org/jctools/main/module.xml
  ee-feature-pack/galleon-shared/src/main/resources/modules/system/layers/base/org/wildfly/clustering/service/main/module.xml
  ee-feature-pack/galleon-shared/src/main/resources/modules/system/layers/base/org/wildfly/extension/undertow/main/module.xml
  ee-feature-pack/galleon-shared/src/main/resources/modules/system/layers/base/org/wildfly/mod_cluster/undertow/main/module.xml
  galleon-pack/galleon-shared/src/main/resources/modules/system/layers/base/io/smallrye/common/annotation/main/module.xml
  galleon-pack/galleon-shared/src/main/resources/modules/system/layers/base/io/smallrye/common/classloader/main/module.xml
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/jca/classloading/AbstractDataSourceClassloadingTestCase.java
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/jca/classloading/custommodule/DatasourceCustomModulesTestCase.java
  testsuite/integration/basic/src/test/modules/org/jboss/test/testDriver/main/module.xml
  testsuite/layers/src/test/java/org/jboss/as/test/layers/LayersTestCase.java
Labels: ready-for-merge, deps-ok, 29.Alpha1

#13543 [WFLY-13834]/ [WFLY-18048] Document the new file encoding parameter added to Elytron audit logging. Add test for WFCORE-5106.
  docs/src/main/asciidoc/_elytron/Audit.adoc
  testsuite/integration/elytron/src/test/java/org/wildfly/test/integration/elytron/audit/FileAuditLogTestCase.java
  testsuite/shared/src/main/java/org/wildfly/test/security/common/elytron/FileAuditLog.java
Labels: core-upgrade-needed, Feature-Docs, deps-ok, 29.Alpha1

#16883 WFLY-18062: Upgrade HAL to 3.6.6.Final
  pom.xml
Labels: core-upgrade-needed, deps-ok, 29.Alpha1

#15340 [WFLY-16163] Integration tests and documentation for Elytron distributed-realm ignore-unavailable-realms ability
  docs/src/main/asciidoc/_elytron/components/Distributed_Security_Realm.adoc
  testsuite/integration/elytron/src/test/java/org/wildfly/test/integration/elytron/realm/DistributedRealmTestCase.java
  testsuite/shared/src/main/java/org/wildfly/test/security/common/elytron/DistributedRealm.java
Labels: core-upgrade-needed, Feature-Docs, deps-ok, 29.Alpha1

#16884 WFLY-18064 Upgrade SmallRye Fault Tolerance to 6.2.3
  pom.xml
Labels: deps-ok

#16895 [WFLY-18079] Mark OidcWithIdentityPropagationTestCase as intermittently failing effectively @Ignore-ing it
  testsuite/integration/elytron-oidc-client/src/test/java/org/wildfly/test/integration/elytron/oidc/client/propagation/OidcIdentityPropagationTestCase.java
Labels: deps-ok, 29.Alpha1

#16892 [WFLY-17934] Eliminating deprecated javax.xml.stream.api module usages - cleanup remaining bits
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/jca/moduledeployment/module-jar.xml
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/jca/moduledeployment/module1-jar.xml
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/jca/moduledeployment/module1.xml
Labels: deps-ok, 29.Alpha1
