Repository wildfly/wildfly, pull requests merged in 2024-07, with the labels that each got.

#17995 [WFLY-19480] Upgrade WildFly Core to 25.0.0.Beta5
  pom.xml
Labels: deps-ok, 33.x

#17565 [WFLY-18881] CopyOnWriteArrayListMultiMap refactor
  connector/src/main/java/org/jboss/as/connector/util/CopyOnWriteArrayListMultiMap.java
Labels: ready-for-merge, 33.x

#17923 [WFLY-11496] Use the correct SocketPermission in RolloutPlanTestCase
  testsuite/domain/src/test/java/org/jboss/as/test/integration/domain/management/cli/RolloutPlanTestCase.java
  testsuite/domain/src/test/java/org/jboss/as/test/integration/domain/management/cli/RolloutPlanTestServlet.java
Labels: ready-for-merge, 33.x

#17984 [WFLY-19468] Remove okhttp and okio-jvm from common-expansion
  boms/common-expansion/pom.xml
  galleon-pack/galleon-shared/pom.xml
  pom.xml
Labels: ready-for-merge, deps-changed, 33.x

#17988 [WFLY-19471][WFLY-19472] WildFly Preview EE 11 Servlet and Security API updates
  boms/preview-ee/pom.xml
Labels: ready-for-merge, deps-ok, 33.x

#17994 WFLY-19474 Upgrade Infinispan to 14.0.29.Final.
  pom.xml
Labels: ready-for-merge, deps-ok, 33.x

#18000 [WFLY-19489] Upgrade HAL to 3.7.4.Final
  pom.xml
Labels: deps-ok, 33.x

#17743 [WFLY-19152] Add indices of APIs annotated with annotations indicating unstable API
  dist/src/verifier/verifications.xml
  docs/src/main/asciidoc/_admin-guide/subsystem-configuration/Core_Management.adoc
  ee-dist/src/verifier/verifications.xml
  ee-feature-pack/galleon-feature-pack/pom.xml
  ee-feature-pack/galleon-local/src/main/resources/configs/domain/model.xml
  ee-feature-pack/galleon-local/src/main/resources/configs/standalone/model.xml
  ee-feature-pack/galleon-shared/assembly.xml
  ee-feature-pack/galleon-shared/pom.xml
  ee-feature-pack/galleon-shared/src/main/resources/packages/unstable-api-annotation-index.wildfly-ee-feature-pack/package.xml
  ee-feature-pack/galleon-shared/src/main/resources/packages/unstable-api-annotation-index.wildfly-ee-feature-pack/pm/wildfly/tasks.xml
  galleon-pack/galleon-feature-pack/pom.xml
  galleon-pack/galleon-local/src/main/resources/configs/domain/model.xml
  galleon-pack/galleon-local/src/main/resources/configs/standalone/model.xml
  galleon-pack/galleon-shared/assembly.xml
  galleon-pack/galleon-shared/pom.xml
  galleon-pack/galleon-shared/src/main/resources/packages/unstable-api-annotation-index.wildfly-galleon-pack/package.xml
  galleon-pack/galleon-shared/src/main/resources/packages/unstable-api-annotation-index.wildfly-galleon-pack/pm/wildfly/tasks.xml
  pom.xml
  testsuite/integration/basic/pom.xml
  testsuite/integration/basic/src/test/java/org/wildfly/test/integration/unstable_api_annotation/UnstableApiAnnotationIndexTestCase.java
  testsuite/integration/basic/src/test/java/org/wildfly/test/integration/unstable_api_annotation/dummy/Dummy.java
  testsuite/integration/basic/src/test/java/org/wildfly/test/integration/unstable_api_annotation/jar/JarClassA.java
  testsuite/integration/basic/src/test/java/org/wildfly/test/integration/unstable_api_annotation/jar/JarClassB.java
  testsuite/integration/basic/src/test/java/org/wildfly/test/integration/unstable_api_annotation/jar2/Jar2ClassA.java
  testsuite/integration/basic/src/test/java/org/wildfly/test/integration/unstable_api_annotation/jar2/Jar2ClassB.java
  testsuite/integration/basic/src/test/java/org/wildfly/test/integration/unstable_api_annotation/jar2/Jar2ClassC.java
  testsuite/integration/basic/src/test/java/org/wildfly/test/integration/unstable_api_annotation/jar2/Jar2ClassD.java
  testsuite/integration/basic/src/test/java/org/wildfly/test/integration/unstable_api_annotation/jar2/Jar2ClassE.java
  testsuite/integration/basic/src/test/java/org/wildfly/test/integration/unstable_api_annotation/jar2/Jar2ClassF.java
  testsuite/integration/basic/src/test/java/org/wildfly/test/integration/unstable_api_annotation/jar2/Jar2ClassG.java
  testsuite/integration/basic/src/test/java/org/wildfly/test/integration/unstable_api_annotation/jar2/Jar2ClassH.java
  testsuite/integration/basic/src/test/java/org/wildfly/test/integration/unstable_api_annotation/war/Servlet.java
  testsuite/integration/basic/src/test/java/org/wildfly/test/integration/unstable_api_annotation/war/WarClassA.java
  testsuite/integration/basic/src/test/java/org/wildfly/test/integration/unstable_api_annotation/war/WarClassB.java
  testsuite/integration/basic/src/test/java/org/wildfly/test/integration/unstable_api_annotation/war/WarClassC.java
Labels: core-upgrade-needed, Feature, missing-reqs, deps-ok, 33.x

#17420 [WFLY-18763] Add an example standalone-core-microprofile.xml example configuration.
  build/pom.xml
  dist/pom.xml
  galleon-pack/galleon-local/src/main/resources/packages/docs.examples.configs/package.xml
  galleon-pack/galleon-local/src/main/resources/packages/docs.examples.configs/pm/wildfly/tasks.xml
  preview/galleon-local/src/main/resources/packages/docs.examples.configs/pm/wildfly/tasks.xml
  testsuite/integration/manualmode-expansion/pom.xml
Labels: Feature, Blocker, deps-ok, 33.x

#18019 [WFLY-19470] Upgrade Narayana to 7.0.2.Final
  pom.xml
Labels: deps-ok

#18018 [WFLY-19506] Upgrade to unstable API scanner plugin 1.0.0.Final
  pom.xml
Labels: deps-ok

#18009 [WFLY-19493] Upgrade the OWASP Dependency Check Plugin to 10.0.1
  pom.xml
Labels: deps-ok

#17997 [WFLY-19482] Upgrade Arquillian Core to 1.8.1.Final.
  pom.xml
Labels: deps-ok

#17970 [WFLY-19442]: [DOCS] Adding documentation covering the umanaged deployments
  docs/src/main/asciidoc/_admin-guide/management-tasks/YAML_Configuration_file.adoc
Labels: Feature-Docs, Critical, 33.x

#18013 [WFLY-19498] Upgrade WildFly Preview to Weld API 6.0.0.Beta5 and Weld…
  boms/preview-ee/pom.xml
  testsuite/integration/elytron-oidc-client/pom.xml
  testsuite/integration/elytron/pom.xml
Labels: deps-ok, EE11

#18020 [WFLY-19339] If Naming subsystem is activated then add both jdk.naming.dns & jdk.naming.rmi dependencies to deployments
  naming/src/main/java/org/jboss/as/naming/deployment/JdkDependenciesProcessor.java
  naming/src/main/java/org/jboss/as/naming/subsystem/NamingSubsystemAdd.java
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/naming/dns/DnsContextLookupBean.java
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/naming/dns/DnsContextLookupTestCase.java
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/naming/rmi/RmiContextLookupTestCase.java
Labels: 33.x

#18016 [WFLY-19504] Remove MyFaces-related test from JSFDeploymentProcessorTestCase
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/jsf/version/JSFDeploymentProcessorTestCase.java
Labels: 33.x

#18025 [WFLY-19434] Fix the Jakarta EE version in the installation root README
  ee-feature-pack/galleon-shared/src/main/resources/content/README.txt
Labels: 33.x

#18026 [WFLY-18547][WFLY-19517] Set attributes to default values if available
  messaging-activemq/subsystem/src/main/java/org/wildfly/extension/messaging/activemq/ActiveMQServerService.java
  messaging-activemq/subsystem/src/main/java/org/wildfly/extension/messaging/activemq/AddressSettingAdd.java
  messaging-activemq/subsystem/src/main/java/org/wildfly/extension/messaging/activemq/AddressSettingDefinition.java
  messaging-activemq/subsystem/src/main/java/org/wildfly/extension/messaging/activemq/AddressSettingsWriteHandler.java
  messaging-activemq/subsystem/src/main/java/org/wildfly/extension/messaging/activemq/ServerAdd.java
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/messaging/mgmt/AddressSettingsTestCase.java
Labels: 33.x

#18032 (docs) WFLY-17323 Update out-of-date and fix CLI script examples in mod_cluster section
  docs/src/main/asciidoc/_high-availability/load-balancing/mod_cluster_Subsystem.adoc
Labels: 33.x

#17844 [WFLY-19274] When SocketsAndInterfacesTestCase searches for a non-def…
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/management/api/SocketsAndInterfacesTestCase.java
Labels: 33.x

#18033 [WFLY-19525] Switching JSTL implementation from org.glassfish.web:jakarta.servlet.jsp.jstl to org.glassfish.wasp:wasp
  boms/common-ee/pom.xml
  ee-feature-pack/galleon-shared/pom.xml
  ee-feature-pack/galleon-shared/src/main/resources/modules/system/layers/base/jakarta/servlet/jstl/api/main/module.xml
  pom.xml
Labels: deps-changed, Critical, 33.x

#17966 WFLY-19441 Decouple SNI host name configuration from physical hostnames and auto-disable hostname validation when unspecified.
  clustering/infinispan/extension/src/main/java/org/jboss/as/clustering/infinispan/subsystem/remote/RemoteCacheContainerConfigurationServiceConfigurator.java
  clustering/infinispan/extension/src/main/java/org/jboss/as/clustering/infinispan/subsystem/remote/SecurityServiceConfigurator.java
Labels: Blocker, 33.x

#18035 [WFLY-19437]: Upgrade Apache Artemis to 2.35.0
  pom.xml
Labels: deps-ok

#17737 [WFLY-19147] Let `mp.health.disable-default-procedures=true` disable all the default procedures when set at application level
  docs/src/main/asciidoc/_admin-guide/subsystem-configuration/MicroProfile_Health.adoc
  microprofile/health-smallrye/src/main/java/org/wildfly/extension/microprofile/health/MicroProfileHealthReporter.java
  microprofile/health-smallrye/src/main/java/org/wildfly/extension/microprofile/health/MicroProfileHealthReporterService.java
  microprofile/health-smallrye/src/main/java/org/wildfly/extension/microprofile/health/_private/MicroProfileHealthLogger.java
  microprofile/health-smallrye/src/main/java/org/wildfly/extension/microprofile/health/deployment/CDIExtension.java
  testsuite/integration/microprofile-tck/health/pom.xml
  testsuite/integration/microprofile-tck/health/src/test/resources/arquillian.xml
  testsuite/integration/microprofile/pom.xml
  testsuite/integration/microprofile/src/test/java/org/wildfly/test/integration/microprofile/health/MicroProfileHealthDisabledDefaultProceduresHTTPEndpointTestCase.java
  testsuite/integration/microprofile/src/test/java/org/wildfly/test/integration/microprofile/health/MicroProfileHealthDisabledDefaultProceduresMultiWarHTTPEndpointTestCase.java
  testsuite/integration/microprofile/src/test/java/org/wildfly/test/integration/microprofile/health/MicroProfileHealthDisabledDefaultProceduresMultiWarOperationTestCase.java
  testsuite/integration/microprofile/src/test/java/org/wildfly/test/integration/microprofile/health/MicroProfileHealthDisabledDefaultProceduresMultiWarTestBase.java
  testsuite/integration/microprofile/src/test/java/org/wildfly/test/integration/microprofile/health/MicroProfileHealthDisabledDefaultProceduresOperationTestCase.java
  testsuite/integration/microprofile/src/test/java/org/wildfly/test/integration/microprofile/health/MicroProfileHealthDisabledDefaultProceduresTestBase.java
  testsuite/integration/microprofile/src/test/java/org/wildfly/test/integration/microprofile/health/MicroProfileHealthUtils.java
Labels: deps-ok, 33.x

#18039 [WFLY-19529] Upgrade the OWASP dependency-check plugin to 10.0.2
  pom.xml
Labels: Blocker, deps-ok, 33.x

#18017 [WFLY-19287] Fail boot if EE 11 APIs are used and the security manage…
  ee/src/main/java/org/jboss/as/ee/logging/EeLogger.java
  ee/src/main/java/org/jboss/as/ee/subsystem/EeSubsystemAdd.java
  testsuite/integration/manualmode/src/test/java/org/wildfly/test/manual/securitymanager/SecurityManagerRejectedTestCase.java
  testsuite/integration/manualmode/src/test/resources/arquillian.xml
  testsuite/integration/pom.xml
  testsuite/integration/secman/pom.xml
  testsuite/preview/manualmode/pom.xml
  testsuite/preview/manualmode/src/test/java/org/wildfly/test/manual/securitymanager/SecurityManagerRejectedTestCase.java
  testsuite/preview/manualmode/src/test/resources/arquillian.xml
Labels: deps-ok, Critical, 33.x

#18046 WFLY-19518 Nightly 'Standard - MP Certifications - JDK 11' CI job fails
  testsuite/integration/microprofile-tck/certification/pom.xml
Labels: deps-ok, 33.x

#18056 Revert "[WFLY-19525] Switching JSTL implementation from org.glassfish.web:jakarta.servlet.jsp.jstl to org.glassfish.wasp:wasp"
  boms/common-ee/pom.xml
  ee-feature-pack/galleon-shared/pom.xml
  ee-feature-pack/galleon-shared/src/main/resources/modules/system/layers/base/jakarta/servlet/jstl/api/main/module.xml
  pom.xml
Labels: deps-changed

#18060 [WFLY-19547] Upgrade WildFly Core to 25.0.0.Final
  pom.xml
Labels: deps-ok

#18059 Fix for WFLY-19544, Allows to make a Galleon package dependency valid for a given stability level
  ee-feature-pack/galleon-feature-pack/pom.xml
  ee-feature-pack/galleon-local/src/main/resources/configs/standalone/model.xml
  galleon-pack/galleon-feature-pack/pom.xml
  pom.xml
  preview/feature-pack/pom.xml
Labels: deps-ok

#18051 [WFLY-19541] Upgrading Jastow to 2.2.8.Final
  pom.xml
Labels: deps-ok

#18064 [WFLY-19523] Always clear the deployment CL from WildFlyConfiguration…
  jaxrs/src/main/java/org/jboss/as/jaxrs/deployment/JaxrsIntegrationProcessor.java
Labels: Critical, 33.x

#17962 WFLY-19419 Distributed timer service should consolidate timeouts that would execute in the past
  clustering/ejb/cache/src/main/java/org/wildfly/clustering/ejb/cache/timer/IntervalTimerMetaDataEntry.java
  clustering/ejb/cache/src/main/java/org/wildfly/clustering/ejb/cache/timer/ScheduleTimerOperatorFactory.java
  clustering/ejb/cache/src/test/java/org/wildfly/clustering/ejb/cache/timer/AbstractIntervalTimerMetaDataEntryTestCase.java
  clustering/ejb/infinispan/src/main/java/org/wildfly/clustering/ejb/infinispan/timer/TimerScheduler.java
  ejb3/src/main/java/org/jboss/as/ejb3/timerservice/CalendarTimerTask.java
  testsuite/integration/clustering/src/test/java/org/jboss/as/test/clustering/cluster/ejb/timer/AbstractTimerServiceTestCase.java
  testsuite/integration/clustering/src/test/java/org/jboss/as/test/clustering/cluster/ejb/timer/CoalesceMissedTimeoutsTestCase.java
  testsuite/integration/clustering/src/test/java/org/jboss/as/test/clustering/cluster/ejb/timer/beans/BurstPersistentCalendarTimerBean.java
  testsuite/integration/clustering/src/test/java/org/jboss/as/test/clustering/cluster/ejb/timer/beans/BurstPersistentIntervalTimerBean.java
  testsuite/integration/clustering/src/test/java/org/jboss/as/test/clustering/cluster/ejb/timer/beans/BurstPersistentTimerBean.java
  testsuite/integration/clustering/src/test/java/org/jboss/as/test/clustering/cluster/ejb/timer/servlet/AbstractTimerServlet.java
  testsuite/integration/clustering/src/test/java/org/jboss/as/test/clustering/cluster/ejb/timer/servlet/BurstTimerServlet.java
  testsuite/integration/clustering/src/test/java/org/jboss/as/test/clustering/cluster/ejb/timer/servlet/TimerServlet.java
  testsuite/integration/clustering/src/test/java/org/jboss/as/test/clustering/single/ejb/timer/CoalesceMissedTimeoutsTestCase.java
Labels: 34.x

#18052 [WFLY-19542] Upgrade ASM to 9.7
  pom.xml
Labels: deps-ok

#18062 WFLY-19548 Remove redundant capability name String instances for core capabilities
  appclient/src/main/java/org/jboss/as/appclient/service/ApplicationClientDeploymentService.java
  appclient/src/main/java/org/jboss/as/appclient/subsystem/AppClientSubsystemAdd.java
  appclient/src/main/java/org/jboss/as/appclient/subsystem/AppClientSubsystemResourceDefinition.java
  batch-jberet/src/main/java/org/wildfly/extension/batch/jberet/_private/Capabilities.java
  batch-jberet/src/main/java/org/wildfly/extension/batch/jberet/deployment/BatchEnvironmentProcessor.java
  clustering/common/src/main/java/org/jboss/as/clustering/controller/CommonRequirement.java
  clustering/common/src/main/java/org/jboss/as/clustering/controller/CommonUnaryRequirement.java
  ee-feature-pack/galleon-shared/src/main/resources/modules/system/layers/base/org/jboss/as/clustering/common/main/module.xml
  ee-feature-pack/galleon-shared/src/main/resources/modules/system/layers/base/org/jboss/as/ee/main/module.xml
  ee-feature-pack/galleon-shared/src/main/resources/modules/system/layers/base/org/jboss/as/mail/main/module.xml
  ee-feature-pack/galleon-shared/src/main/resources/modules/system/layers/base/org/wildfly/extension/health/main/module.xml
  ee/src/main/java/org/jboss/as/ee/concurrent/resource/definition/ManagedExecutorDefinitionInjectionSource.java
  ee/src/main/java/org/jboss/as/ee/concurrent/resource/definition/ManagedScheduledExecutorDefinitionInjectionSource.java
  ee/src/main/java/org/jboss/as/ee/subsystem/EeCapabilities.java
  ee/src/main/java/org/jboss/as/ee/subsystem/GlobalDirectoryResourceDefinition.java
  ee/src/main/java/org/jboss/as/ee/subsystem/ManagedExecutorServiceAdd.java
  ee/src/main/java/org/jboss/as/ee/subsystem/ManagedScheduledExecutorServiceAdd.java
  ee/src/test/java/org/jboss/as/ee/subsystem/EeSubsystemTestCase.java
  ejb3/src/main/java/org/jboss/as/ejb3/subsystem/FileDataStoreAdd.java
  galleon-pack/galleon-shared/src/main/resources/modules/system/layers/base/org/wildfly/extension/micrometer/main/module.xml
  galleon-pack/galleon-shared/src/main/resources/modules/system/layers/base/org/wildfly/extension/microprofile/config-smallrye/main/module.xml
  galleon-pack/galleon-shared/src/main/resources/modules/system/layers/base/org/wildfly/extension/microprofile/opentracing-smallrye/main/module.xml
  health/src/main/java/org/wildfly/extension/health/HealthSubsystemDefinition.java
  health/src/main/java/org/wildfly/extension/health/ServerProbes.java
  health/src/main/java/org/wildfly/extension/health/ServerProbesService.java
  jdr/src/main/java/org/jboss/as/jdr/JdrReportService.java
  jdr/src/main/java/org/jboss/as/jdr/JdrReportSubsystemDefinition.java
  jdr/src/test/java/org/jboss/as/jdr/JdrSubsystemTestCase.java
  legacy/opentracing-extension/pom.xml
  legacy/opentracing-extension/src/main/java/org/wildfly/extension/microprofile/opentracing/TracerAttributes.java
  mail/src/main/java/org/jboss/as/mail/extension/MailServerDefinition.java
  mail/src/main/java/org/jboss/as/mail/extension/MailSessionAdd.java
  mail/src/test/java/org/jboss/as/mail/extension/MailSubsystemTestCase.java
  messaging-activemq/subsystem/src/main/java/org/wildfly/extension/messaging/activemq/Capabilities.java
  messaging-activemq/subsystem/src/main/java/org/wildfly/extension/messaging/activemq/MessagingSubsystemAdd.java
  messaging-activemq/subsystem/src/main/java/org/wildfly/extension/messaging/activemq/ServerAdd.java
  messaging-activemq/subsystem/src/main/java/org/wildfly/extension/messaging/activemq/TransportConfigOperationHandlers.java
  messaging-activemq/subsystem/src/main/java/org/wildfly/extension/messaging/activemq/jms/ExternalConnectionFactoryAdd.java
  messaging-activemq/subsystem/src/main/java/org/wildfly/extension/messaging/activemq/jms/ExternalPooledConnectionFactoryService.java
  metrics/src/main/java/org/wildfly/extension/metrics/MetricsCollectorService.java
  metrics/src/main/java/org/wildfly/extension/metrics/MetricsSubsystemDefinition.java
  microprofile/config-smallrye/src/main/java/org/wildfly/extension/microprofile/config/smallrye/ConfigSourceDefinition.java
  microprofile/config-smallrye/src/main/java/org/wildfly/extension/microprofile/config/smallrye/ConfigSourceRootRegistrationService.java
  mod_cluster/undertow/src/main/java/org/wildfly/mod_cluster/undertow/UndertowEventHandlerAdapterService.java
  observability/micrometer/src/main/java/org/wildfly/extension/micrometer/MicrometerSubsystemRegistrar.java
  transactions/src/main/java/org/jboss/as/txn/subsystem/TransactionSubsystemAdd.java
  undertow/src/test/java/org/wildfly/extension/undertow/DefaultInitialization.java
  undertow/src/test/java/org/wildfly/extension/undertow/RuntimeInitialization.java
Labels: deps-ok

#18071 [WFLY-19570] Update HostExcludesTestCase configuration to work with WF33
  pom.xml
  testsuite/domain/src/test/java/org/jboss/as/test/integration/domain/HostExcludesTestCase.java
Labels: deps-ok

#18073 [WFLY-19572] Upgrade Arquillian Core to 1.9.1.Final, Arquillian Jakar…
  boms/standard-test-expansion/pom.xml
  boms/standard-test/pom.xml
  pom.xml
Labels: deps-ok

#18074 [WFLY-19572] Upgrade Arquillian Core to 1.9.1.Final, Arquillian Jakar…
  boms/standard-test-expansion/pom.xml
  boms/standard-test/pom.xml
  pom.xml
Labels: 33.x

#18079 [WFLY-19578] Upgrade WildFly Core to 26.0.0.Beta1
  pom.xml
Labels: deps-changed

#18075 [WFLY-19576]:Upgrade CXF to 4.0.5
  pom.xml
Labels: deps-ok

#18082 WFLY-19584 Fix typo in testsuite pom.xml: goal "provisioning" to "provision"
  testsuite/integration/basic/pom.xml
  testsuite/integration/elytron-oidc-client/pom.xml
  testsuite/integration/elytron/pom.xml
  testsuite/integration/microprofile/pom.xml
Labels: deps-ok

#18083 [WFLY-19585][WFLY-19586] Upgrade SmallRye Reactive Messaging (4.24.0) and SmallRye Config (3.9.0)
  pom.xml
Labels: deps-ok
