Repository wildfly/wildfly, pull requests merged in 2024-01, with the labels that each got.

#17464 [WFLY-18810] Update Micrometer to 1.12.0
  boms/common-expansion/pom.xml
  galleon-pack/galleon-shared/pom.xml
  galleon-pack/galleon-shared/src/main/resources/modules/system/layers/base/io/micrometer/main/module.xml
  pom.xml
Labels: deps-changed

#17513 [WFLY-18729]: Upgrade Netty from 4.1.100.Final to 4.1.104.Final
  pom.xml
Labels: deps-ok

#17516 Fix for WFLY-18897, testsuite manual-expansion is missing the parsson dependency
  testsuite/integration/manualmode-expansion/pom.xml
Labels: deps-ok

#17520 [WFLY-18906] Upgrade WildFly Core to 23.0.0.Beta5
  pom.xml
Labels: deps-ok

#17521 [WFLY-18908] Update MP platform version to 6.1
  pom.xml
Labels: deps-ok

#17519 WFLY-18905 / Upgrade JBeret to 2.2.0.Final
  pom.xml
Labels: deps-ok

#17518 [WFLY-18904]: Update ANTLR to 4.13.0 for Hibernate 6.4
  pom.xml
Labels: deps-ok

#17523 [WFLY-18915] Upgrade HAL to 3.6.17.Final
  pom.xml
Labels: deps-ok

#17524 [WFLY-18916] [WFLY-18917] Upgrade RESTEasy and RESTEasy MicroProfile
  pom.xml
Labels: deps-ok

#17530 Fix for WFLY-18923, Upgrade to WildFly Glow 1.0.0.Beta5
  pom.xml
  testsuite/integration/clustering/pom.xml
Labels: deps-ok

#17284 [WFLY-17772] Migrate from Apache DS to Apache Kerby for Kerberos testing
  testsuite/integration/elytron/pom.xml
  testsuite/integration/elytron/src/test/java/org/wildfly/test/integration/elytron/http/SpnegoMechTestCase.java
Labels: deps-ok, 31.x

#17537 WFLY-18890 docs/schema does not contain orm_3-1.xsd
  jpa/hibernate6/src/main/resources/schema/orm_3_1.xsd
Labels: deps-ok

#17534 [WFLY-18880] Add missing org.wildfly.clustering.marshalling.spi dep t…
  ee-feature-pack/galleon-shared/src/main/resources/modules/system/layers/base/org/wildfly/clustering/ee/cache/main/module.xml
Labels: Critical, 31.x

#17330 [WFLY-18562] re-evaluated test exclusions for ts.preview and ts.boota…
  testsuite/integration/basic/pom.xml
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/ejb/management/deployments/EjbJarInEarRuntimeResourcesMDBTestCase.java
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/ejb/management/deployments/EjbJarRuntimeResourceTestBase.java
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/ejb/management/deployments/EjbJarRuntimeResourcesMDBTestCase.java
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/ejb/pool/lifecycle/PooledEJBLifecycleTestCase.java
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/jsf/managedbean/managedproperty/JSF23ConfigurationBean.java
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/jsf/managedbean/managedproperty/ManagedPropertyInjectionTestCase.java
  testsuite/integration/basic/src/test/java/org/wildfly/test/integration/metrics/MetricsFromJVMTestCase.java
  testsuite/integration/pom.xml
Labels: deps-ok, 31.x

#17469 [WFLY-18820]: Queue creation might fail if auto-create-addresses is set to false.
  messaging-activemq/subsystem/src/main/java/org/wildfly/extension/messaging/activemq/jms/DestinationConfiguration.java
Labels: 31.x

#17540 [WFLY-18298] Upgrade H2 from 2.2.220 to 2.2.224
  pom.xml
Labels: deps-ok, 31.x

#17538 WFLY-18927 Upgrade to Hibernate 6.4.2.Final release
  pom.xml
Labels: deps-ok, 31.x

#17543 [WFLY-18934] Upgrade WildFly Core to 23.0.0.Final
  pom.xml
Labels: deps-ok

#17545 [WFLY-18855] MicroProfile spec support table is out of date
  docs/src/main/asciidoc/Getting_Started_Guide.adoc
Labels: Blocker, 31.x

#17536 [WFLY-18560] Replace layer-spec refs to javax EE api modules with jak…
  ee-feature-pack/galleon-shared/src/main/resources/layers/standalone/ee/layer-spec.xml
  ee-feature-pack/galleon-shared/src/main/resources/layers/standalone/jsonb/layer-spec.xml
  ee-feature-pack/galleon-shared/src/main/resources/layers/standalone/jsonp/layer-spec.xml
Labels: 31.x

#17362 WFLY-18708 Disable counter-productive "distributable" behavior in Mojarra
  jsf/subsystem/pom.xml
  jsf/subsystem/src/main/java/org/jboss/as/jsf/deployment/JSFMetadataProcessor.java
  jsf/subsystem/src/main/java/org/jboss/as/jsf/deployment/NonDistributableServletContextListener.java
Labels: deps-ok, 31.x

#17542 [WFLY-18717] Update the WildFly vs WildFly Preview document for curre…
  docs/src/main/asciidoc/WildFly_and_WildFly_Preview.adoc
Labels: Critical, 31.x

#17549 [WFLY-18940] Upgrade WildFly Core to 23.0.1.Final
  pom.xml
Labels: deps-ok, 31.x

#17541 [WFLY-18930][WFLY-18931] Upgrade mvc-krazo integration to 0.8.2.Final; fix observability layer doc
  docs/src/main/asciidoc/_galleon/Galleon_layers.adoc
  pom.xml
Labels: Blocker, deps-ok, 31.x

#17547 [WFLY-18856] Document stability levels
  docs/src/main/asciidoc/_admin-guide/Core_management_concepts.adoc
  docs/src/main/asciidoc/_admin-guide/Feature_stability_levels.adoc
  docs/src/main/asciidoc/_admin-guide/management-tasks/Command_line_parameters.adoc
  docs/src/main/asciidoc/_galleon/Galleon_provisioning.adoc
Labels: Critical, 31.x

#17555 WFLY-18946 Upgrade Infinispan to 14.0.22.Final
  clustering/infinispan/extension/src/main/java/org/jboss/as/clustering/infinispan/client/ManagedRemoteCache.java
  pom.xml
Labels: deps-ok
