Repository wildfly/wildfly, pull requests merged in 2024-09, with the labels that each got.

#18160 WFLY-19688 Bump Weld version to 5.1.3.Final
  clustering/weld/core/src/main/java/org/wildfly/clustering/weld/contexts/SerializableContextualInstanceImplMarshaller.java
  pom.xml
Labels: deps-ok

#18164 [WFLY-19697] Add a preview-test-bom and a preview-test-expansion-bom.…
  boms/preview-test-expansion/pom.xml
  boms/preview-test/pom.xml
  pom.xml
  testsuite/integration/legacy/pom.xml
  testsuite/integration/manualmode-expansion/pom.xml
  testsuite/integration/microprofile-tck/pom.xml
  testsuite/integration/microprofile/pom.xml
  testsuite/integration/pom.xml
  testsuite/layers-expansion/pom.xml
  testsuite/pom.xml
  testsuite/preview/pom.xml
Labels: deps-ok

#18163 [WFLY-19695] Upgrade to Hibernate Search 7.1.2
  pom.xml
Labels: deps-ok

#18078 WFLY-19573 Expand WeldCapability to include build compatible extensions
  testsuite/integration/basic/pom.xml
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/weld/extensions/buildcompatible/subsystem/BCEExtension.java
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/weld/extensions/buildcompatible/subsystem/DummyBean.java
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/weld/extensions/buildcompatible/subsystem/RegisteredBean.java
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/weld/extensions/buildcompatible/subsystem/RegisteredExtension.java
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/weld/extensions/buildcompatible/subsystem/SubsystemBceRegistrationTest.java
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/weld/extensions/buildcompatible/subsystem/build-compatible-extension-module.xml
  testsuite/integration/basic/src/test/modules/test/build-compatible-extension/main/module.xml
  weld/common/src/main/java/org/jboss/as/weld/WeldCapability.java
  weld/common/src/main/java/org/jboss/as/weld/deployment/WeldPortableExtensions.java
  weld/common/src/main/java/org/jboss/as/weld/logging/WeldLogger.java
  weld/subsystem/src/main/java/org/jboss/as/weld/WeldCapabilityImpl.java
  weld/subsystem/src/main/java/org/jboss/as/weld/deployment/processors/WeldDeploymentProcessor.java
  weld/subsystem/src/main/java/org/jboss/as/weld/deployment/processors/WeldPortableExtensionProcessor.java
Labels: deps-ok

#18167 Fix for WFLY-19702, Replace usage of wildfly-jar-maven-plugin with wildfly-maven-plugin
  pom.xml
  testsuite/integration/basic/pom.xml
  testsuite/integration/clustering/pom.xml
  testsuite/integration/elytron-oidc-client/pom.xml
  testsuite/integration/elytron/pom.xml
  testsuite/integration/microprofile-tck/config/pom.xml
  testsuite/integration/microprofile-tck/pom.xml
  testsuite/integration/microprofile-tck/rest-client/pom.xml
  testsuite/integration/microprofile/pom.xml
  testsuite/integration/smoke/pom.xml
  testsuite/integration/web/pom.xml
  testsuite/pom.xml
  testsuite/preview/basic/pom.xml
Labels: deps-ok

#18177 [WFLY-19716] Upgrade the wildfly-maven-plugin to 5.0.1.Final.
  pom.xml
Labels: deps-ok

#18121 [WFLY-19638] Upgrade com.google.guava:failureaccess from 1.0.1 to 1.0.2
  pom.xml
Labels: deps-ok

#18122 [WFLY-19639] Update guava from 32.1.2-jre to 33.0.0-jre
  pom.xml
Labels: deps-changed

#18186 [WFLY-19732] Suppress CVE-2024-7885 as it is addressed under UNDERTOW-2429.
  sca-overrides/owasp-suppressions.xml
Labels: Blocker, 33.x

#18180 [WFLY-19683][WFLY-19730] Provide SSLContext via the new ClientCustomizers
  galleon-pack/galleon-shared/src/main/resources/modules/system/layers/base/io/smallrye/reactive/messaging/connector/amqp/main/module.xml
  galleon-pack/galleon-shared/src/main/resources/modules/system/layers/base/io/smallrye/reactive/messaging/connector/kafka/main/module.xml
  galleon-pack/galleon-shared/src/main/resources/modules/system/layers/base/io/smallrye/reactive/messaging/connector/main/module.xml
  galleon-pack/galleon-shared/src/main/resources/modules/system/layers/base/io/vertx/grpc-common/main/module.xml
  galleon-pack/galleon-shared/src/main/resources/modules/system/layers/base/org/wildfly/reactive/messaging/amqp/main/module.xml
  galleon-pack/galleon-shared/src/main/resources/modules/system/layers/base/org/wildfly/reactive/messaging/kafka/main/module.xml
  microprofile/reactive-messaging-smallrye/amqp/pom.xml
  microprofile/reactive-messaging-smallrye/amqp/src/main/java/org/wildfly/microprofile/reactive/messaging/config/amqp/ssl/context/AmqpDynamicDeploymentProcessorAdder.java
  microprofile/reactive-messaging-smallrye/amqp/src/main/java/org/wildfly/microprofile/reactive/messaging/config/amqp/ssl/context/AmqpReactiveMessagingCdiExtension.java
  microprofile/reactive-messaging-smallrye/amqp/src/main/java/org/wildfly/microprofile/reactive/messaging/config/amqp/ssl/context/AmqpReactiveMessagingSslConfigProcessor.java
  microprofile/reactive-messaging-smallrye/amqp/src/main/java/org/wildfly/microprofile/reactive/messaging/config/amqp/ssl/context/_private/AmqpClientCustomizer.java
  microprofile/reactive-messaging-smallrye/amqp/src/main/resources/META-INF/services/org.wildfly.microprofile.reactive.messaging.common.DynamicDeploymentProcessorAdder
  microprofile/reactive-messaging-smallrye/common/src/main/java/org/wildfly/microprofile/reactive/messaging/common/DynamicDeploymentProcessorAdder.java
  microprofile/reactive-messaging-smallrye/common/src/main/java/org/wildfly/microprofile/reactive/messaging/common/ReactiveMessagingAttachments.java
  microprofile/reactive-messaging-smallrye/common/src/main/java/org/wildfly/microprofile/reactive/messaging/common/security/BaseReactiveMessagingSslConfigProcessor.java
  microprofile/reactive-messaging-smallrye/common/src/main/java/org/wildfly/microprofile/reactive/messaging/common/security/ElytronSSLContextRegistry.java
  microprofile/reactive-messaging-smallrye/extension/src/main/java/org/wildfly/extension/microprofile/reactive/messaging/MicroProfileReactiveMessagingSubsystemDefinition.java
  microprofile/reactive-messaging-smallrye/extension/src/main/java/org/wildfly/extension/microprofile/reactive/messaging/deployment/ReactiveMessagingDependencyProcessor.java
  microprofile/reactive-messaging-smallrye/kafka/pom.xml
  microprofile/reactive-messaging-smallrye/kafka/src/main/java/org/wildfly/microprofile/reactive/messaging/config/kafka/ssl/context/KafkaClientCustomizer.java
  microprofile/reactive-messaging-smallrye/kafka/src/main/java/org/wildfly/microprofile/reactive/messaging/config/kafka/ssl/context/KafkaDynamicDeploymentProcessorAdder.java
  microprofile/reactive-messaging-smallrye/kafka/src/main/java/org/wildfly/microprofile/reactive/messaging/config/kafka/ssl/context/KafkaReactiveMessagingSslConfigProcessor.java
  microprofile/reactive-messaging-smallrye/kafka/src/main/java/org/wildfly/microprofile/reactive/messaging/config/kafka/ssl/context/WildFlyKafkaSSLEngineFactory.java
  microprofile/reactive-messaging-smallrye/kafka/src/main/java/org/wildfly/microprofile/reactive/messaging/config/kafka/ssl/context/_private/MicroProfileReactiveMessagingKafkaLogger.java
  microprofile/reactive-messaging-smallrye/kafka/src/main/resources/META-INF/beans.xml
  microprofile/reactive-messaging-smallrye/kafka/src/main/resources/META-INF/services/org.wildfly.microprofile.reactive.messaging.common.DynamicDeploymentProcessorAdder
  pom.xml
  testsuite/integration/microprofile/src/test/java/org/apache/kafka/raft/FileBasedStateStore.java
  testsuite/integration/microprofile/src/test/java/org/wildfly/test/integration/microprofile/reactive/messaging/kafka/compression/ReactiveMessagingKafkaCompressionTestCase.java
  testsuite/shared/src/main/java/org/jboss/as/test/shared/LayersTestBase.java
Labels: deps-ok

#18183 [WFLY-19730] Upgrade to vertx 4.5.10
  galleon-pack/galleon-shared/src/main/resources/modules/system/layers/base/io/vertx/grpc-common/main/module.xml
  pom.xml
Labels: 33.x

#18127 [WFLY-19644] Upgrade version.jakarta.websocket.jakarta-websocket-api …
  pom.xml
Labels: deps-ok

#18184 WFLY-19668 Upgrade Infinispan to 14.0.31.Final.
  pom.xml
Labels: deps-ok

#18187 [WFLY-19733] Upgrade WildFly Core to 26.0.0.Beta4
  pom.xml
Labels: deps-ok

#18094 [WFLY-19604] Upgrade to Hibernate Validator 9.0.0.Beta2 in the EE 11 Preview
  boms/preview-ee/pom.xml
  docs/src/main/asciidoc/WildFly_and_WildFly_Preview.adoc
Labels: deps-ok

#18185 [WFLY-19732] Suppress CVE-2024-7885 as it is addressed under UNDERTOW-2429.
  sca-overrides/owasp-suppressions.xml
Labels: hold

#18199 [WFLY-19739] Upgrade Creaper to 2.0.3
  pom.xml
Labels: deps-ok, 34.x

#18209 [WFLY-19746] Upgrade HAL to 3.7.5.Final
  pom.xml
Labels: deps-ok

#18212 WFLY-19750 Upgrade wildfly-clustering to 1.1.2.Final
  pom.xml
Labels: deps-ok

#18198 WFLY-19306 Upgrade to Hibernate ORM 6.6.0.Final / WFLY-19632 Upgrade to Hibernate Search 7.2.0.Final
  pom.xml
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/hibernate/search/backend/elasticsearch/util/ElasticsearchServerSetupObserver.java
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/jpa/webtxem/TestServlet.java
Labels: deps-changed, 34.x

#18053 [WFLY-19543] Upgrade ByteBuddy to 1.14.18
  pom.xml
Labels: hold, deps-ok

#18195 [WFLY-19735] Integrate Glassfish Expressly 6.0.0-M1 in WildFly Preview
  boms/preview-ee/pom.xml
Labels: deps-ok

#18218 [WFLY-19762] / [WFLY-19764] Additional OWASP dependency check suppressions.
  sca-overrides/owasp-suppressions.xml
Labels: Critical, 34.x

#18217 [WFLY-19757] [CVE-2024-7254] Upgrade protobuf-java to 3.25.5
  pom.xml
Labels: deps-ok, Critical, dependencies, 34.x

#18155 [WFLY-19636]: Upgrading Apache Artemis to 2.37.0
  pom.xml
Labels: deps-ok, 34.x

#18225 [WFLY-19765] Upgrade WildFly Core to 26.0.0.Beta5
  pom.xml
Labels: Blocker, deps-ok, 34.x

#18226 [WFLY-19760] - Distributions contain zips of feature packs index at their root
  dist/src/verifier/verifications.xml
  ee-dist/src/verifier/verifications.xml
  ee-feature-pack/galleon-feature-pack/pom.xml
  ee-feature-pack/galleon-shared/pom.xml
  ee-feature-pack/galleon-shared/src/main/resources/packages/unstable-api-annotation-index.wildfly-ee-feature-pack/pm/wildfly/tasks.xml
  galleon-pack/galleon-feature-pack/pom.xml
  galleon-pack/galleon-shared/pom.xml
  galleon-pack/galleon-shared/src/main/resources/packages/unstable-api-annotation-index.wildfly-galleon-pack/pm/wildfly/tasks.xml
Labels: deps-ok, Critical, 34.x

#18193 [Community] [WFLY-19715] Add documentaion for the new attributes added to control resource constraints for the HTTP management interface.
  docs/src/main/asciidoc/_admin-guide/Management_Clients.adoc
Labels: Feature-Docs, Critical, 34.x

#17990 [WFLY-19464] Aligns user BOMs with server dists
  boms/user/README.adoc
  boms/user/client/ejb-client/pom.xml
  boms/user/client/jaxws-client/pom.xml
  boms/user/client/jms-client/pom.xml
  boms/user/client/pom.xml
  boms/user/ee/pom.xml
  boms/user/pom.xml
  boms/user/server/ee/pom.xml
  boms/user/server/ee/preview/pom.xml
  boms/user/server/ee/preview/with-tools/pom.xml
  boms/user/server/ee/standard/pom.xml
  boms/user/server/ee/standard/with-tools/pom.xml
  boms/user/server/expansion/pom.xml
  boms/user/server/expansion/preview/pom.xml
  boms/user/server/expansion/preview/with-tools/pom.xml
  boms/user/server/expansion/standard/pom.xml
  boms/user/server/expansion/standard/with-tools/pom.xml
  boms/user/server/pom.xml
  boms/user/tools/pom.xml
Labels: deps-ok, 34.x

#17856 [WFLY-19298] Update fasterxml to 2.17.0
  pom.xml
Labels: deps-ok, Critical, 34.x

#18235 [WFLY-19397] Jakarta Data support in WildFly Preview
  boms/preview-ee/pom.xml
  docs/src/main/asciidoc/WildFly_and_WildFly_Preview.adoc
  docs/src/main/asciidoc/_galleon/Galleon_layers.adoc
  ee-feature-pack/galleon-shared/src/main/resources/modules/system/layers/base/org/hibernate/main/module.xml
  jakarta-data/pom.xml
  jakarta-data/src/main/java/org/wildfly/extension/jakarta/data/JakartaDataExtension.java
  jakarta-data/src/main/java/org/wildfly/extension/jakarta/data/_private/JakartaDataLogger.java
  jakarta-data/src/main/resources/org/wildfly/extension/jakarta/data/LocalDescriptions.properties
  jakarta-data/src/main/resources/schema/wildfly-jakarta-data_preview_1_0.xsd
  jakarta-data/src/test/java/org/wildfly/extension/jakarta/data/JakartaDataSubsystemTestCase.java
  jakarta-data/src/test/resources/org/wildfly/extension/jakarta/data/jakarta-data-preview-1.0.xml
  pom.xml
  preview/feature-pack/wildfly-feature-pack-build.xml
  preview/galleon-local/pom.xml
  preview/galleon-local/src/main/resources/feature_groups/domain-host-excludes.xml
  preview/galleon-local/src/main/resources/layers/standalone/jakarta-data/layer-spec.xml
  preview/galleon-local/src/main/resources/modules/system/layers/base/jakarta/data/api/main/module.xml
  preview/galleon-local/src/main/resources/modules/system/layers/base/org/wildfly/extension/jakarta/data/main/module.xml
  testsuite/domain/src/test/java/org/jboss/as/test/integration/domain/HostExcludesTestCase.java
  testsuite/layers-expansion/pom.xml
  testsuite/shared/src/main/java/org/jboss/as/test/shared/LayersTestBase.java
Labels: deps-ok

#18227 [WFLY-19397] Jakarta Data support in WildFly Preview
  boms/preview-ee/pom.xml
  docs/src/main/asciidoc/WildFly_and_WildFly_Preview.adoc
  docs/src/main/asciidoc/_galleon/Galleon_layers.adoc
  ee-feature-pack/galleon-shared/src/main/resources/modules/system/layers/base/org/hibernate/main/module.xml
  jakarta-data/pom.xml
  jakarta-data/src/main/java/org/wildfly/extension/jakarta/data/JakartaDataExtension.java
  jakarta-data/src/main/java/org/wildfly/extension/jakarta/data/_private/JakartaDataLogger.java
  jakarta-data/src/main/resources/org/wildfly/extension/jakarta/data/LocalDescriptions.properties
  jakarta-data/src/main/resources/schema/wildfly-jakarta-data_preview_1_0.xsd
  jakarta-data/src/test/java/org/wildfly/extension/jakarta/data/JakartaDataSubsystemTestCase.java
  jakarta-data/src/test/resources/org/wildfly/extension/jakarta/data/jakarta-data-preview-1.0.xml
  pom.xml
  preview/feature-pack/wildfly-feature-pack-build.xml
  preview/galleon-local/pom.xml
  preview/galleon-local/src/main/resources/feature_groups/domain-host-excludes.xml
  preview/galleon-local/src/main/resources/layers/standalone/jakarta-data/layer-spec.xml
  preview/galleon-local/src/main/resources/modules/system/layers/base/jakarta/data/api/main/module.xml
  preview/galleon-local/src/main/resources/modules/system/layers/base/org/wildfly/extension/jakarta/data/main/module.xml
  testsuite/domain/src/test/java/org/jboss/as/test/integration/domain/HostExcludesTestCase.java
  testsuite/layers-expansion/pom.xml
  testsuite/shared/src/main/java/org/jboss/as/test/shared/LayersTestBase.java
Labels: deps-ok

#18240 [WFLY-19777] Prevent provisioning of preview Jakarta Data modules in a higher stability context
  preview/galleon-local/src/main/resources/modules/system/layers/base/jakarta/data/api/main/module.xml
  preview/galleon-local/src/main/resources/modules/system/layers/base/org/wildfly/extension/jakarta/data/main/module.xml
Labels: deps-ok, 34.x

#18228 [WFLY-19768] MicroProfile Reactive Streams Operators 3.0.1
  pom.xml
  testsuite/integration/microprofile-tck/reactive-streams-operators/pom.xml
Labels: deps-ok

#18253 [WFLY-19794] Upgrade WildFly Arquillian to 5.1.0.Beta5
  pom.xml
Labels: deps-ok
