Repository wildfly/wildfly, pull requests merged in 2024-11, with the labels that each got.

#18341 WFLY-19591 Upgrade MicroProfile OpenAPI to 4.0.
  boms/common-expansion/pom.xml
  galleon-pack/galleon-shared/pom.xml
  galleon-pack/galleon-shared/src/main/resources/modules/system/layers/base/io/smallrye/openapi/main/module.xml
  microprofile/openapi-smallrye/pom.xml
  microprofile/openapi-smallrye/src/main/java/org/wildfly/extension/microprofile/openapi/deployment/DeploymentUnitOpenAPIModelConfiguration.java
  microprofile/openapi-smallrye/src/main/java/org/wildfly/extension/microprofile/openapi/deployment/OpenAPIDocumentProcessor.java
  microprofile/openapi-smallrye/src/main/java/org/wildfly/extension/microprofile/openapi/deployment/OpenAPIHttpHandler.java
  microprofile/openapi-smallrye/src/main/java/org/wildfly/extension/microprofile/openapi/deployment/OpenAPIHttpHandlerServiceInstaller.java
  microprofile/openapi-smallrye/src/main/java/org/wildfly/extension/microprofile/openapi/deployment/OpenAPIModelConfiguration.java
  microprofile/openapi-smallrye/src/main/java/org/wildfly/extension/microprofile/openapi/deployment/OpenAPIModelServiceInstaller.java
  pom.xml
  testsuite/integration/microprofile-tck/openapi/pom.xml
  testsuite/integration/microprofile-tck/openapi/src/test/java/org/wildfly/extension/microprofile/openapi/tck/DeploymentProcessor.java
Labels: MP7

#18339 [WFLY-19899] Upgrade WildFly Core to 27.0.0.Beta2
  pom.xml
Labels: deps-ok

#18347 [WFLY-19908] Forces user BOMs to channel version in reactor
  boms/user/client/ejb-client/pom.xml
  boms/user/client/jaxws-client/pom.xml
  boms/user/client/jms-client/pom.xml
  boms/user/pom.xml
  boms/user/server/ee/preview/pom.xml
  boms/user/server/ee/standard/pom.xml
  boms/user/server/expansion/preview/pom.xml
  boms/user/server/expansion/standard/pom.xml
  boms/user/tools/pom.xml
Labels: deps-ok

#18362 [WFLY-19934] Bump version.org.wildfly.bom-builder-plugin to 2.0.8.Final
  pom.xml
Labels: deps-ok

#18354 [WFLY-19926] Upgrade to Hibernate ORM 6.6.2.Final
  pom.xml
Labels: deps-ok

#18358 [WFLY-19927] & [WFLY-19928] Upgrade RESTEasy in WildFly and WildFly Preview
  boms/preview-ee/pom.xml
  pom.xml
Labels: deps-ok

#18360 WFLY-19591 Community doc updates for MicroProfile OpenAPI 4.0.
  docs/src/main/asciidoc/_admin-guide/subsystem-configuration/MicroProfile_OpenAPI.adoc
Labels: MP7

#18372 [mp-7-wip] WFLY-19592 Test case for MP Fault Tolerance with MP Telemetry Metrics
  testsuite/integration/microprofile/src/test/java/org/wildfly/test/integration/microprofile/faulttolerance/opentelemetry/FaultToleranceOpenTelemetryIntegrationTestCase.java
  testsuite/shared/src/main/java/org/jboss/as/test/shared/observability/setuptasks/OpenTelemetrySetupTask.java
Labels: MP7

#18377 [WFLY-19940] Remove MaxMetaspaceSize settings
  docs/src/main/asciidoc/Getting_Started_Guide.adoc
  ee-feature-pack/galleon-shared/src/main/resources/content/bin/appclient.conf
  ee-feature-pack/galleon-shared/src/main/resources/content/bin/appclient.conf.bat
  ee-feature-pack/galleon-shared/src/main/resources/content/bin/appclient.conf.ps1
  ee-feature-pack/galleon-shared/src/main/resources/feature_groups/host-primary.xml
  ee-feature-pack/galleon-shared/src/main/resources/feature_groups/host-secondary.xml
  ee-feature-pack/galleon-shared/src/main/resources/feature_groups/host.xml
  ee-feature-pack/galleon-shared/src/main/resources/feature_groups/servlet-host-primary.xml
  ee-feature-pack/galleon-shared/src/main/resources/feature_groups/servlet-host-secondary.xml
  ee-feature-pack/galleon-shared/src/main/resources/feature_groups/servlet-host.xml
  pom.xml
  testsuite/domain/src/test/resources/host-configs/host-primary-elytron.xml
  testsuite/domain/src/test/resources/host-configs/host-secondary-elytron.xml
  testsuite/integration/manualmode/src/test/java/org/jboss/as/test/manualmode/messaging/CoreBridgeCallTimeoutTestCase.java
  testsuite/mixed-domain/src/test/resources/primary-config/host-primary-elytron.xml
Labels: deps-ok

#18392 Merge from main to mp-7-wip
  docs/src/main/asciidoc/Getting_Started_Guide.adoc
  ee-feature-pack/galleon-local/src/main/resources/configs/domain/model.xml
  ee-feature-pack/galleon-local/src/main/resources/configs/standalone/model.xml
  ee-feature-pack/galleon-shared/src/main/resources/content/bin/appclient.conf
  ee-feature-pack/galleon-shared/src/main/resources/content/bin/appclient.conf.bat
  ee-feature-pack/galleon-shared/src/main/resources/content/bin/appclient.conf.ps1
  ee-feature-pack/galleon-shared/src/main/resources/feature_groups/host-primary.xml
  ee-feature-pack/galleon-shared/src/main/resources/feature_groups/host-secondary.xml
  ee-feature-pack/galleon-shared/src/main/resources/feature_groups/host.xml
  ee-feature-pack/galleon-shared/src/main/resources/feature_groups/servlet-host-primary.xml
  ee-feature-pack/galleon-shared/src/main/resources/feature_groups/servlet-host-secondary.xml
  ee-feature-pack/galleon-shared/src/main/resources/feature_groups/servlet-host.xml
  ee-feature-pack/galleon-shared/src/main/resources/packages/unstable-api-annotation-index.wildfly-ee-feature-pack/package.xml
  galleon-pack/galleon-local/src/main/resources/configs/domain/model.xml
  galleon-pack/galleon-local/src/main/resources/configs/standalone/model.xml
  galleon-pack/galleon-shared/src/main/resources/modules/system/layers/base/io/smallrye/reactive/mutiny/vertx-core/main/module.xml
  galleon-pack/galleon-shared/src/main/resources/packages/unstable-api-annotation-index.wildfly-galleon-pack/package.xml
  pom.xml
  preview/galleon-local/src/main/resources/configs/domain/model.xml
  preview/galleon-local/src/main/resources/configs/standalone/model.xml
  testsuite/domain/src/test/resources/host-configs/host-primary-elytron.xml
  testsuite/domain/src/test/resources/host-configs/host-secondary-elytron.xml
  testsuite/integration/manualmode/src/test/java/org/jboss/as/test/manualmode/messaging/CoreBridgeCallTimeoutTestCase.java
  testsuite/mixed-domain/src/test/resources/primary-config/host-primary-elytron.xml
Labels: MP7

#18359 [34.x] [WFLY-19927] & [WFLY-19928] Upgrade RESTEasy in WildFly and WildFly Preview
  boms/preview-ee/pom.xml
  pom.xml
Labels: 34.x

#18363 [mp-7-wip] WFLY-19592 Update MicroProfile Fault Tolerance Subsystem documentatio…
  docs/src/main/asciidoc/_admin-guide/subsystem-configuration/MicroProfile_Fault_Tolerance_SmallRye.adoc
Labels: MP7

#18397 WFLY-19891 Fix deadlock when application tries to invoke a timed-out timer referenced from TimerService.getTimers() within a @Timeout method.
  ejb3/src/main/java/org/jboss/as/ejb3/timerservice/distributable/DistributableTimerService.java
  testsuite/integration/clustering/src/test/java/org/jboss/as/test/clustering/cluster/ejb/timer/beans/AbstractManualTimerBean.java
Labels: 34.x

#18403 WFLY-19964 Upgrade netty to 4.1.115.Final
  pom.xml
Labels: 34.x

#18406 WFLY-19977 Upgrade wildfly-clustering to 1.1.3.Final
  pom.xml
Labels: 34.x

#18407 WFLY-19977 Upgrade wildfly-clustering to 1.1.3.Final
  pom.xml
Labels: deps-ok

#18408 Merge from main to mp-7-wip
  boms/common-expansion/pom.xml
  ejb3/src/main/java/org/jboss/as/ejb3/timerservice/distributable/DistributableTimerService.java
  galleon-pack/galleon-shared/pom.xml
  galleon-pack/galleon-shared/src/main/resources/modules/system/layers/base/org/jboss/narayana/lra/lra-coordinator/main/module.xml
  galleon-pack/galleon-shared/src/main/resources/modules/system/layers/base/org/jboss/narayana/lra/lra-participant/main/module.xml
  galleon-pack/galleon-shared/src/main/resources/modules/system/layers/base/org/jboss/narayana/lra/lra-service-base/main/module.xml
  galleon-pack/galleon-shared/src/main/resources/modules/system/layers/base/org/wildfly/extension/microprofile/lra-coordinator/main/module.xml
  galleon-pack/galleon-shared/src/main/resources/modules/system/layers/base/org/wildfly/extension/microprofile/lra-participant/main/module.xml
  microprofile/lra/coordinator/pom.xml
  microprofile/lra/participant/pom.xml
  microprofile/lra/participant/src/main/java/org/wildfly/extension/microprofile/lra/participant/deployment/LRAParticipantDeploymentDependencyProcessor.java
  pom.xml
  testsuite/integration/clustering/src/test/java/org/jboss/as/test/clustering/cluster/ejb/timer/beans/AbstractManualTimerBean.java
  testsuite/integration/microprofile-tck/lra/pom.xml
  testsuite/shared/src/main/java/org/jboss/as/test/shared/LayersTestBase.java
Labels: MP7

#18355 [WFLY-19929]:Upgrade jbossws-cxf to 7.3.0.Final
  pom.xml
Labels: deps-ok

#18368 [WFLY-19936]:Upgrade woodstox-core from 6.4.0 to 7.0.0
  pom.xml
Labels: deps-changed

#18389 [WFLY-19952] - Upgrade Micrometer to 1.14.1
  pom.xml
Labels: deps-ok

#18367 WFLY-19935 Upgrade Weld version in Preview to 6.0.0.CR1
  boms/preview-ee/pom.xml
Labels: deps-ok

#18376 [WFLY-19924] - OpenTelemetry quickstart application logs warning with NoClassDefFoundError exceptionafter URL request
  galleon-pack/galleon-shared/src/main/resources/modules/system/layers/base/org/wildfly/extension/opentelemetry/main/module.xml
  legacy/opentracing-extension/pom.xml
  observability/opentelemetry/pom.xml
  observability/opentelemetry/src/main/java/org/wildfly/extension/opentelemetry/OpenTelemetrySubsystemExtension.java
Labels: deps-ok

#18325 [WFLY-19895]: Upgrade Apache Artemis to 2.38.0.
  pom.xml
Labels: deps-ok

#18410 [WFLY-19982] Upgrade WildFly Core to 27.0.0.Beta3
  pom.xml
Labels: deps-ok

#18418 [WFLY-19985] Upgrade WildFly Arquillian to 5.1.0.Beta7.
  pom.xml
  testsuite/shared/pom.xml
  testsuite/shared/src/main/java/org/wildfly/test/stabilitylevel/StabilityServerSetupSnapshotRestoreTasks.java
Labels: deps-ok

#18423 [MP7] WFLY-19974 - Update Arquillian Testcontainers to 1.0.0.Alpha3
  pom.xml
  testsuite/integration/microprofile/pom.xml
  testsuite/integration/microprofile/src/test/java/org/wildfly/test/integration/microprofile/faulttolerance/micrometer/FaultToleranceMicrometerIntegrationDisabledTestCase.java
  testsuite/integration/microprofile/src/test/java/org/wildfly/test/integration/microprofile/faulttolerance/micrometer/FaultToleranceMicrometerIntegrationTestCase.java
  testsuite/integration/microprofile/src/test/java/org/wildfly/test/integration/microprofile/faulttolerance/multideployment/MultipleDeploymentMetricsTestCase.java
  testsuite/integration/microprofile/src/test/java/org/wildfly/test/integration/microprofile/faulttolerance/opentelemetry/FaultToleranceOpenTelemetryIntegrationTestCase.java
  testsuite/integration/microprofile/src/test/java/org/wildfly/test/integration/observability/micrometer/BasicMicrometerTestCase.java
  testsuite/integration/microprofile/src/test/java/org/wildfly/test/integration/observability/micrometer/MicrometerOtelIntegrationTestCase.java
  testsuite/integration/microprofile/src/test/java/org/wildfly/test/integration/observability/micrometer/multiple/BaseMultipleTestCase.java
  testsuite/integration/microprofile/src/test/java/org/wildfly/test/integration/observability/opentelemetry/BaseOpenTelemetryTest.java
Labels: MP7

#18425 WFLY-17539 Move rbac testing from XSLT to cli script
  testsuite/integration/rbac/enable-rbac.cli
  testsuite/integration/rbac/pom.xml
  testsuite/integration/src/test/xslt/enableRbac.xsl
  testsuite/integration/src/test/xslt/setupRbacRolesMappingTests.xsl
Labels: deps-ok

#18429 Merge from main to mp-7-wip
  clustering/infinispan/extension/src/main/java/org/jboss/as/clustering/infinispan/subsystem/CacheContainerResourceTransformer.java
  clustering/infinispan/extension/src/main/java/org/jboss/as/clustering/infinispan/subsystem/remote/RemoteCacheContainerResourceTransformer.java
  clustering/infinispan/extension/src/test/java/org/jboss/as/clustering/infinispan/subsystem/InfinispanTransformersTestCase.java
  clustering/infinispan/extension/src/test/resources/org/jboss/as/clustering/infinispan/subsystem/subsystem-infinispan-transform-14_0_0.xml
  observability/micrometer/src/main/java/org/wildfly/extension/micrometer/WildFlyMicrometerConfig.java
  pom.xml
  testsuite/shared/pom.xml
  testsuite/shared/src/main/java/org/wildfly/test/stabilitylevel/StabilityServerSetupSnapshotRestoreTasks.java
Labels: deps-changed

#18313 [WFLY-19393] Persistence container bytecode enhancement should be enabled by default
  jpa/subsystem/src/main/java/org/jboss/as/jpa/config/Configuration.java
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/jpa/hibernate/EmployeeWithLastName.java
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/jpa/hibernate/EmployeeWithLastNameNotEnhanced.java
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/jpa/hibernate/SFSBWithLastName.java
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/jpa/hibernate/classfiletransformertest/ClassFileTransformerTestCase.java
Labels: deps-ok

#18420 Fix for WFLY-19989, h2-driver layer rule for jakarta DataSourceDefinition annotation
  ee-feature-pack/galleon-shared/src/main/resources/layers/standalone/h2-driver/layer-spec.xml
  ee-feature-pack/layer-metadata-tests/src/test/java/org/wildfly/ee/feature/pack/layer/tests/h2/driver/H2DriverLayerMetaDataTestCase.java
  ee-feature-pack/layer-metadata-tests/src/test/java/org/wildfly/ee/feature/pack/layer/tests/h2/driver/JakartaDataSourceDefinitionAnnotationUsage.java
  pom.xml
  testsuite/integration/basic/pom.xml
Labels: deps-ok

#18391 [WFLY-19953] Upgrade Jackson to 2.18.1
  pom.xml
Labels: deps-ok

#18405 WFLY-19974 Update Arquillian Testcontainers to 1.0.0.Alpha3
  boms/standard-test-expansion/pom.xml
  pom.xml
  testsuite/integration/microprofile/pom.xml
  testsuite/integration/microprofile/src/test/java/org/wildfly/test/integration/microprofile/faulttolerance/micrometer/FaultToleranceMicrometerIntegrationTestCase.java
  testsuite/integration/microprofile/src/test/java/org/wildfly/test/integration/microprofile/faulttolerance/multideployment/MultipleDeploymentMetricsTestCase.java
  testsuite/integration/microprofile/src/test/java/org/wildfly/test/integration/observability/micrometer/BasicMicrometerTestCase.java
  testsuite/integration/microprofile/src/test/java/org/wildfly/test/integration/observability/micrometer/MicrometerOtelIntegrationTestCase.java
  testsuite/integration/microprofile/src/test/java/org/wildfly/test/integration/observability/micrometer/multiple/BaseMultipleTestCase.java
  testsuite/integration/microprofile/src/test/java/org/wildfly/test/integration/observability/opentelemetry/BasicOpenTelemetryTestCase.java
  testsuite/integration/microprofile/src/test/java/org/wildfly/test/integration/observability/opentelemetry/ContextPropagationTestCase.java
  testsuite/integration/microprofile/src/test/java/org/wildfly/test/integration/observability/opentelemetry/OpenTelemetryIntegrationTestCase.java
  testsuite/preview/expansion/src/test/java/org/wildfly/test/preview/microprofile/telemetry/MetricsTestCase.java
  testsuite/shared/src/main/java/org/jboss/as/test/shared/observability/containers/BaseContainer.java
  testsuite/shared/src/main/java/org/jboss/as/test/shared/observability/setuptasks/MicrometerSetupTask.java
  testsuite/shared/src/main/java/org/jboss/as/test/shared/observability/setuptasks/OpenTelemetrySetupTask.java
Labels: deps-ok

#18443 [WFLY-20027]: Upgrade HornetQ to 2.4.10.Final.
  pom.xml
Labels: deps-ok

#18431 WFLY-19995 Upgrade to Hibernate Search 7.2.2.Final / WFLY-19996 Upgrade to Elasticsearch client 8.15.4 / WFLY-19997 Upgrade to com.carrotsearch:hppc 0.10.0 / WFLY-20013 Upgrade to Hibernate ORM 6.6.3.Final
  ee-feature-pack/galleon-shared/src/main/resources/modules/system/layers/base/org/apache/lucene/main/module.xml
  pom.xml
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/hibernate/search/backend/elasticsearch/util/ElasticsearchServerSetupObserver.java
Labels: deps-ok

#18445 [WFLY-19690] Upgrade to Kafka client 3.9.0
  pom.xml
  testsuite/integration/microprofile/src/test/java/org/apache/kafka/raft/FileBasedStateStore.java
Labels: deps-ok
