Repository wildfly/wildfly, pull requests merged in 2024-12, with the labels that each got.

#18322 [WFLY-19588] Update community documentation MP Platform 7.0
  docs/src/main/asciidoc/Getting_Started_Guide.adoc
  docs/src/main/asciidoc/WildFly_and_WildFly_Preview.adoc
Labels: MP7

#18357 [WFLY-19846] [docs] Promote MicroProfile Telemetry 2.0 to WildFly Standard
  docs/src/main/asciidoc/_admin-guide/subsystem-configuration/MicroProfile_Telemetry.adoc
Labels: MP7

#18460 WFLY-20036 Upgrade SmallRye Fault Tolerance from 6.6.3 to 6.7.0
  pom.xml
  testsuite/integration/microprofile-tck/telemetry/pom.xml
Labels: MP7

#18458 [WFLY-20034] Facilitate groupid transition using project.groupId
  ee-build/src/verifier/verifications.xml
  preview/galleon-local/pom.xml
  testsuite/integration/manualmode/pom.xml
Labels: ready-for-merge, deps-ok

#18450 WFLY-20031 Upgrade WFLY preview to Weld 6.0.0.CR2
  boms/preview-ee/pom.xml
Labels: deps-ok

#18208 [WFLY-19745] Community documentation for systemd services
  docs/src/main/asciidoc/Getting_Started_Guide.adoc
Labels: ready-for-merge, Feature

#18466 [WFLY-20035] Initialize the Vert.x LoggerFactory in the WF Extension classes that use Vert.x
  galleon-pack/galleon-shared/src/main/resources/modules/system/layers/base/org/wildfly/extension/microprofile/reactive-messaging-smallrye/main/module.xml
  galleon-pack/galleon-shared/src/main/resources/modules/system/layers/base/org/wildfly/extension/opentelemetry/main/module.xml
  legacy/opentracing-extension/pom.xml
  microprofile/reactive-messaging-smallrye/extension/pom.xml
  microprofile/reactive-messaging-smallrye/extension/src/main/java/org/wildfly/extension/microprofile/reactive/messaging/MicroProfileReactiveMessagingExtension.java
  observability/opentelemetry/pom.xml
  observability/opentelemetry/src/main/java/org/wildfly/extension/opentelemetry/OpenTelemetrySubsystemExtension.java
  testsuite/integration/microprofile/pom.xml
Labels: deps-ok

#18469 Fix for WFLY-20046, Upgrade Galleon to 6.0.4.Final
  pom.xml
Labels: deps-ok

#18468 WFLY-20045 Upgrade OpenTelemetry from 1.39.1 to 1.42.1 and SR OpenTelemetry to 2.8.2
  pom.xml
  testsuite/integration/microprofile-tck/fault-tolerance/src/test/java/org/wildfly/extension/microprofile/faulttolerance/tck/FaultToleranceApplicationArchiveProcessor.java
  testsuite/integration/microprofile/src/test/java/org/wildfly/test/integration/microprofile/faulttolerance/context/asynchronous/AsynchronousRequestContextTestCase.java
  testsuite/integration/microprofile/src/test/java/org/wildfly/test/integration/observability/opentelemetry/BaseOpenTelemetryTest.java
Labels: MP7

#18462 [WFLY-20039] Only use testsuite.full.galleon.pack.groupId|artifactId|…
  testsuite/integration/microprofile-tck/pom.xml
  testsuite/integration/microprofile-tck/rest-client/pom.xml
Labels: deps-ok

#18324 [WFLY-19890] Upgrade protobuf-java to 4.28.3
  pom.xml
Labels: deps-changed

#17936 [WFLY-19221] Incorporate channel metadata in the download zips
  dist/pom.xml
  dist/src/verifier/verifications.xml
  docs/pom.xml
  ee-dist/pom.xml
  ee-dist/src/verifier/verifications.xml
  ee-feature-pack/galleon-feature-pack/pom.xml
  galleon-pack/channel/pom.xml
  pom.xml
  preview/dist/pom.xml
  preview/dist/src/verifier/verifications.xml
  preview/feature-pack/pom.xml
  testsuite/integration/manualmode-expansion/pom.xml
  testsuite/integration/manualmode/pom.xml
  testsuite/shared/src/main/java/org/wildfly/test/distribution/validation/ProvisioningConsistencyBaseTest.java
Labels: deps-ok, 35.x

#18453 WFLY-19941 - Remove MetaspaceSize settings
  docs/src/main/asciidoc/Getting_Started_Guide.adoc
  ee-feature-pack/galleon-shared/src/main/resources/feature_groups/host-primary.xml
  ee-feature-pack/galleon-shared/src/main/resources/feature_groups/host-secondary.xml
  ee-feature-pack/galleon-shared/src/main/resources/feature_groups/host.xml
  ee-feature-pack/galleon-shared/src/main/resources/feature_groups/servlet-host-primary.xml
  ee-feature-pack/galleon-shared/src/main/resources/feature_groups/servlet-host-secondary.xml
  ee-feature-pack/galleon-shared/src/main/resources/feature_groups/servlet-host.xml
  testsuite/domain/src/test/resources/host-configs/host-primary-elytron.xml
  testsuite/domain/src/test/resources/host-configs/host-secondary-elytron.xml
  testsuite/mixed-domain/src/test/resources/primary-config/host-primary-elytron.xml
  testsuite/pom.xml
Labels: deps-ok

#18461 [WFLY-20054] Use the galleon-pack/pom.xml as the parent for the 'build' and 'dist'…
  build/pom.xml
  dist/pom.xml
Labels: deps-ok

#18476 [WFLY-20053] Upgrade JBeret to 3.1.0.Final
  pom.xml
Labels: deps-ok

#18434 [WFLY-19776][Preview] Jakarta Data support in standard WildFly
  boms/common-ee/pom.xml
  boms/preview-ee/pom.xml
  docs/src/main/asciidoc/Developer_Guide.adoc
  docs/src/main/asciidoc/Getting_Started_Guide.adoc
  docs/src/main/asciidoc/WildFly_and_WildFly_Preview.adoc
  docs/src/main/asciidoc/_admin-guide/Subsystem_configuration.adoc
  docs/src/main/asciidoc/_admin-guide/subsystem-configuration/Jakarta_Data.adoc
  docs/src/main/asciidoc/_admin-guide/subsystem-configuration/Simple_configuration_subsystems.adoc
  docs/src/main/asciidoc/_developer-guide/Jakarta_Data_Reference.adoc
  docs/src/main/asciidoc/_galleon/Galleon_layers.adoc
  ee-feature-pack/galleon-feature-pack/wildfly-feature-pack-build.xml
  ee-feature-pack/galleon-shared/pom.xml
  ee-feature-pack/galleon-shared/src/main/resources/feature_groups/domain-host-excludes.xml
  ee-feature-pack/galleon-shared/src/main/resources/layers/standalone/jakarta-data/layer-spec.xml
  ee-feature-pack/galleon-shared/src/main/resources/modules/system/layers/base/jakarta/data/api/main/module.xml
  ee-feature-pack/galleon-shared/src/main/resources/modules/system/layers/base/org/wildfly/extension/jakarta/data/main/module.xml
  galleon-pack/galleon-local/src/main/resources/feature_groups/domain-host-excludes.xml
  preview/galleon-local/pom.xml
  preview/galleon-local/src/main/resources/configs/standalone/standalone-microprofile-ha.xml/config.xml
  preview/galleon-local/src/main/resources/configs/standalone/standalone-microprofile.xml/config.xml
  preview/galleon-local/src/main/resources/feature_groups/domain-full-ha.xml
  preview/galleon-local/src/main/resources/feature_groups/domain-full.xml
  preview/galleon-local/src/main/resources/feature_groups/domain-ha-profile.xml
  preview/galleon-local/src/main/resources/feature_groups/domain-profile.xml
  preview/galleon-local/src/main/resources/layers/standalone/internal-standalone-profile/layer-spec.xml
  testsuite/domain/src/test/java/org/jboss/as/test/integration/domain/HostExcludesTestCase.java
  testsuite/shared/src/main/java/org/jboss/as/test/shared/LayersTestBase.java
Labels: Feature, deps-changed, 35.x

#18465 [WFLY-20042] Clean up test bom dependency statements in expansion tes…
  testsuite/integration/manualmode-expansion/pom.xml
  testsuite/integration/microprofile/pom.xml
Labels: deps-ok

#18480 [WFLY-19991] / [WFLY-19993] Switch WildFly Preview to support Jakarta Authentication 3.1.0
  boms/preview-ee/pom.xml
Labels: deps-ok

#18490 [WFLY-20067] Stop overriding otel version in WildFly Preview
  boms/preview-expansion/pom.xml
Labels: Blocker, deps-ok, 35.x

#18487 [WFLY-20065] Upgrade resteasy-spring to 3.2.0.Final
  pom.xml
Labels: deps-ok

#18494 [WFLY-20071] Override distribution in preview folder
  preview/dist/pom.xml
Labels: deps-ok

#18493 [WFLY-20069] Upgrade WildFly Core to 27.0.0.Beta5
  pom.xml
Labels: deps-ok

#18495 [WFLY-20072] Include non shaded wildfly-cli artifact in tools user BOM
  boms/user/tools/pom.xml
Labels: deps-ok, 35.x

#18320 [WFLY-19835][WFLY-19836] Integrate Reactive Messaging's AMQP and Kafka connectors with OpenTelemetry
  boms/common-expansion/pom.xml
  docs/src/main/asciidoc/_admin-guide/subsystem-configuration/MicroProfile_Reactive_Messsaging_SmallRye.adoc
  galleon-pack/galleon-shared/pom.xml
  galleon-pack/galleon-shared/src/main/resources/modules/system/layers/base/io/smallrye/reactive/messaging/connector/amqp/main/module.xml
  galleon-pack/galleon-shared/src/main/resources/modules/system/layers/base/io/smallrye/reactive/messaging/connector/kafka/main/module.xml
  galleon-pack/galleon-shared/src/main/resources/modules/system/layers/base/io/smallrye/reactive/messaging/otel/main/module.xml
  galleon-pack/galleon-shared/src/main/resources/modules/system/layers/base/org/wildfly/extension/microprofile/reactive-messaging-smallrye/main/module.xml
  galleon-pack/galleon-shared/src/main/resources/modules/system/layers/base/org/wildfly/reactive/messaging/config/main/module.xml
  microprofile/health-smallrye/src/main/java/org/wildfly/extension/microprofile/health/MicroProfileHealthReporter.java
  microprofile/reactive-messaging-smallrye/amqp/src/main/java/org/wildfly/microprofile/reactive/messaging/config/amqp/ssl/context/_private/AmqpClientCustomizer.java
  microprofile/reactive-messaging-smallrye/config/pom.xml
  microprofile/reactive-messaging-smallrye/config/src/main/java/org/wildfly/microprofile/reactive/messaging/config/ReactiveMessagingConfigSetter.java
  microprofile/reactive-messaging-smallrye/config/src/main/java/org/wildfly/microprofile/reactive/messaging/config/ReactiveMessagingConfigSource.java
  microprofile/reactive-messaging-smallrye/config/src/main/java/org/wildfly/microprofile/reactive/messaging/config/TracingType.java
  microprofile/reactive-messaging-smallrye/config/src/main/java/org/wildfly/microprofile/reactive/messaging/config/TracingTypeInterceptor.java
  microprofile/reactive-messaging-smallrye/config/src/main/java/org/wildfly/microprofile/reactive/messaging/config/TracingTypeInterceptorFactory.java
  microprofile/reactive-messaging-smallrye/config/src/main/java/org/wildfly/microprofile/reactive/messaging/config/_private/MicroProfileReactiveMessagingConfigLogger.java
  microprofile/reactive-messaging-smallrye/config/src/main/resources/META-INF/services/io.smallrye.config.ConfigSourceInterceptorFactory
  microprofile/reactive-messaging-smallrye/config/src/test/java/org/wildfly/microprofile/reactive/messaging/config/AmqpTracingTypeConfigTestCase.java
  microprofile/reactive-messaging-smallrye/config/src/test/java/org/wildfly/microprofile/reactive/messaging/config/KafkaTracingTypeConfigTestCase.java
  microprofile/reactive-messaging-smallrye/config/src/test/java/org/wildfly/microprofile/reactive/messaging/config/TracingTypeConfigTest.java
  microprofile/reactive-messaging-smallrye/extension/pom.xml
  microprofile/reactive-messaging-smallrye/extension/src/main/java/org/wildfly/extension/microprofile/reactive/messaging/MicroProfileReactiveMessagingConnectorOpenTelemetryTracingResourceDefinition.java
  microprofile/reactive-messaging-smallrye/extension/src/main/java/org/wildfly/extension/microprofile/reactive/messaging/MicroProfileReactiveMessagingExtension.java
  microprofile/reactive-messaging-smallrye/extension/src/main/java/org/wildfly/extension/microprofile/reactive/messaging/MicroProfileReactiveMessagingSubsystemDefinition.java
  microprofile/reactive-messaging-smallrye/extension/src/main/java/org/wildfly/extension/microprofile/reactive/messaging/MicroProfileReactiveMessagingSubsystemSchema.java
  microprofile/reactive-messaging-smallrye/extension/src/main/java/org/wildfly/extension/microprofile/reactive/messaging/MicroProfileReactiveMessagingTransformers.java
  microprofile/reactive-messaging-smallrye/extension/src/main/resources/META-INF/services/org.jboss.as.controller.transform.ExtensionTransformerRegistration
  microprofile/reactive-messaging-smallrye/extension/src/main/resources/org/wildfly/extension/microprofile/reactive/messaging/LocalDescriptions.properties
  microprofile/reactive-messaging-smallrye/extension/src/main/resources/schema/wildfly-microprofile-reactive-messaging-smallrye_2_0.xsd
  microprofile/reactive-messaging-smallrye/extension/src/test/java/org/wildfly/extension/microprofile/reactive/messaging/MicroProfileReactiveMessagingAdditionalInitialization.java
  microprofile/reactive-messaging-smallrye/extension/src/test/java/org/wildfly/extension/microprofile/reactive/messaging/MicroProfileReactiveMessagingTransformersTestCase.java
  microprofile/reactive-messaging-smallrye/extension/src/test/resources/org/wildfly/extension/microprofile/reactive/messaging/microprofile-reactive-messaging-smallrye-2.0.xml
  microprofile/reactive-messaging-smallrye/kafka/src/main/java/org/wildfly/microprofile/reactive/messaging/config/kafka/ssl/context/KafkaClientCustomizer.java
  testsuite/integration/microprofile/pom.xml
  testsuite/integration/microprofile/src/test/java/org/wildfly/test/integration/microprofile/reactive/RunArtemisAmqpSetupTask.java
  testsuite/integration/microprofile/src/test/java/org/wildfly/test/integration/microprofile/reactive/messaging/otel/AmqpReactiveMessagingAndOtelConfigTestCase.java
  testsuite/integration/microprofile/src/test/java/org/wildfly/test/integration/microprofile/reactive/messaging/otel/AmqpReactiveMessagingAndOtelTestCase.java
  testsuite/integration/microprofile/src/test/java/org/wildfly/test/integration/microprofile/reactive/messaging/otel/BaseReactiveMessagingAndOtelConfigTest.java
  testsuite/integration/microprofile/src/test/java/org/wildfly/test/integration/microprofile/reactive/messaging/otel/BaseReactiveMessagingAndOtelTest.java
  testsuite/integration/microprofile/src/test/java/org/wildfly/test/integration/microprofile/reactive/messaging/otel/KafkaReactiveMessagingAndOtelConfigTestCase.java
  testsuite/integration/microprofile/src/test/java/org/wildfly/test/integration/microprofile/reactive/messaging/otel/KafkaReactiveMessagingAndOtelTestCase.java
  testsuite/integration/microprofile/src/test/java/org/wildfly/test/integration/microprofile/reactive/messaging/otel/ReactiveMessagingOtelAssertUtils.java
  testsuite/integration/microprofile/src/test/java/org/wildfly/test/integration/microprofile/reactive/messaging/otel/ReactiveMessagingOtelUtils.java
  testsuite/integration/microprofile/src/test/java/org/wildfly/test/integration/microprofile/reactive/messaging/otel/application/ConfigBeanAndEndpoint.java
  testsuite/integration/microprofile/src/test/java/org/wildfly/test/integration/microprofile/reactive/messaging/otel/application/TestReactiveMessagingOtelApplication.java
  testsuite/integration/microprofile/src/test/java/org/wildfly/test/integration/microprofile/reactive/messaging/otel/application/TestReactiveMessagingOtelBean.java
  testsuite/integration/microprofile/src/test/java/org/wildfly/test/integration/microprofile/reactive/messaging/otel/application/TestReactiveMessagingOtelEndpoint.java
  testsuite/integration/microprofile/src/test/java/org/wildfly/test/integration/microprofile/reactive/messaging/otel/application/amqp-microprofile-config.properties
  testsuite/integration/microprofile/src/test/java/org/wildfly/test/integration/microprofile/reactive/messaging/otel/application/kafka-microprofile-config.properties
Labels: Feature, deps-changed, 35.x

#18456 [WFLY-19954] Add the vertx extension/subsystem from wildfly-vertx-feature-pack to WildFly Preview Feature Pack
  boms/preview-expansion/pom.xml
  boms/preview-test-expansion/pom.xml
  galleon-pack/galleon-shared/src/main/resources/modules/system/layers/base/io/smallrye/opentelemetry/main/module.xml
  microprofile/reactive-messaging-smallrye/config/src/main/java/org/wildfly/microprofile/reactive/messaging/config/ReactiveMessagingConfigSource.java
  observability/opentelemetry-api/src/main/java/org/wildfly/extension/opentelemetry/api/WildFlyOpenTelemetryConfig.java
  pom.xml
  preview/feature-pack/pom.xml
  preview/feature-pack/wildfly-feature-pack-build.xml
  preview/galleon-local/src/main/resources/feature_groups/domain-host-excludes.xml
  testsuite/domain/src/test/java/org/jboss/as/test/integration/domain/HostExcludesTestCase.java
  testsuite/layers-expansion/pom.xml
  testsuite/layers/pom.xml
  testsuite/preview/basic/pom.xml
  testsuite/preview/basic/src/test/java/org/wildfly/test/preview/vertx/EchoService.java
  testsuite/preview/basic/src/test/java/org/wildfly/test/preview/vertx/RestApp.java
  testsuite/preview/basic/src/test/java/org/wildfly/test/preview/vertx/ServiceEndpoint.java
  testsuite/preview/basic/src/test/java/org/wildfly/test/preview/vertx/VertxSubsystemSmokeTestCase.java
  testsuite/shared/src/main/java/org/jboss/as/test/shared/LayersTestBase.java
Labels: deps-ok, 35.x

#18467 [WFLY-20084] Add profiles to wildfly sources to separate base and expansion builds/tests
  boms/user/pom.xml
  boms/user/server/ee/pom.xml
  boms/user/server/pom.xml
  pom.xml
  preview/pom.xml
  testsuite/README.md
  testsuite/aggregator-base/pom.xml
  testsuite/aggregator-expansion/pom.xml
  testsuite/aggregator-preview/pom.xml
  testsuite/build-demander-base/pom.xml
  testsuite/build-demander-expansion/pom.xml
  testsuite/build-demander-preview/pom.xml
  testsuite/integration/pom.xml
  testsuite/pom.xml
  testsuite/preview/pom.xml
Labels: deps-ok

#18498 [WFLY-20078] Disable Persistence bytecode enhancement by default
  jpa/subsystem/src/main/java/org/jboss/as/jpa/config/Configuration.java
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/jpa/hibernate/EmployeeWithLastName.java
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/jpa/hibernate/EmployeeWithLastNameNotEnhanced.java
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/jpa/hibernate/SFSBWithLastName.java
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/jpa/hibernate/classfiletransformertest/ClassFileTransformerTestCase.java
Labels: ready-for-merge

#18478 [WFLY-20066] Remove the unused Namespace class
  microprofile/lra/participant/src/main/java/org/wildfly/extension/microprofile/lra/participant/Namespace.java
Labels: ready-for-merge, deps-ok

#18484 [WFLY-20059] Create mixed domains tests against WildFly 31
  testsuite/integration/manualmode/src/test/resources/legacy-configs/domain/wildfly-31-0-0.xml
  testsuite/mixed-domain/src/test/java/org/jboss/as/test/integration/domain/mixed/DomainAdjuster.java
  testsuite/mixed-domain/src/test/java/org/jboss/as/test/integration/domain/mixed/MixedDeploymentOverlayTestCase.java
  testsuite/mixed-domain/src/test/java/org/jboss/as/test/integration/domain/mixed/Version.java
  testsuite/mixed-domain/src/test/java/org/jboss/as/test/integration/domain/mixed/eap740/DomainAdjuster740.java
  testsuite/mixed-domain/src/test/java/org/jboss/as/test/integration/domain/mixed/eap800/DomainAdjuster800.java
  testsuite/mixed-domain/src/test/java/org/jboss/as/test/integration/domain/mixed/wfly31/DomainHostExcludesWFLY31TestCase.java
  testsuite/mixed-domain/src/test/java/org/jboss/as/test/integration/domain/mixed/wfly31/KernelBehaviorWFLY31TestSuite.java
  testsuite/mixed-domain/src/test/java/org/jboss/as/test/integration/domain/mixed/wfly31/LegacyConfigWFLY31TestCase.java
  testsuite/mixed-domain/src/test/java/org/jboss/as/test/integration/domain/mixed/wfly31/LegacyConfigWFLY31TestSuite.java
  testsuite/mixed-domain/src/test/java/org/jboss/as/test/integration/domain/mixed/wfly31/MixedDomainDeploymentOverlayWFLY31TestCase.java
  testsuite/mixed-domain/src/test/java/org/jboss/as/test/integration/domain/mixed/wfly31/MixedDomainDeploymentWFLY31TestCase.java
  testsuite/mixed-domain/src/test/java/org/jboss/as/test/integration/domain/mixed/wfly31/MixedDomainOverlayWFLY31TestSuite.java
  testsuite/mixed-domain/src/test/java/org/jboss/as/test/integration/domain/mixed/wfly31/MixedDomainWFLY31TestSuite.java
  testsuite/mixed-domain/src/test/java/org/jboss/as/test/integration/domain/mixed/wfly31/RBACConfigWFLY31TestCase.java
  testsuite/mixed-domain/src/test/java/org/jboss/as/test/integration/domain/mixed/wfly31/SimpleMixedDomainWFLY31TestCase.java
  testsuite/mixed-domain/src/test/java/org/jboss/as/test/integration/domain/mixed/wfly31/WildcardReadsWFLY31TestCase.java
Labels: ready-for-merge

#18485 WFLY-20064 PersistentResourceXMLDescription of elytron-oidc-client subsystem uses marshallers/parsers inconsistent with its schema.
  elytron-oidc-client/src/main/java/org/wildfly/extension/elytron/oidc/ElytronOidcSubsystemSchema.java
Labels: ready-for-merge

#18492 WFLY-19591 Upgrade SmallRye OpenAPI to 4.0.4.
  galleon-pack/galleon-shared/src/main/resources/modules/system/layers/base/io/smallrye/openapi/main/module.xml
  pom.xml
Labels: ready-for-merge, deps-ok

#18505 WFLY-20086 Upgrade SmallRye Fault Tolerance from 6.7.0 to 6.7.1
  pom.xml
Labels: ready-for-merge, deps-ok

#18511 [WFLY-20084] With ts.bootable, ensure the test-feature-pack is built …
  testsuite/aggregator-base/pom.xml
Labels: deps-ok

#18499 WFLY-20026 run an initial recovery scan when the microprofile-lra sub…
  microprofile/lra/coordinator/src/main/java/org/wildfly/extension/microprofile/lra/coordinator/MicroProfileLRACoordinatorAdd.java
  microprofile/lra/coordinator/src/main/java/org/wildfly/extension/microprofile/lra/coordinator/_private/MicroProfileLRACoordinatorLogger.java
  microprofile/lra/coordinator/src/main/java/org/wildfly/extension/microprofile/lra/coordinator/service/LRARecoveryService.java
Labels: Critical

#18504 [WFLY-19835][WFLY-19836] Rm otel integration followup
  microprofile/reactive-messaging-smallrye/config/src/test/java/org/wildfly/microprofile/reactive/messaging/config/KafkaTracingTypeConfigTestCase.java
  microprofile/reactive-messaging-smallrye/extension/src/main/java/org/wildfly/extension/microprofile/reactive/messaging/MicroProfileReactiveMessagingConnectorOpenTelemetryTracingResourceDefinition.java
  microprofile/reactive-messaging-smallrye/extension/src/test/java/org/wildfly/extension/microprofile/reactive/messaging/MicroProfileReactiveMessagingAdditionalInitialization.java
  testsuite/integration/microprofile/src/test/java/org/wildfly/test/integration/microprofile/reactive/RunArtemisAmqpSetupTask.java
Labels: deps-changed

#18482 [WFLY-20058]: "netty-common" should depend on "org.apache.logging.log4j.api".
  clustering/infinispan/extension/pom.xml
  clustering/infinispan/extension/src/main/java/org/jboss/as/clustering/infinispan/subsystem/InfinispanExtension.java
  ee-feature-pack/galleon-shared/src/main/resources/modules/system/layers/base/io/netty/netty-common/main/module.xml
  ee-feature-pack/galleon-shared/src/main/resources/modules/system/layers/base/org/jboss/as/clustering/infinispan/main/module.xml
  messaging-activemq/subsystem/src/main/java/org/wildfly/extension/messaging/activemq/MessagingExtension.java
  microprofile/reactive-messaging-smallrye/extension/pom.xml
  microprofile/reactive-messaging-smallrye/extension/src/main/java/org/wildfly/extension/microprofile/reactive/messaging/MicroProfileReactiveMessagingExtension.java
  observability/opentelemetry/pom.xml
  observability/opentelemetry/src/main/java/org/wildfly/extension/opentelemetry/OpenTelemetrySubsystemExtension.java
  testsuite/shared/src/main/java/org/jboss/as/test/shared/LayersTestBase.java
Labels: deps-ok

#18510 WFLY-19976 LRA participant module should declare Weld dependencies for proper bean proxy creation
  galleon-pack/galleon-shared/src/main/resources/modules/system/layers/base/org/jboss/narayana/lra/lra-participant/main/module.xml
Labels: 35.x

#18529 [WFLY-20120] Limit passing -Djava.security.manager=allow to SE 18 - 23
  pom.xml
Labels: deps-ok

#18526 [WFLY-20100] Upgrade HAL to 3.7.7.Final
  pom.xml
Labels: Blocker, deps-ok

#18524 [WFLY-20118]: Upgrading to HornetQ 2.4.11.Final
  pom.xml
Labels: deps-ok

#18521 [WFLY-20105] Missing separation between G:A and V
  datasources-agroal/pom.xml
  microprofile/lra/coordinator/pom.xml
  microprofile/lra/participant/pom.xml
  testsuite/integration/microprofile-tck/jwt/pom.xml
  testsuite/integration/microprofile-tck/pom.xml
Labels: deps-ok

#18515 WFLY-20101 Disable overly fragile test cases in MessagingTestCase of VXD integration testsuite.
  testsuite/integration/vdx/src/test/java/org/wildfly/test/integration/vdx/standalone/MessagingTestCase.java
Labels: 35.x

#18503 [WFLY-20070]:Upgrade jbossws-cxf to 7.3.1.Final and jbossws-commont t…
  pom.xml
Labels: ready-for-merge, deps-changed

#18507 WFLY-19869 - @WithSpan annotations stopped working in WildFly 34
  testsuite/integration/microprofile/pom.xml
  testsuite/integration/microprofile/src/test/java/org/wildfly/test/integration/microprofile/reactive/messaging/otel/BaseReactiveMessagingAndOtelTest.java
  testsuite/integration/microprofile/src/test/java/org/wildfly/test/integration/observability/opentelemetry/ContextPropagationTestCase.java
  testsuite/integration/microprofile/src/test/java/org/wildfly/test/integration/observability/opentelemetry/OpenTelemetryIntegrationTestCase.java
  testsuite/integration/microprofile/src/test/java/org/wildfly/test/integration/observability/opentelemetry/WithSpanTestCase.java
  testsuite/shared/src/main/java/org/jboss/as/test/shared/observability/containers/BaseContainer.java
  testsuite/shared/src/main/java/org/jboss/as/test/shared/observability/containers/JaegerContainer.java
  testsuite/shared/src/main/java/org/jboss/as/test/shared/observability/containers/OpenTelemetryCollectorContainer.java
Labels: deps-ok

#18519 [WFLY-20082] Upgrade the WildFly Launcher to 1.0.0.Final.
  pom.xml
Labels: Blocker, deps-ok, 35.x

#18530 [WFLY-20124] Don't test SecurityManager in AppClientScriptTestCase on…
  testsuite/scripts/src/test/java/org/wildfly/test/scripts/AppClientScriptTestCase.java
Labels: 35.x

#18545 [WFLY-20315] / [WFLY-20316] / [WFLY-20317] SCA Override Clean Up
  sca-overrides/owasp-suppressions.xml
Labels: Critical, 35.x

#18531 [WFLY-20125] Don't run testsuite/integration/secman tests on SE 24+
  testsuite/integration/secman/pom.xml
Labels: deps-ok, 35.x

#18497 WFLY-20075 - MP Telemetry Metrics (OpenTelemetry) without any rest/servlet call
  observability/opentelemetry-api/src/main/java/org/wildfly/extension/opentelemetry/api/OpenTelemetryCdiExtension.java
  testsuite/integration/microprofile/src/test/java/org/wildfly/test/integration/observability/opentelemetry/BaseOpenTelemetryTest.java
  testsuite/integration/microprofile/src/test/java/org/wildfly/test/integration/observability/opentelemetry/OpenTelemetryMetricsTestCase.java
Labels: 35.x

#18489 WFLY-19689 - Micrometer extension keeps pushing metrics after removal and reload
  observability/micrometer/src/main/java/org/wildfly/extension/micrometer/MicrometerSubsystemRegistrar.java
  observability/micrometer/src/main/java/org/wildfly/extension/micrometer/metrics/MicrometerCollector.java
  observability/micrometer/src/main/java/org/wildfly/extension/micrometer/registry/WildFlyRegistry.java
  testsuite/integration/microprofile/src/test/java/org/wildfly/test/integration/observability/micrometer/MicrometerRemovalTestCase.java
Labels: Blocker, 35.x

#18435 [WFLY-20007] Remove all non-breaking uses of ModuleIdentifier in Messaging Subsystem
  messaging-activemq/subsystem/src/main/java/org/wildfly/extension/messaging/activemq/ServerAdd.java
  messaging-activemq/subsystem/src/main/java/org/wildfly/extension/messaging/activemq/jms/bridge/JMSBridgeFactory.java
  messaging-activemq/subsystem/src/main/java/org/wildfly/extension/messaging/activemq/jms/bridge/JMSBridgeService.java
Labels: deps-ok

#18532 [WFLY-20122] Disable tests using org.jboss.as.naming.SecurityHelper o…
  naming/pom.xml
  naming/src/test/java/org/jboss/as/naming/NamingContextTestCase.java
  naming/src/test/java/org/jboss/as/naming/WritableServiceBasedNamingStoreTestCase.java
Labels: deps-ok, 35.x

#18547 WFLY-20138 Update Weld 5 and Weld 6
  boms/preview-ee/pom.xml
  pom.xml
Labels: deps-ok, 35.x

#18553 [WFLY-20145] Upgrade WildFly Core to 27.0.0.Beta6
  pom.xml
Labels: deps-ok, 35.x

#18068 [WFLY-19569] Revert "[WFLY-18174] Change the default jakarta.faces.FACELETS_BUFFER…
  jsf/subsystem/src/main/java/org/jboss/as/jsf/deployment/JSFMetadataProcessor.java
Labels: hold

#18554 WFLY-20146 - Upgrade SR OpenTelemetry to 2.9.1
  pom.xml
Labels: Blocker, deps-ok, 35.x

#18534 [WFLY-20015] Remove all non-breaking uses of ModuleIdentifier in Web …
  webservices/server-integration/src/main/java/org/jboss/as/webservices/util/ModuleClassLoaderProvider.java
Labels: 35.x

#18551 WFLY-19986 Increment Infinispan subsystem model version for WF35 so that WF31 transformations have a valid target.
  clustering/infinispan/extension/src/main/java/org/jboss/as/clustering/infinispan/subsystem/CacheContainerResourceTransformer.java
  clustering/infinispan/extension/src/main/java/org/jboss/as/clustering/infinispan/subsystem/InfinispanSubsystemModel.java
Labels: 35.x

#18544 WFLY-20133 Upgrade Hibernate Validator to 9.0.0.CR1 in WildFly preview / WFLY-20132 Upgrade Hibernate Validator to 8.0.2.Final
  boms/preview-ee/pom.xml
  pom.xml
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/beanvalidation/hibernate/validator/Car.java
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/beanvalidation/hibernate/validator/Employee.java
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/beanvalidation/hibernate/validator/UserBean.java
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/jca/beanvalidation/ra/ValidAdminObjectImpl1.java
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/jpa/beanvalidation/Player.java
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/jpa/beanvalidation/SoccerPlayer.java
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/jpa/beanvalidation/beanvalidationinheritancetest/BeanValidationJPAInheritanceTestCase.java
Labels: deps-ok, 35.x

#18555 Fix for WFLY-20149, Upgrade WildFly Glow to 1.2.0.Final
  pom.xml
Labels: Blocker, deps-ok, 35.x

#18557 [WFLY-20152] Remove all non-breaking uses of ModuleIdentifier in EE Subsystem
  ee/src/main/java/org/jboss/as/ee/structure/GlobalModuleDependencyProcessor.java
  ee/src/main/java/org/jboss/as/ee/subsystem/GlobalModulesDefinition.java
Labels: 35.x

#18509 WFLY-20068 Upgrade wildfly-clustering to 5.0.3.Final.
  boms/standard-test/pom.xml
  clustering/ejb/cache/src/main/java/org/wildfly/clustering/ejb/cache/timer/TimerFactory.java
  clustering/ejb/infinispan/src/main/java/org/wildfly/clustering/ejb/infinispan/bean/BeanExpirationScheduler.java
  clustering/ejb/infinispan/src/main/java/org/wildfly/clustering/ejb/infinispan/bean/InfinispanBeanManager.java
  clustering/ejb/infinispan/src/main/java/org/wildfly/clustering/ejb/infinispan/bean/InfinispanBeanMetaDataFilter.java
  clustering/ejb/infinispan/src/main/java/org/wildfly/clustering/ejb/infinispan/bean/InfinispanBeanSerializationContextInitializer.java
  clustering/ejb/infinispan/src/main/java/org/wildfly/clustering/ejb/infinispan/timer/InfinispanTimer.java
  clustering/ejb/infinispan/src/main/java/org/wildfly/clustering/ejb/infinispan/timer/InfinispanTimerFactory.java
  clustering/ejb/infinispan/src/main/java/org/wildfly/clustering/ejb/infinispan/timer/InfinispanTimerManager.java
  clustering/ejb/infinispan/src/main/java/org/wildfly/clustering/ejb/infinispan/timer/InfinispanTimerSerializationContextInitializer.java
  clustering/ejb/infinispan/src/main/java/org/wildfly/clustering/ejb/infinispan/timer/ScheduleWithPersistentTimeoutMetaDataCommand.java
  clustering/ejb/infinispan/src/main/java/org/wildfly/clustering/ejb/infinispan/timer/SimpleTimeoutMetaData.java
  clustering/ejb/infinispan/src/main/java/org/wildfly/clustering/ejb/infinispan/timer/TimerCacheEntryFilter.java
  clustering/ejb/infinispan/src/main/java/org/wildfly/clustering/ejb/infinispan/timer/TimerCacheKeyFilter.java
  clustering/ejb/infinispan/src/main/java/org/wildfly/clustering/ejb/infinispan/timer/TimerScheduler.java
  clustering/ejb/infinispan/src/main/resources/org.wildfly.clustering.ejb.infinispan.bean.proto
  clustering/ejb/infinispan/src/main/resources/org.wildfly.clustering.ejb.infinispan.timer.proto
  clustering/ejb/infinispan/src/test/java/org/wildfly/clustering/ejb/infinispan/bean/InfinispanBeanMetaDataFilterTestCase.java
  clustering/ejb/infinispan/src/test/java/org/wildfly/clustering/ejb/infinispan/timer/SimpleTimeoutMetaDataTestCase.java
  clustering/ejb/infinispan/src/test/java/org/wildfly/clustering/ejb/infinispan/timer/TimerCacheStreamFilterTestCase.java
  clustering/ejb/spi/src/main/java/org/wildfly/clustering/ejb/timer/ImmutableTimerMetaData.java
  clustering/ejb/spi/src/main/java/org/wildfly/clustering/ejb/timer/TimeoutMetaData.java
  clustering/faces/mojarra/src/test/java/org/wildfly/clustering/faces/mojarra/context/SessionMapMutexMarshallerTestCase.java
  clustering/pom.xml
  docs/src/main/asciidoc/_high-availability/Distributable_Web_Applications.adoc
  jpa/hibernate6/pom.xml
  pom.xml
  testsuite/integration/clustering/pom.xml
  testsuite/integration/clustering/src/test/java/org/jboss/as/test/clustering/cluster/web/CoarseNonTransactionalSessionActivationTestCase.java
  testsuite/integration/clustering/src/test/java/org/jboss/as/test/clustering/cluster/web/CoarseNonTransactionalWebFailoverTestCase.java
  testsuite/integration/clustering/src/test/java/org/jboss/as/test/clustering/cluster/web/FineNonTransactionalSessionActivationTestCase.java
  testsuite/integration/clustering/src/test/java/org/jboss/as/test/clustering/cluster/web/FineNonTransactionalWebFailoverTestCase.java
  testsuite/integration/clustering/src/test/java/org/jboss/as/test/clustering/cluster/web/NonTransactionalSessionServerSetup.java
  testsuite/integration/clustering/src/test/java/org/jboss/as/test/clustering/cluster/web/jboss-all_non-tx_coarse.xml
  testsuite/integration/clustering/src/test/java/org/jboss/as/test/clustering/cluster/web/jboss-all_non-tx_fine.xml
Labels: deps-changed, Critical, 35.x

#18558 Revert "[WFLY-19569] Revert "[WFLY-18174] Change the default jakarta.faces.FACELETS_BUFFER…"
  jsf/subsystem/src/main/java/org/jboss/as/jsf/deployment/JSFMetadataProcessor.java
Labels: hold

#18559 Fix for WFLY-20154, Upgrade WildFly Maven Plugin to 5.1.0.Final
  pom.xml
Labels: Blocker, deps-ok, 35.x

#18556 [WFLY-20150][WFLY-20151] A couple of TLDs fixes - switch to non deprecated module name plus added missing TLDs
  web-common/src/main/java/org/jboss/as/web/common/SharedTldsMetaDataBuilder.java
Labels: 35.x

#18098 WFLY-19550 Distributed timer service implementation should not schedule timers while server is suspended.
  check_logging.sh
  clustering/ejb/infinispan/src/main/java/org/wildfly/clustering/ejb/infinispan/timer/InfinispanTimer.java
  clustering/ejb/infinispan/src/main/java/org/wildfly/clustering/ejb/infinispan/timer/InfinispanTimerFactory.java
  clustering/ejb/infinispan/src/main/java/org/wildfly/clustering/ejb/infinispan/timer/InfinispanTimerManagementProvider.java
  clustering/ejb/infinispan/src/main/java/org/wildfly/clustering/ejb/infinispan/timer/InfinispanTimerManager.java
  clustering/ejb/infinispan/src/main/java/org/wildfly/clustering/ejb/infinispan/timer/InfinispanTimerManagerFactory.java
  clustering/ejb/infinispan/src/main/java/org/wildfly/clustering/ejb/infinispan/timer/InfinispanTimerMetaDataFactory.java
  clustering/ejb/infinispan/src/main/java/org/wildfly/clustering/ejb/infinispan/timer/TimerScheduler.java
  clustering/ejb/spi/src/main/java/org/wildfly/clustering/ejb/timer/Timer.java
  clustering/ejb/spi/src/main/java/org/wildfly/clustering/ejb/timer/TimerManager.java
  clustering/infinispan/embedded/service/pom.xml
  clustering/infinispan/embedded/service/src/main/java/org/wildfly/clustering/infinispan/service/CacheServiceInstallerFactory.java
  ee-feature-pack/galleon-shared/src/main/resources/modules/system/layers/base/org/jboss/as/ejb3/main/module.xml
  ee-feature-pack/galleon-shared/src/main/resources/modules/system/layers/base/org/wildfly/clustering/infinispan/embedded/service/main/module.xml
  ejb3/pom.xml
  ejb3/src/main/java/org/jboss/as/ejb3/component/EJBComponent.java
  ejb3/src/main/java/org/jboss/as/ejb3/deployment/processors/TimerServiceDeploymentProcessor.java
  ejb3/src/main/java/org/jboss/as/ejb3/remote/EJBRemoteConnectorService.java
  ejb3/src/main/java/org/jboss/as/ejb3/subsystem/DatabaseDataStoreAdd.java
  ejb3/src/main/java/org/jboss/as/ejb3/subsystem/DatabaseDataStoreResourceDefinition.java
  ejb3/src/main/java/org/jboss/as/ejb3/subsystem/EJB3AsyncResourceDefinition.java
  ejb3/src/main/java/org/jboss/as/ejb3/subsystem/EJB3AsyncServiceAdd.java
  ejb3/src/main/java/org/jboss/as/ejb3/subsystem/EJB3RemoteResourceDefinition.java
  ejb3/src/main/java/org/jboss/as/ejb3/subsystem/EJB3RemoteServiceAdd.java
  ejb3/src/main/java/org/jboss/as/ejb3/subsystem/EJB3SubsystemRootResourceDefinition.java
  ejb3/src/main/java/org/jboss/as/ejb3/subsystem/FileDataStoreAdd.java
  ejb3/src/main/java/org/jboss/as/ejb3/subsystem/FileDataStoreResourceDefinition.java
  ejb3/src/main/java/org/jboss/as/ejb3/subsystem/TimerPersistenceResourceDefinition.java
  ejb3/src/main/java/org/jboss/as/ejb3/subsystem/TimerServiceAdd.java
  ejb3/src/main/java/org/jboss/as/ejb3/subsystem/TimerServiceResourceDefinition.java
  ejb3/src/main/java/org/jboss/as/ejb3/timerservice/NonFunctionalTimerService.java
  ejb3/src/main/java/org/jboss/as/ejb3/timerservice/NonFunctionalTimerServiceFactory.java
  ejb3/src/main/java/org/jboss/as/ejb3/timerservice/SuspendableTimerService.java
  ejb3/src/main/java/org/jboss/as/ejb3/timerservice/TimerServiceConfiguration.java
  ejb3/src/main/java/org/jboss/as/ejb3/timerservice/TimerServiceFactoryServiceConfigurator.java
  ejb3/src/main/java/org/jboss/as/ejb3/timerservice/TimerServiceFactoryServiceInstaller.java
  ejb3/src/main/java/org/jboss/as/ejb3/timerservice/TimerServiceImpl.java
  ejb3/src/main/java/org/jboss/as/ejb3/timerservice/composite/CompositeTimerService.java
  ejb3/src/main/java/org/jboss/as/ejb3/timerservice/composite/CompositeTimerServiceFactoryServiceConfigurator.java
  ejb3/src/main/java/org/jboss/as/ejb3/timerservice/composite/CompositeTimerServiceFactoryServiceInstaller.java
  ejb3/src/main/java/org/jboss/as/ejb3/timerservice/distributable/DistributableTimerService.java
  ejb3/src/main/java/org/jboss/as/ejb3/timerservice/distributable/DistributableTimerServiceFactoryServiceInstaller.java
  ejb3/src/main/java/org/jboss/as/ejb3/timerservice/distributable/DistributableTimerSynchronizationFactory.java
  ejb3/src/main/java/org/jboss/as/ejb3/timerservice/distributable/OOBTimer.java
  ejb3/src/main/java/org/jboss/as/ejb3/timerservice/persistence/TimerPersistence.java
  ejb3/src/main/java/org/jboss/as/ejb3/timerservice/spi/ManagedTimerService.java
  testsuite/integration/clustering/src/test/java/org/jboss/as/test/clustering/cluster/ejb/remote/SuspendResumeRemoteEJBTestCase.java
Labels: deps-ok, 35.x

#18249 [WFLY-19783] Upgrade the keycloak-services and keycloak-core test dependencies to 25.0.6
  pom.xml
Labels: deps-ok, Critical, 35.x

#18541 [WFLY-19907] Update the WildFly vs WildFly Preview document for curre…
  docs/src/main/asciidoc/WildFly_and_WildFly_Preview.adoc
Labels: Blocker, 35.x

#18550 WFLY-20139 Upgrade otel/opentelemetry-collector image to 0.115.1 and jaegertracing/all-in-one to 1.64.0
  testsuite/integration/microprofile/src/test/java/org/wildfly/test/integration/microprofile/faulttolerance/opentelemetry/FaultToleranceOpenTelemetryIntegrationTestCase.java
  testsuite/integration/microprofile/src/test/java/org/wildfly/test/integration/observability/opentelemetry/BaseOpenTelemetryTest.java
  testsuite/shared/src/main/java/org/jboss/as/test/shared/observability/containers/JaegerContainer.java
  testsuite/shared/src/main/java/org/jboss/as/test/shared/observability/containers/OpenTelemetryCollectorContainer.java
  testsuite/shared/src/main/resources/org/jboss/as/test/shared/observability/containers/otel-collector-config.yaml
Labels: 35.x

#17479 [WFLY-18818]:Print log info to let user know the cxf dependenc…
  webservices/server-integration/src/main/java/org/jboss/as/webservices/deployers/WSClassVerificationProcessor.java
  webservices/server-integration/src/main/java/org/jboss/as/webservices/logging/WSLogger.java
  webservices/server-integration/src/test/java/org/jboss/as/webservices/deployers/WSClassVerificationProcessorTestCase.java
Labels: 35.x

#18565 Revert "[WFLY-18174] Change the default jakarta.faces.FACELETS_BUFFER…
  jsf/subsystem/src/main/java/org/jboss/as/jsf/deployment/JSFMetadataProcessor.java
Labels: 35.x

#18569 [WFLY-20163][WFLY-20191] Reuse forks when running testsuite/integration/elytron
  testsuite/integration/elytron/pom.xml
  testsuite/integration/elytron/src/test/java/org/wildfly/test/integration/elytron/realm/FilesystemRealmEncryptedTestCase.java
Labels: deps-ok, 35.x

#18546 WFLY-20023 Remove all non-breaking uses of ModuleIdentifier in Concurrency
  concurrency/spi/src/main/java/org/jboss/as/ee/concurrent/ConcurrentContext.java
Labels: 35.x

#18583 [WFLY-20178] Upgrade WildFly Core to 27.0.0.Beta7
  pom.xml
Labels: deps-ok, Critical, 35.x

#18566 WFLY-20161 Upgrade mod_cluster to 2.1.0.Final
  pom.xml
Labels: deps-ok, 35.x

#18567 [WFLY-20162] Start Artemis/AMQP in testcontainers rather than embedded
  testsuite/integration/microprofile/src/test/java/org/wildfly/test/integration/microprofile/reactive/RunArtemisAmqpSetupTask.java
  testsuite/integration/microprofile/src/test/java/org/wildfly/test/integration/microprofile/reactive/messaging/amqp/AnonymousAmqpTestCase.java
  testsuite/integration/microprofile/src/test/java/org/wildfly/test/integration/microprofile/reactive/messaging/amqp/SslAmqpWithSslConfiguredGloballyTestCase.java
  testsuite/integration/microprofile/src/test/java/org/wildfly/test/integration/microprofile/reactive/messaging/amqp/SslAmqpWithSslConfiguredOnConnectorTestCase.java
  testsuite/integration/microprofile/src/test/java/org/wildfly/test/integration/microprofile/reactive/messaging/amqp/microprofile-config-no-ssl.properties
  testsuite/integration/microprofile/src/test/java/org/wildfly/test/integration/microprofile/reactive/messaging/amqp/microprofile-config-ssl-connector.properties
  testsuite/integration/microprofile/src/test/java/org/wildfly/test/integration/microprofile/reactive/messaging/amqp/microprofile-config-ssl-global.properties
  testsuite/integration/microprofile/src/test/java/org/wildfly/test/integration/microprofile/reactive/messaging/multiple/deployment/amqp/microprofile-config.properties
  testsuite/integration/microprofile/src/test/java/org/wildfly/test/integration/microprofile/reactive/messaging/multiple/earmodule/amqp/microprofile-config.properties
  testsuite/integration/microprofile/src/test/java/org/wildfly/test/integration/microprofile/reactive/messaging/otel/application/amqp-microprofile-config.properties
  testsuite/integration/microprofile/src/test/resources/org/wildfly/test/integration/microprofile/reactive/messaging/amqp/broker-ssl.xml
  testsuite/integration/microprofile/src/test/resources/org/wildfly/test/integration/microprofile/reactive/messaging/amqp/launch.sh
Labels: 35.x

#18595 WFLY-20215 Upgrade wildfly-clustering to 5.0.4.Final.
  clustering/ejb/infinispan/src/main/java/org/wildfly/clustering/ejb/infinispan/timer/InfinispanTimerManager.java
  pom.xml
Labels: deps-ok, 35.x

#18598 [WFLY-20218] Upgrade WildFly Core to 27.0.0.Final
  pom.xml
Labels: deps-ok

#18594 [WFLY-20008] Remove another ModuleIdentifier use now that core's API …
  pojo/src/main/java/org/jboss/as/pojo/descriptor/ModuleConfig.java
Labels: 35.x

#18596 [WFLY-20216] Add org.jboss.logmanager:jboss-logmanager as a test depe…
  testsuite/layers-expansion/pom.xml
  testsuite/layers/pom.xml
Labels: deps-ok, 35.x
