Repository wildfly/wildfly, pull requests merged in 2024-02, with the labels that each got.

#17571 WFLY-18966: bump licenses-plugin to 2.4.1.Final, delete unneeded entries
  ee-feature-pack/galleon-shared/src/main/resources/license/licenses.xml
  galleon-pack/galleon-shared/src/main/resources/license/licenses.xml
  pom.xml
Labels: deps-ok

#17568 [WFLY-18970] Upgrade ASM to 9.6
  pom.xml
Labels: deps-ok

#17577 [WFLY-18980][WFLY-18981] Upgrade SR Config (3.5.2) and Reactive Messaging (4.16.0)
  pom.xml
Labels: deps-ok

#17592 [WFLY-19001]:Upgrade joda-time from 2.12.5 to 2.12.6
  pom.xml
Labels: deps-ok

#17563 Fix for WFLY-18964, Upgrade to Galleon 6 Beta2, upgrade all provisioning tooling
  pom.xml
Labels: deps-ok

#17449 [WFLY-18786] Add tests for SetRequestInformationCallbackMechanismFactory
  testsuite/integration/elytron/src/test/java/org/wildfly/test/integration/elytron/http/CustomRealm.java
  testsuite/integration/elytron/src/test/java/org/wildfly/test/integration/elytron/http/SetRequestInformationCallbackMechanismFactoryTestCase.java
  testsuite/integration/elytron/src/test/java/org/wildfly/test/integration/elytron/http/SetRequestInformationCallbackTest-web.xml
  testsuite/integration/elytron/src/test/java/org/wildfly/test/integration/elytron/http/custom-realm-jboss-web.xml
Labels: 32.x

#17567 [WFLY-18969] Give the Apache Lucene module access to jdk.unsupported
  ee-feature-pack/galleon-shared/src/main/resources/modules/system/layers/base/org/apache/lucene/main/module.xml
Labels: 31.x

#17604 [WFLY-19013] Upgrade wildfly-transaction-client to 3.0.4.Final
  pom.xml
Labels: deps-ok

#17609 WFLY-18989 Upgrade to Hibernate 6.4.4.Final release
  pom.xml
Labels: deps-ok

#17612 [WFLY-19022] Upgrade testcontainers to 1.19.5
  pom.xml
Labels: deps-ok

#17578 [WFLY-18982]: Upgrade Apache Artemis to 2.32.0
  boms/common-ee/pom.xml
  ee-feature-pack/galleon-shared/src/main/resources/modules/system/layers/base/org/apache/activemq/artemis/main/module.xml
  messaging-activemq/subsystem/src/main/java/org/wildfly/extension/messaging/activemq/MessagingSubsystemAdd.java
  messaging-activemq/subsystem/src/main/java/org/wildfly/extension/messaging/activemq/ha/HAPolicyConfigurationBuilder.java
  messaging-activemq/subsystem/src/main/java/org/wildfly/extension/messaging/activemq/jms/ConnectionFactoryAttributes.java
  pom.xml
Labels: deps-ok

#17331 [WFLY-18604][WFLY-18681] re-evaluated test exclusions for ts.preview and ts.bootable.preview profiles
  pom.xml
  testsuite/domain/pom.xml
  testsuite/integration/clustering/pom.xml
  testsuite/integration/pom.xml
Labels: deps-ok

#17620 [WFLY-19028] Upgrade openjdk-orb to 10.1.0.Final
  pom.xml
Labels: deps-ok

#17629 [WFLY-19032] Upgrade snappy-java to 1.1.10.5
  pom.xml
Labels: deps-ok

#17630 [31.x] [WFLY-19032] Upgrade snappy-java to 1.1.10.5
  pom.xml
Labels: 31.x

#17635 [WFLY-19034] Upgrade nimbus-jose-jwt to 9.37.3
  pom.xml
Labels: deps-ok

#17636 [31.x] [WFLY-19034] Upgrade nimbus-jose-jwt to 9.37.3
  pom.xml
Labels: ready-for-merge, 31.x

#17619 31.x - [WFLY-19010] Elytron registry is in common module
  microprofile/reactive-messaging-smallrye/extension/src/main/java/org/wildfly/extension/microprofile/reactive/messaging/MicroProfileReactiveMessagingSubsystemDefinition.java
Labels: ready-for-merge, 31.x

#17631 WFLY-19020 Application client applications should be able to deploy persistence units
  jpa/subsystem/src/main/java/org/jboss/as/jpa/processor/PersistenceUnitParseProcessor.java
  jpa/subsystem/src/main/java/org/jboss/as/jpa/subsystem/JPASubSystemAdd.java
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/ee/appclient/basic/Employee.java
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/ee/appclient/basic/SimpleApplicationClientTestCase.java
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/ee/appclient/basic/SimpleApplicationClientTestCase2.java
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/ee/appclient/basic/persistence.xml
Labels: ready-for-merge, 31.x

#17591 WFLY-19029 Hibernate ORM 6.4+ should export services to consumer classpath
  ee-feature-pack/galleon-shared/src/main/resources/modules/system/layers/base/org/hibernate/jipijapa-hibernate6/main/module.xml
  ee-feature-pack/galleon-shared/src/main/resources/modules/system/layers/base/org/hibernate/main/module.xml
Labels: deps-ok

#17639 [WFLY-19037] Upgrade WildFly Core to 24.0.0.Beta1
  ee-feature-pack/galleon-shared/src/main/resources/feature_groups/domain-host-excludes.xml
  galleon-pack/galleon-local/src/main/resources/feature_groups/domain-host-excludes.xml
  pom.xml
  preview/galleon-local/src/main/resources/feature_groups/domain-host-excludes.xml
  testsuite/domain/src/test/java/org/jboss/as/test/integration/domain/HostExcludesTestCase.java
  testsuite/integration/elytron/src/test/java/org/wildfly/test/integration/elytron/realm/JaasCustomRealmTest-web.xml
  testsuite/integration/elytron/src/test/java/org/wildfly/test/integration/elytron/realm/JaasCustomRealmTest.java
  testsuite/integration/elytron/src/test/java/org/wildfly/test/integration/elytron/realm/TestCallbackHandler.java
  testsuite/integration/elytron/src/test/java/org/wildfly/test/integration/elytron/realm/TestLoginModule.java
  testsuite/integration/elytron/src/test/java/org/wildfly/test/integration/elytron/realm/jaas-jboss-web.xml
  testsuite/integration/elytron/src/test/resources/org/wildfly/test/integration/elytron/realm/jaas-login.config
  testsuite/shared/src/main/java/org/jboss/as/test/shared/LayersTestBase.java
Labels: deps-changed

#17640 [WFLY-19041] Upgrade HAL to 3.7.0.Final
  pom.xml
Labels: deps-ok

#17641 [WFLY-19042] Upgrade HAL to 3.7.0.Final (WildFly 31.0.1.Final)
  pom.xml
Labels: 31.x

#17627 WFLY-19019: Do not hide exceptions of failed deployments in case unde…
  undertow/src/main/java/org/wildfly/extension/undertow/deployment/UndertowDeploymentService.java
Labels: ready-for-merge, 31.x

#17624 WFLY-18946 Upgrade Infinispan to 14.0.22.Final
  clustering/infinispan/extension/src/main/java/org/jboss/as/clustering/infinispan/client/ManagedRemoteCache.java
  pom.xml
Labels: ready-for-merge, 31.x

#17642 WFLY-19029 Hibernate ORM 6.4+ should export services to consumer clas…
  ee-feature-pack/galleon-shared/src/main/resources/modules/system/layers/base/org/hibernate/jipijapa-hibernate6/main/module.xml
  ee-feature-pack/galleon-shared/src/main/resources/modules/system/layers/base/org/hibernate/main/module.xml
Labels: 31.x

#17644 WFLY-19040 Configure SNI hostnames per cluster if possible
  clustering/infinispan/extension/src/main/java/org/jboss/as/clustering/infinispan/subsystem/remote/RemoteCacheContainerConfigurationServiceConfigurator.java
Labels: Critical, 31.x

#17648 [WFLY-19048] Upgrade WildFly Core to 23.0.2.Final
  pom.xml
Labels: 31.x

#17633 WFLY-18977 Upgrade jgroups-kubernetes to 2.0.2.Final
  pom.xml
Labels: deps-ok

#17647 WFLY-19045, WFLY-19046 Upgrade Infinispan to 14.0.24.Final, JGroups to 5.2.22.Final
  pom.xml
Labels: 31.x

#17649 WFLY-18977 Upgrade jgroups-kubernetes to 2.0.2.Final
  pom.xml
Labels: 31.x

#17655 [WFLY-19058] Upgrade WildFly Core to 23.0.3.Final
  pom.xml
Labels: ready-for-merge, Critical, 31.x

#17605 [WFLY-19014][WFLY-19035] Upgrade jboss-ejb-client to 5.0.6.Final, wildfly-http-client to 2.0.7.Final
  pom.xml
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/ejb/remote/contextdata/UseCaseValidator.java
Labels: deps-ok
