Repository wildfly/wildfly, pull requests merged in 2024-06, with the labels that each got.

#17935 [WFLY-19388] Upgrade WildFly Core to 25.0.0.Beta3
  pom.xml
Labels: deps-ok

#17926 [WFLY-19375]:Add the missing cxf-rt-features-throttling dependency
  boms/common-ee/pom.xml
  ee-feature-pack/galleon-shared/pom.xml
  ee-feature-pack/galleon-shared/src/main/resources/modules/system/layers/base/org/apache/cxf/impl/main/module.xml
Labels: deps-changed

#17938 [WFLY-19395] Upgrade WildFly Arquillian to 5.1.0.Beta3. This allows o…
  pom.xml
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/deployment/resourcelisting/JarResourceListingTestCase.java
  testsuite/integration/multinode/src/test/java/org/jboss/as/test/multinode/ejb/http/EjbOverHttpTestCase.java
  testsuite/integration/web/src/test/java/org/jboss/as/test/integration/deployment/resourcelisting/WarResourceListingTestCase.java
Labels: deps-ok

#17931 [WFLY-19166]: Upgrading to Apache Artemis 2.34.0
  messaging-activemq/subsystem/pom.xml
  messaging-activemq/subsystem/src/main/java/org/wildfly/extension/messaging/activemq/ConnectorServiceDefinition.java
  pom.xml
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/messaging/mgmt/PrintDataTestCase.java
Labels: deps-ok

#17950 [WFLY-19405][WFLY-19406] MicroProfile TCK with WildFly Preview fixes
  testsuite/integration/microprofile-tck/pom.xml
  testsuite/integration/microprofile-tck/rest-client/pom.xml
Labels: deps-ok

#17952 [WFLY-19182] Update testsuite.test.galleon.pack.artifactId uses that …
  pom.xml
  testsuite/pom.xml
Labels: deps-ok

#17946 [WFLY-19400][WFLY-19401][WFLY-19402][WFLY-19403] EE11 updates part 1
  boms/preview-ee/pom.xml
Labels: deps-ok

#17903 [WFLY-19198] Move the OIDC scope related tests back to the elytron-oidc-client testsuite: delete manualmode tests
  testsuite/integration/elytron-oidc-client/src/test/java/org/wildfly/test/integration/elytron/oidc/client/KeycloakConfiguration.java
  testsuite/integration/elytron-oidc-client/src/test/java/org/wildfly/test/integration/elytron/oidc/client/OidcBaseTest.java
  testsuite/integration/elytron-oidc-client/src/test/java/org/wildfly/test/integration/elytron/oidc/client/deployment/OidcWithDeploymentConfigTest.java
  testsuite/integration/elytron-oidc-client/src/test/java/org/wildfly/test/integration/elytron/oidc/client/subsystem/OidcWithSubsystemConfigTest.java
  testsuite/integration/elytron-oidc-client/src/test/java/org/wildfly/test/integration/elytron/oidc/client/subsystem/SimpleServletWithScope.java
  testsuite/integration/elytron-oidc-client/src/test/resources/org/wildfly/test/integration/elytron/oidc/client/deployment/OidcWithInvalidScope.json
  testsuite/integration/elytron-oidc-client/src/test/resources/org/wildfly/test/integration/elytron/oidc/client/deployment/OidcWithMultipleScopes.json
  testsuite/integration/elytron-oidc-client/src/test/resources/org/wildfly/test/integration/elytron/oidc/client/deployment/OidcWithOpenIDScope.json
  testsuite/integration/elytron-oidc-client/src/test/resources/org/wildfly/test/integration/elytron/oidc/client/deployment/OidcWithSingleScope.json
  testsuite/integration/manualmode/pom.xml
  testsuite/integration/manualmode/src/test/java/org/wildfly/test/manual/elytron/oidc/KeycloakConfiguration.java
  testsuite/integration/manualmode/src/test/java/org/wildfly/test/manual/elytron/oidc/KeycloakContainer.java
  testsuite/integration/manualmode/src/test/java/org/wildfly/test/manual/elytron/oidc/OidcBaseTest.java
  testsuite/integration/manualmode/src/test/java/org/wildfly/test/manual/elytron/oidc/deployment/OidcWithDeploymentConfigTest.java
  testsuite/integration/manualmode/src/test/java/org/wildfly/test/manual/elytron/oidc/subsystem/OidcWithSubsystemConfigTest.java
  testsuite/integration/manualmode/src/test/resources/arquillian.xml
  testsuite/integration/manualmode/src/test/resources/org/wildfly/test/manual/elytron/oidc/deployment/web.xml
Labels: deps-ok

#17896 WFLY-19349 Add missing protostream marshaller (and Immutability) for SessionMap.Mutex
  clustering/faces/mojarra/src/main/java/org/wildfly/clustering/faces/mojarra/MojarraSerializationContextInitializerProvider.java
  clustering/faces/mojarra/src/main/java/org/wildfly/clustering/faces/mojarra/context/ContextImmutability.java
  clustering/faces/mojarra/src/main/java/org/wildfly/clustering/faces/mojarra/context/ContextMarshallerProvider.java
  clustering/faces/mojarra/src/main/resources/com.sun.faces.context.proto
Labels: deps-ok

#17953 [WFLY-19407] additional artifacts in EE BOMs
  boms/user/ee/ee-with-tools/pom.xml
  boms/user/ee/pom.xml
Labels: deps-ok

#17971 [WFLY-19443] Upgrade WildFly Core to 25.0.0.Beta4
  pom.xml
Labels: deps-ok

#17865 [WFLY-17324] Add documentation for the new wildfly.elytron.oidc.allow.query.params system property
  docs/src/main/asciidoc/_admin-guide/subsystem-configuration/Elytron_OIDC_Client.adoc
Labels: core-upgrade-needed

#17960 Fix for WFLY-19423, Upgrade to Galleon Plugins 7.1.0.Final
  ee-feature-pack/galleon-feature-pack/pom.xml
  ee-feature-pack/galleon-feature-pack/wildfly-feature-pack-build.xml
  galleon-pack/galleon-feature-pack/pom.xml
  galleon-pack/galleon-feature-pack/wildfly-feature-pack-build.xml
  pom.xml
  preview/feature-pack/pom.xml
  preview/feature-pack/wildfly-feature-pack-build.xml
Labels: deps-ok

#17944 [WFLY-19399] Upgrade WildFly Preview to jakarta.enterprise.concurrent…
  boms/preview-ee/pom.xml
Labels: EE11

#17943 [WFLY-19404] Upgrade WildFly Preview to jakarta.websocket:jakarta.web…
  boms/preview-ee/pom.xml
Labels: EE11

#17957 WFLY-19412 Add EAP 8.0.0 transform/reject tests for jgroups subsystem
  clustering/jgroups/extension/src/main/java/org/jboss/as/clustering/jgroups/subsystem/JGroupsSubsystemResourceTransformer.java
  clustering/jgroups/extension/src/test/java/org/jboss/as/clustering/jgroups/subsystem/JGroupsTransformersTestCase.java
  clustering/jgroups/extension/src/test/resources/org/jboss/as/clustering/jgroups/subsystem/jgroups-reject.xml
  clustering/jgroups/extension/src/test/resources/org/jboss/as/clustering/jgroups/subsystem/jgroups-transform-10_0_0.xml
  clustering/jgroups/extension/src/test/resources/org/jboss/as/clustering/jgroups/subsystem/jgroups-transform-8_0_0.xml
Labels: ready-for-merge

#17972 [WFLY-19404][WFLY-19399] Merge EE11 into main
  boms/preview-ee/pom.xml
Labels: deps-ok

#17959 [WFLY-19420] Move the com.fasterxml.jackson.dataformat.jackson-datafo…
  boms/common-ee/pom.xml
  boms/common-expansion/pom.xml
  ee-build/src/verifier/verifications.xml
  ee-dist/src/verifier/verifications.xml
  ee-feature-pack/galleon-shared/pom.xml
  ee-feature-pack/galleon-shared/src/main/resources/modules/system/layers/base/com/fasterxml/jackson/dataformat/jackson-dataformat-yaml/main/module.xml
  galleon-pack/galleon-shared/pom.xml
  testsuite/shared/src/main/java/org/jboss/as/test/shared/LayersTestBase.java
Labels: deps-ok

#17974 [WFLY-19451] Update resteasy-spring to 3.1.3.Final
  pom.xml
Labels: deps-ok

#17980 [WFLY-19458] Upgrade SmallRye Config to 3.8.3
  pom.xml
Labels: deps-ok

#17979 [WFLY-19455] Upgrade reactive messaging
  pom.xml
Labels: deps-ok

#17991 [WFLY-19376] Upgrade Wildscribe to 3.1.0.Final.
  docs/pom.xml
  pom.xml
Labels: ready-for-merge, deps-ok
