Repository wildfly/wildfly, pull requests merged in 2024-08, with the labels that each got.

#18088 [WFLY-19597] Bump version.org.wildfly.galleon-plugins from 7.1.1.Fina…
  pom.xml
Labels: deps-ok

#18040 [WFLY-19530] Add jakarta.activation:jakarta.activation-api to the tes…
  testsuite/integration/microprofile/pom.xml
Labels: deps-ok

#18089 [WFLY-19599]:Upgrade OpenSAML to 4.3.0
  pom.xml
Labels: deps-ok

#18092 [WFLY-19602] Exclude the transitive dependencies from org.jboss.naray…
  testsuite/integration/microprofile-tck/lra/pom.xml
Labels: deps-ok

#18093 [WFLY-19603] Upgrade Infinispan to 14.0.30.Final
  pom.xml
Labels: deps-ok

#17878 [WFLY-19324] Migrate OpenTelemetry extension to new wildfly-subsystem approach
  galleon-pack/galleon-shared/src/main/resources/modules/system/layers/base/org/wildfly/extension/microprofile/telemetry/main/module.xml
  galleon-pack/galleon-shared/src/main/resources/modules/system/layers/base/org/wildfly/extension/opentelemetry-api/main/module.xml
  galleon-pack/galleon-shared/src/main/resources/modules/system/layers/base/org/wildfly/extension/opentelemetry/main/module.xml
  legacy/opentracing-extension/pom.xml
  microprofile/telemetry-smallrye/extension/pom.xml
  microprofile/telemetry-smallrye/extension/src/main/java/org/wildfly/extension/microprofile/telemetry/MicroProfileTelemetryDependencyProcessor.java
  microprofile/telemetry-smallrye/extension/src/main/java/org/wildfly/extension/microprofile/telemetry/MicroProfileTelemetryDeploymentProcessor.java
  microprofile/telemetry-smallrye/extension/src/main/java/org/wildfly/extension/microprofile/telemetry/MicroProfileTelemetrySubsystemAdd.java
  observability/opentelemetry-api/pom.xml
  observability/opentelemetry-api/src/main/java/org/wildfly/extension/opentelemetry/api/OpenTelemetryCdiExtension.java
  observability/opentelemetry-api/src/main/java/org/wildfly/extension/opentelemetry/api/WildFlyOpenTelemetryConfig.java
  observability/opentelemetry/pom.xml
  observability/opentelemetry/src/main/java/org/wildfly/extension/opentelemetry/OpenTelemetryConfigurationConstants.java
  observability/opentelemetry/src/main/java/org/wildfly/extension/opentelemetry/OpenTelemetryDependencyProcessor.java
  observability/opentelemetry/src/main/java/org/wildfly/extension/opentelemetry/OpenTelemetryDeploymentProcessor.java
  observability/opentelemetry/src/main/java/org/wildfly/extension/opentelemetry/OpenTelemetryExtensionTransformerRegistration.java
  observability/opentelemetry/src/main/java/org/wildfly/extension/opentelemetry/OpenTelemetrySubsystemAdd.java
  observability/opentelemetry/src/main/java/org/wildfly/extension/opentelemetry/OpenTelemetrySubsystemExtension.java
  observability/opentelemetry/src/main/java/org/wildfly/extension/opentelemetry/OpenTelemetrySubsystemRegistrar.java
  observability/opentelemetry/src/main/java/org/wildfly/extension/opentelemetry/OpenTelemetrySubsystemSchema.java
  observability/opentelemetry/src/test/java/org/wildfly/extension/opentelemetry/SubsystemParsingTestCase.java
  observability/opentelemetry/src/test/java/org/wildfly/extension/opentelemetry/SubsystemTransformersTestCase.java
  pom.xml
  testsuite/integration/microprofile/pom.xml
  testsuite/integration/microprofile/src/test/java/org/wildfly/test/integration/microprofile/faulttolerance/micrometer/FaultToleranceMicrometerIntegrationTestCase.java
  testsuite/integration/microprofile/src/test/java/org/wildfly/test/integration/observability/container/BaseContainer.java
  testsuite/integration/microprofile/src/test/java/org/wildfly/test/integration/observability/container/JaegerContainer.java
  testsuite/integration/microprofile/src/test/java/org/wildfly/test/integration/observability/container/OpenTelemetryCollectorContainer.java
  testsuite/integration/microprofile/src/test/java/org/wildfly/test/integration/observability/micrometer/BasicMicrometerTestCase.java
  testsuite/integration/microprofile/src/test/java/org/wildfly/test/integration/observability/micrometer/MetricResource.java
  testsuite/integration/microprofile/src/test/java/org/wildfly/test/integration/observability/micrometer/MicrometerOtelIntegrationTestCase.java
  testsuite/integration/microprofile/src/test/java/org/wildfly/test/integration/observability/micrometer/MicrometerSetupTask.java
  testsuite/integration/microprofile/src/test/java/org/wildfly/test/integration/observability/opentelemetry/BaseOpenTelemetryTest.java
  testsuite/integration/microprofile/src/test/java/org/wildfly/test/integration/observability/opentelemetry/BasicOpenTelemetryTestCase.java
  testsuite/integration/microprofile/src/test/java/org/wildfly/test/integration/observability/opentelemetry/ContextPropagationTestCase.java
  testsuite/integration/microprofile/src/test/java/org/wildfly/test/integration/observability/opentelemetry/OpenTelemetryIntegrationTestCase.java
  testsuite/integration/microprofile/src/test/java/org/wildfly/test/integration/observability/opentelemetry/application/JaxRsActivator.java
  testsuite/integration/microprofile/src/test/java/org/wildfly/test/integration/observability/opentelemetry/application/OtelService1.java
  testsuite/integration/microprofile/src/test/java/org/wildfly/test/integration/observability/opentelemetry/application/OtelService2.java
  testsuite/integration/microprofile/src/test/java/org/wildfly/test/integration/observability/setuptask/OpenTelemetrySetupTask.java
  testsuite/integration/microprofile/src/test/resources/org/wildfly/test/integration/observability/container/otel-collector-config.yaml
Labels: deps-ok

#18100 [WFLY-19607] Upgrade to Hibernate ORM 6.4.10.Final release
  pom.xml
Labels: deps-ok

#18101 WFLY-19608 Upgrade SmallRye Fault Tolerance to 6.4.0
  pom.xml
Labels: deps-ok

#18107 [WFLY-19612]:Upgrade jbossws-cxf to 7.2.0.Final
  pom.xml
Labels: deps-ok

#18105 [WFLY-19576]:Upgrade CXF to 4.0.5
  pom.xml
Labels: 33.x

#18111 [WFLY-19583] Deployment-related undertow metrics are not exported
  testsuite/integration/microprofile/src/test/java/org/wildfly/test/integration/observability/micrometer/MicrometerOtelIntegrationTestCase.java
Labels: 34.x

#18110 [WFLY-19583-33.x] Deployment-related undertow metrics are not exported
  observability/micrometer/src/main/java/org/wildfly/extension/micrometer/MicrometerDeploymentProcessor.java
  testsuite/integration/microprofile/src/test/java/org/wildfly/test/integration/observability/container/OpenTelemetryCollectorContainer.java
  testsuite/integration/microprofile/src/test/java/org/wildfly/test/integration/observability/container/PrometheusMetric.java
  testsuite/integration/microprofile/src/test/java/org/wildfly/test/integration/observability/micrometer/MicrometerOtelIntegrationTestCase.java
  testsuite/integration/microprofile/src/test/java/org/wildfly/test/integration/observability/setuptask/OpenTelemetrySetupTask.java
Labels: 33.x

#18106 [WFLY-19611]:Upgrade OpenSAML to 4.3.0
  pom.xml
Labels: 33.x

#18113 WFLY-19613 Immutability performance optimizations
  clustering/web/cache/src/main/java/org/wildfly/clustering/web/cache/session/attributes/coarse/CoarseSessionAttributes.java
  clustering/web/cache/src/main/java/org/wildfly/clustering/web/cache/session/attributes/fine/FineSessionAttributes.java
  ejb3/src/main/java/org/jboss/as/ejb3/component/stateful/StatefulSessionBeanImmutability.java
Labels: 33.x

#18120 [WFLY-19577] Remove usage of AbstractAddStepHandler.attributes from u…
  undertow/src/main/java/org/wildfly/extension/undertow/ServerAdd.java
Labels: 33.x

#18117 [WFLY-19625] Upgrade JSTL Implementation to 3.0.1-jbossorg-1
  pom.xml
Labels: deps-ok

#18134 [WFLY-19652] Upgrade jboss-ejb-client to 5.0.7.Final
  pom.xml
Labels: deps-ok

#18109 [[WFLY-19619] Fix MP Reactive Messaging test failures on JDK23
  pom.xml
  testsuite/pom.xml
Labels: deps-ok

#18141 [WFLY-19658] Turn on compiler annotation processing on SE 23+
  pom.xml
Labels: deps-ok

#18137 [WFLY-19600] [WFLY-19654] RESTEasy Upgrades
  boms/preview-ee/pom.xml
  pom.xml
Labels: deps-ok

#18138 [WFLY-19600] [WFLY-19654] RESTEasy Upgrades
  boms/preview-ee/pom.xml
  pom.xml
Labels: 33.x

#18132 [WFLY-19610] @PostConstruct on Servlet may be called twice
  testsuite/integration/basic/src/test/java/org/wildfly/test/integration/web/postcontstruct/DuplicatePostConstructTestCase.java
  testsuite/integration/basic/src/test/java/org/wildfly/test/integration/web/postcontstruct/beanjar/SimpleBean.java
  testsuite/integration/basic/src/test/java/org/wildfly/test/integration/web/postcontstruct/beanjar/SimpleServlet.java
  testsuite/integration/basic/src/test/java/org/wildfly/test/integration/web/postcontstruct/beanjar/WrapperServlet.java
  testsuite/integration/basic/src/test/java/org/wildfly/test/integration/web/postcontstruct/beanjar/web-fragment.xml
  weld/subsystem/src/main/java/org/jboss/as/weld/deployment/WeldClassIntrospector.java
Labels: 34.x

#18126 [WFLY-19643] Upgrade Apache James Mime4j from 0.8.10 to 0.8.11
  pom.xml
Labels: deps-ok

#18115 [WFLY-19621] Upgrade the keycloak-services and keycloak test dependencies to the latest version
  pom.xml
Labels: deps-ok

#18139 [WFLY-19652] Upgrade jboss-ejb-client to 5.0.7.Final
  pom.xml
Labels: 33.x

#18136 [WFLY-19655] Upgrade JBeret to 3.0.0.Final
  ee-feature-pack/galleon-shared/src/main/resources/modules/system/layers/base/org/jberet/jberet-core/main/module.xml
  pom.xml
Labels: deps-changed

#18146 [WFLY-19610-33x] @PostConstruct on Servlet may be called twice
  testsuite/integration/basic/src/test/java/org/wildfly/test/integration/web/postcontstruct/DuplicatePostConstructTestCase.java
  testsuite/integration/basic/src/test/java/org/wildfly/test/integration/web/postcontstruct/beanjar/SimpleBean.java
  testsuite/integration/basic/src/test/java/org/wildfly/test/integration/web/postcontstruct/beanjar/SimpleServlet.java
  testsuite/integration/basic/src/test/java/org/wildfly/test/integration/web/postcontstruct/beanjar/WrapperServlet.java
  testsuite/integration/basic/src/test/java/org/wildfly/test/integration/web/postcontstruct/beanjar/web-fragment.xml
  weld/subsystem/src/main/java/org/jboss/as/weld/deployment/WeldClassIntrospector.java
Labels: 33.x

#18145 [WFLY-19663] Upgrade WildFly Core to 26.0.0.Beta2
  pom.xml
Labels: deps-ok

#16775 [WFLY-17871] added test-case for managed executor service defined via…
  testsuite/integration/basic/pom.xml
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/ee/concurrent/ManagedExecutorServiceAnnotationBean.java
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/ee/concurrent/ManagedExecutorServiceAnnotationTestCase.java
Labels: deps-ok

#18149 [WFLY-19671] Remove 'galleon content only' dependencies from the list…
  ee-feature-pack/galleon-feature-pack/pom.xml
Labels: deps-ok

#18150 [WFLY-19673] Upgrade to SmallRye Reactive Messaging 4.24.0
  pom.xml
Labels: deps-ok

#18124 [WFLY-19641] Upgrade joda-time from 2.12.6 to 2.12.7
  pom.xml
Labels: deps-ok

#18156 [WFLY-19684] Upgrade WildFly Core to 26.0.0.Beta3
  pom.xml
Labels: deps-ok

#18157 [WFLY-19686] Upgrade ironjacamar to 3.0.10.Final
  pom.xml
Labels: deps-ok

#18123 [WFLY-19640] Upgrade the Jakarta XML Binding Implementation to 4.0.5
  pom.xml
Labels: deps-ok
