Repository wildfly/wildfly, pull requests merged in 2025-06, with the labels that each got.

#18987 [WFLY-20698] Upgrading WildFly HTTP Client to 2.1.1.Final
  pom.xml
Labels: deps-ok

#18977 WFLY-20679 - Update Micrometer to 1.15.0
  boms/common-expansion/pom.xml
  galleon-pack/galleon-shared/pom.xml
  galleon-pack/galleon-shared/src/main/resources/modules/system/layers/base/io/prometheus/main/module.xml
  pom.xml
Labels: deps-changed

#18973 [WFLY-20676] Upgrade HAL to 3.7.12.Final
  pom.xml
Labels: deps-ok

#18963 [WFLY-20661] Upgrade CXF from 4.0.6 to 4.0.8 and CXF XJC Utils from 4.0.1 to 4.1.0
  pom.xml
Labels: deps-ok

#18988 [WFLY-20699] Before adding to the private credentials check the ticket is not null.
  connector/src/main/java/org/jboss/as/connector/security/ElytronSubjectFactory.java
Labels: ready-for-merge

#19015 [WFLY-20728] Upgrade Hibernate Validator to 9.0.1.Final in WildFly preview
  boms/preview-ee/pom.xml
Labels: deps-ok

#19014 [WFLY-20726] Upgrade the MVC Krazo integration to 2.0.0.Final
  pom.xml
Labels: deps-ok

#19024 [WFLY-20742] Upgrade the OWASP dependency check plugin to 12.1.3
  pom.xml
Labels: deps-ok

#19019 [WFLY-20732] Upgrade WildFly Preview to Hibernate ORM 7.0.2.Final
  boms/preview-ee/pom.xml
Labels: deps-ok

#19045 [WFLY-20759] Upgrade Hibernate Search to 7.2.4.Final
  pom.xml
Labels: deps-ok
