Repository wildfly/wildfly, pull requests merged in 2025-03, with the labels that each got.

#18796 [WFLY-20449] Upgrade WildFly Core to 28.0.0.Beta4
  pom.xml
Labels: deps-ok

#18798 [WFLY-20450] Upgrade the OWASP dependency-check plugin to 12.1.0
  pom.xml
Labels: Blocker, deps-ok

#18795 WFLY-20444 Upgrade JGroups AWS to 3.0.1.Final and software.amazon.awssdk to 2.30.32
  boms/common-ee/pom.xml
  docs/src/main/asciidoc/_high-availability/jgroups/AWS-Discovery.adoc
  ee-feature-pack/galleon-shared/pom.xml
  ee-feature-pack/galleon-shared/src/main/resources/modules/system/layers/base/software/amazon/awssdk/s3/main/module.xml
  pom.xml
Labels: deps-changed

#18816 [WFLY-19384] Flaky LRA TckParticipantTests tests
  pom.xml
Labels: deps-changed

#18806 WFLY-20457 Upgrade MicroProfile Fault Tolerance to 4.1.2 (TCK fix release)
  pom.xml
Labels: deps-ok

#18805 WFLY-20456 Upgrade SmallRye Fault Tolerance from 6.8.0 to 6.9.0
  pom.xml
Labels: deps-ok

#18800 [WFLY-20453] [WFLY-20454] Upgrade RESTEasy to 6.2.12.Final in WildFly and 7.0.0.Beta1 in WildFly Preview
  boms/preview-ee/pom.xml
  pom.xml
Labels: deps-ok

#18815 [WFLY-20470][WFLY-20472] WildFly Preview: Trivial micro updates to Ja…
  boms/preview-ee/pom.xml
Labels: EE11

#18813 [WFLY-20467] [JBEAP-29472] Add transitives to Tools BOM, required for…
  boms/user/tools/pom.xml
Labels: deps-ok

#18826 [WFLY-20483] Upgrade HAL to 3.7.9.Final
  pom.xml
Labels: deps-ok

#18774 [WFLY-19722] Add logging to the Undertow track security domain mapped
  undertow/src/main/java/org/wildfly/extension/undertow/ApplicationSecurityDomainDefinition.java
  undertow/src/main/java/org/wildfly/extension/undertow/deployment/UndertowDeploymentProcessor.java
Labels: ready-for-merge, 36.x

#18814 [WFLY-20471][WFLY-20473] WildFly Preview: Upgrade Faces API and Mojarra
  boms/preview-ee/pom.xml
Labels: ready-for-merge, Blocker, EE11, 36.x

#17857 [WFLY-18582] Add prometheus endpoint to micrometer extension
  boms/common-expansion/pom.xml
  docs/src/main/asciidoc/_admin-guide/subsystem-configuration/Micrometer.adoc
  galleon-pack/galleon-shared/pom.xml
  galleon-pack/galleon-shared/src/main/resources/layers/standalone/micrometer/layer-spec.xml
  galleon-pack/galleon-shared/src/main/resources/modules/system/layers/base/io/micrometer/main/module.xml
  galleon-pack/galleon-shared/src/main/resources/modules/system/layers/base/io/prometheus/main/module.xml
  galleon-pack/galleon-shared/src/main/resources/modules/system/layers/base/org/wildfly/extension/micrometer/main/module.xml
  observability/micrometer/pom.xml
  observability/micrometer/src/main/java/org/wildfly/extension/micrometer/MicrometerConfigurationConstants.java
  observability/micrometer/src/main/java/org/wildfly/extension/micrometer/MicrometerDeploymentProcessor.java
  observability/micrometer/src/main/java/org/wildfly/extension/micrometer/MicrometerExtensionLogger.java
  observability/micrometer/src/main/java/org/wildfly/extension/micrometer/MicrometerExtensionTransformerRegistration.java
  observability/micrometer/src/main/java/org/wildfly/extension/micrometer/MicrometerService.java
  observability/micrometer/src/main/java/org/wildfly/extension/micrometer/MicrometerSubsystemModel.java
  observability/micrometer/src/main/java/org/wildfly/extension/micrometer/MicrometerSubsystemRegistrar.java
  observability/micrometer/src/main/java/org/wildfly/extension/micrometer/MicrometerSubsystemSchema.java
  observability/micrometer/src/main/java/org/wildfly/extension/micrometer/WildFlyMicrometerConfig.java
  observability/micrometer/src/main/java/org/wildfly/extension/micrometer/otlp/OtlpRegistryDefinitionRegistrar.java
  observability/micrometer/src/main/java/org/wildfly/extension/micrometer/otlp/WildFlyOtlpRegistry.java
  observability/micrometer/src/main/java/org/wildfly/extension/micrometer/prometheus/PrometheusRegistryDefinitionRegistrar.java
  observability/micrometer/src/main/java/org/wildfly/extension/micrometer/prometheus/WildFlyPrometheusRegistry.java
  observability/micrometer/src/main/java/org/wildfly/extension/micrometer/registry/WildFlyCompositeRegistry.java
  observability/micrometer/src/main/java/org/wildfly/extension/micrometer/registry/WildFlyOtlpRegistry.java
  observability/micrometer/src/main/java/org/wildfly/extension/micrometer/registry/WildFlyRegistry.java
  observability/micrometer/src/main/resources/org/wildfly/extension/micrometer/LocalDescriptions.properties
  observability/micrometer/src/main/resources/schema/wildfly-micrometer_2_0.xsd
  observability/micrometer/src/main/resources/schema/wildfly-micrometer_community_2_0.xsd
  observability/micrometer/src/test/java/org/wildfly/extension/micrometer/SubsystemParsingTestCase.java
  observability/micrometer/src/test/java/org/wildfly/extension/micrometer/SubsystemTransformersTestCase.java
  observability/micrometer/src/test/resources/org/wildfly/extension/micrometer/micrometer-1.0.xml
  observability/micrometer/src/test/resources/org/wildfly/extension/micrometer/micrometer-1.1.xml
  observability/micrometer/src/test/resources/org/wildfly/extension/micrometer/micrometer-community-2.0.xml
  observability/micrometer/src/test/resources/org/wildfly/extension/micrometer/micrometer-reject.xml
  observability/micrometer/src/test/resources/org/wildfly/extension/micrometer/transform-1.1.xml
  observability/micrometer/src/test/resources/org/wildfly/extension/micrometer/transform-1_0_0.xml
  pom.xml
  testsuite/integration/expansion/src/test/java/org/wildfly/test/integration/observability/JaxRsActivator.java
  testsuite/integration/expansion/src/test/java/org/wildfly/test/integration/observability/micrometer/BasicMicrometerTestCase.java
  testsuite/integration/expansion/src/test/java/org/wildfly/test/integration/observability/micrometer/MicrometerOtelIntegrationTestCase.java
  testsuite/integration/expansion/src/test/java/org/wildfly/test/integration/observability/micrometer/MicrometerPrometheusTestCase.java
  testsuite/integration/expansion/src/test/java/org/wildfly/test/integration/observability/micrometer/MicrometerResource.java
  testsuite/integration/expansion/src/test/java/org/wildfly/test/integration/observability/micrometer/multiple/application/DuplicateMetricResource2.java
  testsuite/integration/expansion/src/test/java/org/wildfly/test/integration/observability/setuptask/PrometheusSetupTask.java
  testsuite/shared/src/main/java/org/jboss/as/test/shared/LayersTestBase.java
  testsuite/shared/src/main/java/org/jboss/as/test/shared/observability/setuptasks/AbstractSetupTask.java
  testsuite/shared/src/main/java/org/jboss/as/test/shared/observability/setuptasks/MicrometerSetupTask.java
Labels: ready-for-merge, Feature, deps-changed, 36.x

#18819 [WFLY-20475] JCA: workmanager elytron-enabled attribute should be wri…
  connector/src/main/java/org/jboss/as/connector/subsystems/jca/JcaWorkManagerDefinition.java
Labels: 36.x

#18832 [WFLY-20496] Upgrade to Hibernate Search 7.2.3.Final
  pom.xml
Labels: deps-ok

#18829 [WFLY-20494] Upgrade WildFly Core to 28.0.0.Beta5
  pom.xml
  testsuite/integration/manualmode/src/test/java/org/jboss/as/test/manualmode/ejb/client/outbound/connection/security/ElytronRemoteOutboundConnectionTestCase.java
  testsuite/integration/manualmode/src/test/java/org/jboss/as/test/manualmode/ejb/ssl/SSLEJBRemoteClientTestCase.java
  testsuite/integration/manualmode/src/test/java/org/jboss/as/test/manualmode/ejb/ssl/SSLEJBRemoteRemotingClientTestCase.java
  testsuite/integration/manualmode/src/test/java/org/jboss/as/test/manualmode/ejb/ssl/SSLRealmSetupTool.java
  testsuite/integration/manualmode/src/test/java/org/jboss/as/test/manualmode/ejb/ssl/beans/StatelessBean.java
Labels: deps-ok

#18797 [WFLY-13828] Add support for remote+tls protocol configuration
  testsuite/integration/manualmode/src/test/java/org/jboss/as/test/manualmode/ejb/client/outbound/connection/security/ElytronRemoteOutboundConnectionTestCase.java
  testsuite/integration/manualmode/src/test/java/org/jboss/as/test/manualmode/ejb/ssl/SSLEJBRemoteClientTestCase.java
  testsuite/integration/manualmode/src/test/java/org/jboss/as/test/manualmode/ejb/ssl/SSLEJBRemoteRemotingClientTestCase.java
  testsuite/integration/manualmode/src/test/java/org/jboss/as/test/manualmode/ejb/ssl/SSLRealmSetupTool.java
  testsuite/integration/manualmode/src/test/java/org/jboss/as/test/manualmode/ejb/ssl/beans/StatelessBean.java
Labels: core-upgrade-needed, Feature, missing-reqs, 36.x

#18792 [WFLY-20445] Upgrading WildFly HTTP Client to 2.1.0.Final
  ejb3/src/main/java/org/jboss/as/ejb3/remote/http/EJB3RemoteHTTPService.java
  pom.xml
Labels: ready-for-merge, deps-ok, 36.x

#18828 [WFLY-20490]: Upgrade Apache Artemis to 2.40.0.
  messaging-activemq/subsystem/src/test/java/org/wildfly/extension/messaging/activemq/AttributeDefaultsTest.java
  pom.xml
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/messaging/mgmt/PrintDataTestCase.java
Labels: ready-for-merge, deps-ok, 36.x

#18799 [WFLY-20392] Upgrade to Hibernate ORM 7.0.0.Beta5
  bean-validation/src/main/java/org/jboss/as/ee/beanvalidation/LazyValidatorFactory.java
  boms/preview-ee/pom.xml
  jpa/hibernate7/src/main/java/org/wildfly/persistence/jipijapa/hibernate7/VirtualFileSystemArchiveDescriptor.java
  jpa/subsystem/src/main/java/org/jboss/as/jpa/injectors/PersistenceUnitInjectionSource.java
  jpa/subsystem/src/main/java/org/jboss/as/jpa/messages/JpaLogger.java
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/jpa/hibernate/sessionfactorytest/persistence.xml
  weld/bean-validation/src/main/java/org/jboss/as/weld/CdiValidatorFactoryService.java
Labels: deps-ok, 36.x

#18836 Fix for WFLY-20501, Upgrade WildFly Glow to 1.4.0.Final
  pom.xml
Labels: deps-ok

#18839 WFLY-20466 Upgrade wildfly-clustering to 6.0.1.Final
  pom.xml
Labels: deps-ok

#18846 [WFLY-20514][WFLY-20516] Upgrade to unstable-api-annotation-utils 1.0…
  pom.xml
Labels: deps-ok
