Repository wildfly/wildfly, pull requests merged in 2025-04, with the labels that each got.

#18841 [WFLY-20505] Upgrade WildFly Core to 28.0.0.Beta6
  pom.xml
Labels: deps-ok

#18848 [WFLY-20521] Cannot use CDI with Jakarta Persistence + application defined datasources without explicitly disabling byte code enahacement
  jpa/subsystem/src/main/java/org/jboss/as/jpa/config/Configuration.java
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/jpa/hibernate/EmployeeWithLastName.java
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/jpa/hibernate/EmployeeWithLastNameNotEnhanced.java
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/jpa/hibernate/SFSBWithLastName.java
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/jpa/hibernate/classfiletransformertest/ClassFileTransformerTestCase.java
Labels: Blocker, 36.x

#18851 [WFLY-20526] Upgrade HAL to 3.7.10.Final
  pom.xml
Labels: deps-ok

#18696 [WFLY-20322] Add HtmlUnit based test for the welcome page
  boms/standard-test/pom.xml
  pom.xml
  testsuite/integration/smoke/pom.xml
  testsuite/integration/smoke/src/test/java/org/jboss/as/test/smoke/welcome/WelcomePageTestCase.java
Labels: deps-ok

#18837 WFLY-20482 - Improve context name conflict handling with Metrics and Micrometer
  metrics/src/main/java/org/wildfly/extension/metrics/MetricsContextService.java
  metrics/src/main/java/org/wildfly/extension/metrics/MetricsSubsystemAdd.java
  observability/micrometer/src/main/java/org/wildfly/extension/micrometer/prometheus/PrometheusRegistryDefinitionRegistrar.java
  testsuite/integration/expansion/src/test/java/org/wildfly/test/integration/observability/micrometer/ConflictingPrometheusContextTestCase.java
Labels: Blocker, 36.x

#18855 Fix for WFLY-20529, Upgrade to WildFly Glow 1.4.1.Final
  pom.xml
Labels: deps-ok

#18856 WFLY-20530 Upgrade Weld 6 to 6.0.2.Final
  boms/preview-ee/pom.xml
Labels: deps-ok

#18852 [WFLY-20510] Remove the jboss.org link from the welcome page
  ee-feature-pack/galleon-shared/src/main/resources/content/welcome-content/index.html
  testsuite/integration/elytron/src/test/java/org/wildfly/test/integration/elytron/web/ListenerTestCase.java
Labels: 36.x

#18869 [WFLY-20545] At Server.lookupSecurePort, prevent the NPE when unboxin…
  undertow/src/main/java/org/wildfly/extension/undertow/Server.java
Labels: 36.x

#18870 [WFLY-20546] At ListenerService.start and stop, make sure the port is op…
  undertow/src/main/java/org/wildfly/extension/undertow/ListenerService.java
Labels: 36.x

#18864 [WFLY-20542] EJB: Add SocketPermission to DatabaseTimerServiceMultiNo…
  testsuite/integration/multinode/src/test/java/org/jboss/as/test/multinode/ejb/timer/database/DatabaseTimerServiceMultiNodeExecutionDisabledTestCase.java
Labels: 36.x

#18867 [WFLY-20544] Use java.io.tmpdir to create the FilePermission
  testsuite/integration/microprofile-tck/jwt/src/test/java/org/wildfly/extension/microprofile/jwt/test/DeploymentProcessor.java
  testsuite/integration/pom.xml
Labels: deps-ok, 36.x

#18872 [WFLY-20550] Block additional classes identified by security research…
  ejb3/src/main/java/org/jboss/as/ejb3/subsystem/FilterSpecClassResolverFilter.java
Labels: 36.x

#18868 [WFLY-20533] Do not set the -Djava.security.manager=allow by default. Only add the property if -secmgr is passed.
  ee-feature-pack/galleon-shared/src/main/resources/content/bin/appclient.bat
  ee-feature-pack/galleon-shared/src/main/resources/content/bin/appclient.sh
  naming/pom.xml
  pom.xml
  testsuite/pom.xml
  testsuite/scripts/src/test/java/org/wildfly/test/scripts/ScriptProcess.java
Labels: deps-ok, 36.x

#18883 WFLY-20559 Concurrent build is broken because modules do not depend on feature-packs they provision that are built in other modules
  testsuite/integration/smoke/pom.xml
  testsuite/pom.xml
Labels: deps-ok

#18888 WFLY-20334 Don't include the jipijapa-hibernate7 module if -Dno.preview.build=true
  jpa/pom.xml
Labels: deps-ok

#18874 [WFLY-20552] Upgrade to Hibernate ORM 6.6.13.Final
  pom.xml
Labels: deps-ok, 37.x

#18891 [WFLY-20564] Deploying postgresql-42.7.5.jar causes NPE when upgrading from wildfly 35->36
  jpa/subsystem/src/main/java/org/jboss/as/jpa/processor/PersistenceUnitParseProcessor.java
  testsuite/integration/smoke/src/test/java/org/jboss/as/test/smoke/mgmt/datasource/AddDataSourceOperationsUnitTestCase.java
  testsuite/integration/smoke/src/test/java/org/jboss/as/test/smoke/mgmt/datasource/TestDriver.java
Labels: Blocker, 36.x

#18896 [WFLY-20570][WFLY-20571] Jakarta MVC is not available to ear libraries
  pom.xml
  testsuite/integration/basic/src/test/java/org/wildfly/test/integration/mvc/MVCTestUtil.java
  testsuite/integration/basic/src/test/java/org/wildfly/test/integration/mvc/ear/MVCEarTestCase.java
  testsuite/integration/basic/src/test/java/org/wildfly/test/integration/mvc/ear/NonMVCResource.java
  testsuite/integration/basic/src/test/java/org/wildfly/test/integration/mvc/ear/SharedMVCController.java
  testsuite/integration/basic/src/test/java/org/wildfly/test/integration/mvc/ear/TestApplication.java
  testsuite/integration/basic/src/test/java/org/wildfly/test/integration/mvc/ear/UnsharedMVCController.java
  testsuite/integration/basic/src/test/java/org/wildfly/test/integration/mvc/ear/view.jsp
  testsuite/integration/basic/src/test/java/org/wildfly/test/integration/mvc/viewengine/ViewEngineTestCase.java
Labels: deps-ok

#18895 [WFLY-20573] Exclude dropwizard metrics
  boms/common-ee/pom.xml
Labels: deps-ok

#18899 WFLY-20584 Upgrade SmallRye Fault Tolerance from 6.9.0 to 6.9.1
  pom.xml
Labels: deps-ok

#18908 [WFLY-20593] Remove no longer used verifier.product.release.version property
  pom.xml
Labels: deps-ok

#18906 [36.x] WFLY-20584 Upgrade SmallRye Fault Tolerance from 6.9.0 to 6.9.1
  pom.xml
Labels: 36.x
