Repository wildfly/wildfly, pull requests merged in 2025-08, with the labels that each got.

#19098 [WFLY-20815]: Upgrading Apache Artemis to 2.42.0
  pom.xml
Labels: deps-ok

#19115 [37.x] [WFLY-20832] Bump org.eclipse.angus:angus-mail from 2.0.3 to 2.0.4
  pom.xml
Labels: Blocker, 37.x

#19140 [WFLY-20859] Upgrade Hibernate ORM to 6.6.26
  pom.xml
Labels: 37.x

#19131 [37.x][WFLY-20848] Upgrade wildfly-bom-builder-plugin to 2.0.9; use its new…
  boms/user/client/ejb-client/pom.xml
  boms/user/client/jaxws-client/pom.xml
  boms/user/client/jms-client/pom.xml
  boms/user/pom.xml
  boms/user/server/ee/preview/pom.xml
  boms/user/server/ee/preview/with-tools/pom.xml
  boms/user/server/ee/standard/pom.xml
  boms/user/server/ee/standard/with-tools/pom.xml
  boms/user/server/expansion/preview/pom.xml
  boms/user/server/expansion/preview/with-tools/pom.xml
  boms/user/server/expansion/standard/pom.xml
  boms/user/server/expansion/standard/with-tools/pom.xml
  pom.xml
Labels: 37.x

#19126 [37.x][WFLY-20846] Upgrade Netty to 4.1.124.Final
  pom.xml
Labels: Critical, 37.x
