Repository wildfly/wildfly, pull requests merged in 2025-01, with the labels that each got.

#18600 WFLY-20223 Fix mocking in Mockito 5.14.2 on JDK24.
  clustering/pom.xml
  ejb3/pom.xml
  elytron-oidc-client/pom.xml
  messaging-activemq/injection/pom.xml
  messaging-activemq/subsystem/pom.xml
  mod_cluster/undertow/pom.xml
  undertow/pom.xml
  web-common/pom.xml
  webservices/server-integration/pom.xml
Labels: deps-ok

#18589 [WFLY-20106] For any testsuite/integration/* modules always include a…
  testsuite/pom.xml
Labels: deps-ok

#18602 [WFLY-20222] Have testsuite depend on test boms to ensure they are built
  pom.xml
  testsuite/build-demander-base/pom.xml
  testsuite/build-demander-expansion/pom.xml
  testsuite/build-demander-preview/pom.xml
Labels: deps-ok

#18606 [WFLY-20228] Upgrade the WildFly Arquillian to 5.1.0.Beta8.
  pom.xml
Labels: deps-ok, 35.x

#18609 [WFLY-20225] & [WFLY-20231] Upgrade the jboss-parent POM from 39 to 47
  messaging-activemq/injection/src/main/java/org/wildfly/extension/messaging/activemq/injection/_private/MessagingLogger.java
  messaging-activemq/injection/src/main/java/org/wildfly/extension/messaging/activemq/injection/deployment/AbstractJMSContext.java
  messaging-activemq/injection/src/main/java/org/wildfly/extension/messaging/activemq/injection/deployment/CDIDeploymentProcessor.java
  messaging-activemq/injection/src/main/java/org/wildfly/extension/messaging/activemq/injection/deployment/DefaultJMSConnectionFactoryBinding.java
  messaging-activemq/injection/src/main/java/org/wildfly/extension/messaging/activemq/injection/deployment/InjectedJMSContext.java
  messaging-activemq/injection/src/main/java/org/wildfly/extension/messaging/activemq/injection/deployment/JMSCDIExtension.java
  messaging-activemq/injection/src/main/java/org/wildfly/extension/messaging/activemq/injection/deployment/JMSContextWrapper.java
  messaging-activemq/injection/src/main/java/org/wildfly/extension/messaging/activemq/injection/deployment/JMSInfo.java
  messaging-activemq/injection/src/main/java/org/wildfly/extension/messaging/activemq/injection/deployment/RequestedJMSContext.java
  messaging-activemq/injection/src/main/java/org/wildfly/extension/messaging/activemq/injection/deployment/TransactedJMSContext.java
  messaging-activemq/injection/src/test/java/org/wildfly/extension/messaging/activemq/injection/deployment/AbstractJMSContextTestCase.java
  messaging-activemq/subsystem/src/main/java/org/wildfly/extension/messaging/activemq/MessagingSubsystemAdd.java
  messaging-activemq/subsystem/src/main/java/org/wildfly/extension/messaging/activemq/deployment/DefaultJMSConnectionFactoryBindingProcessor.java
  messaging-activemq/subsystem/src/main/java/org/wildfly/extension/messaging/activemq/deployment/DefaultJMSConnectionFactoryResourceReferenceProcessor.java
  pom.xml
  testsuite/galleon/update/pom.xml
Labels: deps-ok

#18611 [WFLY-20234] Suppress CVE-2024-52046 as mina-core is a test dependency only.
  sca-overrides/owasp-suppressions.xml
Labels: 35.x

#18612 [WFLY-20229] Upgrade SR OpenTelemetry to 2.9.2
  pom.xml
Labels: deps-ok

#18621 [WFLY-20085]:Upgrade CXF from 4.0.5 to 4.0.6;this includes CXF's depe…
  pom.xml
Labels: deps-ok

#18625 [WFLY-20242] Don't disable running execute-commands for all skipTests…
  testsuite/integration/elytron/pom.xml
Labels: deps-ok

#18618 WFLY-20238 Upgrade SmallRye Fault Tolerance from 6.7.1 to 6.7.2
  pom.xml
Labels: deps-ok

#18630 WFLY-19956 Support @DockerRequired skipping on Windows for the whole …
  testsuite/integration/microprofile/pom.xml
  testsuite/pom.xml
Labels: deps-ok

#18629 [WFLY-20249] Upgrade Byteman to 4.0.24
  pom.xml
Labels: deps-ok

#18638 WFLY-20252 Upgrade SmallRye Fault Tolerance from 6.7.2 to 6.7.3
  pom.xml
Labels: deps-ok

#18659 [WFLY-20275] Remove XercesUsageTestCase
  testsuite/integration/basic/pom.xml
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/xerces/JSFManagedBean.java
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/xerces/XercesUsageServlet.java
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/xerces/dummy.xml
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/xerces/unit/XercesUsageTestCase.java
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/xerces/ws/XercesUsageWSEndpoint.java
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/xerces/ws/XercesUsageWebService.java
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/xerces/ws/unit/XercesUsageInWebServiceTestCase.java
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/xerces/xerces-webservice-web.xml
Labels: deps-ok

#18658 [WFLY-20274] Ensure ts.config-as.configure-wildfly runs after ts.copy…
  testsuite/integration/manualmode/pom.xml
Labels: deps-ok

#18241 [WFLY-19781] Upgrade to SmallRye Reactive Messaging 4.25.0
  pom.xml
Labels: deps-ok

#18663 Fix for WFLY-20286, Upgrade WildFly to Glow 1.3.0.Final
  pom.xml
Labels: deps-ok

#18668 [WFLY-20272][WFLY-20273] Adapt microprofile-certification.sh to reflect current status
  testsuite/integration/microprofile-tck/certification/microprofile-certification.sh
Labels: 35.x

#18671 [WFLY-20295] Ban the org.wildfly.security:wildfly-elytron dependency
  boms/common-ee/pom.xml
  pom.xml
Labels: deps-ok

#18687 WFLY-20276 Upgrade Weld to 5.1.5.Final
  pom.xml
Labels: deps-ok

#18683 [WFLY-20305] (WF 36) Upgrade HAL to 3.7.8.Final
  pom.xml
Labels: deps-ok

#18686 WFLY-20259, WFLY-20306 and WFLY-20309 - Upgrade RESTEasy MicroProfile and Wiremock. Allow testing of the MP REST Client with the security manger enabled
  boms/standard-test-expansion/pom.xml
  pom.xml
  testsuite/integration/microprofile-tck/rest-client/pom.xml
  testsuite/integration/microprofile-tck/rest-client/src/test/resources/arquillian-bootable.xml
  testsuite/integration/microprofile-tck/rest-client/src/test/resources/arquillian.xml
Labels: deps-ok, dependencies, java

#18662 [WFLY-20282] Do not attempt to install Policy into JDK via byteman configuration
  testsuite/integration/manualmode/pom.xml
  testsuite/integration/manualmode/src/test/java/org/jboss/as/test/manualmode/messaging/CoreBridgeCallTimeoutTestCase.java
  testsuite/integration/manualmode/src/test/java/org/jboss/as/test/manualmode/messaging/CriticalAnalyzerTestCase.java
  testsuite/integration/manualmode/src/test/resources/arquillian.xml
Labels: deps-ok

#18690 [WFLY-20297] Use the correct maven property when configuring the fat …
  testsuite/build-demander-base/pom.xml
Labels: deps-ok

#18047 [WFLY-19536] Add -Djdk.tracePinnedThreads=full to the args passed to …
  testsuite/pom.xml
Labels: deps-ok

#18693 [WFLY-20319] Upgrade WildFly Core to 28.0.0.Beta1
  pom.xml
Labels: deps-changed

#18702 [WFLY-20323] Upgrade openjdk-orb to 10.1.1.Final
  pom.xml
Labels: deps-ok

#18694 [WFLY-20278] Reactivate SingleSignOnUnitTestCase which has been disabled for 13 years
  testsuite/integration/clustering/src/test/java/org/jboss/as/test/clustering/cluster/sso/ElytronSSOServerSetupTask.java
  testsuite/integration/clustering/src/test/java/org/jboss/as/test/clustering/cluster/sso/HostSSOServerSetupTask.java
  testsuite/integration/clustering/src/test/java/org/jboss/as/test/clustering/cluster/sso/remote/AbstractRemoteSingleSignOnTestCase.java
  testsuite/integration/clustering/src/test/java/org/jboss/as/test/clustering/cluster/sso/remote/RemoteElytronSingleSignOnTestCase.java
  testsuite/integration/web/pom.xml
  testsuite/integration/web/src/test/java/org/jboss/as/test/integration/web/security/WebTestsSecurityDomainSetup.java
  testsuite/integration/web/src/test/java/org/jboss/as/test/integration/web/sso/SingleSignOnSetup.java
  testsuite/integration/web/src/test/java/org/jboss/as/test/integration/web/sso/SingleSignOnUnitTestCase.java
  testsuite/shared/src/main/java/org/jboss/as/test/integration/web/sso/EJBServlet.java
  testsuite/shared/src/main/java/org/jboss/as/test/integration/web/sso/NotAnEJBServlet.java
  testsuite/shared/src/main/java/org/jboss/as/test/integration/web/sso/SSOTestBase.java
  testsuite/shared/src/main/java/org/jboss/as/test/integration/web/sso/interfaces/ReturnData.java
  testsuite/shared/src/main/java/org/jboss/as/test/integration/web/sso/interfaces/StatelessSession.java
  testsuite/shared/src/main/java/org/jboss/as/test/integration/web/sso/interfaces/StatelessSessionBean.java
  testsuite/shared/src/main/java/org/jboss/as/test/integration/web/sso/interfaces/StatelessSessionHome.java
  testsuite/shared/src/main/java/org/jboss/as/test/integration/web/sso/interfaces/StatelessSessionLocal.java
  testsuite/shared/src/main/java/org/jboss/as/test/integration/web/sso/interfaces/StatelessSessionLocalHome.java
  testsuite/shared/src/main/java/org/wildfly/test/security/common/elytron/Path.java
  testsuite/shared/src/main/java/org/wildfly/test/undertow/common/SingleSignOnSetting.java
  testsuite/shared/src/main/java/org/wildfly/test/undertow/common/UndertowApplicationSecurityDomain.java
  testsuite/shared/src/main/resources/org/jboss/as/test/integration/web/sso/resources/application.xml
  testsuite/shared/src/main/resources/org/jboss/as/test/integration/web/sso/resources/ejb-jar.xml
  testsuite/shared/src/main/resources/org/jboss/as/test/integration/web/sso/resources/jboss-web.xml
  testsuite/shared/src/main/resources/org/jboss/as/test/integration/web/sso/resources/jboss.xml
  testsuite/shared/src/main/resources/org/jboss/as/test/integration/web/sso/resources/web-form-auth.xml
Labels: deps-ok

#18701 [WFLY-20290] Add missing dependency on java.xml in Artemis commons mo…
  ee-feature-pack/galleon-shared/src/main/resources/modules/system/layers/base/org/apache/activemq/artemis/commons/main/module.xml
Labels: ready-for-merge, 35.x

#18691 WFLY-20259, WFLY-20306 and WFLY-20309 - Upgrade RESTEasy MicroProfile and Wiremock. Allow testing of the MP REST Client with the security manger enabled
  boms/standard-test-expansion/pom.xml
  pom.xml
  testsuite/integration/microprofile-tck/rest-client/pom.xml
  testsuite/integration/microprofile-tck/rest-client/src/test/resources/arquillian-bootable.xml
  testsuite/integration/microprofile-tck/rest-client/src/test/resources/arquillian.xml
Labels: ready-for-merge, dependencies, java, 35.x

#18684 [WFLY-20307] (WF 35) Upgrade HAL to 3.7.8.Final
  pom.xml
Labels: ready-for-merge, 35.x

#18682 [WFLY-20303] Bump org.jboss.arquillian:arquillian-bom from 1.9.2.Final to 1.9.3.Final
  pom.xml
Labels: ready-for-merge, dependencies, java, 35.x

#18714 [WFLY-20275] Remove XercesUsageTestCase
  testsuite/integration/basic/pom.xml
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/xerces/JSFManagedBean.java
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/xerces/XercesUsageServlet.java
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/xerces/dummy.xml
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/xerces/unit/XercesUsageTestCase.java
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/xerces/ws/XercesUsageWSEndpoint.java
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/xerces/ws/XercesUsageWebService.java
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/xerces/ws/unit/XercesUsageInWebServiceTestCase.java
  testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/xerces/xerces-webservice-web.xml
Labels: 35.x

#18707 [WFLY-20323] Upgrade openjdk-orb to 10.1.1.Final
  pom.xml
Labels: Blocker, 35.x

#18637 [WFLY-20085]:Upgrade CXF from 4.0.5 to 4.0.6;this includes CXF's depe…
  pom.xml
Labels: 35.x

#18712 [WFLY-20329] Use correct key type to read bdmsByIdentifier
  weld/subsystem/src/main/java/org/jboss/as/weld/deployment/processors/WeldDeploymentProcessor.java
Labels: Blocker, 35.x

#18722 WFLY-20335 - Upgrade Mojarra to 4.0.9
  pom.xml
Labels: deps-ok

#18726 [WFLY-20343] Add missing configuration parameter for the bootable JAR…
  testsuite/integration/web/pom.xml
Labels: deps-ok

#18716 WFLY-20336 - Update io.grpc:grpc-api to 1.70.0
  pom.xml
Labels: deps-ok

#18718 [WFLY-20339] Suppress CVE-2024-4109 as triaged as not a security vulnerability
  sca-overrides/owasp-suppressions.xml
Labels: 35.x

#18725 [WFLY-20341] Upgrade Apache Mime4j from 0.8.11 to 0.8.12.
  pom.xml
Labels: dependencies, java, 35.x

#18735 [WFLY-20355] Upgrade WildFly Core to 27.0.1.Final
  pom.xml
Labels: 35.x
