Repository wildfly/wildfly, pull requests merged in 2025-09, with the labels that each got.

#19186 [WFLY-20902] Drop perfmark
  boms/common-expansion/pom.xml
  galleon-pack/galleon-shared/pom.xml
  galleon-pack/galleon-shared/src/main/resources/modules/system/layers/base/com/google/protobuf/main/module.xml
  pom.xml
Labels: deps-changed

#19189 WFLY-20922 Upgrade wildfly-channel-maven-plugin to 1.0.29
  pom.xml
Labels: deps-ok

#19170 WFLY-20855 Update to Narayana LRA 1.0.2.Final
  boms/common-expansion/pom.xml
  galleon-pack/galleon-shared/pom.xml
  galleon-pack/galleon-shared/src/main/resources/modules/system/layers/base/io/smallrye/stork/main/module.xml
  galleon-pack/galleon-shared/src/main/resources/modules/system/layers/base/org/jboss/narayana/lra/lra-participant/main/module.xml
  microprofile/lra/participant/pom.xml
  microprofile/lra/participant/src/main/java/org/wildfly/extension/microprofile/lra/participant/deployment/LRAParticipantDeploymentDependencyProcessor.java
  pom.xml
  testsuite/shared/src/main/java/org/jboss/as/test/shared/LayersTestBase.java
Labels: deps-changed

#19200 [WFLY-20939] Upgrade WildFly Preview to Hibernate ORM 7.1.1.Final + Hibernate Search 8.1.2.Final + Elasticsearch 9.1.3
  boms/preview-ee/pom.xml
Labels: deps-ok

#19201 [WFLY-20944] Upgrade WildFly Core to 30.0.0.Beta2
  pom.xml
Labels: deps-changed

#19221 [WFLY-20966] Work around WFLY-20965 to fix WildFly Preview bootable j…
  testsuite/preview/basic/pom.xml
Labels: hold

#19225 [WFLY-20975] Upgrade WildFly Core to 30.0.0.Beta3
  pom.xml
Labels: deps-ok
