Repository wildfly/wildfly, pull requests merged in 2025-10, with the labels that each got.

#19243 [WFLY-20998] Update the producers to only be added if there was not already a producer available provided by the application.
  docs/src/main/asciidoc/WildFly_and_WildFly_Preview.adoc
  docs/src/main/asciidoc/_developer-guide/Jakarta_Persistence_Reference_Guide.adoc
  jpa/persistence-cdi-extension/src/main/java/org/jboss/as/jpa/beanmanager/IntegratePersistenceAfterBeanDiscovery.java
  testsuite/preview/basic/src/test/java/org/wildfly/test/preview/persistence/cdi/IgnoreDefaultProducerTestCase.java
  testsuite/preview/basic/src/test/java/org/wildfly/test/preview/persistence/cdi/LegacyInjectionTestCase.java
  testsuite/preview/basic/src/test/java/org/wildfly/test/preview/persistence/cdi/PersistenceProducers.java
  testsuite/preview/basic/src/test/java/org/wildfly/test/preview/persistence/cdi/RequiredInjectionTestCase.java
  testsuite/preview/basic/src/test/resources/arquillian-bootable.xml
  testsuite/preview/basic/src/test/resources/arquillian.xml
  testsuite/preview/basic/src/test/resources/org/wildfly/test/preview/persistence/cdi/legacy-persistence.xml
  testsuite/preview/basic/src/test/resources/org/wildfly/test/preview/persistence/cdi/simple-persistence.xml
Labels: Blocker, 38.x

#19244 [WFLY-21002] Upgrade WildFly Core to 30.0.0.Beta4
  pom.xml
Labels: deps-ok

#19230 [WFLY-20986] [WFLY-20987] Upgrade RESTEasy to 6.2.14.Final and 7.0.0.Final in WildFly Preview
  boms/preview-ee/pom.xml
  pom.xml
Labels: deps-ok, 38.x

#19254 [WFLY-21010] Upgrade Hibernate ORM from 6.6.29 to 6.6.31
  pom.xml
Labels: deps-ok, 38.x
